### ISSUE TITLE
httpserver   如何  使用长连 接收文件 

### ISSUE THREAD

**Issue by xiaolong-bao** [sogou/workflow#1000]

**Comment by Barenboim** [comment]
你好。能不能把需求描述具体一些？我们目前的http server，是在收到完整request的时候，调用process函数的。你是不是需要每接收到一块数据，都能有回调操作？

**Comment by xiaolong-bao** [comment]
客户端想要传大文件(100M) 到服务端，需要使用长连接接收文件并保存，可能涉及断点续传。想要保持这个链接，并每次收到数据到回调处理。谢谢。

**Comment by Barenboim** [comment]
正常的断点续传都没有什么问题，连接的话，在一次完整交互，默认都是keep-alive的。
100M的文件最好是分片的上传，如果一次性POST一个100M的文件，server会一直接收到完100M，才调用process让用户处理。

**Comment by xiaolong-bao** [comment]
好的，感谢。
