### ISSUE TITLE
MySql API 能否接受xx.sql

### ISSUE THREAD

**Issue by DDGRCF** [sogou/workflow#1002]
如题

**Comment by Barenboim** [comment]
这啥？

**Comment by DDGRCF** [comment]
> 这啥？
task->get_req()->set_query("SHOW TABLES;");
这里面的字符串能否直接用.sql文件的形式

**Comment by holmes1412** [comment]
没有直接导入文件的接口，但你可以简单读出来处理下。.sql里包含了query语句和注释，其中query语句你读出来用现在的set_query()导入。

**Comment by DDGRCF** [comment]
> 没有直接导入文件的接口，但你可以简单读出来处理下。.sql里包含了query语句和注释，其中query语句你读出来用现在的set_query()导入。

好的
