### ISSUE TITLE
如何在析构函数中安全等待异步任务都完成？

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1003]
我有一个实例，成员变量是之前issues提到的BlockSerise。
主线程退出后，这个Serise中的任务可能还没跑到callback， 我如何在实例的析构函数中等待，安全退出？

**Comment by Barenboim** [comment]
如果你用的是派生的series，可以加个全局的记数，在main结束之前主动等待这个记数归零。我们的pyworkflow项目就是这么搞的。

**Comment by vincentqin-sys** [comment]
是pyworkflow的哪个代码文件，能给个链接吗？我去学习一下。

**Comment by Barenboim** [comment]
就是sogou/pyworkflow项目。

**Comment by vincentqin-sys** [comment]
class CountableSeriesWork final : public SeriesWork 
找到了，多谢~
