### ISSUE TITLE
析构阻塞好像不起作用, 帮忙看看~

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1004]
1. 我在析构里等待.
DataStore::~DataStore() {
  std::cout << "~DataStore" << std::endl;
  CountableSeriesWork::wait_finish();
}
2. 想做一个异步调用,不管执行结果得返回, 主线程直接退出.
void DataStore::MySQL(const std::string &url,
                      const std::string &sql, const MySQLJsonFunc &func) {
  WFMySQLTask *mysql_task =
      WFTaskFactory::create_mysql_task(url, 0, [func](WFMySQLTask *mysql_task) {
        ::Json json = mysql_concat_json_res(mysql_task);
        func(&json);
      });
  mysql_task->get_req()->set_query(sql);
  CountableSeriesWork::start_series_work(
        mysql_task, [](const SeriesWork *series) {
          std::cout << "series call back" << std::endl;
        });
}
3. 单元测试:
  DATA_STORE()->MySQL(true, mysql_url, sql, [](Json* pjson) {
    BOOST_TEST_MESSAGE("call back");
    BOOST_TEST_MESSAGE(pjson->dump().c_str());
  });
  BOOST_TEST_MESSAGE("call end");

5. 得到得结果是:
call end
call back
{"error":"Unknown"}
series call back
in ~CountableSeriesWork, series_count:1
~DataStore

6. 我想达到得效果类似消息队列， 我调一个mysql请求后，我可以退出。 这个mysql请求在执行成功后，再安全退出。

**Comment by Barenboim** [comment]
你这么做确实有点问题。你的DataStore创建，先于第一次使用create mysql task，这时通信器还没有创建。这样的话，析构的顺序是先析构通信器。mysql任务被强制结束，state为WFT_STATE_ABORTED。
你非要搞RAII，可以在DataStore构造之前，调一下WFGlobal::set_scheduler()，这样就先构造通信引擎了。
总之就是个析构顺序的问题。

**Comment by vincentqin-sys** [comment]
可以了，非常感谢！！

**Comment by Barenboim** [comment]
或者你不要在main函数里使用DataStore也可以，再搞一个函数。因为通信器的析构一定是在main的退出。
