### ISSUE TITLE
回调能递归吗？

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1005]
我想实现一个任务出错后，间隔60秒再重试的情景。
void mysql_callback(WFMySQLTask *task)
{
   ::Json json = mysql_concat_json_res(mysql_task);
   if (json.find("errcode") != json.end())
  {
      WFTimerTask *timer =
              WFTaskFactory::create_timer_task(60, 0, [](WFTimerTask *) {
                 WFMySQLTask *mysql_task = WFTaskFactory::create_mysql_task(url, 0, mysql_callback);
              });
  }
}

像上面这样写可以吗？ 或者有其他最佳实践？

**Comment by Barenboim** [comment]
当然可以了。

**Comment by Barenboim** [comment]
我们有点想加一种repeated任务，来方便你这个需求。

**Comment by Barenboim** [comment]
我们自带json解析器的，你也可以用用看。
https://github.com/sogou/workflow/blob/master/src/util/json_parser.h
https://github.com/sogou/workflow/blob/master/src/util/json_parser.c
不过是c语言风格的。

**Comment by vincentqin-sys** [comment]
好的，好的~

**Comment by vincentqin-sys** [comment]
这框架又灵活，又强悍，还很使用起来很优雅，厉害！

**Comment by Barenboim** [comment]
> 这框架又灵活，又强悍，还很使用起来很优雅，厉害！

多谢多谢！那多帮帮我们传播哈。

**Comment by vincentqin-sys** [comment]
那当然，大家都用，才能越来越好~ ：）

> > 这框架又灵活，又强悍，还很使用起来很优雅，厉害！
> 
> 多谢多谢！那多帮帮我们传播哈。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1006
你看看这个PR的修改，增加了WFRepeaterTask。
我把我们tutorial里几个需要repeat的示例用这个来重写一下。

**Comment by vincentqin-sys** [comment]
好的，我学习一下。

**Comment by vincentqin-sys** [comment]
我看了一下例子，在repeatertask里面，有一个等待用户触发后往下再循环的。
我想定时的执行，并且根据执行的结果来决定退出还是循环，这部分怎么实现起来比较好？
repeater = WFTaskFactory::create_repeater_task(create, [&wg](WFRepeaterTask *) {
		wg.done();
	});
在create函数和 回调里，怎么拿到create里面的的子任务的结果，并根据结果来判断退出还是继续？

**Comment by Barenboim** [comment]
> 我看了一下例子，在repeatertask里面，有一个等待用户触发后往下再循环的。
> 我想定时的执行，并且根据执行的结果来决定退出还是循环，这部分怎么实现起来比较好？
> repeater = WFTaskFactory::create_repeater_task(create, [&wg](WFRepeaterTask *) {
> wg.done();
> });
> 在create函数和 回调里，怎么拿到create里面的的子任务的结果，并根据结果来判断退出还是继续？

比较简单方法，因为repeater和所有task是共享series的，你可以在task的callback里，向series context放个标志什么的，在create的时候，可以通过repeater拿到这个标志。
当然，这个方法不一定是最好。接口上，你可以想到什么更好的方案吗？

**Comment by vincentqin-sys** [comment]
你们才给的方案才是最佳实践。。我没想到更好方案。。昨天我用了闭包递归来写callback，结果出现访问内存错误。。：（
我试试repeater的方案看看。

**Comment by Barenboim** [comment]
> 你们才给的方案才是最佳实践。。我没想到更好方案。。昨天我用了闭包递归来写callback，结果出现访问内存错误。。：（
> 我试试repeater的方案看看。

不会吧，闭包递归肯定是一个可用的方法。我们很多示例都是一直用同一个callback的。你应该是哪里用错了。

**Comment by Barenboim** [comment]
> 我看了一下例子，在repeatertask里面，有一个等待用户触发后往下再循环的。
> 我想定时的执行，并且根据执行的结果来决定退出还是循环，这部分怎么实现起来比较好？
> repeater = WFTaskFactory::create_repeater_task(create, [&wg](WFRepeaterTask *) {
> wg.done();
> });
> 在create函数和 回调里，怎么拿到create里面的的子任务的结果，并根据结果来判断退出还是继续？

如果你在task的callback里，可以拿到repeater对象，也可以这么做：
~~~cpp
repeater->set_create([](WFRepeaterTask *)->SubTask *{ return NULL; });
~~~
这就让repeater下次create时，返回一个空指针了。

**Comment by vincentqin-sys** [comment]
> > 你们才给的方案才是最佳实践。。我没想到更好方案。。昨天我用了闭包递归来写callback，结果出现访问内存错误。。：（
> > 我试试repeater的方案看看。
> 
> 不会吧，闭包递归肯定是一个可用的方法。我们很多示例都是一直用同一个callback的。你应该是哪里用错了。

  std::function<void(WFMySQLTask *)> async_mysql_callback =
      [&async_mysql_callback, &url, &sql, &func,
       retry_time](WFMySQLTask *mysql_task) {
        ::Json json = mysql_concat_json_res(mysql_task);
        std::cout << json.dump().c_str() << std::endl;
        // 记录下异步执行的sql
        if (json.find("errcode") == json.end() &&
            json.find("error") == json.end()) {
          if (func) {
            func(&json);
          }
        } else {
          // 出错，添加一个一分钟后重试的定时任务
          WFTimerTask *timer = WFTaskFactory::create_timer_task(
              retry_time, 0,
              [&async_mysql_callback, &url, &sql](WFTimerTask *timer) {
                // -------------------------
                std::time_t t = std::time(nullptr);
                std::cout << std::put_time(std::localtime(&t),
                                           "%Y-%m-%d %H.%M.%S")
                          << std::endl;
                // ----------------------------
               // 打印出时间后,报内存错误, 是下面这个语句,
                WFMySQLTask *mysql_retry_task =
                    WFTaskFactory::create_mysql_task(url, 0,
                                                     async_mysql_callback);
               // dump 1没有输出.
                std::cout << "dump 1" << std::endl;
                mysql_retry_task->get_req()->set_query(sql);
                std::cout << "dump 2" << std::endl;
                series_of(timer)->push_back(mysql_retry_task);
                std::cout << "dump 3" << std::endl;
              });
          series_of(mysql_task)->push_back(timer);
        }
      };
  WFMySQLTask *mysql_task =
      WFTaskFactory::create_mysql_task(url, 0, async_mysql_callback);

  mysql_task->get_req()->set_query(sql);
  CountableSeriesWork::start_series_work(mysql_task, nullptr);

上面是我的实现例子, 哪个地方用错了...帮忙指正一下.

**Comment by vincentqin-sys** [comment]
> 
> 比较简单方法，因为repeater和所有task是共享series的，你可以在task的callback里，向series context放个标志什么的，在create的时候，可以通过repeater拿到这个标志。 当然，这个方法不一定是最好。接口上，你可以想到什么更好的方案吗？

repeater好像只能有一个子任务， 子任务中再建任务，好像不执行，我是不是用错了？

auto &&create = [](WFRepeaterTask *repeater_task) -> SubTask * {
   std::cout << "repeater callback" << std::endl;
   WFTimerTask *timer = WFTaskFactory::create_timer_task(
        10, 0, [](WFTimerTask *timer) {
        std::cout << "timer callback" << std::endl;
        WFMySQLTask *mysql_retry_task = WFTaskFactory::create_mysql_task(url, 0, [](WFMySQLTask *mysql_task) {
            std::cout << "mysql callback" << std::endl;
        });
        mysql_retry_task->get_req()->set_query(sql);
        series_of(timer)->push_back(mysql_retry_task);
   });
  return timer;
};
WFRepeaterTask *repeater;
repeater = WFTaskFactory::create_repeater_task(create, nullptr);
CountableSeriesWork::start_series_work(repeater, nullptr);

上面这段代码，就是10秒输出一次
repeater callback
timer callback
没看到“mysql callback”， 我能这样使用repeater吗？
如果不行，我是不是只能在repeater里面sleep10秒，再创建mysqltask？

**Comment by Barenboim** [comment]
> > 比较简单方法，因为repeater和所有task是共享series的，你可以在task的callback里，向series context放个标志什么的，在create的时候，可以通过repeater拿到这个标志。 当然，这个方法不一定是最好。接口上，你可以想到什么更好的方案吗？
> 
> repeater好像只能有一个子任务， 子任务中再建任务，好像不执行，我是不是用错了？
> 
> auto &&create = [](WFRepeaterTask *repeater_task) -> SubTask * { std::cout << "repeater callback" << std::endl; WFTimerTask *timer = WFTaskFactory::create_timer_task( 10, 0, [](WFTimerTask *timer) { std::cout << "timer callback" << std::endl; WFMySQLTask *mysql_retry_task = WFTaskFactory::create_mysql_task(url, 0, [](WFMySQLTask *mysql_task) { std::cout << "mysql callback" << std::endl; }); mysql_retry_task->get_req()->set_query(sql); series_of(timer)->push_back(mysql_retry_task); }); return timer; }; WFRepeaterTask *repeater; repeater = WFTaskFactory::create_repeater_task(create, nullptr); CountableSeriesWork::start_series_work(repeater, nullptr);
> 
> 上面这段代码，就是10秒输出一次 repeater callback timer callback 没看到“mysql callback”， 我能这样使用repeater吗？ 如果不行，我是不是只能在repeater里面sleep10秒，再创建mysqltask？

你把push_back改成push_front吧。这也是我担心的一个用法问题。reoeater也是一种task，在repeat结束之前一直在series里。push_back的话，mysql task被放到后面去了。
我觉得更好的办法是mysql task.也让create来产生

**Comment by Barenboim** [comment]
另外， repeater callback的调用时机是repeater整体结束，所以你打log最好不要叫repeater callback。

**Comment by vincentqin-sys** [comment]
> 
> 你把push_back改成push_front吧。这也是我担心的一个用法问题。reoeater也是一种task，在repeat结束之前一直在series里。push_back的话，mysql task被放到后面去了。 我觉得更好的办法是mysql task.也让create来产生

mysql task 如果也让create来产生， 那return回去timer task还是 mysql task？
return timer的话， mysql task在creater里面还没有series吧？ 能把mysql task push进series吗？

**Comment by vincentqin-sys** [comment]
好像可以拿到series， 我只要先push timer task， 再push mysql task，然后返回timer。 这样可以吗？

**Comment by Barenboim** [comment]
> 好像可以拿到series， 我只要先push timer task， 再push mysql task，然后返回timer。 这样可以吗？

我的意思是，这两种任务都回create来返回，不再push了。根据状态决定返回什么。
你甚至可以通过切换create函数来完成这个事。

**Comment by vincentqin-sys** [comment]
> 
> 我的意思是，这两种任务都回create来返回，不再push了。根据状态决定返回什么。 你甚至可以通过切换create函数来完成这个事。

push_front方式还是不行. 
通过create来判断series的context, 根据不同context来返回不通task的方式完美解决.
多谢~~

**Comment by vincentqin-sys** [comment]
还有一个小问题，使用repeater后，析构顺序是怎样的？ 
我看如果我不安全退出，没有进入CountableSeriesWork的析构。如果我等待repeater执行完成后，能正确析构CountableSeriesWork。

**Comment by Barenboim** [comment]
> 还有一个小问题，使用repeater后，析构顺序是怎样的？ 我看如果我不安全退出，没有进入CountableSeriesWork的析构。如果我等待repeater执行完成后，能正确析构CountableSeriesWork。

我知道了，repeater插入任务时，直接调用了series的，而不是你派生的。要解决，只能把push back和push front改成virtual

**Comment by vincentqin-sys** [comment]
> 
> 我知道了，repeater插入任务时，直接调用了series的，而不是你派生的。要解决，只能把push back和push front改成virtual

还是不太明白。我看repeatertask用的是series_of(this) ->push_front(this);  是因为这个原因吗？
但这个得到的是父类的函数，但不会生成新的对象，不应该呀。。。
不知道我哪里理解错了？麻烦指点一下。

**Comment by vincentqin-sys** [comment]
> 
> 我知道了，repeater插入任务时，直接调用了series的，而不是你派生的。要解决，只能把push back和push front改成virtual

还是不太明白。我看repeatertask用的是series_of(this) ->push_front(this);  是因为这个原因吗？
但这个得到的是父类的函数，但不会生成新的对象，不应该呀。。。
不知道我哪里理解错了？麻烦指点一下。

**Comment by Barenboim** [comment]
repeater task的dispatch里，有一行是push_front(task)，就是push你create的那个任务。这个push_front调用的是SeriesWork的push_front。我怀疑这个地方没有进入你的count？

**Comment by vincentqin-sys** [comment]
CountableSeriesWork 只记录全局的series数量，不记录series中的task数量。它是等待series_counter。
构造是生成也是父类SeriesWork
 CountableSeriesWork(SubTask *first, series_callback_t &&callback)
      : SeriesWork(first, std::move(callback)) {
    std::unique_lock<std::mutex> lk(series_mtx);
    ++series_counter;
  }

目前析构顺序是这样的：
repeater begin
begin
call end
---这里main退出---
 ~DataStore  //进入wait_finish()
{"errcode":1062}   //create 的第一个任务的callback,设置context【error】
repeater begin
error
2022-08-03 16.20.34 // //create 的第一个任务的callback,设置context【timer_end】
repeater begin
timer_end

然后结束，没进入~CountableSeriesWork()

**Comment by Barenboim** [comment]
噢噢，那不应该了😂可能是你的程序哪里写的有问题。
Repeater你可以看一下实现，不影响series的创建和销毁。

**Comment by vincentqin-sys** [comment]
找到问题了,create 闭包引入使用&引入sql的string串,  第二次运行的时候, 这个串就出错了... 不能&闭包.
多谢耐心解答~

**Comment by Barenboim** [comment]
这么写可能更简单：
~~~cpp
SubTask *create_timer(WFRepeaterTask *repeater)
{
    repeater->set_create(create_mysql);
    return WFTaskFactory::create_timer_task(...);
}

SubTask *create_mysql(WFRpeaterTask *repeater)
{
    if (...)
        repeater->set_create(create_timer);

    if (...)
        return.WFTaskFactory::create_mysql_task(...);
    else
        return NULL;
}
~~~

**Comment by vincentqin-sys** [comment]
好的, 多谢~~这样确实清晰很多!
