### ISSUE TITLE
MySQLCell中没有获取decimal的函数，怎么获取对应字段的值？

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1010]
如题。
我看到is_string 中有判断MYSQL_TYPE_DECIMAL 为string类型。 但现在MySQL的decimal得到类型是MYSQL_TYPE_NEWDECIMAL。
不知道这两个类型有什么区别，能否也使用string的方式来处理？

**Comment by vincentqin-sys** [comment]
看了例子，可以直接转成string类型了，用as_binary_string()。。

**Comment by Barenboim** [comment]
我们在is_string()里也加上NEWDECIMAL类型吧。别的好像也不用改

**Comment by holmes1412** [comment]
嗯嗯，DECIMAL类型可以参考：https://mariadb.com/kb/en/resultset-row/#decimal-binary-encoding
然后看了下别的项目里也是没有找到NEWDECIMAL的说明文档，都是建议直接转string就好。
