### ISSUE TITLE
使用workflow发送post请求崩溃

### ISSUE THREAD

**Issue by deep-practice** [sogou/workflow#1014]
错误信息如下：
![bug20220808082639](https://user-images.githubusercontent.com/54052915/183322562-bf02eca8-3a53-4220-919e-a2593cc75fe7.jpg)
代码：
![code20220808082823](https://user-images.githubusercontent.com/54052915/183322614-122408e0-fff6-4ed7-a1c4-85b487eb3179.jpg)

**Comment by holmes1412** [comment]
用法没有问题～把代码改到了tutorial-01上也没复现。

这里series跑起来之后主进程没有退出吧？

**Comment by deep-practice** [comment]
我重新编译了个workflow解决了，也不知道是为啥~

**Comment by holmes1412** [comment]
好的～还有问题随时po哈

**Comment by deep-practice** [comment]
如果想要让timer task或者go task join到主线程，该怎么设置呢？

**Comment by Barenboim** [comment]
是想让主线程等timer和go task都完成吗？
一般来讲，这两个可以不用等，程序直接退出没有什么关系。没有运行的go task和被打断的timer，会以WFT_STATE_ABORTED的状态callback。

**Comment by deep-practice** [comment]
我现在的情况是启动了很多timer task，通过ctrl-c终止程序的时候，这些timer task还在运行，停不下来，只能kill掉进程。

**Comment by Barenboim** [comment]
不会吧，程序直接退出，timer是可以被打断的。当然了，callback之后你不应该再push_back新的任务。

**Comment by Barenboim** [comment]
~~~cpp
#include "workflow/WFTaskFactory.h"

int main()
{
    for (int i = 0; i < 1000; i++)
        WFTaskFactory::create_timer_task(1, 0, nullptr)->start();

    return 0;
}
~~~
这个代码，是正确的。程序可以立即结束。

**Comment by Barenboim** [comment]
~~~cpp
#include "workflow/WFTaskFactory.h"

int main()
{
    for (int i = 0; i < 1000; i++)
        WFTaskFactory::create_timer_task(1, 0, nullptr)->start();

    return 0;
}
~~~
这个代码，是正确的。程序可以立即结束。

**Comment by deep-practice** [comment]
明白了
