### ISSUE TITLE
Ctrl-C之后如果正常结束程序？

### ISSUE THREAD

**Issue by deep-practice** [sogou/workflow#1015]
**当通过ctrl-c中断程序的时候，如果workflow有任务在执行，就会报这个错**
**该怎么处理呢？**
*** Error in `./app': corrupted double-linked list: 0x00000000018716e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x808ef)[0x7fb15d8358ef]
/lib64/libc.so.6(+0x8117e)[0x7fb15d83617e]
/lib64/ld-linux-x86-64.so.2(_dl_deallocate_tls+0x58)[0x7fb178de4908]
/lib64/libpthread.so.0(+0x6ee7)[0x7fb178280ee7]
/lib64/libpthread.so.0(+0x6fff)[0x7fb178280fff]
/lib64/libpthread.so.0(pthread_join+0xe3)[0x7fb178283053]
/usr/local/lib64/libworkflow.so.0(poller_stop+0x46)[0x7fb162477db6]
/usr/local/lib64/libworkflow.so.0(mpoller_stop+0x26)[0x7fb162476236]
/usr/local/lib64/libworkflow.so.0(_ZN12Communicator6deinitEv+0x14)[0x7fb16247ba14]
/usr/local/lib64/libworkflow.so.0(_ZN13__CommManagerD1Ev+0x18)[0x7fb162487628]
/lib64/libc.so.6(+0x39ce9)[0x7fb15d7eece9]
/lib64/libc.so.6(+0x39d37)[0x7fb15d7eed37]
/lib64/libc.so.6(__libc_start_main+0xfc)[0x7fb15d7d755c]
./app[0x4f550f]
======= Memory map: ========

**Comment by Barenboim** [comment]
你捕获Ctrl-C了吗？如果没有，进程直接就没了，不应该会有core的。如果捕获了，需要等网络任务都结束。

**Comment by deep-practice** [comment]
我捕获了的，怎样等待网络任务都结束呢？

**Comment by Barenboim** [comment]
这个文档里有关于程序退出的说明：
https://github.com/sogou/workflow/blob/master/docs/about-exit.md
