### ISSUE TITLE
咨询一个关于链接管理的问题.

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1018]
举个例子, 像issues推荐的wfrest项目. 作为一个webserver的服务端, 里面又有访问mysql,作为客户端.
实现都是使用workflow来实现. 那链接数是怎么分配的? 作为服务链接和作为客户链接共用一个配置吗? 是哪个配置?
如果是共用, 如果网站并发数量很大的话, 会不会出现链接线程都去做服务去了, 连不了数据库这种情况?

**Comment by Barenboim** [comment]
我们没有总连接数限制，只有对单个IP:port的连接数限制，默认是200。所以不存在连接都被一个目标占用的情况。

**Comment by Barenboim** [comment]
服务器的连接数，是在WFServer的参数里，默认是2000。如果超过了，会关闭最久未使用的空闲连接。如果没有空闲连接，就拒绝服务。这些参数都可以改。

**Comment by vincentqin-sys** [comment]
> 服务器的连接数，是在WFServer的参数里，默认是2000。如果超过了，会关闭最久未使用的空闲连接。如果没有空闲连接，就拒绝服务。这些参数都可以改。

那我是不是可以这样理解, 所有都用默认配置的话, 极端情况下, 10个ip:port把链接占满后, 这时如果有连接数据库的请求, 就会创建不了连接? 总连接数就是这个2000?

**Comment by Barenboim** [comment]
> > 服务器的连接数，是在WFServer的参数里，默认是2000。如果超过了，会关闭最久未使用的空闲连接。如果没有空闲连接，就拒绝服务。这些参数都可以改。
> 
> 那我是不是可以这样理解, 所有都用默认配置的话, 极端情况下, 10个ip:port把链接占满后, 这时如果有连接数据库的请求, 就会创建不了连接? 总连接数就是这个2000?

不好意思，我说的有点歧义。server默认的2000连接，是指server接受client连进来的连接，和server去连接其它上游服务器的连接数无关。

**Comment by vincentqin-sys** [comment]
> 
> 不好意思，我说的有点歧义。server默认的2000连接，是指server接受client连进来的连接，和server去连接其它上游服务器的连接数无关。

我这么理解，你看对不：server本身对外服务默认链接2000，连接上游一个ip：port默认200. 这两块链接是分开管理的。
那我还有一个问题哈： server去连上游服务器， 这个200是动态管理的，会根据空闲会释放不？ 空闲多久会释放，有空闲时间配置吗？

**Comment by Barenboim** [comment]
> > 不好意思，我说的有点歧义。server默认的2000连接，是指server接受client连进来的连接，和server去连接其它上游服务器的连接数无关。
> 
> 我这么理解，你看对不：server本身对外服务默认链接2000，连接上游一个ip：port默认200. 这两块链接是分开管理的。 那我还有一个问题哈： server去连上游服务器， 这个200是动态管理的，会根据空闲会释放不？ 空闲多久会释放，有空闲时间配置吗？

关于持久连接的管理，还是比较智能的。一般默认是保持60秒，FILO。mysql事务的连接，保持时间是1小时（每两条语句之间的时间）。http的话，会根据server的回复和你的请求里是否带connection这个header来决定是否长连接。
自定义协议默认是短连接，你可以调用task->set_keep_alive()来设置连接保持时间，单位是ms。这个接口也适应于其他所有协议。

**Comment by vincentqin-sys** [comment]
好的. 多谢解答~~
