### ISSUE TITLE
关于Communicator中几种状态的疑惑

### ISSUE THREAD

**Issue by Oldvv** [sogou/workflow#1019]
您好！最近在学习workflow，膜拜ing。。。
有一点疑惑想请教。
Communicator::create_message只处理IDLE、KEEPALIVE、CONNECTED三个状态。 是否可能出现在SUCCESS状态（Communicator层还未处理res，状态还没变IDLE）的时候收到了新的消息的情况?

**Comment by Oldvv** [comment]
现在看来，如果出现这种情况，会移除关注fd。 还是说不会出现这种情况？

**Comment by Barenboim** [comment]
是的，同学，你看得非常仔细。主版的实现，消息是严格一来一回的，所以SUCCESS状态还未处理如果收到数据，就认识肯定是垃圾数据，直接关连接，但之前成功的消息还是会返回给用户。
全双工的版本，可以看看这个用户的实现：
https://github.com/sogou/workflow/issues/873

**Comment by Oldvv** [comment]
好的. 感谢解惑~
