### ISSUE TITLE
请问下，LRUCache.h 这里两个list_entry 看起来好像 prune 多了个取指针符号的,不知道有没有问题呢

### ISSUE THREAD

**Issue by edwardL** [sogou/workflow#1023]
![6514645247adefb76a9cbfe0219b13c](https://user-images.githubusercontent.com/3971345/186575295-f4004436-6580-4d6b-999e-e9e28de8025e.jpg)

**Comment by Barenboim** [comment]
prune那里好像不对。我一会改一下。
这个函数应该不会被调用到，所以没有出错。

**Comment by Barenboim** [comment]
改了：https://github.com/sogou/workflow/commit/c8c5da70c74ef505c987aec5500a660a7267aa24
多谢。

**Comment by tothedistance** [comment]
好像还是不对，一旦用就编译不过。

**Comment by Barenboim** [comment]
> 好像还是不对，一旦用就编译不过。

你单独把这个模块拿出来用了？

**Comment by tothedistance** [comment]
是的，我在看dns缓存，想仿写一个视频帧共享缓存。但似乎现在并没有用上这个模块，而是复用了一个commtarget。我是拷贝的文件。

**Comment by Barenboim** [comment]
> 是的，我在看dns缓存，想仿写一个视频帧共享缓存。但似乎现在并没有用上这个模块，而是复用了一个commtarget。我是拷贝的文件。

好的，我单独试一下lru cache看看是什么问题。如果直接使用核心代码开发应用，有什么问题可以重新发issue。
