### ISSUE TITLE
Hololens2

### ISSUE THREAD

**Issue by songguanqing** [sogou/workflow#1025]
你好作者，问几个问题。
我看评论区有人说windows下https有问题，现在改好了吗？
这个库支持hololens2吗？平台是UWP，而且需要把库编译成arm架构下的。
非常感谢能回复我

**Comment by Barenboim** [comment]
Windows下的https server应该有点问题，还没有修复。Windows支持的同学是搜狗输入法的研发，平时工作有点忙。虽然复现了问题，但还不知道怎么改。
UWP好像是基于Windows的系统？这块没有人试过。我们的代码里没有汇编语言，应该不会有CPU架构不兼容的问题。你可以编译一下试试。生产环境我觉得还是尽量用Linux或MacOS。

**Comment by Barenboim** [comment]
@songguanqing
Windows下的https server也可以用了：https://github.com/sogou/workflow/issues/936
