### ISSUE TITLE
希望更新一下vcpkg

### ISSUE THREAD

**Issue by ilongshan** [sogou/workflow#1029]
现在vcpkg包还是0.9.7版本，希望能够更新一下

**Comment by Barenboim** [comment]
您需要的是windows版吗？Windows尽量还是直接吧，维护力量不太足😓

**Comment by ilongshan** [comment]
需要mac/linux版本的

**Comment by ilongshan** [comment]
因为项目中的依赖是用vcpkg管理的，比较统一。用vcpkg管理workflow的话，配置用起来也比较简单。不然既有vcpkg管理的包，又有其他方法管理的包，比较乱，也容易出错。

所以希望能更新一下vcpkg的包。维护这些包确实需要比较多的资源，希望你们后续能有更丰富的资源来维护这些包。

**Comment by chanchann** [comment]
通过vcpkg install workflow --head可以获取最新的master分支的workflow

**Comment by ilongshan** [comment]
我用的是vcpkg.json，用不了--head的选项。在CMakeLists.txt中添加set(VCPKG_USE_HEAD_VERSION ON)，也不起作用。安装的还是0.9.7#1这个版本。

**Comment by Barenboim** [comment]
@dengjunplusplus

**Comment by Barenboim** [comment]
vcpkg已经更新到0.10.5版本！包括windows和Linux版。
