### ISSUE TITLE
named conditional问题

### ISSUE THREAD

**Issue by mwyhaha** [sogou/workflow#1034]
`auto test_fun = []()
	{
		printf("test_fun done!\n");
	};

	WFGoTask *go_test1 = WFTaskFactory::create_go_task("test", []() { printf("test1 done\n"); });
	WFGoTask *go_test2 = WFTaskFactory::create_go_task("test", test_fun);
	WFConditional *cond_test1 = WFTaskFactory::create_conditional("named_cond", go_test1);
	cond_test1->start();
	WFConditional *cond_test2 = WFTaskFactory::create_conditional("named_cond", go_test2);
	cond_test2->start();
	WFTaskFactory::signal_by_name("1111", NULL);`

这段测试代码有什么问题吗，为什么两个gotask都被唤起了？
_ConditionMap::signal函数中，cons是不是不会为NULL。

**Comment by Barenboim** [comment]
但你好像signal_by_name时，name都不是conditional的名字。这也唤醒了?

**Comment by Barenboim** [comment]
😓
完了，代码写错了。我下午修改。

**Comment by Barenboim** [comment]
你好，麻烦试一下我这个修改。原来代码有bug，对于没有匹配上的name，可能会错误的唤醒别的cond。

**Comment by mwyhaha** [comment]
> 你好，麻烦试一下我这个修改。原来代码有bug，对于没有匹配上的name，可能会错误的唤醒别的cond。

不行呢。匹配上的name，无法唤醒了。

**Comment by Barenboim** [comment]
是，没改对……我继续改。

**Comment by Barenboim** [comment]
> > 你好，麻烦试一下我这个修改。原来代码有bug，对于没有匹配上的name，可能会错误的唤醒别的cond。
> 
> 不行呢。匹配上的name，无法唤醒了。

好了，再试一下！
