### ISSUE TITLE
wfkafka在一个kafka broker挂掉时的问题

### ISSUE THREAD

**Issue by kkEdward** [sogou/workflow#1036]
**问题：**
服务使用wfkafka进行produce，重试次数为10次。配置的broker数量为2（实际kafka集群的broker数量大约45个），在其中1个broker挂掉后，出现大量失败，错误日志如下：
>** kafka fail for state 67 error 5006 Kafka meta api failed**

**线下测试复现：**
1.使用线上版本，线下测试复现时，对配置broker数量为2和3的情况进行了测试，在其中一个broker无法访问时，均有一定的概率会出现失败，错误日志和上述一致。

2.更新wfkafka到最新版本，分别对配置broker数量为2和3的情况进行了测试，在其中一个broker无法访问时，也有一定的概率出现失败，错误日志如下：
> **kafka fail for state 1 error 110 Connection timed out**
> **kafka fail for state 1 error 111 Connection refused**

**预期行为：**
配置多个broker，在其中一个broker故障时，能在服务无感知的情况下自动切换到其他broker上

**Comment by Barenboim** [comment]
失败的概率，和broker挂掉的比例是一样的吗？
比如，3个broker有一个挂了，是不是1/3的请求出现失败？

**Comment by kkEdward** [comment]
您好，邮件已经收到，我会尽快回复。

**Comment by kkEdward** [comment]
线上2个broker的情况下，当时找了几个机器看，大部分都失败了。
线下复现测试的时候，概率和挂掉的broker比例相当

**Comment by kkEdward** [comment]
> 失败的概率，和broker挂掉的比例是一样的吗？ 比如，3个broker有一个挂了，是不是1/3的请求出现失败？
<img width="573" alt="image" src="https://user-images.githubusercontent.com/23446680/187860430-904e0717-2fb5-4fb2-b1f8-fc727fdc5942.png">



> 失败的概率，和broker挂掉的比例是一样的吗？ 比如，3个broker有一个挂了，是不是1/3的请求出现失败？

线上配置2个broker，挂了一个1个broker，当时找了几个机器看，大部分都失败了，具体的比例没统计。
线下复现测试的时候，失败的概率和挂掉的broker比例差不多。

**Comment by Barenboim** [comment]
理论上，访问一个broker失败，是会重新获取meta信息的。新的meta信息里，应该不再包含挂了的meta。
从你的现象上看，好像这个逻辑没有被执行。我看看代码上有没有什么问题。

**Comment by Barenboim** [comment]
你是一直用一个client创建任务吧？

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/commit/848386749ffc1674888e2bcab3a2900cee20e461
2022年1月这个改动，让某个任务失败之后，meta重新回到uninit状态。下次会自动重新获取meta。用新代码应该是没有问题的。

**Comment by Barenboim** [comment]
@kkEdward
