### ISSUE TITLE
将ResponseBody保存下来的一点疑问

### ISSUE THREAD

**Issue by jinyunshaobing** [sogou/workflow#1037]
在文档中有说到使用move()的方式保存resp，因为在task运行时，callback函数调用结束后，task指针就莫得了
`my_resp = new protocol::HttpResponse(std::move(*resp));`

在这里我有一个很简单的需求，但是不知道怎么写（原谅我是个C++萌新）
```
string fun(){
    创建task发送http请求
    请求完成后
    return http请求体
}
```
能否麻烦各路大神给个example，感激不尽~

**Comment by Barenboim** [comment]
你是想把异步变成同步吗？首先，你这么做，需要用wait_group做一个等待（不太推荐，但鉴于你的需求就是同步），在callback里，调用HttpUtil::decode_chunked_body()把resp的body转成string就可以了。
比如：
~~~cpp
#include "workflow/HttpUtil.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"

std::string func()
{
    std::string res;
    WFFacilities::WaitGropu wg(1);
    task = WFTaskFactory::create_http_task(..., [&res, &wg](WFHttpTask *t){
        res = HttpUtil::decode_chunked_body(t->get_resp());
        wg.done();
    });
    wg.wait();
    return res;
}
~~~

**Comment by jinyunshaobing** [comment]
感谢，我试一试。
如果我的需求只是单纯的发起HTTP/HTTPS请求，然后拿到响应的结果再去做其他的事情，是不是用workflow有点大材小用了（而且不是异步），是否有更加轻量级的C++ HTTP lib推荐呢

**Comment by Barenboim** [comment]
workflow已经是最轻量级的lib了吧？没有更小的了。你可以简单封装一下这个同步的功能。

**Comment by jinyunshaobing** [comment]
好的ヽ(￣▽￣)و，我写一写
