### ISSUE TITLE
生产者KafkaRecord对象销毁问题

### ISSUE THREAD

**Issue by zydxhs** [sogou/workflow#1038]
我的使用场景如下：
1. 创建消费任务从topic消费数据
2. 在回调函数中，把 KafaRecord 对象指针保存到全局容器中
3. 从全局容器中取出消息进行业务处理
4. 业务处理完毕后提交offset

调试环境：
ubuntu 18.04 + gcc 7.5.0

0.10.1, 0.10.2, 0.10.3 三个版本都测试了，全部都存在这个现象。

问题出在第3步，从容器中取出的 KafkaRecord 对象指针的内容被改写了。调用 get_topic() / get_patition() 有很大概率崩溃。

可以确认的是，g_vctMsg 不存在使用问题。我用 tutorial-13-kafka_cli 这个示例测试，同样会崩溃。

既然已经把 KafkaRecord 从 Task 中移出来了，为什么它还会被释放掉呢？

第2步的回调函数中，保存 KafaRecord 的核心代码大概这样:
```c++
protocol::KafkaResult new_result;
std::vector<std::vector<KafkaRecord *>> records;

case Kafka_Fetch:
    new_result = std::move(*task->get_result());
    new_result.fetch_records(records);

    for (const auto &v : records)
    {
        for (const auto &w : v)
        {
            g_vctMsg.push_back(w);
        }
    }
}
```

第3步的相关代码如下：
```c++
KafkaRecord *pMsg = (KafkaRecord*)g_vctMsg.front();
const char *strTopic = pMsg->get_topic();  // 崩溃
int32_t nPartition = pMsg->get_partition(); // 崩溃
```

**Comment by Barenboim** [comment]
你好。按照我们的设计，KafkaResult可以被移动走的，但KafkaRecord的指针是直接引用KafkaResult。按照的话，只要KafkaResult还在生命周期内，从result里取出的record应该是可以用的。
我没有看到完整的代码，是否你是直接在callback里取走record到g_vctMsg里，但KafkaResult却没有拿走呢？

**Comment by Barenboim** [comment]
~~~cpp
protocol::KafkaResult new_result;
std::vector<std::vector<KafkaRecord *>> records;

case Kafka_Fetch:
    new_result = std::move(*task->get_result());
    new_result.fetch_records(records);

    for (const auto &v : records)
    {
        for (const auto &w : v)
        {
            g_vctMsg.push_back(w);
        }
    }
}
~~~
以这段代码来讲的话，如果g_vctMsg是一个外部传进来的引用，或者是一个全局变量，那么在这个函数之后使用g_vctMsg确实会崩溃。因为new_result是个局部变量，record是要引用result里的内容的。

**Comment by zydxhs** [comment]
> 你好。按照我们的设计，KafkaResult可以被移动走的，但KafkaRecord的指针是直接引用KafkaResult。按理的话，只要KafkaResult还在生命周期内，从result里取出的record应该是可以用的。 我没有看到完整的代码，是否你是直接在callback里取走record到g_vctMsg里，但KafkaResult却没有拿走呢？

确实如你所说，KafkaResult 并没有拿走。对于用户来说，关注的是消息，KafkaRecord 从 KafkaReslt 取出缓存后，我认为不该再关心KafkaResult了。

另外，我的需求应该是这样的：
1. 在 callback 里，把 topic, partition, offset, message, ... 从 KafkaRecord 中取出缓存起来
2. 从缓存中取出数据进行业务处理
3. 使用 topic, partiton, offset 作为参数，提交 offset

但是，由于接口设计的原因，我无法这样做，只能缓存 KafkaRecord 指针，然后就碰到上前面的问题。

**Comment by zydxhs** [comment]
我认为 KafkaRecord 的设计，不是太合理：

1. 对于业务来说，关注的重点是消息，而不是 KafkaResult。
    为了缓存消息，还得缓存 KafkaResut；必需等到KafkaResult 中的所有消息都处理完了，才能统一释放。
2. KafkaRecord 类实现了赋值运算符重载，为什么不实现赋值构造函数呢？
3. 提交 offset 的接口，为什么不提交接受 topic/patition/offset  的接口呢？

**Comment by Barenboim** [comment]
情况是这样的，我解释一下。
在我们其它的网络协议里，结果是跟着resp走的，例如最简单的http：
~~~cpp
void callback(WFHttpTask *task)
{
    auto *resp = task->get_resp();
    const void *data;
    size_t size;
    resp->get_parsed_body(&data, &size);
    ...
}
~~~
在这个例子里，data并不能在callback之外使用，因为data引用的是resp里的内容。如果需要在callback外使用data，一个方法是copy，例如可以用HttpUtil::get_chunked_body函数。如果不想增加内存拷贝，可以再new一个新的resp，把task里的resp完整的移动走。
由于kafka本身是一个分布式的协议，每个WFKafkaTask，可能需要访问多个broker，最终汇总信息。为了让用户使用方便，我们不会让用户直接接触实际的KafkaResponse。所以，WFKafkaTask并不是从WFNetworkTask派生，也没有get_resp()接口。从WFKafkaTask取数据，就只有get_result()接口。可以认为，这个接口就是对应到其它网络协议的get_resp()。
你可以看到，我们从KafkaResult里拿结果的接口是：
void fetch_records(std::vector<std::vector<KafkaRecord *>>& records);
vector里的模板参数是KafkaRecord *，是一个指针。这个目的就是尽可能的减少内存复制。也就是说，取record只是一个指针赋值的过程，并没有常拷贝各个record。那么，对vector结果的使用，必须保证在result的生命周期之内。
所以，像http一样，你可以在callback里把records里你需要的数据copy走，也可以把result直接move另外一个地方，在result的生命周期里使用records。其实，你的代码里搞个全局变量g_vctMsg存reocrds真没有必要，直接存result，需要的时候再展开使用不好吗？把new_result变成全局的，或者是函数参数就可以了。

**Comment by Barenboim** [comment]
> > 你好。按照我们的设计，KafkaResult可以被移动走的，但KafkaRecord的指针是直接引用KafkaResult。按理的话，只要KafkaResult还在生命周期内，从result里取出的record应该是可以用的。 我没有看到完整的代码，是否你是直接在callback里取走record到g_vctMsg里，但KafkaResult却没有拿走呢？
> 
> 确实如你所说，KafkaResult 并没有拿走。对于用户来说，关注的是消息，KafkaRecord 从 KafkaReslt 取出缓存后，我认为不该再关心KafkaResult了。
> 
> 另外，我的真实需求是这样的：
> 
> 1. 在 callback 里，把 topic, partition, offset, message, ... 从 KafkaRecord 中取出缓存起来
> 2. 从缓存中取出数据进行业务处理
> 3. 使用 topic, partiton, offset 作为参数，提交 offset

你也可以把这些结果从records里拷贝出来。就是个深拷贝和浅拷贝的问题。

**Comment by zydxhs** [comment]
你说的有道理。如果可以给用户更多的选择不是更好吗？

我的建议：
1. KafkaRecord 的拷贝构造函数、拷贝赋值运算符重载，要么都实现，要么都禁用
2. 提交 offset 的接口，增加接受 topic/patition/offset 的重载

至于 KafkaResult，或许提供一个接口，允许用户把 KafkaRecord 移走也是个不错的主意。

**Comment by Barenboim** [comment]
你难道没有看出来，我们的所有做法，就是不给用户选择……比如，我们的各种消息，都没有拷贝构造，也没有拷贝赋值。
而且，当我们不支持拷贝构造的时候，并不是用delete禁用，而是彻底当这种东西不存在。
我们一般是只提供一个Generic的方法，用户可以在这个方法进行封装。在我们这个基础上面，你完全可以定义你需要的结构，从我们的KafkaRecord里把想要的域取走。
这个是设计思想上的不同，没有什么好和不好。

**Comment by Barenboim** [comment]
KafkaRecord里那个拷贝赋值，应该是多余的。不好意思，我一会删了。

**Comment by Barenboim** [comment]
KafkaDataTypes里的数据结构，是有拷贝赋值和拷贝构造的。我觉得KafkaRecord应该也加上拷贝构造，这个应该是漏了。
但无论如何，这些数据结构都应该引用一个KafkaResult。

**Comment by Barenboim** [comment]
> 2. 提交 offset 的接口，增加接受 topic/patition/offset 作为参数的重载实现

https://github.com/sogou/workflow/blob/9ab2e08dc8d287eb8255fd84a3d2eacf248b0da3/src/client/WFKafkaClient.h#L52
https://github.com/sogou/workflow/blob/9ab2e08dc8d287eb8255fd84a3d2eacf248b0da3/src/client/WFKafkaClient.h#L61

是这两个吗？

**Comment by zydxhs** [comment]
> > 2. 提交 offset 的接口，增加接受 topic/patition/offset 作为参数的重载实现
> 
> https://github.com/sogou/workflow/blob/9ab2e08dc8d287eb8255fd84a3d2eacf248b0da3/src/client/WFKafkaClient.h#L52
> 
> 
> https://github.com/sogou/workflow/blob/9ab2e08dc8d287eb8255fd84a3d2eacf248b0da3/src/client/WFKafkaClient.h#L61
> 
> 是这两个吗？

是的，函数签名类似这样：
`void add_commit_record(const std::string &topic, int partition, long long offset)`

**Comment by Barenboim** [comment]
这个功能我需要和kafka client的作者讨论一下。issue我先关了哈。
如果项目帮到你了，麻烦点一下star啊。
