### ISSUE TITLE
关于 KAFKA_TIMESTAMP_LATEST 的消费问题

### ISSUE THREAD

**Issue by zydxhs** [sogou/workflow#1040]
wfkafka 跟 rdkafka 的消费行为不一致。

前置条件：
1. topic 有数据，但没有消费过，也就是没有提交过 offset
2. 后续测试中，没有生产者向该topic发布数据

rdkafka 的配置参数中，`auto.offset.reset` 设置为 latest 时，在消费时，不会返回 topic 中的任何消息。

wfkafka 用如下代码进行消费，会返回 topic 中的最后一条数据：
```c++
WFKafkaClient client;
client.init(url, "test_group1");
auto task = client.create_kafka_task("api=fetch&topic=base_test", 3, kafka_callback);

KafkaConfig config;
config.set_client_id("workflow");
config.set_offset_store(0);
config.set_offset_timestamp(KAFKA_TIMESTAMP_LATEST);
task->set_config(std::move(config));
task->start();
```

我的理解，以上两种消费模式，应该是等价的，wfkafka 也不应该返回任务数据才对。

请确认下这个问题。

**Comment by Barenboim** [comment]
这个KAFKA_TIMESTAMP_LATEST好像是我们的默认参数，意思就是返回最后一条。之前这个参数默认为EARLIEST。
这个行为不好？如果你不想返回数据，是不是应该自己设置一个timestamp？
我们这个的含义，和rdkafka里的应该不一样吧。我们就是从哪里开始消费的意思。

**Comment by Barenboim** [comment]
现在的问题可能是，默认行为是LATEST到底好不好😂这块之前也有争论，甚至还改过一次默认。

**Comment by Barenboim** [comment]
应该是当前时间的毫秒数。取一下当前绝对时间（秒），然后乘以1000。和toppar里那个timestamp一样的。然后就只会消费这个时间之后的消息了。

**Comment by zydxhs** [comment]
下面的还是会返回一条数据。麻烦给个示例吧
```c++
WFKafkaClient client;
client.init(url, "test_group1");
auto task = client.create_kafka_task("api=fetch&topic=base_test", 3, kafka_callback);

KafkaConfig config;
config.set_client_id("workflow");
config.set_offset_store(0);

    using namespace std::chrono;
    auto now = system_clock::now().time_since_epoch();
    config.set_offset_timestamp(duration_cast<seconds>(now).count());

task->set_config(std::move(config));
task->start();
```

**Comment by Barenboim** [comment]
是我们代码里有个地方处理的不太好，一会我改一下。

**Comment by zydxhs** [comment]
好的。

**Comment by Barenboim** [comment]
这个修改可以。我们再看看有没有别的问题。

**Comment by Barenboim** [comment]
麻烦再试一下。

**Comment by zydxhs** [comment]
现在可以了。

**Comment by zydxhs** [comment]
顺便问下，#1038中提到的改进建议，有什么进展吗？

**Comment by Barenboim** [comment]
> 顺便问下，#1038 中提到的改进建议，有什么进展吗？

你要不试试写一版我们看看？kakfka client的作者太忙了，没时间搞。

**Comment by zydxhs** [comment]
已提交 #1044
