### ISSUE TITLE
使用user_data获取函数返回结果发生崩溃

### ISSUE THREAD

**Issue by cmoth150415** [sogou/workflow#1042]
我使用about-go-task.md中的例子，运行后在task->user_data = (void*)123;处崩溃，task是个无效地址，不知道是什么原因？

```		
WFGoTask* task = WFTaskFactory::create_go_task("test", [task]() {
			task->user_data = (void*)123;
			});

		WFFacilities::WaitGroup wait_group(1);
		task->set_callback([&wait_group](WFGoTask* task) {
			SeriesWork* series = series_of(task);
				void* context = series->get_context();
			if (task->get_state() == WFT_STATE_SUCCESS) // 成功执行完
			{
				int result = (int)task->user_data;
			}
			else // state == WFT_STATE_ABORTED.         // 超过运行时间限制
			{
			}
			wait_group.done();
			}
		);
		task->start();
		wait_group.wait();
```

**Comment by Barenboim** [comment]
你lambda的这个捕获不对的啊。这个时候task还没有值。用引用捕获吧。

**Comment by cmoth150415** [comment]
引用捕获可以了。主要之前没见过这样
WFGoTask* task = WFTaskFactory::create_go_task("test", [task]() {
			task->user_data = (void*)123;
			});
直接捕捉生成的变量的语法，网上也没搜到这样使用的解释，因为是指针，觉得值捕获似乎也可以。
感谢回复 ~\(≥▽≤)/~

**Comment by cmoth150415** [comment]
引用捕获可以了。主要之前没见过这样
WFGoTask* task = WFTaskFactory::create_go_task("test", [task]() {
			task->user_data = (void*)123;
			});
直接捕捉生成的变量的语法，网上也没搜到这样使用的解释，因为是指针，觉得值捕获似乎也可以。
感谢回复 ~\(≥▽≤)/~

**Comment by cmoth150415** [comment]
引用捕获可以了。主要之前没见过这样
WFGoTask* task = WFTaskFactory::create_go_task("test", [task]() {
			task->user_data = (void*)123;
			});
直接捕捉生成的变量的语法，网上也没搜到这样使用的解释，因为是指针，觉得值捕获似乎也可以。
感谢回复 ~\(≥▽≤)/~
