### ISSUE TITLE
请问有文件，比如图片传输的例子吗

### ISSUE THREAD

**Issue by DDGRCF** [sogou/workflow#1046]

**Comment by Barenboim** [comment]
能说一下具体需求吗？有一个文件服务器的示例。

**Comment by DDGRCF** [comment]
> 能说一下具体需求吗？有一个文件服务器的示例。
1. 这边的需求主要传输图片，视频等文件
2. 这边的初步构想是将以workflow构建的服务器，将文件转为字节流，传输给客服端

**Comment by Barenboim** [comment]
简单的文件传输，完整读完整个文件之后回复client，使用我们tutorial-09示例里的方法就可以了。当然，你也可以只读取部分的文件，使用http断点续传。
我们不太支持streaming方式的传输，server task支持同步的push数据，来实现一边读文件，一遍回复请求。

**Comment by DDGRCF** [comment]
> 简单的文件传输，完整读完整个文件之后回复client，使用我们tutorial-09示例里的方法就可以了。当然，你也可以只读取部分的文件，使用http断点续传。 我们不太支持streaming方式的传输，server task支持同步的push数据，来实现一边读文件，一边回复请求。

好的，谢谢
