### ISSUE TITLE
Sogou_Workflow failed to build with error LNK2038 , error LNK2005 with MSVC on Windows

### ISSUE THREAD

**Issue by nnfdnkns** [sogou/workflow#1047]
Hi all,
Sogou_Workflow failed to build on MSVC due to error LNK2038 , LNK2005. Could you please help look at this issue?

**Environment:**
Windows: windows server 2019
VS: 2019

**Repro steps:**
1.open VS2019 x64 tools command
2.git clone https://github.com/sogou/workflow F:\gitP\sogou\workflow\build_amd64
3.cd F:\gitP\sogou\workflow\build_amd64
4.cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DOPENSSL_ROOT_DIR=F:\tools\OpenSSL\64 -DCMAKE_BUILD_TYPE=Release .. 2>&1
5.msbuild /m /p:Platform=x64 /p:Configuration=Release workflow.sln /t:Rebuild 2>&1
6.cd F:\gitP\Microsoft\vcpkg
7.bootstrap-vcpkg.bat 2>&1
8.vcpkg.exe install --recurse gtest --triplet x64-windows --clean-after-build 2>&1
9.cd F:\gitP\sogou\workflow\test\build_amd64_test
10.cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DOPENSSL_ROOT_DIR=F:\tools\OpenSSL\64 .. 2>&1
11.msbuild /m /p:Platform=x64 /p:Configuration=Release workflow_test.sln /t:Rebuild 2>&1

**Error info:**
10>workflow.lib(Executor.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  151:     10>workflow.lib(SubTask.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  152:     10>workflow.lib(Workflow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  153:     10>workflow.lib(WFGlobal.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  154:     10>workflow.lib(thrdpool.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  155:     10>workflow.lib(WFDnsResolver.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  156:     10>workflow.lib(Communicator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  157:     10>workflow.lib(DnsUtil.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  158:     10>workflow.lib(RouteManager.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  159:     10>workflow.lib(WFResourcePool.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  160:     10>workflow.lib(WFNameService.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  161:     10>workflow.lib(WFDnsClient.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  162:     10>workflow.lib(DnsRoutine.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  163:     10>workflow.lib(DnsCache.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  164:     10>workflow.lib(WinPoller.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  165:     10>workflow.lib(CommScheduler.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  166:     10>workflow.lib(MD5Util.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  167:     10>workflow.lib(StringUtil.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  168:     10>workflow.lib(URIParser.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  169:     10>workflow.lib(DnsTaskImpl.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  170:     10>workflow.lib(CommRequest.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  171:     10>workflow.lib(DnsMessage.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  172:     10>workflow.lib(WFTaskFactory.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  173:     14>workflow.lib(Communicator.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  174:     14>workflow.lib(MySQLMessage.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  175:     14>workflow.lib(SubTask.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  176:     14>workflow.lib(CommRequest.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  177:     14>workflow.lib(Workflow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  178:     14>workflow.lib(WFGlobal.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  179:     14>workflow.lib(MySQLTaskImpl.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  180:     14>workflow.lib(WFServer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  181:     14>workflow.lib(WFMySQLServer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  182:     14>workflow.lib(thrdpool.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  183:     14>workflow.lib(WinPoller.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  184:     14>workflow.lib(MySQLResult.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  185:     14>workflow.lib(WFDnsResolver.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  186:     14>workflow.lib(DnsUtil.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  187:     14>workflow.lib(RouteManager.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  188:     14>workflow.lib(Executor.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  189:     14>workflow.lib(WFResourcePool.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  190:     14>workflow.lib(WFNameService.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  191:     14>workflow.lib(WFDnsClient.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  192:     14>workflow.lib(URIParser.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  193:     14>workflow.lib(SSLWrapper.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  194:     14>workflow.lib(WFTaskFactory.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  195:     14>workflow.lib(StringUtil.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  196:     14>workflow.lib(DnsRoutine.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  197:     14>workflow.lib(DnsCache.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  198:     14>workflow.lib(CommScheduler.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  199:     14>workflow.lib(MD5Util.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  200:     14>workflow.lib(DnsTaskImpl.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  201:     14>workflow.lib(DnsMessage.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  202:     10>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::~basic_streambuf<char,struct std::char_traits<char> >(void)" (??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  203:     10>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void)" (??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  204:     10>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  205:     10>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  206:     10>libcpmt.lib(locale0.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  207:     10>libcpmt.lib(locale0.obj) : error LNK2005: "void __cdecl std::_Facet_Register(class std::_Facet_base *)" (?_Facet_Register@std@@YAXPEAV_Facet_base@1@@Z) already defined in msvcprt.lib(locale0_implib.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  208:     10>libcpmt.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Getgloballocale(void)" (?_Getgloballocale@locale@std@@CAPEAV_Locimp@12@XZ) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  209:     10>libcpmt.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Init(bool)" (?_Init@locale@std@@CAPEAV_Locimp@12@_N@Z) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  210:     10>libcpmt.lib(locale0.obj) : error LNK2005: "public: static void __cdecl std::_Locinfo::_Locinfo_ctor(class std::_Locinfo *,char const *)" (?_Locinfo_ctor@_Locinfo@std@@SAXPEAV12@PEBD@Z) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  211:     10>libcpmt.lib(locale0.obj) : error LNK2005: "public: static void __cdecl std::_Locinfo::_Locinfo_dtor(class std::_Locinfo *)" (?_Locinfo_dtor@_Locinfo@std@@SAXPEAV12@@Z) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  212:     10>libcpmt.lib(cout.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  213:     14>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::~basic_streambuf<char,struct std::char_traits<char> >(void)" (??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  214:     14>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void)" (??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  215:     14>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  216:     14>msvcprt.lib(MSVCP140.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ) already defined in workflow.lib(WFGlobal.obj) [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  217:     10>libcpmt.lib(cout.obj) : error LNK2005: "protected: __cdecl std::basic_ios<char,struct std::char_traits<char> >::basic_ios<char,struct std::char_traits<char> >(void)" (??0?$basic_ios@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  218:     10>libcpmt.lib(cout.obj) : error LNK2005: "protected: __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::basic_streambuf<char,struct std::char_traits<char> >(void)" (??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  219:     10>libcpmt.lib(cout.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  220:     10>libcpmt.lib(cout.obj) : error LNK2005: "public: void __cdecl std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool)" (?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  221:     10>libcpmt.lib(locale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in algo_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  222:     14>libcpmt.lib(locale0.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in mysql_unittest.obj [F:\gitP\sogou\workflow\test\build_amd64_test\mysql_unittest.vcxproj]
	Line  223:     10>libcpmt.lib(locale.obj) : error LNK2005: "public: struct _Cvtvec __cdecl std::_Locinfo::_Getcvt(void)const " (?_Getcvt@_Locinfo@std@@QEBA?AU_Cvtvec@@XZ) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  224:     10>libcpmt.lib(locale.obj) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]
	Line  225:     10>libcpmt.lib(locale.obj) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in msvcprt.lib(MSVCP140.dll) [F:\gitP\sogou\workflow\test\build_amd64_test\algo_unittest.vcxproj]

**logs:**

[build (2).log](https://github.com/sogou/workflow/files/9580318/build.2.log)

**Comment by Barenboim** [comment]
Hi. Did you checkout the 'windows' branch?

**Comment by nnfdnkns** [comment]
Yes,I checkout the 'windows' branch. I re-edited my issue, and failed on this command:msbuild /m /p:Platform=x64 /p:Configuration=Release workflow_test.sln /t:Rebuild 2>&1

**Comment by Barenboim** [comment]
I am sorry I know little about compiling on Windows platform. Maybe you can follow the instructions of the 'windows' branch readme: https://github.com/sogou/workflow/tree/windows

**Comment by holmes1412** [comment]
It seems to be compiling the test directory. We asked other friends who use windows, maybe because the lib is compiled with "MT", but the compile option of test directory is not specified, so it is compiled with "MD" by default.

I tried adding the MT option in the Cmake files of the test. 
https://github.com/holmes1412/workflow-major/tree/windows

 Could you help us try this source code and check if it works?

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1052
@nnfdnkns
