### ISSUE TITLE
C和C++混合代码风格

### ISSUE THREAD

**Issue by darionyaphet** [sogou/workflow#1051]
如题，简单学习了一下代码，感觉有些是C和C++混合编写的，为什么不统一成C++呢？谢谢

**Comment by Barenboim** [comment]
感谢关注。
我们尽量都是C语言。很大模块都是可以独立使用的。比如json-parser，线程池，消息队列这些我都做成独立项目，放在我自己空间。改成C++反而降低复用的场合。
项目只利用了C++少量特征。kernel目录下的C++其实是c with class，为了使用虚函数。用户接口上，用了少量C++11，例如std::function。
我们侧重于解决问题，没有统一成C++的需求，也尽可能的少使用过多的C++新特征。

**Comment by darionyaphet** [comment]
明白了，感谢谢爷的回复~

**Comment by holmes1412** [comment]
@darionyaphet 光光好呀~ 后续随时联系我们交流~ 学习之余记得支持前司的项目点个star哈~
