### ISSUE TITLE
关于执行sql，程序崩溃【很奇怪】的问题，求助！

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1055]
1. 项目之前编译没问题，访问mysql数据库都能获取到数据。
2. 最近不知道增加了什么原因，重新编译后，访问数据库会崩溃。
3. 定位到代码的代码是：
  mysql_parser.h中的mysql_result_set_cursor_next函数中的list_entry()这行代码。
  执行完list_entry()后，只要使用result_set这个指针指向的数据，程序就会崩溃。测试了赋值或者读取程序都会崩溃。
4. 使用项目里的tutori中的mysql_cli可以正常返回数据！！
5. 排查了两天，不知道是什么原因，希望能帮忙解答！！【用之前编译出来的执行文件是正常的，能正确读取数据】
6. 是编译选项项的问题吗？？我使用的是boost的编译文件，不是cmake的。

**Comment by holmes1412** [comment]
你好，如果可以使用固定的sql语句来定位到“最近编译”的版本有问题，而“tutorial里的mysql
_cli”没问题的话，建议还是定位一下编译方式和第1点提到的“之前编译”的那版，对比下编译和链接的区别。

可能性有很多，比如是不是还链接了以前的库或者编译与运行时的头文件不匹配之类。

挂的话可以看看具体是操作到result_set里的哪个域，方便定位问题。

**Comment by vincentqin-sys** [comment]
> 你好，如果可以使用固定的sql语句来定位到“最近编译”的版本有问题，而“tutorial里的mysql _cli”没问题的话，建议还是定位一下编译方式和第1点提到的“之前编译”的那版，对比下编译和链接的区别。
> 
> 可能性有很多，比如是不是还链接了以前的库或者编译与运行时的头文件不匹配之类。
> 
> 挂的话可以看看具体是操作到result_set里的哪个域，方便定位问题。

我回退到之前版本，还是有问题。。。这很奇怪。。。

**Comment by holmes1412** [comment]
那是不是环境的问题？可以换个环境重新编吗

**Comment by vincentqin-sys** [comment]
我把turorial里面的mysql_cli用我的编译文件来编译，出来的程序也会崩溃。。我看编译workflow，有个报警和这里有关。
/workflow/src/protocol/MySQLResult.cc:149:39: warning: ‘result_set’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     this->fetch_result_set(result_set);

 找不到问题呀。。

**Comment by Barenboim** [comment]
> 我把turorial里面的mysql_cli用我的编译文件来编译，出来的程序也会崩溃。。我看编译workflow，有个报警和这里有关。 /workflow/src/protocol/MySQLResult.cc:149:39: warning: ‘result_set’ may be used uninitialized in this function [-Wmaybe-uninitialized] this->fetch_result_set(result_set);
> 
> 找不到问题呀。。

这个warning不用管，有些编译器的问题。

**Comment by Barenboim** [comment]
如果能用tutorial里的代码复现，就好办了啊。你用gdb跟一下吧，或者你把你的makefile什么发一下。

**Comment by vincentqin-sys** [comment]
我的是用boost的那套make。所以很难对比。。目前感觉是编译选项的问题。tutorial是静态编译还是动态呀？我ldd看两边编译出来的执行文件，都是一样的。
 我的jamfile.v2是这样
import path ;
import project ;
path-constant CWD : . ;
constant TARGET_NAME : mysql_cli ;

project
    ;

dependencies =
    /3rd_libs/workflow
    ;

exe $(TARGET_NAME)
      : [ glob src/*.cc ]
        $(dependencies)
      : # requirements
        <link>shared:<linkflags>"-Wl,-Bdynamic -lssl"
        <link>shared:<linkflags>"-Wl,-Bdynamic -lcrypto"
      :
      ;

jameroot里我参照了tutorial里的加了下面的编译选项
    <toolset>gcc:<cxxflags>-Wno-deprecated-declarations
    <toolset>gcc:<cxxflags>-g
    <toolset>gcc:<cxxflags>-Wall
    <toolset>gcc:<cxxflags>-fPIC
    <toolset>gcc:<cxxflags>-pipe
    <toolset>gcc:<cxxflags>-std=nu++11
    <toolset>gcc:<cxxflags>-fno-exceptions
    <toolset>gcc:<cxxflags>-Wno-invalid-offsetof
    <toolset>gcc:<cxxflags>-Werror=return-type
    <toolset>gcc:<cxxflags>-Wno-deprecated-declarations
    <toolset>gcc:<cxxflags>-Wno-unused
    <toolset>gcc,<variant>debug:<cxxflags>--coverage
    <toolset>gcc,<variant>debug:<linkflags>--coverage

**Comment by vincentqin-sys** [comment]
void MySQLResultCursor::init(const MySQLResponse *resp) {
.....
  fprintf(stderr, "init 1.2 %ld\n", &this->parser);
  fprintf(stderr, "init 1.3 %ld\n", &this->parser->result_set_list);
  fprintf(stderr, "init 1.3 %ld\n", (&this->parser->result_set_list)->next); //在这里list_empty里面崩溃，我拿到外面打印next，就在这崩溃。
  if (!list_empty(&this->parser->result_set_list)) {
    ....
  }

#崩溃程序的输出
init 1.2 140557809146832
init 1.3 80
Segmentation fault
#正常程序的输出
init 1.2 140351247256672
init 1.3 20065264
init 1.3 140350874194240

**Comment by vincentqin-sys** [comment]
搞定了。编译器版本的问题。。。狂汗。低级错误。。我系统有两套编译版本，gcc是8.3的，c++是4.8的。makefile出来的命令是c++， 我boost出来的是gcc。哎。。。浪费时间。
