### ISSUE TITLE
windows的分支怎么不使用ssl或者把ssl的lib打包进我的dll里

### ISSUE THREAD

**Issue by fysmart** [sogou/workflow#1057]
目前项目用不到ssl请求，也不想打包`libssl-3.dll`和`libcrypto-3.dll`文件，只想用一个单DLL。
我测试了将依赖的lib改成`\OpenSSL-Win32\lib\VC\static` 内`MT`的DLL，然后无法生成。
测试了nossl分支，在windows下用cmake无法编译。。
有什么解决办法呢？
nossl分支cmake提示错误：
![MK$6Z5}4WM X(T~X}W2{S(R](https://user-images.githubusercontent.com/17706457/192734257-d31b6238-44a9-4b88-822d-fae52bccb5fc.png)

**Comment by Barenboim** [comment]
你好，nossl分支只支持Unix系统，不支持Windows
Windows没有无ssl的实现。要剥离的话，可能需要改不少代码。

**Comment by Barenboim** [comment]
而且，nossl分支，其实也需要链libcrypto的😂

**Comment by fysmart** [comment]
> 

了解了解，谢啦
