### ISSUE TITLE
WF DAG能否实现视频结构化类的应用？

### ISSUE THREAD

**Issue by chris78l** [sogou/workflow#1059]
看到WF支持DAG吗，串并联。请问怎么使用WF来实现视频结构化类或者多媒体类的应用？比如：
     video capture ---> crop-resize-convert---> inference --> osd- > video output
      video streaming-> video decode -> video output
 暂不考虑 batch inference。 
 
 pipeline的每一个stage都可以并发执行。 video capture 按照固定频率比如30fps连续获取输入。
 
 初识Workflow，初步看了tutorial，还没有get到怎么处理连续的输入。

**Comment by Barenboim** [comment]
很有意思的一个问题。
是不是说每一个步骤都是一个时间比较长的计算，但只要产生一小块结果，立刻可以作为下一步的输入被执行？所有的步骤都可以并发。
我想一想怎么实现这个功能比较优雅。

**Comment by chris78l** [comment]
上面说的两个例子，写的pipeline是线性的，也有处理场景是非线性的（DAG）
是，管道和过滤器模式的应用。找到了下面的链接，
https://iambowen.gitbooks.io/cloud-design-pattern/content/patterns/pipes-and-filters.html
关于视频结构化或者多媒体类的两个著名的开源是gstreamer 和mediapipe。这两个都比较重。
看好Workflow能实现类似框架。

**Comment by Barenboim** [comment]
我感觉可以转化为一个生产者消费者问题，我之前曾经发过一个discussion，描述这样一个用法：
https://github.com/sogou/workflow/discussions/876
每个后继任务都可以看成消费者，会在某一个topic上等待。当得到一个消息，就开始进行计算（也可以是通信，取决于消费者是什么任务）并把结果写入下一个topic。用法大概这样：
~~~cpp
WFMessageQueue mq;

void func_video_capture(void **input_buf)
{
    void *output_block;
    // do capture
    // ...
    mq.produce("crop-resize-convert", output_block);
    WFGoTask *task = WFTaskFactory::create_to_task("capture", func_video_capture, input_buf);
    WFConditional *cond = mq.consume("video-capture", input_buf);
    cond->start();
}

void func_crop_resize_convert()
{
     ...
}

int main()
{
    void **input_buf = malloc(sizeof (void **));
    WFGoTask *task = WFTaskFactory::create_to_task("capture", func_video_capture, input);
    WFConditional *cond = mq.consume("video-capture", input);
    cond->start();
    ....
    input_buf = malloc(sizeof (void **));
    WFGoTask *task = WFTaskFactory::create_to_task("resize", func_crop_resize_convert, input);
    cond = mq.consume("video-capture", input);
    cond->start();
    ....
}
~~~
如果你不熟悉workflow里的条件任务用法，你可能不太能理解我上面这个写法。我先解释一下。
你说的pipeline的方法，无论如何我们都需要用等待与唤醒机制。以inference为例如，如果inference是一个函数，那么，函数里必然需要有类似于pthread_cond_wait的代码来等待上游的数据输入。但这样的缺点是，有一个计算线程被占用，在执行等待。这在workflow里是非常不推荐的。
workflow里的等待，是指一个任务在满足某个条件下，被执行。通过这个方法，我们可以很方便的实现无堵塞的资源池，消息队列等。所以，在这个用法下，流水线的每个步骤不再是一次函数的执行，而是多次执行，每次执行处理一小块数据。我们可以通过消息队列的方式，来传递数据。
消息队列这个我还没有实现，你可以先看看我们里面条件任务的几个组件，包括了资源池，观察者等：
https://github.com/sogou/workflow/blob/master/docs/about-conditional.md
https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md

**Comment by chris78l** [comment]
感谢回复。有几个地方我还没有想明白：
（1）如何进行连续capture： 通过连续创建 WFGoTask？
（2）如何处理非线性的pipeline（像DAG这种形态的）：
         a. 下游stages有多个:   cond broadcast？
         b. 需要汇聚多个stages的处理结果来进行下一步的处理:   barrier？ WF counter实际上就是barrier？
（3）build pipeline(graph)的过程怎么做更加优雅？

**Comment by Barenboim** [comment]
现在很多东西还没有设计好。实现方式上，肯定是WFConditional，和WFCounterTask这些组件来实现依赖关系。
你的第一个问题，如果连续capture。普通非workflow的方法，肯定就是一个循环，我相信大概是这样：
~~~cpp
void capture()
{
    while (1) {
        wait_input();
        if (end)
            break;

        do_capture();
    }
}
~~~
这是一个循环结构。workflow里，我们没有循环，而是递归：
~~~cpp
void capture()
{
    if (end)
        return;

    do_capture();

    WFGoTask *next = WFTaskFactory::create_go_task("any name", capture);
    WFConditional *cond = WFTaskFactory::create_conditional(next);
    cond->start();
}

int main()
{
    WFGoTask *task = WFTaskFactory::create_go_task("any name", capture);
    WFConditional *cond = WFTaskFactory::create_conditional(next);
    cond->start();
    ...
}
~~~
这里的cond其实就是workflow里用于异步等待的组件。当条件成立，其包装的任务被执行。cond不一定是从WFTaskFactory产生，也可以通过消息队列，资源池来产生。这个代码第一种写法的区别是，等待的过程不占用线程，而且，只要你启动多个task，就是并行处理了。
当然，这段代码更好一点的写法是在任务的callback里，push_back下一个任务，这样可以让所有任务运行在同一个series里：
~~~cpp
void capture()
{
    do_capture();
}

void capure_callback(WFGoTask *task)
{
    if (end)
        return;

    WFGoTask *next = WFTaskFactory::create_go_task("any name", capture);
    WFConditional *cond = WFTaskFactory::create_conditional(next);
    series_of(task)->push_back(cond);   
}

int main()
{
    WFGoTask *task = WFTaskFactory::create_go_task("any name", capture);
    task->set_callback(capture_callback);
    WFConditional *cond = WFTaskFactory::create_conditional(task);
    cond->start();
    ...
}
~~~
我目前的想法写一个和WFResoucePool类似的WFMessageQueue组件来实现息队列，通过消息传递就已经可以实现你需要的功能了。在这个基础上，再考虑如何更加方便的建图。

**Comment by MaybeShewill-CV** [comment]
我之前做的一个类似的pipeline的工作就是在上一个任务的callback里push back下一个任务，虽然遵循了wf的推荐写法，但是如果这个pipeline稍微一长再加上callback函数如果稍微长点，整个代码的结构就不是特别清晰明，需要把每个callback函数都看完才能知道完整的pipeline结构。

**Comment by MaybeShewill-CV** [comment]
> 我感觉可以转化为一个生产者消费者问题，我之前曾经发过一个discussion，描述这样一个用法： #876 每个后继任务都可以看成消费者，会在某一个topic上等待。当得到一个消息，就开始进行计算（也可以是通信，取决于消费者是什么任务）并把结果写入下一个topic。用法大概这样：
> 
> ```c++
> WFMessageQueue mq;
> 
> void func_video_capture(void **input_buf)
> {
>     void *output_block;
>     // do capture
>     // ...
>     mq.produce("crop-resize-convert", output_block);
>     WFGoTask *task = WFTaskFactory::create_to_task("capture", func_video_capture, input_buf);
>     WFConditional *cond = mq.consume("video-capture", task, input_buf);
>     cond->start();
> }
> 
> void func_crop_resize_convert()
> {
>      ...
> }
> 
> int main()
> {
>     void **input_buf = malloc(sizeof (void **));
>     WFGoTask *task = WFTaskFactory::create_to_task("capture", func_video_capture, input_buf);
>     WFConditional *cond = mq.consume("video-capture", task, input_buf);
>     cond->start();
>     ....
>     input_buf = malloc(sizeof (void **));
>     task = WFTaskFactory::create_to_task("resize", func_crop_resize_convert, input_buf);
>     cond = mq.consume("video-capture", task, input_buf);
>     cond->start();
>     ....
> }
> ```
> 
> 如果你不熟悉workflow里的条件任务用法，你可能不太能理解我上面这个写法。我先解释一下。 你说的pipeline的方法，无论如何我们都需要某种等待与唤醒机制。以inference为例如，如果inference是一个函数，那么，函数里必然需要有类似于pthread_cond_wait的代码来等待上游的数据输入。但这样的缺点是，有一个计算线程被占用，在执行等待。这在workflow里是非常不推荐的。 workflow里的等待，是指一个任务在满足某个条件下，被执行。通过这个方法，我们可以很方便的实现无堵塞的资源池，消息队列等。所以，在这个用法下，流水线的每个步骤不再是一次函数的执行，而是多次执行，每次执行处理一小块数据。我们可以通过消息队列的方式，来传递数据。 消息队列这个我还没有实现，你可以先看看我们里面条件任务的几个组件，包括了资源池，观察者等： https://github.com/sogou/workflow/blob/master/docs/about-conditional.md https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md

这个模式是目前wf已经具备的功能嘛 感觉这样的写法比在callback函数里不断push新任务进去更清晰

**Comment by Barenboim** [comment]
WFMessageQueue还没有。而且，目前的想法，message queue的设计可能也和这个不太一样。
WFMessageQueue最终可能和WFResourcePool类似。然后外面再封闭一层带topic name查找的。

> > 我感觉可以转化为一个生产者消费者问题，我之前曾经发过一个discussion，描述这样一个用法： #876 每个后继任务都可以看成消费者，会在某一个topic上等待。当得到一个消息，就开始进行计算（也可以是通信，取决于消费者是什么任务）并把结果写入下一个topic。用法大概这样：
> > ```c++
> > WFMessageQueue mq;
> > 
> > void func_video_capture(void **input_buf)
> > {
> >     void *output_block;
> >     // do capture
> >     // ...
> >     mq.produce("crop-resize-convert", output_block);
> >     WFGoTask *task = WFTaskFactory::create_to_task("capture", func_video_capture, input_buf);
> >     WFConditional *cond = mq.consume("video-capture", task, input_buf);
> >     cond->start();
> > }
> > 
> > void func_crop_resize_convert()
> > {
> >      ...
> > }
> > 
> > int main()
> > {
> >     void **input_buf = malloc(sizeof (void **));
> >     WFGoTask *task = WFTaskFactory::create_to_task("capture", func_video_capture, input_buf);
> >     WFConditional *cond = mq.consume("video-capture", task, input_buf);
> >     cond->start();
> >     ....
> >     input_buf = malloc(sizeof (void **));
> >     task = WFTaskFactory::create_to_task("resize", func_crop_resize_convert, input_buf);
> >     cond = mq.consume("video-capture", task, input_buf);
> >     cond->start();
> >     ....
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果你不熟悉workflow里的条件任务用法，你可能不太能理解我上面这个写法。我先解释一下。 你说的pipeline的方法，无论如何我们都需要某种等待与唤醒机制。以inference为例如，如果inference是一个函数，那么，函数里必然需要有类似于pthread_cond_wait的代码来等待上游的数据输入。但这样的缺点是，有一个计算线程被占用，在执行等待。这在workflow里是非常不推荐的。 workflow里的等待，是指一个任务在满足某个条件下，被执行。通过这个方法，我们可以很方便的实现无堵塞的资源池，消息队列等。所以，在这个用法下，流水线的每个步骤不再是一次函数的执行，而是多次执行，每次执行处理一小块数据。我们可以通过消息队列的方式，来传递数据。 消息队列这个我还没有实现，你可以先看看我们里面条件任务的几个组件，包括了资源池，观察者等： https://github.com/sogou/workflow/blob/master/docs/about-conditional.md https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md
> 
> 这个模式是目前wf已经具备的功能嘛 感觉这样的写法比在callback函数里不断push新任务进去更清晰

**Comment by Barenboim** [comment]
@MaybeShewill-CV 
可以看看这个实现：https://github.com/sogou/workflow/pull/1064/files

**Comment by MaybeShewill-CV** [comment]
@Barenboim 好的 我先研究下 感谢:)

**Comment by Barenboim** [comment]
我重新思考了这个issue的需求，也看了关于pipeline+filter的设计模式。但好像这个问题对我们来讲并没有那么复杂。我们的处理方法更加简单直接，就是每拿到一块input就创建一个series处理，series里依次运行各个阶段的任务就可以了。
如果有并行需求，可以添加ParallelWork或MultiThreadTask。DAG关系任务，就构造graph task。
我们并不需要用filter的模式设计各级流水线，因为所有计算任务其实共享一个计算线程池，底层会有调度的逻辑，用户只需要拿到input之后编排任务就可以了。
会有这样的区别是因为workflow本质上并不是数据驱动的。数据驱动的方式往往是在线程上等待数据，然后直接在线程上计算，分发。习惯了数据驱动方式，不太好理解workflow。
workflow是任务驱动的，任何时候有数据需要处理就创建计算任务就可以了，一切都是主动的行为。计算任务在底层会再经过一次调度。关于计算调度的逻辑，你可以参考一下相关的文档。
回到你这个例子，其实我上面的示例写得太复杂了。其实就是一个简单的串行执行计算任务。调度相关的，交给底层。

**Comment by Barenboim** [comment]
@chris78l
@MaybeShewill-CV

**Comment by chris78l** [comment]
@Barenboim  感谢，我再研究学习一下。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 好的哈 我再看看。之前我这边的任务流都是用condition task来实现流程控制

**Comment by chris78l** [comment]
@Barenboim 还有个问题，为啥只有WFGoTask的func时不带WFGoTask参数的？task->user_data 怎么再GoTask func中获取呢？

**Comment by Barenboim** [comment]
@chris78l
这个问题有人提过，就是要在go task的函数里捕获task本身。可以这么做：
~~~cpp
WFGoTask *task = WFTaskFactory::create_go_task("test", nullptr);
WFTaskFactory::reset_go_task([task](int){ ... }, ...);
~~~

**Comment by chris78l** [comment]
> @chris78l 这个问题有人提过，就是要在go task的函数里捕获task本身。可以这么做：
> 
> ```c++
> WFGoTask *task = WFTaskFactory::create_go_task("test", nullptr);
> WFTaskFactory::reset_go_task([task](int){ ... }, ...);
> ```

感谢

**Comment by chris78l** [comment]
> 我重新思考了这个issue的需求，也看了关于pipeline+filter的设计模式。但好像这个问题对我们来讲并没有那么复杂。我们的处理方法更加简单直接，就是每拿到一块input就创建一个series处理，series里依次运行各个阶段的任务就可以了。 如果有并行需求，可以添加ParallelWork或MultiThreadTask。DAG关系任务，就构造graph task。 我们并不需要用filter的模式设计各级流水线，因为所有计算任务其实共享一个计算线程池，底层会有调度的逻辑，用户只需要拿到input之后编排任务就可以了。 会有这样的区别是因为workflow本质上并不是数据驱动的。数据驱动的方式往往是在线程上等待数据，然后直接在线程上计算，分发。习惯了数据驱动方式，不太好理解workflow。 workflow是任务驱动的，任何时候有数据需要处理就创建计算任务就可以了，一切都是主动的行为。计算任务在底层会再经过一次调度。关于计算调度的逻辑，你可以参考一下相关的文档。 回到你这个例子，其实我上面的示例写得太复杂了。其实就是一个简单的串行执行计算任务。调度相关的，交给底层。

-----------------------------------
对stream的情况，input持续不断的来， 每拿到一块input创建一个series，意味着多个series同时存在。每个series执行完毕才能释放资源，关于series的释放管理，有什么推荐的实现方式吗？ @Barenboim

**Comment by Barenboim** [comment]
这个没关系的，创建多少series都可以，就是一小块内存。

**Comment by Barenboim** [comment]
你可以把我们的series理解成一个协程。完全不占资源。

**Comment by chris78l** [comment]
@Barenboim  感谢大佬回复
请帮忙看看，每次input到来时，都创建series，下面的代码逻辑是否正确？
退出的时候还是需要等待series执行全部结束，否则会出现segment fault。

        std::atomic<int> count_input{0};
	std::atomic<int> count_output{0};
	
	for(int i = 0; i < MAX_COUNT; i ++) {
		usleep(1000 * 10);
		// data arrived, create series for each input frame	
		WFGoTask *go_task0 = WFTaskFactory::create_go_task("go0", nullptr);
		WFTaskFactory::reset_go_task(go_task0, [&go_task0, i]() {
			printf("Go Task0, id = %d\n", i);
			usleep(1000 * 10);
		});

		WFGoTask *go_task1 = WFTaskFactory::create_go_task("go1", nullptr);
		go_task1->user_data = &size1;
		WFTaskFactory::reset_go_task(go_task1, [&go_task1, i]() {
			printf("Go Task1, id = %d\n", i);
			size_t *size = (size_t *)go_task1->user_data;
			*size = 1000;
			usleep(1000 * 33);
		});
		
		WFGoTask *go_task2 = WFTaskFactory::create_go_task("go2", nullptr);
		go_task2->user_data = &size2;
		WFTaskFactory::reset_go_task(go_task2, [&go_task2, i]() {
			printf("Go Task2, id = %d\n", i);
			size_t *size = (size_t *)go_task2->user_data;
			*size = 1001;
			usleep(1000 * 33);
		});

		WFGoTask *go_task = WFTaskFactory::create_go_task("go", go_func, &size1, &size2);
		/* Create a graph. Graph is also a kind of task */
		WFGraphTask *graph = WFTaskFactory::create_graph_task([&count_output](WFGraphTask *) {
			printf("Graph task complete. Wakeup main process, id = %d\n", count_output.load());
			++count_output;
			usleep(1000 * 10);
		});

		/* Create graph nodes */
		WFGraphNode& a = graph->create_graph_node(go_task0);
		WFGraphNode& b = graph->create_graph_node(go_task1);
		WFGraphNode& c = graph->create_graph_node(go_task2);
		WFGraphNode& d = graph->create_graph_node(go_task);
		/* Build the graph */
		a-->b;  a-->c;  b-->d;  c-->d;
		
		if (count_output > 10) break;  // early exit
	
		++count_input;
		graph->start();
	}
	/* Wait for all tasks finished */
	while(count_input != count_output) usleep(1000 * 10);
	printf("****************count = %d\n", count_output.load());

**Comment by Barenboim** [comment]
代码应该可以执行的吧。不过，你中间break出来那里，没有把graph task释放，会内存泄漏。不运行的task，需要调用task->dismiss()函数把它释放一下。你直接调graph->dismiss()就可以把整个图清了。
程序退出，需要等任务都结束的。

**Comment by chris78l** [comment]
可以运行，感谢大佬

**Comment by Barenboim** [comment]
BTW，我看到你在rest_rpc问uds的问题。我们是支持的噢。你可以看一下tutorial-10，里面有uds的示例。
@chris78l

**Comment by chris78l** [comment]
好的，谢谢
