### ISSUE TITLE
workflow的定位和竞品是什么？

### ISSUE THREAD

**Issue by qinguoyi** [sogou/workflow#1061]
rt. 看了下wf的简介和资料，定位是C++服务 "引擎"，感觉wf里面的东西非常多，像是Web(HTTP) Server + Web FrameWork + Async Task FrameWork糅杂的应用服务器，又好像不是这样。

请教下，wf的定位和竞品具体是什么？

**Comment by Barenboim** [comment]
你好啊，开源圈大佬。
workflow是以服务器引擎开发，但逐渐演化成一套基于C++11子集的独立编程范式。
你看到我们内容很多，是因为我们需要在这个编程范式上实现我们自己的组件和协议库。比如dns协议，如果我们不自己实现，并不能和我们的框架很好的融合。
像MySQL，Kafka这些，我们需要实现基于我们自己任务模型的客户端，才能让用户用起来最高效最自然。所有网络任务都共享同一个通讯引擎。
我们没有竞品哈。基于workflow的srpc，wfrest这些，才有竞品。

**Comment by qinguoyi** [comment]
> 你好啊，开源圈大佬。 workflow是以服务器引擎开发，但逐渐演化成一套基于C++11子集的独立编程范式。 你看到我们内容很多，是因为我们需要在这个编程范式上实现我们自己的组件和协议库。比如dns协议，如果我们不自己实现，并不能和我们的框架很好的融合。 像MySQL，Kafka这些，我们需要实现基于我们自己任务模型的客户端，才能让用户用起来最高效最自然。所有网络任务都共享同一个通讯引擎。 我们没有竞品哈。基于workflow的srpc，wfrest这些，才有竞品。

感谢大佬回复，看wf学到了不少东西^_^.
