### ISSUE TITLE
workflow中的graph任务，启动后如果中途想退出，不再执行后续的graph node，如何做到？

### ISSUE THREAD

**Issue by ypyaaa** [sogou/workflow#1065]
workflow中的graph任务，启动后如果中途想退出，不再执行后续的graph node，如何做到？

**Comment by Barenboim** [comment]
Graph task应该是不能中途取消的，也不能中途改变图结构。如果有一些节点不能确定要运行，你可以用动态任务创建节点。
~~~cpp
SubTask *create(WFDynamicTask *task)
{
    if (...)
        return WFTaskFactory::create_http_task(...);
    else
        return WFTaskFactory::create_empty_task(...);
}

int main()
{
    WFDynamicTask *task = WFTaskFactory::create_dynamic_task(create);
    WFGraphNode& node = graph->create_graph_node(task);
    ....
}
~~~
动态任务的行为是运行是调用create来产生实现的任务。如果一个节点无需运行，你可以直接产生一个empty task。注意create不能返回NULL。

**Comment by ypyaaa** [comment]
> Graph task应该是不能中途取消的，也不能中途改变图结构。如果有一些节点不能确定要运行，你可以用动态任务创建节点。
> 
> ```c++
> SubTask *create(WFDynamicTask *task)
> {
>     if (...)
>         return WFTaskFactory::create_http_task(...);
>     else
>         return WFTaskFactory::create_empty_task(...);
> }
> 
> int main()
> {
>     WFDynamicTask *task = WFTaskFactory::create_dynamic_task(create);
>     WFGraphNode& node = graph->create_graph_node(task);
>     ....
> }
> ```
> 
> 动态任务的行为是运行是调用create来产生实现的任务。如果一个节点无需运行，你可以直接产生一个empty task。注意create不能返回NULL。

图任务中的节点在其前置任务不满足时会等待，如何在其开始执行时得到通知？ 麻烦问下这个问题有答案吗

**Comment by holmes1412** [comment]
@ypyaaa 目前框架里没有这样的通知机制，只能在节点开始执行时，你的代码里自己感知～

**Comment by Barenboim** [comment]
> > Graph task应该是不能中途取消的，也不能中途改变图结构。如果有一些节点不能确定要运行，你可以用动态任务创建节点。
> > ```c++
> > SubTask *create(WFDynamicTask *task)
> > {
> >     if (...)
> >         return WFTaskFactory::create_http_task(...);
> >     else
> >         return WFTaskFactory::create_empty_task(...);
> > }
> > 
> > int main()
> > {
> >     WFDynamicTask *task = WFTaskFactory::create_dynamic_task(create);
> >     WFGraphNode& node = graph->create_graph_node(task);
> >     ....
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 动态任务的行为是运行是调用create来产生实现的任务。如果一个节点无需运行，你可以直接产生一个empty task。注意create不能返回NULL。
> 
> 图任务中的节点在其前置任务不满足时会等待，如何在其开始执行时得到通知？ 麻烦问下这个问题有答案吗

这个dynamic task的create不就相当于通知么？

**Comment by Barenboim** [comment]
@ypyaaa

**Comment by ma-zhiqiang** [comment]
create_empty_task 这个空任务没有回调吗，但是会执行它？

**Comment by Barenboim** [comment]
没有回调。就是什么行为也没有的任务。
