### ISSUE TITLE
流媒体传输的支持

### ISSUE THREAD

**Issue by zhngs** [sogou/workflow#1067]
请问workflow有支持像流媒体传输这种长连接的规划吗，而不是像http这种请求响应式的模型，如果可以支持，那么以workflow为底层网络库的流媒体server的构建将成为可能，这是一项令人期待的特性！

**Comment by zhngs** [comment]
单纯的webrtc sfu server只需要一个udp socket即可，但是业务有可能会调用其他的异步操作如非阻塞的dns请求，rpc请求等，我对workflow尚未完全熟悉，如果workflow能将长连接完美融合进去，将会带来很大便利

**Comment by Barenboim** [comment]
如果你只要一个udp socket，好像这个不太需要workflow里那么复杂的通讯引擎。udp有个好处，是不用考虑异步的写。你可以有自己的通信模块，然后可以很方便的包装成workflow里的一个任务。
非阻塞dns，rpc这些workflow里都是提供的。非阻塞dns你可以看看这个文档：
https://github.com/sogou/workflow/blob/master/docs/tutorial-17-dns_cli.md

**Comment by zhngs** [comment]
十分感谢！
