### ISSUE TITLE
链接低版本的 OpenSSL 的疑问

### ISSUE THREAD

**Issue by tianlong-xiang** [sogou/workflow#1069]
资料里面提到：OpenSSL 1.1 and above is recommended

有项目使用 OpenSSL 1.0.2，workflow 切换到此版本，测试了 https 下面的 post get 请求，都正常

是不是没有发现异常的情况，切换到低版本也是可行的？

**Comment by Barenboim** [comment]
OpenSSl 1.0的没问题，完全兼容。和1.1的区别只在于性能上。
