### ISSUE TITLE
httptask无法进入回调

### ISSUE THREAD

**Issue by guochaopeng** [sogou/workflow#1072]
多个线程里使用httptask会出现task无法进入回调函数中，或者说是不是任务没有启动，因为对方没有收到请求,请问怎么解决?
			//http请求任务;
			auto callback_http = std::bind(&WCSBDHttpTaskCallback::operator(), WCSTaskEntryManage::GetBDHttpTaskCallback(), std::placeholders::_1);
			WCSTaskFactory::WCSBDHttpTask* http_task = WCSTaskFactory::create_bdhttp_task(strurl, 4, 3, callback_http);
			http_task->user_data = WCSTaskEntryManage::GetBDHttpTaskUserData();
			
			protocol::HttpRequest* request = http_task->get_req();
			request->set_method("POST");
			request->set_header_pair("Content-Type", "application/json;charset=UTF-8");
			request->set_header_pair("Accept", "*/*");
			request->set_header_pair("privatekey", strprivatekey);
			request->append_output_body(jbody.dump());

			series_of(task)->push_back(http_task);

**Comment by Barenboim** [comment]
是不是你程序退出了？

**Comment by Barenboim** [comment]
能不能贴一下完整的程序？

**Comment by Barenboim** [comment]
@guochaopeng

**Comment by guochaopeng** [comment]
不好意思，是有进入回调，只是等待的时间会很长，有10s以上的时间才进入回调

**Comment by Barenboim** [comment]
10s以上才回调，结果是成功还是超时？

**Comment by Barenboim** [comment]
不好意思，前几天没看到回复。
我们的connect timeout和receive timeout默认都是10秒。你可以通过global settings修改connect timeout，也可以通过task->set_receive_timeout()修改receive timeout。

**Comment by hnlicong** [comment]
请问一下global settings该如何设置呢，我只看到了get的方法，在【WFGlobal::get_global_settings()->endpoint_params】，我该如何修改呢

**Comment by Barenboim** [comment]
> 请问一下global settings该如何设置呢，我只看到了get的方法，在【WFGlobal::get_global_settings()->endpoint_params】，我该如何修改呢

WORKFLOW_library_init()这个函数。关于全局配置，你可以看一下文档。
