### ISSUE TITLE
高并发推理服务器架构

### ISSUE THREAD

**Issue by xialuxi** [sogou/workflow#1076]
1, 多GPU下的模型推理服务器， 需要多线程初始化推理模型句柄（线程数量等于gpu数量），并在该线程中调用， 之前是使用线程池来做的，但是在workflow中并没有看到这种用法，请问一下思路？

**Comment by xialuxi** [comment]
我目前是采用WFThreadTaskFactory做的，服务起来后默认启动初始化任务，再把接收的htpp推理任务包装成WFThreadTaskFactory来做任务，感觉资源调度不友好。

**Comment by xialuxi** [comment]
推理模型句柄必须绑定线程的pid， 该句柄只能在该线程中使用。当前是在主线程中使用map记录下来推理模型句柄，每个WFThreadTaskFactory执行的时候， 根据pid去查找对应的推理句柄执行任务

**Comment by Barenboim** [comment]
这个的解决方法是用thread local啊。在你的thread task实现里，通过声明thread local的推理模型句柄，来实现每个线程一个。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/issues/822
之前也有人问过类似的问题

**Comment by xialuxi** [comment]
感觉这样使用不优雅，对资源的控制也不够友好。

**Comment by xialuxi** [comment]
这样一旦有其它的WFThreadTaskFactory任务（非推理的）， 也会去这个线程里面执行。我是希望这个线程是专用的只做推理任务， 高效并发利用GPU.

**Comment by xialuxi** [comment]
可不可以实现专用的GPU推理线程池

**Comment by Barenboim** [comment]
> 可不可以实现专用的GPU推理线程池

可以的啊，这个也有人问过。
~~~cpp
{
    Executor *gpu_executor = new Executor;
    ExecQueue *queue = new ExecQueue;

    gpu_executor->init(thread_num);
    queue->init();
    auto *t = WFThreadTaskFactory<...>::create_thread_task(queue, executor, routine, callback);
}
~~~
我们普通的create_thread_task接口，就是去找一个全局的executor，并用你的queue_name找一个对应的queue。这两个你是可以自己来管理的。

**Comment by xialuxi** [comment]
我了解一下， 谢谢！

**Comment by Barenboim** [comment]
executor和queue的生命周期应该覆盖上面的所有任务。用完之后，需要调用deinit()反初始化。
