### ISSUE TITLE
如何对 MySQLCell 内部的数据修改，MySQLCell 内部的数据由谁来释放？

### ISSUE THREAD

**Issue by chenghuaWang** [sogou/workflow#1078]
## 如何修改 MySQLCell 内部的数据
我目前的需求是：将多个 MySQLCell 内的数据做处理，再对这些处理过的 MySQLCell 进行更进一步的操作（比如说从不同服务器到来的表需要合并，合并中存在的冲突(比如说数据类型等)需要直接对 MySQLCell 做操作）。我了解到目前的 MySQLCell 是没法修改内部的数据的。如果把这些 MySQLCell 内的数据拷贝到我自己定义的类中再做进一步操作，会增加很多不必要的时间。

## MySQLCell 的数据由谁来释放
我注意到 MySQLCell 内部是使用 void* data 指针来存储的，那这些数据由谁来释放呢？

**Comment by holmes1412** [comment]
你好，这份数据属于task的response数据，workflow中的request、response属于网络task的一部分，伴随task被delete后释放，而task是在我们这个callback之后就会被delete。

如果你有需要，可以自己把数据拷走，这个拷贝目前看起来没法避免。

对于第一个问题，有没有业界里通用的类推荐给我ua q？我可以做的就是帮你做一个数据拷贝和写这个类的工作～

**Comment by chenghuaWang** [comment]
@holmes1412 感谢你的回复。“workflow中的request、response属于网络task的一部分，伴随task被delete后释放”，这个特性看来是暂时没法避免数据拷贝的。或许可以提供一个 unsafe 的函数来把 task 中的一些数据解绑，直接传出这些数据的指针，然后设立flag 避免释放。我没有找到啥通用的类 :flushed: ，目前我的实现和 MySQLCell 较为相似，只不过是用 std::variant 来存储不同类型的数据的。

@Barenboim MySQLResponse  貌似也是会被 task 释放？还是需要拷贝出来？

**Comment by Barenboim** [comment]
会被task释放，但是，你可以用std::move把它移动走，就不会释放了呀。

**Comment by chenghuaWang** [comment]
@Barenboim 哦哦哦，这样确实好办了。那我接下来就只要改一改 MySQLCell 的实现，提供一个修改内部数据的接口就行了。

**Comment by Barenboim** [comment]
> @Barenboim 哦哦哦，这样确实好办了。那我接下来就只要改一改 MySQLCell 的实现，提供一个修改内部数据的接口就行了。

如果功能可以通用，欢迎pr给我们。
