### ISSUE TITLE
关于mysql事务的实例问题

### ISSUE THREAD

**Issue by vincentqin-sys** [sogou/workflow#1079]
1、我试着使用教程中的事务示例，编译出错。

WFMySQLConnection conn(1);
conn.init("mysql://root@127.0.0.1/test");

// test transaction
const char *query = "BEGIN;";
WFMySQLTask *t1 = conn.create_query_task(query, task_callback);
query = "SELECT * FROM check_tiny FOR UPDATE;";
WFMySQLTask *t2 = conn.create_query_task(query, task_callback);
query = "INSERT INTO check_tiny VALUES (8);";
WFMySQLTask *t3 = conn.create_query_task(query, task_callback);
query = "COMMIT;";
WFMySQLTask *t4 = conn.create_query_task(query, task_callback);
WFMySQLTask *t5 = conn.create_disconnect_task(task_callback);
((*t1) > t2 > t3 > t4 > t5).start();

出错信息 》》 no known conversion for argument 1 from ‘WFMySQLTask’ {aka ‘WFNetworkTask<protocol::MySQLRequest, protocol::MySQLResponse>’} to ‘WFGraphNode&’

2、 拼接一个sql串， 能完成实现事务吗？“begin;insert 1;insert 2;commit;”  我测试好像不行。
3、实例中的task_callback中， 需要自己根据错误码来显示执行ROLLBACK吗？
4、conn.create_disconnect_task(task_callback);这个task执行，会返回错误“{"errcode":1065,"errmsg":"Query was empty"}”。如果在call back中处理错误来roolback， 碰到这个怎么处理？
5、我查里所有实例， 好像没有完整的mysql事务的例子。能提供一个完整的例子吗？

**Comment by Barenboim** [comment]
你用的那个运算符重载，我们是打算废弃的。用的话你需要include一下WFOperator.h。看起来你好像include了WFGraphTask，被匹配到另一个运算符了。
可以rollback的。MySQLConnection只是用来让请求都在一个连接上，上面发什么query用户自行决定。disconnect这个我们目前的做法就是发一个空的SELECT请求，你可以忽略返回的数据。

**Comment by Barenboim** [comment]
改成
~~~cpp
SeriesWork *series = Workflow::create_series_work(t1, nullptr);
*series << t2 << t3 << t4 << t5;
series->start();
~~~
和你上面那个写法等价。不用加WFOperator.h。

**Comment by vincentqin-sys** [comment]
> 你用的那个运算符重载，我们是打算废弃的。用的话你需要include一下WFOperator.h。看起来你好像include了WFGraphTask，被匹配到另一个运算符了。 可以rollback的。MySQLConnection只是用来让请求都在一个连接上，上面发什么query用户自行决定。disconnect这个我们目前的做法就是发一个空的SELECT请求，你可以忽略返回的数据。

回复里的“可以rollback的”，指的是，可以通过拼接sql语句执行事务，然后只要有一个语句出错就会rollback吗？

**Comment by Barenboim** [comment]
我是说用户可以自己发rollback的query。
在一个事务中，如果出现网络错误，那么这个连接也会被关闭，事务会被自动的rollback。这就是为什么connection上的任务都是没有retry的。因为retry的话，自动重新建立了连接，用户可能不知道事务已经中断。

**Comment by vincentqin-sys** [comment]
> 我是说用户可以自己发rollback的query。 在一个事务中，如果出现网络错误，那么这个连接也会被关闭，事务会被自动的rollback。这就是为什么connection上的任务都是没有retry的。因为retry的话，自动重新建立了连接，用户可能不知道事务已经中断。

我模拟出现错误后，断开链接，但后续sql还是会执行。只有断开之前的语句回滚了。
const char *query = "BEGIN;";
  WFMySQLTask *t1 = conn.create_query_task(query, task_callback);
  query = "INSERT INTO test_trancs(id) VALUE (2);";
  WFMySQLTask *t2 = conn.create_query_task(query, task_callback);
  query = "INSERT INTO test_trancs(id) VALUE (3);";
  WFMySQLTask *t3 = conn.create_query_task(query, task_callback);
  query = "COMMIT;";
  WFMySQLTask *t4 = conn.create_query_task(query, task_callback);
  WFMySQLTask *t5 = conn.create_disconnect_task(task_callback);

// 把断开链接的t5放在t3前，模拟callback中发现错误进行链接断开，回滚操作。
*series << t2 << t5 << t3 << t4;

在事务执行过程中，发现错误后，我怎么中断后续事务的运行？

**Comment by Barenboim** [comment]
我们之前的想法，是让用户去处理这种情况，比如你可以给每个task设置callback：
~~~cpp
auto cb = [](WFMySQLTask *task)
{
    if (task->get_state != WFT_STATE_SUCCESS)
        series_of(task)->cancel();
};
t1->set_callback(cb);
t2->set_callback(cb);
t3->set_callback(cb);
t4->set_callback(cb);
t5->set_callback(cb);
~~~
除了最后一个task，都需要配这个callback。是不是觉得不是太方便？

**Comment by vincentqin-sys** [comment]
都加callback，是不是需要设置series->set_context(content); 来传入（con，pre_sql_result），通过这个连接和上一次调用的结果来做回滚？

**Comment by Barenboim** [comment]
是的，就是得到任务的状态。如果一个task不失败，后面就不执行了。你可以这么实验：
~~~cpp
t3->set_receive_timeout(0);
~~~
让t3的读取超时为0，这样t3会得到一个超时失败。

**Comment by Barenboim** [comment]
是的，就是得到任务的状态。如果一个task失败，后面就不执行了。你可以这么实验：
~~~cpp
t3->set_receive_timeout(0);
~~~å让t3的读取超时为0，这样t3会得到一个超时失败。

**Comment by Barenboim** [comment]
是的，就是得到任务的状态。如果一个task失败，后面就不执行了。你可以这么实验：
~~~cpp
t3->set_receive_timeout(0);
~~~
让t3的读取超时为0，这样t3会得到一个超时失败。

**Comment by vincentqin-sys** [comment]
可以了，多谢~~
通过series_of(task)->cancel();来中断后续sql的执行。

**Comment by Barenboim** [comment]
没有commit连接断开，应该就是自动回滚了啊。
比如你的一次query超时了， 这个整个事务肯定就回滚了。

**Comment by vincentqin-sys** [comment]
> 没有commit连接断开，应该就是自动回滚了啊。 比如你的一次query超时了， 这个整个事务肯定就回滚了。

多谢！！
