### ISSUE TITLE
关于连接的管理

### ISSUE THREAD

**Issue by Irelia5** [sogou/workflow#1086]
您好，我遇到了这样的问题：
作为client，连接似乎没有连接池，通过任务自动创建。
但是场景(HTTPS : ssl connect time + connect time+ receive time)对耗时又特别敏感，无法接受因为receive_timeout的超时后连接不断重新建立，占了任务的时间。
这部分连接建立是不是独立于任务之外会更加合理？
或者目前的upstream能解决这样的问题吗？

**Comment by Barenboim** [comment]
也就是说，你希望你的任务时间很短。但我们的连接并不是预先建立的，当没有空闲连接时，会主动建立连接，导致你的任务时间偏长？
解决这个问题，是不是需要提供一种机制，让框架可以预先建立好一些连接？

**Comment by Irelia5** [comment]
解决这个问题，是不是需要提供一种机制，让框架可以预先建立好一些连接？
----------------------------------
我理解是这样的，现有的框架能支持吗？通过upstream可以实现吗？

**Comment by Barenboim** [comment]
upstream是做负载均衡和服务治理的，解决不了这个问题。我觉得你这个需求好像还是很合理的。我想一下怎么解决。

**Comment by Irelia5** [comment]
赞~
![image](https://user-images.githubusercontent.com/52132456/202464193-b62cdb77-63d3-40b5-85a5-cfafcfbd9a37.png)

**Comment by Barenboim** [comment]
想来想去，由于你这个需求太小众而且没有非常完美的解决方案，也只能让你通过配置多个upstream，让连接独立的方式来解决了。例如，你可以通过以下的方法，对"localhost"建立三个独立的连接，然后你自己决定在那个连接上创建http请求：
~~~cpp
int main()
{
    struct AddressParams params = ADDRESS_PARAMS_DEFAULT;
    UpstreamManager::upstream_create_weighted_random("host1", false);
    UpstreamManager::upstream_add_server("host1", "localhost", &params);

    params.endpoit_params.connect_timeout++;
    UpstreamManager::upstream_create_weighted_random("host2", false);
    UpstreamManager::upstream_add_server("host2", "localhost", &params);

    params.endpoit_params.connect_timeout++;
    UpstreamManager::upstream_create_weighted_random("host3", false);
    UpstreamManager::upstream_add_server("host3", "localhost", &params);

    ...
    WFHttpTask *task = WFTaskFactory::create_http_task("https://host2/...", ...);
    task->get_req()->set_header_pair("Host", "localhost");    // otherwise it will be "host2"
    task->start();
}
~~~
通过这个方式，host1到host3不会共享连接。这里比较奇葩的是，每个server的参数还必须又一点小区别，否则内部还是会共用连接池。所以这里我每个host的connect_timeout增加了一毫秒。
然后，我们依然无法预建立连接。建立连接只能通过发送HTTP请求，然后保持连接。但是现在起码你可以自己控制连接池了。你可以轮询使用连接避免连接断开。当某一个请求失败，可以取下一个host发生请求，然后后台重新建立断开的连接。
需要把代码更新到最新（0.10.5）。之前代码多个upstream指向同一目标时一定共用连接池。

**Comment by Irelia5** [comment]
“可以取下一个host发生请求，然后后台重新建立断开的连接”
请问这里重新建立连接是框架实现的吗？

“你可以轮询使用连接避免连接断开”
请问轮询动作是和上一次超时回调同步的吗？

**Comment by Barenboim** [comment]
1、是的。连接上发生错误之后，再次请求会重新建立连接。例如host1发生receive timeout，你可以把host1这个upstream名从连接池里摘除，再向它发起一次GET请求，如果成功callback里把host1重新加回。
2、轮询是指成功的时候轮流使用每个upstream name。因为如果长时间不使用一个连接，达到keep alive timeout后连接是会被断开的。轮询是确保连接一直会被使用。

**Comment by Irelia5** [comment]
感谢~我先尝试下
