### ISSUE TITLE
如何从一个 Task 中调用并执行另一个 Task？

### ISSUE THREAD

**Issue by chenghuaWang** [sogou/workflow#1087]
# 问题描述
我目前的需求是这样的：在主线程中有一个 Http Server 在监听到来的 Post 信息。然后需要通过 Post 信息来构建出一个图任务，并且把图任务加入到一个任务列表中执行，这个任务列表需要定时循环执行其中的图任务（当然，最好是各个图任务并发的执行）。我刚接触并发编程，请问在这个需求下，是要专门再开一个线程来管理各个图任务吗？用 workflow 提供的功能可以如何优雅的实现这个需求呢？

**Comment by Barenboim** [comment]
你好。
定时执行的任务，就用timer来实现就可以了。workflow编程里，用户任何时候无需创建线程。
你这个应用，就是timer+graph。例如：
~~~cpp
void graph_callback(WFGraphTask *graph)
{
    ...
    WFTimerTask *timer = WFTask Factory::create_timer_task(seconds, nanonseconds, timer_callback);
    series_of(graph)->push_back(timer);
}

void timer_callback(WFTimerTask *timer)
{
    WFGraphTask  *graph = create_graph_task(...);
    ...
    series_of(timer)->push_back(graph);
}
~~~
所有task对象，都是实时创建的。存在反复使用的task。

**Comment by chenghuaWang** [comment]
@Barenboim 感谢您的回答。也就是说，我只需要在 Http server call_back 中进行图任务创建和执行就行了，被 Http sever 阻塞的线程与其他任务执行无关，workflow 会负责线程的管理。对于循环任务，只需要互相循环创建 task 就行了。

**Comment by Barenboim** [comment]
你好。workflow编程里，用户永远无需自己创建线程。你这个需求，好像是timer+graph的反复执行。只需要在timer callback里创建graph，在graph callback里创建timer。例如：
~~~cpp
void timer_callback(WFTimerTask *timer)
{
    WFGraphTask *graph = WFTaskFactory::create_graph_task(..., graph_callback);
    // build the graph
    series_of(timer)->push_back(graph);
}

void graph_callback(WFGraphTask *graph)
{
    ...
    WFTimerTask *timer = WFTaskFactory::create_timer_task(seconds, nanoseconds, timer_callback);
    series_of(graph)->push_back(timer);
}
~~~
所有的task都是实时创建，不存在反复使用的task。当然，对于这种repeat需求，也可以用repeater任务。我们tutorial里有几个实例也用了repeater。

**Comment by Barenboim** [comment]
另外，你的http是什么时候进行回复的？是所有图任务执行完成吗？
如果是的话，不要阻塞process啊，把任务push_back就好：
~~~cpp
void http_process(WFHttpTask *task)
{
    WFGraphTask *graph = WFTaskFactory::create_graph_task(..., graph_callback);
    sereis_of(task)->push_back(graph);
}
~~~

**Comment by Barenboim** [comment]
workflow里没有阻塞，回复的时机是series里任务执行完，而不是process函数执行完。

**Comment by chenghuaWang** [comment]
Http 并不进行回复，但是 Http server 还需要接收和处理其他的请求，所以有一个 waitGroup()存在。

Http server 像这样的：
```cpp
signal(SIGTERM, signal_kill);
  if (m_server->start(m_port) == 0) {
    __wait_group.wait();
    m_server->stop();
  } else {
    perror("Cannot start server");
    exit(1);
  }
```
在 http callback 中创建图任务：
```cpp
void http_callback(WFHttpTask *task) {
    WFGraphTask *graph = WFTaskFactory::create_graph_task(..., graph_callback);
    execGraph(graph);
}
```
为了保证图任务执行貌似在 execGraph 中还需要一个 waitGroup.wait();像这样：
```cpp
void execGraph(WFGraphTask * task){
    task->start();
    waitGroup.wait();
}
```

**Comment by Barenboim** [comment]
首先，http process我们不叫callback。callback是http回复完成之后的。你这个应该是http_process。
你的逻辑，就是图执行结束之后回复吧？正确的做法是：
~~~cpp
void http_process(WFHttpTask *task)
{
    WFGraphTask *graph = WFTaskFactory::create_graph_task(..., [task](WFGraphTask *) {
                task->get_resp()->append_output_body(....);
        });
    series_of(task)->push_back(graph);
}
~~~
# http 服务器回复时机，是series里的任务执行完，而不是process函数执行完！
# 永远不要阻塞（main函数除外）！

**Comment by chenghuaWang** [comment]
emmmm...... 在 建图的 post 过来后，**http 是不返回图处理完的信息的只是根据建图的规则返回了建图是否成功。http server不等待图执行结束。**

我上文中说的确实不准确，可以说 http server 和 图执行 是完全不相干的。或者说 图放在一个容器里，http server 只是根据到来的请求来增加图和删除图（我抽象了一个图的类，其包含一个函数可以生成 workflow 的图）。图的执行是根据存放图的容器里面的repeater启动的（图第一次被加入时也要执行）。但是 http server 是在 main 函数中使用 waitGroup 阻塞了，所以我在这个 issues 的开头说了`要专门再开一个线程来管理各个图任务吗？`这段话（当然，workflow中不用这么做）。http server 和 repeater 是分别各自运行的（从程序开始到结束一直运行），那么这个问题变成了如何让 http server 和  repeater 一起执行？

貌似 Workflow::create_parallel_work(callback); 可以做到这一点。
---
让 pwork 同时包含一个 阻塞 的 httpserver 和 每隔一定时间执行的图任务？

确实 https://github.com/sogou/workflow/issues/1087#issuecomment-1319889085 中提到的 callback 是个错误用法。
---

**Comment by Barenboim** [comment]
http server和repeater一起执行，也没有必要用parallel。。。
直接：
~~~cpp
server.start();
repeater->start();
...
~~~
我们特点就是非阻塞，你就算开10个server，也是连续start就可以了啊。

**Comment by chenghuaWang** [comment]
明白了，我这个框架没搞清楚 :cry:

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/master/tutorial/tutorial-09-http_file_server.cc
你可以看一下file server这个例子。这个就是在启动server之后，发起一个repeater任务，从stdin读取用户输入，访问server。
@chenghuaWang
