### ISSUE TITLE
user_defined_protocol， server向client发送消息，如何实现比较好？

### ISSUE THREAD

**Issue by chris78l** [sogou/workflow#1092]
您好，我遇到了这样的问题：
参照tutorial-10-user_defined_protocol实现了TLV。
希望server能够向client 发送TLV消息（publish），但是不影响client的 request和response交互。
请问，这块怎么实现比较好？

**Comment by Barenboim** [comment]
Client侧也打开一个server。内网的话。
如果不能这么做，也可以反向server/client。但不是很好写。最好的方法还是各起一server。

**Comment by chris78l** [comment]
好的，感谢。我再想一下。这里存在两种情况，一种是server也是自己实现的，一种是server是第三方的。
对第二种情况，存在server发送请求的情况，client 可能不能参照turtorial-10了。

**Comment by Barenboim** [comment]
如果server是别人的协议，就需要根据协议来看看好不好实现了。

**Comment by chris78l** [comment]
我看了一下和server的协议，需要支持：
1. 能够接收来自server的推送，
2. 能够向server发送 request，接收response 
使用WF实现一个这样的tcp client，有推荐的做法吗？

**Comment by Barenboim** [comment]
第一点，需要知道具体协议。因为推送的方式有很多种。
例如k8s基于https的api server，就是一种推送。方式是client发送http request，server那边有数据改变时，返回一个http chunk。像这种，我们无论server还是client都比较容易实现。server使用push接口，而client侧就是在append里直接处理消息。
如果像websocket那样的全双工，我们目前client虽然支持，但是使用方式上不太满意。目前没有合并master。我们有用户在以自己的方法开发完整的websocket。
如果是有client发起connect，然后只有server向client发送请求（推送），client回复请求，这个是可以实现的，就是反向的server/client。我一会写一个demo看看。
最推荐的方式，就是client侧也启动一个服务，server连接client侧的服务发请求。排除防火墙的原因，我认为这是后端开发最理想的模式，这样极大的简化了业务模型，效率非常高，不影响任何功能实现。

**Comment by holmes1412** [comment]
补充一下上面关于websocket全双工的描述：目前workflow的websocket分支只支持client，是个dev版，测试过与开源的uwebsocket、php内的websocket进行简单互通。
如果有需要可以参考这个文档：https://github.com/sogou/workflow/blob/websocket/docs/tutorial-14-websocket_cli.md

**Comment by chris78l** [comment]
感谢大佬们的回复。

补充描述第三方的自定义协议，存在这样几种情况：
1.  client   发送request , server 回应response
2.  client   发送数据，    server无需应答
3.  server  发送request，client回应response
4.  server  发送数据，     client无需应答
这种完全自定义的，太特殊了。直接通过tcp socket 长连接读写，解析/组装协议更合适一些。

**Comment by Barenboim** [comment]
> 感谢大佬们的回复。
> 
> 补充描述第三方的自定义协议，存在这样几种情况：
> 
> 1. client   发送request , server 回应response
> 2. client   发送数据，    server无需应答
> 3. server  发送request，client回应response
> 4. server  发送数据，     client无需应答
>    这种完全自定义的，太特殊了。直接通过tcp socket 长连接读写，解析/组装协议更合适一些。

如果是在一同一个连接上做这些事情，那真的是自由度太高了😂不过我们的poller是完全支持你这么干的。但记得同一个fd要全双工，需要加两次，第二次要dup一下。

**Comment by chris78l** [comment]
感谢，我先学习一下。
