### ISSUE TITLE
支持SSL/TLS客户端吗

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1097]
框架有封装tls+tcp吗？

**Comment by Barenboim** [comment]
明显就支持啊😂
你那边是用什么协议？自定义吗？

**Comment by coderwxl** [comment]
是自定义的tcp协议，那用哪个task创建客户端任务呢，我没找到

**Comment by Barenboim** [comment]
~~~cpp
auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
~~~
这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。

**Comment by Barenboim** [comment]
如果只是为了加密不用加。认证才需要加。就好像你访问https一样，不用加任何认证文件的。
要加的话，调用WFGlobal::get_ssl_client_ctx，把client的SSL_CTX拿出来，自己加东西。

**Comment by coderwxl** [comment]
明白了，感谢

**Comment by MasterL-min** [comment]
> ```c++
> auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> ```
> 
> 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。

想请问如果是TLS的话，是create_client_task(TT_TCP_TLS,...)吗

**Comment by MasterL-min** [comment]
> > > > ```c++
> > > > auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。
> > > 
> > > 
> > > 想请问如果是TLS的话，是create_client_task(TT_TCP_TLS,...)吗
> > 
> > 
> > > ```c++
> > > auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。
> > 
> > 
> > 想请问下如果是TLS的话该怎么弄，好像没有TT_TCP_TLS
> 
> 用TT_TCP_SSL就可以了。这两个词没有什么区别。

非常感谢！

**Comment by MasterL-min** [comment]
> > > > ```c++
> > > > auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。
> > > 
> > > 
> > > 想请问如果是TLS的话，是create_client_task(TT_TCP_TLS,...)吗
> > 
> > 
> > > ```c++
> > > auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。
> > 
> > 
> > 想请问下如果是TLS的话该怎么弄，好像没有TT_TCP_TLS
> 
> 用TT_TCP_SSL就可以了。这两个词没有什么区别。

如果我希望让客户端和服务器执行TLS handshake协商密钥，函数好像是SSL_connect(),然后再进行传输数据，我该怎么把这个跟task结合在一起，想请问是要重构task->start()吗

**Comment by Barenboim** [comment]
> > > > > ```c++
> > > > > auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。
> > > > 
> > > > 
> > > > 想请问如果是TLS的话，是create_client_task(TT_TCP_TLS,...)吗
> > > 
> > > 
> > > > ```c++
> > > > auto *task = WFNetworkTaskFactory<REQ, RESP>::create_client_task(TT_TCP_SSL, ...);
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这就创建了SSL通信的client task了。Server侧的话，start时加上key和cert文件就可以了。
> > > 
> > > 
> > > 想请问下如果是TLS的话该怎么弄，好像没有TT_TCP_TLS
> > 
> > 
> > 用TT_TCP_SSL就可以了。这两个词没有什么区别。
> 
> 如果我希望让客户端和服务器执行TLS handshake协商密钥，函数好像是SSL_connect(),然后再进行传输数据，我该怎么把这个跟task结合在一起，想请问是要重构task->start()吗

麻烦重新开issue吧。描述清楚原始需求。
