### ISSUE TITLE
WF部署网关遇到了一点问题

### ISSUE THREAD

**Issue by modestpower** [sogou/workflow#1098]
工作岗位要求使用wf开发网关试试，途中遇到了一些现象，因为有一些转换不能公开，我直接拿官方的tutorial的代码来复现了一下

现象：频繁错误：/: Fetch failed. state = 1, error = 11: Resource temporarily unavailable
除此之外。在公司还会报 errorn 2 No such file or directory

环境: open files                          (-n) 65535
wf配置：maxconnections=10000，keepalive=-1，其他默认
服务器配置(这个肯定够了):64核-----

复现环境：
open files                          (-n) 1048576
wf配置：maxconnections=2000，keepalive=-1，其他默认
配置：虚拟机20核，内存6G

测压工具：jmeter，1000个线程，循环次数10000，没特殊消息，默认回复helloworld

场景：proxy固定连接一个服务器，给用户做转发，与自己复现主要差异在proxy连接的服务器是自定义协议，发送和接收有协议转换的过程。

请求：
helloworld<--proxy<--用户

回复：
helloworld-->proxy-->用户

复现代码只是把tutorial的helloworld和proxy部署了下就OK了，proxy中对process做了个简单的修改，改为连接固定服务器
~~~cpp
void process(WFHttpTask *proxy_task)
{
	auto *req = proxy_task->get_req();
	SeriesWork *series = series_of(proxy_task);
	WFHttpTask *http_task; /* for requesting remote webserver. */

	tutorial_series_context *context = new tutorial_series_context;
	context->url = req->get_request_uri();
	context->proxy_task = proxy_task;

	series->set_context(context);
	series->set_callback([](const SeriesWork *series) {
		delete (tutorial_series_context *)series->get_context();
	});

	context->is_keep_alive = req->is_keep_alive();
	http_task = WFTaskFactory::create_http_task("http://192.168.1.7:8888", 0, 0, http_callback);									
	const void *body;
	size_t len;
	
	http_task->get_resp()->set_size_limit(200 * 1024 * 1024);
	http_task->set_keep_alive(-1);

	*series << http_task;
}
~~~

**Comment by Barenboim** [comment]
这个是因为你对下游的最大连接数太少了。默认单个目标最大连接数为200。你可以改一下：
~~~cpp
#include <workflow/WFGlobal.h>

int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 10000; // default is 200
    WORKFLOW_library_init(&settings);
    ...
}
~~~
另外，server的默认最大接入连接数是2000，超过了会关闭持久连接。你这个可能也要改一下。这是server的参数。

**Comment by modestpower** [comment]
> 这个是因为你对下游的最大连接数太少了。默认单个目标最大连接数为200。你可以改一下：
> 
> ```c++
> #include <workflow/WFGlobal.h>
> 
> int main()
> {
>     struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
>     settings.endpoint_params.max_connections = 10000; // default is 200
>     WORKFLOW_library_init(&settings);
>     ...
> }
> ```

改完之后，在我自己复现的案例下是没有报上面错了，但是在公司的环境下，依然是会出现state==1，但errorn为0，这会不会和我公司环境下连接是tcp连接的原因？

**Comment by Barenboim** [comment]
对下游访问state为1的话，error不可能是0的啊。是通过task-&gt;get_error()看错误码，不是看系统的errno。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月30日(周三) 中午12:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] WF部署网关遇到了一点问题 (Issue #1098)




  
这个是因为你对下游的最大连接数太少了。默认单个目标最大连接数为200。你可以改一下：
 #include <workflow/WFGlobal.h&gt; int main() {     struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;     settings.endpoint_params.max_connections = 10000; // default is 200     WORKFLOW_library_init(&amp;settings);     ... }
  
改完之后，在我自己复现的案例下是没有报上面错了，但是在公司的环境下，依然是会出现state==1，但errorn为0，这会不会和我公司环境下连接是tcp连接的原因？

**Comment by modestpower** [comment]
> 对下游访问state为1的话，error不可能是0的啊。是通过task->get_error()看错误码，不是看系统的errno。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年11月30日(周三) 中午12:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sogou/workflow] WF部署网关遇到了一点问题 (Issue #1098) 这个是因为你对下游的最大连接数太少了。默认单个目标最大连接数为200。你可以改一下： #include <workflow/WFGlobal.h&gt; int main() { struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT; settings.endpoint_params.max_connections = 10000; // default is 200 WORKFLOW_library_init(&amp;settings); ... } 改完之后，在我自己复现的案例下是没有报上面错了，但是在公司的环境下，依然是会出现state==1，但errorn为0，这会不会和我公司环境下连接是tcp连接的原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

疏忽了，查了下代码发现用的是error，改完后实际报的是Connection reset by peer

**Comment by Barenboim** [comment]
嗯嗯。如果是ECONNRESET，并且你好公司网络隔着公网，那么出现连接中断（包括任何消息没有传输完成的TCP关闭）还是有可能的。如果概率太高，可以看看server的回复有没有问题。就是是错误的任务，也可以通过task->get_resp()获得已经读到的数据的。

**Comment by Barenboim** [comment]
另外，keep-alive最好不要-1，这样肯导致连接永远不释放（除非对端主动关闭）。

**Comment by modestpower** [comment]
> 嗯嗯。如果是ECONNRESET，并且你和公司网络隔着公网，那么出现连接中断（包括任何消息没有传输完成的TCP关闭）还是有可能的。如果概率太高，可以看看server的回复有没有问题。就算是错误的任务，也可以通过task->get_resp()获得已经读到的数据的。 解决小概率的连接中断问题，也让retry_max=1，出错了内部重试一次。

工作时段我用的公司服务器测的。根据您的分析后我试了下在服务器负载低的时段下进行测试，就没有出现这种断开的情况了。分析是在负载重的时段，服务器可能会对客户端进行管理，有没有办法统计wf内部开了多少个客户端呢？或者多个连接共用一个或多个客户端。因为我们连接的目标服务器是固定的，所以不用需要进行筛选，这也是我们把keepalive设为-1的原因

**Comment by Barenboim** [comment]
keepalive设为-1的问题在于，如果某个时刻并发请求非常多，proxy就需要建立很多对server的连接。但由于keepalive是无限时间，proxy永远不会主动断开这些连接，哪怕这时候已经不需要那么多连接了。只能等server去关闭。如果server也是keepalive -1的话，那么连接就一直保留着了，除非连接上出现错误。
workflow对连接数的统计是可以的，因为，我们支持连接上下文。你可以在访问server的callback里，这样设置连接上下文：
~~~cpp
void callback(WFHttpTask *task)
{
    if (task->get_task_seq() == 0)  // 连接上的第一个任务，设置连接上下文
    {
        WFConnection *conn = task->get_connection();
        if (conn) // 有可能根本没有建立连接，需要判断连接是否存在
        {
            MyClass *connctx = new MyClass;  // 任何你自己的类
            conn->set_context(connctx, [](void *ctx) { delete (MyClass *)ctx; });  // 第二个参数是deleter
        }
    }
    ...
}
~~~
通过这个方式，你就可以捕捉连接的建立与释放时机了，释放时机就是deleter的调用。注意，在callback（包括server task和client task）里，访问连接上下文需要需要判断连接是否存在，还要考虑并发访问的问题（多个callback同时在访问连接上下文）。但是在server的process里（注意，process不是callback），就无需考虑了，这个时候连接是独占的（但process和callback同时访问，需要考虑并发）。可以看这个文档：
https://github.com/sogou/workflow/blob/master/docs/about-connection-context.md

**Comment by Barenboim** [comment]
@modestpower 
上线了记得star一下项目啊。

**Comment by modestpower** [comment]
> @modestpower 上线了记得star一下项目啊。

你好你好，根据之前的判断我们得出一个是因为宽带到达了上线到达了网关的瓶颈，也是因为这个，导致了响应比较慢，上游判断断开了连接。这个解决之后，又对其测试效果就好，不过还是会出现概率被断开，而且和旧的网关有3w的差距。在单纯作为服务器上，workflow比旧网关的纯服务器优秀很多，不过在网关这一块，由于我们的协议做过特化导致了在网关性能上旧网关比纯wf的网关好一点。主要区别在于，wf底层会开启多个客户端，微观下客户会独占一个网关，这样会多出一个资源竞争的开销，而我们这边的协议有对这一情况做了特化解决了资源竞争的问题。后续会尝试在wf中实现这个想法。抱歉这么久没回复，因为疫情，我们一个接一个的阳了。所以有点搁置

**Comment by Barenboim** [comment]
比旧的网关慢没有什么道理。workflow作为proxy的效率是作为纯server效率的精确1/2，也就是说没有任何转发overhead。所以我觉得可能是参数的问题。
如果你的qps比较高，带宽接近用完，你调节一下poller的线程数试一试：
~~~cpp
int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.poller_threads = 16;
    WORKFLOW_library_init(&settings);
}
~~~
连接偶尔断开是server主动断开，还是proxy（workflow）断开？

**Comment by modestpower** [comment]
> 比旧的网关慢没有什么道理。workflow作为proxy的效率是作为纯server效率的精确1/2，也就是说没有任何转发overhead。所以我觉得可能是参数的问题。 如果你的qps比较高，带宽接近用完，你调节一下poller的线程数试一试：
> 
> ```c++
> int main()
> {
>     WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
>     settings.poller_threads = 16;
>     WORKFLOW_library_init(&settings);
> }
> ```
> 
> 连接偶尔断开是server主动断开，还是proxy（workflow）断开？

断开是服务器那边断的，和wf无关，因为不只是网关这边连服务器，还有其他客户会连，所以在一些时间段内负载太大会断掉。至于参数方面我是有调过的，poller_threads调大了没有太大的变化，而调整handle_thread，最大的变化是内部开启的客户端减少了，吞吐量也相应的增加一点。

**Comment by Barenboim** [comment]
想让连接独占不争抢很简单的哈。你可以试一下。不过，需要派生。
WFComplexClientTask<REQ, RESP>的set_info()方法，可以设置任何信息用于区分请求的连接池。info不同的task不会公用连接池。
你大概需要这么派生：
~~~cpp
class MyClientTask : public WFComplexClientTask<MyRequest, MyResponse>
{
public:
    MyClientTask(const ParsedURI& uri, int connid, int retry_max, my_callback_t callback) :
        WFComplexClientTask(retry_max, std::move(callback))
    {
        char buf[32];
        sprintf(buf, "%d", connid);
        init(uri);
        set_info(buf);
    }
};
~~~
然后，在创建client task的时候new这个类就可以了。传入一个connid，不同的connid的task不会争抢连接的。可参考我们http或redis等任务的实现（相同IP下，不同密码或数据库号的redis任务，不共享连接）。
