### ISSUE TITLE
关于workflow json的修改操作

### ISSUE THREAD

**Issue by chanchann** [sogou/workflow#1101]
请教下，我看到json有find和append，remove操作，我们如何优雅的进行更新操作呢。

除了先remove，再append，还有什么办法做到。

**Comment by Barenboim** [comment]
怎么个更新法？改一个具体value的内容吗？
先remove再append可以，但这样的话，这个value就变成object或array的末尾元素了。所以update的话我们可能还需要加个接口。

**Comment by Barenboim** [comment]
你是不是想实现这个功能：
~~~cpp
json["aaa"] = "bbb";
~~~
然后先find一下有没有"aaa"这个key，有的话更新它的value为"bbb"，没有就添加一个？
没有update接口之前，你可以这么做：
~~~c
{
    const json_value_t *val = json_object_find("aaa", obj);

    if (val)
        json_value_destroy(json_object_remove(val, obj));

    json_object_append(obj, "aaa", JSON_VALUE_STRING, "bbb");
}
~~~
新加的member会被放到object的末尾。我感觉这么做问题不大。

**Comment by Barenboim** [comment]
你是不是想实现这个功能：
~~~cpp
json["aaa"] = "bbb";
~~~
没有update接口之前，你可以这么做：
~~~c
{
    const json_value_t *val = json_object_find("aaa", obj);

    if (val)
        json_value_destroy(json_object_remove(val, obj));

    json_object_append(obj, "aaa", JSON_VALUE_STRING, "bbb");
}
~~~
新加的member会被放到object的末尾。我感觉这么做问题不大。

**Comment by chanchann** [comment]
object可能从逻辑上来说，顺序问题不大，但是array需要顺序

```cpp
// create an array using push_back
json j;
j.push_back("foo");
j.push_back(1);
j.push_back(true);

j[2] = 1.3;
```

**Comment by Barenboim** [comment]
> object可能从逻辑上来说，顺序问题不大，但是array需要顺序
> 
> ```c++
> // create an array using push_back
> Json j;
> j.push_back("foo");
> j.push_back(1);
> j.push_back(true);
> 
> j[2] = 1.3;
> ```

我去，你数组还能这么用。。。
