### ISSUE TITLE
workflow的test失败

### ISSUE THREAD

**Issue by chanchann** [sogou/workflow#1102]
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/27816166/205483071-e4737ae7-9222-481c-a280-0fb5eac6d441.png">

**Comment by Barenboim** [comment]
这个test需要本地启动一个redis server才能通过。test基本是给我们自己开发环境用的😂

**Comment by chanchann** [comment]
ok好的

**Comment by Barenboim** [comment]
我把测试用例里redis密码改成空了，你可以开个redis server再试一下。可能可以test过。

**Comment by chanchann** [comment]
OK好的
