### ISSUE TITLE
redis异步客户端支持redis cluster么

### ISSUE THREAD

**Issue by jiangdongzi** [sogou/workflow#1107]
支持cluster中的 ask 和 moved 命令么

**Comment by Barenboim** [comment]
支持的:
https://github.com/sogou/workflow/blob/d4c36259af3c1a63278d4f6398a1c43f4b8066bf/src/factory/RedisTaskImpl.cc#L193
麻烦帮我们用一下看看有没有什么问题。

**Comment by jiangdongzi** [comment]
> 

好的, 近期准备在项目中使用

**Comment by jiangdongzi** [comment]
> 支持的:
> 
> https://github.com/sogou/workflow/blob/d4c36259af3c1a63278d4f6398a1c43f4b8066bf/src/factory/RedisTaskImpl.cc#L193
> 
> 
> 麻烦帮我们用一下看看有没有什么问题。

几个问题需要请教下

![image](https://user-images.githubusercontent.com/17529657/206719413-3d17eb5c-ea02-4759-af1a-932a2023a5a6.png)
1. task是需要手动delete的吧? 不然会内存泄漏?
2. 在项目中我需要调用 	wait_group.wait(); 这句吧
3.   WFTaskFactory::create_redis_task 这个成本高不高? 高的话是否可以保存复用? 是否线程安全

**Comment by Barenboim** [comment]
1、task不需要delete。task的生命周期到callback之后就结束了。
2、workflow的最佳用法是全程无等待。所以，除了main函数，不应该有任何地方使用wait_group。
3、不用考虑成本问题，需要的地方就创建。线程安全的。

你的这几个问题都特别好，很少见到完全没看过文档就能提出这么重要问题的。可能你之后用起来会觉得很顺手。

**Comment by jiangdongzi** [comment]
> 1、task不需要delete。task的生命周期到callback之后就结束了。 2、workflow的最佳用法是全程无等待。所以，除了main函数，不应该有任何地方使用wait_group。 3、不用考虑成本问题，需要的地方就创建。线程安全的。
> 
> 你的这几个问题都特别好，很少见到完全没看过文档就能提出这么重要问题的。可能你之后用起来会觉得很顺手。

多谢解答，后续遇到问题再反馈

**Comment by Barenboim** [comment]
> > 1、task不需要delete。task的生命周期到callback之后就结束了。 2、workflow的最佳用法是全程无等待。所以，除了main函数，不应该有任何地方使用wait_group。 3、不用考虑成本问题，需要的地方就创建。线程安全的。
> > 你的这几个问题都特别好，很少见到完全没看过文档就能提出这么重要问题的。可能你之后用起来会觉得很顺手。
> 
> 多谢解答，我看到每次调用都需要传入url，链接是短链接还是长链接呢，链接是会复用的吧，应该不是每次请求都创建新的链接吧？

redis默认都是长连接。例如你贴的那个tutorial02示例，两个请求必然用同一个连接。
http的话，会自动识别http header来决定是长连接还是短连接。

**Comment by jiangdongzi** [comment]
@Barenboim 调用 HGETALL时候 得到了 全是nil的结果, 遇到过这种情况么

![image](https://user-images.githubusercontent.com/17529657/207251360-349c2b2f-d6cc-469c-80dd-ca5ced0c65d5.png)
![image](https://user-images.githubusercontent.com/17529657/207251432-1a939466-7f43-464a-8c85-f94ee98fb527.png)

**Comment by Barenboim** [comment]
> @Barenboim 调用 HGETALL时候 得到了 全是nil的结果, 遇到过这种情况么
> 
> ![image](https://user-images.githubusercontent.com/17529657/207251360-349c2b2f-d6cc-469c-80dd-ca5ced0c65d5.png) ![image](https://user-images.githubusercontent.com/17529657/207251432-1a939466-7f43-464a-8c85-f94ee98fb527.png)
> 
> 使用redis++调用结果是正常的 返回的个数匹配, 但是就是所有都是空, 这些值中有很多是protobuf序列化的二进制字符串, 不知道是否有关系

你通过resp->get_result_ptr()可以得到一个redis_reply_t型的原始Redis reply结构：
~~~c
typedef struct __redis_reply {
    int type; /* REDIS_REPLY_TYPE_* */
    long long integer; /* The integer when type is REDIS_REPLY_TYPE_INTEGER */
    size_t len; /* Length of string */
    char *str; /* Used for both REDIS_REPLY_TYPE_ERROR and REDIS_REPLY_TYPE_STRING */
    size_t elements; /* number of elements, for REDIS_REPLY_TYPE_ARRAY */
    struct __redis_reply **element; /* elements vector for REDIS_REPLY_TYPE_ARRAY */
} redis_reply_t;
~~~
你看看这个内容对不对。

**Comment by kedixa** [comment]
@jiangdongzi 
请问使用的是master分支的最新代码吗，这个问题是在单机redis遇到的还是集群redis遇到的呢？
麻烦用下面的代码试一下能不能复现，如果可以复现用`sudo tcpdump -A -i any tcp port 6379`抓一下包发出来看看，6379为实际redis的端口号，抓包的时候构造一组测试样例，不要包含隐私数据
```cpp
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include "workflow/RedisMessage.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"

static WFFacilities::WaitGroup wait_group(1);

void redis_callback(WFRedisTask *task)
{
	protocol::RedisRequest *req = task->get_req();
	protocol::RedisResponse *resp = task->get_resp();
	int state = task->get_state();
	int error = task->get_error();

    if (state == WFT_STATE_SUCCESS) {
        redis_reply_t *reply = resp->result_ptr();
        if (reply->type == REDIS_REPLY_TYPE_ARRAY) {
            for (size_t i = 0; i < reply->elements; i++) {
                redis_reply_t *r = reply->element[i];
                if (r->type == REDIS_REPLY_TYPE_STRING) {
                    printf("i:%zu len:%zu\n", i, r->len);
                }
                else {
                    printf("i:%zu type:%d\n", i, r->type);
                }
            }
        }
        else {
            printf("type:%d\n", reply->type);
        }
    }
    else {
        printf("state:%d error:%d\n", state, error);
    }

    wait_group.done();
}


void sig_handler(int signo)
{
	wait_group.done();
}

int main(int argc, char *argv[])
{
    std::string url, key;
	WFRedisTask *task;

	if (argc != 3)
	{
		fprintf(stderr, "USAGE: %s <redis URL> <key>\n", argv[0]);
		exit(1);
	}

	/* Redis URL format: redis://:password@host:port/dbnum
	   examples:
	   redis://127.0.0.1
	   redis://:12345@redis.sogou:6379/3
	*/
    url = argv[1];
	if (strncasecmp(argv[1], "redis://", 8) != 0 &&
		strncasecmp(argv[1], "rediss://", 9) != 0)
	{
		url = "redis://" + url;
	}
    key = argv[2];

	task = WFTaskFactory::create_redis_task(url, 1, redis_callback);
	protocol::RedisRequest *req = task->get_req();
	req->set_request("hgetall", { key });

	task->start();

	wait_group.wait();
	return 0;
}

```

**Comment by jiangdongzi** [comment]
> 

这是我用gdb打印的, 需要什么数据我再提供
![image](https://user-images.githubusercontent.com/17529657/207273242-a9af47be-d964-4f04-abee-e1c8f32a963a.png)

**Comment by jiangdongzi** [comment]
> @jiangdongzi 请问使用的是master分支的最新代码吗，这个问题是在单机redis遇到的还是集群redis遇到的呢？ 麻烦用下面的代码试一下能不能复现，如果可以复现用`sudo tcpdump -A -i any tcp port 6379`抓一下包发出来看看，6379为实际redis的端口号，抓包的时候构造一组测试样例，不要包含隐私数据
> 
> ```c++
> #include <stdlib.h>
> #include <stdio.h>
> #include <string.h>
> #include <string>
> #include "workflow/RedisMessage.h"
> #include "workflow/WFTaskFactory.h"
> #include "workflow/WFFacilities.h"
> 
> static WFFacilities::WaitGroup wait_group(1);
> 
> void redis_callback(WFRedisTask *task)
> {
> 	protocol::RedisRequest *req = task->get_req();
> 	protocol::RedisResponse *resp = task->get_resp();
> 	int state = task->get_state();
> 	int error = task->get_error();
> 
>     if (state == WFT_STATE_SUCCESS) {
>         redis_reply_t *reply = resp->result_ptr();
>         if (reply->type == REDIS_REPLY_TYPE_ARRAY) {
>             for (size_t i = 0; i < reply->elements; i++) {
>                 redis_reply_t *r = reply->element[i];
>                 if (r->type == REDIS_REPLY_TYPE_STRING) {
>                     printf("i:%zu len:%zu\n", i, r->len);
>                 }
>                 else {
>                     printf("i:%zu type:%d\n", i, r->type);
>                 }
>             }
>         }
>         else {
>             printf("type:%d\n", reply->type);
>         }
>     }
>     else {
>         printf("state:%d error:%d\n", state, error);
>     }
> 
>     wait_group.done();
> }
> 
> 
> void sig_handler(int signo)
> {
> 	wait_group.done();
> }
> 
> int main(int argc, char *argv[])
> {
>     std::string url, key;
> 	WFRedisTask *task;
> 
> 	if (argc != 3)
> 	{
> 		fprintf(stderr, "USAGE: %s <redis URL> <key>\n", argv[0]);
> 		exit(1);
> 	}
> 
> 	/* Redis URL format: redis://:password@host:port/dbnum
> 	   examples:
> 	   redis://127.0.0.1
> 	   redis://:12345@redis.sogou:6379/3
> 	*/
>     url = argv[1];
> 	if (strncasecmp(argv[1], "redis://", 8) != 0 &&
> 		strncasecmp(argv[1], "rediss://", 9) != 0)
> 	{
> 		url = "redis://" + url;
> 	}
>     key = argv[2];
> 
> 	task = WFTaskFactory::create_redis_task(url, 1, redis_callback);
> 	protocol::RedisRequest *req = task->get_req();
> 	req->set_request("hgetall", { key });
> 
> 	task->start();
> 
> 	wait_group.wait();
> 	return 0;
> }
> ```
是最新的master分支

**Comment by kedixa** [comment]
会不会是你在callback之后又访问了task的数据？我给的代码可以复现问题吗

**Comment by jiangdongzi** [comment]
> 会不会是你在callback之后又访问了task的数据？我给的代码可以复现问题吗

你给的貌似没问题:
![image](https://user-images.githubusercontent.com/17529657/207276917-175fa43a-ddb8-434f-ada0-80ddb583fe00.png)

![image](https://user-images.githubusercontent.com/17529657/207277450-4cba62ff-4676-41fc-bea4-f89df4ac7924.png)
下面是我的代码, 麻烦帮忙看看是不是哪里有问题

**Comment by jiangdongzi** [comment]
> 会不会是你在callback之后又访问了task的数据？我给的代码可以复现问题吗

是在callback后访问了, 我在callback中调用试试

**Comment by jiangdongzi** [comment]
> 会不会是你在callback之后又访问了task的数据？我给的代码可以复现问题吗

确实是因为callback后调用了, 没问题了.
请教个问题, 我在不同的线程中使用workflow redis 客户端, 会创建多个链接还是复用单个链接?   因为我们可能在几百个线程中使用客户端, 担心会创建几百个链接

**Comment by Barenboim** [comment]
就是我上面说的问题，workflow的用法里，是没有wait和signal的。你的程序在callback里signal主进程处理结果是不对的。
我们会复用连接的，你无需要自建连接池。

**Comment by Barenboim** [comment]
task的生命周期到callback之后就结束了。如果需要保留resp，可以这么做：
~~~cpp
void redis_callback(WFRedisTask *task)
{
    protocol::RedisResponse *resp = new protocol::RedisResponse(std::move(*task->get_resp());
    ...
}
~~~

**Comment by jiangdongzi** [comment]
> 就是我上面说的问题，workflow的用法里，是没有wait和signal的。你的程序在callback里signal主进程处理结果是不对的。 我们会复用连接的，你无需要自建连接池。

我使用signal的目的与workflow的用法无关, 是配合协程使用, 调用workflow异步redis后挂起协程, 在callback中唤醒协程

**Comment by Barenboim** [comment]
你要这么用，只能把resp给move出来了。

**Comment by jiangdongzi** [comment]
> 你要这么用，只能把resp给move出来了。

知道哪里可以正确得到数据, 别的很简单了, 我直接lamda引用传递了response, 在callback中赋值即可

**Comment by jiangdongzi** [comment]
> > 你要这么用，只能把resp给move出来了。
> 
> 知道哪里可以正确得到数据, 别的很简单了, 我直接lamda引用传递了我需要的response (vector<string>), 在callback中赋值即可

**Comment by jiangdongzi** [comment]
> 嗯嗯。另外有一个问题，如果你用同步方式的话，需要注意一下。 例如下面这个例子：
> 
> ```c++
> void http_callback(WFHttpTask *task)
> {
>     WFRedisTask *redis_task = WFTaskFactory::create_redis_task(..., [](void *) { event.signal(...); });
>     event.wait();
> }
> ```
> 
> 如果这种用法，wait所在的线程和signal所在的线程，其实属于同一个线程池。这必然可能导致死锁。 所有，要么保证你wait的线程不是我们框架的线程，要么使用我们的WFWaitGroup。我们的wait group是可以避免这种死锁的。 不过，最好的用法还是不等待。用我们的series就好了。

嗯, wait所在线程是协程库所在线程池, 与workflow不共用, 不过你说的series会考虑看看

**Comment by Barenboim** [comment]
再广告一下，如果你访问brpc的服务，我们也是直接支持brpc协议的噢：https://github.com/sogou/srpc

**Comment by jiangdongzi** [comment]
> 再广告一下，如果你访问brpc的服务，我们也是直接支持brpc协议的噢：https://github.com/sogou/srpc
哈哈, 曾经看到过, 有机会可以试试
