### ISSUE TITLE
自定义协议的客户端task支持长链接吗？

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1114]
使用 WFNetworkTaskFactory<REQ, RESP>::create_client_task(...) 创建client task后在回调里面处理服务端返回的数据，然后能否复用这个task继续给服务端发数据。

**Comment by Barenboim** [comment]
我们的tutorial-10自定义协议client，就是长连接的。不过，对于自定义协议，长连接并不是默认行为，而是需要设置：
~~~cpp
{
    using NTF = WFNetworkTaskFactory<TutorialRequest, TutorialResponse>;
    WFTutorialTask *task = NTF::create_client_task(TT_TCP, host, port, retry_max, std::move(callback));
    task->set_keep_alive(30 * 1000);
    return task;
}
~~~
这里task->set_keep_alive(30*1000)就是把连接保持时间设置为30秒。
连接复用和task复用没有关系，task一般不复用，但连接会复用。并且，连接在进入callback调用之前，就可能已经被其它请求复用了。
client task其实可以复用，但不太建议，因为重新create一个task开销也不是太大。复用task的方法如下：
~~~cpp
template<class REQ, RESP>
void callback(WFNetworkTask<REQ, RESP> *task)
{
    WFComplexClientTask<REQ, RESP> *t = static_cast<...>(task);
    t->set_redirect(TT_TCP, sockaddr, addrlen, "");
}
~~~
这样这个task在callback后会被重新拉起。但是，不一定会复用原连接，因为连接在callback前就归还连接池了。
