### ISSUE TITLE
SSL服务端开启证书认证有问题

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1121]
SSL服务端开启证书认证后回调函数(verify_callback)走不进去，SSL客户端没问题，服务端代码：
    SSL_CTX *ctx = WFGlobal::new_ssl_server_ctx();

    //载入CA证书
    if (SSL_CTX_load_verify_locations(ctx, cacert, NULL)<=0){
        ERR_print_errors_fp(stderr);
        exit(1);
    }

    //SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER|SSL_VERIFY_FAIL_IF_NO_PEER_CERT, verify_callback);
	WFCustomServer server(&params, process);
	if (server.start(m_svrCfg.Port, certfile, keyfile) == 0)
	{
        SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER|SSL_VERIFY_FAIL_IF_NO_PEER_CERT, verify_callback);
        trace_log(INF, "ssl server start success");
		wait_group.wait(); //阻塞，直到调用wait_group.done();
		server.shutdown();
        exit(0);
	}
	else
	{
		trace_log(ERR, "server start failed!");
        exit(1);
	}

verify_callback那一句不管放到start之前还是之后都不行，服务端好像始终就没有进行证书认证。

**Comment by Barenboim** [comment]
这个的原因是并非所有的server用同一个ctx。你无法在外面命到server的ssl ctx

**Comment by Barenboim** [comment]
这个的原因是并非所有的server用同一个ctx。你无法在外面拿到server的ssl ctx

**Comment by Barenboim** [comment]
好像不太对。WFServerBase::get_server_ssl_ctx是每个连接都要调用一次的，主要是给SNI功能使用。没有必要每次连接都调用一次set_verify。我可能需要加个接口减少你的调用次数。

**Comment by Barenboim** [comment]
~~~cpp
class MyHttpServer : public WFHttpServer
{
private:
    bool flag = false;
protected:
    SSL_CTX *get_server_ssl_ctx(const char *)
    {
        SSL_CTX *ctx = this->get_ssl_ctx()
        if (!flag)
        {
             SSL_CTX_set_verify(ctx, ...);
             flag = true;
        }
        return ctx;
    }
};
~~~
这么用试试。

**Comment by coderwxl** [comment]
这样改客户端第一次认证的时候还是不行。我改了下WFServerBase的源码：
`	virtual SSL_CTX *new_ssl_server_ctx()
	{
		SSL_CTX *ssl_ctx = WFGlobal::new_ssl_server_ctx();

		if (!ssl_ctx)
			return NULL;

		SSL_CTX_set_verify(ssl_ctx, SSL_VERIFY_NONE, NULL);
		return ssl_ctx;
	}

int WFServerBase::init_ssl_ctx(const char *cert_file, const char *key_file)
{
	SSL_CTX *ssl_ctx = new_ssl_server_ctx();

	if (!ssl_ctx)
		return -1;

	if (SSL_CTX_use_certificate_file(ssl_ctx, cert_file, SSL_FILETYPE_PEM) > 0 &&
		SSL_CTX_use_PrivateKey_file(ssl_ctx, key_file, SSL_FILETYPE_PEM) > 0 &&
		SSL_CTX_set_tlsext_servername_callback(ssl_ctx, ssl_ctx_callback) > 0 &&
		SSL_CTX_set_tlsext_servername_arg(ssl_ctx, this) > 0)
	{
		this->set_ssl(ssl_ctx, this->params.ssl_accept_timeout);
		return 0;
	}

	SSL_CTX_free(ssl_ctx);
	return -1;
}
`
我应用里面override这个函数就可以了

**Comment by coderwxl** [comment]
@Barenboim 还有其它更好的办法吗，没有我就close了

**Comment by Barenboim** [comment]
现在这个work吗？你先帮我试一下。
我也在想别的方法，避免派生。

**Comment by Barenboim** [comment]
你看看这个修改：https://github.com/sogou/workflow/pull/1122
和你的思路比较接近，通过派生server的new_ssl_ctx方法来产生初始的SSL CTX。
~~~cpp
MyHttpServer : public WFHttpServer
{
public:
    using WFHttpServer::WFHttpServer;
protected:
    SSL_CTX *new_ssl_ctx(const char *cert, const char *key) override
    {
        SSL_CTX *ctx = WFHttpServer::new_ssl_ctx(cert, key);
        if (ctx)
        {
            // set verify here.
        }
        return ctx;
    }
}
~~~

**Comment by Barenboim** [comment]
另外还有一种方法，原来的代码也可以用，直接派生CommService的init_ssl()：
~~~cpp
class MyHttpServer : public WFHttpServer
{
private:
    int init_ssl(SSL *ssl) override   // this is from CommService
    {
        SSL_set_verify(ssl, ...);
        return 0;
    }
};
~~~
你可以都帮我们试试看。

**Comment by coderwxl** [comment]
派生new_ssl_ctx测试没问题。
init_ssl是私有的，子类派生不了。

**Comment by Barenboim** [comment]
> 派生new_ssl_ctx测试没问题。
> init_ssl是私有的，子类派生不了。

init_ssl是私有的，但私有的虚函数是可以被子类派生的。我们大量虚函数都是私有。
