### ISSUE TITLE
WFRedisServer如果处理Redis协议保序

### ISSUE THREAD

**Issue by redkongdong** [sogou/workflow#1123]
你好，请教一下WFRedisServer是单线程Server吗？请问是如何处理Redis协议保序的？

**Comment by Barenboim** [comment]
WFRedisServer和WFHttpServer是完全一样的逻辑。我们这边已经大量使用了。
用的时候注意一下，用户的AUTH请求和SELECT请求，可以把信息（密码，数据库ID）存在连接上下文上，之后的请求可能需要用到。
你说的保序是什么意思？是返回的顺序和请求顺序一致的问题吗？

**Comment by redkongdong** [comment]
> 

是的，返回顺序要求和请求顺序一致

**Comment by Barenboim** [comment]
哈哈哈，这个我们的处理方式简单粗暴。workflow所有server禁止pipeline，上一个请求没处理完之前收到数据一律当作垃圾数据，连接断开。一般来讲，你用我们这个写redis server是面向分布式集群的，pipeline可能语义上本来就存在问题了。所以直接禁用问题不大。
另外，都是多线程的。

**Comment by redkongdong** [comment]
好的，感谢

**Comment by Barenboim** [comment]
这个可以满足你们需求吗

**Comment by redkongdong** [comment]
> 这个可以满足你们需求吗

我们有个中间件proxy用单连接和server之间通讯，感觉短连接或连接池是OK的，单连接server好像没法去断连接？一个连接上有可能发多个有效的请求

**Comment by Barenboim** [comment]
单连接就是指pipeline吧？改成连接池就可以了。你们是brpc吗？

**Comment by redkongdong** [comment]
非pipeline也有保序的要求，一个长连接上发出的所有请求需要按照请求顺序返回
是的，首先得把中间件改成连接池，嗯嗯，用的brpc现在

**Comment by Barenboim** [comment]
非pipeline那无论如何都是保存的，因为如果有一条没返回根本不接受下一条。
你之后可以试试用我们的srpc，直接和brpc互通。可以看看这两个例子：
https://github.com/sogou/srpc/blob/master/tutorial/tutorial-05-brpc_pb_server.cc
https://github.com/sogou/srpc/blob/master/tutorial/tutorial-06-brpc_pb_client.cc

**Comment by redkongdong** [comment]
> 非pipeline那无论如何都是保序的，因为如果有一条没返回根本不接受下一条。 你之后可以试试用我们的srpc，直接和brpc互通。可以看看这两个例子： https://github.com/sogou/srpc/blob/master/tutorial/tutorial-05-brpc_pb_server.cc https://github.com/sogou/srpc/blob/master/tutorial/tutorial-06-brpc_pb_client.cc

好的，感恩
