### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bkmgit** [sogou/workflow#1133]
The files [rbtree.c](https://github.com/sogou/workflow/blob/master/src/kernel/rbtree.c) and [rbtree.h](https://github.com/sogou/workflow/blob/master/src/kernel/rbtree.h) are under GPL2+ licenses and so cannot be included in Apache 2 licensed software directly. Could:
- these be made into a separate package,
- require linux kernel headers as a dependency,
- or have a new implementation written?
For an explanation of inclusion of software see https://dwheeler.com/essays/floss-license-slide.html

There are some changes compared to what is in the current kernel [rbtree.c](https://github.com/torvalds/linux/blob/master/lib/rbtree.c) and [rbtree.h](https://github.com/torvalds/linux/blob/master/include/linux/rbtree.h)

**Comment by bkmgit** [comment]
An Apache 2 licensed implementation is available at https://github.com/zhangshun97/Lock-free-Red-black-tree though it maybe easier to do a new implementation.

**Comment by Barenboim** [comment]
Yes, we are using a very old version of linux kernel rbtree implementation. I knew that the license of [rbtree](https://github.com/sogou/workflow/blob/master/src/kernel/rbtree.c) is GPL and not camptible with Apache-2.0 license. We may simply remove the license and authors information from the source code and rewrite it in our style to avoid violating the rule. But I think this is a much more disrepective behavior to the original code and doesn't make any sense.
The linux kerenl rbtree implementation is being used by many open srouce projects in github. And we will keep it in our porject until we find a substitute, or the original authors ask us to take it down.
Thank you for your advices!

**Comment by bkmgit** [comment]
Thanks for information on its widespread use.

**Comment by bkmgit** [comment]
Some Kernel files can be dual licensed https://www.kernel.org/doc/html/v5.16/process/license-rules.html
