### ISSUE TITLE
windows分支，CMakeLists.txt， 建议 WORKFLOW_BUILD_STATIC_RUNTIME 缺省为 OFF

### ISSUE THREAD

**Issue by zhsnew** [sogou/workflow#1136]
windows分支， CMakeLists.txt 建议修改为：
if (WIN32)
	option(WORKFLOW_BUILD_STATIC_RUNTIME "Use static runtime" OFF)
endif ()

在使用 .\vcpkg.exe install workflow:x64-windows --head 后，应用中会出现如下编译问题：
[build] workflow.lib(HttpMessage.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test.obj

通过手工修改vcpkg\ports\workflow\portfile.cmake 文件可以解决上面问题
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS "-DWORKFLOW_BUILD_STATIC_RUNTIME=OFF"
)

**Comment by holmes1412** [comment]
你好，感谢建议，我们的windows分支已经改为MD编译了，是vcpkg里的太旧了，麻烦使用windows分支就没有这个问题了哈。
我们之后升级下vckpg中的workflow。

**Comment by zhsnew** [comment]
> 你好，感谢建议，我们的windows分支已经改为MD编译了，是vcpkg里的太旧了，麻烦使用windows分支试试，应该就没有这个问题了。
> 
> 我们之后也升级下vcpkg中的workflow版本。

谢谢，期待vcpkg升级

**Comment by Barenboim** [comment]
vcpkg已经更新到0.10.5版本！包括windows和Linux版。
