### ISSUE TITLE
想搞个落地应用，为啥我这个程序，每次刷新的时候，都会进入 两次啊？ 

### ISSUE THREAD

**Issue by ChunelFeng** [sogou/workflow#1142]
如下图

![image](https://user-images.githubusercontent.com/37905059/211163891-6e8045e5-6a34-41cf-a168-3a466445ab4d.png)

**Comment by Barenboim** [comment]
每次刷新是指什么？浏览器刷新网页吗。

**Comment by ChunelFeng** [comment]
是的，网页刷新。每次打印出来的加过，都是 +2

**Comment by Barenboim** [comment]
没什么道理啊，只能是发了两次请求。你第一次访问的时候，val是加1吗？之后每次刷新都加2？

**Comment by ChunelFeng** [comment]
我尝试使用 curl 命令去获取，的确是 进入一次。    但是用 浏览器刷新，无论是第几次，必现的每次都是两次。代码在这里：https://github.com/CDev-io/CGraph-NIO ，随时可以review。

![image](https://user-images.githubusercontent.com/37905059/211183995-151af15a-4555-45de-aafc-3c16272aa858.png)

by the way，我想搞的应用逻辑是，CGraph的开头的node，接收http请求，然后收录请求参数，经过一个CGraph自己的dag计算，最后一个node，返回 response 结果。

大佬有没有这方面的tutorial，跪求提供一个

**Comment by Barenboim** [comment]
可能是你的F5键卡住了？
框架外的异步过程，可以用counter堵住series，然后在异步过程结束的callback里打开counter。在计数器的文档里有介绍。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月8日(周日) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 想搞个落地应用，为啥我这个程序，每次刷新的时候，都会进入 两次啊？  (Issue #1142)




 
我尝试使用 curl 命令去获取，的确是 进入一次。    但是用 浏览器刷新，无论是第几次，必现的每次都是两次。代码在这里：https://github.com/CDev-io/CGraph-NIO ，随时可以review。
 

 
by the way，我想搞的应用逻辑是，CGraph的开头的node，接收http请求，然后收录请求参数，经过一个CGraph自己的dag计算，最后一个node，返回 response 结果。
 
大佬有没有这方面的tutorial，跪求提供一个

**Comment by Barenboim** [comment]
我在Mac上试了一下，chrome浏览器无论是第一次打开还是刷新，都会连续发两条请求，而且是在同一个连接上，得到http回复后又立刻发一条。Saferi浏览器没这个问题，每次都只发一条请求。
我也不清楚这是chrome的什么策略，但你的程序应该是正确的。
关于Server和其它异步引擎结合使用，看这里：https://github.com/sogou/workflow/blob/master/docs/about-counter.md#server与其它异步引擎结合使用

**Comment by ChunelFeng** [comment]
看了一下例子，感觉想写个dag的后台服务，这样就可以了。哈哈哈，还是挺简单的。

不过有个问题，无法使用一个 pipeline ，同时应对两次外部请求，需要在pipeline->run() 前面加锁。
因为CGraph的pipeline 内部的所有参数信息，都是有状态的。

![image](https://user-images.githubusercontent.com/37905059/212476018-073350b6-b03f-4bfc-b76e-67529de51f91.png)

**Comment by Barenboim** [comment]
这个pipeline是你自己的类啊？你说的无法使用，是什么原因呢。

**Comment by Barenboim** [comment]
你这个做法，是占着通信线程计算？你不是有自己的线程池的吗。

**Comment by ChunelFeng** [comment]
是占用了通信线程在计算。无论是用通信的thread，还是我内部自己搞个 thread，暂时都无法解决一个问题。
就是 pipeline内部，多个 node之间的参数传递，是共享一个 指针副本的。

多次请求，发到同一个pipeline上，肯定会导致参数管理混乱的。

我想一下，没有其他办法的话，我尝试CGraph内部new出来n个相同的pipeline变量，放到一个 free_list中，
如果有请求来的话，从 free_list 中去拿 pipeline，然后run吧。

这样至少能确保多次请求之间，互相不影响。

**Comment by Barenboim** [comment]
那是因为我们的server是多线程的啊，你的pipeline不是线程安全，那肯定不行啊。

**Comment by ChunelFeng** [comment]
是的。我要改一下了

**Comment by ChunelFeng** [comment]
哈哈哈，改好了。改成 manager里，管控了n个相同的pipeline逻辑，
每次请求来的时候，拿出来一个进行运行了

![image](https://user-images.githubusercontent.com/37905059/212542545-c0c18ee9-2c6d-413b-b1bc-5c7043d1e08a.png)

**Comment by Barenboim** [comment]
你这里直接写成thread_local的就可以了，都不用搞池子了。

**Comment by ChunelFeng** [comment]
你的意思是，这样写就可以了？不需要我来管控 那个pipeline是可执行状态的了，是么？

![image](https://user-images.githubusercontent.com/37905059/213435416-4d6742c4-ca28-4684-9310-9c8b0a4a4e4c.png)

**Comment by Barenboim** [comment]
你这么写不知道对不对，一般是写在process函数所在文件的全局变量里。你都试试看吧。
