### ISSUE TITLE
SeriesWork::push_front() 是否只能在 SeriesWork start 前执行，不能在运行过程中执行？

### ISSUE THREAD

**Issue by MoonChasing** [sogou/workflow#1144]
`SeriesWork::push_front()` 在使用时有什么要额外注意的吗？
我阅读代码时，感觉它不能在 `SeriesWork` 运行时调用，我的理解是正确的吗？

**Comment by Barenboim** [comment]
没有什么特别的啊。在任务的callback里调用push_front没有任何问题。为什么觉得不能在运行时调用？是指不能在series运行过程中，由一个series之外的独立线程调用吗？那是不行的，这么做本来也很危险。一般都是series里的任务才能对series进行操作（可以例外，例如用counter堵住series，确保series不会运行结束，然后其他地方对这个series执行push_back）。

**Comment by MoonChasing** [comment]
`push_front` 是将 `SubTask` 放到当前 `SeriesWork` 的最前面，如果在一个任务 `callback` 中调用，一般来说 `callback` 调用时这个任务还没有 `pop` 出，这时会将新任务放在当前未 `pop` 出的任务前面，这种情况下是任务怎么安排调度的呢？
还是说这种情况可以先 `pop` 后 `callback`？

**Comment by Barenboim** [comment]
不是的，任务是先pop再执行的。一个典型的done()实现是这样子的：
~~~cpp
class SomeTask : public SubTask
{
protected:
	virtual SubTask *done()
	{
		SeriesWork *series = series_of(this);

		if (this->callback)
			this->callback(this);

		delete this;
		return series->pop();
	}
}
~~~
done()返回的就是下一个执行任务。可以看到，是callback之后从series里取出下一个任务执行。

**Comment by MoonChasing** [comment]
正如你说的，如果在 `callback` 中调用 `push_front` ，那么不是会将新 Task 放到当前执行的、还未 `pop` 的 Task 之前吗？ 那我们现在的 `SeriesWork` 顺序就会是  新加入的任务 -> 当前正在执行 `callback` 还未 `pop` 的任务 -> 后续其他任务。执行完 `callback` 后执行 `pop`，我感觉 `SeriesWork` 就会乱了。

**Comment by Barenboim** [comment]
不是的，你对pop和执行的顺序理解有误：
~~~cpp
class SomeTask : public SubTask
{
protected:
	virtual SubTask *done()
	{
		SeriesWork *series = series_of(this);

		if (this->callback)    // 这个this是正在callback的
			this->callback(this);  // 这里面执行了push_front()

		delete this;  // callback的任务已经被delete了
		return series->pop();  // 这里pop出来的，就是callback里push_front的任务。done()的返回值是series里下一个执行的任务
	}
}
~~~

**Comment by MoonChasing** [comment]
写了个小例子，gdb 了一下，了解了，感谢。 `this->first` 是不在队列中的，执行 `this->first->done()` 时， `pop()` 出来的是 `this->queue[this->front]`，我之前理解成了此时才 `pop` 出 `this->first`。 也就是说， Task 是先出队列后被执行的，而不是先执行，执行完后再出队列的，我这里的顺序搞反了。非常感谢。
