### ISSUE TITLE
是否有将两个 SeriesWork 拼接在一起的接口

### ISSUE THREAD

**Issue by MoonChasing** [sogou/workflow#1145]
是否有将两个 SeriesWork 拼接在一起的接口，类似 splice 操作，是否有这个接口的需要？

**Comment by Barenboim** [comment]
没有join/splice两个series的接口。你的时机需求是不是想在series里嵌套series？
这个可以用module，module是一种任务，相当于series里的一个子series。这个挺有用的，你看看能不能满足需求：
https://github.com/sogou/workflow/blob/master/docs/about-module.md

**Comment by MoonChasing** [comment]
好的，非常感谢，我先了解下~
