### ISSUE TITLE
新建一个空url请求task，没有立刻返回，win和linux都是一样，请求时长都要2s左右，代码的结果如下

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#1146]
WFHttpTask *task;
    std::string url = "http://localhost:3344";
    double time_Start = (double)clock();
    double time_End = 0.0;
    qDebug()<<"start:";
    WFFacilities::WaitGroup wait_group(1);
    task = WFTaskFactory::create_http_task(url, 0, 0, [&](WFHttpTask *t){
        protocol::HttpResponse *resp = task->get_resp();
        int state = task->get_state();

        if(state != WFT_STATE_SUCCESS)
        {
            qDebug()<<"url: "<<url.c_str()<<".ask failed!";
            wait_group.done();
            time_End = (double)clock();
            qDebug()<<"ask time: "<<(time_End - time_Start)/1000.0<<"s. url:"<<url.c_str();
            return;
        }
        std::string content = protocol::HttpUtil::decode_chunked_body(resp);
        if (!nlohmann::json::accept(content))
        {
            qDebug()<<"url: "<<url.c_str()<<".ask failed!";
            wait_group.done();
            return;
        }
        res = nlohmann::json::parse(content);
        wait_group.done();
    });
    protocol::HttpRequest *req = task->get_req();
    req->set_method("GET");
    req->add_header_pair("Accept", "*/*");
    req->add_header_pair("User-Agent", "Wget/1.14");
    req->add_header_pair("Connection", "close");
    task->start();
    wait_group.wait();

    time_End = (double)clock();
    qDebug()<<"ask time1: "<<(time_End - time_Start)/1000.0<<"s. url:"<<url.c_str();
![image](https://user-images.githubusercontent.com/62458770/211436298-f8dcc944-f4c4-4c42-9364-c0b293eee120.png)

**Comment by MoonChasing** [comment]
多线程不要使用 `clock()` 。

**Comment by HzjFirst** [comment]
WFFacilities::WaitGroup这个不是线程阻塞吗？感觉这样算是对的，打印的时间基本和算的时间能对应上，那怎么才能计算耗时？我学习一下，重新打印

**Comment by MoonChasing** [comment]
`clock()` 函数返回从开启这个程序进程到程序中调用clock()函数时之间的CPU时钟计时单元（clock tick）数，如果是多线程的话，每个线程都会记录到这里。
你说的 `WFFacilities::WaitGroup`线程阻塞我不太理解是啥意思，我也是个学习者。
多线程计算耗时的话，网上一搜 “C语言多线程计算耗时”应该就会有一大堆方法啦，总之就是使用开始/结束时的真正时间差，而非是 CPU clock tick 数。

**Comment by HzjFirst** [comment]
嗯嗯，这样打印可能有误差，但是程序就是进入假死状态1-2s左右，你也可以测试一下

**Comment by MoonChasing** [comment]
好的，我有空尝试测下~

**Comment by Barenboim** [comment]
sysconf(_SC_CLK_TCK)是1000?我这么记得这个不是100就是10000。

**Comment by Barenboim** [comment]
我们的初次启动会构造通信调度器，这里会默认产生20多个线程。但如果耗时高达1秒以上肯定是不对的。
我在我的wsl上实验的话，后端开一个echo server，然后用paralle_wget抓取，实际墙上耗时大概1ms。parallel_wget的逻辑和你这个程序是一样的。

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/211495658-59697c41-2649-40ea-9346-259b5e7e7bc7.png)
我没有看过源码，还没有那个水平看源码实现，只会用这个库请求一些简单的http请求，只能发现现象，不是专业做web开发这块的，不懂http请求原理，不能提供很好的解决思路

**Comment by Barenboim** [comment]
你好，你直接在tutorial目录里，运行：
$ ./time paralle_wget http://127.0.0.1:3344
看一看打印出来的时间是多少。

**Comment by MoonChasing** [comment]
把 1000.0 换成 CLOCKS_PER_SEC 。

**Comment by Barenboim** [comment]
> 你好，你直接在tutorial目录里，运行： $ ./time paralle_wget http://127.0.0.1:3344 看一看打印出来的时间是多少。

@HzjFirst

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/211502869-09514a08-036c-4a28-9fef-24ba9a3020ec.png)
这样好像是正确的，代码写的这个有什么区别啊？

**Comment by Barenboim** [comment]
啊，你先把http server打开啊。让他得到一个正确的结果。

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/211507829-e526e00e-989c-4f96-b509-9390ddbb3460.png)
大佬，你说的好像有道理，就是这样，但是第一次还是慢，放到第二个请求就快了

**Comment by Barenboim** [comment]
还是不太对。那我们的parallel_get为什么可以那么快呢？我们一样要初始化通信引擎和开线程的啊。

**Comment by HzjFirst** [comment]
难道是我环境的问题，等有时间我再好好排查一下，例子里面的速度确实很快，我再好好对比一下，谢谢了，大佬
