### ISSUE TITLE
centos8下编译tutorial时出现referenced by variable WORKFLOW_INCLUDE_DIR does not exist

### ISSUE THREAD

**Issue by tiobei** [sogou/workflow#1147]
如图进行模块编译
[root@qos tutorial]# make
mkdir -p build.cmake
rm -rf build.cmake/CMakeCache.txt
cd build.cmake && cmake3 -D KAFKA= -D MYSQL= -D REDIS= /usr/local/workspace/cpp/workflow/workflow-0.9.8/tutorial
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1k")  
CMake Error at /usr/local/workspace/cpp/workflow/workflow-0.9.8/workflow-config.cmake:11 (message):
  File or directory
  /usr/local/workspace/workspace/cpp/workflow/workflow-0.9.8/_include
  referenced by variable WORKFLOW_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /usr/local/workspace/cpp/workflow/workflow-0.9.8/workflow-config.cmake:28 (set_and_check)
  CMakeLists.txt:13 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/local/workspace/cpp/workflow/workflow-0.9.8/tutorial/build.cmake/CMakeFiles/CMakeOutput.log".
make: *** [GNUmakefile:14：all] 错误 1

在workflow主目录下执行make命令是可以的

**Comment by Barenboim** [comment]
你这个版本有点太老了。先下载最新代码试吧。
根目录make，然后再到tutorial里make，应该没什么问题的。

**Comment by tiobei** [comment]
> 你这个版本有点太老了。先下载最新代码试吧。 根目录make，然后再到tutorial里make，应该没什么问题的。

选择最新版本编译时还是有这个错，cmake版本3.20.4，gcc版本8.5.0 20210514 (Red Hat 8.5.0-15) (GCC)
[root@localhost tutorial]# make
mkdir -p build.cmake
rm -rf build.cmake/CMakeCache.txt
cd build.cmake && cmake3 -D KAFKA= -D MYSQL= -D REDIS= /usr/local/workspace/workflow/tutorial
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.1k")  
CMake Error at /usr/local/workspace/workflow/workflow-config.cmake:11 (message):
  File or directory /usr/workspace/workflow/_include referenced by variable
  WORKFLOW_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /usr/local/workspace/workflow/workflow-config.cmake:28 (set_and_check)
  CMakeLists.txt:17 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/local/workspace/workflow/tutorial/build.cmake/CMakeFiles/CMakeOutput.log".
make: *** [GNUmakefile:14：all] 错误 1


根目录下经过make构建生成的workflow-config.cmake内容如下：
[CMakeOutput.log](https://github.com/sogou/workflow/files/10388141/CMakeOutput.log)

 6 get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
  7 
  8 macro(set_and_check _var _file)
  9   set(${_var} "${_file}")
 10   if(NOT EXISTS "${_file}")
 11     message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
 12   endif()
 13 endmacro()
 14 
 15 macro(check_required_components _NAME)
 16   foreach(comp ${${_NAME}_FIND_COMPONENTS})
 17     if(NOT ${_NAME}_${comp}_FOUND)
 18       if(${_NAME}_FIND_REQUIRED_${comp})
 19         set(${_NAME}_FOUND FALSE)
 20       endif()
 21     endif()
 22   endforeach()
 23 endmacro()
 24 
 25 ####################################################################################
 26 
 27 set(WORKFLOW_VERSION "0.10.5")
 28 set_and_check(WORKFLOW_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/workspace/workflow/_include")
 29 set_and_check(WORKFLOW_LIB_DIR "${PACKAGE_PREFIX_DIR}/workspace/workflow/_lib")
 30 
 31 if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/workflow-targets.cmake")
 32     include ("${CMAKE_CURRENT_LIST_DIR}/workflow-targets.cmake")
 33 endif ()
 34 
 35 check_required_components(workflow)

**Comment by Barenboim** [comment]
~~~sh
cd build.cmake && cmake3 -D KAFKA= -D MYSQL= -D REDIS= /usr/local/workspace/workflow/tutorial
~~~
这个编译命令好奇怪，现在的版本应该是还有“-D CONSUL=” 和“-D UPSTREAM=”
你是一个全新的环境吗？

**Comment by tiobei** [comment]
@Barenboim 项目我是git clone的master分支，运行环境是通过vmware安装的centos8 stream

**Comment by Barenboim** [comment]
但是，我用最新代码编译，这行是这样的：
~~~sh
cd build.cmake && cmake -D CONSUL= -D KAFKA= -D MYSQL= -D REDIS= -D UPSTREAM= /home/xiehan/github/workflow
~~~
和你打出来的信息不一样。

**Comment by Barenboim** [comment]
我知道了，你好像还没有make出我们的库啊。
你要先在workflow目录下make，再到tutorial里make。
因为你直接在tutorial里make，外面的_include和_lib目前还没有建立，所以找不到目录。

**Comment by Barenboim** [comment]
😂这个真的不知道了。我们明天转群里，让群友看看吧。或者你再研究一下cmake。
你现在的错误信息，和我直接在tutorial里make是一样的，所以我以为你外层没有make。

**Comment by holmes1412** [comment]
hi~ 仔细看了下，有几个路径都对不上，怀疑依然还是用旧版编译、没有清空某些cache、曾经改过Cmake文件或者挪过目录。

1、编译命令还是比较旧，新版的make已经加上CONSUL了，执行make应该类似：
mkdir -p build.cmake
cd build.cmake && cmake `-D CONSUL=` -D KAFKA= -D MYSQL= -D REDIS= -D UPSTREAM= /search/ted/workflow/workflow_1412

2、workflow-config.cmake中的${PACKAGE_PREFIX_DIR}没有被替换。如果按我上述编译，这个文件应该长这样：
```
 27 set(WORKFLOW_VERSION "0.10.5")                                                  
 28 set_and_check(WORKFLOW_INCLUDE_DIR "/search/ted/workflow/workflow_1412/_include")
 29 set_and_check(WORKFLOW_LIB_DIR "/search/ted/workflow/workflow_1412/_lib")       
```
但是我看你的还是
```
28 set_and_check(WORKFLOW_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/workspace/workflow/_include")
```

3、WORKFLOW_INCLUDE_DIR的路径两次都比较奇怪：

第一次用0.9.8版本的时候，路径是：
 `/usr/local/workspace/cpp/workflow/workflow-0.9.8`/tutorial
但是WORKFLOW_INCLUDE_DIR变成了
`/usr/local/workspace/workspace/cpp/workflow/workflow-0.9.8`/_include
前缀的中间多了一个`workspace`

第二次使用0.10.5版本的时候，路径是：
`/usr/local/workspace/workflow`/tutorial
但是WORKFLOW_INCLUDE_DIR变成了
`/usr/workspace/workflow`/_include 
前缀的中间少了一个`local`

这个INCLUDE和LIB的路径是在CMakeLists.txt中24、25行指定的。
```
 24 set(INC_DIR ${PROJECT_SOURCE_DIR}/_include CACHE PATH "workflow inc")          
 25 set(LIB_DIR ${PROJECT_SOURCE_DIR}/_lib CACHE PATH "workflow lib") 
```
麻烦确认下是否你是否曾经改过这块的代码，或者手动挪动过目录。建议重新拉取workflow项目进行编译～

**Comment by tiobei** [comment]
@holmes1412 @Barenboim 谢谢解答，现在已经好了，重新拉取最新代码，换一个编译环境确实可以了。之前的系统有点问题，多谢多谢！

**Comment by NickWuzh** [comment]
hi~ 我在麒麟ky10环境下编译遇到相同的问题。
我在`workflow-config.cmake`下多加了一个`../`解决了该问题。
```cmake
 6 get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../../" ABSOLUTE) 
```
