### ISSUE TITLE
GPL2 License

### ISSUE THREAD

**Issue by bkmgit** [sogou/workflow#1148]
Can a copy of [GPL2 license](https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt) be added to the repository? It is mentioned in [rbtree.h](https://github.com/sogou/workflow/blob/master/src/kernel/rbtree.h#L15) and [rbtree.c](https://github.com/sogou/workflow/blob/master/src/kernel/rbtree.c#L16)

**Comment by Barenboim** [comment]
Yes. I think this is a good suggestion. Would you like to create a pull request for us?

**Comment by bkmgit** [comment]
Pull request in progress

**Comment by Barenboim** [comment]
Thanks you so much!

**Comment by bkmgit** [comment]
没关系
