### ISSUE TITLE
workflow 是否支持流式的请求

### ISSUE THREAD

**Issue by kevinmgyu** [sogou/workflow#1162]
您好，我这里的使用场景是比如语音的输入，用户是流式输入，workflow是否支持类似grpc的双向流式方式

**Comment by Barenboim** [comment]
语音流式场景比较不太好搞。目前的server结构都是收一条完整的消息再处理。除非你用我们底层的纯C的模块写，但就相当于不是使用workflow了，只是在用我们底层通讯。
这块的代码在：
https://github.com/sogou/workflow/blob/master/src/kernel/poller.h
https://github.com/sogou/workflow/blob/master/src/kernel/poller.c
这里实现的是适合于任何场景的网络模块（不包括UDP server，但也很好加）。
workflow在Communicator模块就简化成接近request->response模式了。

**Comment by kevinmgyu** [comment]
> 语音流式场景比较不太好搞。目前的server结构都是收一条完整的消息再处理。除非你用我们底层的纯C的模块写，但就相当于不是使用workflow了，只是在用我们底层通讯。 这块的代码在： https://github.com/sogou/workflow/blob/master/src/kernel/poller.h https://github.com/sogou/workflow/blob/master/src/kernel/poller.c 这里实现的是适合于任何场景的网络模块（不包括UDP server，但也很好加）。 workflow在Communicator模块就简化成接近request->response模式了。

好的，多谢您的回复
