### ISSUE TITLE
代码问题请教

### ISSUE THREAD

**Issue by sourcema** [sogou/workflow#1170]
您好，请问下__poller_thread_routine接口中：node > (struct __poller_node *)1 这个判断是什么意思？

**Comment by Barenboim** [comment]
你好。这里， node为NULL或(struct __poller_node  *)1分布代表timer事件和pipe事件，否则为普通的fd事件。由于fd事件的概率比较大，这里相当于通过一次判断就确定是fd事件。否则如果这么写：
~~~c
{
    if (node == NULL)
          handle_timer();
    else if (node == (void *1)
          handle_pipe();
     else
          handle_fd_event(node);
}
~~~
大多少情况下，就会多一次条件判断。

**Comment by sourcema** [comment]
> node为NULL或(struct __poller_node *)1分别代表timer事件和pipe事件

请问这个是如何对应的，是通过(struct __poller_node *)1后，根据结构体中字段值确定的吗？

**Comment by Barenboim** [comment]
不是啊，NULL和1是两个特殊值，不是一个真的指针。通过判断NULL和1，可以确定是timer事件或pipe事件。

**Comment by sourcema** [comment]
这个规则是代码里限定的么？

**Comment by Barenboim** [comment]
~~c
			node = (struct __poller_node *)__poller_event_data(&events[i]);
			if (node > (struct __poller_node *)1)
			{
				switch (node->data.operation)
				{
				...
				}
			}
			else if (node == (struct __poller_node *)1)
				has_pipe_event = 1;
~~~
是的啊。只是这个代码特定的。在open pipe的时候，转了一个(struct __poller_node *)1作为epoll的数据：
~~~c
static int __poller_open_pipe(poller_t *poller)
{
	int pipefd[2];

	if (pipe(pipefd) >= 0)
	{
		if (__poller_add_fd(pipefd[0], EPOLLIN, (void *)1, poller) >= 0)
		{
			poller->pipe_rd = pipefd[0];
			poller->pipe_wr = pipefd[1];
			return 0;
		}

		close(pipefd[0]);
		close(pipefd[1]);
	}

	return -1;
}
~~~
这个1只是一个标记而己。

**Comment by sourcema** [comment]
好的明白了，谢谢。
