### ISSUE TITLE
kafka benchmark性能压测代码是否有样例？

### ISSUE THREAD

**Issue by hardy-luo** [sogou/workflow#1171]
1. kafka benchmark性能压测代码是否样例？类似rdkafka的
2. 能否帮忙看看我写的benchmark哪里有问题？
报错信息如下：
error msg: Kafka produce api failed
Failed. Press Ctrl-C to exit.
Segmentation fault

```c++
int main(int argc, char *argv[]) {
    KafkaConfig config;
    config.set_compress_type(compress_type);
    config.set_client_id("workflow");
    config.set_produce_acks(-1);

    client.init(url);
    WFKafkaTask* task = client.create_kafka_task("api=produce", 3, kafka_callback);
    task->set_config(std::move(config));

    pthread_t pId;
    int ret= pthread_create(&pId, NULL, do_produce, (void *)task);
    printf("pthread_create start\n");

    if(ret!=0){
        printf("create pthread error!\n");
        exit(1);
    }
    task->start();
    printf("task start\n");
    pthread_join(pId,NULL);
    wait_group.wait();
    return 0;
}    

void* do_produce(void* ptr) {
    WFKafkaTask* task = (WFKafkaTask*)ptr;
    while (1) {
        sleep(1);
        char buf[1 * 1024];
        for (size_t i = 0; i < sizeof(buf); ++i) {
            buf[i] = '1' + rand() % 128;
        }
        KafkaRecord record;
        record.set_value(buf, sizeof(buf));
        task->add_produce_record("demo4", -1, std::move(record));
        printf("task add_produce_record\n");
    }
}```

**Comment by Barenboim** [comment]
先调一下代码格式吗？

**Comment by Barenboim** [comment]
一般来讲，用workflow没有自己创建线程的需要。看到pthread_create，应该是用错了。

**Comment by Barenboim** [comment]
大概看了一下，用法完全是错误的。应该每次produce产生一个task。可以先参考一下这个fetch的例子：
https://github.com/sogou/workflow/issues/1160
之后我们在出一个完整的Kafka示例。

**Comment by Barenboim** [comment]
你想要一秒produce一个记录，就一秒start一个task就可以了，每次都重新create，填写内容。

**Comment by huiluo2008** [comment]
> 你想要一秒produce一个记录，就一秒start一个task就可以了，每次都重新create，填写内容。

明白了，start类似一个flush操作，发送一个批次的数据是吧

**Comment by Barenboim** [comment]
我们每次操作都是一个独立的任务，需要的时候就发起就可以了。其实非常直观。task对象本身是一次性的，到callback之后生命周期就结束了。
和批次也没什么关系，总之就是你想produce的时候，就发起任务就好

**Comment by huiluo2008** [comment]
`#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>

#include "../src/include/workflow/WFKafkaClient.h"
#include "../src/include/workflow/KafkaMessage.h"
#include "../src/include/workflow/KafkaResult.h"
#include "../src/include/workflow/WFTaskFactory.h"
#include "../src/include/workflow/WFFacilities.h"
#include "../src/include/workflow/WFGlobal.h"

//#include "workflow/WFKafkaClient.h"
//#include "workflow/KafkaMessage.h"
//#include "workflow/KafkaResult.h"
//#include "workflow/WFTaskFactory.h"
//#include "workflow/WFFacilities.h"
//#include "workflow/WFGlobal.h"


#define RD_MIN(a, b) ((a) < (b) ? (a) : (b))
#define RD_MAX(a, b) ((a) > (b) ? (a) : (b))

using namespace protocol;

WFFacilities::WaitGroup wait_group(1);
std::string url, topic;
std::string client_id("wfkafka");

int retry_max = 2;

WFKafkaClient client;
std::atomic<bool> running = {true};

void signal_handler(int signo) {
    running = false;
}

void kafka_produce_callback(WFKafkaTask *);

WFKafkaTask *create_produce_task(bool first = false) {
    WFKafkaTask *task;
    KafkaConfig config;

    config.set_client_id(client_id.c_str());
    config.set_produce_msg_max_bytes(2 * 10000 * 1024);


    task = client.create_kafka_task("api=produce", retry_max, kafka_produce_callback);
    task->set_config(std::move(config));


    char *msgpattern  = "librdkafka_performance testing!";
    int msgsize       = -1;
    if (msgsize == -1){
        msgsize = (int)strlen(msgpattern);
    }

    int minlen = (int)(strlen("LATENCY:") + strlen("18446744073709551615 ") + 1);
    msgsize    = RD_MAX(minlen, msgsize);

    char *sbuf;
    off_t rof   = 0;
    size_t plen = strlen(msgpattern);


    sbuf = malloc(msgsize);
    /* Copy payload content to new buffer */
    while (rof < msgsize) {
        size_t xlen = RD_MIN((size_t)msgsize - rof, plen);
        memcpy(sbuf + rof, msgpattern, xlen);
        rof += (off_t)xlen;
    }

//    char buf[1 * 1024];
//    for (size_t i = 0; i < sizeof(buf); ++i) {
//        buf[i] = '1' + rand() % 128;
//    }

    for (size_t i = 0; i < 10000; ++i) {
        KafkaRecord record;
        record.set_value(sbuf, msgsize);
        task->add_produce_record("demo4", -1, std::move(record));
    }
    return task;
}

void kafka_produce_callback(WFKafkaTask *task) {
    SeriesWork *series = series_of(task);
    int state = task->get_state();
    int error = task->get_error();
    bool wait = false;

    if (state != WFT_STATE_SUCCESS) {
        wait = true;
        printf("produce Failed state:%d error:%d errmsg:%s\n", state, error, WFGlobal::get_error_string(state, error));
    } else {
        std::vector<std::vector<KafkaRecord *>> records;
        task->get_result()->fetch_records(records);
        for (const auto &v: records) {
            for (const auto &w: v) {
                const void *value;
                size_t value_len;
                w->get_value(&value, &value_len);
//                    msg_delivered(w->get_offset(), value, value_len);
                printf("produce\ttopic: %s, partition: %d, status: %d, offset: %lld, val_len: %zu\n", w->get_topic(),w->get_partition(), w->get_status(), w->get_offset(), value_len);
            }
        }
    }

    if (running) {
        if (wait) {
            series->push_back(WFTaskFactory::create_timer_task(1000 * 1000, nullptr));
        }
        series->push_back(create_produce_task());
    }
}

const char *usage =
        R"(
Usage: ./kafka_consume_example.out url group topic [start_at]
    url: kafka://host:port/
    start_at: earliest, latest

Example:
    ./kafka_consume_example.out "kafka://kafka001.sogou:9092" test_group topic_name latest
)";

int main(int argc, char *argv[]) {
    if (argc != 4 && argc != 3) {
        printf(usage);
        return -1;
    }

    url.assign(argv[1]);
    topic.assign(argv[2]);
    printf("topic:%s url:%s \n", topic, url);

    int ret = client.init(url);
    if (ret != 0) {
        printf("InitClientFailed ret:%d\n", ret);
        return ret;
    }
    printf("client init\n");

    signal(SIGINT, signal_handler);

    WFKafkaTask *task = create_produce_task(true);
    SeriesWork *series = Workflow::create_series_work(task, [](const SeriesWork *) {
        wait_group.done();
    });
    series->start();

    wait_group.wait();
    client.deinit();
    return 0;
}`

**Comment by huiluo2008** [comment]
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>

#include "workflow/WFKafkaClient.h"
#include "workflow/KafkaMessage.h"
#include "workflow/KafkaResult.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"
#include "workflow/WFGlobal.h"


#define RD_MIN(a, b) ((a) < (b) ? (a) : (b))
#define RD_MAX(a, b) ((a) > (b) ? (a) : (b))

using namespace protocol;

WFFacilities::WaitGroup wait_group(1);
std::string url, topic;
std::string client_id("wfkafka");

int retry_max = 2;

WFKafkaClient client;
std::atomic<bool> running = {true};

void signal_handler(int signo) {
    running = false;
}

void kafka_produce_callback(WFKafkaTask *);

WFKafkaTask *create_produce_task(bool first = false) {
    WFKafkaTask *task;
    KafkaConfig config;

    config.set_client_id(client_id.c_str());
    config.set_produce_msg_max_bytes(2 * 10000 * 1024);


    task = client.create_kafka_task("api=produce", retry_max, kafka_produce_callback);
    task->set_config(std::move(config));


    char *msgpattern  = "librdkafka_performance testing!";
    int msgsize       = -1;
    if (msgsize == -1){
        msgsize = (int)strlen(msgpattern);
    }

    int minlen = (int)(strlen("LATENCY:") + strlen("18446744073709551615 ") + 1);
    msgsize    = RD_MAX(minlen, msgsize);

    char *sbuf;
    off_t rof   = 0;
    size_t plen = strlen(msgpattern);


    sbuf = malloc(msgsize);
    /* Copy payload content to new buffer */
    while (rof < msgsize) {
        size_t xlen = RD_MIN((size_t)msgsize - rof, plen);
        memcpy(sbuf + rof, msgpattern, xlen);
        rof += (off_t)xlen;
    }

//    char buf[1 * 1024];
//    for (size_t i = 0; i < sizeof(buf); ++i) {
//        buf[i] = '1' + rand() % 128;
//    }

    for (size_t i = 0; i < 10000; ++i) {
        KafkaRecord record;
        record.set_value(sbuf, msgsize);
        task->add_produce_record("demo4", -1, std::move(record));
    }
    return task;
}

void kafka_produce_callback(WFKafkaTask *task) {
    SeriesWork *series = series_of(task);
    int state = task->get_state();
    int error = task->get_error();
    bool wait = false;

    if (state != WFT_STATE_SUCCESS) {
        wait = true;
        printf("produce Failed state:%d error:%d errmsg:%s\n", state, error, WFGlobal::get_error_string(state, error));
    } else {
        std::vector<std::vector<KafkaRecord *>> records;
        task->get_result()->fetch_records(records);
        for (const auto &v: records) {
            for (const auto &w: v) {
                const void *value;
                size_t value_len;
                w->get_value(&value, &value_len);
//                    msg_delivered(w->get_offset(), value, value_len);
                printf("produce\ttopic: %s, partition: %d, status: %d, offset: %lld, val_len: %zu\n", w->get_topic(),w->get_partition(), w->get_status(), w->get_offset(), value_len);
            }
        }
    }

    if (running) {
        if (wait) {
            series->push_back(WFTaskFactory::create_timer_task(1000 * 1000, nullptr));
        }
        series->push_back(create_produce_task());
    }
}

const char *usage =
        R"(
Usage: ./kafka_consume_example.out url group topic [start_at]
    url: kafka://host:port/
    start_at: earliest, latest

Example:
    ./kafka_consume_example.out "kafka://kafka001.sogou:9092" test_group topic_name latest
)";

int main(int argc, char *argv[]) {
    if (argc != 4 && argc != 3) {
        printf(usage);
        return -1;
    }

    url.assign(argv[1]);
    topic.assign(argv[2]);
    printf("topic:%s url:%s \n", topic, url);

    int ret = client.init(url);
    if (ret != 0) {
        printf("InitClientFailed ret:%d\n", ret);
        return ret;
    }
    printf("client init\n");

    signal(SIGINT, signal_handler);

    WFKafkaTask *task = create_produce_task(true);
    SeriesWork *series = Workflow::create_series_work(task, [](const SeriesWork *) {
        wait_group.done();
    });
    series->start();

    wait_group.wait();
    client.deinit();
    return 0;
}

**Comment by Barenboim** [comment]
create_produce_task()这个函数里，sbuf要free一下，要不然这个有内存泄露。
@huiluo2008

**Comment by huiluo2008** [comment]
再请教下，workflow的线程模型是什么样的，跟batch数量无关，每次我看都是25个线程：kafka_producer

**Comment by Barenboim** [comment]
> 再请教下，workflow的线程模型是什么样的，跟batch数量无关，每次我看都是25个线程：kafka_producer

对，workflow的线程都是内部创建的。你看到的25个线程应该是4个网络IO线程和20个处理结果的handler线程，这是很标准的线程模型。可以看一下这个文档，里面有关于参数调整的一些说明：
https://github.com/sogou/workflow/blob/master/docs/about-config.md
我改一下你这个demo，让网络请求和数据积累可以并发，这样会快一些。

**Comment by Barenboim** [comment]
~~~cpp
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>

#include "workflow/ResourcePool.h"
#include "workflow/WFKafkaClient.h"
#include "workflow/KafkaMessage.h"
#include "workflow/KafkaResult.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"
#include "workflow/WFGlobal.h"


#define RD_MIN(a, b) ((a) < (b) ? (a) : (b))
#define RD_MAX(a, b) ((a) > (b) ? (a) : (b))

using namespace protocol;

WFResourcePool respool(1);             // 用一个只有一个资源的资源池，实现produce任务的串行化
WFFacilities::WaitGroup wait_group(1);
std::string url, topic;
std::string client_id("wfkafka");

int retry_max = 2;

WFKafkaClient client;
std::atomic<bool> running = {true};

void signal_handler(int signo) {
    running = false;
}

void kafka_produce_callback(WFKafkaTask *);

WFKafkaTask *create_produce_task(bool first = false) {
    WFKafkaTask *task;
    KafkaConfig config;

    config.set_client_id(client_id.c_str());
    config.set_produce_msg_max_bytes(2 * 10000 * 1024);


    task = client.create_kafka_task("api=produce", retry_max, kafka_produce_callback);
    task->set_config(std::move(config));


    char *msgpattern  = "librdkafka_performance testing!";
    int msgsize       = -1;
    if (msgsize == -1){
        msgsize = (int)strlen(msgpattern);
    }

    int minlen = (int)(strlen("LATENCY:") + strlen("18446744073709551615 ") + 1);
    msgsize    = RD_MAX(minlen, msgsize);

    char *sbuf;
    off_t rof   = 0;
    size_t plen = strlen(msgpattern);


    sbuf = malloc(msgsize);
    /* Copy payload content to new buffer */
    while (rof < msgsize) {
        size_t xlen = RD_MIN((size_t)msgsize - rof, plen);
        memcpy(sbuf + rof, msgpattern, xlen);
        rof += (off_t)xlen;
    }

//    char buf[1 * 1024];
//    for (size_t i = 0; i < sizeof(buf); ++i) {
//        buf[i] = '1' + rand() % 128;
//    }

    for (size_t i = 0; i < 10000; ++i) {
        KafkaRecord record;
        record.set_value(sbuf, msgsize);
        task->add_produce_record("demo4", -1, std::move(record));
    }

    free(sbuf);     // 这里要释放一下sbuf，否则会内存泄露
    return task;
}

void kafka_produce_callback(WFKafkaTask *task) {
    SeriesWork *series = series_of(task);
    int state = task->get_state();
    int error = task->get_error();
    bool wait = false;

    if (state != WFT_STATE_SUCCESS) {
        wait = true;
        printf("produce Failed state:%d error:%d errmsg:%s\n", state, error, WFGlobal::get_error_string(state, error));
    } else {
        std::vector<std::vector<KafkaRecord *>> records;
        task->get_result()->fetch_records(records);
        for (const auto &v: records) {
            for (const auto &w: v) {
                const void *value;
                size_t value_len;
                w->get_value(&value, &value_len);
//                    msg_delivered(w->get_offset(), value, value_len);
                printf("produce\ttopic: %s, partition: %d, status: %d, offset: %lld, val_len: %zu\n", w->get_topic(),w->get_partition(), w->get_status(), w->get_offset(), value_len);
            }
        }
    }
    // 不在这里产生下一个produce任务了，main里直接循环

    // 这里归还一下资源，让下一个produce任务可以执行
    respool.post(NULL);
}

const char *usage =
        R"(
Usage: ./kafka_consume_example.out url group topic [start_at]
    url: kafka://host:port/
    start_at: earliest, latest

Example:
    ./kafka_consume_example.out "kafka://kafka001.sogou:9092" test_group topic_name latest
)";

int main(int argc, char *argv[]) {
    if (argc != 4 && argc != 3) {
        printf(usage);
        return -1;
    }

    url.assign(argv[1]);
    topic.assign(argv[2]);
    printf("topic:%s url:%s \n", topic, url);

    int ret = client.init(url);
    if (ret != 0) {
        printf("InitClientFailed ret:%d\n", ret);
        return ret;
    }
    printf("client init\n");

    signal(SIGINT, signal_handler);

    for (int i = 0; i < 100; i++)  //假设发送100次生产任务
    {
        WFKafkaTask *task = create_produce_task();
        WFConditional *cond = respool.get(task);   // 从资源里获得一个资源时运行任务
        cond->start();
    }

    // 产生一个空任务。同样，当获得资源时运行。
    // 因为是最后一个从资源池里申请资源的任务，所以一定在所有produce任务之后才能执行
    WFEmptyTask *task = WFTaskFactory::create_empty_task();
    WFConditional *cond = respool.get(task);
    SeriesWork *series = Workflow::create_series_work(task, [](const SeriesWork *) {
        respool.post(NULL);
        wait_group.done();
    });
    series->start();

    wait_group.wait();
    client.deinit();
    return 0;
}
~~~
你可以看看这样例如，连接产生100个produce任务，通过一个只有一个资源的resource pool实现串行化。关于资源池的文档：
https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md

**Comment by Barenboim** [comment]
我把你原来代码里一些编译错误或警告也修了一下，上面那个程序应该是可以编译的了。

**Comment by huiluo2008** [comment]
请问，kafka producer是否支持幂等？不能全部依靠业务层面去支持幂等。（一般的client是通过ProducerID和SequenceNumber实现幂等）

**Comment by Barenboim** [comment]
这个我问题了这边kafka协议开发的同学，确实没有自动支持幂等。
我们的produce就是原封不动的将用户的任务发出，不会对内容进行过滤等处理。或者说，我们其实是实现属于kafka协议的内容，协议之上的功能，可能需要自己做一些封装。
幂等这个功能，是不是在积累数据时，需要做一些过滤？另外，就是要考虑一个SequenceNumber已经发送过了，下一批数据里也不应该包括这个SequenceNumber。
