### ISSUE TITLE
DAG任务的异常流程如何处理

### ISSUE THREAD

**Issue by Kevin-Ren97** [sogou/workflow#1173]
对于A->B->C->D->E这种流程，如果正常情况下是按顺序执行的，可以用SeriesWork完成。
但是如果异常流程下，A、B的下一步是执行D，然后D->E。这种有没有好的解决方案？
如果用counter似乎要注意内存的问题？

**Comment by Barenboim** [comment]
你觉得我们开发一个可以跳过（同时销毁）当前任务之后n个任务的功能，是不是可以解决你这个问题？并行任务算一个任务。

**Comment by Kevin-Ren97** [comment]
另外还有个问题是，我们后面可能要使用choice（即多个出口）这种流程，这种框架有没有好的解决方案？

**Comment by Barenboim** [comment]
> 另外还有个问题是，我们后面可能要使用choice（即多个出口）这种流程，这种框架有没有好的解决方案？

其实，我们有很多任务是可以用来支持这种动态性的。比如，有个WFDynamicTask，他的作用就是在执行的时候，动态产生一个实际的任务。因为module或并行也是一种任务，所以相当于也可以产生多个任务。
你说的这种路径选择，就看看有没有必要抽象出一种模型或任务来解决了。你可以先用我们目前的组件试一下。

**Comment by Kevin-Ren97** [comment]
> > 另外还有个问题是，我们后面可能要使用choice（即多个出口）这种流程，这种框架有没有好的解决方案？
> 
> 其实，我们有很多任务是可以用来支持这种动态性的。比如，有个WFDynamicTask，他的作用就是在执行的时候，动态产生一个实际的任务。因为module或并行也是一种任务，所以相当于也可以产生多个任务。 你说的这种路径选择，就看看有没有必要抽象出一种模型或任务来解决了。你可以先用我们目前的组件试一下。

那么按我理解这个就是动态生成吧？意思是等callback的时候在相应的对象里，push_back / push_front 进行处理？

**Comment by Barenboim** [comment]
用dynamic任务的好处是实现解耦吧，本质上还是动态生成。大概是这么做：
~~~cpp
SubTask *dynamic_create(WFDynamicTask *task)
{
    WFSeriesWork *series = series_of(task);
    MyContext *ctx = (MyContext *)series->get_context();
    if (ctx->use_pathA)
        return create_moduleA();
    else if (ctx->use_pathB)
         return create_moduleB();
    else
        return WFTaskFactory::create_redis_task(...);
}

void http_callback(WFHttpTask *task)
{
    // set series context here according to http fetching result
}

void f()
{
    WFHttpTask *http_task = WFTaskFactory::create_http_task(url, 0, 0, http_callback);
    WFDynamicTask *dtask = WFTaskFactory::create_dynamic_task(dynamic_create));
    WFSeriesWork *series = Workflow::create_series_work(http_task);
    series->push_back(dtask);
    series->set_context(new MyContext);
    series->start();
 }
~~~
如果你想设计成一开始就把所有任务都建好，运行过程中动态选择，可能需要增加一些功能。可以讨论一下。

**Comment by Kevin-Ren97** [comment]
> 用dynamic任务的好处是实现解耦吧，本质上还是动态生成。大概是这么做：
> 
> ```c++
> SubTask *dynamic_create(WFDynamicTask *task)
> {
>     WFSeriesWork *series = series_of(task);
>     MyContext *ctx = (MyContext *)series->get_context();
>     if (ctx->use_pathA)
>         return create_moduleA();
>     else if (ctx->use_pathB)
>          return create_moduleB();
>     else
>         return WFTaskFactory::create_redis_task(...);
> }
> 
> void http_callback(WFHttpTask *task)
> {
>     // set series context here according to http fetching result
> }
> 
> void f()
> {
>     WFHttpTask *http_task = WFTaskFactory::create_http_task(url, 0, 0, http_callback);
>     WFDynamicTask *dtask = WFTaskFactory::create_dynamic_task(dynamic_create));
>     WFSeriesWork *series = Workflow::create_series_work(http_task);
>     series->push_back(dtask);
>     series->set_context(new MyContext);
>     series->start();
>  }
> ```
> 
> 如果你想设计成一开始就把所有任务都建好，运行过程中动态选择，可能需要增加一些功能。可以讨论一下。

最开始把所有任务建好有个比较方便的是可以在最开始运行的时候知晓用户的输入是否合法（比如构建不同的任务的时候需要不同的参数，在最开始构建的时候可以校验输入参数是否合法，并生成该任务）。
如果用动态生成，那么比较方便的方式就是后面生成该任务的时候才校验到参数；要么就是需要在最开始校验输入参数但是不生成任务，后面再用这些参数生成任务。
不过，看起来动态生成可以满足我们的使用，我们先试着写一版看看。

**Comment by Kevin-Ren97** [comment]
> 对于A->B->C->D->E这种流程，如果正常情况下是按顺序执行的，可以用SeriesWork完成。 但是如果异常流程下，A、B的下一步是执行D，然后D->E。这种有没有好的解决方案？ 如果用counter似乎要注意内存的问题？

再问一下，按照这个例子。
我其实只有知道A的执行结果才能知道下一步是到D还是到B，那么如果到B，可能任务是5个（A、B、C、D、E）。但是到D的话，是3个（A、D、E）。
那么A执行完成之后根据是成功还是失败的请求，Create对应的Module，然后再push_back到series上？

**Comment by Barenboim** [comment]
如果用普通的push_back，就是在A的callback里，根据结果push_back你要的任务就好了。其实也很直观。
如果用dynamic task的方法，可以这么做：
~~~cpp
SubTask *dynamic_create(WFDynamicTask *task)
{
    MyContext *ctx= (MyContext *)series_of(task)->get_context();
    WFModuleTask *module = WFTaskFactory::create_module_task(...);
    SeriesWork *sub_series = module->sub_series();  // module内的series
    auto *taskD = WFTaskFactory::create_http_task(...); // 假设都是http
    auto *taskE = WFTaskFactory::create_http_task(...);
    sub_series->push_back(taskD);
    sub_series->push_back(taskE);
    if (flag)  // 执行ABCDE
    {
        auto *taskB = WFTaskFactory::create_http_task(...);
        auto *taskC = WFTaskFactory::create_http_task(...);
        sub_series->push_front(taskC); // 这里用push_front，反向插入B和C
        sub_series->push_front(taskB);
    }

    return module;
}

void http_callback(WFHttpTask *task)
{
    MyContext *ctx= (MyContext *)series_of(task)->get_context();
    if (task->get_state() == WF_STATE_SUCCESS);
        ctx->flag = true;   // 执行ABCDE
    else
        ctx->flag = false;  // 执行ADE
}

f()
{
    WFHttpTask *taskA = WFTaskFactory::create_http_task(..., http_callback);  // 假设这个是A
    SeriesWork *series = Workflow::create_series_work(taskA);
    WFDynamicTask *dtask = WFTaskFactory::create_dynamic_task(dynamic_create);
    series->push_back(dtask);
    series->set_context(new MyContext);
    series->start();
}
~~~
这个例子把A之后的任务结合成一个module，根据A的状态，决定module是BCDE还是DE。我觉得这么做比先把BC建好再skip要好。

**Comment by Barenboim** [comment]
这里用这个dynamic只是为了解耦。你A的callback里直接push_back，其实也是一个效果。

**Comment by Kevin-Ren97** [comment]
> 这里用这个dynamic只是为了解耦。你A的callback里直接push_back，其实也是一个效果。

大概明白了。
那其实针对框架来说，似乎是在回调中构建下一个task，然后push_front()似乎是更加贴近设计的？
而类似
```
try {
} catch(...) {
} finally{
}
```
提前生成好，然后发现某一个步骤异常了，想提前退出再加一个兜底似乎是和设计的使用不那么贴近一点？

**Comment by Barenboim** [comment]
对，这样也可以。反正你DE是都要执行的，你先放好也挺好的。
其实怎么简单怎么来就好。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月14日(周二) 晚上8:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] DAG任务的异常流程如何处理 (Issue #1173)




  
这里用这个dynamic只是为了解耦。你A的callback里直接push_back，其实也是一个效果。
  
大概明白了。
 那其实针对框架来说，似乎是在回调中构建下一个task，然后push_front()似乎是更加贴近设计的？
 而类似
 try { } catch(...) { } finally{ }  
提前生成好，然后发现某一个步骤异常了，想提前退出再加一个兜底似乎是和设计的使用不那么贴近一点？
