### ISSUE TITLE
请问有没有数据库预处理的语句？如何绑定参数？

### ISSUE THREAD

**Issue by shuidaan** [sogou/workflow#1174]
4. 预处理
用户也可以通过WFMySQLConnection来做预处理PREPARE，因此用户可以很方便地用作防SQL注入。如果连接发生了重连，也会得到一个ECONNRESET错误。
虽然有[WFMySQLConnection.h](https://github.com/sogou/workflow/blob/master/src/client/WFMySQLConnection.h) 参考，但是，里面的内容，比较难以理解。 还是看不懂如何调用，如何绑定参数？ 能不能给一些案例，方便理解。

多谢。

**Comment by shuidaan** [comment]
异步MySQL客户端：mysql_cli  https://github.com/sogou/workflow/blob/master/docs/tutorial-12-mysql_cli.md

**Comment by Barenboim** [comment]
WFMySQLConnection这个类，并不是专门用来做PREPARE的。而是说，用这个类创建出来的MySQL请求任务，会固定在一个连接上。如果连接断开，用户也可感知（得到一个ECONNRESET错误的任务）。
由于固定在一个连接上了，你当然就可以先发送PREPARE请求，之后执行EXECUTE请求只要匹配参数就可以了。而且我们的一个query里，可以直接包括多个SQL语句，用分号分开就好了。

**Comment by Barenboim** [comment]
关于PREPARE的一些文档：
https://www.tutorialspoint.com/mysql/mysql_prepare_statement.htm#:~:text=A%20prepared%20statement%20in%20MySQL%20represents%20a%20precompiled,values%20we%20pass%20place%20holders%20to%20this%20statement.

**Comment by shuidaan** [comment]
Example
Following is a prepared statement with the SELECT query −

--Preparing the statement
mysql> PREPARE prepared_stmt FROM 'SELECT ? FROM EMPLOYE where Name = ?';
Query OK, 0 rows affected (0.00 sec)
Statement prepared

--Setting the values
mysql> SET @col = 'Salary';
Query OK, 0 rows affected (0.00 sec)

mysql> SET @name = 'Raghu';
Query OK, 0 rows affected (0.00 sec)
--Executing the statement
mysql> EXECUTE prepared_stmt USING @col, @name;
+--------+
| ?      |
+--------+
| Salary |
+--------+
1 row in set (0.11 sec)

多谢，大概明白了。

**Comment by SuKunlun** [comment]
> WFMySQLConnection这个类，并不是专门用来做PREPARE的。而是说，用这个类创建出来的MySQL请求任务，会固定在一个连接上。如果连接断开，用户也可感知（得到一个ECONNRESET错误的任务）。 由于固定在一个连接上了，你当然就可以先发送PREPARE请求，之后执行EXECUTE请求只要匹配参数就可以了。而且我们的一个query里，可以直接包括多个SQL语句，用分号分开就好了。

这样还是需要将value拼接到sql语句中，感觉还是不能防SQL注入

**Comment by Barenboim** [comment]
> > WFMySQLConnection这个类，并不是专门用来做PREPARE的。而是说，用这个类创建出来的MySQL请求任务，会固定在一个连接上。如果连接断开，用户也可感知（得到一个ECONNRESET错误的任务）。 由于固定在一个连接上了，你当然就可以先发送PREPARE请求，之后执行EXECUTE请求只要匹配参数就可以了。而且我们的一个query里，可以直接包括多个SQL语句，用分号分开就好了。
> 
> 这样还是需要将value拼接到sql语句中，感觉还是不能防SQL注入

可以预防一部分吧。

**Comment by SuKunlun** [comment]
> > > WFMySQLConnection这个类，并不是专门用来做PREPARE的。而是说，用这个类创建出来的MySQL请求任务，会固定在一个连接上。如果连接断开，用户也可感知（得到一个ECONNRESET错误的任务）。 由于固定在一个连接上了，你当然就可以先发送PREPARE请求，之后执行EXECUTE请求只要匹配参数就可以了。而且我们的一个query里，可以直接包括多个SQL语句，用分号分开就好了。
> > 
> > 
> > 这样还是需要将value拼接到sql语句中，感觉还是不能防SQL注入
> 
> 可以预防一部分吧。

有没有办法达到MySQL原生的client C 的API(mysql_stmt_execute)的效果呢？

**Comment by SuKunlun** [comment]
> > mysql_stmt_execute
> 
> 在现在这个的基础上，可以封装出来吧？

能提供下思路吗？谢谢

**Comment by Barenboim** [comment]
这个我也不懂是什么语意，但我们提供的是原子操作，所以我认为在任何建立在原始SQL语句上的功能，都可以在这个基础上封装。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 上午10:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [sogou/workflow] 请问有没有数据库预处理的语句？如何绑定参数？ (Issue #1174)




   
mysql_stmt_execute
  
在现在这个的基础上，可以封装出来吧？
  
能提供下思路吗？谢谢

**Comment by Barenboim** [comment]
> > 这个我也不懂是什么语意，但我们提供的是原子操作，所以我认为在任何建立在原始SQL语句上的功能，都可以在这个基础上封装。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年8月2日(周五) 上午10:19 收件人: _**@**_.**_>; 抄送: _**@**_._**>;"State _**@**_.**_>; 主题: Re: [sogou/workflow] 请问有没有数据库预处理的语句？如何绑定参数？ (Issue #1174) mysql_stmt_execute 在现在这个的基础上，可以封装出来吧？ 能提供下思路吗？谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 看了下源码： 1、workflow中仅实现了COM_QUERY协议 2、libmysql中mysql_stmt_execute实现的源码，其底层发送的依次是下列请求： COM_STMT_PREPARE请求 预编译请求 COM_STMT_SEND_LONG_DATA请求 发送参数值给预编译语句，预编译中有几个就得发几个该请求，参数值按内容copy到数据包 COM_STMT_EXECUTE请求 执行预编译语句
> 
> 所以我理解 Prepare Satement 不是建立在原始SQL语句上的功能，它有自己特定的请求协议，只是用原始的SQL语句也能实现。（不确定理解的对不对。。。。）
> 
> 根据目前workflow提供的接口，好像也只能对参数值做下转义处理，然后拼接出SET语句执行，我还没有想到怎样封装能避免这种手动拼接SQL的方法。
> 
> 要想实现libmysql预编译相关接口功能，可能还是需要在workflow底层实现COM_STMT_...相关的通信协议，并提供相应接口。。。。

这个我们需要调研一下。可以重新发一个issue来跟进。

**Comment by SuKunlun** [comment]
> > > 这个我也不懂是什么语意，但我们提供的是原子操作，所以我认为在任何建立在原始SQL语句上的功能，都可以在这个基础上封装。
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年8月2日(周五) 上午10:19 收件人: _**@**_.**_>; 抄送: _**@**_._**>;"State _**@**_.**_>; 主题: Re: [sogou/workflow] 请问有没有数据库预处理的语句？如何绑定参数？ (Issue #1174) mysql_stmt_execute 在现在这个的基础上，可以封装出来吧？ 能提供下思路吗？谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> > 
> > 
> > 看了下源码： 1、workflow中仅实现了COM_QUERY协议 2、libmysql中mysql_stmt_execute实现的源码，其底层发送的依次是下列请求： COM_STMT_PREPARE请求 预编译请求 COM_STMT_SEND_LONG_DATA请求 发送参数值给预编译语句，预编译中有几个就得发几个该请求，参数值按内容copy到数据包 COM_STMT_EXECUTE请求 执行预编译语句
> > 所以我理解 Prepare Satement 不是建立在原始SQL语句上的功能，它有自己特定的请求协议，只是用原始的SQL语句也能实现。（不确定理解的对不对。。。。）
> > 根据目前workflow提供的接口，好像也只能对参数值做下转义处理，然后拼接出SET语句执行，我还没有想到怎样封装能避免这种手动拼接SQL的方法。
> > 要想实现libmysql预编译相关接口功能，可能还是需要在workflow底层实现COM_STMT_...相关的通信协议，并提供相应接口。。。。
> 
> 这个我们需要调研一下。可以重新发一个issue来跟进。

好的
