### ISSUE TITLE
POST请求task设置超时时长

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#1175]
在POST请求task的HttpRequest如何设置连接时长？

**Comment by Barenboim** [comment]
没看懂你的需求是什么。

**Comment by HzjFirst** [comment]
我用python起了一个本地服务，打算用workflow中http的task去请求，但是这个服务运行的时间比较长，如果不设置时间，task刚起没有多长时间就和python服务断开了，调用了task的回调函数，我怎么设置这个task让这个链接时间长一点，等python服务执行完在调用task的回调函数

**Comment by Barenboim** [comment]
噢噢，这是send的timeout吧？关于send的超时，受到两个因素影响，一个是全局的response_timeout，这代表每发送成功一块数据的时候，这个默认值是10秒。另外一个是task的send_timeout，这个默认是-1，无限。所以，你的请求应该是被全局的response_timeout限制了。可以这么改：
~~~cpp
int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.response_timeout = 30*1000; // 改成30秒
    WORKFLOW_library_init(&settings);
    ...
}
~~~

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/218997995-56bf1ead-b405-402a-8708-c0625ba8d70f.png)
这个我好像在起服务的时候设置了啊，但是还是不能实现效果啊

**Comment by Barenboim** [comment]
不会吧！你现在从发起到出错的时间是多长？错误码是什么？

**Comment by HzjFirst** [comment]
从发起到结束大概30秒，state的值是1，WFT_STATE_SYS_ERROR不知道什么原因

**Comment by Barenboim** [comment]
看task->get_error()；

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/219003006-e89d7e20-d4c2-4c6a-b981-2446e7992222.png)

task->get_error()是138

**Comment by Barenboim** [comment]
问题是并没有这个错误吗。
你在你机器上打一下：
~~~c
fprintf(stderr, "%s\n", strerror(task->get_error()));
~~~
看看打出来的是什么。

**Comment by HzjFirst** [comment]
打印的结果是timed out

**Comment by Barenboim** [comment]
你看看有没有地方调用了set_send_timeout和set_receive_timeout吧。这个是任务级的，默认是无限。可能被你哪里设置成30秒了。

**Comment by HzjFirst** [comment]
全局搜索代码的关键字了，都没有出现啊

**Comment by HzjFirst** [comment]
关键是服务还在跑，workflow这边回调已经执行了，服务器那边显示正常调用

**Comment by Barenboim** [comment]
你post的数据多大？服务器那边其实都成写入了是吧？





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 晚上7:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] POST请求task设置超时时长 (Issue #1175)




 
关键是服务还在跑，workflow这边回调已经执行了，服务器那边显示正常调用

**Comment by HzjFirst** [comment]
post的数据也不是很大2kb左右，关键是服务器获取到数据之后直接跑了一个算法，比较耽误时间，在跑算法的途中workflow调用回调了

**Comment by Barenboim** [comment]
噢噢，服务器跑完算法，才回复http吗？

**Comment by HzjFirst** [comment]
对，是这个效果

**Comment by Barenboim** [comment]
你那边workflow是在什么平台上？138表示timedout应该不是linux吧

**Comment by HzjFirst** [comment]
厉害啊，大佬，在window上，是不是window的原因

**Comment by Barenboim** [comment]
你把精确的执行时间告诉我一下。如果是30秒，应该是什么地方设置了

**Comment by Barenboim** [comment]
Windows啊。。。早说啊。如果Windows这里有什么硬限制我就不知道了。比如iocp默认没数据30秒就返回。这个我不太懂，可能得看代码。

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/219026179-a5f0c078-fadb-4992-b071-ca98c6eba22a.png)
对是Windows，我的问题，没有提前说，但是那个时间就是30秒，可能有什么设置死了

**Comment by Barenboim** [comment]
如果你没有调用过task->set_receive_timeout，那应该哪里写死了或windows系统调用的什么限制。你也可以在Linux也试试，应该没有这个问题。我们再看看。

**Comment by HzjFirst** [comment]
刚刚在Linux上测试了，连接超过了30秒也没有问题，整个流程也没有问题，可能就是因为平台的原因，window下的workflow可能设置了限制

**Comment by Barenboim** [comment]
我搜了一下windows分支的代码，也没有发现哪里有这个30秒超时的设置。不知道是不是系统调用的问题。

**Comment by Barenboim** [comment]
这个问题我先关了。暂时认为是Windows系统调用的一个硬限制，因为代码里没有任何30秒的限制。

**Comment by Barenboim** [comment]
我知道你这个的问题出在哪儿了。读取的超时还受到response timeout的限制，这个是10秒。然后·你可能设置了retry max为3，所以30秒超时。这个的修改可以这么写：
~~~cpp
#include <workflow/WFGlobal.h>

int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.response_timeout = 100 * 1000; // 100秒
    WORKFLOW_library_init(&settings);
}
~~~

**Comment by Barenboim** [comment]
另外为什么Linux下这个10秒没有生效，我需要看一下。

**Comment by Barenboim** [comment]
我这边实测Linux下2次重试也是30秒的超时，行为符合预期。改一下response_timeout就可能等待更长的时间了 @HzjFirst

**Comment by HzjFirst** [comment]
好的，谢谢大佬了，我测试一下，这么上心，挺感动
