### ISSUE TITLE
无法打开文件workflow.libkernel32.lib

### ISSUE THREAD

**Issue by ZackJing** [sogou/workflow#1176]
我在windows平台使用VS2022编译workflow项目之后，运行了github上第一个简单http server的代码，编译报错说"无法打开文件workflow.libkernel32.lib"，是什么原因？我编译完成后只有workflow.lib呀。

**Comment by Barenboim** [comment]
说个别的事，你刚才为啥unstar我们项目😂是不是点错了。
Windows下好像只产生一个lib。我们让群友看一下。Windows的编译我确实不太懂。

**Comment by ZackJing** [comment]
不好意思。。。。。。

**Comment by ZackJing** [comment]
github用的太少了，有没有 star都分不清。。。。

**Comment by Barenboim** [comment]
哈哈哈。没关系。我们转发群里了。

**Comment by holmes1412** [comment]
你好，小伙伴帮看了下，说是路径配置错了或者依赖项配置错了，正确应该是`workflow.lib;kernel32.lib`
你可以检查一下哈

**Comment by ZackJing** [comment]
确实是少打了";"，已经解决了

**Comment by Barenboim** [comment]
这个issue我先关了哈。使用中有什么问题随时反馈。感谢！
