### ISSUE TITLE
无法解析的符号(windows, VS2022)

### ISSUE THREAD

**Issue by ZackJing** [sogou/workflow#1179]
我在运行可执行文件时遇到了94条"无法解析外部符号的错误"(代码是简单http server教程当中的)。
共计有59条无法解析的指令。
错误描述如下(其中三条)：
1、错误	LNK2001	无法解析的外部符号 __imp_socket	test_workflow	D:\ZuckJingProject\ZuckTL\test_workflow\workflow.lib(RouteManager.obj)	1

2、错误	LNK2001	无法解析的外部符号 SSL_get_servername	test_workflow	D:\ZuckJingProject\ZuckTL\test_workflow\workflow.lib(WFServer.obj)	1

3、错误	LNK2001	无法解析的外部符号 __imp_getaddrinfo	test_workflow	D:\ZuckJingProject\ZuckTL\test_workflow\workflow.lib(DnsTaskImpl.obj)	1

**Comment by Barenboim** [comment]
这个好像没有链上系统库吧？那几个都是系统的函数。是kernel.lib没链吗。

**Comment by Barenboim** [comment]
我们的tutorial可以编过吗

**Comment by ZackJing** [comment]
编译通过了

**Comment by Barenboim** [comment]
都好了？还是只有tutorial可以？如果这样，就仿照tutorial写个cmake。

**Comment by ZackJing** [comment]
我再试试

**Comment by ZackJing** [comment]
我添加了kernel32.lib库文件，之后仍然有这些无法解析的错误。

**Comment by Barenboim** [comment]
ssl?

**Comment by ZackJing** [comment]
还剩24个无法解析的命令

**Comment by ZackJing** [comment]
我看到这些函数都是__imp开头，还有 __cdel修饰

**Comment by ZackJing** [comment]
1、无法解析的外部符号 __imp_getaddrinfo	TestWF	D:\ZuckJingProject\ZuckTL\TestWF\workflow.lib(DnsRoutine.obj)	1	

2、错误	LNK2001	无法解析的外部符号 __imp_freeaddrinfo	TestWF	D:\ZuckJingProject\ZuckTL\TestWF\workflow.lib(DnsCache.obj)	1	

3、错误	LNK2001	无法解析的外部符号 __imp_closesocket	TestWF	D:\ZuckJingProject\ZuckTL\TestWF\workflow.lib(WinPoller.obj)	1	

4、错误	LNK2019	无法解析的外部符号 __imp_WSAGetLastError，函数 "int __cdecl __set_fd_nonblock(unsigned __int64)" (?__set_fd_nonblock@@YAH_K@Z) 中引用了该符号	TestWF	D:\ZuckJingProject\ZuckTL\TestWF\workflow.lib(Communicator.obj)	1

**Comment by Barenboim** [comment]
你查一下这几个是Windows下什么lib的。

**Comment by ZackJing** [comment]
找到了，这个库叫做Ws2_32.lib。是windows下的网络系统调用的库。

**Comment by Barenboim** [comment]
我看你对windows也不是太熟，不如直接用Linux版。Windows上安装个wsl2就可以了，可以直接用vs2022对接。
