### ISSUE TITLE
如何导入workflow

### ISSUE THREAD

**Issue by Sunburst7** [sogou/workflow#1181]
我是一个cmake初学者，最近想要使用workflow开源库，但是苦于不会导入，请问一下该如何使用呢，如果另外能介绍一下按需导入就更好了

**Comment by chanchann** [comment]
你make install后，在cmake里写find_package()， 然后target link就行了

**Comment by chanchann** [comment]
也可以参考下wfrest库将workflow作为submodule倒入，https://github.com/wfrest/wfrest/blob/e63c91555470ad60380390bb3487fab7e469af7e/src/CMakeLists.txt#L21

**Comment by holmes1412** [comment]
用cmake依赖workflow的写法也可以参考：
https://github.com/sogou/wf-prometheus
和
https://github.com/sogou/workflow-polaris
这两个都是非常小型的项目～

**Comment by Sunburst7** [comment]
我是模仿的一个项目建的项目结构：
![image](https://user-images.githubusercontent.com/65580753/219938706-f6f86666-7eb0-4805-8414-569c0e75b4f3.png)
然后我在workflow工作目录下运行了make install，出现了这样的报错
![image](https://user-images.githubusercontent.com/65580753/219938804-38da8bb3-b589-4c7c-9d67-a3528fb7cfbd.png)
我是在Windows环境下通过安装MinGW安装的make，也安装了cmake。
请问我的步骤有什么地方错误了吗

> 你make install后，在cmake里写find_package()， 然后target link就行了

**Comment by Sunburst7** [comment]
请问学习cmake有什么比较好的方式吗？我从网上看一些教程感觉晕晕了，只知道一些简单的概念，看一些项目的cmakefile时还是很吃力😭😭

**Comment by Barenboim** [comment]
Cmake是很繁琐，没有逻辑。都是照猫画虎，通过了就通过了。使用时可以安装或者把.a和.h拷过去，然后直接写Makefile。
项目里的依赖，可以参考wfrest项目：https://github.com/wfrest/wfrest

**Comment by chanchann** [comment]
既然是windows，可以用vcpkg来包管理

**Comment by Barenboim** [comment]
我们这个项目GNUMakefile+Cmake的方法不是太推荐，不要学。一般有Cmake就可以了。用户会自己建build目录的。

**Comment by Sunburst7** [comment]
我今天尝试使用add_subdirectory的方式引入，但是在workflow/CMakeLists.txt中报错：
![image](https://user-images.githubusercontent.com/65580753/219997131-770f7d4b-f58b-4b1a-8054-5567b617898d.png)
定位错误是在workflow/CMakeLists_Headers.txt中的一个判断语句：
![image](https://user-images.githubusercontent.com/65580753/219997352-a4b1aac1-0b66-4237-9aac-9028d5c97e15.png)
请问windows没有这个IOService是没法编译吗，所以需要在linux环境下才能运行吗

**Comment by Sunburst7** [comment]
> 我今天尝试使用add_subdirectory的方式引入，但是在workflow/CMakeLists.txt中报错： ![image](https://user-images.githubusercontent.com/65580753/219997131-770f7d4b-f58b-4b1a-8054-5567b617898d.png) 定位错误是在workflow/CMakeLists_Headers.txt中的一个判断语句： ![image](https://user-images.githubusercontent.com/65580753/219997352-a4b1aac1-0b66-4237-9aac-9028d5c97e15.png) 请问windows没有这个IOService是没法编译吗，所以需要在linux环境下才能运行吗

在网上看到了类型的问题，已解决

**Comment by Barenboim** [comment]
这个else直接不加就可以了。Windows下没有实现异步文件IO。

**Comment by Sunburst7** [comment]
后续：已解决
在公司用Linux开发机环境下，用nossl分支，通过使用add_subdirectory的方式成功引入。
十分感谢各位的解答🎉

**Comment by Barenboim** [comment]
nossl好久没更新了。既然你要用，我也更新一下。
另外，之后nossl还是要依赖libcrypto。原因是，MySQL大量依赖相关的加密函数。
感觉现在很多应用离不开SSL，非特殊情况尽量跟进主分支。

**Comment by Barenboim** [comment]
新的nossl分支我重新整理了一下代码。你要用的话可能要重新clone一下。

**Comment by Sunburst7** [comment]
> 新的nossl分支我重新整理了一下代码。你要用的话可能要重新clone一下。

我用master分支又试了一下，也是可以引用的，原来只是开发环境的问题，是我太菜了😭

**Comment by Barenboim** [comment]
不菜不菜。本来C++的依赖就很麻烦。

**Comment by Sunburst7** [comment]
今天尝试使用workflow写一个http server，但是编译时又出了问题，之前解决原来是因为我还没有导入workflow的头文件。附上cmake报错提示与我的CMakeLists.txt：

> [  0%] Built target LINK_HEADERS
[  1%] Building CXX object third/workflow/src/client/CMakeFiles/client.dir/WFDnsClient.cc.o
[  3%] Building CXX object third/workflow/src/client/CMakeFiles/client.dir/WFMySQLConnection.cc.o
[  5%] Building CXX object third/workflow/src/client/CMakeFiles/client.dir/WFConsulClient.cc.o
[  5%] Built target client
[  6%] Building CXX object third/workflow/src/kernel/CMakeFiles/kernel.dir/IOService_linux.cc.o
[  8%] Building C object third/workflow/src/kernel/CMakeFiles/kernel.dir/mpoller.c.o
[ 10%] Building C object third/workflow/src/kernel/CMakeFiles/kernel.dir/poller.c.o
[ 11%] Building C object third/workflow/src/kernel/CMakeFiles/kernel.dir/rbtree.c.o
[ 13%] Building C object third/workflow/src/kernel/CMakeFiles/kernel.dir/msgqueue.c.o
[ 15%] Building C object third/workflow/src/kernel/CMakeFiles/kernel.dir/thrdpool.c.o
[ 16%] Building CXX object third/workflow/src/kernel/CMakeFiles/kernel.dir/CommRequest.cc.o
[ 18%] Building CXX object third/workflow/src/kernel/CMakeFiles/kernel.dir/CommScheduler.cc.o
[ 20%] Building CXX object third/workflow/src/kernel/CMakeFiles/kernel.dir/Communicator.cc.o
[ 22%] Building CXX object third/workflow/src/kernel/CMakeFiles/kernel.dir/Executor.cc.o
[ 23%] Building CXX object third/workflow/src/kernel/CMakeFiles/kernel.dir/SubTask.cc.o
[ 23%] Built target kernel
[ 25%] Building C object third/workflow/src/util/CMakeFiles/util.dir/json_parser.c.o
[ 27%] Building CXX object third/workflow/src/util/CMakeFiles/util.dir/EncodeStream.cc.o
[ 28%] Building CXX object third/workflow/src/util/CMakeFiles/util.dir/StringUtil.cc.o
[ 30%] Building CXX object third/workflow/src/util/CMakeFiles/util.dir/URIParser.cc.o
[ 30%] Built target util
[ 32%] Building CXX object third/workflow/src/manager/CMakeFiles/manager.dir/DnsCache.cc.o
[ 33%] Building CXX object third/workflow/src/manager/CMakeFiles/manager.dir/RouteManager.cc.o
[ 35%] Building CXX object third/workflow/src/manager/CMakeFiles/manager.dir/WFGlobal.cc.o
[ 37%] Building CXX object third/workflow/src/manager/CMakeFiles/manager.dir/UpstreamManager.cc.o
[ 37%] Built target manager
[ 38%] Building CXX object third/workflow/src/algorithm/CMakeFiles/algorithm.dir/DnsRoutine.cc.o
[ 38%] Built target algorithm
[ 40%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/PackageWrapper.cc.o
[ 42%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/SSLWrapper.cc.o
[ 44%] Building C object third/workflow/src/protocol/CMakeFiles/protocol.dir/dns_parser.c.o
[ 45%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/DnsMessage.cc.o
[ 47%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/DnsUtil.cc.o
[ 49%] Building C object third/workflow/src/protocol/CMakeFiles/protocol.dir/http_parser.c.o
[ 50%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/HttpMessage.cc.o
[ 52%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/HttpUtil.cc.o
[ 54%] Building C object third/workflow/src/protocol/CMakeFiles/protocol.dir/mysql_stream.c.o
[ 55%] Building C object third/workflow/src/protocol/CMakeFiles/protocol.dir/mysql_parser.c.o
[ 57%] Building C object third/workflow/src/protocol/CMakeFiles/protocol.dir/mysql_byteorder.c.o
[ 59%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/MySQLMessage.cc.o
[ 61%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/MySQLResult.cc.o
[ 62%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/MySQLUtil.cc.o
[ 64%] Building C object third/workflow/src/protocol/CMakeFiles/protocol.dir/redis_parser.c.o
[ 66%] Building CXX object third/workflow/src/protocol/CMakeFiles/protocol.dir/RedisMessage.cc.o
[ 66%] Built target protocol
[ 67%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/WFGraphTask.cc.o
[ 69%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/DnsTaskImpl.cc.o
[ 71%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/WFTaskFactory.cc.o
[ 72%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/Workflow.cc.o
[ 74%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/HttpTaskImpl.cc.o
[ 76%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/WFResourcePool.cc.o
[ 77%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/WFMessageQueue.cc.o
[ 79%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/FileTaskImpl.cc.o
[ 81%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/MySQLTaskImpl.cc.o
[ 83%] Building CXX object third/workflow/src/factory/CMakeFiles/factory.dir/RedisTaskImpl.cc.o
[ 83%] Built target factory
[ 84%] Building CXX object third/workflow/src/nameservice/CMakeFiles/nameservice.dir/WFNameService.cc.o
[ 86%] Building CXX object third/workflow/src/nameservice/CMakeFiles/nameservice.dir/WFDnsResolver.cc.o
[ 88%] Building CXX object third/workflow/src/nameservice/CMakeFiles/nameservice.dir/WFServiceGovernance.cc.o
[ 89%] Building CXX object third/workflow/src/nameservice/CMakeFiles/nameservice.dir/UpstreamPolicies.cc.o
[ 89%] Built target nameservice
[ 91%] Building CXX object third/workflow/src/server/CMakeFiles/server.dir/WFServer.cc.o
[ 93%] Building CXX object third/workflow/src/server/CMakeFiles/server.dir/WFMySQLServer.cc.o
[ 93%] Built target server
[ 94%] Linking CXX static library ../../../../third/workflow/_lib/libworkflow.a
[ 94%] Built target workflow-static
[ 96%] Building CXX object CMakeFiles/WebServer.dir/src/WebServer.cpp.o
[ 98%] Linking CXX executable WebServer
../third/workflow/_lib/libworkflow.a(WFGlobal.cc.o)：在函数‘__SSLManager::new_ssl_server_ctx()’中：
WFGlobal.cc:(.text._ZN12__SSLManager18new_ssl_server_ctxEv[_ZN12__SSLManager18new_ssl_server_ctxEv]+0xd)：对‘TLS_server_method’未定义的引用
WFGlobal.cc:(.text._ZN12__SSLManager18new_ssl_server_ctxEv[_ZN12__SSLManager18new_ssl_server_ctxEv]+0x15)：对‘SSL_CTX_new’未定义的引用
../third/workflow/_lib/libworkflow.a(WFGlobal.cc.o)：在函数‘__SSLManager::__SSLManager()’中：
WFGlobal.cc:(.text._ZN12__SSLManagerC2Ev[_ZN12__SSLManagerC5Ev]+0xd)：对‘TLS_client_method’未定义的引用
WFGlobal.cc:(.text._ZN12__SSLManagerC2Ev[_ZN12__SSLManagerC5Ev]+0x15)：对‘SSL_CTX_new’未定义的引用
../third/workflow/_lib/libworkflow.a(WFGlobal.cc.o)：在函数‘__SSLManager::~__SSLManager()’中：
WFGlobal.cc:(.text._ZN12__SSLManagerD2Ev[_ZN12__SSLManagerD5Ev]+0x17)：对‘SSL_CTX_free’未定义的引用
../third/workflow/_lib/libworkflow.a(WFGlobal.cc.o)：在函数‘__ExecManager::get_exec_queue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
WFGlobal.cc:(.text._ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x2d)：对‘pthread_rwlock_rdlock’未定义的引用
WFGlobal.cc:(.text._ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xae)：对‘pthread_rwlock_unlock’未定义的引用
WFGlobal.cc:(.text._ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xcc)：对‘pthread_rwlock_wrlock’未定义的引用
WFGlobal.cc:(.text._ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN13__ExecManager14get_exec_queueERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x205)：对‘pthread_rwlock_unlock’未定义的引用
../third/workflow/_lib/libworkflow.a(HttpTaskImpl.cc.o)：在函数‘__encode_auth(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’中：
HttpTaskImpl.cc:(.text+0xed6)：对‘EVP_EncodeBlock’未定义的引用
../third/workflow/_lib/libworkflow.a(HttpTaskImpl.cc.o)：在函数‘__create_ssl(ssl_ctx_st*)’中：
HttpTaskImpl.cc:(.text+0xf24)：对‘BIO_s_mem’未定义的引用
HttpTaskImpl.cc:(.text+0xf2c)：对‘BIO_new’未定义的引用
HttpTaskImpl.cc:(.text+0xf3c)：对‘BIO_s_mem’未定义的引用
HttpTaskImpl.cc:(.text+0xf44)：对‘BIO_new’未定义的引用
HttpTaskImpl.cc:(.text+0xf5b)：对‘SSL_new’未定义的引用
HttpTaskImpl.cc:(.text+0xf7d)：对‘SSL_set_bio’未定义的引用
HttpTaskImpl.cc:(.text+0xf8f)：对‘BIO_free’未定义的引用
HttpTaskImpl.cc:(.text+0xf9b)：对‘BIO_free’未定义的引用
../third/workflow/_lib/libworkflow.a(HttpTaskImpl.cc.o)：在函数‘ComplexHttpProxyTask::init_ssl_connection()::{lambda(void*)#1}::operator()(void*) const’中：
HttpTaskImpl.cc:(.text+0xfca)：对‘SSL_free’未定义的引用
../third/workflow/_lib/libworkflow.a(HttpTaskImpl.cc.o)：在函数‘ComplexHttpProxyTask::init_ssl_connection()’中：
HttpTaskImpl.cc:(.text+0x103f)：对‘SSL_ctrl’未定义的引用
HttpTaskImpl.cc:(.text+0x104b)：对‘SSL_set_connect_state’未定义的引用
../third/workflow/_lib/libworkflow.a(WFNameService.cc.o)：在函数‘WFNameService::add_policy(char const*, WFNSPolicy*)’中：
WFNameService.cc:(.text+0x89)：对‘pthread_rwlock_wrlock’未定义的引用
WFNameService.cc:(.text+0x1b4)：对‘pthread_rwlock_unlock’未定义的引用
../third/workflow/_lib/libworkflow.a(WFNameService.cc.o)：在函数‘WFNameService::get_policy(char const*)’中：
WFNameService.cc:(.text+0x1f3)：对‘pthread_rwlock_rdlock’未定义的引用
WFNameService.cc:(.text+0x22d)：对‘pthread_rwlock_unlock’未定义的引用
../third/workflow/_lib/libworkflow.a(WFNameService.cc.o)：在函数‘WFNameService::del_policy(char const*)’中：
WFNameService.cc:(.text+0x25c)：对‘pthread_rwlock_wrlock’未定义的引用
WFNameService.cc:(.text+0x2ad)：对‘pthread_rwlock_unlock’未定义的引用
../third/workflow/_lib/libworkflow.a(Communicator.cc.o)：在函数‘__create_ssl(ssl_ctx_st*, CommConnEntry*)’中：
Communicator.cc:(.text+0x3ef)：对‘BIO_new_socket’未定义的引用
Communicator.cc:(.text+0x406)：对‘SSL_new’未定义的引用
Communicator.cc:(.text+0x439)：对‘SSL_set_bio’未定义的引用
Communicator.cc:(.text+0x44c)：对‘BIO_free’未定义的引用
../third/workflow/_lib/libworkflow.a(Communicator.cc.o)：在函数‘__ssl_writev(ssl_st*, iovec const*, int)’中：
Communicator.cc:(.text+0x4ca)：对‘SSL_write’未定义的引用
Communicator.cc:(.text+0x5a6)：对‘SSL_write’未定义的引用
../third/workflow/_lib/libworkflow.a(Communicator.cc.o)：在函数‘CommMessageIn::feedback(void const*, unsigned long)’中：
Communicator.cc:(.text+0x737)：对‘SSL_write’未定义的引用
Communicator.cc:(.text+0x755)：对‘SSL_get_error’未定义的引用
../third/workflow/_lib/libworkflow.a(Communicator.cc.o)：在函数‘Communicator::release_conn(CommConnEntry*)’中：
Communicator.cc:(.text+0xc32)：对‘SSL_free’未定义的引用
../third/workflow/_lib/libworkflow.a(Communicator.cc.o)：在函数‘Communicator::push(void const*, unsigned long, CommSession*)’中：
Communicator.cc:(.text+0x37ee)：对‘SSL_write’未定义的引用
Communicator.cc:(.text+0x380c)：对‘SSL_get_error’未定义的引用
../third/workflow/_lib/libworkflow.a(RouteManager.cc.o)：在函数‘RouteTargetSNI::init_ssl(ssl_st*)’中：
RouteManager.cc:(.text._ZN14RouteTargetSNI8init_sslEP6ssl_st[_ZN14RouteTargetSNI8init_sslEP6ssl_st]+0x3a)：对‘SSL_ctrl’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::SSLHandshaker::encode(iovec*, int)’中：
SSLWrapper.cc:(.text+0x1f)：对‘SSL_get_wbio’未定义的引用
SSLWrapper.cc:(.text+0x3e)：对‘BIO_ctrl’未定义的引用
SSLWrapper.cc:(.text+0x61)：对‘SSL_do_handshake’未定义的引用
SSLWrapper.cc:(.text+0x7f)：对‘SSL_get_error’未定义的引用
SSLWrapper.cc:(.text+0xc1)：对‘BIO_ctrl’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::__ssl_handshake(void const*, unsigned long*, ssl_st*, char**, long*)’中：
SSLWrapper.cc:(.text+0x127)：对‘SSL_get_wbio’未定义的引用
SSLWrapper.cc:(.text+0x137)：对‘SSL_get_rbio’未定义的引用
SSLWrapper.cc:(.text+0x156)：对‘BIO_ctrl’未定义的引用
SSLWrapper.cc:(.text+0x185)：对‘BIO_write’未定义的引用
SSLWrapper.cc:(.text+0x1b1)：对‘SSL_do_handshake’未定义的引用
SSLWrapper.cc:(.text+0x1cb)：对‘SSL_get_error’未定义的引用
SSLWrapper.cc:(.text+0x214)：对‘BIO_ctrl’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::SSLHandshaker::append(void const*, unsigned long*)’中：
SSLWrapper.cc:(.text+0x2a3)：对‘SSL_set_ex_data’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::SSLWrapper::encode(iovec*, int)’中：
SSLWrapper.cc:(.text+0x347)：对‘SSL_get_wbio’未定义的引用
SSLWrapper.cc:(.text+0x364)：对‘SSL_get_ex_data’未定义的引用
SSLWrapper.cc:(.text+0x38c)：对‘SSL_set_ex_data’未定义的引用
SSLWrapper.cc:(.text+0x3ba)：对‘BIO_ctrl’未定义的引用
SSLWrapper.cc:(.text+0x450)：对‘SSL_write’未定义的引用
SSLWrapper.cc:(.text+0x46e)：对‘SSL_get_error’未定义的引用
SSLWrapper.cc:(.text+0x4b4)：对‘BIO_ctrl’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::SSLWrapper::append_message()’中：
SSLWrapper.cc:(.text+0x526)：对‘SSL_read’未定义的引用
SSLWrapper.cc:(.text+0x5bf)：对‘SSL_get_error’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::SSLWrapper::append(void const*, unsigned long*)’中：
SSLWrapper.cc:(.text+0x610)：对‘SSL_get_rbio’未定义的引用
SSLWrapper.cc:(.text+0x630)：对‘BIO_write’未定义的引用
../third/workflow/_lib/libworkflow.a(SSLWrapper.cc.o)：在函数‘protocol::SSLWrapper::feedback(void const*, unsigned long)’中：
SSLWrapper.cc:(.text+0x686)：对‘SSL_get_wbio’未定义的引用
SSLWrapper.cc:(.text+0x6b6)：对‘BIO_ctrl’未定义的引用
SSLWrapper.cc:(.text+0x6e6)：对‘SSL_write’未定义的引用
SSLWrapper.cc:(.text+0x704)：对‘SSL_get_error’未定义的引用
SSLWrapper.cc:(.text+0x740)：对‘BIO_ctrl’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘__poller_handle_ssl_error’中：
poller.c:(.text+0x879)：对‘SSL_get_error’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘__poller_handle_read’中：
poller.c:(.text+0x9b9)：对‘SSL_read’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘__poller_handle_write’中：
poller.c:(.text+0xb99)：对‘SSL_write’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘__poller_handle_ssl_accept’中：
poller.c:(.text+0x1028)：对‘SSL_accept’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘__poller_handle_ssl_connect’中：
poller.c:(.text+0x10da)：对‘SSL_connect’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘__poller_handle_ssl_shutdown’中：
poller.c:(.text+0x118c)：对‘SSL_shutdown’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘poller_start’中：
poller.c:(.text+0x1f01)：对‘pthread_create’未定义的引用
../third/workflow/_lib/libworkflow.a(poller.c.o)：在函数‘poller_stop’中：
poller.c:(.text+0x2bc8)：对‘pthread_join’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘__thrdpool_routine’中：
thrdpool.c:(.text+0x25)：对‘pthread_setspecific’未定义的引用
thrdpool.c:(.text+0x13f)：对‘pthread_join’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘__thrdpool_terminate’中：
thrdpool.c:(.text+0x1c3)：对‘pthread_detach’未定义的引用
thrdpool.c:(.text+0x242)：对‘pthread_join’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘__thrdpool_create_threads’中：
thrdpool.c:(.text+0x292)：对‘pthread_attr_setstacksize’未定义的引用
thrdpool.c:(.text+0x2b2)：对‘pthread_create’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘thrdpool_create’中：
thrdpool.c:(.text+0x3b7)：对‘pthread_key_create’未定义的引用
thrdpool.c:(.text+0x429)：对‘pthread_key_delete’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘thrdpool_increase’中：
thrdpool.c:(.text+0x53f)：对‘pthread_attr_setstacksize’未定义的引用
thrdpool.c:(.text+0x56d)：对‘pthread_create’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘thrdpool_in_pool.localalias.0’中：
thrdpool.c:(.text+0x5e1)：对‘pthread_getspecific’未定义的引用
../third/workflow/_lib/libworkflow.a(thrdpool.c.o)：在函数‘thrdpool_destroy’中：
thrdpool.c:(.text+0x66c)：对‘pthread_key_delete’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [CMakeFiles/WebServer.dir/build.make:98：WebServer] 错误 1
make[1]: *** [CMakeFiles/Makefile2:280：CMakeFiles/WebServer.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

CMakeLists.txt
```
cmake_minimum_required (VERSION 3.8)

project (WebServer)
MESSAGE(STATUS "Project Directory: ${PROJECT_SOURCE_DIR}")

include_directories(
    ${PROJECT_SOURCE_DIR}/src
    ${PROJECT_SOURCE_DIR}/third/workflow/_include/
)

file(GLOB_RECURSE CODE_SRC  "${PROJECT_SOURCE_DIR}/src/*.h"
	                        "${PROJECT_SOURCE_DIR}/src/*.cpp")

# 包含子项目。
add_subdirectory(${PROJECT_SOURCE_DIR}/third/workflow)

add_executable (WebServer ${CODE_SRC})

target_link_libraries(WebServer workflow-static)
```

项目构成：
![image](https://user-images.githubusercontent.com/65580753/220541217-e2cc3720-fb62-4450-b8bc-2f7bc01fb4d0.png)

**Comment by Barenboim** [comment]
target_link_libraries(WebServer workflow-static)
这里要加上pthread，ssl和crypto。tutorial里有，抄一下。

**Comment by holmes1412** [comment]
链接那句话改成👇
target_link_libraries(WebServer workflow-static pthread OpenSSL::SSL OpenSSL::Crypto)

**Comment by Sunburst7** [comment]
> target_link_libraries(WebServer workflow-static) 这里要加上pthread，ssl和crypto。tutorial里有，抄一下。

大功告成！😘

哦哦，明白了，看到解答才忽然想起在公司的项目里好像看到过😥
这里的作用是链接时利用pthread ssl 与crypto的可执行文件吗

**Comment by Sunburst7** [comment]
> 链接那句话改成👇 target_link_libraries(WebServer workflow-static pthread OpenSSL::SSL OpenSSL::Crypto)

我参考公司的CMakeLists.txt改成了target_link_libraries(WebServer workflow-static pthread ssl crypto)成功通过了编译。
终于可以开始愉快的使用WF了😏😏

**Comment by Sunburst7** [comment]
> 链接那句话改成👇 target_link_libraries(WebServer workflow-static pthread OpenSSL::SSL OpenSSL::Crypto)

但是有个地方我不是很懂，OpenSSL::SSL前面的命名空间是什么意思呀，可执行文件也存在命名空间吗？

**Comment by Barenboim** [comment]
> > 链接那句话改成👇 target_link_libraries(WebServer workflow-static pthread OpenSSL::SSL OpenSSL::Crypto)
> 
> 但是有个地方我不是很懂，OpenSSL::SSL前面的命名空间是什么意思呀，可执行文件也存在命名空间吗？

这个不是可执行文件吧，就是lib。应该就是cmake内置的一些库的名字。

**Comment by Barenboim** [comment]
@Sunburst7  star一下项目呀。

**Comment by Sunburst7** [comment]
> @Sunburst7 star一下项目呀。

抱歉抱歉，我光去fork忘了star了😰😰，我还是个入门菜鸟，有些东西还不是很懂。
再次感谢前辈们的解答

**Comment by Barenboim** [comment]
> > @Sunburst7 star一下项目呀。
> 
> 抱歉抱歉，我光去fork忘了star了😰😰，我还是个入门菜鸟，有些东西还不是很懂。 再次感谢前辈们的解答

不客气呀。感谢使用哈。
