### ISSUE TITLE
rpmlint report: Incorrect FSF address

### ISSUE THREAD

**Issue by topazus** [sogou/workflow#1184]
rpmlint report `workflow-devel.x86_64: E: incorrect-fsf-address /usr/include/workflow/rbtree.h`, it seemed it can fixed by changed from `59 Temple Place, Suite 330, Boston, MA  02111-1307  USA` to `51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA`. 
https://github.com/sogou/workflow/blob/64cadd6b756af0ce449d47a6601c2d1581f47a33/src/kernel/rbtree.h#L17
ref: 
[Matroska-Org/libebml#15](https://github.com/Matroska-Org/libebml/issues/15)
https://bugzilla.redhat.com/show_bug.cgi?id=2157252
https://github.com/jeremyevans/aqualung/commit/9efe41aba904938066265a570ced6e5ac98b9b19

**Comment by Barenboim** [comment]
This rbtree files are copies from a very old version of linux kernel. We prefer to keep these files untouched. And we have another GPLv2 licence copy in our repo:  https://github.com/sogou/workflow/blob/master/LICENSE_GPLV2, with a correct fsf address in it.
