### ISSUE TITLE
Add Fedora linux to CI

### ISSUE THREAD

**Issue by bkmgit** [sogou/workflow#1187]
Would like to add CI using Fedora linux through Podman with Ubuntu host. Would this be welcome?
At present tests fail when built on Fedora Rawhide and Gtest 1.13
https://download.copr.fedorainfracloud.org/results/fed500/workflow/fedora-rawhide-x86_64/05556325-workflow/builder-live.log.gz
```
make -C build.cmake check CTEST_OUTPUT_ON_FAILURE=1
make[1]: Entering directory '/builddir/build/BUILD/workflow-0.10.5/test/build.cmake'
[  4%] Building CXX object CMakeFiles/uriparser_unittest.dir/uriparser_unittest.cc.o
In file included from /usr/include/gtest/gtest-message.h:57,
                 from /usr/include/gtest/gtest-assertion-result.h:46,
                 from /usr/include/gtest/gtest.h:64,
                 from /builddir/build/BUILD/workflow-0.10.5/test/uriparser_unittest.cc:19:
/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~
In file included from /usr/include/gtest/gtest-printers.h:115,
                 from /usr/include/gtest/gtest-matchers.h:48,
                 from /usr/include/gtest/internal/gtest-death-test-internal.h:47,
                 from /usr/include/gtest/gtest-death-test.h:43,
                 from /usr/include/gtest/gtest.h:65:
/usr/include/gtest/internal/gtest-internal.h:636:58: error: wrong number of template arguments (0, should be 1)
  636 |   typedef ::std::map<std::string, CodeLocation, std::less<>> RegisteredTestsMap;
      |                                                          ^
In file included from /usr/include/c++/13/string:49,
                 from /usr/include/c++/13/bits/locale_classes.h:40,
                 from /usr/include/c++/13/bits/ios_base.h:41,
                 from /usr/include/c++/13/iomanip:42,
                 from /usr/include/gtest/gtest.h:54:
/usr/include/c++/13/bits/stl_function.h:403:12: note: provided for 'template<class _Tp> struct std::less'
  403 |     struct less : public binary_function<_Tp, _Tp, bool>
      |            ^~~~
/usr/include/gtest/internal/gtest-internal.h:636:59: error: template argument 3 is invalid
  636 |   typedef ::std::map<std::string, CodeLocation, std::less<>> RegisteredTestsMap;
      |                                                           ^~
/usr/include/gtest/internal/gtest-internal.h: In member function 'bool testing::internal::TypedTestSuitePState::AddTestName(const char*, int, const char*, const char*)':
/usr/include/gtest/internal/gtest-internal.h:613:23: error: request for member 'insert' in '((testing::internal::TypedTestSuitePState*)this)->testing::internal::TypedTestSuitePState::registered_tests_', which is of non-class type 'testing::internal::TypedTestSuitePState::RegisteredTestsMap' {aka 'int'}
  613 |     registered_tests_.insert(
      |                       ^~~~~~
/usr/include/gtest/internal/gtest-internal.h: In member function 'bool testing::internal::TypedTestSuitePState::TestExists(const std::string&) const':
/usr/include/gtest/internal/gtest-internal.h:619:30: error: request for member 'count' in '((const testing::internal::TypedTestSuitePState*)this)->testing::internal::TypedTestSuitePState::registered_tests_', which is of non-class type 'const testing::internal::TypedTestSuitePState::RegisteredTestsMap' {aka 'const int'}
  619 |     return registered_tests_.count(test_name) > 0;
      |                              ^~~~~
/usr/include/gtest/internal/gtest-internal.h: In member function 'const testing::internal::CodeLocation& testing::internal::TypedTestSuitePState::GetCodeLocation(const std::string&) const':
/usr/include/gtest/internal/gtest-internal.h:623:40: error: qualified-id in declaration before 'it'
  623 |     RegisteredTestsMap::const_iterator it = registered_tests_.find(test_name);
      |                                        ^~
/usr/include/gtest/internal/gtest-internal.h:624:5: error: 'it' was not declared in this scope; did you mean 'int'?
  624 |     GTEST_CHECK_(it != registered_tests_.end());
      |     ^~~~~~~~~~~~
/usr/include/gtest/internal/gtest-internal.h:624:5: error: request for member 'end' in '((const testing::internal::TypedTestSuitePState*)this)->testing::internal::TypedTestSuitePState::registered_tests_', which is of non-class type 'const testing::internal::TypedTestSuitePState::RegisteredTestsMap' {aka 'const int'}
  624 |     GTEST_CHECK_(it != registered_tests_.end());
      |     ^~~~~~~~~~~~
/usr/include/gtest/internal/gtest-internal.h:625:12: error: 'it' was not declared in this scope; did you mean 'int'?
  625 |     return it->second;
      |            ^~
      |            int
make[4]: *** [CMakeFiles/uriparser_unittest.dir/build.make:76: CMakeFiles/uriparser_unittest.dir/uriparser_unittest.cc.o] Error 1
make[3]: *** [CMakeFiles/Makefile2:418: CMakeFiles/uriparser_unittest.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:113: CMakeFiles/check.dir/rule] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/workflow-0.10.5/test/build.cmake'
make[1]: *** [Makefile:134: check] Error 2
make: Leaving directory '/builddir/build/BUILD/workflow-0.10.5/test'
make: *** [GNUmakefile:23: check] Error 2
```

**Comment by Barenboim** [comment]
It seems that Gtest 1.13 needs C++14 to compile? We don't want to import anything that requires above C++11.

**Comment by bkmgit** [comment]
Will Gtest be replaced or will only version 1.12 be supported? Some other options:
- https://www.use-strict.de/sput-unit-testing/
- https://github.com/doe300/cpptest-lite
- https://github.com/catchorg/Catch2

**Comment by holmes1412** [comment]
@bkmgit Thanks for your advice. We will try to check the Gtest VERSION in unittest's cmake file to decide whether to push the C++ standard to version 14.  
If this is not a possible way, we prefere to use Gtest version 1.12 rather than replace it.

**Comment by holmes1412** [comment]
@bkmgit I have make [Pull Request : 1188](https://github.com/sogou/workflow/pull/1188) to support checking Gtest Version, which will use c++14 if version >= 1.13.0 
To make sure if it is suitable for Fedora Linux CI, it would be very appreciated if you could check it with my repo first. https://github.com/holmes1412/workflow-major

**Comment by bkmgit** [comment]
@holmes1412 Thanks for the fix. Checking.

**Comment by bkmgit** [comment]
@holmes1412 Your changes work, perhaps they should be merged? Or perhaps just use c++14 as default with Gtest.

When running tests, get the following output:
```
The following tests FAILED:
	  4 - redis_unittest (Failed)
	 16 - redis_unittest-memory-check (Failed)
```
See https://github.com/sogou/workflow/actions/runs/4250074504/jobs/7390827969 and https://download.copr.fedorainfracloud.org/results/fed500/workflow/fedora-rawhide-x86_64/05559564-workflow/builder-live.log.gz
Any suggestions?

**Comment by holmes1412** [comment]
@bkmgit Thanks for you checking. We will merge the change. 
And the redis unittest test fails because a local redis server is required. I'll fix that too.

**Comment by holmes1412** [comment]
@bkmgit The redis test issue above has been fixed. Please check my repo again, thank~

**Comment by bkmgit** [comment]
@holmes1412 Please see https://github.com/holmes1412/workflow-major/pull/92 Could also make same change in main repository.

**Comment by Barenboim** [comment]
> @holmes1412 Please see [holmes1412#92](https://github.com/holmes1412/workflow-major/pull/92) Could also make same change in main repository.

holmes1412's changes have been merged.

**Comment by bkmgit** [comment]
If using CMake, checking for .pc file may not always work to get the version, should check CMake files for the version. If using XMake, may still need .pc file.

**Comment by holmes1412** [comment]
> @holmes1412 Please see [holmes1412#92](https://github.com/holmes1412/workflow-major/pull/92) Could also make same change in main repository.

Thanks for your PR to my repo. I have tried to check Gtest_VERSION, too. But not all cmake versions support this variable, so I can't get Gtest_VERSION in my environment even find_package(Gtest) succees. That's why I use .pc file to check version. If Gtest is a newer version, such as 1.13.0, the .pc file must exist.

**Comment by bkmgit** [comment]
On Fedora, probably also RHEL derivatives get `grep: /pkgconfig/gtest.pc:` No such file or directory` gtest.pc does exist in `/usr/lib64/pkgconfig/` but the paths seem incorrect.

**Comment by bkmgit** [comment]
Would have expected use of `GTest_LIBRARY` rather than `GTEST_LIBRARY` https://cmake.org/cmake/help/book/mastering-cmake/chapter/Finding%20Packages.html as the name of the package is `GTest` not `GTEST`

**Comment by bkmgit** [comment]
Thanks. It seems to work now. Updated to https://github.com/sogou/workflow/pull/1193

**Comment by Barenboim** [comment]
Thank @bkmgit . The testing problem with GTest 1.13 is solved!

**Comment by Barenboim** [comment]
Yes. We will make a new release for Federa rpm ASAP.

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/releases/tag/v0.10.6
@bkmgit

**Comment by bkmgit** [comment]
谢谢您的帮
