### ISSUE TITLE
请问workflow支持Content-Type: application/json类型的post吗

### ISSUE THREAD

**Issue by MasterL-min** [sogou/workflow#1197]
如果可以的话可否有一定的示例可参考呢？

**Comment by chanchann** [comment]
post直接把json数据序列化然后append就行了

**Comment by chanchann** [comment]
我对workflow的json进行了一层c++的封装，你可以看看内部流程，https://github.com/wfrest/wfrest/blob/main/example/09_json.cc

**Comment by chanchann** [comment]
关于如何使用内置的c接口，我这里有example：https://github.com/chanchann/json-parser-example

**Comment by MasterL-min** [comment]
非常感谢，我先拜读一下！

**Comment by Barenboim** [comment]
你是client吗？如果是server，直接用wfrest：https://github.com/wfrest/wfrest

**Comment by MasterL-min** [comment]
> 我对workflow的json进行了一层c++的封装，你可以看看内部流程，https://github.com/wfrest/wfrest/blob/main/example/09_json.cc

想请问下wfrest与workflow的区别是什么，wfrest是基于workflow实现的吗

**Comment by Barenboim** [comment]
wfrest是基于workflow实现的一个Restful框架，属于第三方的生态项目。不过workflow团队提供了很多技术支持。
