### ISSUE TITLE
代码编译问题请教

### ISSUE THREAD

**Issue by sourcema** [sogou/workflow#1201]
您好，请问下我看CmakeLists中
在编译kafka这个文件（KafkaMessage.cc）指定禁用RTTI，set_property(SOURCE KafkaMessage.cc APPEND PROPERTY COMPILE_OPTIONS "-fno-rtti")，为什么单单针对这个文件，是出于什么考虑呢？

**Comment by Barenboim** [comment]
因为snappy某个版本禁用了rtti，并且拒绝了加回来：https://github.com/google/snappy/pull/129
所以派生snappy也需要no-rtti。

**Comment by sourcema** [comment]
> 

好的，多谢
