### ISSUE TITLE
Windows版HTTP Client超时设置失败

### ISSUE THREAD

**Issue by akjay** [sogou/workflow#1205]
分别使用tutorial-01-wget.cc和tutorial-04-http_echo_server.cc搭建http客户端和服务器，做了如下修改：
对于客户端，设置超时时间、等待时间、发送超时均为-1,即
`task->set_receive_timeout(-1);`
`task->set_send_timeout(-1);`
`task->set_wait_timeout(-1);`
对于服务器，模拟收到请求后处理复杂计算，等待完成后再向客户端回复请求，在process回调函数最后增加延时任务，即：
`WFTimerTask* timer = WFTaskFactory::create_timer_task(1000*1000*10,nullptr)  //10s延时`
`series_of(server_task)->push_back(timer);`

实测，当延时设置大于等于10s时，WFHttpClient客户端的请求会报超时错误，小于10s时可以客户端可以正常接收到响应，用Microsoft Edge访问服务器时则无论延时设置为多少均可以正常收到响应。

同样的，在client中把超时时间设置为大于10s的其他值，服务端延时10s时客户端仍会报超时错误。

**Comment by Barenboim** [comment]
我刚刚关了这个issue：https://github.com/sogou/workflow/issues/1175，也是在Windows下遇到类似的问题。不过他的超时正好是30秒，你这边是10秒。这个我目前找不到什么解释，感觉上像是Windows系统调用有什么超时的硬限制，如果要突破这个限制，我们可能要加不少代码。

**Comment by Barenboim** [comment]
不对，这个10秒好像是我们的默认值。你试试task->set_receive_timeout(1000000) ，看看他多久会超时。

**Comment by akjay** [comment]
设置receive_timeout为1s的情况与设置为–1相同，还是会报超时(服务器延时10s)

**Comment by akjay** [comment]
另外我打印了client报告超时的时间，是在请求发出后的20s，但实际上服务器在收到请求后的10s已经给出来回复，客户端没有收到此回复并且在20s的时候给出来超时错误。

**Comment by Barenboim** [comment]
如果完全不改receive_timeout呢？10秒之后可以收到回复吗？我们默认的receive timeout是无限。

**Comment by akjay** [comment]
完全不设置超时时间现象和之前一样，而且不论超时设置为多少现象都一样，似乎这个参数并没有生效

**Comment by Barenboim** [comment]
不好意思，对client来讲，读取的超时还受到全局配置的response_timeout控制。response_timeout指的是，每成功读取或发送一块数据的超时，这个超时默认是10秒。也就是说，哪怕receive_timeout是无限制，也需要每10秒收到至少1字节的数据。这个可以这么修改：
~~~cpp
#include <workflow/WFGlobal.h>

int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.response_timeout = 100 * 1000; // 100秒
    WORKFLOW_library_init(&settings);
}
~~~
上面的代码修改全局的response timeout。你也可以通过 uptream配置来修改某一个独立IP或域名的参数。

**Comment by akjay** [comment]
> 不好意思，对client来讲，读取的超时还受到全局配置的response_timeout控制。response_timeout指的是，每成功读取或发送一块数据的超时，这个超时默认是10秒。也就是说，哪怕receive_timeout是无限制，也需要每10秒收到至少1字节的数据。这个可以这么修改：
> 
> ```c++
> #include <workflow/WFGlobal.h>
> 
> int main()
> {
>     WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
>     settings.endpoint_params.response_timeout = 100 * 1000; // 100秒
>     WORKFLOW_library_init(&settings);
> }
> ```
> 
> 上面的代码修改全局的response timeout。你也可以通过 uptream配置来修改某一个独立IP或域名的参数。 20秒那个可能是你retry max等于1

感谢大佬，修改设置参数后问题解决了！
