### ISSUE TITLE
workflow-websocket分支使用时遇到崩溃现象

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1208]
场景:
server端监听一个地址,我通过wf-client连接正常收数据,此时server端挂死,wf-client端也崩溃

gdb后错误在
../src/factory/Workflow.cc:37 行
具体代码是
37: assert(!series_of(first)) 
38:first->set_pointer(this) 

我该如何继续定位或者解决这个问题

**Comment by Detxie** [comment]
用官方给的例子测试发现server端关闭不会出现上述情况,目前我是把client端嵌入到自己代码中管理 出现了上述问题,关于
‘
gdb后错误在
../src/factory/Workflow.cc:37 行
具体代码是
37: assert(!series_of(first))
38:first->set_pointer(this)
’
这个问题有什么排查解决思路么

**Comment by holmes1412** [comment]
你好，请问是用什么server测试的呢？“把server挂死”是指gdb卡住吗？可以提供一下更加详细的信息我去复现排查一下。

另外怎么把代码嵌入到你的代码里用法方便的话也发我一下哈～

**Comment by Detxie** [comment]
> 你好，请问是用什么server测试的呢？“把server挂死”是指gdb卡住吗？可以提供一下更加详细的信息我去复现排查一下。
> 
> 另外怎么把代码嵌入到你的代码里用法方便的话也发我一下哈～
1.Server用的Go实现,其他的Serve如Python写的一个工具也会这样
2."Server"挂死比如将Go程序停止,Python工具点击停止监听
3.Client我是用一个Object类来实现管理(Object里面clietn实现用的官方的代码),用map缓存object类,看了一下崩溃前没有并没有走Object的析构函数。
4.用gdb起的wf-client端,报上面的错误
5.我现在直接使用官方的代码测试把Server退出后 client没有问题,所以/src/factory/Workflow.cc:37中37: assert(!series_of(first)) 这个问题是怎么造成的呢,或许我能排查一下?

**Comment by Detxie** [comment]
@holmes1412 
1.Server用的Go实现,其他的Serve如Python写的一个工具也会这样
2."Server"挂死比如将Go程序停止,Python工具点击停止监听
3.Client我是用一个Object类来实现管理(Object里面clietn实现用的官方的代码),用map缓存object类,看了一下崩溃前没有并没有走Object的析构函数。
4.用gdb起的wf-client端,报上面的错误
5.我现在直接使用官方的代码测试把Server退出后 client没有问题,所以/src/factory/Workflow.cc:37中37: assert(!series_of(first)) 这个问题是怎么造成的呢,或许我能排查一下?

**Comment by holmes1412** [comment]
1. 我先前也用过go的server互通过，停止过确实也没发现问题，你说的有问题的停止具体是不是强制退出进程呢？是什么平台呢？
2. 这个错误直接猜测是出错（而非关闭且发送一个close frame）而引发的出错流程的bug，我晚上再详细看看。

**Comment by Detxie** [comment]
@holmes1412 
1.client强制退出进程
2.linux

**Comment by holmes1412** [comment]
workflow 框架如果任务发出，client强制退出的话是不能保证的正确的。如果你用tutorial的例子没有问题，可能需要考虑参考下里边的wait_group和signal配合的退出写法？

**Comment by Detxie** [comment]
@holmes1412 
我没描述清楚,是Server直接断开后,client直接奔溃
伪代码实现:
`
funcA(){
    obj = Object()
   map[k] = obj //全局map
}

funcB(){
   obj = map[k]
   obj.Run() 
   ......
   ......
}
`

`
//Object::Run实现
   this->client = WebsocketClient(process_recv) 
   this->client.init(url) 
   wg(1)
   task = this->client.create_websocket_task(process_send) //这里就是tutorial中的三个task
   msg = task->get_msg()
   msg->set_text_data()
   task->start()
   wg.wait()
   //方法从这里退出
`

此时断开Server。就出现上面问题

**Comment by Detxie** [comment]
@holmes1412 
已解决
1.项目中也用到了主线的代码,可能出错的版本有个地方冲突了
2.重新编译了一下websokect分支的代码
按上述操作ws-client不会崩溃退出 了

**Comment by holmes1412** [comment]
@Detxie 好的！使用期间如果有任何问题也欢迎随时交流

**Comment by Barenboim** [comment]
@Detxie 项目中用上了，记得点一下star呀。

**Comment by Detxie** [comment]
> > @holmes1412 已解决 1.项目中也用到了主线的代码,可能出错的版本有个地方冲突了 2.重新编译了一下websokect分支的代码 按上述操作ws-client不会崩溃退出 了
> 
> 我是说点一下星星啊。不是点爱心……

star 了

**Comment by Barenboim** [comment]
> > > @holmes1412 已解决 1.项目中也用到了主线的代码,可能出错的版本有个地方冲突了 2.重新编译了一下websokect分支的代码 按上述操作ws-client不会崩溃退出 了
> > 
> > 
> > 我是说点一下星星啊。不是点爱心……
> 
> star 了

多谢！
