### ISSUE TITLE
websocket server

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1209]
我想使用workflow来实现一个websocket的server服务。现在有这方面的解决方案么

**Comment by Barenboim** [comment]
Server的话，有一个用户修改的项目，是支持的：
https://github.com/gnblao/workflow/tree/channel
你可以看一下这个。

**Comment by Barenboim** [comment]
项目里好像只实现了标准的websocket协议，你自己在process里可以处理推送逻辑吧。之前他发过一个issue介绍这个项目：https://github.com/sogou/workflow/issues/873

**Comment by gnblao** [comment]
> 感谢回复！ 另外我在这个项目中没有看到有关于Server向Client进行订阅推送的接口方式。以及处理Client请求的接口。

更新代码了，新的demo里有接口，让srv和cli有相互推送的接口了～

**Comment by Barenboim** [comment]
@gnblao 要不你把channel改成默认分支？大家一看就知道项目是做什么的
