### ISSUE TITLE
看到conan 工具链 管理各种CPP 包非常方便 可以支持一下conan 吗？

### ISSUE THREAD

**Issue by betteryjs** [sogou/workflow#1212]
看到conan 工具链 管理各种CPP 包非常方便 可以支持一下conan 吗？

**Comment by chanchann** [comment]
要不要试试xmake的工具链，感觉更方便

**Comment by Barenboim** [comment]
我们目前自己维护的只有xmake-repo，vcpkg偶尔更新一下。然后Debian，ubuntu和Fedora三个Linux发行版都有自带安装包，直接apt-get或dnf一下就可以了。Conan也很有名，如果有需要可以帮我们上传一下。
