### ISSUE TITLE
现在的WebSocket 支持wss协议吗？

### ISSUE THREAD

**Issue by yurr2008** [sogou/workflow#1215]
使用tutorial-14 的websocket_cli 似乎不支持wss协议，使用时会http upgrade失败，server返回 400 The plain HTTP request was sent to HTTPS port

**Comment by Barenboim** [comment]
你也可以看一看这个的websocket： https://github.com/gnblao/workflow/tree/channel
我们这个再查一下。

**Comment by Barenboim** [comment]
这是他的示例：
https://github.com/gnblao/workflow/blob/channel/tutorial/tutorial-14-websocket_cli.cc

**Comment by holmes1412** [comment]
@yurr2008 已经加上了，和go的wss的server互通过ok。麻烦试试，如果还有什么问题欢迎随时给我们反馈～
Pull Request: https://github.com/sogou/workflow/pull/1221

**Comment by Barenboim** [comment]
@yurr2008
