### ISSUE TITLE
如何和已有的一些基础设施结合?

### ISSUE THREAD

**Issue by neland** [sogou/workflow#1220]
看了整个框架，很优雅，对任务抽象那部分很感兴趣
自己所在团队已经有了很多底层相关的通信方式 ，有开源的，也有不开源的
大部分都是异步流程，现在仅仅是想使用任务抽象那部分(有很多原因不能完全按照kafka、自定义协议之类的推进)
结合自身异步应答，把复杂的异步流程抽象为一个完整的事务，简化业务逻辑
不知道有没有小伙伴曾经做过相关库的剥离? 或者在完整库上面如何开展

**Comment by Barenboim** [comment]
理论上，任何一个其它框架的异步任务+WFCounterTask就可以构成一个workflow里的任务，这个可以参考这个文档：
https://github.com/sogou/workflow/blob/master/docs/about-counter.md#server%E4%B8%8E%E5%85%B6%E5%AE%83%E5%BC%82%E6%AD%A5%E5%BC%95%E6%93%8E%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8
不过对于一些简单的协议，推荐用我们的自定义协议模式实现一下。

**Comment by Barenboim** [comment]
@neland
