### ISSUE TITLE
为什么可以设置linkoff为sizeof (struct poller_result)呢？

### ISSUE THREAD

**Issue by Aglargil** [sogou/workflow#1223]
https://github.com/sogou/workflow/blob/701be478571f63bf8e70b44d4f27233b4c343e24/src/kernel/Communicator.cc#L1411

请教一下，这里设置linkoff为sizeof (struct poller_result)，那么不应该会使用结构体外面的地址吗？这样为什么可以呢？

**Comment by Barenboim** [comment]
因为callback里的poller_result是由一个__poller_node强转的，__poller_node的定义在：
https://github.com/sogou/workflow/blob/b8e24193a6e0c3fc9e2a4b079b59cdd403d9ee3a/src/kernel/poller.c#L47
这个结构体比poller_result多了6个指针，因此，callback里的poller_result后面有空间可以利用。我在poller.h里注释了。

**Comment by Aglargil** [comment]
好的，谢谢

**Comment by sourcema** [comment]
> 因为callback里的poller_result是由一个__poller_node强转的，__poller_node的定义在：
> 
> https://github.com/sogou/workflow/blob/b8e24193a6e0c3fc9e2a4b079b59cdd403d9ee3a/src/kernel/poller.c#L47
> 
> 这个结构体比poller_result多了6个指针，因此，callback里的poller_result后面有空间可以利用。我在poller.h里注释了。

poller_node比poller_result多出来的结构是：
#pragma pack(1)
	union
	{
		struct list_head list;
		struct rb_node rb;
	};//3 pointer
#pragma pack()
	char in_rbtree;
	char removed;
	int event;//1
	struct timespec timeout;//2
	struct __poller_node *res;//1
多出来的指针大小不是：3+1+2+1=7么？

**Comment by Barenboim** [comment]
> > 因为callback里的poller_result是由一个__poller_node强转的，__poller_node的定义在：
> > https://github.com/sogou/workflow/blob/b8e24193a6e0c3fc9e2a4b079b59cdd403d9ee3a/src/kernel/poller.c#L47
> > 
> > 这个结构体比poller_result多了6个指针，因此，callback里的poller_result后面有空间可以利用。我在poller.h里注释了。
> 
> poller_node比poller_result多出来的结构是： #pragma pack(1) union { struct list_head list; struct rb_node rb; };//3 pointer #pragma pack() char in_rbtree; char removed; int event;//1 struct timespec timeout;//2 struct __poller_node *res;//1 多出来的指针大小不是：3+1+2+1=7么？

哈哈哈。是的目前是7个指针了。好像res是我后加的。

**Comment by sourcema** [comment]
> > > 因为callback里的poller_result是由一个__poller_node强转的，__poller_node的定义在：
> > > https://github.com/sogou/workflow/blob/b8e24193a6e0c3fc9e2a4b079b59cdd403d9ee3a/src/kernel/poller.c#L47
> > > 
> > > 这个结构体比poller_result多了6个指针，因此，callback里的poller_result后面有空间可以利用。我在poller.h里注释了。
> > 
> > 
> > poller_node比poller_result多出来的结构是： #pragma pack(1) union { struct list_head list; struct rb_node rb; };//3 pointer #pragma pack() char in_rbtree; char removed; int event;//1 struct timespec timeout;//2 struct __poller_node *res;//1 多出来的指针大小不是：3+1+2+1=7么？
> 
> 哈哈哈。是的目前是7个指针了。好像res是我后加的。

谢谢回复，我还以为我算错了。

**Comment by Barenboim** [comment]
> > > > 因为callback里的poller_result是由一个__poller_node强转的，__poller_node的定义在：
> > > > https://github.com/sogou/workflow/blob/b8e24193a6e0c3fc9e2a4b079b59cdd403d9ee3a/src/kernel/poller.c#L47
> > > > 
> > > > 这个结构体比poller_result多了6个指针，因此，callback里的poller_result后面有空间可以利用。我在poller.h里注释了。
> > > 
> > > 
> > > poller_node比poller_result多出来的结构是： #pragma pack(1) union { struct list_head list; struct rb_node rb; };//3 pointer #pragma pack() char in_rbtree; char removed; int event;//1 struct timespec timeout;//2 struct __poller_node *res;//1 多出来的指针大小不是：3+1+2+1=7么？
> > 
> > 
> > 哈哈哈。是的目前是7个指针了。好像res是我后加的。
> 
> 谢谢回复，我还以为我算错了。

在32bits系统下，会多8个指针，因为
~~~c
{
#pragma pack(1)
    union
    {
        struct list_head list;
        struct rb_node rb;
    };
#pragma pack()
    char in_rbtree;
    char removed;
    int event;
}
~~~
这部分需要占5个指针。rb_node只能和后面两个char挤到4个指针里，int event需要独立占一个指针空间。
