### ISSUE TITLE
HTTP 超时时间

### ISSUE THREAD

**Issue by wxing2008666** [sogou/workflow#1224]
auto *http_task = WFTaskFactory::create_http_task(url, 0 , 0, callback);
http_task->set_receive_timeout(300);

上面这个set_receive_timeout没有生效？

WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
settings.endpoint_params.response_timeout = 200;

你好！
问题1：全局的超时settings.endpoint_params.response_timeout  和  http_task->set_receive_timeout(300);  如果都设置了，哪个会生效？

问题2：有没有办法为每个连接单独设置超时时间？

谢谢

**Comment by Barenboim** [comment]
你好。
receive_timeout是一个任务级的参数，指完整读取完一个response（对server来讲，则是完整读取一个request）的时间，默认值为-1，表示无限。response_timeout是全局参数，可以为单个upstream独配置，代表每读取或发送一块数据的时间，默认10秒。
对于一个http client任务，读取时会要求同时满足这两个参数的约束。例如，如果response_timeout是10秒，而receive_timeout为1秒，那么response_timeout在这里就不起作用了。如果相反，receive_timeout为10秒，response_timeout为1秒，那么就要求server至少每秒返回一块数据，并且10秒内完成整个response的传输。
问题2我没有太明白，receive_timeout是任务级的，粒度比单个连接更小。response_timeout能到upstream这个级别，你可以把你的IP放在一个upstream里，然后设置这个upstream的参数。

**Comment by wxing2008666** [comment]
目前我们的使用方式是：
WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
settings.poller_threads = 24;
settings.handler_threads = 24;
settings.endpoint_params.connect_timeout = 35;
WORKFLOW_library_init(&settings);

同时
auto *http_task = WFTaskFactory::create_http_task(url, 0 , 0, callback);
http_task->set_receive_timeout(300);


就是只设置了任务级别的receive_timeout，全局的response_timeout没有设置，应该是默认值；

但是任务级别的300毫秒超时时间没生效，超过300毫秒了还没有超时，超时时间没生效

**Comment by wxing2008666** [comment]
目前我们的使用方式是：
WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
settings.poller_threads = 24;
settings.handler_threads = 24;
settings.endpoint_params.connect_timeout = 35;
WORKFLOW_library_init(&settings);

同时
auto *http_task = WFTaskFactory::create_http_task(url, 0 , 0, callback);
http_task->set_receive_timeout(300);


就是只设置了任务级别的receive_timeout，全局的response_timeout没有设置，应该是默认值；

但是任务级别的300毫秒超时时间没生效，超过300毫秒了还没有超时，超时时间没生效

怎么才能让任务级别的超时时间生效？从而达到目的，每个任务使用不同的超时时间

**Comment by Barenboim** [comment]
这个没道理啊。你实际多久回到callback?结果是成功还是失败？按你这个配置，最多等一个connect_timeout+receive_timeout。

**Comment by Barenboim** [comment]
还可能是dns超时了！dns的参数也在全局设置里。
