### ISSUE TITLE
关于websocket-client 超时的机制

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1232]
看文档描述,在未接受到server发送的数据后，默认10S会断开连接。
在断开时,我该如何做后续的处理。或者我怎么知道client是什么时候断开的。现在测试没发现会自动断开。。
现在有个场景,服务端在未正常关闭时,不会发送opclose数据包。所有想尝试使用这个逻辑,做后续的逻辑处理

**Comment by Detxie** [comment]
> @Detxie 感谢！这里是两个问题：
> 
> 1. 关于自动断开的逻辑：
>    我确认了下，是"第一次请求server后还没收到数据的话，默认10s就会断开"，而只要server回复了，就会一直保持连接，现在默认是没有通过ping去发心跳，后续如果会有心跳才会考虑后续的断开。
>    文档的描述是不准确的，我改一下文档。
> 2. 关于被server断开如何感知？
>    内部是可以知道断开的，目前感觉是我应该给你构造一个Close Frame，通过process传给你，这样只要你process里拿到opcode==WebSocketFrameConnectionClose的时候，就是断开了，可以做后续处理。
>    这个我明天加上～
> 
> ```c++
> void process(WFWebSocketTask *task)
> {
>     if (task->get_msg()->get_opcode() == WebSocketFrameConnectionClose)                   
>     {
>         ...
>     }
> }  
> ```

感谢！

**Comment by Detxie** [comment]
> @Detxie 感谢！这里是两个问题：
> 
> 1. 关于自动断开的逻辑：
>    我确认了下，是"第一次请求server后还没收到数据的话，默认10s就会断开"，而只要server回复了，就会一直保持连接，现在默认是没有通过ping去发心跳，后续如果会有心跳才会考虑后续的断开。
>    文档的描述是不准确的，我改一下文档。
> 2. 关于被server断开如何感知？
>    内部是可以知道断开的，目前感觉是我应该给你构造一个Close Frame，通过process传给你，这样只要你process里拿到opcode==WebSocketFrameConnectionClose的时候，就是断开了，可以做后续处理。
>    这个我明天加上～
> 
> ```c++
> void process(WFWebSocketTask *task)
> {
>     if (task->get_msg()->get_opcode() == WebSocketFrameConnectionClose)                   
>     {
>         ...
>     }
> }  
> ```

现在有一个疑惑点,现在有两种关闭处理的方式.
client(process,connection_close)
(1)第一种就是之前的处理逻辑，process里面判断opcode是不是close数据,这种需要server端主动发送opclose
(2)第二种就是在连接关闭时会调用connection_close,目前测试server端不发送opclose或者发送opclose都会调用这个connection_close()
现在版本意思是只处理connection_close()即可？,process只处理optext或者opbinary就可以了么？

**Comment by holmes1412** [comment]
@Detxie 对的，任何情况下被关了都会调用到connection_close这个回调，process里可以只处理：optext、opbinary、opping/oppong就行。

我想了想，如果你想要知道“server发close的原因”，那么process里才需要处理下opclose。

另外，昨天另一个小伙伴帮我定位了一个debug模式下被关闭的小问题，我今天也会尽快推进修复，并且推进这个PR
的合并：https://github.com/sogou/workflow/pull/1237/files 

谢谢~

**Comment by Detxie** [comment]
> @Detxie 对的，任何情况下被关了都会调用到connection_close这个回调，process里可以只处理：optext、opbinary、opping/oppong就行。
> 
> 我想了想，如果你想要知道“server发close的原因”，那么process里才需要处理下opclose。
> 
> 另外，昨天另一个小伙伴帮我定位了一个debug模式下被关闭的小问题，我今天也会尽快推进修复，并且推进这个PR 的合并：https://github.com/sogou/workflow/pull/1237/files
> 
> 谢谢~

多谢
