### ISSUE TITLE
内置json如何生成 这个结构，尝试了好久，我无法生成这个结构

### ISSUE THREAD

**Issue by ma-zhiqiang** [sogou/workflow#1233]
使用wfrest 响应json数据时， 需要使用如下结构
![image](https://user-images.githubusercontent.com/60458644/227953818-94156b4f-46b4-4734-b548-249fa9781645.png)
，但是我尝试了好多，还是无法生成这个结构， 文档中灭有找到， 主要是data里面的数组这个结构

![image](https://user-images.githubusercontent.com/60458644/227954571-1211cd2a-2d8e-4002-a7e3-8294e3459578.png)
![image](https://user-images.githubusercontent.com/60458644/227954715-a77cd38d-a44d-49b3-91b7-f4a63ef60fbe.png)

请指点一下

**Comment by Barenboim** [comment]
https://github.com/wfrest/wfrest/issues/155
