### ISSUE TITLE
如何实现一个只接收消息但不回复，并且不断开连接的server？（Windows）

### ISSUE THREAD

**Issue by fightCC** [sogou/workflow#1234]
您好：
1、应用场景server 只接收数据30秒一次，不回复。
2、windows 分支下  append 返回1 process 后连接被自动断开。
3、请问如何让连接一直保持。 谢谢！！

**Comment by Barenboim** [comment]
你是用来做server吧？还是说是一个workflow的client？

**Comment by fightCC** [comment]
> 你是用来做server吧？还是说是一个workflow的client？
对 做server，按示例的自定义消息，经测试Linux下正常，在windows下，encode 返回0后也会把客户端连接给断开。noreply也会把客户端连接断开。看这两种情况框架会调用release_conn函数执行closesocket操作。

**Comment by fightCC** [comment]
必须的，框架接口清晰易用，感谢😊。

**Comment by Barenboim** [comment]
Windows下MySQL协议，client也是先发一个空包，连接是没有问题的。所以为什么server发完空包连接会断，这个代码在这里：
https://github.com/sogou/workflow/blob/81b5afac5565c560c5ed03d5a5870556c34dbb0d/src/kernel_win/Communicator.cc#L1830

**Comment by fightCC** [comment]
跟踪了下发现是这样：服务端encode返回0后，执行到

```c++
  handle_incoming_idle()
 if(--entry->ref==0)
 Communicator.cc1155      release_conn(entry)
``` 
连接被关闭。

**Comment by Barenboim** [comment]
> 跟踪了下发现是这样：服务端encode返回0后，执行到
> 
> ```c++
>   handle_incoming_idle()
>  if(--entry->ref==0)
>  Communicator.cc1155      release_conn(entry)
> ```
> 
> 连接被关闭。

这个好奇怪。我不知道回去1字节和回复0字节在这里有什么区别。你如果response是1 byte，是不是没有这个问题？

**Comment by fightCC** [comment]
对 response是1byte 就没有这个问题，0就会释放连接出现上面的问题。
