### ISSUE TITLE
连接https，使用固定ip

### ISSUE THREAD

**Issue by yurr2008** [sogou/workflow#1240]
这边连接一个https服务，有多个可用ip，其中一个ip比较快，使用curl工具可以用如下的命令行，让域名解析为指定的ip
curl --resolve example.com:443:127.0.0.1 https://example.com/test
对应的libcpr http/https库也有类似的参数设置

请教下workflow这边create_http_task 如何人为设置dns解析url中的域名为指定的固定ip，这边尝试用WFServiceGovernance类，但是可能由于代码理解不到位的原因，导致https报ssl错误
`

	WFServiceGovernance* policy = new WFServiceGovernance();
	std::string address = "127.0.0.1:443";
	struct AddressParams param = ADDRESS_PARAMS_DEFAULT;
	param.endpoint_params.use_tls_sni = true;
	policy->add_server(address, &param);
        WFNameService *ns = WFGlobal::get_name_service();
        ns->add_policy("example.com", policy);
       std::string url = "https://example.com/test"
	task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
										   wget_callback);
	protocol::HttpRequest *req = task->get_req();
	req->add_header_pair("Accept", "*/*");
	req->add_header_pair("User-Agent", "Wget/1.14 (linux-gnu)");
	req->add_header_pair("Connection", "close");
	task->start();
`

**Comment by Barenboim** [comment]
用upstream就可以了吧？没必要自定义名称服务。把快的ip的权重搞大一点。

**Comment by Barenboim** [comment]
你直接用域名的话，感觉也没问题啊。一个域名如果解析出来多个ip，这些ip会有负载均衡的。快的ip自然请求多。

**Comment by yurr2008** [comment]
> 用upstream就可以了吧？没必要自定义名称服务。把快的ip的权重搞大一点。
这个能麻烦给个简单demo代码吗？

**Comment by yurr2008** [comment]
> 你直接用域名的话，感觉也没问题啊。一个域名如果解析出来多个ip，这些ip会有负载均衡的。快的ip自然请求多。
主要是有些ip ping延时会低一些，我们想延时更低些

**Comment by Barenboim** [comment]
主页上就有链接：
https://github.com/sogou/workflow/blob/master/docs/about-service-governance.md

**Comment by Barenboim** [comment]
@yurr2008 跑通了的话和我们反馈一下啊。项目中用上请点一下star。

**Comment by yurr2008** [comment]
> @yurr2008 跑通了的话和我们反馈一下啊。项目中用上请点一下star。
好的，刚刚写代码试了下，部分域名IP是可以的，但是有些域名Ip会报错，比如 https://testnet.binancefuture.com/fapi/v1/time 这个域名，我用ping获取ip后，然后用upstream
代码就是仿照主页上的写的，
`
		UpstreamManager::upstream_create_weighted_random("testnet.binancefuture.com", false);
		struct AddressParams params = ADDRESS_PARAMS_DEFAULT;
		params.endpoint_params.use_tls_sni = true;
		params.weight = 1;
		UpstreamManager::upstream_add_server("testnet.binancefuture.com", "18.65.185.27:443", &params);

	struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
	settings.poller_threads = 1;
	settings.handler_threads = 1;
	settings.endpoint_params.use_tls_sni = true;
	WORKFLOW_library_init(&settings);

	task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
										   wget_callback);
	protocol::HttpRequest *req = task->get_req();
	req->add_header_pair("Accept", "*/*");
	req->add_header_pair("User-Agent", "Wget/1.14 (linux-gnu)");
	req->add_header_pair("Connection", "close");
	task->start();

`

![image](https://user-images.githubusercontent.com/7933278/229069943-28eb8e87-afd7-43b6-a1c2-ee8590b4fb04.png)

**Comment by Barenboim** [comment]
~~~cpp
  UpstreamManager::upstream_add_server("testnet.binancefuture.com", "18.65.185.27:443", &params);
~~~
过里不用加":443"。
~~~cpp
  UpstreamManager::upstream_add_server("testnet.binancefuture.com", "18.65.185.27", &params);
~~~
这样也是对的。
另外，这里可能是因为sni的问题。你改一下全局的配置：
~~~cpp
int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.use_tls_sni = true;
    WORKFLOW_libraray_init(&settings);
    ...
}
~~~

**Comment by Barenboim** [comment]
啊，我这边加了sni，可以抓取的啊。

**Comment by Barenboim** [comment]
> > 啊，我这边加了sni，可以抓取的啊。
> > 你的代码确实没有抓取成功，我看一下是什么原因。
> 
> 好的，麻烦了

这个问题的原因是，你用upstream指向IP之后，我们的sni信息其实无法知道原来的域名，哪怕你的upstream名和域名是一样的。解决问题我们可能需要一些开发时间。你要快速实现这个需求，直接配置一个你自己的hosts文件就可以了。
~~~cpp
int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.hosts_path = "./my_hosts";     // 默认为：/etc/hosts"
    settings.endpoint_params.use_tls_sni = true;
    WORKFLOW_libraray_init(&settings);
    ...
}
~~~
hosts文件的格式，你自己参考一下/etc/hosts。

**Comment by Barenboim** [comment]
如果你的hosts要实时修改，可以缩短一下dns cache的有效期。这样可以更快的重新读取。

**Comment by Barenboim** [comment]
~~~cpp
int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.hosts_path = "./my_hosts";     // 默认为：/etc/hosts"
    settings.endpoint_params.use_tls_sni = true;
    settings.dns_ttl_default = 10;  // 10秒过期。默认12小时。
    settings.dns_ttl_min = 1;  // 出错时，超过1秒就更新。默认3分钟
    WORKFLOW_libraray_init(&settings);
    ...
}
~~~
如上。麻烦star一下！

**Comment by yurr2008** [comment]
> ```c++
> int main()
> {
>     WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
>     settings.hosts_path = "./my_hosts";     // 默认为：/etc/hosts"
>     settings.endpoint_params.use_tls_sni = true;
>     settings.dns_ttl_default = 10;  // 10秒过期。默认12小时。
>     settings.dns_ttl_min = 1;  // 出错时，超过1秒就更新。默认3分钟
>     WORKFLOW_libraray_init(&settings);
>     ...
> }
> ```
> 
> 如上。麻烦star一下！

多谢，已star

**Comment by Barenboim** [comment]
嗯嗯，感谢使用。你试试我的方法吧。如果有问题，随时问。
