### ISSUE TITLE
如何实现JS 跨域访问 

### ISSUE THREAD

**Issue by hjfsz** [sogou/workflow#1245]
我用workfow 搭建了一个 HTTPS服务 提供外部访问接口，但JS就是无法访问，Postman可以。请问要怎么设置？

**Comment by Barenboim** [comment]
是server SNI吗？多个证书？

**Comment by chanchann** [comment]
js跨域访问增加一个"Access-Control-Allow-Origin: *"头字段就能解决吧

**Comment by hjfsz** [comment]
问题已经解决，加了下面协议头就好了
resp->add_header_pair("Access-Control-Allow-Origin", "*");
	resp->add_header_pair("Access-Control-Allow-Methods", "GET,POST");
	resp->add_header_pair("Access-Control-Max-Age", "3600");
	resp->add_header_pair("Access-Control-Allow-Headers", "*");
	resp->add_header_pair("Access-Control-Allow-Credentials", "true");

**Comment by Barenboim** [comment]
好的。那我这边也把issue关了哈。如果项目中用上了，记得点星星，感谢！
