### ISSUE TITLE
workflow能够实现sse服务端吗

### ISSUE THREAD

**Issue by ManfredJZ** [sogou/workflow#1248]
各位大佬各位前辈们，想问一下workflow能够实现Server-Sent Events吗

**Comment by Barenboim** [comment]
可以具体点描述需求吗？我也不太懂Server-Sent Events是什么类型的应用。

**Comment by ManfredJZ** [comment]
> 可以具体点描述需求吗？我也不太懂Server-Sent Events是什么类型的应用。

感谢您的回复，简单的说就是http的持久化连接，每当我服务器收到新数据时，就将数据发送给客户端，类似websocket但更轻量级

**Comment by ManfredJZ** [comment]
> 可以具体点描述需求吗？我也不太懂Server-Sent Events是什么类型的应用。

然后我这个程序既需要作为客户端又需要作为服务端，作为客户端我会向一个远程api发送请求然后他会不停回包，我每收到一个包就拆解获取所需数据，然后又打包发给客户端

**Comment by Barenboim** [comment]
这个类似于K8s的API server。可以实现的，参考这个issue：
https://github.com/sogou/workflow/issues/929

**Comment by ManfredJZ** [comment]
> 这个类似于K8s的API server。可以实现的，参考这个issue： #929

十分感谢，我明白了作为服务端是可行的，还有另一个问题，就是workflow能不能实现作为客户端，从一个连接一直不停的收包呢

**Comment by Barenboim** [comment]
这个也是可行的！我们这个项目就是实现一个K8s API server的client：https://github.com/sogou/workflow-k8s
不过，这个里面的实现搞得太复杂了。如果你是自定义协议，就是自己在append函数里挂钩子。我们框架不关心你append过程，每收到一块数据怎么处理完全你自己决定。

**Comment by Barenboim** [comment]
不客气，感谢使用！注意一下，server task->push是同步非阻塞操作，理论上如果tcpbuf满了，可能无法push全部数据，或者得到EAGAIN。这个时候需要你自己解决剩余数据的重试问题。比如加入timer等待，一段时间之后再push剩余数据。

**Comment by ManfredJZ** [comment]
> 不客气，感谢使用！注意一下，server task->push是同步非阻塞操作，理论上如果tcpbuf满了，可能无法push全部数据，或者得到EAGAIN。这个时候需要你自己解决剩余数据的重试问题。比如加入timer等待，一段时间之后再push剩余数据。

好的，感谢提醒！

**Comment by Barenboim** [comment]
我们在wfrest项目里实现了SSE规范以及更一般的server推送。可以帮我们试用一下。
https://github.com/wfrest/wfrest

**Comment by Barenboim** [comment]
基于Workflow的RESTful项目wfrest项目实现了SSE规范以及更一般的server推送。可以帮我们试用一下。
https://github.com/wfrest/wfrest
