### ISSUE TITLE
websocket task->get_error()问题

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1250]
1.这个问题是概现的,还没发现如何百分百复现
2.用的是websocket分支的代码
3.在使用WFXXTASK时,比如当前使用的是 WFWebSocketTask *task, 报的错误为 task->state = 1, task->error = 1076943786(这个error每次都不一样)----代码就是Websocket样例中client 给server发数据那里 create_websocket_task
4.同一个创建逻辑,多次调用就会概现上面的问题

目前我该怎么继续排查呢？ 这个error代表的是什么? error和什么有关

**Comment by holmes1412** [comment]
这个error应该是没有被初始化导致的，所以state设置了，但error没设置。
我检查一下流程，也麻烦你描述一下更具体的场景，或者server行为等其他信息，感谢🙏

**Comment by Detxie** [comment]
> 

:) 
在给出的样例程序中我未复现出这个问题.
实际使用中将client实例做了多层包装,多个线程使用
目前并没有找到合适的排查方向，这个error未被设置,有什么排查的方向吗。现在主要在看释放连接的逻辑

**Comment by holmes1412** [comment]
样例程序里没有高并发，所以不能复现也是正常，但是error没有改值怎么想都是不对的。
我的排查方向：
- 目前把样例改成并发测了一会儿，暂时没有复现出这种情况，会继续换方式测试；
- 继续review一下代码逻辑；

**Comment by holmes1412** [comment]
@Detxie 你好，我大概知道问题了，另外就是还有别的要改动，明天我会再提个PR，感谢～

**Comment by holmes1412** [comment]
本次问题的修改：https://github.com/sogou/workflow/pull/1251
感谢开发者小伙伴帮发现问题🙏

**Comment by Detxie** [comment]
> 本次问题的修改：#1251 感谢开发者小伙伴帮发现问题🙏

感谢！ 我去测试一下
