### ISSUE TITLE
workflow的http-client返回长度不对

### ISSUE THREAD

**Issue by ganggangliu** [sogou/workflow#1252]
发送数据请求，postman返回解析正常：
![image](https://user-images.githubusercontent.com/38499119/232767947-3d0d7a79-aefa-4616-9423-f96c33b9a05f.png)
workflow返回数据代码:
 const void* body;
        size_t body_len;
        task->get_resp()->get_parsed_body(&body, &body_len);
        // Convert the body to a char pointer
        const char* charPtr = reinterpret_cast<const char*>(body);
        printf("charPtr :%s\n", charPtr);
打印输出为：
charPtr :**f88**
{"resultCode":200,"message":"OK","data":{"canframe_num":274,"canList":[-140740726161601,-140740721967297,-140740717772993,-140740713578689,4539839526863961983,-144393278617812960,2574090796752437312,2574090796756666944,2574090796760836677,2574091896545103688,2574090796752456777,2574090796756680521,2574090796760889161,2574090796765055819,2574090796752501067,2574090796756632652,2574090796760847692,2574091896545109325,2574090796752485198,2574090796756644943,2574090796760880463,-19414076274226560,-1244868155348055424,-295699353798437503,652502994210291073,1313476603963565697,1750272991264515458,2193912743231787650,1615182590342858115,1173935371374318723,366612361614246531,-356461656294232445,-948580566569555836,-1819006721917940348,-2483375632176108923,-1690794874312789371,-1251658739152829050,-7468969065127802,1159386654994618247,-53189973959456633,1464399959461220232,1464241646954115976,-48686374336326775,-48686374332117879,-48686374327894135,669532260353505161,368846582126792074,-291195741286134901,-4777377472644725,-437421991695743860,-439937661410978420,-7029177290571635,-439796923914230387,-727956935629336946,-14910476642632818,-1244780190118693745,-1681594178187242097,-2123017280361547888,-1832517542270678895,-1686291291865289583,-956549796782912110,-444282927073144430,-439849713365640813,-18288176761648512,-18763157190702464,1152489400966845825,3440231163141586305,3440301527595017857,3440248751041029506,3440283939695530626,5187662994343462275,3440371883454256259,3440319106900345475,3440354304144764547,3440459844380289156,-18691671759221372,-1207729938606052731,-1171755017669381499,-1171719846178044538,-1171649473134665594,-1171508727052216441,-18288176770004857,-1171614297356742776,-1171772609847069816,-18288176757468279,-18288176770036599,-18288176765812855,-1171596662216788087,-1171667065316520566,-1171649468848108661,-18288176765798005,-1171508731351399284,-18851096646101620,-273778260557683,-695960656648819,-625596203266418,-273778247943282,-660793468636017,-625617682246257,1152507023226091408,1098482489334745233,1098341751833816209,1098500107282173330,1098482519395324306,1098412133475457427,-3169569562907115360,-5110304553269985120,-668798025568,-668793795936,-668806403419,-668802199640,-668798006103,-668793782359,-668806350935,-668802184277,-668797961813,-668793830228,-668806392404,-668802194003,-668797977682,-668793817937,-668806359633,585306624135547552,-8919821864402384224,5351522404785500064,246129277194999201,-1553058773935313759,2490892216470896033,-5140457352104198239,1205114522848257697,850737527173684386,-5705659105343429214,-7933815020980774750,-1370100039077555550,3537980229341992866,-5247979693700282973,-5171699975007491677,-5671036583704767325,-2067030981897331037,-3568418507667750237,8033698557372975523,8398490127177412259,-7807713131911174236,-5926334387572938588,-2465881023887935580,-7146809886598722140,-4540070127277115740,6347101596430117541,160563083310825125,6659820295547318949,2994734623802016678,2490612940517426598,5737426796879046822,-3543647610213965658,-3681007398844622937,2523828087280916391,3832405254012974759,-3011095854765782873,2625722028845977512,2268530283404355752,3855204727126520744,2135392619411850152,-1890543972476513367,-2820537295524311895,-2158225575808286807,-3880852433290070103,-3282436632799039062,-4936383595946652246,7536054097083368363,7407701507690761131,3669150867024040619,4106000030883183019,2450083842410153132,-5755474678671453268,9088671168122607020,-8048088363971328596,-7745784238979923795,-1400493839004179027,-6863078712023654995,-8370658687281787218,-5331853739197695314,-1721655687919387730,1318837010513278127,-8978925012441862481,5660588526283576751,836107425450357167,9145248737953101744,-7484573261573374031,3772174007043410097,-9123320575991160399,7739563803771727025,5291575931323350449,2490618438079761842,6684032641102563250,7982195233696305586,1152767873769822899,4618851836500679091,4482899422736866995,6711081516342463136,4264501018777651
**5de**
872,3329722621125767072,3911531397974070689,9100804068615924897,-983318447015821919,4136148429401800609,-7751665737008617823,-2056864008194483038,6086207068048991650,-4648404118761088862,-8393147208932224350,8254690288623736738,-7812745806946499165,7968993187270764963,980813940462736547,-1036798692595048797,263052749858980515,8837906440376600995,7469656578573528739,5597285033498388388,-1679687539397990236,-7660186369565100124,-6506983389994119772,6896855000971540132,6032726822473968293,3799785832232550053,2792105415595848357,1351797959771571110,2937065028610180518,8701954026625329318,-303837853244661594,-2464721249448224857,3156896985421207463,-1957784816383904089,-876639430850852697,3233176704105598888,-4692877165085562712,-7502841857583844440,5829501889280525224,4606211640500163497,9002850776724819113,-2667946182624886871,-5765015351384803415,5048691403400982954,509907403945856426,5987691925716075435,-7987540667980543061,-1860674849915481429,6499413433371916715,-5389808107905350484,-4882871674862021716,2179054015835821484,20985369399444908,4853066294595436717,170730057001100717,3345486319324814765,7670630811464896174,1909963938108832430,3713655588858149806,7681045385599005871,6314202898696269487,-7156908011694795345,2355820301205959087,2506972363703760816,6330809922322186161,66584315630766257,4102654006672286129,-7714509940566987599,-8650695713102430799,-5045282736411488846,8433429097854060466,-7346902521471249998,1016000511583214259,5269087409685436851,5126942546433990323]}}
0

**（上面2个空行是打印出来的）**
**5de也是多出来的，正常中间没有这个值**
4264501018777651
**5de**
872
**应该是：4264501018777651872**

其中：**f88**，header，offset错误的，postman长度为162，workflow的debug模式offset为160，差2个字节；
整个返回的长度：postman显示5.51k，这里面msgbuf的长度5657；

猜测：是否是多线程导致读的时候中间多读了些数据。

**Comment by ganggangliu** [comment]
黑色为异常数据，用boost.beast及其他的库都没问题，workflow异常。

**Comment by Barenboim** [comment]
是Linux平台是吧？

**Comment by ganggangliu** [comment]
是的，ubuntu20.04，gcc9.03

**Comment by Barenboim** [comment]
这是chunk编码呀。我们默认是返回原文的，避免不必要的内存复制。解码chunk编码，可以直接用HttpUtil里的HttpChunkCursor或调用HttpUtil::decode_chunked_body()

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/61dca8e699856eeff1ea59780c50669ab1dd4a88/src/protocol/HttpUtil.h#L164
https://github.com/sogou/workflow/blob/61dca8e699856eeff1ea59780c50669ab1dd4a88/src/protocol/HttpUtil.h#L126

**Comment by Barenboim** [comment]
{
    std::string body = HttpUtil::decode_chunked_body(resp);
}

**Comment by ganggangliu** [comment]
服务器采用chunk编码导致解析错误，更为如下：   
 std::string html1 =protocol::HttpUtil::decode_chunked_body(resp);
 std::cout << html1 << std::endl;
解析成功。

**Comment by Barenboim** [comment]
嗯嗯，可以用ChunkCursor，进一步减少内存复制。
记得star项目哈。
