### ISSUE TITLE
编译的一些问题

### ISSUE THREAD

**Issue by gooker** [sogou/workflow#1253]
cmake.在虚拟机(centos)的共享目录(win10)编译 链接权限会出现错误,当然放非共享目录编译没问题

CMake Error: failed to create symbolic link '../../_lib/libworkflow.so.0': Operation not supported
CMake Error: cmake_symlink_library: System Error: Operation not supported
CMake Error: failed to create symbolic link '../../_lib/libworkflow.so': Operation not supported
CMake Error: cmake_symlink_library: System Error: Operation not supported

xmake(环境centos7.8 gcc10.2.1 make2.6.8),平时主要用xmake
1. 出现下面错误,加了set_exceptions("no-cxx") 跳过
`error: ./xmake.lua:23: global 'set_exceptions' is not callable (a nil value)`
2. 还是编不过去

[ 30%]: ccache compiling.release src/util/json_parser.c
error: /mnt/hgfs/vmshare/github/workflow/_include/workflow/list.h:1:1: error: expected identifier or ‘(’ before ‘.’ token
    1 | ../../kernel/list.h
      | ^
In file included from src/util/json_parser.c:27:
src/util/json_parser.h:41:1: error: unknown type name ‘json_value_t’
   41 | json_value_t *json_value_parse(const char *doc);
      | ^~~~~~~~~~~~
src/util/json_parser.h:42:1: error: unknown type name ‘json_value_t’
   42 | json_value_t *json_value_create(int type, ...);
      | ^~~~~~~~~~~~
src/util/json_parser.h:43:25: error: unknown type name ‘json_value_t’
   43 | void json_value_destroy(json_value_t *val);
      |                         ^~~~~~~~~~~~
src/util/json_parser.h:45:27: error: unknown type name ‘json_value_t’
   45 | int json_value_type(const json_value_t *val);
      |                           ^~~~~~~~~~~~
src/util/json_parser.h:46:37: error: unknown type name ‘json_value_t’

**Comment by Barenboim** [comment]
第一个问题是不是windows文件系统不支持符号链接啊。用cmake编译，动态库是要用符号链接的，xmake就没有。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/61dca8e699856eeff1ea59780c50669ab1dd4a88/xmake.lua#L23
这一行是xmake作者帮我们加的啊。是不是你的xmake版本的问题？如果去了这一行，最好这个地方：
https://github.com/sogou/workflow/blob/61dca8e699856eeff1ea59780c50669ab1dd4a88/xmake.lua#L39
改成：
add_cxxflags("-fPIC", "-fno-exceptions", "-pipe", "-Wno-exceptions")
另外，后面你没有编译过，还是符号链接的问题。我们src下的include目前，需要符号链接。

**Comment by gooker** [comment]
windows符号链接的问题,知道一些,主要是之前很少遇到...

xmake2.6.8 -> 2.7.8  set_exceptions这个解决了.

下面这个还是不行.
[ 30%]: ccache compiling.release src/util/json_parser.c
error: /mnt/hgfs/vmshare/github/workflow/_include/workflow/list.h:1:1: error: expected identifier or ‘(’ before ‘.’ token

**Comment by gooker** [comment]
确实是这个问题,  xmake /cmake 都不能放 虚拟机共享到windows的目录,因为符号链接不支持.

**Comment by gooker** [comment]
我把 hello world加入到我的程序 发现编译出错,首先subtask命名冲突,这个改了,然后出现下面的报错
centos7.8 c++20 gcc 10.2.1
![image](https://user-images.githubusercontent.com/5688076/233242355-3dac8017-5317-4d7d-9fda-9e680cd6fb24.png)

**Comment by Barenboim** [comment]
我感觉是你的cmake没写好？这个报错也太奇怪了。你可以试试用srpc工具建项目：
https://github.com/idealvib

**Comment by Barenboim** [comment]
可能是cmake没写对？你可以试试用srpc工具来建项目：https://github.com/sogou/srpc/blob/master/tools/README_cn.md

**Comment by gooker** [comment]
> 可能是cmake没写对？你可以试试用srpc工具来建项目：https://github.com/sogou/srpc/blob/master/tools/README_cn.md

我的项目用的是xmake写的编译规则很简单,也使用了很多c++库 没有遇到过这种问题.

**Comment by chanchann** [comment]
> > 可能是cmake没写对？你可以试试用srpc工具来建项目：https://github.com/sogou/srpc/blob/master/tools/README_cn.md
> 
> 我的项目用的是xmake写的编译规则很简单,也使用了很多c++库 没有遇到过这种问题.

能不能给下你是怎么写的，我复现一下

**Comment by chanchann** [comment]
> > 可能是cmake没写对？你可以试试用srpc工具来建项目：https://github.com/sogou/srpc/blob/master/tools/README_cn.md
> 
> 我的项目用的是xmake写的编译规则很简单,也使用了很多c++库 没有遇到过这种问题.

我xmake升级到2.7.8没问题
