### ISSUE TITLE
客户端连接问题

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1256]
使用WFNetworkTaskFactory<REQ, RESP>::create_client_task创建的客户端连接在底层有没有连接池，有的话如何限制socket的数量。

**Comment by Barenboim** [comment]
有连接池。最大连接数在全局配置或upstream配置。这个值默认是200，超过了得到EAGAIN错误。
BTW，这个和用什么协议没关系，http也是受这个的控制。

**Comment by Barenboim** [comment]
不过有一点，自定义协议默认是短连接，需要调一下task->set_keep_alive()设置连接保持时间。这个在示例里有。

**Comment by coderwxl** [comment]
有只针对客户端socket连接数的配置吗

**Comment by Barenboim** [comment]
你具体需求是什么？

**Comment by coderwxl** [comment]
我有一个自定义协议的server，server里面会通过create_client_task创建tcp客户端连接其它的服务，但是这个其它的服务要求同时只能有一个socket连接，所以我就想问下有只针对tcp客户端连接数的配置吗。

**Comment by Barenboim** [comment]
这个方法好多啊。可以用资源池，也可以用同步等待的方法。推荐用资源池：
https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md
这里相当于限制并发度的问题。
