### ISSUE TITLE
Delete WFResourcePool是否存在内存泄漏

### ISSUE THREAD

**Issue by gnblao** [sogou/workflow#1257]
virtual ~WFResourcePool() { delete []this->data.res; }
这个地方在delete一个   WFResourcePool时候也需要清理data-> wiat_list中的condition吧，不然有可能内存泄漏风险

**Comment by Barenboim** [comment]
我们好像是默认你必须都归还res，才能释放资源池的吧？

**Comment by gnblao** [comment]
> 我们好像是默认你必须都归还res，才能释放资源池的吧？

嗯嗯，看到dns中把资源池当作全局变量来用应该没问题。除全局变量场景外，想灵活主动释放资源池和资源池中一连串条件还是很有用的。我想想怎么扩展下^_^

**Comment by Barenboim** [comment]
> > 我们好像是默认你必须都归还res，才能释放资源池的吧？
> 
> 嗯嗯，看到dns中把资源池当作全局变量来用应该没问题。除全局变量场景外，想灵活主动释放资源池和资源池中一连串条件还是很有用的。我想想怎么扩展下^_^

我感觉和全局或非全局没有什么关系。就是默认要用完才能释放。如果用户在资源池申请了很多conditional然后直接把资源池删了，我们好像并没有什么好办法处理这种情况。直接把这些conditional释放也是不对的。

**Comment by gnblao** [comment]
> > > 我们好像是默认你必须都归还res，才能释放资源池的吧？
> > 
> > 嗯嗯，看到dns中把资源池当作全局变量来用应该没问题。除全局变量场景外，想灵活主动释放资源池和资源池中一连串条件还是很有用的。我想想怎么扩展下^_^
> 
> 我感觉和全局或非全局没有什么关系。就是默认要用完才能释放。如果用户在资源池申请了很多conditional然后直接把资源池删了，我们好像并没有什么好办法处理这种情况。直接把这些conditional释放也是不对的。

嗯，确实是个问题，有可能这conditional背后是一连串task，这样确实比较麻烦 :^)
