### ISSUE TITLE
close回调和client.deinit() 疑问

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1258]
现在遇到的问题
1.新的client(process,close) -- 这个close回调函数概现会被调用两次
2.这个client.deinit()函数调用时机？我现在是放在close()回调里面执行,会出现问题: gdb 堆栈如下
   src/kernel/Communicator.cc:1471
   src/kernel/poller.c:926
   src/kernel.poller.c:1021

**Comment by Detxie** [comment]
我是这么使用ws-client ，省去了好多其他业务代码，只保留ws相关的

有一个全局变量map

(1)启动 一个run线程 初始化一个client 
client = websocketClient(process,close) 
map[k] = client 

其中的 close(){
   client.deinit() 
   map.erase(k) 
}

2.启动发送数据线程 create_websocket_task() 
3.waitGroup等待发送数据线程执行完成
4.退出Run线程 

close回调接收到异常后 关闭链接

**Comment by Detxie** [comment]
> 

多谢讲解！

**Comment by holmes1412** [comment]
客气~ 新增close接口的用法建议，我也整理到文档中🙏

**Comment by Detxie** [comment]
关于deinit(),目前我在项目中又遇到了一个奇怪的问题 
1.我在项目中是 这样的流程
ws-client.init(url) -> process 接受数据 > ws-client.deinit()
我会有多个ws-client端,当其中一个ws-client(比如实例A)不使用时,我会调用A的deinit()方法,来释放连接,因为A初始化时的process里面有我传入的其他资源,我需要调用A的deinit()来销毁process生命周期,从而释放我传入Process中的资源。
2.我使用如下方式调用时程序会崩溃
---两个接口
接口1:
初始化一个client a 连接的地址是 c  --- 创建了一段时间
接口2:
(1) a.deinit() (我在1~2步骤之间加了延时，发现还未执行步骤2在步骤1执行完就挂死了) 
(2)初始化一个client b 连接的地址是c 

3.gdb大概信息 
# 0 xxx in Communicator::callback(res = xx , context = )  at xxx/src/kernel/Communicator.cc:1471
# 1 xxx in __poller_handle_timeout()   at  src/kernel/poller.c:926
# 2 xxx in __poller_thread_routine () at src/kernel/poller.c:1021
# 3 from /lb63/libpthread.so.0 
# 4 from /lib64/libc.so.6

**Comment by Detxie** [comment]
> 你好，关于1. 中调用a.deinit()来释放资源不是很明白，可以再描述具体一点么？我理解的deinit()是用来给用户显式给对方发一个close包并关闭连接用的，可以看看你具体的是什么调用需求。
> 
> 2.里挂的原因大概是deinit()完a内部的双工channel就会被delete，然后这个堆栈就挂在关闭连接的时候调用这个channel->handle_terminate()上。
> 
> 可以等你给更具体的1.的用法之后我模拟一下🙏

把项目拆解完测试了。
1.官方版无问题, 嵌入到项目中有问题
2.官方版-release无问题,项目release版本无问题

目前已经解决了,嵌入到项目中使用在编译debug版本时会有问题,改了一些依赖。现在可以了

**Comment by holmes1412** [comment]
好的，你们定位问题很给力！如果用法有不好用、容易给开发者误用的地方也欢迎随时提建议～
