### ISSUE TITLE
能否取消未执行的图节点

### ISSUE THREAD

**Issue by tothedistance** [sogou/workflow#1259]
可以在任务执行流外面的线程中取消未执行的任务吗，我看有cancel字段。一个线程在创建图并运行，callback是一样的函数。然后可能某些节点我不执行了。

**Comment by Barenboim** [comment]
另外一个线程是可以调用series->cancel()函数的，这个问题不大。最大的问题是，你必须有机制可以保证，你调用的时候series还存在而不是已经是一个野指针。不过我感觉这个好像也不是太难。

**Comment by tothedistance** [comment]
series_of不让task往base转。

**Comment by tothedistance** [comment]
图节点的callback还是ok的哦。该被取消的task的callback呢

**Comment by Barenboim** [comment]
> 图节点的callback还是ok的哦。该被取消的task的callback呢

我不太理解你这个问题……series的cancel是取消还没有执行的task。你是在series里放了一个WFGraphTask么？这个时候，如果graph已经在运行了，是cancel不了的。

**Comment by tothedistance** [comment]
图里面某个节点取消，图的callback应该还是会执行吧。这个被取消的节点的callback会执行么。

**Comment by tothedistance** [comment]
WFGraphTask里面某个task不执行了。这个task的回调会通知某个硬件空闲。

**Comment by Barenboim** [comment]
WFGraphTask里的节点任务不太好取消。你还是配合WFDynamicTask使用吧。如果一个节点可能被取消，用一个WFDynamicTask来表示这个节点，当这个节点不需要被执行，就展开成一个empty task。
这个的定义在：
https://github.com/sogou/workflow/blob/2283695b114bee2c4dad8eed8fba0948bfa68944/src/factory/WFTaskFactory.h#L328
其中，create是一个std::function，用来产生实际要执行的任务。

**Comment by tothedistance** [comment]
行，我看看。

**Comment by ma-zhiqiang** [comment]
我也遇到这个问题， 比如有俩个节点WFGraphNode a,b， a-->b     然后a执行完成后，做了一些判断，发现不需要执行b，然后直接返回，这个b 是否可以取消或跳过它不执行

**Comment by Barenboim** [comment]
让b是一个dynamic task就可以：
~~~cpp
WFDynamicTask *b = WFTaskFactory::create_dynamic_task([](WFDynamicTask *b) {
        if (...)
            return WFTaskFactory::create_xxx_task();
        else
            return WFTaskFactory::create_empty_tas();
    });
~~~

**Comment by ma-zhiqiang** [comment]
ok， 我看看
