### ISSUE TITLE
我想利用workflow写一个用cuda处理计算

### ISSUE THREAD

**Issue by JackyLucifer** [sogou/workflow#1261]
cuda加速计算
先把要计算的数据和结果都给cuda内存
完后cuda计算
计算完了
把结果再弄回到内存

有没有类似写这样任务流的例子
我也是没办法，不用cuda，cpu根本算不过来

**Comment by JackyLucifer** [comment]
好的，谢谢
https://github.com/arrayfire/arrayfire
后续使用arrayfire这个库和workflow结合的例子也会给上来

**Comment by holmes1412** [comment]
太厉害了～期待一下！期间欢迎随时交流，和GPU使用的深度结合我也还在学习中

**Comment by WangFengtu1996** [comment]
最近也在看taskflow 
https://github.com/taskflow/taskflow.git
