### ISSUE TITLE
并行编程库技术比较和探讨

### ISSUE THREAD

**Issue by unity20221019** [sogou/workflow#1262]
首先，感谢workflow提供的解决方案。已start！
最近想在C++库里找一个并行库实现大量http请求的并发，并且尽量确保请求的成功率。同一个物理机上。想测试耗尽带宽的情况下，能达到多快的速度。
目前找到的几个库在进行比较，想在底层实现方面多一些了解和技术思路探讨。
英特尔的并行开源库TBB。根据提供的信息，TBB 采用基于工作窃取算法的任务调度方式，将一个大任务分解成多个小任务，并且自动平衡负载，保证所有 CPU 核心都能充分利用。这个不知道对workflow的优化是否有借鉴意义。本来用curl+tbb实现 不过成功率不高，可能需要再根据实时的结果再动态调整对应的并行数和超时设置，另外还有共享一些网络连接相关的cache。
目前刚开始看workflow，好像我checkout了nossl的分支，但是用cmake编译的时候还是提醒需要设置openssl相关的系统变量。 

我稍微修改了 parallel_wget 的源码。暴力请求了一万次百度的地址。记录返回成功次数大概有400-600次，用时1到2秒。因为这里没有做队列或者同时请求数的并发控制。可能的使用场景会是定时的需要请求几千个http的数据，失败了就收集失败的请求再继续重试。想问问在workflow里该如何做这类需求。 之前用网站压测工具测试过本地的带宽 同样也是请求百度，成功个数会有几百个每秒，当然后面也是会短期内被限制请求的权限。

针对上面的情况，目前是想根据实时的请求结果，失败成功的次数来调整并发的请求数，确保比较顺利的请求到数据。

这里也提出一点疑惑。本人在网络编程方面了解不多。如果假如按照测速工具，物理机带宽是1M每秒，那么如果我同时请求某个网址，加入每个请求的数据量大小是1k，除开其他的通信开销，那么极限的理论上的成功速度是否是逼近1000条 才是达到性能内最优的状态。同一主机的http连接数是否有其他的因素限制。希望有经验的老哥帮忙解释解释。

还有一个我一会测试下用cmake的fetch content 能否直接在原有工程的基础上直接添加workflow库进来。这样会更有利于已有项目的接入workflow 方便使用和推广。

单个http请求的返回中 ，能否和curl一样有方法获取本次请求的耗时，CURLINFO_TOTAL_TIME。

**Comment by Barenboim** [comment]
是的，nossl分支其实还是需要链接libcrypto，因为要用到SHA256 和RSA的一些加密算法。并行计算的问题我看一下，应该是个好问题！

**Comment by Barenboim** [comment]
另外如果觉得项目好，可以先star一下哈：）

**Comment by Barenboim** [comment]
关于你抓百度并发度的问题，如果你不控制直接100w个同时过去，肯定大多数都是错误的。并发度的控制我们有很好的方法，在这个文档里有说明：
https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md
其中第二个点就是并发度控制的问题。

**Comment by Barenboim** [comment]
不好意思前面几天太忙没有来得及回复。
1、关于并行计算，我们有一个自己的模型。这个模型的特点是不适合做粒度特别小的计算调度，因为我们并没有使用任何的无锁技术来加快消息队列的put/get吞吐量，而据我所知work stealing都是基于CAS的无锁队列的。我们的计算调度更有利于多种任务下的公平调度，提升计算+网络的应用里服务的平均响应时间以及优化长尾效果。具体的算法运行原理可以参考这个文章：https://zhuanlan.zhihu.com/p/518265010
2、workflow作为spider吞吐率和支持的并发度是非常高的。你同时并发抓100万个百度首页肯定无法成功。起码默认参数里我们对一个IP:port并发度就只有200（当然可以调整）。用workflow实现spider可以满足绝大多数需求。
3、建立cmake项目，可以使用srpc工具：https://github.com/sogou/srpc/blob/master/tools/README_cn.md
4、请求耗时这个，你需要自己统计。当然也可以二次封装。我记得srpc里封装的http client就可以统计请求时间，甚至可以以opentelemetry的协议自动上报。
