### ISSUE TITLE
fio 对接 workflow 客户端，出现段错误

### ISSUE THREAD

**Issue by xxpbb** [sogou/workflow#1264]
![heihei](https://user-images.githubusercontent.com/70773497/233842651-b544f147-858b-4981-bbed-eadd64262489.png)

**Comment by Barenboim** [comment]
你好。你提供的信息到少了，我无法确认你这个错误。这个看上去应该不是我们的bug。

**Comment by Barenboim** [comment]
好的。让我们查问题的话，在不泄露机密的情况下信息越全面越好！感谢。

**Comment by Barenboim** [comment]
你说的这个fio是什么呢？
从你代码上看，我没有看出什么问题，就是导出了一个c语言的接口。lambda捕获那里捕获的arg指针，你确认一下生命周期没有问题应该就是对的。我一会再仔细review一下你的代码。

**Comment by Barenboim** [comment]
你好，这个有什么新进展吗？ @xxpbb
