### ISSUE TITLE
如何提高mysql插入更新速度

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#1266]
我现在基于mysql异步客户端，创建了一个series，把任务放到里面去执行，目前一秒钟执行20条左右语句，有其他更好的方式提高执行速度吗？比如能支持批处理？

**Comment by xiaoshizijiayou** [comment]
单个series，能支持从多个线程往里添加任务吗，我测试时发现不行，会出现死锁，不执行sql任务的情况

**Comment by holmes1412** [comment]
你指的添加任务是指series->push_back()或者series->push_front()么？多个线程往里添加不会有问题的。可以更具体描述一下场景？

另外问下，多个线程往同一个series添加是什么需求呢？如果你有并行的需求，多发起几个series就可以了，只有前后请求回复有依赖关系的任务才需要穿到一个series中。

**Comment by xiaoshizijiayou** [comment]
我创建了一个paralle，里面加了5个series，怎么往每个series里动态添加任务呢，本来想用pwork->series_at(i)，但是这个返回的是const，不能修改，请解答下

**Comment by Barenboim** [comment]
pwork->series_at()最新代码，有一个重载。当pwork不是const时，返回的指针也不是const。
~~~cpp
public:
class ParallelWork : public ParallelTask
{
public:
	SeriesWork *series_at(size_t index)
	{
		if (index < this->subtasks_nr)
			return this->all_series[index];
		else
			return NULL;
	}

	const SeriesWork *series_at(size_t index) const
	{
		if (index < this->subtasks_nr)
			return this->all_series[index];
		else
			return NULL;
	}
};
~~~

**Comment by xiaoshizijiayou** [comment]
我参考blockseries的使用集成到程序 ，现在就一个series，出现了一次死锁，任务不执行了，还没有改成多个呢
