### ISSUE TITLE
咨询一个关于生产者和消费者的问题

### ISSUE THREAD

**Issue by libaineu2004** [sogou/workflow#1274]
咨询一个问题：
方法1、多线程实现生产者-消费者问题
方法2、多进程实现生产者-消费者问题
请问哪个性能更好？执行效率更高？

应用场景是多对多：
生产者是几十个工业相机采集图像；
消费者是要处理这些图像，有算法耗时。

**Comment by Barenboim** [comment]
这个不好说吧。不过多线程之前的消息传递，肯定比多进程的快，毕竟共享内存空间。
你说生产者是一些硬件，那肯定需要把消息通过网络发送到什么地方统一处理吧？

**Comment by libaineu2004** [comment]
> 这个不好说吧。不过多线程之前的消息传递，肯定比多进程的快，毕竟共享内存空间。 你说生产者是一些硬件，那肯定需要把消息通过网络发送到什么地方统一处理吧？

是单机。就一台电脑。生产者和消费者都在一台电脑。相机采集的图片会进入到消息队列。

**Comment by Barenboim** [comment]
相机和处理进程之前怎么传递数据呢？还是要用TCP/IP网络吧，还是说是读一个设备描述字？
如果通过网络，可以开一个workflow的server接收一下，然后里面就是线程之间的消息传递问题了。

**Comment by libaineu2004** [comment]
> 相机和处理进程之前怎么传递数据呢？还是要用TCP/IP网络吧，还是说是读一个设备描述字？ 如果通过网络，可以开一个workflow的server接收一下，然后里面就是线程之间的消息传递问题了。

是通过网络。传输这部分是相机厂商提供的SDK。我们应用程序只能在他们封装好的回调函数，获取每一帧的图像。

**Comment by Barenboim** [comment]
嗯嗯，那就在进程里处理就可以了。如果用workflow的话，在回调里创建计算任务并执行。
