### ISSUE TITLE
希望int WFServerBase::create_listen_fd()是protected成员

### ISSUE THREAD

**Issue by wangyongxiao** [sogou/workflow#1275]
希望int WFServerBase::create_listen_fd()是protected成员，而不是private成员，这样可以有机会设置他为FD_CLOEXEC，或者其他的socket设置

**Comment by Barenboim** [comment]
我觉得你说的有道理。我改一下。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1276
