### ISSUE TITLE
client是怎样触发server的？

### ISSUE THREAD

**Issue by checkman-shy** [sogou/workflow#1277]
您好，我是一名初学者。想请教一下server是怎样识别是否接收到client的连接的？

**Comment by holmes1412** [comment]
hi~ 这个问题有点模糊。如果是学习怎么上手，可以先通过命令把tutorial编译出来，workflow的server提供的开发接口是一个process()函数，如下，你可以在这里知道client的请求到来，并做一些处理：
```cpp
WFHttpServer server([](WFHttpTask *task) {
    // print...
    task->get_resp()->append_output_body("<html>Hello World!</html>");
});
```

如果是想要学习网络连接模型，可以看看Communicator模块，内部调用到下面这一句话的时候就是识别到client的连接，server新建一个会话进行处理。感兴趣可以读一下前后的逻辑～
```cpp
session = service->new_session(entry->seq, entry->conn);
```

**Comment by Barenboim** [comment]
@checkman-shy
