### ISSUE TITLE
http 请求报错

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1279]
使用http task时，请求返回erro: 35，这个错误是因为请求丢得太快了么，我现在的实现是有两个队列一直在发http请求，间隔大概2ms一次。

**Comment by Barenboim** [comment]
你好。你这是macOS是吧？errno 35在mac下就是EAGAIN。
我们对单个IP的最大连接数默认是200，超过了最大连接数并且没有打开等待超时，就是得到EAGAIN。可以增大一下全局的最大连接数配置：
~~~cpp
int main()
{
    WFGobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 2000;
    WORKFLOW_libraray_init(&settings);
    ...
}
~~~
关于全局配置的，有相关的说明：https://github.com/sogou/workflow/blob/master/docs/about-config.md
你也可以通过upstream对单个目标的最大连接数进行配置。

**Comment by 18328594608** [comment]
好的，我还有个问题还想问下，这个网络连接的复用策略是什么？

**Comment by Barenboim** [comment]
连接复用就是简单的先进后出。优先复用刚刚释放的连接。
