### ISSUE TITLE
WFGraphTask 可以获取series的get_context()吗？

### ISSUE THREAD

**Issue by ma-zhiqiang** [sogou/workflow#1285]
[https://github.com/wfrest/wfrest/issues/168](url)

**Comment by Barenboim** [comment]
麻烦你把问题再发一遍，描述清楚。

**Comment by ma-zhiqiang** [comment]
![image](https://github.com/sogou/workflow/assets/60458644/bebdcba0-c544-42a8-91ec-297c0d9feabc)
![image](https://github.com/sogou/workflow/assets/60458644/dc99f817-1313-450e-8795-84b2bee616b7)
![image](https://github.com/sogou/workflow/assets/60458644/58d9f804-cd0b-449b-93ab-28003c9eaf53)

使用wfrest 3个参数重载， 使用WFGraphTask构建图， 然后再task1(第一个节点)的回调中取context, 无法取到,context是null

**Comment by Barenboim** [comment]
噢噢，graph node和graph并不共享同一个series。graph node如果想拿到graph的series，可以用下面的方式：
~~~cpp
void callback(WFXXXTask *task)
{
    ParallelTask *p = series_of(task)->get_in_parallel();
    SeriesWork *series = series_of(p);
    ...
}
~~~
get_in_parallel这个函数是v0.10.7加入的，用于得到一个series所在的parallel，通过这个方法可以递归向外找series。

**Comment by ma-zhiqiang** [comment]
好的我尝试一下

**Comment by Barenboim** [comment]
现在wfrest的依赖也是v0.10.7，应该可以直接用。

**Comment by ma-zhiqiang** [comment]
感谢指点，它可以了， 这个新的函数是？

**Comment by Barenboim** [comment]
> 感谢指点，它可以了， 这个新的函数是？

新函数就是SeriesWork::get_in_parallel()啊。

**Comment by ma-zhiqiang** [comment]
它的作用是为了获取父series吗？

**Comment by Barenboim** [comment]
用于获得series所在的并行任务。但一般来讲，用户不是为了得到这个并行任务，而且进一步获得并行任务所在series。这个过程可以递归。有以下几个场合可以用到：
* 在server逻辑里，无论任务在多少级的parallel里都可以得到server task所在的series。
* graph节点，可以得到graph所在series。因为graph的所有节点，其实也在一个parallel。
* module里的任务，可以得到module所在的series。这个和graph一个道理。
SeriesWork::get_in_parallel()返回值是一个ParallelTask而不是ParallelWork，主要是为了兼容module。不过这些都不重要，一般用不到这个类。

**Comment by ma-zhiqiang** [comment]
好的，感谢
