### ISSUE TITLE
串行流men leak

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1286]
使用方式如下：
SeriesWork *series = Workflow::create_series_work(http_task,
                                                      nullptr);
    series->push_back(go_task);
    series->start();
在运行Valgrind时这地方报了一个警告，使用这个SeriesWork方法时 指针需要自己释放么

**Comment by Barenboim** [comment]
应该是你代码的问题，我们测试都是开valgrind的。能不能贴一下完整的程序？

**Comment by 18328594608** [comment]
void ProtocolHttpRequest::send_http_request(std::string request_body, WFGoTask *go_task) {

    std::string url = ConfigManager::getInstance().getNetworkIo();
    std::string http_url = url;
    if (strncasecmp(url.c_str(), "http://", 7) != 0 &&
        strncasecmp(url.c_str(), "https://", 8) != 0)
    {
        http_url = "http://" + http_url;
    }
    WFHttpTask *http_task  = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
                                                             response_callback);

   // BaseRequestPtr base_ptr = std::make_shared<ProtocolHttpRequest>(*this);
    http_task->user_data = this;

    ParsedURI uri;
    if (URIParser::parse(http_url, uri) < 0)
    {
        return;
    }

    std::string route;
    if (uri.path && uri.path[0])
    {
        route.append(uri.path);
    } else
    {
        route.append("/");
    }

    if(uri.query && uri.query[0])
    {
        route.append("?");
        route.append(uri.query);
    }

    HttpRequest *req = http_task->get_req();
    req->add_header_pair("Content-Type", "application/json");
    req->set_method("POST");
    req->set_request_uri(route);
    __proto_body = request_body;
    req->append_output_body(static_cast<const void *>(request_body.c_str()), request_body.size());

    SeriesWork *series = Workflow::create_series_work(http_task,
                                                      nullptr);
    series->push_back(go_task);
    series->start();
}
完整函数是这样，go_task为在http请求返回处理完成之后回调通知调用方的接口，调用方通常是智能指针的对象。

**Comment by Barenboim** [comment]
Valgrind的报错信息是什么呢？是不是OpenSSL 1.1以上退出时的泄露问题?





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月31日(周三) 中午1:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 串行流men leak (Issue #1286)




 
void ProtocolHttpRequest::send_http_request(std::string request_body, WFGoTask *go_task) {
 std::string url = ConfigManager::getInstance().getNetworkIo(); std::string http_url = url; if (strncasecmp(url.c_str(), "http://", 7) != 0 &amp;&amp;     strncasecmp(url.c_str(), "https://", 8) != 0) {     http_url = "http://" + http_url; } WFHttpTask *http_task  = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,                                                          response_callback);  
// BaseRequestPtr base_ptr = std::make_shared(*this);
 http_task-&gt;user_data = this;
 ParsedURI uri; if (URIParser::parse(http_url, uri) < 0) {     return; } std::string route; if (uri.path &amp;&amp; uri.path[0]) {     route.append(uri.path); } else {     route.append("/"); } if(uri.query &amp;&amp; uri.query[0]) {     route.append("?");     route.append(uri.query); } HttpRequest *req = http_task-&gt;get_req(); req-&gt;add_header_pair("Content-Type", "application/json"); req-&gt;set_method("POST"); req-&gt;set_request_uri(route); __proto_body = request_body; req-&gt;append_output_body(static_cast<const void *&gt;(request_body.c_str()), request_body.size()); SeriesWork *series = Workflow::create_series_work(http_task,                                                   nullptr); series-&gt;push_back(go_task); series-&gt;start();  
}
 完整函数是这样，go_task为在http请求返回处理完成之后回调通知调用方的接口，调用方通常是智能指针的对象。

**Comment by 18328594608** [comment]
64 bytes in 1 blocks are possibly lost in loss record 56 of 259
  at 0x4865058 malloc
  at 0x5190637 gaih_inet.constprop.0 (getaddrinfo.c:1039)
  at 0x51918BB getaddrinfo (getaddrinfo.c:2240)
  at 0x4923793 DnsRoutine::run(DnsInput const*, DnsOutput*) (DnsRoutine.cc:110)
  at 0x4950A87 WFResolverTask::dispatch() (WFDnsResolver.cc:272)
  at 0x6718FF SeriesWork::start() (Workflow.h:71)
  at 0x66FF4F ProtocolHttpRequest::send_http_request(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, WFGoTask*) (ProtocolHttpRequest.cpp:143)
  at 0x6936AB HistoryOrders::request_core(WFGoTask*) (HistoryOrders.cpp:144)
  at 0x7A6523 DealServer::_run(void*, int) (DealServer.cpp:48)
  at 0x710CDF CServer::__go(void*, int) (Server.cpp:85)
  at 0x66AF97 void std::__invoke_impl<void, void (CServer::*)(void*, int), CServer*, int*, int>(std::__invoke_memfun_deref, void (CServer::*&&)(void*, int), CServer*&&, int*&&, int&&) (invoke.h:74)
  at 0x66AD37 std::__invoke_result<void (CServer::*)(void*, int), CServer*, int*, int>::type std::__invoke<void (CServer::*)(void*, int), CServer*, int*, int>(void (CServer::*&&)(void*, int), CServer*&&, int*&&, int&&) (invoke.h:96)
完整的Valgrind堆栈是这样的，看起来是erro往外抛出的时候malloc出来没有释放掉
