### ISSUE TITLE
如何用workflow框架去跟Openssl TLS结合做一个HTTPS通信

### ISSUE THREAD

**Issue by MasterL-min** [sogou/workflow#1287]
大致需求是：
1.客户端去跟服务器完成一个TLS握手，双方协商一个对称密钥，在C++里客户端实现这个TLS握手的函数应该是SSL_connect，服务器是SSL_accept
2.双方用生成的对称密钥进行通信
如何把这个去跟workflow的框架结合起来有点困惑，假设客户端创建一个WFNetworkTaskFactory<REQ, RESP>::create_client_task后，如何在这个task里实现这个SSL_connect步骤呢？

**Comment by Barenboim** [comment]
Https通信不是本来就支持了么？

**Comment by MasterL-min** [comment]
> 你用tutorial里wget示例，直接就能抓https的。

if (strncasecmp(argv[1], "http://", 7) != 0 &&
		strncasecmp(argv[1], "https://", 8) != 0)
	{
		url = "http://" + url;
	}
tutorial里wget我只能找到这个...很困惑，还有就是这个openssl是自己定制的，需要走一个openssl握手流程，实在是在wget里找不到对应部分...

**Comment by MasterL-min** [comment]
> 这个有什么问题吗？你直接： $ ./wget https://www.baidu.com/ 就是抓取https的百度首页。https server的话，tutorial-09-http_file_server就是支持的，需要传一下证书。 openssl握手相关的，workflow里都实现了。我们甚至支持MySQL over TLS，只要写成“mysqls://”就可以。 你是想使用https还是想知道原理？

emmm...那就是说只要我指定url是https，剩下的这些握手什么的就不需要我们去做了是吗，只要把url设定好即可...如果是这样的话，那我是不是只要用的是把定制的Openssl匹配上，把url设定成https开头即可，openssl握手在workflow内部实现，不再需要去手动写代码

**Comment by Barenboim** [comment]
定制的openssl是说你的openssl库是你改过的？那你就链接你的libssl就可以了，只要接口兼容。我们本来也完全支持openssl或boringssl。
如果你是需要做ssl双向认证，可以取出client的ssl_ctx，自己添加认证信息：
~~~cpp
{
    SSL_CTX *ssl_ctx = WFGlobal::get_ssl_client_ctx();
    SSL_set_verify(ssl_ctx, ...);
    task = WFTaskFactory::create_http_task("https://....", ...);
}
~~~

**Comment by MasterL-min** [comment]
> 
是的是的，是改过的，好的好的，感谢您，那我http payload加密什么的是不是也不用管，直接创建任务后append_output_body，这个包里的内容会自动变成握手协商出来的密钥加密后的,只要url是https开头即可。

**Comment by Barenboim** [comment]
对你有帮助的话记得star啊。感谢。
