### ISSUE TITLE
关于workflow和std:executor之间的区别和联系

### ISSUE THREAD

**Issue by heliark** [sogou/workflow#1291]
如题，刚刚翻阅了下workflow相关文档，感觉我们这个库和std:executor有部分功能有重叠。想问下在设计和使用层面的区别和联系～

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Barenboim** [comment]
你好。我们和现代C++的executor没有联系，也没有参考过相关的文档。
实现上我们的异步模型是kernel目录下的SubTask，一共就100行代码，不包含模板。我们的Executor模块是我们的计算执行器，和Communicator通讯调度器对应，这个和std::executor可能不一样。

**Comment by Barenboim** [comment]
> > 你好。我们和现代C++的executor没有联系，也没有参考过相关的文档。 实现上我们的异步模型是kernel目录下的SubTask，一共就100行代码，不包含模板。我们的Executor模块是我们的计算执行器，和Communicator通讯调度器对应，这个和std::executor可能不一样。
> 
> 哈哈，这儿没有想说workflow是“抄袭”std:executor。我想问的是，从设计思想上，两者是否有什么区别。 之后是否有可能结合着使用~

嗯嗯，就是因为设计思想上完全没有联系，所以确实也没有抄袭的可能。关键是我完全看不懂std::executor……
我们的异步是这两个文件：
https://github.com/sogou/workflow/blob/master/src/kernel/SubTask.h
https://github.com/sogou/workflow/blob/master/src/kernel/SubTask.cc
任何任务都是从这里派生的。每个任务实现dispatch和done两个操作。在任务完成时，调用一下subtask_done。你可以帮我们看看有没有什么相通之处。
我自己不太喜欢Modern C++那些些。

**Comment by Barenboim** [comment]
@heliark
