### ISSUE TITLE
链接所需Openssl版本编译后使用无变化

### ISSUE THREAD

**Issue by MasterL-min** [sogou/workflow#1292]
使用的客户端是workflow tutorial里的wget，使用的服务器是wfrest里example目录下的19_https，运行时19_https加载example目录下cert目录生成的证书，使用wget访问https://127.0.0.1:8888抓包分析如下所示：
![YLS0KS9Q63O$RDJ5IL8FV2C](https://github.com/sogou/workflow/assets/71004611/e9661a21-72f0-4ecf-a339-94af3c24d41c)
证明workflow编译链接使用的openssl版本是TLS V1.3。
在wfrest example与workflow tutorial文件夹的CMakelist发现，原本的方法是find_package(OpenSSL REQUIRED),找到的版本可能是TLS V1.3，但我目前所需使用的TLS在/opt/openssl文件夹下，使用的版本是TLS V1.2，于是我在两个CMakelist中进行了改动，在example文件夹下的CMakeList中，我没有选择find_package，直接
set(OPENSSL_INCLUDE_DIR "/opt/openssl/include")
set(OPENSSL_LIBRARY_DIR "/opt/openssl/lib64")，
tutorial我进行了一样的操作，只不过tutorial还有一行是
set(WORKFLOW_LIB workflow pthread OpenSSL::SSL OpenSSL::Crypto  ${LIBRT})，
我替换成了
set(WORKFLOW_LIB workflow pthread /opt/openssl/lib64/libssl.so /opt/openssl/lib64/libcrypto.so ${LIBRT})，
接下来sudo cmake . sudo make均无报错，但我运行后抓包分析发现还是TLS V1.3，这种情况该如何解决

**Comment by MasterL-min** [comment]
> 我觉得你应该先看看链接上的是哪个lib，再来看TLS握手协议的问题。你opt下的openssl是否版本不一样？你可以打印一下OPENSSL_VERSION_NUMBER的值，看看到底include的路径对不对再说。而且，你也完全可以把libworkflow.a拿出来，直接手动编译一下。

在看到了消息后，我对这些进行了确认以及处理，我先具体说明一下我对workflow的改动想请您看一下是否正确

**Comment by MasterL-min** [comment]
> 我觉得你应该先看看链接上的是哪个lib，再来看TLS握手协议的问题。你opt下的openssl是否版本不一样？你可以打印一下OPENSSL_VERSION_NUMBER的值，看看到底include的路径对不对再说。而且，你也完全可以把libworkflow.a拿出来，直接手动编译一下。

感谢您的建议，经过两天确认我现在说明情况如下，想请您评估一下我对workflow的cmake改动是否正确：
我在查看workflow源码后发现workflow可能内置实现这一块的文件是src/protocol/SSLWrapper，其中使用了#include<openssl/ssl>等头文件，所以我意识到可能我只更改了tutorial示例文件目录下的cmake是不对的，因此我对workflow/src目录下的cmake文件也进行了更改，指定了在/opt/openssl目录，同时这次在cmake运行中，cmake也输出了-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.8")，因此应该可以确认链接上的库是正确的，基于这个，我把workflow的tutorial，wfrest的src目录 ，wfrest的example目录，全部做了相同的处理，这样保证每一个cmake输出链接的库都是3.0.8版本的Openssl，然后各自进行了sudo make。至此对cmake的改动结束。
目前情况是抓包分析还是TLS V1.3，我又查阅了一下，这可能是因为openssl 3.0.8可能默认使用的TLS协议是1.3，如果能确认上述对cmake改动没问题的话，可能我现在需要做的是如何在workflow或者openssl里进行改动，让他实行TLS版本为1.2协议的握手。
恳请您指教。

**Comment by MasterL-min** [comment]
> > > 我觉得你应该先看看链接上的是哪个lib，再来看TLS握手协议的问题。你opt下的openssl是否版本不一样？你可以打印一下OPENSSL_VERSION_NUMBER的值，看看到底include的路径对不对再说。而且，你也完全可以把libworkflow.a拿出来，直接手动编译一下。
> > 
> > 
> > 感谢您的建议，经过两天确认我现在说明情况如下，想请您评估一下我对workflow的cmake改动是否正确： 我在查看workflow源码后发现workflow可能内置实现这一块的文件是src/protocol/SSLWrapper，其中使用了#include<openssl/ssl>等头文件，所以我意识到可能我只更改了tutorial示例文件目录下的cmake是不对的，因此我对workflow/src目录下的cmake文件也进行了更改，指定了在/opt/openssl目录，同时这次在cmake运行中，cmake也输出了-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.8")，因此应该可以确认链接上的库是正确的，基于这个，我把workflow的tutorial，wfrest的src目录 ，wfrest的example目录，全部做了相同的处理，这样保证每一个cmake输出链接的库都是3.0.8版本的Openssl，然后各自进行了sudo make。至此对cmake的改动结束。 目前情况是抓包分析还是TLS V1.3，我又查阅了一下，这可能是因为openssl 3.0.8可能默认使用的TLS协议是1.3，如果能确认上述对cmake改动没问题的话，可能我现在需要做的是如何在workflow或者openssl里进行改动，让他实行TLS版本为1.2协议的握手。 恳请您指教。
> 
> 原来是这样……这一行
> 
> https://github.com/sogou/workflow/blob/e40dbb7400cdecf220280e435dae66a4fa48cb0f/src/manager/WFGlobal.cc#L197
> 
> 
> 把SSLv23_client_method()改成TLSv1_2_client_method()应该就对了。

您好，之前的根据您的建议全部解决了，非常感谢您。
还想请问下，现在给redis也连上了定制的Openssl库，这边希望用workflow作为redis-cli去跟Redis服务器做加密交互，
我试了下直接把tutorial里的tutorial-02-redis_cli去作为客户端，不使用tls情况下是正常运行的，然后把url开头从redis://改为rediss://,但目前报错ssl error，
Redis服务器显示Error accepting a client connection: error:0A0000C7:SSL routines::peer did not return a certificate (addr=127.0.0.1:48248 laddr=127.0.0.1:6379)
我推测是客户端这边运行没用自己的证书和密钥，如果是这样的话我该如何操作呢，如果是直接在运行时填入证书密钥路径我看代码方面只设置了USAGE: %s <redis URL> <key> <value>，好像没有填证书相关的位置，相关的issue里提到WFGlobal::get_ssl_client_ctx等等，不清楚是要从这里入手吗，主要我考虑到验证客户端证书应该是redis服务器方面的代码相关，感觉应该不是workflow客户端这边需要做的事，有点困惑，恳请您指教

**Comment by Barenboim** [comment]
太好了，之前没有人帮我们试过rediss。你server那边报这个错是因为server要求client的证书吧。加证书的方式就是往ssl_ctx里设置。至于怎么设，你可以找一找相关的函数。大概就是这样：
~~~cpp
#include "workflow/WFGlobal.h"
#include "openssl/ssl.h"
int main()
{
    SSL_CTX *ssl_ctx = WFGlobal::get_ssl_client_ctx();
    SSL_CTX_set_verify(ssl_ctx, ...);
}
~~~
如果rediss跑通了，麻烦告知一下我们。因为我们这边也没有用过这个功能。

**Comment by MasterL-min** [comment]
> 太好了，之前没有人帮我们试过rediss。你server那边报这个错是因为server要求client的证书吧。加证书的方式就是往ssl_ctx里设置。至于怎么设，你可以找一找相关的函数。大概就是这样：
> 
> ```c++
> #include "workflow/WFGlobal.h"
> #include "openssl/ssl.h"
> int main()
> {
>     SSL_CTX *ssl_ctx = WFGlobal::get_ssl_client_ctx();
>     SSL_CTX_use_certificate_file(ssl_ctx, cert_file, SSL_FILETYPE_PEM);
>     SSL_CTX_use_PrivateKey_file(ssl_ctx, key_file, SSL_FILETYPE_PEM);
>     ...
> }
> ```
> 
> 如果rediss跑通了，麻烦告知一下我们。因为我们这边也没有用过这个功能。

您好 后续暂时直接把redis-server那边的验证改成允许单向验证后rediss是成功了的，没有问题。
不过现在有个问题发现之前链接自定义库还是有点问题，
我在workflow的tutorial目录 的cmakelist里改了这些：
set(OPENSSL_INCLUDE_DIR "/usr/local/include/openssl")
set(OPENSSL_LIBRARY_DIR "/usr/local/lib64")
set(WORKFLOW_LIB workflow pthread /usr/local/lib64/libssl.so /usr/local/lib64/libcrypto.so ${LIBRT})
但是我使用ldd wget查看了下他们链接的动态库，我发现
libcrypto.so.3 => /usr/local/lib64/libcrypto.so.3 (0x00007f92f2c00000)
libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f92f3195000)
不知道为什么libcrypto.so是链接的正确的目录，libssl.so没有按我上面设置的那样链接到/usr/local/lib64/libssl.so里面
不知道您有没有遇到过类似情况...而且有点棘手的是他连的这个libssl.so动态库应该是ubuntu22.04默认自带的openssl，想卸载都卸不了，有点痛苦。

**Comment by Barenboim** [comment]
要不别编译workflow的动态库了，全都静态链接，就没这么多事了。

**Comment by MasterL-min** [comment]
> 要不别编译workflow的动态库了，全都静态链接，就没这么多事了。

链接现在解决了，现在的问题是定制的openssl库我的wfrest服务器跟workflow客户端tls握手不成功，自己拿C++手写了一个server和client执行握手查看问题，发现可能是改动后的openssl库，服务器除了得装填cert和key以外还得预先传入DH参数，像这样：
  `SSL_CTX_set_tmp_dh(ctx, dhParams);`
  改动后我自己手写的服务器和客户端能在保证调用的是定制的openssl库下tls握手成功并进行交互了，但是我把这个转到workflow上好像还是报错，我在wfrest的服务器上加了代码如下：
  `
 SSL_CTX *ctx = WFGlobal::new_ssl_server_ctx();
 // Load the DH parameters from a file
    FILE* dhParamFile = fopen("./cert/dhparam.pem", "r");
    if (dhParamFile == nullptr) {
        std::cerr << "Failed to open DH parameters file." << std::endl;
        SSL_CTX_free(ctx);
        return 1;
    }
    DH* dhParams = PEM_read_DHparams(dhParamFile, nullptr, nullptr, nullptr);
    fclose(dhParamFile);
    if (dhParams == nullptr) {
        std::cerr << "Failed to load DH parameters." << std::endl;
        SSL_CTX_free(ctx);
        return 1;
    }
    if(svr.start(8888,argv[1],argv[2])==0)
    {
        SSL_CTX_set_tmp_dh(ctx, dhParams);
        wait_group.wait();
        svr.stop();
    }
    `
    大概是这样，服务器代码改动在wfrest example的19_https文件中，不知道我这样使用的代码对不对，目前在链接定制库的情况下这样还是无法完成tls握手

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/issues/1313
