### ISSUE TITLE
线程池和调度策略等是不暴露给使用者的么

### ISSUE THREAD

**Issue by chloro-pn** [sogou/workflow#1294]
比如我想限制最多使用的计算资源，以及定制一些调度策略这种目前可以实现么，我看了下示例程序好像没有看到。

**Comment by Barenboim** [comment]
第一个问题，限制计算资源，可以有两个方法。
* 指定默认计算调度器的线程数。这个现场数默认为CPU核数。可以这么设置：
~~~cpp
#include "workflow/WFGlobal.h"
int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.compute_threads = 10;
    WORKFLOW_library_init(&settings);
    ...
}
~~~
* 也可以自己创建执行器和执行队列，在自己的执行器上创建计算任务。可以参考这个issue：https://github.com/sogou/workflow/issues/1076

第二个问题，关于调度策略。我们每一个计算任务都有一个计算队列名，用户可以用这个名字指导调度。在FAQ里有一些说明。一般来讲，只需给每一种计算任务起一个独立的名字就可以很好的指导调度。原理可以参考知乎这个文章：https://zhuanlan.zhihu.com/p/518265010

**Comment by chloro-pn** [comment]
明白了感谢。
