### ISSUE TITLE
使用kafka示例程序报URI Scheme InvalidFailed

### ISSUE THREAD

**Issue by taazzj** [sogou/workflow#1296]
使用GitHub上的kafka示例客户端，填写url为kafka://172.16.10.137:9092，workflow_test1、workflow_test2这两个topic都已经手动创建好，执行kafka客户端程序，报错信息为 error msg: URI Scheme InvalidFailed. Press Ctrl-C to exit.
kafka版本为2.8.1

**Comment by Barenboim** [comment]
你好。这么写没有什么问题啊。你试一下这个例子可以运行么：
https://github.com/sogou/workflow/issues/1160
我们在tutorial里也有kafka的例子，你可以make KAFKA=y编出来试一下。

**Comment by Barenboim** [comment]
我们的tutorial例子里的程序，运行没什么问题。你的kafka有认证信息吗？

**Comment by Barenboim** [comment]
> > 我们的tutorial例子里的程序，运行没什么问题。你的kafka有认证信息吗？
> 
> 我使用nossl版本连接kafka失败，使用master连接成功了，我的kafka没有设置验证信息，使用kafka必须使用master版本吗，如果是这样希望在nossl分支说明一下不能使用kafka

按理nossl版本是可以用kafka的，我们的kafka不支持ssl所以代码应该没区别。我一会看看是什么问题。

**Comment by Barenboim** [comment]
你好。我们试了nossl分支，没有问题。可能是你机器上安装过master的workflow导致头文件不匹配引起？
