### ISSUE TITLE
MySQL protocol

### ISSUE THREAD

**Issue by ineffable-yp** [sogou/workflow#1298]
if I can use postgresql to replace mysql, is the workload large? or I can use use current version code to support postgresql ? thanks all

**Comment by Barenboim** [comment]
You have to implement Postgres server-client protocol to support Postgres client. Though the Postgres protocol is much simpler than MySQL. You may have  a look at this: https://github.com/sogou/workflow/issues/766#issuecomment-1050390099

**Comment by Barenboim** [comment]
@ineffable-yp
