### ISSUE TITLE
线程模型是  线程池，还是 m:n ？当阻塞的时候会自动做线程切换么？

### ISSUE THREAD

**Issue by zhaojinzhou** [sogou/workflow#1300]

**Comment by Barenboim** [comment]
你好！目前我们的任务都是普通线程，所以最佳的使用方式是永不阻塞。虽然我们有WaitGroup可以在通信任务的callback里使用，但这么用并非高效。
正好的最近在思考一种协程任务，就是你说的模式，M个协程运行在N个线程上，然后使用方式与目前的计算任务类似（运行在另外一个线程池），但在协程任务里，可以调用一系列同步等待操作，例如：
~~~cpp
voiod f()   // 协程任务的函数
{
    WFChannel channel;
    auto *task = WFTaskFactory::create_http_task(..., [&channel](WFHttpTask *task) { channel << *task->get_resp(); });
    task->start();

    protocol::HttpResponse resp;
    resp << channel;    // 协程里同步等待
}
~~~
这样，就可以很好的实现计算任务中等待网络通信的结果了。目前我们普通的计算任务是不能这么操作的。

**Comment by Barenboim** [comment]
有另外一个workflow的相关项目也是支持协程的，不过是C++20的协程：https://github.com/kedixa/coke

**Comment by Barenboim** [comment]
有一个workflow协程化的项目，不过是用C++20的协程：https://github.com/kedixa/coke
