### ISSUE TITLE
Why can a pointer of type ExecSessionEntry* be passed to __thrdpool_schedule() ?

### ISSUE THREAD

**Issue by zhihuacc** [sogou/workflow#1302]
I found [here](https://github.com/sogou/workflow/blob/master/src/kernel/Executor.cc#L92) a pointer of type ExecSessionEntry* is passed to __thrdpool_schedule(), in [which](https://github.com/sogou/workflow/blob/master/src/kernel/thrdpool.c#L187) the pointer will be cast to type of __thrdpool_task_entry*. I don't see why this can be done, because the two structs are not compatible to each other in memory layout,  right ?

`
void __thrdpool_schedule(const struct thrdpool_task *task, void *buf, thrdpool_t *pool)
{
	((struct __thrdpool_task_entry *)buf)->task = *task;
	msgqueue_put(buf, pool->msgqueue);
}
`

**Comment by Barenboim** [comment]
The internal function `__thrdpool_schedule` accepts a buffer as the first argument, and will use the buffer (at least 3 times pointer size) to store the thread task's routine and context.
In the function `executor_thread_routine`, an `entry` of `ExecSessionEntry*` type is taken from the `session_list` and ready to been free. The size of `entry` is large enough and we make use of it as `__thrdpool_schedule` 's buffer.

**Comment by zhihuacc** [comment]
So you just discard the info in the passed buf and reuse it to avoid unnecessary memory dealloc and alloc ?

**Comment by Barenboim** [comment]
Yes. Besides reusing memory, it is hard to deal with failure in that function, and __thrdpool_schedule never fails.

**Comment by yockie** [comment]
@Barenboim Is the safer way to add static_assert here? eg:
static_assert(sizeof(struct ExecSessionEntry) >= sizeof(struct __thrdpool_task_entry));
