### ISSUE TITLE
What's the order btw process() and callback() if multiple tasks in the same series ?

### ISSUE THREAD

**Issue by zhihuacc** [sogou/workflow#1303]
In this [article](https://zhuanlan.zhihu.com/p/388958241), specifically in the second to last paragraph 

> 而server的回复时机，并不是process函数的结束，而是在server任务所在的series已经没有任务的时候

, it's mentioned that the server task will only reply after all the tasks in the series are processed. Here I think it means the server task's callback will be called after all the other tasks in the series are processed. Do I understand it right ? 

More generally, can I say if a task A adds a task B in the same series when it's being processed (the A.process() is called), in turn, the task B adds a task C in the same series when B.process() is called, then the order of function calls will be A.process()->B.process()->C.process()->C.callback()->B.callback()->A.callback() ? Or it's A.process()->A.callback()->B.process()->B.callback()->C.process()->C.callback() ?

**Comment by Barenboim** [comment]
The `process` function is specific for the server and it's called only once for each a client request. An http (or any other protocol) client task has a `callback` function which is called after the http interaction is complete. The actual sequence of function calls would be A.process()->B.callback()->C.callback()->A.callback()->series.callback(), where A is the server task, B, C can be any other tasks. Server task can has a callback as well, and it's called after the reply is sent, also means the http interaction is complete.

**Comment by zhihuacc** [comment]
So can I say different types of tasks have different timing of callbacks being called ? 

E.g., as you said, ServerTask's callback is called after all tasks in the series are finished. 

However, for ThreadTask, I know there is an interface `execute()` for each WFThreadTask inherited from `ExecSession`. And this interface is designed to do real job of the task, e.g., sorting for WFSortTask. According to logic [here](https://github.com/sogou/workflow/blob/master/src/kernel/Executor.cc#L98), the `execute()` is called. just before the callback(). If the A,  B, C tasks are WThreadTasks, then the order would be A.execute()->A.callback()->B.execute()->B.callback()->C.execute()->C.callback() ?

If different types of tasks have different timing of calling callbacks, then do you have some docs where summarise the information ?

**Comment by Barenboim** [comment]
1、The timing of callback of any kind of task is **consistent**. It's called after the task is finished! The server task's callback is called after the reply is sent, also means the server task is finished. Server task **replies** after all tasks in the series are finished, not **callback**! Callback is after reply. 
2、Correct.
3、The logic of our tasking system is not that complicated. You may run some of the tutorial codes and will easily understand.

**Comment by zhihuacc** [comment]
Thanks for more clarification. Maybe I can rephrase my point 1) and 2). What I mean is: 

for server task, its callback is called after all tasks in the series are finished (their callbacks are called), 

in contrast, for thread task, the call back is called immediately after the current task is finished (i.e., its execute() is called), then the remaining tasks in the series are scheduled to run.  Do I understand it right ?

Sure I'll checkout the logic of server task in code to understand more. Thanks again.

**Comment by Barenboim** [comment]
Well. Again, an http server task (as well as a http client task), it's callback is called after the http interaction is complete, which means the http response is sent (written to tcp buf).
For server task, it replies when all the tasks in the series are finished (again **reply**, not **callback**). You may consider server task's **reply** corresponds to WFThreadTask's **execute**, and after **reply**, the server task's **callback** is called and you may obtain the **state** and **error** code.
The **process** function is a function of the server, not a behavior of the server task.

**Comment by Barenboim** [comment]
@zhihuacc
