### ISSUE TITLE
关于计算任务的多线程

### ISSUE THREAD

**Issue by lazyman1992** [sogou/workflow#1304]
在一个server的process函数中进行复杂计算，想使用多线程进行计算
void process(){
    for(int i=0;i<ccount;i++){
         执行单步计算
    }
}和
void process(){
    for(int i=0;i<ccount;i++){
         使用go_task执行单步计算
    }
}
上述两种方式实测第一种反而比第二种写法快一倍左右，不知道是不是我的理解写法有问题，请指教

**Comment by Barenboim** [comment]
我不知道你这个是怎么个具体实现。能不能贴一下代码。我需要知道你是怎么等待计算任务结束的。

**Comment by lazyman1992** [comment]
void linksloss_resp(std::string strParam,HttpResp *resp){
    
    Json links = Json::parse(strParam);
    Json::Array results;
    for(int i=0;i<links.size();i++){

        Json result;
        Json paramJson = links[i];
 
       //直接计算
        // DiffLinkLoss *lk = new DiffLinkLoss(i);
        // if(lk->init(vecDisInfo, vecElevInfo, freq, ht, hr)){
        //     lk->crun();
        //     result["loss"] = lk->jisuan1;
        //     results.push_back(result);
        // } else {
            
        
        // }
        // delete lk;

       //使用go_task计算
        WFFacilities::WaitGroup gotask_wait_group(1);
        std::vector<double> vec_results;
        bool isOK=false;

        std::string queue_name = "linkloss_compute" + std::to_string(i);
        WFGoTask *task = WFTaskFactory::create_go_task(queue_name, linkloss_compute, vecDisInfo, 
                                                        vecDisInfo,freq,ht,hr, std::ref(vec_results),std::ref(isOK));
        task->set_callback([&](WFGoTask *task) {
            //printf("%f\n", vec_results.at(0));
            if(isOK){
                result["loss"] = vec_results.at(0);
            
            }else{
                result["loss"] = -100;
            }
            results.push_back(result);
            gotask_wait_group.done();

        });
        task->start();
        gotask_wait_group.wait();
        
    }
    resp->Json(results);
}

这个是请求的处理函数

**Comment by lazyman1992** [comment]
我在主函数中是使用了计算型handler的
    svr.POST("/linksloss", 2, [](const HttpReq *req, HttpResp *resp)
    {
        if (req->content_type() != APPLICATION_JSON)
        {
            resp->String("NOT APPLICATION_JSON");
            return;
        }

        std::string& body = req->body();
        //linkloss_resp(body, resp);   
        resp->Compute(2,linksloss_resp,body,resp);
        
    });
这样就不需要在linkloss_resp函数中再进行多线程的计算了是么？

**Comment by Barenboim** [comment]
计算型handler本来就是一个计算任务了，不用再创建go task，也不用再调用resp->Compute()，这个函数也是启动一个计算任务。你的代码相当于启动了三次计算任务……
wfrest里，使用计算任务有三种方法，1、计算型handler，就是带数字的那个。2、resp->Compute()。3、Series handler里自己创建任务并push back。

**Comment by Barenboim** [comment]
另外，你代码里使用waitgroup在一个计算任务里等待，这是一个严重的错误，会导致计算线程被占用。

**Comment by lazyman1992** [comment]
明白了感谢您的回答
