### ISSUE TITLE
window上运行的问题

### ISSUE THREAD

**Issue by zZQI** [sogou/workflow#1306]
求助，下载了windows分支的代码并且手动编译了，想链接到qt中使用下，结果总是出问题，
![image](https://github.com/sogou/workflow/assets/40666801/d0172cc5-b2c1-4a32-bace-2ad1ea0b97e0)
这是cmakelist文件，是不是哪里写错了，
![image](https://github.com/sogou/workflow/assets/40666801/0e7d02e8-e220-4f2f-a455-ba8cce45c485)
库文件也都拷贝到编译目录下了
![image](https://github.com/sogou/workflow/assets/40666801/da44b6ba-dace-4a9b-bcb2-7cacf8121738)
![image](https://github.com/sogou/workflow/assets/40666801/6b7e265d-cba1-464a-9600-61b8eba582b6)
linux就能正常使用，windows就各种奇奇怪怪的问题

**Comment by Barenboim** [comment]
你好。在不使用qt的情况下跑通过吗？

**Comment by zZQI** [comment]
这个编译器有关吗，qt用的mingw编译项目，但这个workflow的库是用vs编译的，还有，vcpkg下载的也是出问题，而且库的大小和我手动编译出来的不一样，这啥情况

**Comment by Barenboim** [comment]
> 这个编译器有关吗，qt用的mingw编译项目，但这个workflow的库是用vs编译的，还有，vcpkg下载的也是出问题，而且库的大小和我手动编译出来的不一样，这啥情况

Windows下的编译我真的是完全不敢。不过tutorial一运行就闪退很奇怪啊，没听说过有遇到这个问题的。要不群里问问？

**Comment by zZQI** [comment]
你们windows上用都正常的吗，

**Comment by Barenboim** [comment]
我们自己没有windows需求，但群里很多windows用户。用户量不少。

**Comment by zZQI** [comment]
windows编程真的是一言难尽，

**Comment by Barenboim** [comment]
> windows编程真的是一言难尽，

实在不好意思，我们这边都是搞后端的，没有使用windows的需求。Windows的编译现在只能群里互相帮忙一下……我们肯定没你们懂。

**Comment by Barenboim** [comment]
这个issue先关了。群里解决。
