### ISSUE TITLE
关于客户端超时的问题

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1309]
程序全局设置了超时10秒
`    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.response_timeout = 10*1000;
    WORKFLOW_library_init(&settings);`
程序里面的客户端WFNetworkTask设置了超时15秒
`    WFCustomTask *task = WFNetworkTaskFactory<CustomRequest, CustomResponse>::create_client_task(
                            m_isSSL ? TT_TCP_SSL : TT_TCP, m_host, m_port, 0, std::bind(&CTcpClient::process, this, _1));
    task->set_receive_timeout(15*1000); `
为什么WFNetworkTask 10秒就提示超时了？不应该是15秒超时吗？

**Comment by Barenboim** [comment]
这两个timeout意义不一样。
response_timeout是全局（或upstream）级别配置，代码每读取到或发送出任何一块数据的超时。
receive_timeout是任务级参数参数，代码读完整个消息的超时。
如果你10秒就超时了，说明是10秒内没有收到任何数据。
