### ISSUE TITLE
mysql的url中带#会报错

### ISSUE THREAD

**Issue by Jie-Xio** [sogou/workflow#1310]
我要连接的Mysql的密码中带#， 任务状态返回 URI Parse Failed
我的url是这样的： mysql://root:asdfghjkl#hh@192.168.1.18:3306/nvr

版本：workflow 0.10.7

**Comment by Barenboim** [comment]
你好。密码里特殊字符需要用StringUtil::url_encode_conponent进行转义的。可以参考这个issue：https://github.com/sogou/workflow/issues/537

**Comment by Jie-Xio** [comment]
@Barenboim  
谢谢！改成下面这样就不报错了
std::string url = "mysql://root:" + StringUtil::url_encode_component("asdfghjkl#hh") + "@192.168.1.18:3306/nvr";
