### ISSUE TITLE
client怎么以同步的方式发送http请求,等待返回？

### ISSUE THREAD

**Issue by bayueqiankong** [sogou/workflow#1311]
workflow中，client怎么以同步的方式发送http请求（post/get）,（阻塞）等待结果返回？

**Comment by Barenboim** [comment]
client无法同步发送请求，只有server可以同步回复请求（SSE模式）。

**Comment by Barenboim** [comment]
不知道我对你的问题理解得对不对。是否是想要实现client从文件里读出一块就发送一块POST的内容。

**Comment by bayueqiankong** [comment]
> 不知道我对你的问题理解得对不对。是否是想要实现client从文件里读出一块就发送一块POST的内容。
是的

**Comment by Barenboim** [comment]
> 不知道我对你的问题理解得对不对。是否是想要实现client从文件里读出一块就发送一块POST的内容。
> 是的

这块确实目前没有办法，你只能用最底层的poller模块实现这个功能，做起来也比较麻烦。在这个问题上，我们和brpc是一样的，server可以一块一块回复，但client没办法。
