### ISSUE TITLE
workflow服务器tls装填除cert file以及key file以外的ssl_ctx该如何处理

### ISSUE THREAD

**Issue by MasterL-min** [sogou/workflow#1313]
需要给服务器装填一个DH参数，
// Set the DH parameters in the SSL context
SSL_CTX_set_tmp_dh(ctx, dhParams);
在生成ctx后，我该如何把我生成的这个ctx装填进我要运行的服务器中？（假设我创建了HttpServer svr;）
我尝试使用svr.set(ctx,2500);显示'set_ssl' is a protected member of 'CommService'
我阅读了WFServer.cc代码只找到了SSL_CTX *WFServerBase::new_ssl_ctx(const char *cert_file, const char *key_file)，
然后服务器在init中将cert file及key file用this->set_ssl()实现了。
好像没有对其他的实现，我生成的dh文件为dhparam.pem.

**Comment by Barenboim** [comment]
对，只能派生重写new_ssl_ctx函数。可以看一下这个issue：https://github.com/sogou/workflow/issues/1121

**Comment by MasterL-min** [comment]
> 对，只能派生重写new_ssl_ctx函数。可以看一下这个issue：#1121

我看了这个issue，我跟这个作者最初自己的改动很像直接从WFServer.c和WFServer.h里进行了改动，目前运行成功。
我跟那个issue里相对不一样的是我需要把dhparam.pem跟server.crt还有server.key一起都读入ssl_ctx里然后让服务器启动，所以我感觉我这样改需要改的地方特别多，相当于svr.start(8888, argv[1], argv[2], "./cert/dhparam.pem")比之前额外多了一个参数，
然后对应的就得在WFServer.c里面把所有的比如start,serve,init,new_ssl_ctx，包括WFServer.h里需要加入这个额外参数的地方都进行了改动，改成类似这样，
`SSL_CTX *WFServerBase::new_ssl_ctx(const char *cert_file, const char *key_file, const char *DH_file)`
```
int WFServerBase::init(const struct sockaddr *bind_addr, socklen_t addrlen,
					   const char *cert_file, const char *key_file, const char *DH_file)
```
```
int WFServerBase::start(const struct sockaddr *bind_addr, socklen_t addrlen,
						const char *cert_file, const char *key_file, const char *DH_file)
```
```
int WFServerBase::serve(int listen_fd,
						const char *cert_file, const char *key_file, const char *DH_file)
```
WFServer.h里也是因为额外加了一个参数，类似这样全部做了对应更改
```
	int start(unsigned short port, const char *cert_file, const char *key_file, const char *DH_file)
	{
		return start(AF_INET, NULL, port, cert_file, key_file, DH_file);
	}
```
我不太懂是不是还有更好的办法，我看那个issue里推荐直接派生server的new_ssl_ctx方法，但是我感觉我这样在派生new_ssl_ctx时需要多加入一个参数，而这个new_ssl_ctx又得init去调用，也就是init也需要知道我运行中多加入了这个参数，好像单纯派生一个也没用，所以请教下不知道是否有更好的方法，如果没有的话我就这样更改就结束了，目前运行正常。

**Comment by Barenboim** [comment]
你都派生了，参数不是随便传吗？当然就是用你派生的MyHttpServer的接口了，新的成员也放在派生类里。

**Comment by MasterL-min** [comment]
> 你都派生了，参数不是随便传吗？当然就是用你派生的MyHttpServer的接口了，新的成员也放在派生类里。

好的，谢谢，抱歉问了这样一个不太好的问题。

**Comment by Barenboim** [comment]
没关系哈。任何问题随便问。

**Comment by Barenboim** [comment]
start接口可以不用改，用现在的start就可以。
