### ISSUE TITLE
websocket task超时问题

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1314]
在样例中，有这么一段代码
auto *task = client.create_websocket_task([&wg, &client] (WFWebSocketTask *task)
	{
		fprintf(stderr, "send callback() state=%d error=%d\n",
				task->get_state(), task->get_error());

		if (task->get_state() != WFT_STATE_SUCCESS)
		{
			wg.done();
			return;
		}
		auto *ping_task = client.create_ping_task(nullptr);
		auto *timer_task = WFTaskFactory::create_timer_task(3000000 /* 3s */, nullptr);
		auto *close_task = client.create_close_task([&wg] (WFWebSocketTask *task) {
			wg.done();
		});

		series_of(task)->push_back(ping_task);
		series_of(task)->push_back(timer_task);
		series_of(task)->push_back(close_task);
	});

	WebSocketFrame *msg = task->get_msg();
	msg->set_text_data("This is Workflow websocket client.");
	task->start();

如果task->start(),执行时间过长，超过30S了，我该如何设置这个超时时间，当超时的时候需要state为失败吧

**Comment by holmes1412** [comment]
你好，我在参数里增加了一个send_timeout，用法如下：
```cpp
    WFWebSocketTask *task = client.create_websocket_task(process); 
    task->set_send_timeout(30 * 1000); // 单位：毫秒
```

但一般来说写还是很快的，基本不太需要这个值。

等这个PR:https://github.com/sogou/workflow/pull/1315 合并了之后你就可以用了，或者可以先拉我的fork试一下，谢谢。

**Comment by Detxie** [comment]
> 你好，我在参数里增加了一个send_timeout，用法如下：
> 
> ```c++
>     WFWebSocketTask *task = client.create_websocket_task(process); 
>     task->set_send_timeout(30 * 1000); // 单位：毫秒
> ```
> 
> 但一般来说写还是很快的，基本不太需要这个值。
> 
> 等这个PR:#1315 合并了之后你就可以用了，或者可以先拉我的fork试一下，谢谢。

如果超时的话，task->get_state()可以判断么，还是当前连接直接不创建。

**Comment by holmes1412** [comment]
可以通过task->get_state()等于WFT_STATE_SYS_ERROR和task->get
_error()等于ETIMEOUT判断是否是超时～

**Comment by Detxie** [comment]
> 可以通过task->get_state()等于WFT_STATE_SYS_ERROR和task->get _error()等于ETIMEOUT判断是否是超时～
多谢解答~~
