### ISSUE TITLE
修改max_connections为2000，还需不需要设置操作系统的进程fd最大限制（setrlimit 或/etc/security/limits.conf）

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1317]

**Comment by Barenboim** [comment]
系统的限制我们不会动的。能开多少连接，肯定受到最大文件描述字的限制。
最好是启动进程脚本里就把参数设置好，不要启动后再去调setrlimit

**Comment by coderwxl** [comment]
还有个问题，高并发情况下，为什么handler线程如果比较耗时，就会出现大量的CLOSE_WAIT，然后服务就卡死无响应了

**Comment by Barenboim** [comment]
卡死不会吧。你是不是在handler里等待了？
如果handler不够用，来不及处理对方的连接关闭，确实会有CLOSE_WAIT没处理的问题。但按你说的情况，可能是你在handler里同步等待网络任务的完成，引起了死锁。如果handler里需要等待，只能用我们的wait_group或WFFuture，不能用std::future或pthread condition。
最好的用法，是全异步，不要用等待的方式。
