### ISSUE TITLE
如何根据用户配置去限制server的qps

### ISSUE THREAD

**Issue by MaybeShewill-CV** [sogou/workflow#1319]
想咨询下如何可以实现在服务启动的时候按照用户配置去限制server的qps，对于超出qps能力范围的请求是否可以做到不直接拒绝而是按顺序等候server对它们进行处理?

**Comment by Barenboim** [comment]
qps可能也可能用resource pool，或至少也能用WFConditional来做。比如通过一个timer定期向资源池里放入资源，用户用完也不用post了，资源的放回都由timer去管理。其实这也是一个很有意思的问题。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 感谢大佬回复。
1.我想了下如果我的server端的process函数执行的业务逻辑耗时是恒定的，那么控制了并发度是不是就是变向控制了每秒我的server能处理的总请求数量，如果是这样的话其实我控制并发目前也可以达到我的目的。
2.针对定时任务，如果server端自己维护两个任务队列，一个任务队列A用来承接所有的用户请求，另一个队列B按照qps限额来存放实际待执行的任务，然后wf启动一个定时任务每秒都从A队列搬运qps - len(b) 的任务到B队列。这样是不是能实现限制qps的目的。但这样实现的话任务一旦接收到，不管客户端是不是还在等待server都得去处理这个任务，好像有点不智能，不知道有没有什么好的解决方案。

**Comment by Barenboim** [comment]
你的第一个问题是不是通过resource pool就可以解决了？第二个问题里，你有提到定时任务，是不是纯粹是对qps控制的讨论呢？这个我下午想想能不能抽象出一个组件出来，但感觉应用场景不多啊，大多数情况还是资源池模式。就是说你的计算资源是有限的，任务获得资源才能被执行。这个和控制并发度是一个道理，只是每次运行时，可以的道一个void *类型的资源。
至于客户端还在不在等待的问题，是不是就是说如果连接被关闭了，就不再执行任务？连接关闭时间你是可以捕获的啊，例如：
~~~cpp
void process(WFHttpTask *task)
{
    task->get_connectiton()->set_context(NULL, [](void *){printf("connection closed\n");});
}
~~~
你只能在process函数内部设置连接上下文。这个文档里也有。
不过，看起来好像不是太方便，我看看能不能直接加个接口，让用户知道连接还在不在。

**Comment by MaybeShewill-CV** [comment]
@Barenboim Thanks
1.第一个问题通过资源池我觉得应该就可以解决了。
2.原来可以这样获取连接是否被关闭了啊，学到了。

目前看资源池应该就可以满足我现在的需求了：）

**Comment by Barenboim** [comment]
@MaybeShewill-CV 
你看一下这个新接口：https://github.com/sogou/workflow/pull/1322 ，应该可以满足你的需求。任何时候决定要不要继续，可以task->close() 检查一下连接状态。如果task不是一个需要回复的server task，closed()调用也是有意义的，返回值代表任务是否已经完结。
