### ISSUE TITLE
发送post请求崩溃

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1320]
![image](https://github.com/sogou/workflow/assets/57793691/21648fb1-8a05-4d96-8a6a-1033f0076f61)
代码是参考tutorial-01-wget.cc写的

**Comment by Barenboim** [comment]
你调get_parsed_body，size是不是传了个nullptr？

**Comment by coderwxl** [comment]
解决了，通过HttpChunkCursor方式获取数据就行了

**Comment by Barenboim** [comment]
get_parsed_body应该也是正常的才对啊。你原来代码是怎么写的？
