### ISSUE TITLE
程序卡住，如何排查一下.

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1324]
现象：
1、起了一个服务，目前程序无法访问(实现了http接口，调不通-curl请求卡住)
2、netstat看了一下出现了大量的close_wait状态
3、看了之前的issues，可能和handle线程有关？
4、在主要的代码中，使用了一个create_go_task的异步任务来处理一个request请求。在create_go_task传入了callback，callback中使用了create_http_task来发送一个http请求，同步操作使用的WFFcilities::WaitGroup,同步完成后callback退出。

我应该如何继续排查呢？能提供一下思路么

**Comment by holmes1412** [comment]
callback里不要使用waitgroup哈，否则会卡住handler线程。你把http task串到当前的series之后就可以了

**Comment by Detxie** [comment]
是改成这样么

void callback(*go_task){
 http_task = create_http_task() ;
 series_of(go_task)->push_back(http_task);
}

这样的话http_task里面怎么做同步呢，htpp_task->start()不就直接退出了，并没有等待server回复消息

**Comment by Barenboim** [comment]
计算任务的计算函数和callback里，千万不要用wait group等待！这个直接让计算线程陷入阻塞。

**Comment by holmes1412** [comment]
你是server么？如果你想要http请求回来之后再让server回复，整个任务流应该这样：

```cpp
void process(WFHttpTask *server_task) // 假设你是http server
{
    auto *go_task = WFTaskFactory::create_go_task();
    series_of(server_task)->push_back(go_task);
}

void go_task_callback(WFGoTask *go_task)
{
    auto *http_task = WFTaskFactory::create_http_task();
    series_of(go_task)->push_back(http_task);
}
```
如果你有上下文传递需求可以参考一下文档：https://github.com/sogou/workflow/blob/master/docs/tutorial-05-http_proxy.md

**Comment by Barenboim** [comment]
> 是改成这样么
> 
> void callback(*go_task){ http_task = create_http_task() ; series_of(go_task)->push_back(http_task); }
> 
> 这样的话http_task里面怎么做同步呢，htpp_task->start()不就直接退出了，并没有等待server回复消息

你之前在process里也用wait group等待了？

**Comment by Detxie** [comment]
@holmes1412 
目前情况就是程序卡住，还没有找到最开始的卡住原因。因为现象很多，可能是A卡住了，导致B被卡住了....... 无法确定是谁造成的。
1.netstata - a 查看连接，会有一个tcp的连接。这个tcp连接为使用了workflow-websocket作为客户端，与Go的server进行通信。此时Recv-Q显示存在大量的数据未被消费，多次netstat -a , 发现Recv-Q并不会变化了。那感觉上就是websocket.client的process卡住了？
2.现在handle和poller设置大小都为6，以handle为例，这个我可以理解为创建一个线程池，大小为6，如果6个线程都被阻塞，那么就不会再创建新的线程出来。关于这个我可以通过什么方式查看当前handle或者poller线程的状态么。
3.又看了一下websocket_cli.md，有几个疑问。
  `1. 与Workflow原有用法的差异
   由于WebSocket协议是Workflow中首个实现的双工通信协议，因此有些差异是必须强调的：

   WebSocket协议的收发都是使用poller线程，因此websocket_cli用户需要把poller线程数改大点，同理可以把handler线程数改 
   小。参考：[about-config.md](https://github.com/sogou/workflow/blob/websocket/docs/about-config.md)
   process函数中所有的消息都是由同一个线程串行执行的；
   回调函数callback的执行不一定在同一个线程；`

我在about-config.md文档中看到有个介绍,poller线程主要负责epoll(kqueue)和消息的反序列化。handle线程是网络任务callback和process所在线程。
这个websocket.client中的Process在被执行时是poller线程?

**Comment by Detxie** [comment]
> 

poller线程对于websocket.client来说是不是把server->网卡->内核中的数据取出来，然后响应process方法。

**Comment by holmes1412** [comment]
1. 查看连接状态如果感觉是websocket卡住，可以检查一下process和callback里，不要有wait_group或者等锁或者sleep等阻塞行为；
2. 如何查看进程状态可以执行`gstack 进程号`看看程序每个线程都在干嘛；
3. 是的，在poller线程中进行处理的；

**Comment by Detxie** [comment]
大致伪代码: 下面这些逻辑是wfrest基于Route路由匹配后进入的一个接口。svr.Post("xx",interface)

p;  //一个处理类
http_callback(){
  http_task = create_http_task();
}
p.handle(){
  task = create_go_task(http_callback); 
}
my_callback(p，data) //处理websocket的数据。P会对数据进行处理，并响应注册的回调

ws_client = client(my_callback) //这里对websocket-client进行了封装，注册了这个my_callback
ws_client_process(WFWebSocketTask  *task){
  ws_client.my_callback(data)
}

我描述的可能有些混乱，以server发送数据为源头，流程大概就是
1.websocket-client.process接收到数据
2.在proccess中调用初始化client时注册的my_callback。
3.在my_callback中会把数据拷贝给事先创建的P类。此时my_callback方法退出。websocket-client.process也结束。
4.在处理P类的线程里面，此时收到数据，响应一次p.handle方法，handle中创建go_task异步任务，并将数据拷贝到http_callback，然后handle结束，此时go_task.start()也退出。
5.最后在http_callback中处理数据，并发送request。退出。

**Comment by holmes1412** [comment]
有个地方还没有太明白哈：P的处理线程是你创建的么？

如果说P要做的事情就是做go_task和http_task，感觉更好的方式是在my_callback里create_go_task并放到当前websocket的任务所在的任务流后面，由于go task是计算线程，因此websocket-client.process在把go task交给计算线程之后这个poller线程就可以继续收下一份数据了。

然后你go task处理完还要创建http task并发送request，这些都是不变的，是在handler线程做的。

按你的代码大概这样：
```cpp
XXX ws_client = client(my_callback);

void ws_client_process(WFWebSocketTask *task) {
    ws_client.my_callback(data, task);
}

// 等同于上面的p.handle()，在这里创建一个go任务并且设置它的callback，然后串到websocket task后面
void my_callback(DATA *data, WFWebSocketTask *task) {
    auto *go_task = WFTaskFactory::create_go_task(...);
    go_task->set_callback(go_callback);
    series_of(task)->push_back(go_task);
} 

// 等同于上面的http_callback，是go task的回调函数
void go_callback(WFGoTask *task) {
    auto *http_task = create_http_task();
    series_of(task)->push_back(http_task);
}
```

**Comment by Detxie** [comment]
> 

这个P类和P的处理线程是其他同事开发的SDK中的。。必须经过它，基于这种情况，我必须做两件事
1.将数据copy给P。
2.当P处理完逻辑时会响应我注册给它的回调，这个回调里面go_task .... http_task

所以整个流程也可以分成两部分。
(1)ws-client.process->my_callabck() - >拷贝给P(此时是poller)
(2)P中响应我注册时的callback，这个callaback里面就是起go_task和http_task。(handle)
看之前的堆栈信息是卡在(1)的部分，这么看是poller线程。

我正在复现这个问题，并尝试用pstack排查一下。

我还有个疑惑，请教一下。如果我设置了4个poller线程，我有10条ws-client ----ws-server连接
当1个线程阻塞住时，是不是剩余的3个poller线程处理剩余的9个连接，还是说3个线程处理剩余的10个连接。
这个poller线程卡住，是只影响某个ws连接的这一次回调。还是把整个ws连接影响了？

**Comment by holmes1412** [comment]
了解了，如果可以尽量简化模型来复现问题就比较好排查，我们也方便一起复现一下。

如果堆栈卡在(1)，可以看看都卡在哪个函数。

后面的问题：连接建立好之后就是固定某个线程负责了，所以如果一个poller线程卡住，那么会影响它所负责的1/4的连接。

**Comment by Detxie** [comment]
问一下几个疑问。
1.HttpServer svr;起 server服务时，负责路由匹配这个时handle线程负责的吧？看HttpServer.h里面ROUTE会传入handle。
2.create_http_task是handle还是poller？
这个我可以从哪里区分是poller还是handle,有个文档指路么。WFTaskFactory还是WFGlobal获取scheduler的时候

**Comment by holmes1412** [comment]
1. 是的
2. create和start task本身是个很快的操作，当前在哪个线程就是哪个线程。

一般可以参考config文档：https://github.com/sogou/workflow/blob/master/docs/about-config.md

比如这段：

与网络性能相关的两个参数为poller_threads和handler_threads：

- poller线程主要负责epoll（kqueue）和消息反序列化。
- handler线程是网络任务callback和process所在线程。
