### ISSUE TITLE
HTTPS Client 证书问题

### ISSUE THREAD

**Issue by liuyatao** [sogou/workflow#1325]
# 过程

1.  使用`start`方法启动了一个https服务(使用自签名证书)
2. 使用curl 调用 https服务需要通过`--cacert`指定自签名证书请求https服务结果(符合预期)
3. 编译[tutorial-01-wget.cc](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-01-wget.cc)，用该程序请求https服务，没有设置自签名证书，结果竟然也请求成功了（不符合预期）

# 疑问

为什么不设置自签名证书也可以访问？是不进行证书校验吗？

**Comment by Barenboim** [comment]
~~~cpp
#include <workflow/WFGlobal.h>
int main()
{
    SSL_CTX *ssl_ctx  WFGlobal::get_ssl_client_ctx();
    // 然后随便设置需要的证书
}
~~~

**Comment by liuyatao** [comment]
> ```c++
> #include <workflow/WFGlobal.h>
> int main()
> {
>     SSL_CTX *ssl_ctx = WFGlobal::get_ssl_client_ctx();
>     // 然后随便设置需要的证书
> }
> ```

@Barenboim  但是为什么不设置证书竟然可以访问成功呢？

**Comment by Barenboim** [comment]
本来就不用设置证书啊。你直接抓去任何网站都可以成功。证书是需要双向认证才需要。
记得star项目哈。

**Comment by liuyatao** [comment]
@Barenboim  但是为什么[tutorial-01-wget.cc](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-01-wget.cc) 可以不设置证书就能访问成功呢？ 是默认比校验证书？在源码中也没有看到这些信息

**Comment by liuyatao** [comment]
@Barenboim  我是设置的自定义证书起的https服务，使用curl调用需要添加信任正式才可以，浏览器就提示不安全的证书，为什么[tutorial-01-wget.cc](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-01-wget.cc)不需要信任自定义证书就能访问？

**Comment by Barenboim** [comment]
SSL默认不设置，就只有加密，没有认证啊。认证需要加verify。这个本来就是这样的。https抓取，没有必要加证书。curl和浏览器不能访问，是因为认证server失败（不是信任机构的证书）。你可以跳过server认证成功抓取。
双向认证本来就不是必须的。
