### ISSUE TITLE
workflow版本:0.10.7，kafka版本:2.11-2.3.1；消费者报错errmsg:Kafka fetch api failed, state:67, syserror:5003

### ISSUE THREAD

**Issue by licj520** [sogou/workflow#1328]
1、用workflow的生产者能成功把消息发到服务器，消费者报错errmsg:Kafka fetch api failed, state:67, syserror:5003
2、使用同一套代码，消费老版本的kafka(0.8.2)，业务正常

**Comment by licj520** [comment]
个性化代码导致特殊主题名创建消息任务异常

**Comment by Barenboim** [comment]
workflow的代码也建议升级到v0.10.8 。kafka相关更新比较多。
