### ISSUE TITLE
交叉编译问题

### ISSUE THREAD

**Issue by ouclbc** [sogou/workflow#1329]
你好，请教一下
我用arm linux交叉编译链工具编译，workflow能编译过，但是tutorial编译不过：
CMake Error at CMakeLists.txt:17 (find_package):
  Could not find a package configuration file provided by "workflow" with any
  of the following names
我需要先编译一个本地版本的workflow么？然后指定？

**Comment by ouclbc** [comment]
修改CMakelist后OK
#find_package(workflow REQUIRED CONFIG HINTS ..)
set(WORKFLOW_INCLUDE_DIR   "../_include")
set(WORKFLOW_LIB_DIR   "../_lib")

**Comment by holmes1412** [comment]
你好，在编译workflow的时候，会通过`workflow-config.cmake.in`文件，生成`workflow-config.cmake`文件，并在里边指定include和lib的路径：
```
set_and_check(WORKFLOW_INCLUDE_DIR "xxx/_include")
set_and_check(WORKFLOW_LIB_DIR "xxx/_lib")
```
然后tutorial里通过`find_package(workflow REQUIRED CONFIG HINTS ..)`这句话，会自动查找到workflow-config.cmake并使用里边设置的变量，所以**按说tutorial里不再需要重新指定才对**。

不知道是不是由于交叉编译导致的一些差异？麻烦是否帮我们检查一下：
- 你编译workflow的路径下，是否有`workflow-config.cmake`这个文件？
- 这个文件里是否有上面`set_and_check`这两行，指定的位置是否是你本地正确的位置呢？

**Comment by holmes1412** [comment]
那么看起来你的环境里，虽然workflow-config.cmake正确设置了这两行，但是tutorial里通过find_package(workflow REQUIRED CONFIG HINTS ..)这句话没有通过workflow-config.cmake正确用到这两个变量。

麻烦请问一下你使用的cmake版本是什么呢？

**Comment by ouclbc** [comment]
3.16.5
