### ISSUE TITLE
自定义协议解析时如何拿到对端的IP和端口信息

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1331]
服务端解析自定义协议的append(const void *buf, size_t size)里面我需要打印对端的IP地址和端口信息，该如何做？

**Comment by Barenboim** [comment]
这个不行，消息解析和ip信息无关。
你的原始需求是什么？

**Comment by coderwxl** [comment]
服务端有时候可能会收到一些乱七八糟的数据（不是我们自定义的协议），我想知道这些数据是从哪发来的

**Comment by Barenboim** [comment]
当然，非要那也是有办法的。你的message里加一个set_peer_addr的接口，然后：
~~~cpp
template<class REQ, class RESP>
class MyServerTask : public WFServerTask<REQ, RESP>
{
protected:
    CommMessageIn *message_in() override
    {
        const struct sockaddr *addr;
        socklen_t addrlen;
        this->get_target()->get_addr(&addr, &addrlen);
        this->req.set_peer_addr(addr, addrlen);   // 这里甚至可以直接保存指针
        return &this->req;
    }
};

template<class REQ, class RESP>
WFMyServer : public WFServer<REQ, RESP>
{
private:
    CommSession *new_session(...) override
    {
        return new WFMyServerTask<REQ, RESP>;
    }
}
~~~
client想保存server地址，也可以如法炮制，派生ComplexClientTask，重写message_in()。
另外，client还有一种方法，可以不派生，直接在给task设置一个prepare函数：
~~~cpp
{
    MyTask *task = create_my_task(...);
    task->set_prepare([](MyTask *task) {
        struct sockaddr_storage addr;
        socklen_t addrlen = sizeof addr;
        // get_target是task的保护方法，prepare函数无法调用。这里只能调用get_peer_addr。
        task->get_peer_addr(&addr, &addrlen);
        task->get_resp()->set_peer_addr((const struct sockaddr *)&addr, addrlen); // 这里的addr指针是局部变量，不可以引用哦。
    });
}
~~~

**Comment by Barenboim** [comment]
> 服务端有时候可能会收到一些乱七八糟的数据（不是我们自定义的协议），我想知道这些数据是从哪发来的

如果是这个需求，直接重写WFServer的new_session就可以了。https://github.com/sogou/workflow/blob/578d60b51183265c3fe449fef8f9cc4578e9db20/src/server/WFServer.cc#L140

**Comment by coderwxl** [comment]
我参考WFServerBase::new_connection重写了new_connection：
`template<class REQ, class RESP>
WFConnection *CWFServerDerived<REQ, RESP>::new_connection(int accept_fd)
{
    struct sockaddr_in peersockaddr;
    socklen_t len = sizeof(peersockaddr);
    if (-1 == getpeername(accept_fd, (struct sockaddr*)&peersockaddr, &len)) 
        trace_log(ERR, "getpeername err: %s[%d]!", strerror(errno), errno);
    else
        trace_log(INF, "accept connect: %s:%hu", inet_ntoa(peersockaddr.sin_addr), ntohs(peersockaddr.sin_port));

	if (++this->conn_count <= this->params.max_connections ||
		this->drain(1) == 1)
	{
		int reuse = 1;
		setsockopt(accept_fd, SOL_SOCKET, SO_REUSEADDR,
				   &reuse, sizeof (int));
		return new WFServerConnection(&this->conn_count);
	}

	this->conn_count--;
	errno = EMFILE;
	return NULL;
}`
然后编译的时候报错：error: expected type-specifier before ‘WFServerConnection’，我看了下WFServerConnection是在WFServer.cc中声明定义的，其它地方没有声明，这个要怎么搞？

**Comment by Barenboim** [comment]
这么写吧：
~~~cpp
template<class REQ, class RESP>
WFConnection *CWFServerDerived<REQ, RESP>::new_connection(int accept_fd)
{
    struct sockaddr_in peersockaddr;
    socklen_t len = sizeof(peersockaddr);
    if (-1 == getpeername(accept_fd, (struct sockaddr*)&peersockaddr, &len)) 
        trace_log(ERR, "getpeername err: %s[%d]!", strerror(errno), errno);
    else
        trace_log(INF, "accept connect: %s:%hu", inet_ntoa(peersockaddr.sin_addr), ntohs(peersockaddr.sin_port));

    return this->WFServer<REQ, RESP>::new_connection(accept_fd);
}
~~~

**Comment by coderwxl** [comment]
上面set_peer_addr那个方法中WFServerTask的构造函数是`	WFServerTask(CommService *service, CommScheduler *scheduler, std::function<void (WFNetworkTask<REQ, RESP> *)>& proc)`，new task的时候第二个参数scheduler该怎么填，填NULL吗？

**Comment by Barenboim** [comment]
参考WFTaskFactory.inl里的：
~~~cpp
template<class REQ, class RESP>
WFNetworkTask<REQ, RESP> *
WFNetworkTaskFactory<REQ, RESP>::create_server_task(CommService *service,
                std::function<void (WFNetworkTask<REQ, RESP> *)>& proc)
{
    return new WFServerTask<REQ, RESP>(service, WFGlobal::get_scheduler(), proc);
}
~~~

**Comment by coderwxl** [comment]
测过了，可以，感谢大佬
