### ISSUE TITLE
SQL SERVER链接支持

### ISSUE THREAD

**Issue by BugTan** [sogou/workflow#1336]
经常需要链接SQL SERVER，可以提供该数据库的支持么？

**Comment by Barenboim** [comment]
这个现在太不主流了，也不是开源产品吧？我们连接数据库是根据公开的协议规范自己解析的，这个就实现不了。
你只能在我们框架里直接调用官方的驱动，然后和counter task结合成workflow的异步任务。没有办法使用workflow自己的通讯框架。

**Comment by Barenboim** [comment]
建议直接上MySQL！

**Comment by BugTan** [comment]
> 建议直接上MySQL！

好的，谢谢了。
