### ISSUE TITLE
看了下mysql客户端代码, 有个疑惑, 

### ISSUE THREAD

**Issue by jiangdongzi** [sogou/workflow#1337]
![image](https://github.com/sogou/workflow/assets/17529657/e40ebd93-8ecb-4953-9e69-5240360d3410)
parse_row_packet 中的decode_string没看出作用是什么, 就是为了向前移动指针么?

我看fetch_row也有decode_string
![image](https://github.com/sogou/workflow/assets/17529657/3be82fe3-13bc-475c-8dc4-584579f56fd1)
decode_string 两次? 
看的还不太深, 望指教

**Comment by holmes1412** [comment]
你好，可以看看src/protocol/mysql_byteorder.h这个文件里对`decode_string`的注释：
```c
// decode encoded length string within *end, move pos forward
int decode_string(const unsigned char **str, unsigned long long *len,
                  const unsigned char **pos, const unsigned char *end);
```
mysql协议中string的存储是length+data，其中length是变长的，这个函数是在pos到end的范围内，把变量str拿到data，变量len拿到length，pos移动到解析后的位置。

解析row的逻辑可以多参考mysql协议中一个返回结构的结构～

**Comment by Barenboim** [comment]
@jiangdongzi 麻烦star一下项目啊！

**Comment by jiangdongzi** [comment]
> 你好，可以看看src/protocol/mysql_byteorder.h这个文件里对`decode_string`的注释：
> 
> ```c
> // decode encoded length string within *end, move pos forward
> int decode_string(const unsigned char **str, unsigned long long *len,
>                   const unsigned char **pos, const unsigned char *end);
> ```
> 
> mysql协议中string的存储是length+data，其中length是变长的，这个函数是在pos到end的范围内，把变量str拿到data，变量len拿到length，pos移动到解析后的位置。
> 
> 解析row的逻辑可以多参考mysql协议中一个返回结果的结构～

parse_row_packet中cell_data, cell_len好像没有用途?

**Comment by jiangdongzi** [comment]
> @jiangdongzi 麻烦star一下项目啊！

好的

**Comment by Barenboim** [comment]
> > 你好，可以看看src/protocol/mysql_byteorder.h这个文件里对`decode_string`的注释：
> > ```c
> > // decode encoded length string within *end, move pos forward
> > int decode_string(const unsigned char **str, unsigned long long *len,
> >                   const unsigned char **pos, const unsigned char *end);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mysql协议中string的存储是length+data，其中length是变长的，这个函数是在pos到end的范围内，把变量str拿到data，变量len拿到length，pos移动到解析后的位置。
> > 解析row的逻辑可以多参考mysql协议中一个返回结果的结构～
> 
> parse_row_packet中cell_data, cell_len好像没有用途?

这个地方没有用到。消息的append的目的，是为了以最快速度判断消息的结束，这个地方只是为了跳过字符串，不会把内容保存下来。

**Comment by jiangdongzi** [comment]
> > > 你好，可以看看src/protocol/mysql_byteorder.h这个文件里对`decode_string`的注释：
> > > ```c
> > > // decode encoded length string within *end, move pos forward
> > > int decode_string(const unsigned char **str, unsigned long long *len,
> > >                   const unsigned char **pos, const unsigned char *end);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > mysql协议中string的存储是length+data，其中length是变长的，这个函数是在pos到end的范围内，把变量str拿到data，变量len拿到length，pos移动到解析后的位置。
> > > 解析row的逻辑可以多参考mysql协议中一个返回结果的结构～
> > 
> > 
> > parse_row_packet中cell_data, cell_len好像没有用途?
> 
> 这个地方没有用到。消息的append的目的，是为了以最快速度判断消息的结束，这个地方只是为了跳过字符串，不会把内容保存下来。

感觉这种成本太高了, 感觉是不是可以把部分状态保存下来节省以后的解析

**Comment by holmes1412** [comment]
这个是一个trace off：我是希望网络线程和执行线程分工明确、还是希望尽量做多点事情？

这里提供两点考虑（还可能有更多考虑点）：
- 按这个解析方式，到底有多慢，是否已经成为用户瓶颈
- 网络收回来，是不是所有东西用户都要用，要是不用，我在解析时构造好这些结果的状态不是浪费了么，至少得多花内存、还得分配吧

其实第一点并不慢，第二点非常取决于不同用户的用法。所以更通用来说目前的实现是收消息与解消息分离。欢迎实测一下～
