### ISSUE TITLE
windows平台websocket（client和server）有计划什么时间支持吗？

### ISSUE THREAD

**Issue by SuKunlun** [sogou/workflow#1339]
老项目改造，有在Windows上使用websocket的client和server的需求

**Comment by Barenboim** [comment]
实在不好意思……Windows平台目前没有开发websocket的计划和能力。我们有一个用户基于主分支的修改的websocket client/server支持，也只能支持unix系统：https://github.com/gnblao/workflow 。所以，可能要等等看有没有其他用户基于我们windows来魔改。

**Comment by SuKunlun** [comment]
好的，谢谢
希望有人能快点魔改下吧。。。
我们项目上希望接下来，http、mysql、redis、通信都能使用workflow，现在用的三方库比较杂乱
