### ISSUE TITLE
想使用workflow做MySQL client端预编译，怎么做？

### ISSUE THREAD

**Issue by SuKunlun** [sogou/workflow#1340]
项目为了防sql注入，需要使用sql预编译，看到前面有说过使用MySQL prepare做服务端预编译。
想问有没有办法实现类似其它语言MySQL驱动（如MySQL Java驱动Connector/J）提供的客户端预编译的方法？
类似https://www.cnblogs.com/micrari/p/7112781.html这篇文章描述的这样。

**Comment by Barenboim** [comment]
不太清楚预编译是什么含义，我们的防注入，利用的是MySQL支持的PREPARE语句。使用PREPARE是，需要固定连接，所以在WFMySQLConnection上创建任务就可以。一个connection上的任务，只能串行的执行，除此之外和直接从WFTaskFactory创建MySQL任务没有什么区别。
我们支持的是MySQL最原始的语义，在这个基础上可以很方便的进行二次封装。我感觉你说的方法，就是向外部提供一个执行过PREPARE操作的WFMySQLConnection封装，不是太复杂。需要注意的是，如果连接上出现网络错误（例如ECONNRESET等），说明connection中断了，需要重写执行PREPARE。

**Comment by SuKunlun** [comment]
OK，我先了解其它三方库怎么实现的，然后根据您的建议看看使用workflow怎么封装接口

**Comment by Barenboim** [comment]
建议先用现有的接口试一试，看看什么地方不太方便再考虑封装。有什么疑问随时反馈噢。

**Comment by SuKunlun** [comment]
好的
