### ISSUE TITLE
直接调用thrdpool_create线程池会coredump

### ISSUE THREAD

**Issue by waynejssl** [sogou/workflow#1341]
直接调用thrdpool_create来创建线程池，运行会产生coredump如下图：
`thrdpool = thrdpool_create(10, 0);`
![图片](https://github.com/sogou/workflow/assets/141733207/0113996a-0ae4-46fc-896c-b750fff3ac6d)

代码层面：没有投递任务时，直接创建线程池，最后的崩溃堆栈在msgqueue_get；
另外这里想请教一下，msgqueue拿不到task就直接break退出循环，线程退出，为什么不是继续等待任务，这样设计是有什么考虑？
![图片](https://github.com/sogou/workflow/assets/141733207/888b46ca-e359-455c-88cf-28035bc15846)

**Comment by Barenboim** [comment]
你好。你直接创建一个线程池什么都不干，不会崩溃的啊。能不能发一个demo程序我们看一下？
第二个问题，msgqueue_get得到NULL，只会出现在msgqueue被设置为nonblock，并且没有任何msg在队列里的时候。对应在thrdpool，只会出现在thrdpool_destroy被调用之后，这时候线程是要退出的。

**Comment by waynejssl** [comment]
感谢解答～coredump问题应该是我本地问题

**Comment by waynejssl** [comment]
感谢解答～coredump问题已经解决，应该是我本地问题
