### ISSUE TITLE
资源池的使用方法。

### ISSUE THREAD

**Issue by Zhangdian825** [sogou/workflow#1345]
在资源池的readme中https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md ，有相关的代码，但是只有片面的，能否给出一个完整的使用代码示例，
`
#include "workflow/Workflow.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/HttpMessage.h"
#include "workflow/WFFacilities.h"
#include <string>
#include <vector>
int fetch_with_max(std::vector<std::string>& url_list, size_t max_p)
{
    WFResourcePool pool(max_p);

    for (std::string& url : url_list)
    {
        WFHttpTask *task = WFTaskFactory::create_http_task(url, [&pool](WFHttpTask *task) {
            pool.post(nullptr);
        });
        WFConditional *cond = pool.get(task);  // 无需保存res，可以不传resbuf参数。
        cond->start();
    }

    // wait_here...
}
int main(int argc, char *argv[])
{
  std::vector<std::string> url_list;
  for (int i = 1; i < argc; i++)
  {
    std::string url(argv[i]);
    if (strncasecmp(argv[i], "http://", 7) != 0 &&
        strncasecmp(argv[i], "https://", 8) != 0)
    {
      url = "http://" +url;
    }

    url_list.push_back(url);
  }

  fetch_with_max(url_list,argc - 1);

  return 0;
}

`
比如能否基于该代码，用一个完整的示例写出来，将抓取的url结果也一并保存，因为对具体使用流程不清楚，所以不知道callback如何传。

**Comment by Barenboim** [comment]
你好。你要保存结果的话，可以看一下wget的例子，在http callback里把body存一下，这个问题和资源池好像没有关系吧？这个例子只是展示用资源池做并发度控制而已。如果你之前没有用过workflow，不妨先试试我们一些简单的示例。

**Comment by Zhangdian825** [comment]
那就是资源池还要和ParallelWork配合使用吗？那如何单独使用呢？

**Comment by Barenboim** [comment]
你好。你如果理解我们task的用法，也应该可以理解资源池相关的文档啊。我们的task的都是异步的，任务dispatch就发出去了，所以，你想要并发，并不需要用ParallelTask。
资源是一个抽象的概念，在我们这里可以是任何void *指针，甚至这些个指针都是NULL。意思就是任务实现运行之前，必要从池子里拿到一个资源。池里初始资源是n，每个任务在结束之后又会放回资源。在这个逻辑下，最多就只有n个任务在执行了。所以可以用来限制并发度。
如果你是想要间隔一段时间再抓取，用timer就可以了。可能不需要用到资源池。

**Comment by Barenboim** [comment]
@Zhangdian825
