### ISSUE TITLE
同步阻塞式发起http请求

### ISSUE THREAD

**Issue by lazyman1992** [sogou/workflow#1348]
如题，如何使用workflow发起同步阻塞式的请求，支持吗

**Comment by Barenboim** [comment]
支持肯定是可以的，用wait group包一下就行。还支持C++20协程方式，用这个项目：https://github.com/kedixa/coke

**Comment by lazyman1992** [comment]
您说的用wait group包一下是怎么写啊，比如下面的代码该怎么改啊。因为在国产化平台上运行，编译环境还不支持c++20
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include "workflow/HttpUtil.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"
#include "wfrest/Json.h"

#define REDIRECT_MAX    5
#define RETRY_MAX       2


static WFFacilities::WaitGroup wait_group(1);

class get_profile_client{

public:

    std::string m_str_result;

    void getProfile(std::string ip,std::string port,float startLon,float startLat,float endLon,float endLat){
        std::string url = "http://" + ip+":"+port+"/getProfile?startLon="+std::to_string(startLon)+"&startLat="+std::to_string(startLat)
                          +"&endLon="+std::to_string(endLon)+"&endLat="+std::to_string(endLat);//不重要

        //std::cout<<url<<std::endl;
        WFHttpTask *task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
                                                           [this](WFHttpTask *task){
                                                               auto *resp = task->get_resp();
                                                               if (strcmp(resp->get_status_code(), "200") == 0)
                                                               {

                                                                   protocol::HttpChunkCursor cursor(resp);
                                                                   const void *chunk;
                                                                   size_t size;
                                                                   std::string valueJson;
                                                                   while(cursor.next(&chunk, &size)){

                                                                       std::string tmp((char *)chunk, size);
                                                                       valueJson += tmp;

                                                                   }
                                                                   //std::cout<<valueJson<<std::endl;
                                                                   this->m_str_result = std::move(valueJson);
                                                               }
                                                               else
                                                               {
                                                                   printf("%s %s\n", resp->get_status_code(), resp->get_reason_phrase());
                                                               }
                                                               wait_group.done();
                                                           });

        task->start();
        wait_group.wait();
    }

    get_profile_client(){
        
    };



};

**Comment by Barenboim** [comment]
你这个代码不就是同步的http请求吗？你的意思是不知道怎么吧resp带到函数外面？你callback里，把resp用std::move()移到你想要的地方就可以了。

**Comment by lazyman1992** [comment]
我在别的地方这么用的
get_profile_client* client= new get_profile_client();
client->getProfile()
std::string result = client->m_str_result;
result经常为空，在getProfile里实际是收到回复了的
我是应该把resp移出去么

**Comment by Barenboim** [comment]
经常为空，就是说一些时候还是有结果的了？怀疑有一些请求失败了吧？
你callback里，也需要判断task->get_state()==WFT_STATE_SUCCESS, 而不是直接判断http code。例如一个请求读取一般连接断了，http resp里依然保持了一个不完整的结果，你可以得到200，但没有http body。

**Comment by lazyman1992** [comment]
是在调用的地方std::string result = client->m_str_result;经常为空，但是在函数get_profile_client里面是一直能收到数据的，所以觉得不是同步阻塞式调用的

**Comment by Barenboim** [comment]
你的wait_group应该放到类里面啊，你如果一直用同一个wait_group变量，就肯定是错的。

**Comment by lazyman1992** [comment]
wait_group放类里面咋写啊，试了好多种方式一直报错

**Comment by Barenboim** [comment]
这个是c++语法问题，不是workflow问题😂
类里包含另一个类，可以在构造函数初始化：
~~~cpp
class B
{
public:
    B(int a) { }
};

class A
{
public:
    B b;
    A : b(1) { }
};
~~~
此外C++11之后，还有一下其他写法

**Comment by lazyman1992** [comment]
类改成了下面的写法 wait_group放到类里面了
class get_profile_client{

    public:

        std::string m_str_profiles;

        std::shared_ptr<WFFacilities::WaitGroup> wait_group = nullptr;

        get_profile_client (std::string ip, std::string port){
            m_str_ip = ip;
            m_str_port = port;
            wait_group.reset(new WFFacilities::WaitGroup(1));

        };


        void getProfile(float startLon,float startLat,float endLon,float endLat){
            std::string url = "http://" + m_str_ip+":"+m_str_port+"/getProfile?startLon="+std::to_string(startLon)+"&startLat="+std::to_string(startLat)
                              +"&endLon="+std::to_string(endLon)+"&endLat="+std::to_string(endLat);

            //LOG(INFO)<<url;
            WFHttpTask *task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
                                                               [this](WFHttpTask *task){
                                                                   auto *resp = task->get_resp();

                                                                   int state = task->get_state();
                                                                   int error = task->get_error();
                                                                   switch (state)
                                                                   {
                                                                       case WFT_STATE_SYS_ERROR:
                                                                           LOG(ERROR)<<"system error: "<<error;
                                                                           break;
                                                                       case WFT_STATE_DNS_ERROR:
                                                                           LOG(ERROR)<<"DNS error: "<<error;
                                                                           break;
                                                                       case WFT_STATE_SSL_ERROR:
                                                                           LOG(ERROR)<<"SSL error: "<<error;
                                                                           break;
                                                                       case WFT_STATE_TASK_ERROR:
                                                                           LOG(ERROR)<<"Task error: "<<error;
                                                                           break;
                                                                       case WFT_STATE_SUCCESS:
                                                                           break;
                                                                   }

                                                                   if (state != WFT_STATE_SUCCESS){
                                                                       LOG(ERROR)<<"get Profile Failed";
                                                                       wait_group->done();
                                                                       return;
                                                                   }

                                                                   if (strcmp(resp->get_status_code(), "200") == 0)
                                                                   {

                                                                       protocol::HttpChunkCursor cursor(resp);
                                                                       const void *chunk;
                                                                       size_t size;
                                                                       std::string valueJson;
                                                                       while(cursor.next(&chunk, &size)){

                                                                           std::string tmp((char *)chunk, size);
                                                                           valueJson += tmp;

                                                                       }
                                                                       std::cout<<valueJson;
                                                                       this->m_str_profiles = std::move(valueJson);
                                                                   }
                                                                   else
                                                                   {
                                                                       printf("%s %s\n", resp->get_status_code(), resp->get_reason_phrase());
                                                                   }
                                                                   wait_group->done();
                                                               });

            task->start();
            wait_group->wait();
        }

private:
    std::string m_str_ip;
    std::string m_str_port;
};
在其他类里面用下面的代码调用
get_profile_client* client= new get_profile_client();
client->getProfile()
std::string result = client-> m_str_profiles;
还是会出现client-> m_str_profiles为空，但是请求里实际是收到数据的情况，感觉不是同步阻塞式的请求

**Comment by kedixa** [comment]
```cpp
#include <iostream>
#include <string>
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"
#include "workflow/HttpUtil.h"

class SyncHttpClient {
public:
    SyncHttpClient(const std::string &host, const std::string &port, int max_redirect, int max_retry)
        : host(host), port(port), max_redirect(max_redirect), max_retry(max_retry)
    {}

    std::string request(const std::string &path) const {
        std::string url;
        std::string body;
        WFFacilities::WaitGroup wg(1);

        url.assign("http://").append(host).append(":").append(port)
           .append(path);

        WFHttpTask *task = WFTaskFactory::create_http_task(url, max_redirect, max_retry,
            [&wg, &body](WFHttpTask *task) {
                get_http_body(task, body);
                wg.done();
            }
        );

        task->start();

        wg.wait();
        return body;
    }

private:
    static void get_http_body(WFHttpTask *task, std::string &body) {
        int state = task->get_state();

        if (state == WFT_STATE_SUCCESS) {
            protocol::HttpResponse *resp = task->get_resp();
            protocol::HttpChunkCursor cursor(resp);
            const void *chunk;
            std::size_t size;

            while (cursor.next(&chunk, &size))
                body.append((const char *)chunk, size);
        }
        else {
            // handle error
        }
    }

private:
    std::string host;
    std::string port;
    int max_redirect;
    int max_retry;
};

int main() {
    SyncHttpClient http_cli("sogou.com", "80", 2, 2);
    std::string body = http_cli.request("/robots.txt");
    std::cout << body << std::endl;
    return 0;
}
```

**Comment by lazyman1992** [comment]
谢谢您的帮助
