### ISSUE TITLE
一个服务里面的多个tls客户端如何设置不同的SSL_CTX

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1349]
我一个服务里面有两个客户端，一个是通过WFNetworkTaskFactory<CustomRequest, CustomResponse>::create_client_task创建的，这个客户端需要强制进行双向TLS认证，所以我通过获取WFGlobal::get_ssl_client_ctx();对SSL_CTX进行了一些配置。现在另外一个客户端通过WFTaskFactory::create_http_task创建的，不需要进行双向认证，这个时候我该怎么办，还是设置全局的SSL_CTX吗？

**Comment by Barenboim** [comment]
目前的情况，这个不太好改，目前client全局的SSL_CTX只有一个。我对这块不太了解，SSL_CTX里，可以根据不同的目标配置不同的认证信息吗？

**Comment by Barenboim** [comment]
这个后面是怎么解决的？

**Comment by coderwxl** [comment]
封了个程序，代码中调用那个程序进行tls通信。
