### ISSUE TITLE
压测时出现大量错误 code. 11  Resource temporarily unavaila

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1350]
使用的场景是： 
app -->|| 1、websock 接口 -->2、 业务逻辑组包 -->3、wf client ||--> other server 
1 2 3 事在同一个进程下面，wfclient 使用http请求去访问other server 
app的请求访问过来之后保持长连接，然后把收到的请求业务处理之后使用wf的client转发给另一个服务的接口，这个服务不熟wf写的。现在问题是wf client访问的时候报错code 11 Resource temporarily unavailable  ，这个情况在我本地机器上没有出现，部署换了个云服务器之后出现了  所以想问一下 这个错误会和什么默认的设置有关系。

**Comment by holmes1412** [comment]
你好，你本机没有，听上去可能呢对方限制连接有关。麻烦帮确认几个问题：
1. 看看现在的3、wf client ||--> other server的连接数是多少呢？
2. other server是否有设置连接限制？或者说这台机器是否有最大连接限制？
3. 你压测云服务器的压力和你测本机是一样的么？

**Comment by Barenboim** [comment]
你这个应该就是client对外最大连接数的问题，你改一下全局配置就好了。
~~~cpp
#include "workflow/WFGlobal.h"
int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 2000;
    WORKFLOW_library_init(&settings);
    ...
}
~~~

**Comment by 18328594608** [comment]
最新问题更新：
换到本地之后也有出现这个问题，wf client ||--> other server的连接数量是一直在增加的，大概连接数量到1000左右之后报错。
关于settings.endpoint_params.max_connections = 2000; 这个设置是有的，修改过这个全局设置，我需要把这个2000再加大一些么。

**Comment by Barenboim** [comment]
如果你的max_connections配置为2000，那么1000连接的时候肯定不会出现EAGAIN错误的。但EAGAIN也只有在client对单个目标连接数过多的时候才会出现，好像没有其它的可能。你是不是对连接的统计有问题，或者根本没有设置成功？

**Comment by 18328594608** [comment]
后续确认了一下。是在2000左右的时候出现的这个报错，那应该就是这个问题，我把这个设置再设大一些看看实际情况，另外这个设置会影响到运行性能之类的么

**Comment by Barenboim** [comment]
不会，几千个连接没有什么。
这个配置是client对一个目标IP的最大连接数。
