### ISSUE TITLE
websocket分支一个问题求帮助

### ISSUE THREAD

**Issue by Detxie** [sogou/workflow#1352]
问题描述：
正常使用websocket分支跑业务代码。大约10几分钟挂死。段错误。
gdb core文件 在/src/kernel/Communicator.cc 980 line 出现问题。
也就是else if ((session->out = session->message_out()) != NULL) 这一行。是seesion空指针了?

打印了一下session变量
(gdb) o *session
$9 = {
_vptr.CommSession = 0xffff6c08d670,
target = 0x0 ,
conn = 0x45,
out = 0xffff4000ab70,
int = 0xfffffc08d680,
seq = 281472494261872,
begin_time = {
  tv_sec = 281472494262464,
  tv_nsec = 281472494262448
},
timeout = 1812604976,
passive = 65535
}

疑问:
1.这是在websocket-client处理process接受server数据时出现问题了？
2.是server发送的数据有问题么?

**Comment by holmes1412** [comment]
你好，这个是在建立完连接之后，准备用这个session（也就是我们的channel）发出一个message，这时候发现session的内存错乱了。
可能的原因有两个：
- 你的程序有非法内存操作，写错了别的地方（这个可能发生在任何情况，比如释放了一个东西，又操作它，它的地址可能已经被session用了），这个你可以用valgrind跑一下看看有没有invalid write；
- 框架代码有非法释放session的操作，这个我也再review一下代码。

你可以先valgrind、并且复现一下，提供一下更多信息，感谢～

**Comment by Detxie** [comment]
> 你好，这个是在建立完连接之后，准备用这个session（也就是我们的channel）发出一个message，这时候发现session的内存错乱了。 可能的原因有两个：
> 
> * 你的程序有非法内存操作，写错了别的地方（这个可能发生在任何情况，比如释放了一个东西，又操作它，它的地址可能已经被session用了），这个你可以用valgrind跑一下看看有没有invalid write；
> * 框架代码有非法释放session的操作，这个我也再review一下代码。
> 
> 你可以先valgrind、并且复现一下，提供一下更多信息，感谢～

好的，我会测试一下。 昨晚跑稳定性又遇到一个问题。
问题描述: 
1.程序挂死，GDB查看后问题代码在 src/protocol/websocket_parser/c : 178
2.挂在memcpy方法。
3.查看了一下几个变量。
(1)*parser {
fin = 1 '\001',
mask = 1 '001',
opcode = 8, 
masking_key = "\203,Q\253",
payload_length = 1 , 
header_buf = "\270\201\203,Q\253\000\000\000\000\000\000\000"
payload_data = 0xffff5c4abea0,
nreceived = 2 , 
nleft = 1 , 
satus_code = 39682
}

(2) *p  Cabbit access nenory at address 0x0 

看问题是出现在payload_length = 1 ? ,这个是server发送的数据有问题，还是接受的时候有问题。

**Comment by Detxie** [comment]
顺便问一下，这个parser数据就是poller线程去缓存中拿的websocket-server发送的数据吧？ 这个memcpy(p,*data+2,len-2)中的+2 -2是什么意思。

**Comment by holmes1412** [comment]
你好，感谢这么仔细的信息。这里是解析close frame时，进行status_code的解析。

参考：https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.1

里边说的是close frame里可以带上body，body前两个字节是一个status_code，表示close的原因，包括：an endpoint shutting down, an endpoint having received a frame too large, or an endpoint having received a frame that does not conform to the format expected by the endpoint等。

然后body内容是一段不一定可读的message。所以这里的解析是：

```cpp
if (parser->opcode == WebSocketFrameConnectionClose)                        
{                                                                           
    parser->status_code = ntohs(*((uint16_t*)p));  // 按网络序读出前两个字节
    p = malloc(parser->payload_length - 2);        // 后面的就是message了

    // 把message整理一下，重新挂到payload_data上。这样可以让读取接口可以读到message，且正确被析构时释放
    memcpy(p, (unsigned char *)parser->payload_data + 2, parser->payload_length - 2);
    free(parser->payload_data);
    parser->payload_data = p;  
    parser->payload_length -= 2;                                            
}
```

不过我仔细读了下，这个body不是必须有的。但如果没有，payload_length也不应该是1，应该是0才对。但无论如何，client都不应该crash。

- 我会改一下这段代码，对长度进行判断再进行解析；
- 如果你想定位server的问题，可以gdb时再看看它的payload拿一个字节是个什么信息。理论上应该是无，或者是个status_code；

**Comment by Detxie** [comment]
> 

- 多谢讲解。
- 有改动代码，如何方便的可以先发到这里么，我本地同步先测试一下。

**Comment by Detxie** [comment]
最开的问题我在tutorial-14-websocket_cli.cc上进行了复现，如果有时间帮忙看一下是否是使用的问题还是本身框架处理逻辑问题。
一、问题描述

- 之前在创建websocket-client时提了一个超时需求，client会起一个task，向server发送一条消息，来确保双方连接建立。当时测试时发现会阻塞住，所以使用task->set_send_timout()，根据最近的测试，我发现这个机制并不生效，我在task->get_state()时不会得到错误。
- 基于上面的问题，我发现waitgroup.wait(10),可以传入一个ms时间来保证创建ws-client不阻塞住。所以我就进行了测试，报最上面的Communicator.cc 780错误。

二、问题复现

- 在我自己项目中会有大批量的websocket-client被建立，此时网络环境也开始变得很差，当我create一个task给server端发送ping包建立连接时，我发现这个task并不会立马被执行(task回调中的代码并不会被打印)，可能会等上10几秒，此时我设置wg.wait(2000) 2S时间内，task还是没有执行，整个流程结束。
- 在tutorial-14-websocket_cli.cc，由于我无法模拟让task执行变得慢起来，所以我把wait操作task->start()操作换了一下顺序，报的错误和我发的一样，代码如下。
`
......
msg_>set_text_data("");
wg.wait(10);
task->start();
client.deinit();
sleep(10000); 
return 0;
`

**Comment by holmes1412** [comment]
> * 多谢讲解。
> * 有改动代码，如何方便的可以先发到这里么，我本地同步先测试一下。

这个已经提PR了：https://github.com/sogou/workflow/pull/1355
可以先拉我的fork再试一下：https://github.com/holmes1412/workflow-major/tree/websocket 谢谢！

**Comment by Detxie** [comment]
> > * 多谢讲解。
> > * 有改动代码，如何方便的可以先发到这里么，我本地同步先测试一下。
> 
> 这个已经提PR了：#1355 可以先拉我的fork再试一下：https://github.com/holmes1412/workflow-major/tree/websocket 谢谢！

多谢！

**Comment by holmes1412** [comment]
对于你的场景我大概了解了，应该是因为你发现慢的task比较多，想要一些解决办法。

#### 1. crash的问题
你给的示例代码这么做是肯定会crash的。因为task发出之后还没回来，client已经调用deinit()了，deinit()的时候会delete内部的channel，也就是昨天你的那个session，它是我们建立的连接对象。所以task实际发出的一瞬间，session被释放，就是昨天列的第二种可能性。

想要不crash，需要你保证所有task都处理完之后再deinit。按照websocket协议，最好deinit之前给server发个close说明退出原因。这个我们讨论一下是否有引用计数等更好的办法，让client和task解耦，有好的解决方案我再找你交流一下～

#### 2. 慢的问题
send_timeout保证的是写入缓冲区，并不能保证对方可以收到。你可以看看是不是ping的时候就已经发现链路比较慢呢？还是说其他慢的原因，我们看看怎么解决。

**Comment by holmes1412** [comment]
hi~ 上述的PR重新提交了，在这次修复的功能之外，内部优化了一些代码，并且加上了client设置close reason的接口，和更新了拿server发过来的close的信息的接口实现，可以继续使用。我今天也跑了valgrind，明天继续跟进更多测试。

**Comment by Detxie** [comment]
你上面说了一个问题:

所以应该就是还没send开始出去。比较可能的原因是同一个client内的发送的task在排队（因为内部需要串行在一个连接上发出），我也批量测一下看看速度

我对我的场景再做一下补充:

- 我初始化一个ws-client。这个client只有一个task，即task = ws-client.crate_ping_task。用这个task来建立和server的连接。出现的问题就是有时候这个task->start()并不会很快的执行，会等一段时间(判断依据就是task的回调打印)，然后我wait操作超时->deinit()->crash
- 每个ws-client每秒大约接受server端30个数据，10k ~ 1000K
- 我会有多个ws-client被建立
- 如果需要测试的话。建议使用4核或者更少的CPU，创建12个ws-client。每个client每秒接受30次数据。

**Comment by holmes1412** [comment]
> wait操作超时->deinit()->crash

wait的时长是send超时时间么？所以实际上task还没被调度？还是说能够保证所有task已经回调了再deinit client呢？crash的问题也许你可以先尝试不deinit client，简单排除一下原因。

> 每个ws-client每秒大约接受server端30个数据

所以一次请求是30ms左右？你可以看看client和server端的ping耗时大概多少么？

**Comment by DonieGeng** [comment]
> > wait操作超时->deinit()->crash
> 
> wait的时长是send超时时间么？所以实际上task还没被调度？还是说能够保证所有task已经回调了再deinit client呢？crash的问题也许你可以先尝试不deinit client，简单排除一下原因。
第一种情况：send设置100ms，wait设置150s，ping task的回调没有执行，wait超时，执行deinit
第二种情况：仅设置wait  150s，ping task的回调没有执行，wait超时，执行deinit
应用场景是需要保证websocket建立，返回上层业务成功，或者websocket未建立成功，回滚操作，销毁client，返回失败
现在搞不清楚是ping包还没有发出去，还是pong包没回来，还是pong包回来了，callback等待中，这些某个过程中 deinit了
> 
> > 每个ws-client每秒大约接受server端30个数据
> 
> 所以一次请求是30ms左右？你可以看看client和server端的ping耗时大概多少么？
不是一个请求30ms，是业务上每个client每秒会接受到服务端发的30个左右的数据包，一颗4个A53组成的4核嵌入式CPU，需要建立12个 websocket client

**Comment by Barenboim** [comment]
@Detxie
