### ISSUE TITLE
关于executor同名队列任务执行顺序的问题

### ISSUE THREAD

**Issue by JustDoIt0910** [sogou/workflow#1357]
您好，最近拜读项目时有个小疑问。看到您在对于Executor调度算法的文中说同名队列下的任务是按照FIFO顺序执行的，但是代码中executor_thread_routine函数是先将身后的任务调度起来，再执行session->execute()，执行当前任务。这样有没有可能后面的任务先被某个空闲线程执行，当前的任务才被执行呢？
```c++
void Executor::executor_thread_routine(void *context)
{
	ExecQueue *queue = (ExecQueue *)context;
	struct ExecSessionEntry *entry;
	ExecSession *session;

	pthread_mutex_lock(&queue->mutex);
	entry = list_entry(queue->session_list.next, struct ExecSessionEntry, list);
	list_del(&entry->list);
	session = entry->session;
	if (!list_empty(&queue->session_list))
	{
		struct thrdpool_task task = {
			.routine = Executor::executor_thread_routine,
			.context = queue
		};
               // 这里在session->execute()之前调度了下一个任务，有没有可能下个任务先被执行？
		__thrdpool_schedule(&task, entry, entry->thrdpool);
	}
	else
	    free(entry);

	pthread_mutex_unlock(&queue->mutex);
	session->execute();
	session->handle(ES_STATE_FINISHED, 0);
}
```

**Comment by Barenboim** [comment]
你好。同名任务里，后一个任务是由前一个任务放入线程池的。显然前一个任务已经执行（虽然还没有到实际的execute）了，后一个任务才可能被放入线程池。前一个任务把下一个任务放入线程池之后，就直接执行execute了。所以，这里不存在下个任务先执行的可能。如果有空闲线程，是并行执行的，后一个会慢一点被调度。

**Comment by Barenboim** [comment]
@JustDoIt0910

**Comment by yockie** [comment]
> 你好。同名任务里，后一个任务是由前一个任务放入线程池的。显然前一个任务已经执行（虽然还没有到实际的execute）了，后一个任务才可能被放入线程池。前一个任务把下一个任务放入线程池之后，就直接执行execute了。所以，这里不存在下个任务先执行的可能。如果有空闲线程，是并行执行的，后一个会慢一点被调度。

@Barenboim 大佬，我看这段代码的时候跟lz有同样的疑惑。
我理解你这段表达的意思是task是串行的、session->execute的执行可能是并行的对吗？

但是这个task只是一个封装，实际传入和执行的任务就是session吧。那就还是lz所说的执行任务不是FIFO的？

**Comment by Barenboim** [comment]
> > 你好。同名任务里，后一个任务是由前一个任务放入线程池的。显然前一个任务已经执行（虽然还没有到实际的execute）了，后一个任务才可能被放入线程池。前一个任务把下一个任务放入线程池之后，就直接执行execute了。所以，这里不存在下个任务先执行的可能。如果有空闲线程，是并行执行的，后一个会慢一点被调度。
> 
> @Barenboim 大佬，我看这段代码的时候跟lz有同样的疑惑。 我理解你这段表达的意思是task是串行的、session->execute的执行可能是并行的对吗？
> 
> 但是这个task只是一个封装，实际传入和执行的任务就是session吧。那就还是lz所说的执行任务不是FIFO的？


我们的同名计算任务，肯定是可以并行执行的。也就是说，executor同一个计算队列里的session，只要有线程肯定是可以并发。
只有外部同一个series上的task，是严格串行执行的。
