### ISSUE TITLE
http客户端请求后，在响应回调中如何获取req的body内容？

### ISSUE THREAD

**Issue by guoshengjer** [sogou/workflow#1361]
使用workflow进行http服务的开发。目前需要在获取http响应结果后，获取http请求的body字段中的内容。
通过下面的获取方式，在响应的回调中可以获取到http响应的body字段，获取不到http请求的body字段。
想确认一下是否支持http客户端获取请求的body字段。
```c++
//请求
void AAA::httpclient_request(){
  std::string url = "http://xxxxx";
  //请求数据
  WFHttpTask* task = WFTaskFactory::create_http_task(url, 5, 0,
	  std::bind(&AAA::HttpClientCallback, this, std::placeholders::_1));
  auto req = task->get_req();
  req->add_header_pair("Content-Type", "application/json;charset=UTF-8");
  req->set_method("POST");
  std::string body = "{\"xxx\":100}";
  req->append_output_body(body);
  task->set_receive_timeout(timeout_);
  task->start();
}

//回调中获取请求时的body字段
void AAA::HttpClientCallback(WFHttpTask* task){
  auto resp = task->get_resp();
  auto req = task->get_req();
  //判断是否返回正常
  int state = task->get_state();
  int error = task->get_error();
  if (state != WFT_STATE_SUCCESS)
  {
	  return;
  }
  std::string code = resp->get_status_code();
//获取server的响应body
  protocol::HttpChunkCursor cursor(resp);
  const void* chunk;
  size_t size;
  std::string body;
  while (cursor.next(&chunk, &size))
  {
	  std::string chunk_body = std::string((const char*)chunk, size);
	  chunk_body = Utf8ToGbk(chunk_body.c_str());
	  body += chunk_body;
  }
//获取请求时的请求body
protocol::HttpChunkCursor cursor_temp(req);
const void* chunk_temp;
size_t size_temp;
std::string body_temp;
while (cursor_temp.next(&chunk_temp, &size_temp))
{
	std::string chunk_body_temp = std::string((const char*)chunk_temp, size_temp);
	chunk_body_temp = Utf8ToGbk(chunk_body_temp.c_str());
	body_temp += chunk_body_temp;
}
//此时server的响应body可以获取到，请求时的请求body获取失败

}
```

**Comment by Barenboim** [comment]
目前output body确实拿不到噢。我想想能不能加个接口。如果是现在的代码的话，你可以把output body放在HttpMessage的attachment里，然后通过req->append_output_body_nocopy把数据无拷贝的放到output body。attachment的生命周期和message一致，在message销毁时也同步被销毁。
不过这么用确实不是太方便。

**Comment by guoshengjer** [comment]
谢谢！目前按照您这边提供的方法，我实现了一个简单的派生类。
由于项目上对内存和性能要求不大（技术水平有限，不会写），没有使用req->append_output_body_nocopy进行数据无拷贝。
刚开始没有手动进行派生类内存释放，怕会有内存泄露。后面看到在httpmessage里有做销毁操作，看上去没有内存泄露的问题。
能成功获取请求时的body内容。问题解决。

具体的代码如下：
```c++
//派生类，只声明了一个body成员变量。使用set和get方法进行操作。
class BodyInfo :public protocol::HttpMessage::Attachment {
public:
	BodyInfo() = default;
	~BodyInfo() = default;
	void set_body(const std::string& att) {
		body = att;
	}
	std::string get_body() const { return this->body; }
private:
	std::string body = "";
};

//请求
void AAA::httpclient_request(){
  std::string url = "http://xxxxx";
  //请求数据
  WFHttpTask* task = WFTaskFactory::create_http_task(url, 5, 0,
	  std::bind(&AAA::HttpClientCallback, this, std::placeholders::_1));
  auto req = task->get_req();
  req->add_header_pair("Content-Type", "application/json;charset=UTF-8");
  req->set_method("POST");
  std::string body = "{\"xxx\":100}";
/****************新增body存放*********************/
BodyInfo* bi = new BodyInfo();
bi->set_body(body);
req->set_attachment(bi);
/****************************************************/
  req->append_output_body(body);
  task->set_receive_timeout(timeout_);
  task->start();
}

//回调中获取请求时的body字段
void AAA::HttpClientCallback(WFHttpTask* task){
  auto resp = task->get_resp();
  auto req = task->get_req();
  //判断是否返回正常
  int state = task->get_state();
  int error = task->get_error();
  if (state != WFT_STATE_SUCCESS)
  {
	  return;
  }
  std::string code = resp->get_status_code();
//获取server的响应body
  protocol::HttpChunkCursor cursor(resp);
  const void* chunk;
  size_t size;
  std::string body;
  while (cursor.next(&chunk, &size))
  {
	  std::string chunk_body = std::string((const char*)chunk, size);
	  chunk_body = Utf8ToGbk(chunk_body.c_str());
	  body += chunk_body;
  }
//获取请求时的请求body
/****************新增获取req的body*********************/
BodyInfo *bi = (BodyInfo*)req->get_attachment();
std::string body_temp = bi->get_body();
/*********************************************/
//此时server的响应body可以获取到，请求时的请求body也可以获取到

}

```

后续是否有计划开放读取请求body的接口？因为我在调试时看到req的output_body里其实有存放body信息。

**Comment by Barenboim** [comment]
> 谢谢！目前按照您这边提供的方法，我实现了一个简单的派生类。 由于项目上对内存和性能要求不大（技术水平有限，不会写），没有使用req->append_output_body_nocopy进行数据无拷贝。 刚开始没有手动进行派生类内存释放，怕会有内存泄露。后面看到在httpmessage里有做销毁操作，看上去没有内存泄露的问题。 能成功获取请求时的body内容。问题解决。
> 
> 具体的代码如下：
> 
> ```c++
> //派生类，只声明了一个body成员变量。使用set和get方法进行操作。
> class BodyInfo :public protocol::HttpMessage::Attachment {
> public:
> 	BodyInfo() = default;
> 	~BodyInfo() = default;
> 	void set_body(const std::string& att) {
> 		body = att;
> 	}
> 	std::string get_body() const { return this->body; }
> private:
> 	std::string body = "";
> };
> 
> //请求
> void AAA::httpclient_request(){
>   std::string url = "http://xxxxx";
>   //请求数据
>   WFHttpTask* task = WFTaskFactory::create_http_task(url, 5, 0,
> 	  std::bind(&AAA::HttpClientCallback, this, std::placeholders::_1));
>   auto req = task->get_req();
>   req->add_header_pair("Content-Type", "application/json;charset=UTF-8");
>   req->set_method("POST");
>   std::string body = "{\"xxx\":100}";
> /****************新增body存放*********************/
> BodyInfo* bi = new BodyInfo();
> bi->set_body(body);
> req->set_attachment(bi);
> /****************************************************/
>   req->append_output_body(body);
>   task->set_receive_timeout(timeout_);
>   task->start();
> }
> 
> //回调中获取请求时的body字段
> void AAA::HttpClientCallback(WFHttpTask* task){
>   auto resp = task->get_resp();
>   auto req = task->get_req();
>   //判断是否返回正常
>   int state = task->get_state();
>   int error = task->get_error();
>   if (state != WFT_STATE_SUCCESS)
>   {
> 	  return;
>   }
>   std::string code = resp->get_status_code();
> //获取server的响应body
>   protocol::HttpChunkCursor cursor(resp);
>   const void* chunk;
>   size_t size;
>   std::string body;
>   while (cursor.next(&chunk, &size))
>   {
> 	  std::string chunk_body = std::string((const char*)chunk, size);
> 	  chunk_body = Utf8ToGbk(chunk_body.c_str());
> 	  body += chunk_body;
>   }
> //获取请求时的请求body
> /****************新增获取req的body*********************/
> BodyInfo *bi = (BodyInfo*)req->get_attachment();
> std::string body_temp = bi->get_body();
> /*********************************************/
> //此时server的响应body可以获取到，请求时的请求body也可以获取到
> 
> }
> ```
> 
> 后续是否有计划开放读取请求body的接口？因为我在调试时看到req的output_body里其实有存放body信息。

你这个水平很高啊，一下就会有attachment了，之前只在我们内部的一些项目里有用这个接口。
我正在设计一个让用户拿output body的方法，感觉还是有用的。因为output body也是离散内存，所以这里可能需要设计一下接口。
如果项目好用记得star哈。

**Comment by Barenboim** [comment]
@guoshengjer 
看一下这个PR：https://github.com/sogou/workflow/pull/1362
