### ISSUE TITLE
如何处理高并发耗时请求

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1364]
业务逻辑里面有一个操作比较耗时，这个操作是同步的。如果突然有大量的客户端（几千个）请求连接，服务好像就死掉了，如何进行优化？加消息队列吗？

**Comment by Barenboim** [comment]
你好。你这个场景下，这些突发的请求，都是重计算的请求吗？如果用计算任务，那么这些计算请求本身会被排队，不需要再用消息队列。
有一个优化点，是否有一些请求在开始计算之前，连接就已经被client关闭了？这种情况可以自行判断一些，减少不必要的计算。另外，能不能发一下你的服务器基本框架，我们看看有什么可以优化一下。

**Comment by coderwxl** [comment]
`void process(WFCustomTask *task)
{
	int state = task->get_state();
	int error = task->get_error();
	CustomRequest *req = task->get_req();
	CustomResponse *rsp = task->get_resp();
	TProtoContext *ctx = NULL;
	unsigned char *data = NULL;
	int *len = NULL;

	if (state != WFT_STATE_TOREPLY)
	{
        const char *str = WFGlobal::get_error_string(state, error);
		trace_log(ERR, "%s:%d Error: %s\n", __FUNCTION__, __LINE__, str);
		return;
	}

	req->GetMessage(&ctx, &data, &len);
    
    SetDBConnection();

    pthread_rwlock_rdlock(&g_rwlock);
    try
    {
	    g_servicePluginFacade->Handle(*ctx, data, *len);
        pthread_rwlock_unlock(&g_rwlock);
    }
    catch(...)
    {
        pthread_rwlock_unlock(&g_rwlock);
        trace_log(ERR, "service exception! exit...");
        exit(-1);
    }

	*rsp = std::move(*req); //减少内存拷贝
}`
g_servicePluginFacade->Handle是具体的业务处理逻辑，业务逻辑里面主要慢的是连接第三方程序进行处理，第三方程序处理的比较慢，这个该怎么优化。

**Comment by Barenboim** [comment]
啊，你这个好处理啊。第三方应用程序，如果不能写在workflow的网络任务的话，可以用counter的方式，把workflow的process线程让出来。可以看一下这个文档：
https://github.com/sogou/workflow/blob/master/docs/about-counter.md#server%E4%B8%8E%E5%85%B6%E5%AE%83%E5%BC%82%E6%AD%A5%E5%BC%95%E6%93%8E%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8
一个第三方的异步任务+一个Counter或Mailbox任务，可以变成一个workflow任务，然后push_back就可以了。

**Comment by coderwxl** [comment]
把耗时的网络任务push_back到当前series的后面，这样会一直占用process线程吗

**Comment by Barenboim** [comment]
你是不是这么久一直用错……workflow的用法就是一直push_back，不会占用线程。
server回复的时机，是server task所在的series里的任务被清空，而不是process函数结束啊。你push_back一个任务，process函数就结束了，但并不会立刻回复的。不要在我们的网络线程里进行任何的等待，一直push_back就对了。

**Comment by Barenboim** [comment]
你Handle里也是发起一个workflow的网络任务吗？那不用counter了，直接push_back就可以了。

**Comment by Barenboim** [comment]
@coderwxl
