### ISSUE TITLE
如何实现创建单个任务，持续处理数据

### ISSUE THREAD

**Issue by douge** [sogou/workflow#1369]
如何建立一个task持续处理接收到的数据？例如，一个tcp服务端持续接收来自客户端的数据，数据需要被经过多个流程处理后发送给另外一个服务端，如何用workflow的task实现启动一个任务后，持续接收数据并完成整个流程，而无需每次收到数据重新建立任务？

**Comment by Barenboim** [comment]
这个问题其实我们也考虑过。但本质上，让一个task等待数据的方式（数据驱动？），优化到极致就会变成我们目前的方式，也就是主动发起模式。
因为数据驱动的话，如果一个让任务等待数据，那么这个线程就只能做一种事情，如果没有这种事情对应的数据，这个线程就一直处于等待中。而我们现有的方式，相当于让线程等待的对像是数据+操作，这样所有线程都是对等的，只要线程有空闲就不存在任务无法被及时调度的情况。你可以思考一下以下两种生产者，消费者模式的实现有什么区别：
#### 程序1：
~~~cpp
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t cond = PTHREAD_COND_INITIALIZER;
list_t list;

void comsumer(void *context)
{
    while (1) {
        void *data;
        pthread_mutex_lock(&mutex);
        while (list.empty())
            pthread_cond_wait(&cond, &mutex);
        data = list.pop();
        pthread_mutex_unlock(&mutex);
        do_consume(data);
    }
}

void producer()
{
    while (1) {
        void *data = do_produce();
        pthread_mutex_lock(&mutex);
        list.push(data);
        pthread_cond_signal(&cond);
        pthread_mutex_unlock(&mutex);
    }
}

int main(void)
{
    threadpool_t pool(N);  // N consumer threads
    int i;
    for (i = 0; i < N; i++)
       pool.submit(consumer, NULL);
    ....
}
~~~
#### 程序2
~~~cpp
threadpool_t pool(N);

void do_consume(void *context)
{
    void *data = context;
    ...
}

void producer()
{
    while (1) {
        void *data = do_produce();
        pool.submit(do_consume, data);
    }
}
~~~
你会发现，这两个程序在这个场景下是等价的。程序1对应你说的数据驱动模式，程序2是我们目前使用的主动模式，或者说数据+操作的模式。程序1的问题是所有线程卡在同一件事情上，而程序2每次提交的是数据+操作，那么他可以灵活很多，整个线程池可以被多种消费者复用。
workflow里的计算线程比程序2还更进一步，因为程序2依然会有某种生产者把线程池队列占满，新的任务进来要等待很久的情况。workflow为解决这个问题引起了计算队列。但本质上还是这种数据+操作的提交模式。
不知道你能不能理解我这个解释？当然，我们对于数据驱动也做过一次实验，你可以看看这个项目：https://github.com/kedixa/workflow-extra#gopipe

**Comment by douge** [comment]
牛！打开了一个新思路。你的意思是否为将对数据的操作作为task，将数据作为task参数传入，交给框架进行处理运行？
例如：
```yaml
WFGoTask* task = WFaskFactory::create_go_task("go", func, data);
SeriesWork* series = Workflow::create_serise_work(task, nullptr);
series->start();
```
如果是的话，有几个问题请教一下：
1. 数据每次过来是否都需要重新创建任务和series？如果是的话创建任务中有new操作，是否会降低效率？
2. 如果数据需要多个处理步骤，例如包括数据解析、数据提取，数据处理等等，这些步骤组合为一个task更好还是分成多个task进而组成一个serise更好？
3. 如果分成多个task，如何在task之间传递数据效率更高？

**Comment by Barenboim** [comment]
1、一般来讲，只需要一个series。后面来的任务就一直push_back就可以了。你可以把series理解成我们的协程。每次创建释放任务，会有一次new/delete，所以，我们的计算任务不适合做特别小的计算。比如你就乘两个数，直接算就可以了，没必要创建计算任务。
2、多个步骤的任务，如果步骤之间不用等待网络请求，文件IO什么的，那直接一个任务就可以了，减少线程调度的次数（计算任务一定会切线程）。如果中间有IO，那就做成多个计算任务，每种计算任务一个队列名。这样效率是最高的。
3、task之间传递数据，一般是在task的callback里做，把前一个任务的输出交给后一个任务的输入。计算任务的callback在计算结束之后立刻执行。我这里说的是标准的WFThreadTask，你用WFGoTask的话，传递数据的方法就很灵活了，比如大家可以共享一块全局数据什么的。你也可以在series context上传递数据，不过用WFTimedGoTask（带超时的go task）时，要注意一下series先结束的问题。

**Comment by douge** [comment]
学到了，感谢大牛

**Comment by Barenboim** [comment]
关于第一个问题，你说每次创建series，应该指的是一系列task的series，对应一个完整的处理流程，那是没有问题的。我以为你说每个task都create一次series，那就没有必要了。
