### ISSUE TITLE
如何在其他程序的异步回调中，使用workflow的push_back任务

### ISSUE THREAD

**Issue by cloud-yd** [sogou/workflow#1371]
~~~cpp
void captureCallBack()
{
    WFThreadTask<media_input_t, media_output_t> *media_task =
        WFThreadTaskFactory<media_input_t, media_output_t>::create_thread_task("dispenseMedia", mediaRoutine, mediaCallback);
    //这个回调函数是毫秒级的，目前会发生任务队列不停扩容，直到程序崩溃
    series_of(first_task)->push_back(media_task);
    
   //改成下面这种方式程序没有问题，就是已启动就会有50多个线程，但是我看runing的也就5~8个
   media_task->start();
}

void Init(const input_t* input, output_t* output)
{
    //这里启动一个异步捕获线程
    input->pThis->captureDevice(..., captureCallBack);
}

void InitCallback(WFThreadTask<sip_info_input_t, media_output_t>* threadTask){}

void start()
{
    // 该任务用于启动一个异步回调的任务
    // first_task是保存在类里的，程序结束时才会被销毁
    WFThreadTask<input_t, output_t> *first_task =
        WFThreadTaskFactory<sip_info_input_t, media_output_t>::create_thread_task("capture", Init, InitCallback);

    first_task->start();
}
~~~

**Comment by cloud-yd** [comment]
我目前主要是对线程池的使用有疑问，用户不需要去关心线程池的创建和初始化，但是当task执行结束之后，task的资源就被销毁了，那是不是连带着底层线程池的资源也被回收了？

**Comment by cloud-yd** [comment]
不好意思，忘记添加代码块了
```c++
void captureCallBack()
{
WFThreadTask<media_input_t, media_output_t> *media_task =
WFThreadTaskFactory<media_input_t, media_output_t>::create_thread_task("dispenseMedia", mediaRoutine, mediaCallback);
//这个回调函数是毫秒级的，目前会发生任务队列不停扩容，直到程序崩溃
series_of(first_task)->push_back(media_task);

//改成下面这种方式程序没有问题，就是启动会有50多个线程，但是我看runing的也就5~8个
media_task->start();
}

void Init(const input_t* input, output_t* output)
{
//这里启动一个异步捕获线程
input->pThis->captureDevice(..., captureCallBack);
}

void InitCallback(WFThreadTask<sip_info_input_t, media_output_t>* threadTask){}

void start()
{
// 该任务用于启动一个异步回调的任务
// first_task是保存在类里的，程序结束时才会被销毁
WFThreadTask<input_t, output_t> *first_task =
WFThreadTaskFactory<sip_info_input_t, media_output_t>::create_thread_task("capture", Init, InitCallback);

first_task->start();
}

**Comment by holmes1412** [comment]
你好，这个地方传的参数应该callback当前的task，而不是first_task。崩溃应该是这个原因：
```cpp
void captureCallBack(task)
{
    WFThreadTask<media_input_t, media_output_t> *media_task = ...;

    // 不是这个：series_of(first_task)->push_back(media_task);
    series_of(task)->push_back(media_task);
}
```

**Comment by holmes1412** [comment]
> 我目前主要是对线程池的使用有疑问，用户不需要去关心线程池的创建和初始化，但是当task执行结束之后，task的资源就被销毁了，那是不是连带着底层线程池的资源也被回收了？

计算线程池在第一计算task触发时才会创建，但是task结束之后，线程池资源还在，不会被回收。

**Comment by cloud-yd** [comment]
> 你好，这个地方传的参数应该callback当前的task，而不是first_task。崩溃应该是这个原因：
> 
> ```c++
> void captureCallBack(task)
> {
>     WFThreadTask<media_input_t, media_output_t> *media_task = ...;
> 
>     // 不是这个：series_of(first_task)->push_back(media_task);
>     series_of(task)->push_back(media_task);
> }
> ```

但是这个captureCallBack 是pcap的回调，不是workflow的回调，我需要把first_task传到captureCallBack 的参数里吗？

**Comment by cloud-yd** [comment]
> 你好。我们一切任务的生命周期，都是到callback结束。你这里的代码似乎不全，好几个callback都没有看到实现。不过原因应该是你的first task已经不存在了，你还去使用series_of(first_task)。应该是在每个 task的callback里，调用series_of(task)。

你好，请问如何实现在其他程序的异步回调中使用workflow的push_back，因为captureCallBack是pcap的回调

**Comment by Barenboim** [comment]
我大概知道你的意思了……

就是说，你的任务到达的时机很随机，可能是某个task结束之后一段时间，下一个task才会需要开始启动。这个时候，你还想push_back到原来的series里，所以，你就记得下first_task（或记得series）其后进行push_back。

这里的问题是，我们的series并不是堵塞的，series里的任务都结束，series就callback并且释放了。你好像是需要一个可以一直存在的series，可以在需要的时候push_back。

我们确实可以有一些办法让series变成堵塞模式，但我感觉你这个场景下并不是太需要。你的captureCallBack相当就是一次mediaRoutine的开始，你重新start一个series（或直接start一个media_task）就可以了。一个series代表一系列task，完成一个特定的任务。但在你这个应用里，你的完整任务就是media_task，没有必要一直用同一个series。

**Comment by cloud-yd** [comment]
> 我大概知道你的意思了……
> 
> 就是说，你的任务到达的时机很随机，可能是某个task结束之后一段时间，下一个task才会需要开始启动。这个时候，你还想push_back到原来的series里，所以，你就记得下first_task（或记得series）其后进行push_back。
> 
> 这里的问题是，我们的series并不是堵塞的，series里的任务都结束，series就callback并且释放了。你好像是需要一个可以一直存在的series，可以在需要的时候push_back。
> 
> 我们确实可以有一些办法让series变成堵塞模式，但我感觉你这个场景下并不是太需要。你的captureCallBack相当就是一次mediaRoutine的开始，你重新start一个series（或直接start一个media_task）就可以了。一个series代表一系列task，完成一个特定的任务。但在你这个应用里，你的完整任务就是media_task，没有必要一直用同一个series。

果然是大佬，表达 能力一流，我确实是希望有一个一直存在的serise，然后有数据的时候就触发任务的push_back。

还有一个问题因为我的captureCallBack 触发很频繁，每次回调我都使用media_task->start(); 不会有问题吗？如果不会对性能有影响的话，我就这样写了。

我之前只简单的看过你们的文档，我一直在纠结我只是使用了task，但是没有使用series，听你这么一说我对框架的设计有些理解了，有时间我得好好拜读下源码。

真的感谢！

**Comment by Barenboim** [comment]
只要你的计算任务不会太轻，这里start一个任务的开销可以忽略的。你可以实测一下性能。你这用法基本就是把我们当线程池了。

如果你的应用是一个server，有接收和回复的需要，那么我们的作用会更大一些。或者，你在你这个应用里，处理完之后需要发一个网络请求，那你就可以在mediaCallback里把一个网络任务（例如http）push_back到series里。

**Comment by cloud-yd** [comment]
> 只要你的计算任务不会太轻，这里start一个任务的开销可以忽略的。你可以实测一下性能。你这用法基本就是把我们当线程池了。
> 
> 如果你的应用是一个server，有接收和回复的需要，那么我们的作用会更大一些。或者，你在你这个应用里，处理完之后需要发一个网络请求，那你就可以在mediaCallback里把一个网络任务（例如http）push_back到series里。

因为刚刚接触到workflow，但是又手痒，所以先简单的使用了线程池和http请求、json这些东西。

我的task是解析各种协议，例如解析rtp，然后解码音频数据等等一系列操作

你说的很对，我现在确实需要在media_task后发起http请求。但是因为不熟悉，我把http请求写在了task里面，我待会就去改一下，在callback中使用series_of(media_task)->push_back(httptask);

学到了！

**Comment by Barenboim** [comment]
> > 只要你的计算任务不会太轻，这里start一个任务的开销可以忽略的。你可以实测一下性能。你这用法基本就是把我们当线程池了。
> > 如果你的应用是一个server，有接收和回复的需要，那么我们的作用会更大一些。或者，你在你这个应用里，处理完之后需要发一个网络请求，那你就可以在mediaCallback里把一个网络任务（例如http）push_back到series里。
> 
> 因为刚刚接触到workflow，但是又手痒，所以先简单的使用了线程池和http请求、json这些东西。
> 
> 我的task是解析各种协议，例如解析rtp，然后解码音频数据等等一系列操作
> 
> 你说的很对，我现在确实需要在media_task后发起http请求。但是因为不熟悉，我把http请求写在了task里面，我待会就去改一下，在callback中使用series_of(media_task)->push_back(httptask);
> 
> 学到了！

我们的目的是让算法和业务逻辑解耦。这样你的mediaRoutine就是一个从media input到output的纯算法了。算法结束之后干什么是业务逻辑的事，例如启动一个http请求。业务逻辑应该写在callback里。
