### ISSUE TITLE
MySQL客户端连接超时问题

### ISSUE THREAD

**Issue by SuKunlun** [sogou/workflow#1372]
你好，
我这边在产品测试环境中使用workflow作为MySQL客户端遇到一个连接超时的错误：
k3s pod的 容器内主进程中出现以下现象：

> 25号线程：
> 1694510275067（时间戳）
> 2023-09-12 17:17:55 执行mysql task（query）成功
> 1694510275068
> 2023-09-12 17:17:55 执行mysql task（query）
> 1694510285072
> 2023-09-12 17:18:05 任务超时，底层建立连接超时失败,task->get_error()返回110
> 
> 26号线程：
> 1694510282227
> 2023-09-12 17:18:02 执行mysql task（query）成功
> 1694510282228
> 2023-09-12 17:18:02 执行mysql task（query）
> 1694510292233
> 2023-09-12 17:18:12 任务超时，底层建立连接超时失败,task->get_error()返回110

说明三点：
1、连接超时参数我设置的是10s;
2、在这个时间段无其它线程创建执行mysql task;
3、代码实现方式与tutorial示例类似

从上面的执行流程可以看出：
1、25和26号线程执行成功的task应该是复用的已建立的连接
2、新建立的连接会超时，可能与MySQL服务器有关

我的问题是：
1、理论上25号线程第一个task执行成功后，第二次task会复用已经建立的连接，不知道这里为什么会新建连接？
2、如果与MySQL服务器无法建立连接，但原有已建立的连接是正常的，有什么办法能保证新建的task使用已建立的连接吗？

**Comment by Barenboim** [comment]
你好。如果你没有并发的去请求mysql，不管是哪个线程去发起任务，应该必须是一直只有一个连接，并且每次都会复用这个连接才对。哪怕你的mysql是一个域名，域名下多个IP地址，这种情况下依然会只有一个连接。

如果你一直两个并发，那也应该是一直两个连接，没有什么可能会建立第三个连接。

所以，我感觉你是不是什么地方并发数不小心上去了？

**Comment by Barenboim** [comment]
另外，我们的连接管理是FILO，即先进后出的机制。这种情况下，例如你有100个并发在访问mysql，那么，需要·的连接数很可能是90多个。那么，不排除某一时刻需要再建立一个连接。有没有可以这种情况引起？

**Comment by Barenboim** [comment]
你好，请问一下问题还存在吗？
@SuKunlun
