### ISSUE TITLE
http_proxy 处理 https请求的解决方案推荐

### ISSUE THREAD

**Issue by xx-zhang** [sogou/workflow#1376]
http_proxy 处理 https请求的解决方案推荐。
老师，请教一个问题。
就是类似这个的正向代理，我看行业是有个 mitmProxy/burpsuit 之类的工具，我想在这个 http_proxy 基础上完善出来一个 能够代理 https 的内容，有没有推荐的解决方案，处理这种 https-cert 之类的解包方法。

我已阅读和使用了 http_proxy, 卡在了这里
https://github.com/sogou/workflow/blob/master/tutorial/tutorial-05-http_proxy.cc#L88

**Comment by Barenboim** [comment]
https代理的原理不一样。你可以看看我们的http client任务，是可以用代理访问https的。但workflow本身做不了https代理服务器。

https代理其实就是一个转发，实现起来非常简单（你可以基于我们的poller模块实现）。收到一个CONNECT request之后建立一个连接，然后就互相转发就和可以了，都不用依赖SSL。

**Comment by Barenboim** [comment]
当然，你给我买tutorial里的代理发一个https URL，也是可以抓取并返回的。但不就都变成明文了吗。

**Comment by xx-zhang** [comment]
@Barenboim 好的，谢谢老师，我尝试结合您的描述操作一下

**Comment by xx-zhang** [comment]
> 当然，你给我们tutorial里的代理发一个https URL，也是可以抓取并返回的。但不就都变成明文了吗。

## 测试使用`http_proxy`代理
```
➜  cxxws git:(test) curl -x http://localhost:9980 https://www.qq.com  -v 
* About to connect() to proxy localhost port 9980 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9980 (#0)
* Establish HTTP proxy tunnel to www.qq.com:443
> CONNECT www.qq.com:443 HTTP/1.1
> Host: www.qq.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 404 Not Found
< Content-Length: 27
< Connection: Keep-Alive
< 
* Received HTTP code 404 from proxy after CONNECT
* Connection #0 to host localhost left intact
curl: (56) Received HTTP code 404 from proxy after CONNECT
```

## 代理控制台打印的信息

```
➜  tutorial ./http_proxy 9980 
www.qq.com:443: Fetch failed. state = 67, error = 1002: URL error (Cannot be a HTTPS proxy)

```

**Comment by Barenboim** [comment]
我的意思是，以http代理的格式发请求，是可以转发https的结果的。请求格式如下：
~~~
GET https://www.sogou.com/ HTTP/1.1
Host: www.sogou.com
...
~~~
这样是能转发https的首页的。但这不是https代理的格式，因为client到proxy之前的数据是明文，但你在内网里做个中转服务器没问题。

**Comment by actanble** [comment]
@Barenboim hi，我想做到的不仅仅是转发，如果是 mitm(Man-in-the-middle )效果，能够过滤出https的流量并且能够进行篡改转发，这种有没有推荐的方案，就是已有的源代码，简单改下就可以，我准备参考下 mitmproxy 但是现在结构比较臃肿，改动繁琐，看看老师又没有推荐的

**Comment by Barenboim** [comment]
> @Barenboim hi，我想做到的不仅仅是转发，如果是 mitm(Man-in-the-middle )效果，能够过滤出https的流量并且能够进行篡改转发，这种有没有推荐的方案，就是已有的源代码，简单改下就可以，我准备参考下 mitmproxy 但是现在结构比较臃肿，改动繁琐，看看老师又没有推荐的

这种情况下，你首先需要一个假的证书吧？然后client侧不进行证书的验证，否则你也不可能进行篡改。
其实要实现这个功能并不难，但用不了workflow整体框架。你需要直接使用底层poller模块。你可以用这个模块先写几个小程序试试。
