### ISSUE TITLE
有没有办法使用 workflow + dpdk 来加速并行wget的速度

### ISSUE THREAD

**Issue by xx-zhang** [sogou/workflow#1380]
老师可以给出一个可行的方法么

dpdk 网卡数据包绕过内核的加速 + workflow。 两者是否有结合的可能。如果有可以有什么样的思路。当前我咨询的角度，对于client的刚需大一点。

**Comment by Barenboim** [comment]
根本没必要搞dpdk。大多数应用瓶颈不在这。

**Comment by xx-zhang** [comment]
好的，多谢

**Comment by xx-zhang** [comment]
@Barenboim 老师，我紧接着问一个问题，我要是基于workflow做一个扫描器，比如嗅探服务端口有没有开放的这个，或者直接是测试有没有http服务开放的，建议用这个，还是建议用现有的一些成熟的方案，也就是说我们的检测速度会比他们现有的（多线程）要慢吗，还是说可能咱们的 series_task 并不会和  muti_thread 拉开差距。

**Comment by Barenboim** [comment]
如果你说的只有端口扫描，那么workflow肯定不是最快的，我们需要正常的发起tcp连接，并发送请求。而专门的端口扫描，是直接通过raw socket来发tcp sync包的，肯定比这个快。
如果你用workflow来做端口扫描，可以正常构造网络请求，但把receive_timeout设置为0。在callback里，看看timeout的原因(task->get_timeout_reason)是connect还是transmit，就知道端口连上了没有。比你自己写个多线程connect肯定快得多。

**Comment by xx-zhang** [comment]
@Barenboim 多谢答疑
