### ISSUE TITLE
关于跨域时 shareArrayBuffer报错的问题

### ISSUE THREAD

**Issue by whynogo** [sogou/workflow#1386]
问题求救！使用windows版本workflow，开发时一直使用127.0.0,1来访问服务器，直到开发完成开始部署时，发现在本机使用127.0.0.1访问正常,但是从使用其它IP访问时则出现跨域提示（为此只能使用https nginx代理，但是请求速度下降很大），问是否有办法可以在服务器端设置解决此问题：可以使用http访问避免跨域提示？
![image](https://github.com/sogou/workflow/assets/8939744/4a3fba2b-16ad-4081-8c3f-dd9baa71e339)

**Comment by whynogo** [comment]
response已加如下header：resp->add_header_pair("Cross-Origin-Embedder-Policy", "require-corp");
			resp->add_header_pair("Cross-Origin-Opener-Policy", "same-origin");
			resp->add_header_pair("Access-Control-Allow-Origin", "*");
			resp->add_header_pair("Access-Control-Allow-Credentials", "true");
			resp->add_header_pair("Access-Control-Allow-Methods", "POST, GET, OPTIONS, DELETE, PUT");
			resp->add_header_pair("Access-Control-Max-Age", "120");

**Comment by Barenboim** [comment]
你好。请问一下，这个问题是不是只和http协议有关系？如果是这样，应该是加一些header可以解决吧？

**Comment by whynogo** [comment]
> 你好。请问一下，这个问题是不是只和http协议有关系？如果是这样，应该是加一些header可以解决吧？

查阅了资料后，已经加了上述的大量header，解决了在https的使用的问题，但是没有解决在http下的问题。主要想法就是不使用https，而使用除了127.0.0.1 的ip进行访问而不出现跨域的问题，还有其它header可以使用吗？

**Comment by Barenboim** [comment]
这个问题，我们也不懂……看看不能不能群里问题一下？

**Comment by Barenboim** [comment]
你好，目前找到解决方案了吗？
