### ISSUE TITLE
压力测试时程序崩溃

### ISSUE THREAD

**Issue by taazzj** [sogou/workflow#1391]
代码如下
~~~cpp
#include <iostream>
#include "workflow/HttpMessage.h"
#include "workflow/HttpUtil.h"
#include "workflow/WFServer.h"
#include "workflow/WFHttpServer.h"
#include "workflow/WFFacilities.h"

using namespace std;
using namespace protocol;


int main()
{
    WFHttpServer *m_http = new WFHttpServer([=](WFHttpTask *server_task){
        HttpResponse *resp = server_task->get_resp();

        std::string myString(1024*1024*2, '\0');

        std::cout << "resp" << std::endl;

        resp->append_output_body(myString);
    });

    if (m_http->start(8888) == 0)
    {
        getchar(); 
        m_http->stop();
    }

    return 0;
}

~~~
![image](https://github.com/sogou/workflow/assets/136426142/9a668c49-3787-4d44-9b9d-281191577e4d)

debug模式启动，使用apipost做压力测试时会崩溃

**Comment by Barenboim** [comment]
代码里是有禁止SIGPIPE的啊，按理不会出现broken pipe。
https://github.com/sogou/workflow/blob/5a458723469d22667ca0b0fc5a1f6e51f9453cd4/src/manager/WFGlobal.cc#L351
好像之前也有人报过broken pipe，是否肯设置不成功？你在release模式下会有问题吗？

**Comment by Barenboim** [comment]
麻烦在signal(SIGPIPE, SIG_IGN)这里打印一下返回值吧，debug模式下。看看是不是设置不成功。

**Comment by taazzj** [comment]
> 麻烦在signal(SIGPIPE, SIG_IGN)这里打印一下返回值吧，debug模式下。看看是不是设置不成功。

设置成功了，我单独设置了一个捕获信号的函数，依然会崩溃

**Comment by taazzj** [comment]
> 麻烦在signal(SIGPIPE, SIG_IGN)这里打印一下返回值吧，debug模式下。看看是不是设置不成功。

你们可以测试一下吗，很好复现，我看到有2021年Issues同样情况，没有看到解决结果

**Comment by Barenboim** [comment]
> > 麻烦在signal(SIGPIPE, SIG_IGN)这里打印一下返回值吧，debug模式下。看看是不是设置不成功。
> 
> 你们可以测试一下吗，很好复现，我看到有2021年Issues同样情况，没有看到解决结果

我们肯定是测试过无数遍的，而且这是线上产品啊。
我感觉是环境的问题，比如是不是安装过两个版本，导致头文件不一致？broken pipe只能是收到SIGPIPE了，你崩溃前的SIGPIPE没有捕捉到吗？

**Comment by Barenboim** [comment]
我们试了一下，如果在gdb里运行是会broken pipe的。gdb好像会修改信号处理函数。
是不是你的调试器也会有类似的行为？

**Comment by kedixa** [comment]
https://www.cnblogs.com/mingzhang/p/11864808.html

**Comment by kedixa** [comment]
```cpp
#include <csignal>
using namespace std;

int main() {
    std::signal(SIGPIPE, SIG_IGN);
    std::raise(SIGPIPE);
    return 0;
}
```

```bash
g++ a.cpp -o a.out
gdb ./a.out # will SIGPIPE
```

```bash
(gdb) handle SIGPIPE nostop noprint
Signal        Stop      Print   Pass to program Description
SIGPIPE       No        No      Yes             Broken pipe
(gdb) r
Starting program: /a.out 
[Inferior 1 (process 1) exited normally]
```

**Comment by taazzj** [comment]
> 我们试了一下，如果在gdb里运行是会broken pipe的。gdb好像会修改信号处理函数。 是不是你的调试器也会有类似的行为？

**Comment by taazzj** [comment]
> 我们试了一下，如果在gdb里运行是会broken pipe的。gdb好像会修改信号处理函数。 是不是你的调试器也会有类似的行为？

是的，我的调试器本质上也是gdb，已经解决了。添加handle SIGPIPE nostop noprint，有效

**Comment by Barenboim** [comment]
> > 我们试了一下，如果在gdb里运行是会broken pipe的。gdb好像会修改信号处理函数。 是不是你的调试器也会有类似的行为？
> 
> 是的，我的调试器本质上也是gdb，已经解决了。添加handle SIGPIPE nostop noprint，有效

好咧！感谢报问题。

**Comment by taazzj** [comment]
> https://www.cnblogs.com/mingzhang/p/11864808.html

感谢，设置handle SIGPIPE nostop noprint有效
