### ISSUE TITLE
一些重要更新

### ISSUE THREAD

**Issue by Barenboim** [sogou/workflow#1392]
在用户需求的推动下，workflow项目近期进行了多次更新，并加入了一些新特征。目前master分支版本号升级到0.11.1。主要改动如下：

#### 1、带超时的计算任务状态码修改

通过create_timedgo_task或create_thread_task指定执行时限产生的计算任务，在任务超时时，状态码由原来的WFT_STATE_ABORTED，改为WFT_STATE_SYS_ERROR且错误码为ETIMEDOUT。这个更新可能导致一些原来通过判读ABORTED状态的代码会出现问题。建议判断超时的代码改为：
~~~cpp
void callback(WFGoTask *task)
{
    if (task->get_state() != WFT_STATE_SUCCESS)
    {
        // handle timeout
    }
}
~~~
通过判断状态码是为SUCCESS来确定任务正常完成，如果不为SUCCESS即为超时，可以兼容新旧代码。对于这个修改引起状态不一致的问题，我们深表歉意。这么修改是为了让用户可以区分计算任务超时和程序退出导致计算任务未运行。如果是后一种情况，任务依然将得到WFT_STATE_ABORTED状态。

#### 2、新增支持取消的定时器

可取消的定时器一直被认为是一个重新功能，从项目开源一直期待可以实现，之前我们尝试了一些方法都不太满意。我们最近代码解决了几个关键技术难题，终于实现了这个功能。目前定时器的主要接口如下：
~~~cpp
class WFTaskFactory
{
public:
    static WFTimerTask *create_timer_task(time_t seconds, long nanoseconds,
                                          timer_callback_t callback);

    /* create a named timer. */
    static WFTimerTask *create_timer_task(const std::string& timer_name,
                                          time_t seconds, long nanoseconds,
                                          timer_callback_t callback);

    /* cancel all timers under the name. */
    static void cancel_by_name(const std::string& timer_name)
    {
        WFTaskFactory::cancel_by_name(timer_name, (size_t)-1); 
    }

    /* cancel at most 'max' timers under the name. */
    static void cancel_by_name(const std::string& timer_name, size_t max);

    /* timer in microseconds (deprecated) */
    static WFTimerTask *create_timer_task(unsigned int microseconds,
                                          timer_callback_t callback);
};
~~~
其中，新增带timer_name的接口，产生一个命名timer，可以通过cancel_by_name操作进行取消。如果取消成功，timer task在callback里将得到WFT_STATE_SYS_ERROR状态且错误码为ECANCELED。请注意，如果多个timer同名，cancel_by_name操作将取消这个名称下的所有timer。用户也可以通过带max的接口，取消带上限个数的timer。

命名timer在被创建开始，就可以被cancel_by_name取消，而不用等实际启动之后。这种情况下，timer启动后会立刻结束，并以取消状态在网络线程被callback。

需要注意的是，命名timer相比普通的timer是有一些多余开销的，包括启动和结束时增加的锁操作。因此，如果没有取消的需求，不要给timer命名。另外，任何timer都可以被程序退出打断，返回WFT_STATE_ABORTED状态。

timer将统一以seconds+nanoseconds作为参数，以microseconds为参数的timer进入废弃状态，且不可命名。

#### 3、Kafka client支持TLS传输

Kafka client终于完成了对SSL的支持。只需要在初始化kafka client时，以**kafkas://** 作为URL前缀，即可实现TLS传输。一般大多数开放在外网的kafka broker，都会要求以 TLS加密传输。

由于我们的kafka client支持多URL初始化（多个borker），因此我们要求这些URL要么全都为SSL，要么全都是普通TCP，否则初始化操作会失败（scheme缺省时为普通TCP），errno被设置为EINVAL。**kafkas://** 前缀的URL，默认端口为9093。

至此，我们所有的内置协议，dns，http，redis，mysql和kafka全部支持了SSL，只需要在URL的scheme里加上's'，就是以TLS传输了。

#### 4、新增一个异步回复的辅助类

我们发现关于异步server的实现，很多用户采用了错误的方法。我们以一个延迟1秒返回的http server为例。

**最正确的写法是：**
~~~cpp
/* Right way. */
void process(WFHttpTask *server_task)
{
    server_task->get_resp()->append_output_body("<html>Hello World!</html>");
    series_of(server_task)->push_back(WFTaskFactory::create_timer_task(1, 0, nullptr));
}
~~~
因为我们返回的时机是server task所在series被清空，而不是process函结束。所以只需要把一个timer push_back到series末尾就可以了，而不是下面这种**错误写法：**
~~~cpp
/* Wrong way!!! */
void process(WFHttpTask *server_task)
{
    server_task->get_resp()->append_output_body("<html>Hello World!</html>");
    WFFacilities::WaitGroup wg(1);
    WFTimerTask *timer = WFTaskFactory::create_timer_task(1, 0, [&wg](WFTimerTask *){
        wg.done();
    });
    timer->start();
    wg.wait();
}
~~~
为了让一些不想接触到series的用户也可以高效的实现异步server，我们加入了WFFacilities::ReplyGuard组件，支持通过guard的方法来控制回复时机，方法如下：
~~~cpp
/* Altanative way. */
void process(WFHttpTask *server_task)
{
    server_task->get_resp()->append_output_body("<html>Hello World!</html>");
    auto *guard = new WFFacilities::ReplyGuard(server_task);
    WFTimerTask *timer = WFTaskFactory::create_timer_task(1, 0, [guard](WFTimerTask *){
        delete guard;
    });
    timer->start();
}
~~~
通过一个guard保护server_task的回复行为，在需要回复的时刻删除guard就可以手动控制回复时机了。在使用时，也可以用std::unique_ptr的方式来控制guard生命周期。

注意一点，使用ReplyGuard时，**不要再使用server task series的cancel操作**，即不要使用series_of(server_task)->cancel()，这两个操作无法完全兼容。不过一般使用ReplyGuard，已经说明了放弃对这个series的使用了。

**Comment by BugTan** [comment]
windows分支能更新一下么

**Comment by Barenboim** [comment]
> windows分支能更新一下么

Windows的代码不太会改😥 
外网代码是一样的，但核心里有个计时器需要实现一下取消。
