### ISSUE TITLE
win10环境下，使用cmake+vcpkg引入workflow，报出错误，如何解决

### ISSUE THREAD

**Issue by jacob-zhang-213** [sogou/workflow#1394]
`[build] workflow.lib(RouteManager.cc.obj) : error LNK2001: 无法解析的外部符号 __imp_socket [D:\testCode\cmakeandvcpkg\build\main.vcxproj]
[build] main.obj : error LNK2001: 无法解析的外部符号 __imp_socket [D:\testCode\cmakeandvcpkg\build\main.vcxproj]`

cmake检查引入包时是没什么问题的，但是在`build`的过程中报出LNK2001、LNK2019的错误，我查了相关博客，但是并没有找到解决方案，请各位大佬答疑解惑

**Comment by xiaohuistyle** [comment]
![1697426448652](https://github.com/sogou/workflow/assets/22876641/b9d8f534-ba7a-4766-9173-a14a5a13420b)

**Comment by Barenboim** [comment]
看起来是个SSL的问题？是不是没有安装OpenSSL？

**Comment by jacob-zhang-213** [comment]
> 看起来是个SSL的问题？是不是没有安装OpenSSL
安装了，并且加了系统变量
![image](https://github.com/sogou/workflow/assets/22876641/4ffeb441-601b-4236-a9ae-3d60bee6421c)

**Comment by jacob-zhang-213** [comment]
> 看起来是个SSL的问题？是不是没有安装OpenSSL？

有可能是哪里引发的问题呢？

**Comment by Barenboim** [comment]
@dengjun101 能不能帮忙看看这个编译问题？

**Comment by dengjun101** [comment]
> > 看起来是个SSL的问题？是不是没有安装OpenSSL
> 
> 安装了，并且加了系统变量 ![image](https://user-images.githubusercontent.com/22876641/275681722-4ffeb441-601b-4236-a9ae-3d60bee6421c.png)

需要看一下你编译的是X86的工程还是X64的工程，从截图看本地安装的是X64版本的openssl，如果编译的是X86的话会出现链接错误。可以直接使用vcpkg的openssl

**Comment by jacob-zhang-213** [comment]
> > > 看起来是个SSL的问题？是不是没有安装OpenSSL
> > 
> > 
> > 安装了，并且加了系统变量 ![image](https://user-images.githubusercontent.com/22876641/275681722-4ffeb441-601b-4236-a9ae-3d60bee6421c.png)
> 
> 需要看一下你编译的是X86的工程还是X64的工程，从截图看本地安装的是X64版本的openssl，如果编译的是X86的话会出现链接错误。可以直接使用vcpkg的openssl

![image](https://github.com/sogou/workflow/assets/22876641/c1485abf-cdc6-4b42-b837-57a3c80dc401)
我就是编译x64工程，本地安装的也是x64的openssl，我看一篇博客说了这个事，专门换了openssl

**Comment by jacob-zhang-213** [comment]
> @jacob-zhang-213 要不群里求助一下？群里Windows用户很多。

哪里有群？

**Comment by holmes1412** [comment]
可以加workflow用户qq群～ 618773193

**Comment by Barenboim** [comment]
@jacob-zhang-213 你好，找到解决方法了？
