### ISSUE TITLE
接口解析报错

### ISSUE THREAD

**Issue by yk0211** [sogou/workflow#1400]
WFMySQLConnection::init  解析mysql://root:123456@@@127.0.0.1:3306/db_test?character_set=utf8mb4报错，其中mysql密码是123456@@

**Comment by Barenboim** [comment]
URL里的密码部分，如果有特殊字符需要用StringUtil::url_encode_component()编码一下。参考：https://github.com/sogou/workflow/issues/1310

**Comment by Barenboim** [comment]
你确定需要用到WFMySQLConnection么？一般直接WFTaskFactory::create_mysql_task就可以。connection用在事务上多一些。

**Comment by yk0211** [comment]
> URL里的密码部分，如果有特殊字符需要用StringUtil::url_encode_component()编码一下。参考：#1310



> 你确定需要用到WFMySQLConnection么？一般直接WFTaskFactory::create_mysql_task就可以。connection用在事务上多一些。

需要与mysql建立长连接，避免每次都创建连接。还有一个问题就是，mysql server在达到空闲时间（wait_timeout）默认是8h未处理任何请求时，会主动关闭连接，不知道设置设置keep_alive会不会有效。

**Comment by Barenboim** [comment]
啊，你用WFTaskFactory创建的任务，也是默认长链接的啊。我们所有协议都是一个原理，都有连接池的管理的。
MySQL连接默认keep alive实际好像是3分钟，你可以改。用WFMySQLConnection创建的mysql任务，默认keep alive为一小时，也可以改。

**Comment by Barenboim** [comment]
@yk0211 这个先关了，还有疑问的话重新打开。
