### ISSUE TITLE
请教下怎么优雅的和paho mqtt一起使用收发mqtt信息？

### ISSUE THREAD

**Issue by boboxxd** [sogou/workflow#1402]
用go task和 counter task封装的话，就是我没想到怎么处理对方主动发送的信息的场景

**Comment by boboxxd** [comment]
用go task和 counter task封装的话，就是我没想到怎么处理对方主动发送的信息的场景

**Comment by Barenboim** [comment]
你好。我感觉你用go task的方法有点问题。go task是计算线程，最好不要在我们的计算线程里等东西。如果你用一个第三方的网络通信模块（怪我们实现不了MQTT），不要用我们的线程池来调用会好一些。

对于对方主动发送的场景，只需要在收到对方数据时启动workflow的任务或打开counter就可以了吧？和主动发送再等回复，好像没有什么本质区别。但记得最好有自己的线程池。

**Comment by boboxxd** [comment]
你好，我已收到你的邮件，我会尽快回复的

**Comment by Barenboim** [comment]
> 那应该在哪一层做这个操作，我看了demo,没找到差不多的场景，不知道哪里着手

不好意思，前两天没有看到你后面这个回复。

我不熟悉你的这个mqtt的接口。但我感觉一般网络库有两种用法。一种是它本身有一个线程池，在收到消息时执行你的回调。如果是这种类型，你就在收到消息时正常执行我们的任务就可以了。

另外一种，用户需要有自己的线程，在线程里等待它的消息到达。对于这种情况，注意不要使用workflow的计算线程等待就可以了，最好是有一个你自己的线程池，用于等待mqtt的消息，然后收到消息是，执行workflow任务或者和counter交互。

无论是哪一种，其实都是可以把你的异步任务+counter任务，变成一个workflow的任务。/

**Comment by Barenboim** [comment]
@boboxxd

**Comment by boboxxd** [comment]
你好，我已收到你的邮件，我会尽快回复的
