### ISSUE TITLE
Go Task使用

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#1403]
在go task函数中，创建新的http任务，如何保证创建的http请求结束后再执行go task函数后面语句，因为go task函数可能要用到http请求中的数据？

**Comment by Barenboim** [comment]
你好。这个是个好问题。
你的应用模型大概是这样吧：
~~~cpp
int f()
{
    while (...) {
        resp = http_get(...);
        process(resp);    // 重计算
    }
}
~~~
这种计算->IO->计算的模式，用原生workflow最高效的方法，只能是循环的push_back计算任务和通信任务。注意不可以在计算任务里等待IO结束，否则会占用一个计算线程。

为了降低任务之间的耦合，你可以用WFModuleTask把上面整个过程封装成一个module，外部直接得到module的结果就可以了。关于module，可以看这个文档：https://github.com/sogou/workflow/blob/master/docs/about-module.md

另外，workflow的协程封装项目[Coke](https://github.com/kedixa/coke)，可以直接用同步的方式实现上面的效果。不过需要使用C++20。

**Comment by HzjFirst** [comment]
好的，收到了，谢谢，我看一下如何使用
