### ISSUE TITLE
有关SSL_CTX

### ISSUE THREAD

**Issue by IYinxf** [sogou/workflow#1408]
1、当服务的SSL证书不是根证时，如何设置根证书；
2、如何使用有密码的私钥文件；

以上，我需要重写new_ssl_ctx的实现吗，调试代码发现似乎无法外部设置

**Comment by Barenboim** [comment]
这是两个问题，需要分别实现两个虚函数。
1、不同的Host使用不同的证书，需要派生重写get_server_ssl_ctx()函数。这个函数传给你一个server name，你返回对应的SSL_CTX。认证信息填这里面。
2、设置全局证书的私钥，需要派生new_ssl_ctx()函数。可以先调用父类的new_ssl_ctx，然后自己加认证信息。

**Comment by Barenboim** [comment]
通过get_server_ssl_ctx()产生的证书，退出后需要里自己释放。new_ssl_ctx()因为有默认实现，这个证书是server本身管理，server退出是，内部会自动释放。

**Comment by IYinxf** [comment]
好的 感谢
