### ISSUE TITLE
请问server如何主动向client发送消息

### ISSUE THREAD

**Issue by qiqiqiren** [sogou/workflow#1412]
您好，我现在是使用了自定义协议，并使用了长链接模式。
server端在处理一次client发来的请求后，会存有与该client的Connection，那么当server需要向该client发送消息时该怎么做呀？

**Comment by Barenboim** [comment]
我们建议的方法，是双方都是client/server。其实我们天生是actor模式，节点之间是对等的。需要接受消息的一方，就开一个server就好了。

另外一种方法是使用server task的push接口，这个可以实现http协议的SSE模式，这也是一种很常用的http推送方式。不过，可能你的需求更加复杂，建议用第一种方式。

**Comment by qiqiqiren** [comment]
好的，感谢回复。 (^v^)

**Comment by Barenboim** [comment]
第一个模式可以满足你的需求么？我们确实做不到在一个连接上相互调用，这种方式会带来一些其它的问题，也会让系统别得更复杂。

**Comment by qiqiqiren** [comment]
我们的原始需求是一个server对应几千个client，这几个client是在同一台机器上面，这样就会多占用几千个端口。
现在在考虑尝试用第二种模式去实现。

**Comment by Barenboim** [comment]
> 我们的原始需求是一个server对应几千个client，这几个client是在同一台机器上面，这样就会多占用几千个端口。 现在在考虑尝试用第二种模式去实现。

我们的server启动是可以分配随机端口的哈（port传0），随机端口分配范围是32768-65535。然后用server->get_listen_addr()获得监听地址。
另外，如果你的client和server运行在同一个机器上，也可以使用unix domain proxy通讯，无需占用端口。

**Comment by qiqiqiren** [comment]
我们确实有client和server运行在同一个机器上的情况，感谢您的建议。（^v^）

**Comment by kedixa** [comment]
我刚好在想如何使用当前的模式实现一个全局资源管理器，具体场景是：某个后台服务被数个等价的调用方调用，如果客户端不加任何限制地请求，很可能把服务打挂，全局资源管理器可以在客户端增减时计算出一个数值，提示客户端友好地使用资源。这个场景类似于有数千个客户端访问服务器，并有服务器主动发消息的需求。
我的一个想法是服务端维护一个消息队列，客户端维护一个心跳连接，心跳发出后，服务端检查是否有待发消息，如果一段时间内（比如5秒）没有任何需要发送的，则返回一个没有消息的状态，否则立刻返回消息。心跳消息返回后，客户端需立刻发起下一次心跳。
这样可以保证任何一条消息至多在1.5个RTT内推送到客户端，在不严格的场景下可以接受。且不显著增加连接数开销，也无需将协议解析与业务逻辑耦合。

**Comment by qiqiqiren** [comment]
我之前也考虑过这种方式，但我当时的想法这样会阻塞网络线程。
我想workflow是不是有某种类型的Task，server在process里能保留当前的client请求，在需要的时候再将其返回。

**Comment by Barenboim** [comment]
> 我之前也考虑过这种方式，但我当时的想法这样会阻塞网络线程。 我想workflow是不是有某种类型的Task，server在process里能保留当前的client请求，在需要的时候再将其返回。

当然有了。 WFCounterTask或WFMailboxTask都可以用来做这个事情。类似于用一个塞子把 series堵住，回复的时候打开。然后甚至可以给这个塞子命名，用名称来打开。

**Comment by qiqiqiren** [comment]
那太棒了，我想这正是我想要的。

**Comment by qiqiqiren** [comment]
请问下我在调试时`Connection timed out`，看起来是遇到了连接超时的问题

这是我Server端process的简要实现
```
void SwapCallServer::newConnection(NetworkTask *task)
{
    NetworkRequest *req     = task->get_req();
    NetworkResponse *resp   = task->get_resp();
    void *body;
    size_t size;

    {
        WFCounterTask *counter = WFTaskFactory::create_counter_task(1, nullptr);
        *series_of(task) << counter;
    }
}
```

Server端我设置了如下配置
```
struct WFServerParams params = SERVER_PARAMS_DEFAULT;
params.request_size_limit = 4 * 1024;
params.keep_alive_timeout = -1;
```

这是我Client端process的简要实现
```
task = NTF::create_client_task(TT_TCP, m_host, m_port, 0, std::move(callback));
task->set_keep_alive(-1);
char buf[1024];
strcpy(buf, data.c_str());
size_t body_size = strlen(buf);

task->get_req()->setMessageBody(buf, body_size);
task->get_resp()->set_size_limit(4 * 1024);
task->start();
```

我的本意是想让服务端长时间保留该Client的请求，在需要时才返回

**Comment by Barenboim** [comment]
这个是client侧超时了。client超时，主要是全局response_timeout默认为5秒的原因。response_timeout代表每次成功发送或接收一块数据的超时。server的第一个返回包，也受到这个超时的限制。

你可以修改全局的response timeout。不过，有个更好的方法。你不是自定义协议的吗，可以重写client任务的first_timeout方法，这是client收到server第一个包的超时，可以理解为watch超时。方法是：
~~~cpp
class MyClientTask : public WFComplexClientTask<MyRequest, MyResponse>
{
protected:
    int first_timeout() override { return 60 * 1000; }  // 第一个包超时为一分钟。
};

class MyFactory
{
    static WFNetworkTask<MyRequest, MyResponse> *create_my_task(..., my_callback_t callback)
    {
        return new MyClientTask(..., std::move(callback));
    }
};
~~~

**Comment by qiqiqiren** [comment]
感谢大佬，我试了一下确实可以了。我还有问题想要请教一下：

- client端在一个网络task任务结束后，重新再实例化一个网络task去请求同一个server端，底层是否会复用原有的连接
        - 若是复用原有的连接，那我想要在该连接之外，新起一个对该服务的连接的话，我该怎么做
        - 若不是复用原有的连接，那我该如何做才能复用原有的连接

**Comment by Barenboim** [comment]
连接复用很智能的。如果你的连接都是无状态的，你正常用就可以了。只有keep_alive_timeout不为0（自定义协议，默认的keep_alive_timeout是0，需要创建完任务之后设置一下），都是可能复用的。

你在callback里重写启动一个任务（包括push_back或直接start），是会复用之前的连接的。如果没有连接可用就会新发起一个。一般使用的时候无需关心这些。

**Comment by qiqiqiren** [comment]
好的，感谢回复。
