### ISSUE TITLE
在Windows上WFHttpsServer处理业务时崩溃

### ISSUE THREAD

**Issue by IYinxf** [sogou/workflow#1413]
openssl用的是3.1.2

我继承了WFHttpsServer并重写new_ssl_ctx
`
SSL_CTX *HttpsServer::new_ssl_ctx(const char *cert_file, const char *key_file) {
  (void) cert_file;
  (void) key_file;
  SSL_CTX *ssl_ctx = WFGlobal::new_ssl_server_ctx();

  if (!ssl_ctx)
    return nullptr;

  SSL_CTX_set_default_passwd_cb(ssl_ctx, passwordCallback);
  if (SSL_CTX_load_verify_locations(ssl_ctx, ca_file_.c_str(), nullptr) > 0 &&
      SSL_CTX_set_default_verify_paths(ssl_ctx) > 0 &&
      SSL_CTX_use_certificate_file(ssl_ctx, cert_file_.c_str(), SSL_FILETYPE_PEM) > 0 &&
      SSL_CTX_use_PrivateKey_file(ssl_ctx, key_file_.c_str(), SSL_FILETYPE_PEM) > 0 &&
      SSL_CTX_set_tlsext_servername_callback(ssl_ctx, ssl_ctx_callback) > 0 &&
      SSL_CTX_set_tlsext_servername_arg(ssl_ctx, this) > 0) {
    return ssl_ctx;
  }

  SSL_CTX_free(ssl_ctx);
  return nullptr;
}
`

业务是读取文件，Content-Type:application/pdf; charset=UTF-8，每次业务读取文件的一部分，所以大文件会发比较多请求
请求了若干次之后会出现崩溃

在windows可以看到堆栈信息，但linux上表现相同 继承的是WFHttpServer ，linux没有获取堆栈信息

windows堆栈信息如下
![12](https://github.com/sogou/workflow/assets/28833325/ae547852-e62c-4b84-a4e9-a3939605135c)

**Comment by Barenboim** [comment]
你好。是说linux上也会崩？linux和windows在https server上的实现完全不一样，可以看看linux崩在什么地方吗。

**Comment by IYinxf** [comment]
> 你好。是说linux上衍生崩溃吗？linux和windows在https服务器上的实现完全不一样，可以看看linux崩溃在什么地方吗。

您好，稍等我正在减少代码定位是否是我自己报文处理有误，刚刚测试发现不仅是读文件的请求会崩溃，其他请求手动多触发几次也会崩溃

**Comment by Barenboim** [comment]
嗯嗯，不急。我看了一下这个堆栈是在握手阶段，堆栈信息有点奇怪。https server在Windows和linux实现原理差别巨大，同样原理崩溃有点不太可能。

**Comment by IYinxf** [comment]
> 嗯嗯，不急。我看这个堆栈是在握手阶段，堆栈信息有点奇怪。https 服务器在 Windows 和 linux 实现原理差别巨大，同样原理崩溃不太可能。

我也在考虑这个问题，目前我定位到在响应头中设置参数后，会导致崩溃，我再逐个排查一下

**Comment by IYinxf** [comment]
收集了linux的堆栈
![13](https://github.com/sogou/workflow/assets/28833325/b95c3005-ba08-4126-939c-f9e76d46b1b9)

**Comment by Barenboim** [comment]
像是内存被写坏了，可能是哪里有越界访问。可以贴一下部分源代码。
或者，试一试不加认证是否有问题。理论上，我们的https server应该不会这么容易挂。

**Comment by IYinxf** [comment]
我需要在处理http task的函数里加锁吗

**Comment by Barenboim** [comment]
加锁保护什么信息呢？一般来讲处理http task的函数要么是create之后运行之前，要么是callback里。这时候不太可能会有人需要争抢。

当然我们的req，resp这种东西，是不能并发操作的。毕竟只是一个数据容器。如果你需要并发的操作req，resp，是需要加锁的。

**Comment by Barenboim** [comment]
你是server，所以是指process过程吧？如果你让两个并发任务操作task，需要加锁的。

**Comment by IYinxf** [comment]
未能解决

**Comment by Barenboim** [comment]
> 未能解决

啊啊，有没有什么发现？去掉认证可以吗？不派生new_ssl_ctx，也有相同的问题吗。
