### ISSUE TITLE
自定义协议TCP客户端可以主动断开连接吗？

### ISSUE THREAD

**Issue by QidongLi** [sogou/workflow#1415]
我尝试在客户端调用task->noreply()断开与服务端的连接，但没有成功；但我在服务端调用task->noreply()时，则可断开与客户端的连接，请问是有其他方法使客户端主动断开与服务端的连接吗？而不是通过等待超时的方式

**Comment by Barenboim** [comment]
我们的WFMySQLConnection的create_disconnect_task()其实就是你这个需求，不得已发送了一个空请求来关闭连接。

**Comment by QidongLi** [comment]
也就是说，如果TCP客户端要主动断开连接，需要像WFMySQLConnection实现一个create_disconnect_task()吗？主动断开连接的场景还是有的，不知道workflow后面能否加上这个功能

**Comment by Barenboim** [comment]
Mysql connection比较特殊吧，因为只有一个连接。你的client任务是连接池，你是想断开全部连接？

**Comment by QidongLi** [comment]
client任务没有用到连接池，只在需要的时候create一个client任务而已。在传输数据过程中，有时候因其他原因需要断开连接，进行重传，才发现workflow没有API主动断开连接

**Comment by Barenboim** [comment]
我思考一下这个问题。

如果你可以提前知道本次传输之后需要断开连接，倒是可以先set_keep_alive(0)。

不过看上去你是在得到结果之后才知道要断开。

**Comment by Barenboim** [comment]
想起来了……你这个不就是相当于我们的http协议看到connection: close就不保持连接吗？有非常标准的方法。
~~~cpp
class MyClientTask : public WFComplexClientTask<MyRequest, MyResponse>
{
protected:
    int keep_alive_timeout() override
    {
        MyResponse *resp = this->get_resp();
        if (...)
            return KEEP_ALIVE_DEFAULT;
        else
           return 0;    // 短连接
    }
}
~~~
可以参数一下：https://github.com/sogou/workflow/blob/d0e0320adb49f435a567bb6a12f8c5366a22f0a1/src/factory/HttpTaskImpl.cc#L169
然后自己找个factory，new这个类就可以了。

**Comment by Barenboim** [comment]
factory的接口长这样：
~~~cpp
using my_callback_t = std::function<void (WFNetworkTask<MyRequest, MyResponse> *)>;

class MyFactory
{
    WFNetworkTask<MyRequest, MyResponse> *create_my_task(..., my_callback_t callback);
    {
        new MyClientTask(.., std::move(callback));
    }
};
~~~

**Comment by QidongLi** [comment]
非常感谢Barenboim，代码已经可以正常断开连接了；但有一个问题是，如果在其他项目也需要用到这个功能，都需要自己重新实现一遍，岂不是很麻烦

**Comment by Barenboim** [comment]
确实是这样，这就是我们对于协议消息的实现方式。我们tutorial里的示例只是最最简单的一种实现，现实中大多数复杂一点协议实现都需要派生task，你可以参考一下我们的其它几个协议的实现。
你在项目其它地方用的时候，也是需要通过这个工厂来产生任务。

**Comment by Barenboim** [comment]
你说的其它项目也是workflow的代码吗？如果是，直接复用就可以了。
如果不是，那需要其它代码里控制啊。

**Comment by Barenboim** [comment]
我把这个接口开放到网络任务了，可以对所有的client task设置watch timeout，无需派生。相关PR：https://github.com/sogou/workflow/pull/1434
建议使用这个新的接口。
