### ISSUE TITLE
Build error on uwp 

### ISSUE THREAD

**Issue by autoantwort** [sogou/workflow#1417]
When I try to build the project via vcpkg (`vcpkg install workflow --triplet=x64-uwp`) it fails with the following error:
```
C:\Users\xx\git_projects\vcpkg\buildtrees\workflow\src\0.10.9-win-b44fda80d6.clean\src\manager\WFGlobal.cc(906): error C2440: 'return': cannot convert from 'WCHAR *' to 'const char *'
```

**Comment by Barenboim** [comment]
Thank you.
The project's windows branch hasn't been tested on uwp platform. It seems that on uwp 'gai_strerror()' is redirected to 'gai_strerrorW()' which returns a WCHAR string and no compatible with char string. We will try to fix this problem as soon as possible.

**Comment by Barenboim** [comment]
I hope this works: https://github.com/sogou/workflow/commit/e0600af638390cb21314cfd9db084aef1bef945d
