### ISSUE TITLE
关于http client 超时的问题

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1421]
我的全局设置如下:
 WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 20000;
    settings.endpoint_params.connect_timeout   =	30 * 1000;
    settings.endpoint_params.response_timeout  =	30 * 100;
    WORKFLOW_library_init(&settings);

使用http client 的方式 向一个java服务发送post请求,
 WFHttpTask *http_task = WFTaskFactory::create_http_task(url,
                                                            0,
                                                            0,
                                                            [func](WFHttpTask *http_task){
                                                                func(proxy_http_callback(http_task));

                                                            });

    HttpRequest *req = http_task->get_req();
    req->add_header_pair("Content-Type", "application/json");
    req->set_method("POST");
    req->append_output_body(static_cast<const void *>(request_body.c_str()), request_body.size());
    http_task->get_resp()->set_size_limit(20 * 1024 * 1024);
    http_task->set_receive_timeout(30 * 1000);
    if (seriesWork != nullptr)
        seriesWork->push_back(http_task);
    else
        http_task->start();
我的问题是,这个请求任务在很短的时间内就失败了,大概三秒左右. 报错信息为:Fetch failed. state = 1, error = 110 Connection timed out" 
这个超时的时间是怎么设置才能生效.

**Comment by 18328594608** [comment]
> 我的全局设置如下: WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT; settings.endpoint_params.max_connections = 20000; settings.endpoint_params.connect_timeout = 30 * 1000; settings.endpoint_params.response_timeout = 30 * 100; WORKFLOW_library_init(&settings);
> 
> 使用http client 的方式 向一个java服务发送post请求, WFHttpTask *http_task = WFTaskFactory::create_http_task(url, 0, 0, [func](WFHttpTask *http_task){ func(proxy_http_callback(http_task));
> 
> ```
>                                                         });
> 
> HttpRequest *req = http_task->get_req();
> req->add_header_pair("Content-Type", "application/json");
> req->set_method("POST");
> req->append_output_body(static_cast<const void *>(request_body.c_str()), request_body.size());
> http_task->get_resp()->set_size_limit(20 * 1024 * 1024);
> http_task->set_receive_timeout(30 * 1000);
> if (seriesWork != nullptr)
>     seriesWork->push_back(http_task);
> else
>     http_task->start();
> ```
> 
> 我的问题是,这个请求任务在很短的时间内就失败了,大概三秒左右. 报错信息为:Fetch failed. state = 1, error = 110 Connection timed out" 这个超时的时间是怎么设置才能生效.

使用postman能正常访问通访问的server。排除server设置的问题

**Comment by Barenboim** [comment]
settings.endpoint_params.response_timeout = 30 * 100;
你这个地方，设置的响应超时是3秒。这个的含义是，每收到/发出一块数据的超时。可能第一个返回包，就超过3秒了吧。

**Comment by 18328594608** [comment]
是的,在第一个包时间就超过3秒了. 使用http_task->set_receive_timeout(30 * 1000); 对于单个task进行超时设置不能更改这个响应时间么

**Comment by Barenboim** [comment]
任何一个超时都是超时啊。你的response timeout是3秒，receive timeout是30秒，意思是没3秒至少收到1字节数据，30秒内必须收完完整消息的意思。

**Comment by Barenboim** [comment]
你把响应超时也加大就可以了。

**Comment by 18328594608** [comment]
好的。我把超时加大就没什么问题了..感谢解惑
