### ISSUE TITLE
关于Executor调度算法的讨论

### ISSUE THREAD

**Issue by kedixa** [sogou/workflow#1425]
摘自 v0.11.1
https://github.com/sogou/workflow/blob/1d434f30d37b1138ab0a249b8b64b349c4bfc830/src/kernel/Executor.cc#L76-L100

https://github.com/sogou/workflow/blob/1d434f30d37b1138ab0a249b8b64b349c4bfc830/src/kernel/Executor.cc#L120-L150

观察到最近的PR #1423 在考虑优化Executor调度的问题，但似乎未切中要害，故收效甚微。我们来考虑如下极端场景：

1. 有且仅有一个`ExecQueue`
2. 有足够的计算任务期望被发起
3. 任务的执行耗时(C1)**远小于**线程切换耗时(C2)

假设在某一时刻0，所有`Executor`线程刚好空闲，队列为空，计算任务(Tx)被逐个启动，有

1. 时刻0：T1被发起，队列为空，经132路径被调度
2. 0 ~ C2: 有更多的任务被发起，但因队列不空，不会被调度
3. 时刻C2: T1被取出执行，且发现队列不空，经L86调度下一个任务
4. 时刻C2+C1: T1执行完毕
5. C2+C1 ~ 2C2: 空闲
6. 时刻2C2: T2被取出执行，且发现队列不空，经L86调度下一个任务
7. 时刻2C2+C1: T2执行完毕
8. 2C2+C1 ~ 3C2: 空闲
9. **...**

因此，这种情况下，同一个队列中的任务全部为串行执行。我们可以据此事实做出以下猜想

1. 使用同一个队列调度简单任务，效率会极其低下，其原因与 #1423 中提到的锁完全无关，与计算线程数较为无关，与CPU线程切换效率有一定关系
2. 使用多个队列调度简单任务，效率会随队列数逐步增加，并在到达某个极限后不再明显变动，但仍与 #1423 完全无关，因为几乎没有抢锁的事情发生

**Comment by Barenboim** [comment]
我们的调度算法本来也不是给非常轻量级的计算任务调度准备的，因为启动计算任务无论如何都需要执行一次线程调度，而且严格的进行加锁，确保执行不会乱序。

我觉得，同一队列的任务被串行执行这个描述不准确。只要有线程空闲，任何计算任务都是立刻调取。你描述的串行执行，是基于任务本身的CPU消耗远低于一次线程切换开销，没有两个线程同时运行到任务执行函数。我们认为这种情况本来就不应该使用计算任务。当然，我们没有很好的办法解决那种无法预估CPU开销的计算任务。

一般情况下，复杂的后端服务不会只有一个计算队列，这种情况下，同一队列的调度延迟已经不太重要。我们目前的模式是为了保障多队列的调度公平性，保证CPU负载很高情况下有好的长尾效果。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1423 这个修改，虽然对于大多数应用看不到什么效果，但确实优化了单个计算队列调度大量轻量级任务时，消费与生产者抢锁的问题。实测极端场景下有超过20%的性能提升。虽然不是典型的应用场景，但这个修改对于常规的应用，好像也没有额外的性能损失。另外https://github.com/sogou/workflow/commit/7d012264004dca5ca6216e2e010ed40c707327a0 解决了指令乱序问题。

不过，确实让代码比之前复杂，不好理解。

**Comment by kedixa** [comment]
对于20%的结论有所不解，我感觉只需要将`executor_thread_routine`中，`__thrdpool_schedule`的部分移到锁外执行就能有一定的提升。此处不加证明地给出思考方式

1. L83-L86约有几十条指令，常见的CPU可在数十纳秒内完成
2. pthread_mutex_lock在没有竞争的情况下，大概为一次atomic compare and set，在有竞争的情况下通过几次自旋来避免陷入内核
3. 在这个极端性能测试中，有极其频繁的线程切换，单独某个线程正在抢锁的可能性极低

在这样的条件下，这个小锁仍能带来20%的性能损失，确实难以理解。

不过，只要实现过程是正确的，运行结果是正确的，那就无需耗费时间讨论该实现的问题。如果确实有时间，可以用在研究哪些情况下、有锁或无锁会带来什么收益和问题，等。

**Comment by Barenboim** [comment]
简单__thrdpool_schedule移动到锁外，比目前最快版本在极端的小任务场景，性能损失低于5%。我觉得可以考虑一下这个方案。主要是代码可读性会好很多。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1426/commits/6832510509cff4d312020e72c5f6bf3b033a1dcf
改为加锁取任务，锁外调度线程。代码简单一下。

**Comment by kedixa** [comment]
我了解并赞同该调度算法的优点，但对几种可能存在的使用场景做如下思考

假如我正在实现一个需要执行一系列计算的服务端，我可能

## 没有能力预估哪个请求计算量大
对我来说，估计某场景是否计算量大是比较困难的，例如

1. 对3000个整数排序
2. 解析一段50KB的json
3. 通过正则从10KB的HTML中提取链接

此时，我可以对固定场景指定多个队列名并循环使用来解决调度瓶颈，有一点点代码逻辑开销，还有其他办法吗？

## 无法预估哪个请求计算量大
有些请求可能需要在计算过程中才能发现是否有较大计算量，这种情况下，我可能会选择将所有请求都切换到计算线程，也可能全部选择在handler线程计算结果。若我简单地选择后者，并将handler线程数调大会是一种较好的做法吗？

## 可以直接估计请求的计算量
假如可以直接根据请求的参数确定是否要切换到计算线程，那就好办了。如果异步逻辑较多，还可以使用[coke](https://github.com/kedixa/coke)来简化，比如

```cpp
process() {
    if (req.n > 1000)
        co_await coke::switch_go_thread(name1);

    // 此时，若n <= 1000 则处于handler线程，否则处于计算线程

    // 执行计算
    // 执行其他异步逻辑

    if (req.m > 1000)
        co_await coke::switch_go_thread(name2);

    // 执行计算
    // 执行其他异步逻辑
}
```

**Comment by Barenboim** [comment]
> 我了解并赞同该调度算法的优点，但对几种可能存在的使用场景做如下思考
> 
> 假如我正在实现一个需要执行一系列计算的服务端，我可能
> 
> ## 没有能力预估哪个请求计算量大
> 对我来说，估计某场景是否计算量大是比较困难的，例如
> 
> 1. 对3000个整数排序
> 2. 解析一段50KB的json
> 3. 通过正则从10KB的HTML中提取链接
> 
> 此时，我可以对固定场景指定多个队列名并循环使用来解决调度瓶颈，有一点点代码逻辑开销，还有其他办法吗？
> 
> ## 无法预估哪个请求计算量大
> 有些请求可能需要在计算过程中才能发现是否有较大计算量，这种情况下，我可能会选择将所有请求都切换到计算线程，也可能全部选择在handler线程计算结果。若我简单地选择后者，并将handler线程数调大会是一种较好的做法吗？
> 
> ## 可以直接估计请求的计算量
> 假如可以直接根据请求的参数确定是否要切换到计算线程，那就好办了。如果异步逻辑较多，还可以使用[coke](https://github.com/kedixa/coke)来简化，比如
> 
> ```c++
> process() {
>     if (req.n > 1000)
>         co_await coke::switch_go_thread(name1);
> 
>     // 此时，若n <= 1000 则处于handler线程，否则处于计算线程
> 
>     // 执行计算
>     // 执行其他异步逻辑
> 
>     if (req.m > 1000)
>         co_await coke::switch_go_thread(name2);
> 
>     // 执行计算
>     // 执行其他异步逻辑
> }
> ```

我觉得coke里这个switch_go_thread的方法还是很便捷的。用原生workflow根据数据规模大小来决定要不要切到计算任务，代码比较复杂。
