### ISSUE TITLE
编译失败， undefined reference to `EVP_PKEY_CTX_set_rsa_padding' collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by liutaosgsg** [sogou/workflow#1427]
-- Build files have been written to: /home/lt/Documents/code/workflow/workflow/tutorial/build.cmake
make -C build.cmake -f Makefile
make[1]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
make[2]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
make[3]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Scanning dependencies of target bootstrap_server
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
make[3]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
[  2%] Linking CXX executable ../tutorial-16-graceful_restart/server
/home/lt/Documents/code/workflow/workflow/_lib/libworkflow.so: undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
collect2: error: ld returned 1 exit status
CMakeFiles/bootstrap_server.dir/build.make:97: recipe for target '../tutorial-16-graceful_restart/server' failed
make[3]: *** [../tutorial-16-graceful_restart/server] Error 1
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bootstrap_server.dir/all' failed
make[2]: *** [CMakeFiles/bootstrap_server.dir/all] Error 2
make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
GNUmakefile:12: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Barenboim** [comment]
你好。你机器上的OpenSSL什么版本？EVP_PKEY_CTX_set_rsa_padding这个函数我们测过的，从 OpenSSL 1.0起，都没有问题。
也可能是动态连接库的原因。你试一下把_lib目录下的.so文件都删了，看看能不能编译tutorial。

**Comment by liutaosgsg** [comment]
你好，删除了之后有报其他错误。
usr/bin/ld: cannot find -lworkflow
collect2: error: ld returned 1 exit status
CMakeFiles/bootstrap_server.dir/build.make:97: recipe for target '../tutorial-16-graceful_restart/server' failed
make[3]: *** [../tutorial-16-graceful_restart/server] Error 1
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bootstrap_server.dir/all' failed
make[2]: *** [CMakeFiles/bootstrap_server.dir/all] Error 2
make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
GNUmakefile:12: recipe for target 'all' failed

**Comment by liutaosgsg** [comment]
openssl version
openssl: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
版本查不到。

**Comment by Barenboim** [comment]
这里看你是OpenSSL 3。但你的openssl命令也找不到连接库啊，是不是没有正确安装OpenSSL开发包。安装OpenSSL开发包的命令是：
$ sudo apt-get install libssl-devel

**Comment by Barenboim** [comment]
如果可以使用了的话，麻烦回复一下。

**Comment by liutaosgsg** [comment]
sudo apt-get install libssl-devel
[sudo] password for lt: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libssl-devel

**Comment by liutaosgsg** [comment]
您好，感谢指导，这种安装方式有点问题。

**Comment by Barenboim** [comment]
你的是什么系统？这是Debian或ubuntu安装openssl开发包的标准命令。如果是centos或federo，可以用:
$ sudo def install openssl-devel
不过看起来你是有apt-get命令的啊。为啥找不到openssl开发包呢？

**Comment by liutaosgsg** [comment]
ubantu系统，确实很奇怪。

**Comment by liutaosgsg** [comment]
ake[3]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
[  2%] Linking CXX executable ../tutorial-16-graceful_restart/server
/usr/bin/ld: cannot find -lworkflow
collect2: error: ld returned 1 exit status
CMakeFiles/bootstrap_server.dir/build.make:97: recipe for target '../tutorial-16-graceful_restart/server' failed
make[3]: *** [../tutorial-16-graceful_restart/server] Error 1
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bootstrap_server.dir/all' failed
make[2]: *** [CMakeFiles/bootstrap_server.dir/all] Error 2
make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
GNUmakefile:12: recipe for target 'all' failed
make: *** [all] Error 2
现在是报这个错误。

**Comment by kedixa** [comment]
```bash
sudo apt install libssl-dev
```

**Comment by liutaosgsg** [comment]
> ```shell
> sudo apt install libssl-dev
> ```
  2%] Linking CXX executable ../tutorial-16-graceful_restart/server
/usr/bin/ld: cannot find -lworkflow
collect2: error: ld returned 1 exit status
CMakeFiles/bootstrap_server.dir/build.make:97: recipe for target '../tutorial-16-graceful_restart/server' failed
make[3]: *** [../tutorial-16-graceful_restart/server] Error 1
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bootstrap_server.dir/all' failed
make[2]: *** [CMakeFiles/bootstrap_server.dir/all] Error 2
make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
GNUmakefile:12: recipe for target 'all' failed
make: *** [all] Error 2
不行

**Comment by Barenboim** [comment]
你到根目录先make clean，然后重新make，再到tutorial里make一下。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月18日(周六) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 编译失败， undefined reference to `EVP_PKEY_CTX_set_rsa_padding' collect2: error: ld returned 1 exit status (Issue #1427)




  sudo apt install libssl-dev
  
2%] Linking CXX executable ../tutorial-16-graceful_restart/server
 /usr/bin/ld: cannot find -lworkflow
 collect2: error: ld returned 1 exit status
 CMakeFiles/bootstrap_server.dir/build.make:97: recipe for target '../tutorial-16-graceful_restart/server' failed
 make[3]: *** [../tutorial-16-graceful_restart/server] Error 1
 make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
 CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bootstrap_server.dir/all' failed
 make[2]: *** [CMakeFiles/bootstrap_server.dir/all] Error 2
 make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
 Makefile:83: recipe for target 'all' failed
 make[1]: *** [all] Error 2
 make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
 GNUmakefile:12: recipe for target 'all' failed
 make: *** [all] Error 2
 不行

**Comment by liutaosgsg** [comment]
[  4%] Linking CXX executable ../tutorial-16-graceful_restart/server
/home/lt/Documents/code/workflow/workflow/_lib/libworkflow.so: undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
collect2: error: ld returned 1 exit status
CMakeFiles/bootstrap_server.dir/build.make:97: recipe for target '../tutorial-16-graceful_restart/server' failed
make[3]: *** [../tutorial-16-graceful_restart/server] Error 1
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bootstrap_server.dir/all' failed
make[2]: *** [CMakeFiles/bootstrap_server.dir/all] Error 2
make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
GNUmakefile:12: recipe for target 'all' failed
make: *** [all] Error 2
还是不行，有啥靠谱的方法吗

**Comment by Barenboim** [comment]
最主要的问题就是你没有安装上openssl的链接库😳至于为什么装不上，我也搞不懂了。
不过这里只提示rsa的这个函数找不到，你试试这样：
~~~sh
make clean
make MYSQL=n
cd tutorial
make MYSQL=n
~~~
这样不需要用到那个rsa函数，看看提示什么。

**Comment by liutaosgsg** [comment]
> 最主要的问题就是你没有安装上openssl的链接库😳至于为什么装不上，我也搞不懂了。 不过这里只提示rsa的这个函数找不到，你试试这样：
> 
> ```shell
> make clean
> make MYSQL=n
> cd tutorial
> make MYSQL=n
> ```
> 
> 这样不需要用到那个rsa函数，看看提示什么。

make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
[ 95%] Built target consul_cli
make[3]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
Scanning dependencies of target wget_to_redis
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
make[3]: Entering directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
[ 97%] Building CXX object CMakeFiles/wget_to_redis.dir/tutorial-03-wget_to_redis.cc.o
[100%] Linking CXX executable ../wget_to_redis
make[3]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
[100%] Built target wget_to_redis
make[2]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake'
make[1]: Leaving directory '/home/lt/Documents/code/workflow/workflow/tutorial/build.cmake
感谢，编译是通过了，这样后面使用会有问题吗？

**Comment by Barenboim** [comment]
居然过了！这个把mysql client给裁剪掉了，用不了mysql。
这个就很奇怪了，你的openssl不支持那几个rsa函数。但我们实测从1.0到3.0都是有的。我们再check一下这个问题。

**Comment by Barenboim** [comment]
你用的是master分支吧？

**Comment by liutaosgsg** [comment]
> 你用的是master分支吧？

是的，默认的分支。那我现在即使编译过了还是不能用其中的功能把。

**Comment by Barenboim** [comment]
不能用mysql client，别的不影响。

**Comment by Barenboim** [comment]
@liutaosgsg 先close了。有什么使用上的问题随时issue。
