### ISSUE TITLE
实现一次redis写入与读出：redis_cli 编译的时候报错。

### ISSUE THREAD

**Issue by liutaosgsg** [sogou/workflow#1432]
![image](https://github.com/sogou/workflow/assets/57380281/7dfad960-187e-427a-b738-5a336f234726)

**Comment by Barenboim** [comment]
你是linux环境吧？netdb.h是任何unix环境都有点头文件。

**Comment by liutaosgsg** [comment]
是windows的环境

**Comment by Barenboim** [comment]
你怎么换成了Windows环境。Windows下需使用Windows分支的代码，这里这个文件不包括netdb.h。
我们比较建议在Windows下用WSL 2。Windows版代码我们现在支持力度不足。

**Comment by liutaosgsg** [comment]
使用windows方便一点，那Windows可以用吗，测试第一个用例是可以的。

**Comment by Barenboim** [comment]
可以用，但Windows的代码并不在主分支，而是在Windows分支。你用主分支的示例代码没办法编译的。

**Comment by Barenboim** [comment]
@liutaosgsg
