### ISSUE TITLE
利用workflow 写了一个redis客户端程序，当传入的命令是brpop这种阻塞式命令后，redis server一段时间没数据返回就会报错

### ISSUE THREAD

**Issue by youfeiyou** [sogou/workflow#1433]
返回的结果里，task state 为1 ， task error 为 110，尝试修改了文档里提到的超时参数，包括receive_timeout, send_timeout 均无效，请问这种情况该如何处理呢？这边需求是对于brpop 这种命令如果redis-server 没有返回数据就一直阻塞

**Comment by Barenboim** [comment]
我们全局有个response_timeout，默认是10秒。也就是说，对于一个通讯目标，10秒内没有收到（或发出）一块数据，就是超时了。这个在global settings里的endpoint params，和connect_timeout并列的。

理论上，对于这种watch类请求，是可以设置watch timeout的，但这个需要自己实现一个虚函数，而redis client task没有实现。可以考虑一下开放这个接口。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1434
可以看一下这个PR。加上了set_watch_timeout接口。当设置了这个值，client接收首个包的超时会使用这个watch timeout，而不是全局的response timeout。

**Comment by youfeiyou** [comment]
> #1434 可以看一下这个PR。加上了set_watch_timeout接口。当设置了这个值，client接收首个包的超时会使用这个watch timeout，而不是全局的response timeout。

好的，感谢

**Comment by Barenboim** [comment]
麻烦试一下这个功能，如果可用了同步一下。
