### ISSUE TITLE
有个指针和引用问题，请教一下。

### ISSUE THREAD

**Issue by liutaosgsg** [sogou/workflow#1435]
您好，
代码中有的地方使用引用，有的地方使用指针，我知道指针和引用的区别，
我个人觉得引用比指针使用起来相对更安全。实际应用中该何时使用指针，何时使用引用？？
create_series_work(SubTask *first, series_callback_t callback);
std::string MySQLUtil::escape_string(const std::string& str)；
谢谢。

**Comment by Barenboim** [comment]
涉及STL的才用引用。另外就是运算符重载，只能用引用。
其它都是指针。

用上我们的项目的话，记得star噢。

**Comment by liutaosgsg** [comment]
您好，感谢回复，能进一步解释下为什么涉及STL的才用引用吗？如果不方便的话我自己查下资料也可以。

**Comment by Barenboim** [comment]
我们这种工厂模式，应该用指针比较方便吧。让函数返回一个引用也太奇怪了。原则上，我们任何自己的类，都不会有引用，除非是运算符重载。

至于stl的对象，我们一般是传值或传引用，因为这样才能做隐式转换，例如const std::string&的地方可以传入C的字符串。

本质上我们是一个c with class项目，会尽可能用更加原始的语言特征，只代表这个项目的风格而已。

**Comment by Barenboim** [comment]
@liutaosgsg 没有什么别的疑问我先关了。
