### ISSUE TITLE
C++语法问题请教一下。

### ISSUE THREAD

**Issue by liutaosgsg** [sogou/workflow#1436]
您好：
class Workflow
{
public:
	static SeriesWork *
	create_series_work(SubTask *first, series_callback_t callback);
这里面的static SeriesWork *这个用法是怎么使用的，是代表了什么含义？没见过这种写法。
谢谢。

**Comment by Barenboim** [comment]
这个是函数是static的，不是说返回值static。最根本的C++语法。

**Comment by Barenboim** [comment]
这个是函数是static的，不是说返回值static。最基本的C++语法，就是个静态函数。

**Comment by liutaosgsg** [comment]
了解了，看错了，以为是两行两个内容，其实是表达一个意思。
