### ISSUE TITLE
queue get

### ISSUE THREAD

**Issue by ss2020214** [sogou/workflow#1438]
*queue->get_head = *(void **)*queue->get_head;
void*通过*解引用，在强转void**,再解引用？

**Comment by Barenboim** [comment]
你可以看一下这个比较容易阅读的写法：https://github.com/Barenboim/msgqueue_thrdpool/blob/main/msgqueue_simple.c
这个代码编译结果是完全二进制相同的。

**Comment by ss2020214** [comment]
谢谢，我觉得这样写更好理解一点

**Comment by Barenboim** [comment]
当时觉得多定义一个结构太麻烦，也不知道起什么名字，就直接写了😓
