### ISSUE TITLE
关于redis-proxy 超时问题

### ISSUE THREAD

**Issue by youfeiyou** [sogou/workflow#1445]
这边利用REDIS-SERVER 写了一个redis-proxy, 逻辑就是接受客户端请求，然后create_redis_task 请求到真实的redis 服务器，最后回调函数里把redis 回包透传给客户端；因为客户端这边会有阻塞是调用，所以proxy server 将response_time_out 设置为-1， 另外keep_alive 也设置为-1；
在我测试过中，用hiredis 库写了客户端请求逻辑，每个客户端开三个线程请求proxy，然后我在开了一个redis-client 请求 proxy发现请求时延很高，如set 或者get 需要1到3秒；
请问这个可能是哪方面原因呢？

**Comment by Barenboim** [comment]
你好。能不能贴一下你的实现逻辑。是不是按照我们http-proxy的结构写的？WFRedisServer在我们内部大量使用，不会有什么问题。我不太理解为什么客户端用阻塞，你就把response_timeout设置为-1，这两个事之间看不出什么联系。

另外，实现redis-proxy有个建议，可以把auth命令的用户名密码信息以及select命令db num的信息填在连接上下文里，因为这个是连接上的状态，在同一个连接的下一个命令里可能需要用到。大多数proxy可以不支持select，但auth一般还是要的。

还有一点要注意，就是workflow server完全放弃pipeline，无法支持pipeline请求。

**Comment by youfeiyou** [comment]
> 你好。能不能贴一下你的实现逻辑。是不是按照我们http-proxy的结构写的？WFRedisServer在我们内部大量使用，不会有什么问题。我不太理解为什么客户端用阻塞，你就把response_timeout设置为-1，这两个事之间看不出什么联系。
> 
> 另外，实现redis-proxy有个建议，可以把auth命令的用户名密码信息以及select命令db num的信息填在连接上下文里，因为这个是连接上的状态，在同一个连接的下一个命令里可能需要用到。大多数proxy可以不支持select，但auth一般还是要的。
> 
> 还有一点要注意，就是workflow server完全放弃pipeline，无法支持pipeline请求。

`void callback(WFRedisTask *task)
{
	auto req = task->get_req();
	auto rsp= task->get_resp();
	if(task->get_error()!=0||task->get_state()!=0){
		std::cerr << task->get_error()  << " " << task->get_state() << std::endl;
	}
	auto proxy_task = (WFRedisTask*)series_of(task)->get_context();
	auto proxy_rsp = proxy_task->get_resp();
	*proxy_rsp=std::move(*rsp);
}


void process(WFRedisTask *proxy_task)
{
	auto *req = proxy_task->get_req();
    auto rsp = proxy_task->get_resp();
	std::string command;
	req->get_command(command);
	std::cout << "com: " << command << std::endl;
	auto series = series_of(proxy_task);
	series->set_context(proxy_task);
	auto task = WFTaskFactory::create_redis_task("redis://127.0.0.1:6379",0,callback);
	task->set_keep_alive(-1);
	*task->get_req()=std::move(*proxy_task->get_req());
	series->push_back(task);
}

static WFFacilities::WaitGroup wait_group(1);

void sig_handler(int signo)
{
	wait_group.done();
}

int main(int argc, char *argv[])
{
	unsigned short port;

	if (argc != 2)
	{
		fprintf(stderr, "USAGE: %s <port>\n", argv[0]);
		exit(1);
	}

	port = atoi(argv[1]);
	signal(SIGINT, sig_handler);

	struct WFServerParams params = REDIS_SERVER_PARAMS_DEFAULT;
	params.keep_alive_timeout=-1;
	struct WFGlobalSettings setting = GLOBAL_SETTINGS_DEFAULT;
	setting.endpoint_params.response_timeout=-1;
	WORKFLOW_library_init(&setting);

	WFRedisServer server(&params,process);
	if (server.start(port) == 0)
	{
		wait_group.wait();
		server.stop();
	}
	else
	{
		perror("Cannot start server");
		exit(1);
	}

	return 0;
}`

**Comment by youfeiyou** [comment]
`void callback(WFRedisTask *task)
{
	auto req = task->get_req();
	auto rsp= task->get_resp();
	if(task->get_error()!=0||task->get_state()!=0){
		std::cerr << task->get_error()  << " " << task->get_state() << std::endl;
	}
	auto proxy_task = (WFRedisTask*)series_of(task)->get_context();
	auto proxy_rsp = proxy_task->get_resp();
	*proxy_rsp=std::move(*rsp);
}


void process(WFRedisTask *proxy_task)
{
	auto *req = proxy_task->get_req();
    auto rsp = proxy_task->get_resp();
	std::string command;
	req->get_command(command);
	std::cout << "com: " << command << std::endl;
	auto series = series_of(proxy_task);
	series->set_context(proxy_task);
	auto task = WFTaskFactory::create_redis_task("redis://127.0.0.1:6379",0,callback);
	task->set_keep_alive(-1);
	*task->get_req()=std::move(*proxy_task->get_req());
	series->push_back(task);
}

static WFFacilities::WaitGroup wait_group(1);

void sig_handler(int signo)
{
	wait_group.done();
}

int main(int argc, char *argv[])
{
	unsigned short port;

	if (argc != 2)
	{
		fprintf(stderr, "USAGE: %s <port>\n", argv[0]);
		exit(1);
	}

	port = atoi(argv[1]);
	signal(SIGINT, sig_handler);

	struct WFServerParams params = REDIS_SERVER_PARAMS_DEFAULT;
	params.keep_alive_timeout=-1;
	struct WFGlobalSettings setting = GLOBAL_SETTINGS_DEFAULT;
	setting.endpoint_params.response_timeout=-1;
	WORKFLOW_library_init(&setting);

	WFRedisServer server(&params,process);
	if (server.start(port) == 0)
	{
		wait_group.wait();
		server.stop();
	}
	else
	{
		perror("Cannot start server");
		exit(1);
	}

	return 0;
}`

**Comment by Barenboim** [comment]
结构上没有什么毛病。两处keep_alive_timeout和response_timeout其实都没有必要设置，都有默认值。redis client的连接会保持60秒，redis server默认保持300秒，这已经足够长了。

你可以打一下各个时间点，包括client发请求的时候，process开始的时候和callback开始的时候，确认一下卡在哪一步了。

**Comment by youfeiyou** [comment]
> 结构上没有什么毛病。两处keep_alive_timeout和response_timeout其实都没有必要设置，都有默认值。redis client的连接会保持60秒，redis server默认保持300秒，这已经足够长了。
> 
> 你可以打一下各个时间点，包括client发请求的时候，process开始的时候和callback开始的时候，确认一下卡在哪一步了。

感谢，我这边发现proxy 在请求redis 的时候会返回state=1 error=11 错误

**Comment by Barenboim** [comment]
噢噢，那加大endpoint params里的max connections就可以了。默认对一个通信目标的最大连接数只有200，这里可能qps太大，用超了。

你大概打了多大的qps?

**Comment by youfeiyou** [comment]
> 噢噢，那加大endpoint params里的max connections就可以了。默认对一个通信目标的最大连接数只有200，这里可能qps太大，用超了。
> 
> 你大概打了多大的qps?

qps应该是过千了，另外我想请教一下这里默认最大连接数200出于什么考虑呢，以及什么情况下一个tcp 连接会被复用呢？假设一种场景：如果我这里发起200个redis task ，命令全都是brpop这种阻塞是命令，redis-server 隔了半小时才回包，那么在这半小时中我再发起redis task 会复用这已有的200个连接吗？

**Comment by Barenboim** [comment]
> > 噢噢，那加大endpoint params里的max connections就可以了。默认对一个通信目标的最大连接数只有200，这里可能qps太大，用超了。
> > 你大概打了多大的qps?
> 
> qps应该是过千了，另外我想请教一下这里默认最大连接数200出于什么考虑呢，以及什么情况下一个tcp 连接会被复用呢？假设一种场景：如果我这里发起200个redis task ，命令全都是brpop这种阻塞是命令，redis-server 隔了半小时才回包，那么在这半小时中我再发起redis task 会复用这已有的200个连接吗？

我们各种默认参数都比较保守。例如server的默认最大连接数也只有2000，很多时候也需要加大。你这个场景，主要是因为只有一个通讯目标（127.0.0.1），而且是brpop这种长时间等待的命令，所以200个对外连接很快就慢了。默认值的设定没有什么特别的原因，确实有点小。

我们的连接复用是FILO，最近释放的连接会先复用。redis client的连接，只要是相同用户名密码而且db num相同，都会完美复用。在callback之前就可能复用了，所以callback里设置keep alive无效。你的这个场景，所有连接都是会复用的，无论请求多长时间完成。

**Comment by youfeiyou** [comment]
> > > 噢噢，那加大endpoint params里的max connections就可以了。默认对一个通信目标的最大连接数只有200，这里可能qps太大，用超了。
> > > 你大概打了多大的qps?
> > 
> > 
> > qps应该是过千了，另外我想请教一下这里默认最大连接数200出于什么考虑呢，以及什么情况下一个tcp 连接会被复用呢？假设一种场景：如果我这里发起200个redis task ，命令全都是brpop这种阻塞是命令，redis-server 隔了半小时才回包，那么在这半小时中我再发起redis task 会复用这已有的200个连接吗？
> 
> 我们各种默认参数都比较保守。例如server的默认最大连接数也只有2000，很多时候也需要加大。你这个场景，主要是因为只有一个通讯目标（127.0.0.1），而且是brpop这种长时间等待的命令，所以200个对外连接很快就满了。默认值的设定没有什么特别的原因，确实有点小。
> 
> 我们的连接复用是FILO，最近释放的连接会先复用。redis client的连接，只要是相同用户名密码而且db num相同，都会完美复用。在callback之前就可能复用了，所以callback里设置keep alive无效。你的这个场景，所有连接都是会复用的，无论请求多长时间完成。

好的，感谢
