### ISSUE TITLE
关于会收到重复Http请求的问题

### ISSUE THREAD

**Issue by qiqiqiren** [sogou/workflow#1446]
您好，我在项目里简单的引用了tutorial00的示例，启动了一个http server。
我用网页进行访问，我只触发了一次请求，但是我服务内实现的process却进来了2次，时隔只有300ms。
请问这会是什么原因？

**Comment by qiqiqiren** [comment]
另外我在该项目里还启用了一个基于WF的自定义协议的server，其中修改了以下参数，不知道是否有关联。

`struct WFServerParams params = SERVER_PARAMS_DEFAULT;
    params.request_size_limit = 4 * 1024;
    params.keep_alive_timeout = -1;`

**Comment by Barenboim** [comment]
你用浏览器访问的吧？浏览器就是这个行为，会多发请求，不用管。
我们的server收到一个请求，必要只会调一次process。

**Comment by qiqiqiren** [comment]
好的，感谢。
