### ISSUE TITLE
workflow server能否在process中向另一个客户端创建http任务发送数据 还有对 workflow wait_group使用的问题

### ISSUE THREAD

**Issue by MasterL-min** [sogou/workflow#1449]
大致场景如下：
客户端A向服务器B发送信息，进入server process
服务器B在处理信息的过程中，需要向客户端C转发信息。
服务器B不希望等给C转发完消息后再给A回复信息。

我看了一些相关的issue，服务器的process是在当前task所在的series里没任务了才结束，所以我想是不是不能创建一个给C的http_task，然后series_of(server_task)->push_back(to_c_task)；这样会导致给C转发完信息后才会给A回复信息。
还是说这种情况需要使用一个ParallelWork *pwork去把这个给C的新任务放在另一个series去做，然后启动这个pwork。

还有我C++的线程等等可能学艺不精，对异步理解也有问题，在使用wait_group的时候经常会陷入纠结，我在翻看一些issue中看到提到wait_group一般只在main函数里应用，用于防止程序退出。我也尝试了在main函数中使用wait_group.wait()，然后在main函数调用的函数（比如我们称这个函数为A）中创建一个http task，然后task->start()，并且在A函数中并没有再使用wait_group.wait()，这个任务的确可以正确运行，所以我想workflow中的task->start()是不是只要保证调用这个异步任务的线程不结束，任务就能正常运行。

我目前在保证main函数中wait_group.wait()的情况下，只在task任务启动后需要拿到回调函数中返回的内容进行下一步处理的时候才会使用wait_group.wait()，不知道这种用法是否合理正确，还有在服务器process中series->push_back()或创建并行任务后是否需要像在main函数中调用wait_group.wait()，还是直接push_back后启动series即可。

**Comment by Barenboim** [comment]
1、你不需要等C返回，完全可以在server_task的callback里再去push_back(c_task)啊。server_task的callback是在回复之后（数据写入tcpbuf）执行的。你在process里push_back，肯定是C返回之后才回复。你非要在process里做的话，那就只能直接start了。这个时候这个C任务的结束和server.stop()以及main的退出，就没有先后关系了，需要你自己处理。我感觉上你就是想在回复之后做点什么事，那就在callback里再push_back(c_task)，这种情况，server.stop()会等所有series执行完成。

2、我看不太懂你的描述。总之我们是全程无等待的，在main里用wait_group.wait是为了防止有些任务还没有callback，主进程就退出了。其它任何地方都没有使用wait_group的必要。很奇怪你为什么说要在process里用wait_group来等待，你也是清楚在process里push_back的用法的。你还是重新描述一下你的实际需求吧。

**Comment by Barenboim** [comment]
第一个你就理解错了……
我说的是server_task的callback啊，server_task是可以有callback的啊，这个callback是在回复之后，你可以这么写：
~~~cpp
void process(WFHttpTask *server_task)
{
    server_task->get_resp()->append_output_body("Hello world!\n");
    server_task->set_callback([](WFHttpTask *server_task) {
        c_task = ....
        series_of(server_task)->push_back(c_task);
   });
}
~~~
回复之后向C发送，就是实现你说的效果了。

**Comment by MasterL-min** [comment]
> 第一个你就理解错了…… 我说的是server_task的callback啊，server_task是可以有callback的啊，这个callback是在回复之后，你可以这么写：
> 
> ```c++
> void process(WFHttpTask *server_task)
> {
>     server_task->get_resp()->append_output_body("Hello world!\n");
>     server_task->set_callback([](WFHttpTask *server_task) {
>         c_task = ....
>         series_of(server_task)->push_back(c_task);
>    });
> }
> ```
> 
> 回复之后向C发送，就是实现你说的效果了。

GET到您的意思了，谢谢老哥

**Comment by Barenboim** [comment]
第二个问题，如果你是自己的一组线程池，你要等也可以等。不过，我不太明白为什么要这么做，一组串行任务就是在callback里一直push_back就可以了啊。

**Comment by MasterL-min** [comment]
> 第一个你就理解错了…… 我说的是server_task的callback啊，server_task是可以有callback的啊，这个callback是在回复之后，你可以这么写：
> 
> ```c++
> void process(WFHttpTask *server_task)
> {
>     server_task->get_resp()->append_output_body("Hello world!\n");
>     server_task->set_callback([](WFHttpTask *server_task) {
>         c_task = ....
>         series_of(server_task)->push_back(c_task);
>    });
> }
> ```
> 
> 回复之后向C发送，就是实现你说的效果了。

这个在server_task的callback里加入push_back新任务跟直接在process里创建c_task然后c_task.start()的效率哪个会更高一点呢？我感觉在回调函数里push_back（c_task）看起来更优美一些，感觉是一个非常流畅的串行任务，但是是不是直接c_task.start()会更快一些

**Comment by Barenboim** [comment]
> > 第一个你就理解错了…… 我说的是server_task的callback啊，server_task是可以有callback的啊，这个callback是在回复之后，你可以这么写：
> > ```c++
> > void process(WFHttpTask *server_task)
> > {
> >     server_task->get_resp()->append_output_body("Hello world!\n");
> >     server_task->set_callback([](WFHttpTask *server_task) {
> >         c_task = ....
> >         series_of(server_task)->push_back(c_task);
> >    });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 回复之后向C发送，就是实现你说的效果了。
> 
> 这个在server_task的callback里加入push_back新任务跟直接在process里创建c_task然后c_task.start()的效率哪个会更高一点呢？我感觉在回调函数里push_back（c_task）看起来更优美一些，感觉是一个非常流畅的串行任务，但是是不是直接c_task.start()会更快一些

我前面有说，你直接start一个c_task当然可以，但这个task就不受server的控制了。你调用server.stop()完全，可能这个task还没有回来。如果你用push_back的方式的话，server.stop()会等这个series结束。

**Comment by Barenboim** [comment]
@MasterL-min
