### ISSUE TITLE
一个SeriesWork 使用上面的疑问

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1454]
问题如下:
    SeriesWork *series 我往这个series里面push 100个 gotask 任务.这样子执行所用和我直接把这100个gotask 封装成fuction 然后放进一个线程里面去执行所用的耗时是不是相同的.

  按照我的理解,SeriesWork 为串行执行,在时间维度上面来说100个 gotask消耗的时间是100个这个函数的执行时间,那和放进线程执行应该是一样的吧

**Comment by Barenboim** [comment]
同一个series里的任务，就是业务逻辑上就是串行执行的，你push_back 100个任务，这些任务一点是依次执行，并且每个任务之间肯定会切换一次线程。如果任务粒度非常小，那么，总的执行时间会比你一个线程内连续执行要长一些。任务粒度大，可能没有什么区别。

不过，你连续100个go task，完全可以简化成一个啊。常见的场景是一个业务流程里，通讯和计算交替执行。

**Comment by 18328594608** [comment]
会有这个场景的原因是我在一个观察者模式的的推送模块里面使用了一个block series作为推送方.数据生产之后往这个block series里面塞任务,然后执行这个任务把数据推送出去,推送的频率是微秒级别. 所以我想知道一下一个series 顺序执行任务的时候和单线程跑的速度对比

**Comment by Barenboim** [comment]
用线程运行的话，就是占用一个线程等待。如果不想等待，就同样是需要线程切换，那就和我们的模式一样了。

我们适合于那种非常复杂的业务，就是同一个进程里有许多个你这样的业务，远远多于本机的CPU核心数据，需要在多个业务之间进行协调，那我们就能发挥作用了。

**Comment by 18328594608** [comment]
好的 感谢答疑
