### ISSUE TITLE
域名问题

### ISSUE THREAD

**Issue by conniecao** [sogou/workflow#1457]
我连接api.hbdm.vn这个域名会报错：system error: Network is unreachable。但是api.hbdm.com就可以。这两个域名都是交易所接口里面指定的，我朋友用别的库连api.hbdm.vn是可以的。请问下为啥呢

**Comment by Barenboim** [comment]
你好。请问是不是最新代码？如果是最新代码，你可以这么做试一下：
~~~
#include <workflow/WFGlobal.h>
int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.address_family = AF_INET;
    WORKFLOW_library_init(&settings);
    ...
}
~~~
我觉得原因可能是，你的.vn域名有IPv6地址而且你本机也支持IPv6，但是，因为某些原因你的机器又发不了IPv6的请求。你先改成全都用IPv4试一下。需要使用主分支最新代码。

**Comment by conniecao** [comment]
那改成ipv4会影响速度吗

**Comment by Barenboim** [comment]
你本机很可能本来主用不了IPv6。先试一下吧，能跑了再考虑速度的问题。

**Comment by Barenboim** [comment]
@conniecao 你好，试了这个方法了吗？可不可行？

**Comment by conniecao** [comment]
我还没试这个方法，我服务器确实没开IPv6，我打算直接开IPv6，然后再看，谢谢大佬
