### ISSUE TITLE
WFConditional可以加一个访问task的接口嘛

### ISSUE THREAD

**Issue by chloro-pn** [sogou/workflow#1458]
有些场景可能需要在将task封装到WFConditional后再设置callback。

**Comment by Barenboim** [comment]
在WFTaskFactory.cc里，我的__WFNamedGuard是这么干的，用的方法是派生。你看一下实现。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/ba98ed0945f8888f73350ddfe5d9681306103702/src/factory/WFTaskFactory.cc#L928C36-L928C36

**Comment by chloro-pn** [comment]
呃，我的意思就是可以把get_task放在WFConditional里不，不然为了访问task还要派生一个新的类。
你目前没时间的话我提个pr？

**Comment by Barenboim** [comment]
我研究一下。
不过，在我们这个上面做深度的二次开发，需要派生很正常的。你目前的需求如果可以派生解决，建议用派生。我们的WFConditional类就是到处被派生的啊。

**Comment by Barenboim** [comment]
这个地方直接搞个get_task的话，类型信息也丢失了啊，感觉不太好的样子。你派生一下甚至可以用上模板，还能get出原来的类型。

**Comment by chloro-pn** [comment]
ok

**Comment by chloro-pn** [comment]
想到好的解决办法了，感谢。
这个确实不太合理，之前没想到类型信息丢失的问题。
