### ISSUE TITLE
http请求的body数据多了些内容？

### ISSUE THREAD

**Issue by algoqt** [sogou/workflow#1460]
执行  ./tutorial/Debug/wget.exe https://qt.gtimg.cn/q=sz002055,sh601318

为何返回的body数据 和 浏览器看到的不一样？前面多了多了 字符"3cc" 和一个换行。后面多了个0...
代码返回：
![image](https://github.com/sogou/workflow/assets/93410715/e89dc3b2-033b-4870-9daf-fcdad80600b3)

浏览器的response：
![image](https://github.com/sogou/workflow/assets/93410715/c871f6d7-2889-4282-aee4-bdfea3124622)

**Comment by Barenboim** [comment]
这是chunk编码。可以用HttpUtil里的chunk cursor或decode_chunked_body来解码。为了性能，默认我们不会解码chunk。

**Comment by algoqt** [comment]
> 这是chunk编码。可以用HttpUtil里的chunk cursor或decode_chunked_body来解码。为了性能，默认我们不会解码chunk。

明白。了解了。用 HttpUtil::decode_chunked_body 就ok了
