### ISSUE TITLE
Ubuntu23.04会有undefined reference to `SSL_ctrl'错误

### ISSUE THREAD

**Issue by GLfuture** [sogou/workflow#1461]
我在编译coke项目的时候直接apt安装了libworkflow-dev，链接时发生错误
 /usr/lib/x86_64-linux-gnu/libworkflow.a(RouteManager.cc.o): in function `non-virtual thunk to RouteTargetSNI::init_ssl(ssl_st*)':
(.text._ZN14RouteTargetSNI8init_sslEP6ssl_st[_ZN14RouteTargetSNI8init_sslEP6ssl_st]+0x5d): undefined reference to `SSL_ctrl'，
于是我git下workflow的源码重新编译，在编译workflow自带的tutorial时仍然
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.so: undefined reference to `SSL_ctrl'
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.so: undefined reference to `SSL_CTX_callback_ctrl'
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.so: undefined reference to `SSL_CTX_ctrl'
检查cmake发现链接了ssl和crypto，是什么原因呢

**Comment by Barenboim** [comment]
你好，麻烦用静态链接再试一下。make完直接删除_lib里的.so文件再到tutorial里make。另外，看一下openssl的版本。

**Comment by GLfuture** [comment]
仍然链接错误
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.a(HttpTaskImpl.cc.o): in function `ComplexHttpProxyTask::init_ssl_connection()':
/home/gong/src/workflow/src/factory/HttpTaskImpl.cc:487: undefined reference to `SSL_ctrl'
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.a(WFServer.cc.o): in function `WFServerBase::new_ssl_ctx(char const*, char const*)':
/home/gong/src/workflow/src/server/WFServer.cc:77: undefined reference to `SSL_CTX_callback_ctrl'
/usr/bin/ld: /home/gong/src/workflow/src/server/WFServer.cc:78: undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.a(RouteManager.cc.o): in function `RouteTargetSNI::init_ssl(ssl_st*)':
/home/gong/src/workflow/src/manager/RouteManager.cc:85: undefined reference to `SSL_ctrl'
/usr/bin/ld: /home/gong/src/workflow/_lib/libworkflow.a(RouteManager.cc.o): in function `non-virtual thunk to RouteTargetSNI::init_ssl(ssl_st*)':
/home/gong/src/workflow/src/manager/RouteManager.cc:83: undefined reference to `SSL_ctrl'
我的openssl版本是
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

**Comment by Barenboim** [comment]
搜了一下，hiredis有人问过类似的问题：https://github.com/redis/hiredis/issues/1159  。他的原因是机器上还安装了一个openssl 1.0，导致链接错误。你看看是不是一样的原因。

**Comment by GLfuture** [comment]
谢谢，我用locate找到了/usr/local/lib中存在一个libssl.a文件，使用readelf -h libssl.a查看版本为1，修改环境变量后问题得到解决
