### ISSUE TITLE
http server 如何将一个大文件分块传输给http client？

### ISSUE THREAD

**Issue by QidongLi** [sogou/workflow#1463]
是需要为每块数据都创建一个任务然后进行数据发送吗？有没有示例可参考

**Comment by oceanfan1990** [comment]
这个问题有没有例子可以参考，有些场景需要分包发送

**Comment by Barenboim** [comment]
> 这个问题有没有例子可以参考，有些场景需要分包发送

重新发个issue描述一下具体需求吧。

**Comment by oceanfan1990** [comment]
@Barenboim 重新发了一个issue #1591
