### ISSUE TITLE
KAFKA客户端的几个问题

### ISSUE THREAD

**Issue by LZUXK** [sogou/workflow#1472]
手工模式：
1、set_offset(0) 和set_offset_timestamp(KAFKA_TIMESTAMP_EARLIEST)的区别是啥
2、KAFKA_TIMESTAMP_EARLIEST和KAFKA_TIMESTAMP_LATEST两个参数，我没发现有啥不一样，都是消费最新的消息
3、设置set_offset_timestamp参数为KAFKA_TIMESTAMP_LATEST，我是使用的debezium和kafka connect同步SQL SERVER CDC的数据，在SQL SERVER中同时变更两条数据，kafka客户端消费者命令可以完整的fetch到两条数据的变更消息，但是wf的kafka cli只能fetch到第一条

**Comment by Barenboim** [comment]
这几个问题看起来和Windows无关。我们看一下。应该都是配置相关的。

**Comment by LZUXK** [comment]
第三个问题：我用消费者组模式没有这个问题。手工模式有这个问题。
第四个问题：是我使用的问题，我删除了。

**Comment by Barenboim** [comment]
看了一下你在gitee上的源代码，toppar上的set_offset()应该不是让用户调用的，你只能设置task里的set_offset_timestamp，toppar上的offset会被覆盖。

我们的代码可能也有一些不合理，比如如果不允许用户设置toppar上的offset，是不是不应该暴露这个接口。另外还有一些内容实现的问题我们还需要review一下。你目前可通过client或task来设置offset，应该就没问题了。

**Comment by Barenboim** [comment]
我们会提交一版新的代码，解决toppar上offset timestamp不生效的问题。

**Comment by LZUXK** [comment]
> 看了一下你在gitee上的源代码，toppar上的set_offset()应该不是让用户调用的，你只能设置task里的set_offset_timestamp，toppar上的offset会被覆盖。
> 
> 我们的代码可能也有一些不合理，比如如果不允许用户设置toppar上的offset，是不是不应该暴露这个接口。另外还有一些内容实现的问题我们还需要review一下。你目前可通过client或task来设置offset，应该就没问题了。

好的

**Comment by LZUXK** [comment]
> 我们会提交一版新的代码，解决toppar上offset timestamp不生效的问题。

第三个问题是否有解决

**Comment by Barenboim** [comment]
> > 我们会提交一版新的代码，解决toppar上offset timestamp不生效的问题。
> 
> 第三个问题是否有解决

一个一个来……

**Comment by kedixa** [comment]
kafka partition中每条消息都有其唯一且自增的偏移量，常称为`offset`，手动消费时，可通过`KafkaToppar::set_offset`来设置偏移量。在Group模式下由内部统一管理偏移量，不可自由指定。

手动模式下，可通过`set_offset(offset)`指定一个绝对偏移量，表示我期望当前partition被消费的下一条消息的offset，而`0`表示的是该partition下的第一条消息。通常情况下，kafka集群会设置数据过期策略，一段时间后`offset==0`的消息可能会被删除，此时由于该offset的数据已经不存在，所以也无法被消费到。

此时，可通过`set_offset_timestamp(KAFKA_TIMESTAMP_EARLIEST)`来获取到当前partition下**尚未被删除的最旧的**那条消息，此前WFKafkaTask仅允许通过`KafkaConfig::set_offset_timestamp`设置Task级别的`offset_timestamp`，#1475 尝试修改了该逻辑，允许通过`KafkaToppar::set_offset_timestamp`为每个partition设置该参数。

之前的逻辑不会判断`KafkaToppar`上的`offset_timestamp`，而`KafkaConfig`上该参数的默认值是`KAFKA_TIMESTAMP_LATEST`，所以会得到**问题2**的结果。

在手动模式下，仅有在第一次发起消费请求时需要使用`set_offset_timestamp`，因为用户是不知道集群上当前的偏移量的，而从第二次请求开始应当根据上一次请求的结果，通过`set_offset`来设置下一条数据的`offset`，而不能每次请求都设置`set_offset_timestamp(KAFKA_TIMESTAMP_LATEST)`或其他的什么值，这样会因每次请求都拉取最新offset而错误地跳过某些消息。**问题3**或许是因该错误使用方式导致。

**Comment by Barenboim** [comment]
@LZUXK 麻烦用最新代码帮我们再试一下。

**Comment by LZUXK** [comment]
> @LZUXK 麻烦用最新代码帮我们再试一下。

问题二：试了可以的。
问题三：我用set_offset指定下一条数据的offset是可以的。但是为什么group模式下用set_offset_timestamp(KAFKA_TIMESTAMP_LATEST)没问题呢。手动模式下为啥不能用。

**Comment by kedixa** [comment]
自动模式之所以自动，即在于自动管理消费偏移量。kafka客户端在已知当前消费偏移量时，是不会看用户设置的timestamp的。

**Comment by LZUXK** [comment]
> 自动模式之所以自动，即在于自动管理消费偏移量。kafka客户端在已知当前消费偏移量时，是不会看用户设置的timestamp的。

好的，受教了。虽然不知道为什么这么设计。但是先用着，后续有问题再来请教。

**Comment by Barenboim** [comment]
> > 自动模式之所以自动，即在于自动管理消费偏移量。kafka客户端在已知当前消费偏移量时，是不会看用户设置的timestamp的。
> 
> 好的，受教了。虽然不知道为什么这么设计。但是先用着，后续有问题再来请教。

设计上有什么改进意见，也可以在这里交流哈。
