### ISSUE TITLE
使用xmake构建遇到一样的问题

### ISSUE THREAD

**Issue by int-fanle** [sogou/workflow#1473]
windows符号链接的问题,知道一些,主要是之前很少遇到...

xmake2.6.8 -> 2.7.8  set_exceptions这个解决了.

下面这个还是不行.
[ 30%]: ccache compiling.release src/util/json_parser.c
error: /mnt/hgfs/vmshare/github/workflow/_include/workflow/list.h:1:1: error: expected identifier or ‘(’ before ‘.’ token

_Originally posted by @gooker in https://github.com/sogou/workflow/issues/1253#issuecomment-1514382873_

**Comment by Barenboim** [comment]
xmake编译不过吗？我们的xmake-repo就是用xmake编译的。你是编译我们的库过不去，还是编译应用程序？

**Comment by int-fanle** [comment]
在编译 workflow，还没到tutorial



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月11日 17:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sogou/workflow] 使用xmake构建遇到一样的问题 (Issue #1473) |

xmake编译不过吗？我们的xmake-repo就是用xmake编译的。你是编译我们的库过不去，还是编译应用程序？

**Comment by Barenboim** [comment]
我这边xmake运行都没有问题啊，编译tutorial，test也正常。我的xmake版本是v2.8.6. 。

**Comment by int-fanle** [comment]
我重新拉代码试一下

**Comment by int-fanle** [comment]
哈哈，重新拉取代码就好了，应该是我自己哪里操作有问题
