### ISSUE TITLE
gotask设置执行时间 

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#1476]
如何给gotask设置任务的执行时间，如果时间到了，自动结束，往下执行

**Comment by Barenboim** [comment]
不是已经支持了吗？create_timedgo_task。
当然，我们无法中断你的执行函数，但是如果执行时间到直接callback，state=WFT_STATE_SYS_ERROR，error=ETIMEDOUT。

**Comment by Barenboim** [comment]
建议通过判断state是否为WFT_STATE_SUCCESS来确定时正常执行完成，还是超时（之前有一个版本，超时时的state不是ERROR而是ABORTED）。
另外需要注意的是，不要在你的执行函数里访问series，因为这种情况下series可能已经结束了。但执行函数里访问task没问题。

**Comment by HzjFirst** [comment]
好的，好的，没好好看，

**Comment by HzjFirst** [comment]
好的，好的，收到了，不好意思，没有好好看😂
