### ISSUE TITLE
自定义协议，某个请求收到后不需要进行响应，process中该怎么处理？

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1478]

**Comment by coderwxl** [comment]
是不用给*rsp赋值直接return就行了吗

**Comment by Barenboim** [comment]
关连接不？

**Comment by coderwxl** [comment]
关和不关分别怎样做？

**Comment by Barenboim** [comment]
如果是关闭连接的话，就调用一下server_task->noreply()接口，这样在原本回复的时机，直接关闭。
如果是保持连接，相关于回复一个空消息，并且keep_alive_timeout不为0。这种情况下，就是让resp序列化的结果为空，只要它的encode函数返回0就可以了。

**Comment by coderwxl** [comment]
好的，谢谢
