### ISSUE TITLE
不安装workflow，如何cmake导入，像add_subdirectory(glog)那样。

### ISSUE THREAD

**Issue by tothedistance** [sogou/workflow#1482]
如题，我看之前的issue好像例子里直接一个find_package，如果我还没编译workflow那_include还没生成，会报错。
有没有办法直接add_subdirectory。glog我是这么弄的。
因为github网络的关系，我是下载了固定版本的workflow，然后cmake解压缩后，add_subdirectory。glog可以，workflow似乎不行。
目前我只能cmake 外部命令执行workflow的build。

**Comment by tothedistance** [comment]
我大概看了一下glog，可能需要你们export。主要我是嵌入式交叉编译，所以不太想install。

**Comment by Barenboim** [comment]
大概怎么改呢？能不能PR一个我们先看一下。

**Comment by holmes1412** [comment]
hi，你可以使用这个文件导入吗：https://github.com/sogou/workflow/blob/master/workflow-config.cmake.in

**Comment by tothedistance** [comment]
我搞好了，现在提交pr

**Comment by tothedistance** [comment]
> hi，你可以使用这个文件导入吗：https://github.com/sogou/workflow/blob/master/workflow-config.cmake.in

find_package应该是可以的，之前不太懂，可能大家一般用find_package()比较多。下午研究了一下，现在也可以add_subdirectory了，这种新手比较容易。

**Comment by tothedistance** [comment]
https://github.com/sogou/workflow/pull/1483

**Comment by tothedistance** [comment]
![2024-01-24_21-33](https://github.com/sogou/workflow/assets/70138378/2d2167c0-22a6-46ef-a1e0-5745a971b28e)
a littel extraneous code.

**Comment by Barenboim** [comment]
非常感谢！我们简单review一下。

**Comment by tothedistance** [comment]
export多余了，加上`target_include_directory()`哪一行就行。
从报错的130行看，`${SHARED_LIB_NAME}`为空，你是执行的什么报错。workflow下直接`cmake -B build .`过不去，还是别的项目`find_package(workflow)` 过不去。

**Comment by holmes1412** [comment]
@tothedistance 你好，感谢你的需求，目前已经通过target_include_directories()将workflow的所有可能需要导出的target提前指定了，提了一个PR：https://github.com/sogou/workflow/pull/1485

验证了下你一开始的问题：'如果我还没编译workflow那_include还没生成，会报错。' 只要咱们项目设置好要依赖的项目（比如workflow）应该是不会报错的，比如这样写：
```
# demo CMakeLists.txt
target_link_libraries(demo my_lib workflow-shared)
```
麻烦看看是否符合你需要的哈～

**Comment by tothedistance** [comment]
我明天去公司试一下，但我感觉是不行的。你最新的cmake，add_subdirectory(workflow)以后需要再include(${WORKFLOW_INCLUDE})。而我理解的cmake就是要把依赖模块化，也就是workflow的include直接放在workflow这个target上。你现在用的是<$INSTALL_INTERFACE>，这个在非安装时是为0的，应该加上<$BUILD_INTERFACE>。
正常我应该是只需要一行add_subdirectory(workflow)，然后直接target_link_libraries(demo workflow-shared)就完事了。不需要include。target会自动计算头文件依赖的传递。
你前面说的报错我没有复现成功。

**Comment by tothedistance** [comment]
确认了，加个<$BUILD_INTERFACE>就行。

**Comment by holmes1412** [comment]
是的，加上<$BUILD_INTERFACE>之后，可以不用用户include，感谢指正～新的PR已经改了：https://github.com/sogou/workflow/pull/1487

**Comment by Barenboim** [comment]
@tothedistance 能用了的话麻烦star一下项目啊。
