### ISSUE TITLE
想请问一下如何在本地部署

### ISSUE THREAD

**Issue by CodeExplorerQuantumScripter** [sogou/workflow#1484]
本人cpp菜鸟，本地部署报错了。已经在cmakelist加上了set(CMAKE_CXX_STANDARD 11)，但是在编译的时候报错
#error CPLUSPLUS VERSION required at least C++11. Please use "-std=c++11".
 ^
CPPFolder/workflow/src/include/workflow/WFGlobal.h:24:10: fatal error: 'C++11_REQUIRED' file not found
#include <C++11_REQUIRED>
         ^~~~~~~~~~~~~~~~
255 warnings and 4 errors generated.

目前很抓瞎，跪求大佬们帮助！

**Comment by Barenboim** [comment]
如果你对cmake不熟的话，可以直接用这个工具来生成工程：https://github.com/sogou/srpc/tree/master/tools

**Comment by CodeExplorerQuantumScripter** [comment]
感谢大佬的回复。已经编译出了可执行文件。但是我是想通过Clion或者vscode启动，然后debug学习一下源码的。是否有什么方法可以在Clion中解决题目上编译报错的问题呢？

**Comment by Barenboim** [comment]
Clion我记得直接把项目拉过去就可以了啊。要不你先用一下tutorial里的，这个用Clion肯定可以编译的，先Debug一下tutorial里的代码，然后你改里面的Cmake，增加你自己的示例就可以了。

**Comment by CodeExplorerQuantumScripter** [comment]
我是拉下来以后按照文档
git clone https://github.com/sogou/workflow # From gitee: git clone https://gitee.com/sogou/workflow
cd workflow
make
cd tutorial
make

然后进入第一个例子，无法启动起来
![image](https://github.com/sogou/workflow/assets/157099995/26b31b73-9c5c-4d37-ac19-7f54a4ed7503)

自己很少在github拉项目部署，不会的比较多。麻烦了

**Comment by Barenboim** [comment]
第0个例子就是在8888商品上打开一个http server。你启动之后，再按一下回车就退出了，你说没有办法启动是不是多按了一下enter键啊？
你可以在浏览器上访问这个server，例如在浏览器地址栏输入http://127.0.0.1:8888/ ，会返回一个Hello World!

**Comment by CodeExplorerQuantumScripter** [comment]
是的是的，我原来是写java的，代码含义完全可以理解。主要是不会部署项目，就是点击start那个按钮以后，编译器会进行编译，开始build；上述报错就是在build过程中报错的。
![image](https://github.com/sogou/workflow/assets/157099995/d7fe0382-5dae-469b-94c9-d23d91e88670)

**Comment by Barenboim** [comment]
从图上看，你不是已经编译出可执行文件了吗

**Comment by Barenboim** [comment]
你说的部署项目是什么意思？你用静态链接的方式，可执行文件直接运行就可以了，没必要那么麻烦。外部make完，把_lib里的.so文件删了，只留下.a。然后编译，就肯定是静态链接了。

**Comment by Barenboim** [comment]
@CodeExplorerQuantumScripter 问题解决了么？
