### ISSUE TITLE
使用自定义协议时，收发数据和实际数据大小不一致

### ISSUE THREAD

**Issue by dingyaoyang** [sogou/workflow#1489]
我使用了[message.cc](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-10-user_defined_protocol/message.cc)的自定义协议

当进行数据收发时，我发现有时（从第二次发数据开始必出现）实际收到的数据长度会比body_size（https://github.com/sogou/workflow/blob/773aef1f40c5d15ad791dcefd97f608a1044100e/tutorial/tutorial-10-user_defined_protocol/client.cc#L85 ）长一点，
像这样：
`"{\"data\":1}80,141,22,18,5\301\006\002"`

但我期望收到的数据是`"{\"data\":1}"`

客户端最先发生这种情况，起初我用字符串截取解决
`res.assign(res.substr(0,body_size));`

后来发现，服务端在第2个连接来时，收到的数据也会比实际数据长一点，这导致json::parse解析失败，这是bug吗？

使用了[nlohmann](https://github.com/nlohmann/json)的json，传的json数据
```
{
...
"arr":[246,240,68,245,43,......]
...
}
```

arr实际是一个unsigned char数组，使用json["arr"] = arr;时自动转化成整形数组，arr的实际内容可能是这样：
`arr = ['\123','\201','a','b',...];`

**Comment by dingyaoyang** [comment]
或许应该在结尾加上'\0'
`*(char*)(body+body_size) = '\0';`

**Comment by Barenboim** [comment]
你好，我们内置有TLV消息，你可以直接用的：https://github.com/sogou/workflow/blob/master/docs/about-tlv-message.md

tutorial里那个例子，确实没有\0的消息结尾，只是为了演示怎么解析和编码消息。
