### ISSUE TITLE
workflow的使用场景

### ISSUE THREAD

**Issue by Ricardo-M-Mao** [sogou/workflow#1491]
如果一个项目只用到workflow中某一些功能例如http服务，workflow是否太过庞大不如使用单独的小型http框架呢

**Comment by Barenboim** [comment]
你好，你可以对比一下，我们的库其实是最小的，完整编译，不带调试信息的库600KB多一些。运行内存也很小，你可能找不到更小的企业级http框架了。

如果你是嵌入式环境，还可以裁剪编译，最小编译的方式是：
$ make REDIS=n MYSQL=n UPSTREAM=n CONSUL=n
这样可以再裁掉100多KB多二进制代码。

如果不需要SSL，还可以使用nossl分支。不过，其实都没必要……

**Comment by Ricardo-M-Mao** [comment]
嗯 对比了一下 确实相较于其他框架小了很多 打算试试

**Comment by Barenboim** [comment]
如果用来做restful服务，可以用基于workflow的wfrest，更加方便。
https://github.com/wfrest/wfrest



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月31日(周三) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow的使用场景 (Issue #1491)




 
嗯 对比了一下 确实相较于其他框架小了很多 打算试试
