### ISSUE TITLE
http请求去除connection header

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1495]
想要在发送http的时候禁用connection这个header pair 目前没有看到相应的接口 都是默认在发送请求时加上了这个header pair ,能新增一个接口去掉这个header pair么

**Comment by Barenboim** [comment]
你好。我们目前已经支持对header的删除了，具体代码修改可以看这个PR：https://github.com/sogou/workflow/pull/1492
不过，你的需求是删除connection这个header。这个header是框架在发送消息之前再加的。所以，你要删除的话需要给task设置一个prepare函数，设置prepare的接口在WFClientTask上。具体的方法如下：
~~~cpp
void f()
{
    WFHttpTask *task = WFTaskFactory::create_http_task(...);
    auto *client_task = static_cast<WFClientTask<protocol::HttpRequest, protocol::HttpResponse> *>task;
    client_task->set_prepare([](WFHttpTask *t) {
        protocol::HttpHeaderCursor cursor(t->get_req());
        cursor.find_and_erase("Connection");
    });
    task->start();
}
~~~
HttpHeaderCursor的find_and_erase()操作，删除这个名字下的第一个header，如果可能存在多个同名的header，则需要写成循环。例如：
~~~cpp
void f()
{
    while (cursor.find_and_erase("Cookie"))
        ;
}
~~~

**Comment by Barenboim** [comment]
@18328594608 你好，请问是否解决了问题？

**Comment by 18328594608** [comment]
感谢支持!
最近在改业务上面的东西 这个还没更新过代码去试,我周一去试过之后给您回复.

**Comment by 18328594608** [comment]
后续我在业务上验证过了。使用task新增prepare的方式能够解决我的问题. 感谢支持.

**Comment by Barenboim** [comment]
请问一下，你那边为什么有这个删除connection header对需求呢？删除之后，对连接是否保持的协商可能不准确。

**Comment by 18328594608** [comment]
这边是因为对向服务器对于这个字段的支持有bug, 在这个字段存在的时候,多次发送请求,他那边服务会拒绝请求.暂时那边改不了就只能先把这个字段删除掉. 连接是否保持这个不考虑,只要能满足正常的回包response功能就行.

**Comment by Barenboim** [comment]
> 是因为对向服务器对于这个字段的支持有bug, 在这个字段存在的时候,多次发送请求,他那边服务会拒绝请求.暂时那边改不了就只能先把这个字段删除掉. 连接是否保持这个不考虑,只要能满足正常的回包response功能就行.

好的。之后可以吧服务器也改用workflow实现😂

**Comment by 18328594608** [comment]
> > 是因为对向服务器对于这个字段的支持有bug, 在这个字段存在的时候,多次发送请求,他那边服务会拒绝请求.暂时那边改不了就只能先把这个字段删除掉. 连接是否保持这个不考虑,只要能满足正常的回包response功能就行.
> 
> 好的。之后可以把服务器也改用workflow实现😂

那是一个windows 下的中间件服务 比较古老了 等后面淘汰哈哈😄
