### ISSUE TITLE
workflow在windows上的编译是否不支持mingw？

### ISSUE THREAD

**Issue by scarftree** [sogou/workflow#1497]
如题，是否不支持mingw编译器

**Comment by holmes1412** [comment]
你好，是的不支持MINGW~

**Comment by scarftree** [comment]
> 你好，是的不支持MINGW~

那有什么轻量版的编译器可以用？

**Comment by scarftree** [comment]
windows上，直接使用cmake -B build -S .命令提示
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
一般怎么设置指定编译器呢

**Comment by Barenboim** [comment]
> windows上，直接使用cmake -B build -S .命令提示 CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage 一般怎么设置指定编译器呢

你好，可以参考我们Windows分支首页的编译指引。
不过，如果你对Windows编译也不熟悉，强烈推荐再Windows上安装WSL 2，然后使用Linux版，会方便很多。我们目前对Windows的支持力量不足。

**Comment by holmes1412** [comment]
@scarftree 你好，我们不是很了解windows开发环境，看了下以前群友的相关讨论，你可以使用g++，但是如果不指定一般也会会使用操作系统的默认设置才对。

可以试一下这样 `cmake -B build -S . -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++` 么？

**Comment by scarftree** [comment]
> @scarftree 你好，我们不是很了解windows开发环境，看了下以前群友的相关讨论，你可以使用g++，但是如果不指定一般也会会使用操作系统的默认设置才对。
> 
> 可以试一下这样 `cmake -B build -S . -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++` 么？
回到另一个报错
CMake Error at CMakeLists.txt:6 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory

**Comment by Barenboim** [comment]
你好。请问你是下载了我们的windows分支吧？主分支只支持Unix系统。我们的Windows分支主页上有编译方法的描述。

另外，如果你也不熟悉Windows构建，还是建议用WSL来运行Linux版本。

**Comment by scarftree** [comment]
> 你好。请问你是下载了我们的windows分支吧？主分支只支持Unix系统。我们的Windows分支主页上有编译方法的描述。
> 
> 另外，如果你也不熟悉Windows构建，还是建议用WSL来运行Linux版本。

想问一下在tutorial下执行make的，编译目的是什么？谢谢。

**Comment by Barenboim** [comment]
tutorial里make出来的可执行文件，就在tutorial目录里。
