### ISSUE TITLE
客户端断开后，服务端的任务能自动取消吗

### ISSUE THREAD

**Issue by jim-yefeng** [sogou/workflow#1517]
客户端超时是10s， 但是服务端收到消息后有多个task步骤， 某个步骤网络抖动，读数据库或者缓存的时间延长了一下，10s内处理不完。
服务端检测到客户端10s断开事件后，能中断未完成的task流吗

**Comment by Barenboim** [comment]
可以啊。利用连接上下文，可以捕捉到连接关闭事件：
~~~cpp
void process(WFHttpTask *task)
{
    if (task->get_seq() == 0) {
        WFConnection *conn = task->get_connect();
        void *ctx = create_my_ctx();
        conn->set_context(ctx, [](void *ctx) {
         ...
        });
    }
    ...
}
~~~
get_connection函数只能在server task的process或callback过程中调用，用于获得当前连接。
set_context设置一个连接上下文，第二个参数是一个deleter，用于在连接关闭时删除context。
由于可能是长连接，所以只需要在连接上第一个任务设置context和deleter。之后的任务，如果调用conn->get_context()也可以得到设置的上下文。
相关文档：https://github.com/sogou/workflow/blob/master/docs/about-connection-context.md

**Comment by Barenboim** [comment]
此外，server task有个closed()方法，可在回复前的任何时刻，判断连接是否已经被关闭。

**Comment by jim-yefeng** [comment]
谢谢回复，closed方法看起来更简单，不过不能终止已经启动但是还未运行到callback的任务

**Comment by Barenboim** [comment]
> 谢谢回复，closed方法看起来更简单，不过不能终止已经启动但是还未运行到callback的任务

是的，一般来讲，closed()是在任务链里某个任务callback里调用，如果发现连接已经关闭，就不在加入新任务，这时候还可以直接调用series->cancel()，不用再尝试reply()了。

中断任务比较困难。用的比较多的是，在某一路数据超时的时候，提前reply()，但超时的任务还会一直执行到正常结束。我目前正在写一个WFSelectorTask来方便用户实现这个功能，有点类似golang的select。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1518
