### ISSUE TITLE
计算线程相关问题

### ISSUE THREAD

**Issue by awinds** [sogou/workflow#1520]
1、process函数中在计算线程中执行的吗？
2、计算线程是你创建server实例的时候就启动了吗？
3、我看到相关上下文的doc说明，但是第一次的上下文需要自己设置进去，有没有可能在server实例的时候给init和uninit回调设置上下文？
4、process函数中除了上下文有没有办法获取一些线程的唯一性数据，像threadId或threadIndex等等

**Comment by Barenboim** [comment]
1、process函数运行在网络线程里。如果你希望process运行在计算线程，可以看一下这个issue：https://github.com/sogou/workflow/issues/660 。我们的RESTful项目[wfrest](https://github.com/wfrest/wfrest)也支持计算型handler，每个handler还支持不同的计算队列。原理也issue里的方法差不多。
2、计算线程是使用第一个计算任务的使用启动的。
3、你说的是process的上下文吗？std::function可以任意绑定上下文的吧。如果是面向切面编程相关，还是参考[wfrest](https://github.com/wfrest/wfrest)里的实现。
4、线程唯一信息你可以自己设置thread local。除此之外，可以利用pthread的set_speicific等操作。

**Comment by Barenboim** [comment]
> @Barenboim #660 这种改写server的方式和直接在process函数里启动一个计算任务有什么区别么，感觉应该是等价的吧？

本质上肯定是等价的，但使用方就可以不用关心计算任务了。
另外，像wfrest里还可以根据path配置就很有用了：
https://github.com/wfrest/wfrest/blob/main/docs/compute_handler.md

**Comment by awinds** [comment]
如果是执行时间比较长的请求可以放到计算线程，这个是没有问题的，有几点关于上下文的还想了解下：
1、看到wfrest的切片编程逻辑，有before和after实时，但是这个也是处在接收到请求后再去先before->process->after，如果是一些长连接，如mysql、redis，每个请求都去你做before和after就没有必要，所以才提到可否在请求外有before和after？
2、我们具体业务会有一些上下文的唯一性，就是一个环境变量只会绑定到一个线程（process），具体是网络线程还是计算线程就看具体实现，所以才会提到需要没有任何请求的时候线程（process）先启动并有回调可实现环境变量的绑定。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 感谢解惑：）

**Comment by Barenboim** [comment]
> 如果是执行时间比较长的请求可以放到计算线程，这个是没有问题的，有几点关于上下文的还想了解下： 1、看到wfrest的切片编程逻辑，有before和after实时，但是这个也是处在接收到请求后再去先before->process->after，如果是一些长连接，如mysql、redis，每个请求都去你做before和after就没有必要，所以才提到可否在请求外有before和after？ 2、我们具体业务会有一些上下文的唯一性，就是一个环境变量只会绑定到一个线程（process），具体是网络线程还是计算线程就看具体实现，所以才会提到需要没有任何请求的时候线程（process）先启动并有回调可实现环境变量的绑定。

thread local不能解决你的问题么？就是process函数所在文件里，写一个thread local变量。我们以前也这么用过。不过，需要注意的是，thread local变量可能会在所有的线程里都有一份。如果数据比较大，使用的方法应该是：
~~~cpp
void process(WFHttpTask *task)
{
    thread_local static MyData data(...);
    ....
}
~~~
这样应该就是每个process线程里初始化一个了。

**Comment by Barenboim** [comment]
@awinds
