### ISSUE TITLE
mysql URL里密码的转义

### ISSUE THREAD

**Issue by iamysx** [sogou/workflow#1522]
HI，现在遇到一个问题，连接数据库的时候报error msg: URI Parse Failed 错误，
mysql://username:password@127.0.0.1:8899/db
我的 password密码中存在 @ 符号，这里是不是会导致解析失败，如果是这个导致的话能转义吗？

**Comment by holmes1412** [comment]
你好，需要urlencode一下哈~

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/issues/1310
StringUtil::url_encode_component();

**Comment by iamysx** [comment]
static void task_ga_http_req(WFHttpTask *task)
{
    protocol::HttpResponse *resp = task->get_resp();

	SeriesWork *series = series_of(task);
	server::HttpContextBase *context = (server::HttpContextBase *)series->get_context();	
	auto *proxy_resp = context->server_task->get_resp();

    std::string body;
    Json::Value json;

	if (0 != server::get_http_chuncked_json(task, body, json))
	{
		printf("recevie error:%s\n", body.c_str());
		return;
	}
	printf("recevie success:%s\n", body.c_str());

	std::string username = "";
	
	const Json::Value *data_json = nullptr;
	if (utils::json::get_object(json, "data", data_json))
	{
		printf("error: data is error\n");
		return;
	}
	
	if (0 != utils::json::get_attr(*data_json, "username", username))
	{
		printf("error: username is empty\n");
		return;
	}
	
	WFMySQLTask *to_task;

	std::string url_b = "mysql://root:R00t@xxx2018@127.0.0.1:3306";
	
	std::string url_f  = StringUtil::url_encode_component(url_b);

	printf("url_f:%s\n", url_f.c_str());

	std::string insert_user = "INSERT mng.user VALUES (1, NULL,'" + username + 
				"',NULL,27,NULL,NULL,38,1,2,NULL,0,NULL,NULL,NULL,0,0,'" + username +
				"',NULL,NULL,0,0,NULL,NULL,NULL,0,NULL, NULL, NULL, 0,0,1712889474,"
				"0,NULL,0,NULL,'','','',NULL,0,100,0,0,'','0000000104','lwf','','')";

	printf("insert_user:%s\n", insert_user.c_str());
	
	to_task = WFTaskFactory::create_mysql_task(url_f, 5, task_ga_mysql_req);
	to_task->get_req()->set_query(insert_user);
	
    series->push_back(to_task);    	

    return;
}

输出：
do_ga_test
recevie success:{"code":"SUCCESS", "data":{"username":"user_525"}}
url_f:mysql%3A%2F%2Froot%3AR00t%40xxx2018%40127.0.0.1%3A3306
insert_user:INSERT mng.user VALUES (1, NULL,'user_525',NULL,27,NULL,NULL,38,1,2,NULL,0,NULL,NULL,NULL,0,0,'user_525',NULL,NULL,0,0,NULL,NULL,NULL,0,NULL, NULL, NULL, 0,0,1712889474,0,NULL,0,NULL,'','','',NULL,0,100,0,0,'','0000000104','lwf','','')
error msg: URI Parse Failed

已经使用了url_encode_component转义还是报的这个错呢。

**Comment by iamysx** [comment]
也就是这里的 @ 符号在用在密码中了，和后面的 @ ip重复了，也就是 url里面出现了两个 @ ，这样解析的时候错了，应该是这里的问题吧，即便使用url_encode把 @ 转成 %40，这不是还是两个吗？是不是还是没解决呢？

**Comment by Barenboim** [comment]
std::string url_f = "mysql://root:" + StringUltil::url_encode_component("R00t@xxx2018") + "@127.0.0.1:3306";
应该是这么写吧。上面的issue里也有。

**Comment by iamysx** [comment]
嗯，搞定了，另外咨询一下呢，mysql连接这里会是长连接吗？也就是会不会每次一条语句都需要重新连接一下？

**Comment by Barenboim** [comment]
默认长连接，和http一个道理。

但是，如果想执行事务（以及PREPARE），需要用到WFMySQLConnection，确保多个请求会在同一个连接上发送。

一般情况，用WFTaskFactory来创建任务就可以了。

**Comment by iamysx** [comment]
也就是我会在一个HTTP请求里面依次执行多条SQL操作，比如先查询存不存在，若不存在则插入，插入完成后再插入另外的数据表，相当于可能会有三四次数据库操作，这种场景。

**Comment by Barenboim** [comment]
就看你有没有事务性的需求了。如果这些插入必须全部成功或全部失败，不能接受不一致，就需要用到事务。

**Comment by iamysx** [comment]
那mysql连接的时候有设置最大连接数的吗？比如我看我们现在跑有1000多个连接，比如能不能限制到200之类的呢。类似连接池的设置

**Comment by Barenboim** [comment]
client对一个server，默认最大连接数就是200，你跑到1000多是不是改过参数了？

**Comment by Barenboim** [comment]
如果是不占线程的限制连接数，并且让请求不会失败，可以用资源池来实现：https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md

**Comment by iamysx** [comment]
还有一个问题，当我的sql语句是查询select的时候没有执行回调，当第二次查询的时候回调才调用了，但其它sql语句，比如delete,insert等回调就是正常的。
	std::string select_user = "select * from xxx.user where account='" + username + "';";

	printf("select_user:%s\n", select_user.c_str());
	
	to_task = WFTaskFactory::create_mysql_task(url_f, 5, task_ga_mysql_select);
	to_task->get_req()->set_query(select_user);
	
    series->push_back(to_task);  
查询语句如上，这种写法有问题吗？如果我把语句改成
std::string select_user = "delete from xxx.user where account='" + username + "';";
就会正常回调了。

**Comment by iamysx** [comment]
void task_ga_mysql_select(WFMySQLTask *task)
{
	SeriesWork *series = series_of(task);
	
	server::HttpContextBase *_context = (server::HttpContextBase *)series->get_context();	
	GaContext *context = dynamic_cast<GaContext *>(_context);
	
	auto *proxy_resp = context->server_task->get_resp();

	protocol::MySQLResponse *resp = task->get_resp();

	protocol::MySQLResultCursor cursor(resp);
	const protocol::MySQLField *const *fields;
	std::vector<protocol::MySQLCell> arr;

	printf("select result:%llu", cursor.get_affected_rows());

	if (task->get_state() != WFT_STATE_SUCCESS)
	{
		printf("error msg: %s\n",WFGlobal::get_error_string(task->get_state(),task->get_error()));	
		proxy_resp->append_output_body("select user error\n");
		return;
	}
	else if (cursor.get_cursor_status() == MYSQL_STATUS_OK)
	{				
		printf("select success\n");
        }
}
这是我的回调函数

**Comment by Barenboim** [comment]
这不会的啊。select语句和delete一样，都会callback的。一个task一次callback。
你可以用我们tutorial里面的mysql client试一下。应该不会有问题的。

**Comment by Barenboim** [comment]
@iamysx 搞定了吗？
