### ISSUE TITLE
框架现在支不支持创建多个tcp tls客户端任务，每个tls客户端使用的证书私钥以及ca证书都不同的通信方式

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1524]

**Comment by Barenboim** [comment]
这个问题你之前好像发过issue，当时我们没有解决。

我觉得这个功能还是有必要支持一下的。我跟进一下。你多个client task是访问不同的协议（http/mysql这些），还是相同的协议呢？

**Comment by coderwxl** [comment]
相同的协议，目前用的是tcpsocket+tls，支持这个功能后麻烦给我说下。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1525
使用方法：
~~~cpp
#include "workflow/UpstreamManager.h"
#include "workflow/EndpointParams.h"

int main()
{
    struct EndpointParams ep_params = ENDPOINT_PARAMS_DEFAULT;

    params.ssl_ctx = SSL_CTX_new();
    ...
    UpstreamManager::upstream_create_round_robin("www.sogou.com", false);
    UpstreamManager::upstream_add_server("www.sogou.com", "www.sogou.com", &ep_params);

    params.ssl_ctx = SSL_CTX_new();
    ...
    UpstreamManager::upstream_create_round_robin("127.0.0.1", false);
    UpstreamManager::upstream_add_server("127.0.0.1", "127.0.0.1", &ep_params);
}
~~~
URL里用这些upstream名就可以了，可以和目标IP或域名同名。程序退出之前先把你自己的这些ctx释放掉。
我没有测试，你跑通了说一下。

**Comment by Barenboim** [comment]
mysqls和使用https proxy的任务，还是用全局的。我想想能不能也用上这个。

**Comment by coderwxl** [comment]
params是什么类型

**Comment by Barenboim** [comment]
> params是什么类型

struct EndpointParams

上面有吧？

**Comment by coderwxl** [comment]
struct EndpointParams
{
	size_t max_connections;
	int connect_timeout;
	int response_timeout;
	int ssl_connect_timeout;
	bool use_tls_sni;
};
里面没有ssl_ctx

**Comment by Barenboim** [comment]
你看我的fork啊。从我的fork拉一下代码。你这边可以用了，我再merge。

**Comment by Barenboim** [comment]
上面不是有个PR地址么？

**Comment by Barenboim** [comment]
又改了个小问题，支持不同的upstream名指向同一个IP或域名，分别使用不同的ssl_ctx。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1525
实现方式改了，不使用upstream了。用户需要自己设置域名或IP地址下的ssl_ctx：
~~~cpp
int main()
{
    std::string host = ...;
    unsigned short port = ...;
    SSL_CTX *ctx = ...;
    WFGlobal::set_ssl_client_ctx(host, port, ctx);
    ...
}
~~~
还没改完。

**Comment by coderwxl** [comment]
大佬，改完了吗

**Comment by Barenboim** [comment]
还没有。我尽量今晚出一个可用的版本。你到时候可以先从我的fork拉。

**Comment by Barenboim** [comment]
可能又要改设计了，没那么快可以完工。

**Comment by Barenboim** [comment]
新的PR：https://github.com/sogou/workflow/pull/1530

**Comment by coderwxl** [comment]
我测试了下有问题。我开了30个线程，线程里面会定时创建临时tls客户端任务给服务端发请求，只有第一轮请求的15个客户端收到了响应数据，其它的没有收到响应数据（append函数没走进去），接下来所有线程就彻底都收不到服务端的响应了。

另外请问下SSL_CTX*需要我在外面手动释放还是框架会自动释放。

**Comment by Barenboim** [comment]
我们期待是在task生命周期之内，用户确保SSL_CTX有效。

正确性问题我们再测一下。

**Comment by Barenboim** [comment]
先合并到主项目的ssl_ctx分支了。具体用法，你参考一下WFMySQLConnection里这个：
https://github.com/sogou/workflow/blob/34ac0c0fa37ef2cbd184b91283301b635537c732/src/client/WFMySQLConnection.h#L67
你把你的网络任务强传成WFComplexClientTask<MyRequest, MyResponse>类型，调用这个类的void set_ssl_ctx(SSL_CTX *)接口就可以了。ssl_ctx的生命周期需要覆盖task的生命周期。

**Comment by coderwxl** [comment]
没事，我不着急，等你填上坑了我再用

**Comment by Barenboim** [comment]
你先试一下啊，现在也是可以用的。就是用这个函数：
https://github.com/sogou/workflow/blob/34ac0c0fa37ef2cbd184b91283301b635537c732/src/factory/WFTaskFactory.h#L449
我们也需要用户的使用建议才能确定怎么改。

**Comment by coderwxl** [comment]
我现在就是调用这个函数创建的任务，但是有我上面说的异常问题
	static T *create_client_task(enum TransportType type,
								 const struct sockaddr *addr,
								 socklen_t addrlen,
								 SSL_CTX *ssl_ctx,
								 int retry_max,
								 std::function<void (T *)> callback);

**Comment by Barenboim** [comment]
> 我测试了下有问题。我开了30个线程，线程里面会定时创建临时tls客户端任务给服务端发请求，只有第一轮请求的15个客户端收到了响应数据，其它的没有收到响应数据（append函数没走进去），接下来所有线程就彻底都收不到服务端的响应了。
> 
> 另外请问下SSL_CTX*需要我在外面手动释放还是框架会自动释放。

你是说这个问题吗？

**Comment by coderwxl** [comment]
是的。
用上面那个create_client_task创建任务后应该不需要再调用set_ssl_ctx来设置ctx吧

**Comment by Barenboim** [comment]
对，struct sockaddr + socklen 创建的，只能在create里设置，后面set_ssl_ctx无效。我看一下你说的问题。

**Comment by Barenboim** [comment]
@coderwxl 改了一点小问题，麻烦再试一下。觉得你说的现象有点奇怪，这边看不也会有这种问题。

**Comment by coderwxl** [comment]
我发现一个严重的问题，和你这次改的没关系，我开了30个线程，每个线程里都通过create_client_task创建客户端任务给服务器发送消息，然后只有17个线程的客户端收到了服务端的响应数据，框架没报什么异常，这是我创建客户端的代码：
![image](https://github.com/sogou/workflow/assets/57793691/27ff514a-f392-4929-b967-f5f106b9dd1a)

**Comment by coderwxl** [comment]
我知道导致我上面说的异常原因了，是因为你这次改动没有使用连接池，导致每次都是新连接，但是服务端对连接数有限制，应该超过限制就会关闭新连接，从而导致后面就收不到服务端的响应了。

**Comment by Barenboim** [comment]
现在的代码还是没有复用连接吗？不应该啊。是不是你自定义协议没有调用set_keep_alive()？连接复用方面，和之前的没有什么区别。

**Comment by coderwxl** [comment]
不是我的问题，我只是调用不同的create_client_task函数，其它的没变：
![image](https://github.com/sogou/workflow/assets/57793691/8f89fcd8-ae97-4204-bd02-d026f7d2355c)

**Comment by Barenboim** [comment]
你每次的ctx指针变了吗？不同的ctx（指针值），不会复用连接的。

**Comment by coderwxl** [comment]
可以了，我测了下没问题。

**Comment by coderwxl** [comment]
create_http_task能否也加上ssl_ctx的支持

**Comment by Barenboim** [comment]
http的话，你可以模仿WFMySQLConnection的办法设置一下。可以自己搞个http client来创建任务，把ssl ctx封装进去。

如果加在我们的任务工厂里，那要加一堆函数。

**Comment by coderwxl** [comment]
好的，感谢大佬！
