### ISSUE TITLE
我看了workflow和wfrest，都写得很优雅，上手很快👍🏻。但是我有个疑问，Web服务器为什么不用go和gin呢，而要用workflow？选择workflow的优势有啥？

### ISSUE THREAD

**Issue by chuzilaolin** [sogou/workflow#1529]
如果用来做restful服务，可以用基于workflow的wfrest，更加方便。
https://github.com/wfrest/wfrest

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月31日(周三) 下午2:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow的使用场景 (Issue #1491)

 
嗯 对比了一下 确实相较于其他框架小了很多 打算试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

_Originally posted by @Barenboim in https://github.com/sogou/workflow/issues/1491#issuecomment-1918503938_

**Comment by Barenboim** [comment]
这个语言都不一样，怎么对比啊。那个顺手就用那个吧。workflow本身也不是为了做web server，主要是提供一个高性能的编程范式。

**Comment by chuzilaolin** [comment]
明白了，workflow可以做Web server，但不止于Web server。
