### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [sogou/workflow#153]
I would like to point out that identifiers like “[`_POLLER_H_`](https://github.com/sogou/workflow/blob/c4fe05eecda5b88da1a5c5fee3db9918ad172d99/src/kernel/poller.h#L19 "Update candidate")” and “[`_WFKAFKACLIENT_H_`](https://github.com/sogou/workflow/blob/52d64c00b11bc7a4c8305da07e1aefc60e50aead/src/client/WFKafkaClient.h#L19 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by Barenboim** [comment]
Thanks!
