### ISSUE TITLE
用WFFileIOTask写入字符串到文件里出现乱码

### ISSUE THREAD

**Issue by chuzilaolin** [sogou/workflow#1532]
<img width="806" alt="image" src="https://github.com/sogou/workflow/assets/82101835/413a5669-053a-472a-9fb3-c7b2b99e7747">

在上面的代码中，我将一个字符串buf写入文件里，文件用vim打开是乱码的；
而我用注释掉的两行系统调用的方式写入文件，打开就是正确的;
请问是我没用对吗？

**Comment by Barenboim** [comment]
你buf是局部变量，任务是异步的，你传进来的buf生命周期必须可以到任务结束。

你写成static buf[1024]应该就可以了。或者malloc出来。

**Comment by chuzilaolin** [comment]
感谢回答，问题解决了
