### ISSUE TITLE
咨询tutorial-05-http-proxy的reply_callback()

### ISSUE THREAD

**Issue by Treston-W** [sogou/workflow#1537]
关于tutorial-05，我理解有三个角色：
网页客户端client、proxy server（咱们要实现的代理服务器）、web server（真正存储资源的服务器）

关于涉及到的四个回调函数，我的理解如下：
【process()】：proxy server收到来自client请求时触发，目的是组织proxy server向web server的请求
【http_callback()】：proxy server收到来自web server回复时触发，目的是组织proxy server向client的回复 
【series_callback()】：delete (tutorial_series_context *)series->get_context();当前series内的所有task结束后触发，目的是释放context资源
**【reply_callback()】：这个回调函数我没有理解，触发时机是什么时候？目的是什么？**

**Comment by Treston-W** [comment]
> 你好。你还是代码看得比较仔细的。前面几个回调函数的时机描述都没有问题。
> 
> reply_callback()是server task的callback。server task和client task都是WFHttpTask类型，callback的时机也是一样的，都是在http请求交互完成之后。对于server task来讲，就是把reply写完整写入tcp send buffer。当然，还有一种情况是失败了。
> 
> 所以，reply_callback的主要目的就是看回复成功了没有。并且，server task在callback之后，还可以继续向series里放入新的任务的。例如加一个上报请求状态给监控服务器的网络任务。
> 
> 调用顺序：process->http_callback->reply_callback->series_callback。

谢谢谢爷！我比对几个demo测试了一下，现在对几个回调的理解清晰了。

**Comment by HT-Sun** [comment]
> 你好。你还是代码看得比较仔细的。前面几个回调函数的时机描述都没有问题。
> 
> reply_callback()是server task的callback。server task和client task都是WFHttpTask类型，callback的时机也是一样的，都是在http请求交互完成之后。对于server task来讲，就是把reply写完整写入tcp send buffer。当然，还有一种情况是失败了。
> 
> 所以，reply_callback的主要目的就是看回复成功了没有。并且，server task在callback之后，还可以继续向series里放入新的任务的。例如加一个上报请求状态给监控服务器的网络任务。
> 
> 调用顺序：process->http_callback->reply_callback->series_callback。

你好，刚开始学习网络编程，对于回调做法非常困惑，所以我仍旧有很多问题。
1. 在proxy server调用process过程时，存在一个proxy_task，这个任务时如何产生的。上述的server task指的是不是就是这个proxy_task。从角色上看，proxy_task是proxy server为client提供服务的，所以会被称作server task?
2. proxy_task存在于一个series中，process过程创建了一个向web server请求的http_task，并将该任务追加在当前proxy_task所在的series。在process执行完毕时，proxy_task中的resp仍旧是初始化状态，完全没有能力完整写入tcp send buffer。
3. 由于series中出现了新的任务http_task（proxy server通过该任务向web server请求服务，所以被称为client task?)，在接收到web server的回复后，触发http_callback回调。在执行http_task到触发回调的过程中，proxy_task的状态是暂用线程等待还是被挂起了。
4. 在http_callback触发开始执行后，通过series的上下文更新了proxy_task中的resq，此时对于proxy_task而言，写入tcp send buffer的条件已经具备，写入的过程是如何触发的。
5. 我的理解是：proxy_task->process->http_task->http_callback->proxy_task->reply_callback->series_callback？但是这里面应该有多线程才对，对于这个series任务流而言，线程是如何切换的？

**Comment by Barenboim** [comment]
> > 你好。你还是代码看得比较仔细的。前面几个回调函数的时机描述都没有问题。
> > reply_callback()是server task的callback。server task和client task都是WFHttpTask类型，callback的时机也是一样的，都是在http请求交互完成之后。对于server task来讲，就是把reply写完整写入tcp send buffer。当然，还有一种情况是失败了。
> > 所以，reply_callback的主要目的就是看回复成功了没有。并且，server task在callback之后，还可以继续向series里放入新的任务的。例如加一个上报请求状态给监控服务器的网络任务。
> > 调用顺序：process->http_callback->reply_callback->series_callback。
> 
> 你好，刚开始学习网络编程，对于回调做法非常困惑，所以我仍旧有很多问题。
> 
> 1. 在proxy server调用process过程时，存在一个proxy_task，这个任务时如何产生的。上述的server task指的是不是就是这个proxy_task。从角色上看，proxy_task是proxy server为client提供服务的，所以会被称作server task?
> 2. proxy_task存在于一个series中，process过程创建了一个向web server请求的http_task，并将该任务追加在当前proxy_task所在的series。在process执行完毕时，proxy_task中的resp仍旧是初始化状态，完全没有能力完整写入tcp send buffer。
> 3. 由于series中出现了新的任务http_task（proxy server通过该任务向web server请求服务，所以被称为client task?)，在接收到web server的回复后，触发http_callback回调。在执行http_task到触发回调的过程中，proxy_task的状态是暂用线程等待还是被挂起了。
> 4. 在http_callback触发开始执行后，通过series的上下文更新了proxy_task中的resq，此时对于proxy_task而言，写入tcp send buffer的条件已经具备，写入的过程是如何触发的。
> 5. 我的理解是：proxy_task->process->http_task->http_callback->proxy_task->reply_callback->series_callback？但是这里面应该有多线程才对，对于这个series任务流而言，线程是如何切换的？

可以引用一下重新发个issue。
