### ISSUE TITLE
咨询curl向workflow server上传文件，workflow server如何读取文件内容

### ISSUE THREAD

**Issue by Treston-W** [sogou/workflow#1538]
我想通过curl命令向workflow server上传文件，如：
curl -F "file=@./curl.log" http://127.0.0.1:8000

其中curl.log的内容如下：
<img width="236" alt="image" src="https://github.com/sogou/workflow/assets/164054745/46ff454d-b3bc-46d8-8cf5-996b7d06a1ec">

我在workflow server端通过req->get_parsed_body()拿到的数据如下：
<img width="414" alt="image" src="https://github.com/sogou/workflow/assets/164054745/dfa6ae18-82b4-4a1a-947d-f926b82b25c1">
<img width="674" alt="image" src="https://github.com/sogou/workflow/assets/164054745/d5c081f7-f2cf-4c75-800e-ede81f32a91a">
如上图所示，body为原始文件数据+一些格式数据

如果我只想拿到那三行文件内容，我需要基于那一堆body去自定义解析拿到，还是咱们workflow有现成的提取工具？

**Comment by Barenboim** [comment]
这是multipart/form-data吧。wfrest里好像有支持这个的解析：https://github.com/wfrest/wfrest

**Comment by Barenboim** [comment]
https://github.com/wfrest/wfrest/blob/main/docs/cn/post_form.md
