### ISSUE TITLE
httpServerTask的回调函数中设置响应会回复默认响应

### ISSUE THREAD

**Issue by xiaguanggun** [sogou/workflow#1540]
当我在workflow的httpServerTask的回调函数中设置响应时，回复给浏览器的却是默认的响应而不是我自己设置的响应，在回调之前设置的响应就可以成功回复给浏览器，是为什么呢？

**Comment by Barenboim** [comment]
Http任务的回调函数，调用时机是在http交互结束，无论是client task还是server task。

server task的回调，可以用来查看回复成功了没有，以及可以向series里push新任务：比如打log或上报状态。

**Comment by Barenboim** [comment]
server task所在的序列是以processor为首任务，server task为末尾任务。这两个任务在被执行前，位置不受push_back，push_front等的影响。

processor任务的执行行为（dispatch）是调用process函数，server task的执行行为是reply，reply完成（所有数据写入tcp buf，或失败）之后，server task的callback被调用。这时候序列里已经没有其它任务了，可以继续push_back，否则序列也就结束了。

**Comment by Barenboim** [comment]
你是不是看了哪个代码的阅读笔记，说是序列结束之后回复。这个不准确。

**Comment by xiaguanggun** [comment]
谢谢解惑，懂了！
