### ISSUE TITLE
nossl分支tutorial make报错

### ISSUE THREAD

**Issue by jack416** [sogou/workflow#1544]
root@0b42136aea27:/home/docker_dir/code_work/workflow/tutorial# make -j9
mkdir -p build.cmake
rm -rf build.cmake/CMakeCache.txt
cd build.cmake && cmake -D CONSUL= -D KAFKA= -D MYSQL= -D REDIS= /home/docker_dir/code_work/workflow/tutorial
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /home/docker_dir/code_work/refuel_controller/thirdlib/FastDDS/lib/libcrypto.so (found version "3.0.2")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/docker_dir/code_work/workflow/tutorial/build.cmake
make -C build.cmake -f Makefile
make[1]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
make[1]: 进入目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make[2]: 进入目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make[3]: 进入目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make[3]: 离开目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make[3]: 进入目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
[  2%] Building CXX object CMakeFiles/helloworld.dir/tutorial-00-helloworld.cc.o
[  4%] Linking CXX executable ../helloworld
/usr/bin/ld: /home/docker_dir/code_work/workflow/_lib/libworkflow.so: undefined reference to `EVP_PKEY_CTX_set_rsa_padding'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/helloworld.dir/build.make:98：../helloworld] 错误 1
make[3]: 离开目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make[2]: *** [CMakeFiles/Makefile2:123：CMakeFiles/helloworld.dir/all] 错误 2
make[2]: 离开目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make[1]: *** [Makefile:91：all] 错误 2
make[1]: 离开目录“/home/docker_dir/code_work/workflow/tutorial/build.cmake”
make: *** [GNUmakefile:15：all] 错误 2
root@0b42136aea27:/home/docker_dir/code_work/workflow/tutorial#

**Comment by Barenboim** [comment]
你好。这个问题我们之前也有用户报过。如果你不用到MySQL，先把MySQL关了再试一下。
~~~sh
$ make MYSQL=n
$ cd tutorial
$ make MYSQL=n
~~~

**Comment by Barenboim** [comment]
你好，解决了么？

**Comment by jack416** [comment]
解决了，按您说的关掉 make MYSQL=n 就好了，建议最好再README.md说明一下

**Comment by jack416** [comment]
解决了，按您说的关掉 MYSQL 就好了：
make MYSQL=n 
建议最好再README.md说明一下

**Comment by jack416** [comment]
解决了，按您说的关掉 MYSQL 就好了：
make MYSQL=n
建议最好在 README.md 说明一下

**Comment by Barenboim** [comment]
> 解决了，按您说的关掉 MYSQL 就好了： make MYSQL=n 建议最好在 README.md 说明一下

不是。这个是部分SSL库的问题，可能和版本有关系，或者和用户机器上安装多个OpenSSL有关系。大多数情况下都没有这个问题。

**Comment by jack416** [comment]
> > 解决了，按您说的关掉 MYSQL 就好了： make MYSQL=n 建议最好在 README.md 说明一下
> 
> 不是。这个是部分SSL库的问题，可能和版本有关系，或者和用户机器上安装多个OpenSSL有关系。大多数情况下都没有这个问题。

好的。谢谢解答
