### ISSUE TITLE
关于GPL许可证兼容性的疑虑

### ISSUE THREAD

**Issue by xusiwei** [sogou/workflow#1545]
Workflow的部分源码来自于Linux内核：
* [list.h](https://github.com/torvalds/linux/blob/master/include/linux/list.h)
* [rbtree.h](https://github.com/torvalds/linux/blob/master/include/linux/rbtree.h)
* [rbtree.c](https://github.com/torvalds/linux/blob/master/lib/rbtree.c)

然而，Linux内核的开源许可证是GPLv2，它是相对“严格的”开源许可证，
Apache 2.0 开源许可证是相对“宽松的”许可证，

二者组合之后，通常只能按照更严格的GPLv2再次发布。
也就是说，如果Workflow的代码直接依赖这些代码，只能以GPLv2发布，不应该以Apache 2.0发布。

以上，是我的个人理解和疑惑。

另外是**个人建议**，如果Workflow希望最终Apache 2.0许可证发布，那么应该解除对这部分代码的依赖，具体做法有两种：
* 重写以上代码，并且要尽可能避免代码的相似度较高（PS：链表的操作代码很难做到不相似）；
* 使用C++标准库，这种方式相对更容易实现合规；

参考了一部分资料：
[《开源许可证兼容性指南》](https://gitee.com/trustworthy-open-source-community/License-Compatibility/raw/master/%E5%BC%80%E6%BA%90%E8%AE%B8%E5%8F%AF%E8%AF%81%E5%85%BC%E5%AE%B9%E6%80%A7%E6%8C%87%E5%8D%97.pdf)

**Comment by Barenboim** [comment]
我们首页上写的是双证书。

另外，这个影响不大。GPL只限制非开源形式的售卖，正常后端业务什么不受影响。如果用户真的要拿去卖钱，简单吧rbtree重新一下就规避里，照抄都行。

开源协议我们也是研究过的。不少商业的apache协议项目都有依赖GPL代码。只要不拿去卖钱都不属于违反协议。

Linux内核的rbtree到处都在用，这个代码的版权属于原作者，不是GNU也不是Linux组织。我们正是基于对代码的尊重，保留了所有版权信息。否则我们删了重写一下很简单。
