### ISSUE TITLE
workflow充当HTTP网关时数据量太大就收不全

### ISSUE THREAD

**Issue by 253027** [sogou/workflow#1548]
我使用workflow充当了一个HTTP的网关，然后将请求通过workflow的自定义协议转发给本地的另一个进程，在本地的同一台服务器上两个进程可以正常通信。然后我将HTTP网关进程放在本地虚拟机上，做业务的放在云服务器上，发现大概超过40000字节的时候做业务服务器发来的数据，HTTP本地就就收不全了，有没有一些可能解决的方向。
这一部分是根据教程的自定义协议做的
```
#include "../include/PrivatePtotocal.h"
#include <iostream>

PrivateProtocal::PrivateProtocal()
{
    this->head_received = 0;
    this->body = nullptr;
    this->body_size = 0;
}

PrivateProtocal::PrivateProtocal(PrivateProtocal &&val)
    : protocol::ProtocolMessage(std::move(val))
{
    ::memcpy(this->head, val.head, 4);
    this->head_received = val.head_received;
    this->body = val.body;
    this->body_received = val.body_received;
    this->body_size = val.body_size;

    val.head_received = 0;
    val.body = nullptr;
    val.body_size = 0;
}

PrivateProtocal &PrivateProtocal::operator=(PrivateProtocal &&val)
{
    if (this == &val)
        return *this;
    *(protocol::ProtocolMessage *)this = std::move(val);
    ::memcpy(this->head, val.head, 4);
    this->head_received = val.head_received;
    this->body = val.body;
    this->body_received = val.body_received;
    this->body_size = val.body_size;

    val.head_received = 0;
    val.body = nullptr;
    val.body_size = 0;
    return *this;
}

void PrivateProtocal::getMessageBody(void **body, size_t *size)
{
    *body = this->body;
    *size = this->body_size;
}

int PrivateProtocal::setMessageBody(const void *body, size_t size)
{
    void *p = ::malloc(sizeof(char) * size);
    if (!p)
        return -1;
    ::memcpy(p, body, size);
    if (this->body)
        ::free(this->body);
    this->body = (char *)p;
    this->body_size = size;
    this->head_received = 4;
    this->body_received = size;
    return 0;
}

PrivateProtocal::~PrivateProtocal()
{
    ::free(this->body);
}

int PrivateProtocal::encode(struct iovec vectors[], int max)
{
    uint32_t n = ::htonl(this->body_size);
    ::memcpy(this->head, &n, 4);
    vectors[0].iov_base = this->head;
    vectors[0].iov_len = 4;
    vectors[1].iov_base = this->body;
    vectors[1].iov_len = this->body_size;
    return 2;
}

int PrivateProtocal::append(const void *buf, size_t size)
{
    std::cout << size << "\n";
    // 获取头部信息直到获取完毕
    if (this->head_received < 4)
    {
        void *p = &this->head[head_received];
        size_t need = std::min(4 - this->head_received, size);
        size -= need, this->head_received += need;
        memcpy(p, buf, need);
        if (size <= 0)
            return 0;
        buf = (const char *)buf + need;
        p = this->head;
        this->body_size = ntohl(*(u_int32_t *)p);
        if (this->body_size > this->size_limit)
        {
            errno = EMSGSIZE;
            return -1;
        }
        this->body = (char *)malloc(sizeof(char) * this->body_size);
        if (!this->body)
            return -1;
        this->body_received = 0;
    }

    size_t need = this->body_size - this->body_received;

    if (size > need)
    {
        errno = EBADMSG;
        return -1;
    }

    memcpy(this->body + this->body_received, buf, size);
    this->body_received += size;
    if (size < need)
        return 0;
    return 1;
}

```
这里是我HTTP网关主要的代码
```
#include <workflow/WFTaskFactory.h>
#include <workflow/WFHttpServer.h>
#include <workflow/WFFacilities.h>
#include <workflow/HttpUtil.h>
#include <workflow/HttpMessage.h>
#include <workflow/WFConnection.h>
#include <workflow/Workflow.h>
#include <signal.h>
#include <iostream>
#include <string>
#include "./include/utility.h"
#include "./include/PrivatePtotocal.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <nlohmann/json.hpp>

static WFFacilities::WaitGroup wait_group(1);
using PrivateRequest = PrivateProtocal;
using PrivateResponse = PrivateProtocal;
using PrivateTask = WFNetworkTask<PrivateRequest, PrivateResponse>;

void singal_handel(int sig)
{
    if (sig != SIGINT)
        return;
    wait_group.done();
}

void PrivateProtocalCallback(PrivateTask *task)
{
    int state = task->get_state();
    int error = task->get_error();

    PrivateProtocal *resp = task->get_resp();
    void *body;
    size_t size;
    resp->getMessageBody(&body, &size);

    if (state == WFT_STATE_SUCCESS)
    {
        WFHttpTask *http_task = (WFHttpTask *)task->user_data;
        nlohmann::ordered_json js;
        js["id"] = std::to_string(*(int *)body);
        js["content"] = std::string((char *)body + 4, size - 4);
        std::string res = js.dump();
        http_task->get_resp()->append_output_body(res.data(), res.size());
    }
    else
    {
        const char *str = WFGlobal::get_error_string(state, error);
        fprintf(stderr, "Error: %s\n", str);
    }
}

void process(WFHttpTask *task)
{
    protocol::HttpRequest *resquest = task->get_req();
    size_t size;
    const void *body;
    resquest->get_parsed_body(&body, &size);
    std::string message((char *)body, size);

    nlohmann::json js = nlohmann::json::parse(message);
    std::string id, content;
    id = js["id"], content = js["content"];
    char buf[(4 + content.size())];

    *(int *)buf = std::stoi(id);
    ::memcpy(buf + 4, content.data(), content.size());

    using NTF = WFNetworkTaskFactory<PrivateRequest, PrivateResponse>;

    PrivateTask *tcp_task = NTF::create_client_task(TT_TCP, "tcp://xxxxxxxxx:xxxx", 1, PrivateProtocalCallback);
    tcp_task->get_req()->setMessageBody(buf, sizeof(buf));
    tcp_task->user_data = task;

    *series_of(task) << tcp_task;
}

int main()
{
    struct WFServerParams params = HTTP_SERVER_PARAMS_DEFAULT;
    /* for safety, limit request size to 8MB. */
    params.request_size_limit = 8 * 1024 * 1024;
    params.peer_response_timeout = 100;

    signal(SIGINT, singal_handel);
    WFHttpServer server(&params, &process);
    server.start(9190);
    wait_group.wait();
    return 0;
}
```

**Comment by Barenboim** [comment]
怎么看都好像被云主机限制了😂

你自定义协议通信部分没有什么问题，就是http server收不到400000字节上以上的请求是吗？

**Comment by 253027** [comment]
> 怎么看都好像被云主机限制了😂
> 
> 你自定义协议通信部分没有什么问题，就是http server收不到40000字节上以上的请求是吗？

是的40000以上就不行了，那我再去看看😭

**Comment by 253027** [comment]
> 另外你这个自定义协议，可以用我们protocol里的TLVMessage。

好的,主要刚开始接触workflow,我想都试试后面会尝试的😁

**Comment by Barenboim** [comment]
> > 怎么看都好像被云主机限制了😂
> > 你自定义协议通信部分没有什么问题，就是http server收不到40000字节上以上的请求是吗？
> 
> 是的40000以上就不行了，那我再去看看😭

嗯嗯，看看你的云主机有没有什么参数限制。我觉得某些安全机制可能会让云主机限制http请求的大小，避免用户的http server被攻击。

**Comment by Barenboim** [comment]
都是http协议，无论如何都是可以互通的啊。

你尝试用我们tutorial里的http_echo_server，让外部发一个40KB以上的请求，看看能不能立刻响应。

**Comment by Barenboim** [comment]
**params.peer_response_timeout = 100;**
这一行也可以先去掉试试。这个表示请求数据每两个包之间最多间隔100ms。

**Comment by 253027** [comment]
> **params.peer_response_timeout = 100;** 这一行也可以先去掉试试。这个表示请求数据每两个包之间最多间隔100ms。

这个是我做业务读TCP数据的代码
```
#include "../include/iodevice.h"
#include "../include/utility.h"

IoDevice::IoDevice(int socket) : _socket(socket) {}

int IoDevice::boundary_recv(std::string &buf)
{
    char buffer[1024];
    int ret = ::recv(_socket, buffer, 4, MSG_WAITALL);
    ERROR_CHECK(ret == -1, "boundary recv error which is -1");
    if (ret == 0)
        return 0;
    size_t len = *(size_t *)buffer, hash_recv = 0;
    while ((ret = ::recv(_socket, buffer, std::min(1024UL, len - hash_recv), MSG_WAITALL)) > 0)
    {
        if (ret == -1 && (errno & EAGAIN))
            continue;
        else if (ret == -1)
            return -1;
        buf.append(buffer, ret), hash_recv += ret;
    }
    return hash_recv;
}

int IoDevice::boundary_send(const std::string &buf)
{
    int len = buf.size(), has_send = 0;
    int ret = ::send(_socket, &len, sizeof(len), 0);
    ERROR_CHECK(ret == -1, "boundary send data size error");
    return send(buf);
}

int IoDevice::send(const std::string &buf)
{
    int ret;
    size_t len = buf.size(), has_send = 0;
    while ((ret = ::send(_socket, buf.data() + has_send, std::min(1024UL, len - has_send), MSG_DONTWAIT)) > 0)
    {
        if (ret == -1 && (errno & EWOULDBLOCK))
            continue;
        else if (ret == -1)
            return -1;
        has_send += ret;
    }
    return has_send;
}

int IoDevice::recv(std::string &buf)
{
    int ret = 0, bytes_read = 0;
    char buffer[1024];
    while ((ret = ::read(_socket, buffer, 1024)) > 0)
    {
        if (ret == -1)
            return (errno & EAGAIN) ? bytes_read : -1;
        buf.append(buffer, ret), bytes_read += ret;
    }
    return bytes_read;
}

```
我的疑问是在这个问题上面，create_client_task是不是有什么确认机制，确认连接存在呢？这边刚测试了100000字节的基本上发一多半链接就关闭了。我明天会试试workflow对称收发。
```
PrivateTask *tcp_task = NTF::create_client_task(TT_TCP, "tcp://xxxxxxxx:xxxxx", 1, PrivateProtocalCallback);
```

**Comment by Barenboim** [comment]
你的client和server之间rtt多少？如果100ms以上，那么40kb的请求必然会出现100ms以上的包延迟，这是tcp窗口导致的。

**Comment by Barenboim** [comment]
你编码的时候执行了htonl转成网络序了，但boundary_recv里没有转啊。那肯定是错误的。

**Comment by Barenboim** [comment]
并且，encode时用的是uint32_t，接收又使用size_t。

还有，(errno & EAGAIN)又是什么意思，不应该是(errno == EAGAIN)吗？

**Comment by 253027** [comment]
> 并且，encode时用的是uint32_t，接收又使用size_t。
> 
> 还有，(errno & EAGAIN)又是什么意思，不应该是(errno == EAGAIN)吗？

这一块确实写的有问题已经改正了，htonl转成网络序我是在发送数据之前转换过了，IODevice只负责发送数据。改正之后再次测试，本地确实可以收发，收一次数据的过程基本收一半多断开了。我将两个进程一起放在云服务器上，最后的HTTP报文是可以完整收到的，说明服务器带宽没有限制
```
6832
head: 726560
13068 5808 1452 2904 5808
1452 2904 2904 2904 2904 
2904 2904 2904 2904 2904 
2904 2904 2904 2904 2904 
2904 2904
Error: Connection timed out
```
打印信息实在这里加上的

```
int PrivateProtocal::append(const void *buf, size_t size)
{
    std::cout << size << "\n";
    // 获取头部信息直到获取完毕
    if (this->head_received < 4)
    {
        void *p = &this->head[head_received];
        size_t need = std::min(4 - this->head_received, size);
        size -= need, this->head_received += need;
        memcpy(p, buf, need);
        if (size <= 0)
            return 0;
        buf = (const char *)buf + need;
        p = this->head;
        this->body_size = ntohl(*(u_int32_t *)p);
        if (this->body_size > this->size_limit)
        {
            errno = EMSGSIZE;
            return -1;
        }
        this->body = (char *)malloc(sizeof(char) * this->body_size);
        if (!this->body)
            return -1;
        this->body_received = 0;
        std::cout << "head: " << this->body_size << "\n";
    }
    ...................
```

**Comment by 253027** [comment]
> 你编码的时候执行了htonl转成网络序了，但boundary_recv里没有转啊。那肯定是错误的。

这是我云服务器发给本地HTTP网关的数据，我在IODevice发送消息data前会再发送一个4字节的头部指定此次发送数据大小，不知道这样对不对
```
void task(void *eventloop, int socket, int type, const std::string &query)
{
    // std::cout << pthread_self() << std::endl;
    //  std::this_thread::sleep_for(std::chrono::seconds(1));
    std::string res;
    if (type == 1)
        res = Dictionary::GetInstance()->query(query), type = 100;
    else if (type == 2)
        res = webquery.query(query), type = 200;
    std::cout << "取得" << res.size() << "\n";
    std::string data(8 + res.size(), '\0');
    *(int *)data.data() = ::htonl(4 + res.size());    //根据PrivateProtocal指定协议的头部大小
    *((int *)data.data() + 1) = type;     //这一块自己用的数据
    ::memcpy(data.data() + 8, res.data(), res.size());   //这一块自己用的数据

    EventLoop *loop = (EventLoop *)eventloop;
    loop->appendSendPoll(std::make_pair(socket, data));
}
```

**Comment by Barenboim** [comment]
你真正上线还是直接用我们的TLVMessage吧，完全就是你需要的结构。你代码这写法，我也搞不清楚还会有什么问题。

**Comment by 253027** [comment]
> 你真正上线还是直接用我们的TLVMessage吧，完全就是你需要的结构。你代码这写法，我也搞不清楚还会有什么问题。

好

**Comment by Barenboim** [comment]
http server从外网接收大数据问题已经解决了是吧？

**Comment by 253027** [comment]
> http server从外网接收大数据问题已经解决了是吧？

😭没，我想换条路。

**Comment by Barenboim** [comment]
Response timeout那个去掉了没？





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 晚上7:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)




  
http server从外网接收大数据问题已经解决了是吧？
  
😭没，我想换条路。

**Comment by 253027** [comment]
> Response timeout那个去掉了没？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你说过后我就去掉了

**Comment by Barenboim** [comment]
用我们tutorial里的http echo server试过了吗？







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月7日(周二) 晚上7:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)




  
Response timeout那个去掉了没？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你说过后我就去掉了

**Comment by 253027** [comment]
> 用我们tutorial里的http echo server试过了吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

试过了云服务器发200K左右本地不能立刻收到有延迟

**Comment by Barenboim** [comment]
这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 凌晨0:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)




  
用我们tutorial里的http echo server试过了吗？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
试过了云服务器发200K左右本地不能立刻收到有延迟

**Comment by 253027** [comment]
> 这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？
> 
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年5月8日(周三) 凌晨0:36
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
> 
> 
> 
> 
>   
> 用我们tutorial里的http echo server试过了吗？
>  …
>  ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
>   
> 试过了云服务器发200K左右本地不能立刻收到有延迟
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

怎么看rtt时间呢太底层了，不熟悉

**Comment by Barenboim** [comment]
Ping一下啊。。。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 凌晨0:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)




  
这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2024年5月8日(周三) 凌晨0:36
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
 
用我们tutorial里的http echo server试过了吗？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
 
试过了云服务器发200K左右本地不能立刻收到有延迟
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
怎么看rtt时间呢太底层了，不熟悉

**Comment by 253027** [comment]
> Ping一下啊。。。
> 
> 
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年5月8日(周三) 凌晨0:43
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
> 
> 
> 
> 
>   
> 这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？
>  
> ---原始邮件---
>  发件人: @.&gt;
>  发送时间: 2024年5月8日(周三) 凌晨0:36
>  收件人: @.&gt;;
>  抄送: @.@.&gt;;
>  主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
>  
> 用我们tutorial里的http echo server试过了吗？
>  …
>  ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
>  
> 试过了云服务器发200K左右本地不能立刻收到有延迟
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you commented.Message ID: @.***&gt;
>   
> 怎么看rtt时间呢太底层了，不熟悉
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

有没有别的工具，问题就是ping不通啊

**Comment by 253027** [comment]
> Ping一下啊。。。
> 
> 
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年5月8日(周三) 凌晨0:43
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
> 
> 
> 
> 
>   
> 这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？
>  
> ---原始邮件---
>  发件人: @.&gt;
>  发送时间: 2024年5月8日(周三) 凌晨0:36
>  收件人: @.&gt;;
>  抄送: @.@.&gt;;
>  主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
>  
> 用我们tutorial里的http echo server试过了吗？
>  …
>  ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
>  
> 试过了云服务器发200K左右本地不能立刻收到有延迟
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you commented.Message ID: @.***&gt;
>   
> 怎么看rtt时间呢太底层了，不熟悉
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

我自己再试试吧，您早点休息😁

**Comment by Barenboim** [comment]
你connect一下看看多长时间连上也行啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 凌晨0:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)




  
Ping一下啊。。。
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2024年5月8日(周三) 凌晨0:43
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
 
这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？
 
---原始邮件---
 发件人: @.&gt;
 发送时间: 2024年5月8日(周三) 凌晨0:36
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548)
 
用我们tutorial里的http echo server试过了吗？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
 
试过了云服务器发200K左右本地不能立刻收到有延迟
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
 
怎么看rtt时间呢太底层了，不熟悉
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you commented.Message ID: @.***&gt;
  
我自己再试试吧，您早点休息😁

**Comment by 253027** [comment]
> 你connect一下看看多长时间连上也行啊
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月8日(周三) 凌晨0:52 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Ping一下啊。。。
> ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月8日(周三) 凌晨0:43 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) 这。。。是不是rtt大啊。超过16k的话，因为tcp窗口的原因，会达到数个rtt。延迟是多久？
> ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月8日(周三) 凌晨0:36 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) 用我们tutorial里的http echo server试过了吗？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:59 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) Response timeout那个去掉了没？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年5月7日(周二) 晚上7:31 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [sogou/workflow] workflow充当HTTP网关时数据量太大就收不全 (Issue #1548) http server从外网接收大数据问题已经解决了是吧？ 😭没，我想换条路。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 你说过后我就去掉了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 试过了云服务器发200K左右本地不能立刻收到有延迟 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 怎么看rtt时间呢太底层了，不熟悉 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 我自己再试试吧，您早点休息😁 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Elapsed time: 0.023836986 seconds
connect函数返回时间，说明没问题啊。
