### ISSUE TITLE
handler_threads配置的问题

### ISSUE THREAD

**Issue by coderwxl** [sogou/workflow#1553]
wf server中handler_threads我配置的16，然后客户端并发50向wf server发请求，然后我发现wf server创建了50个process线程，不应该是16个吗？

**Comment by Barenboim** [comment]
你是不是用wait_group了？

**Comment by coderwxl** [comment]
是的
![image](https://github.com/sogou/workflow/assets/57793691/a4f447f7-c7c9-4884-b5f4-42907ee22db4)

**Comment by Barenboim** [comment]
你用wait group相当于堵住了我们一个线程。我们会根据你最多同时堵住我们多少个网络线程来动态增加线程，避免没有活跃的线程可以用。

所以，除了main或者你自己创建的线程里，最好不要调用wait group的wait。对于计算线程，我们是不会动态增加的。所计计算线程绝对不应该wait。

**Comment by Barenboim** [comment]
@coderwxl 
最新代码已经支持动态减少线程了，你可以再试一下你的场景。

**Comment by coderwxl** [comment]
动态减少线程能达到的效果是什么？

**Comment by Barenboim** [comment]
效果是你同步等待的线程减少之后，增加的线程也会逐步退出。


可以试一下你的场景是什么效果。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 上午10:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] handler_threads配置的问题 (Issue #1553)




 
动态减少线程能达到的效果是什么？
