### ISSUE TITLE
thrdpool 如何实现动态减少线程数

### ISSUE THREAD

**Issue by huangsefenggmail** [sogou/workflow#1559]
### 问题
现在我有个场景外部分配的cpu资源可能有变化，想要能够在动态调整线程池的大小。
查看了下thrdpool.c的源码，当前thrdpool有实现increase接口，但是没有decrease接口。
想要在thrdpool_destroy函数中控制销毁线程的次数，但是发现不是很好控制。

希望可以调了decrease接口之后，某个线程执行完当前的任务之后不要再从msgqueue中取任务并销毁。

**请教一下，大佬会怎么实现线程池的动态缩容。** 是否只能新建线程池。

**Comment by Barenboim** [comment]
这个问题不错，我之前也有在考虑。想一想。

**Comment by Barenboim** [comment]
看看这个：https://github.com/Barenboim/msgqueue_thrdpool/pull/2

**Comment by huangsefenggmail** [comment]
> 看看这个：[Barenboim/msgqueue_thrdpool#2](https://github.com/Barenboim/msgqueue_thrdpool/pull/2)

👍🏼👍🏼👍🏼，抛一个结束任务到消息队列，哪个线程先抢到哪个线程退出。非常优雅的实现。

有个小点：在decrease加个判断当前线程数为0的话，就不抛结束任务进去？不然下一个增加的线程会直接结束。

**Comment by Barenboim** [comment]
代码还有些小问题没改完，比如没有人join这些线程的结果，还有同时调用destroy的线程可能没有被唤醒。

不过，decrease到负线程数时正常的，而且也是必须的。这种情况下，increase的线程会立刻退出。

**Comment by Barenboim** [comment]
@huangsefenggmail 又增加了WFGlobal::increase_compute_thread()和WFGlobal::decrease_compute_thread()函数，可以随时动态加减计算线程了。
