### ISSUE TITLE
c++使用wfkafka 调用create_kafka_task崩溃

### ISSUE THREAD

**Issue by zxyAcmen** [sogou/workflow#1560]
`bool CKafkaProduce::produceMsg(const std::string &msg) {
    if (msg.empty()) {
        return false;
    }
    LOG_INFO("msg= %s", msg.c_str());
    WFKafkaClient client;
    WFKafkaTask * task = client.create_kafka_task("api=produce", -1, produceRspCb2);
    if (task == NULL) {
        LOG_INFO("333333333333333333333 msg= %s", msg.c_str());
        return false;
    }
    return true;
}

`

上面的接口会给别的类调用传要写入的消息，produceRspCb2是这个空函数体
void produceRspCb2(WFKafkaTask *task) {
}
下面是崩溃信息
![image](https://github.com/sogou/workflow/assets/20756430/09bac586-bb2e-449b-aab1-6797e11797bc)

文字崩溃提示信息
Core was generated by `/opt/comm_app/hax/bin/tiis -r/opt/comm_app/hax/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043394d in std::__atomic_base<int>::operator++ (this=0x130) at /usr/include/c++/11/bits/atomic_base.h:385
385           { return __atomic_add_fetch(&_M_i, 1, int(memory_order_seq_cst)); }
[Current thread is 1 (Thread 0x7fc2b07f8640 (LWP 421578))]

**Comment by Barenboim** [comment]
你好，我们的client需要调用init()初始化。示例里有，文档里也有

client也不应该是只用一次，应该只打开一次，然后一直用它create任务就可以了。

**Comment by Barenboim** [comment]
你原来的代码，连broker地址都没有传过给我，我怎么都不可能访问到啊？
client的init操作在：
https://github.com/sogou/workflow/blob/c2eb095c09b266507b70290a9710e21d12b5137a/src/client/WFKafkaClient.h#L144
可以填入多个broker地址。
还一点很重新，你的client应该是全局的，不是一个task创建一次client

**Comment by Barenboim** [comment]
client.init("kafka://10.101.251.195:9092");
没有前面的“brokeraddr="。另外，9092是默认端口也可以缺省。
你看一下我们的文档和例子吧。

**Comment by zxyAcmen** [comment]
brokeraddr= 是我配置项，只会使用后面的内容的，我没有说清楚，有看文档，并没有提供一个完整的使用示例，或者我说没找到完整的示例吗？

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/master/tutorial/tutorial-13-kafka_cli.cc
示例在这里，可以跑一下先看看。在tuturial目录里，也要make KAFAK=y
我看起来你后面部分的URL好像没有什么问题啊，你也用tutorial试试吧。

**Comment by zxyAcmen** [comment]
![image](https://github.com/sogou/workflow/assets/20756430/6381eb54-7ced-451c-8e8e-d4112b50b6b7)
这个是我初始化的时候日志打印，看格式应该是没问题的

**Comment by Barenboim** [comment]
我们的tutorial可以跑吗？你是不是client被销毁了？代码可以再贴一下吗。

**Comment by Barenboim** [comment]
你好，用我们tutorial-13的代码，可以成功的生产吗？

**Comment by zxyAcmen** [comment]
tutorial还需要花时间编译，我看了下失败的地方我确实调用了m_KafkaCliPtr_->deinit(); 接口，
但是我始终无法成功解析那个url, 
![image](https://github.com/sogou/workflow/assets/20756430/ebe34969-b35f-4d8d-a91c-416f0adcff2f)
![image](https://github.com/sogou/workflow/assets/20756430/fd3bf168-8c7d-438b-b930-c9afff8e96a1)
![image](https://github.com/sogou/workflow/assets/20756430/1c0238b0-1bdb-4fd9-907e-03dc6b025769)

**Comment by Barenboim** [comment]
麻烦也发一下你用的代码的版本等信息吧。

目前只要你不加上那句deinit，我没有看出什么问题。

另外，你关注一下main函数是不是结束了？

**Comment by Barenboim** [comment]
我知道了，可能是新版本改错了……

我们马上修复一下，也可以退回上一个release

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1561
你好，麻烦再帮我们试一下，我更新了代码。
这是前几个commit的一个问题，不好意思。

**Comment by zxyAcmen** [comment]
我用的是库v0.11.4版本，我还修改了cmakelists，你直接告诉修改哪行代码吧，不然我要重新下载，重新写make，太麻烦了

**Comment by Barenboim** [comment]
我目前主分支上已经改了。就在上面那个PR里。

**Comment by Barenboim** [comment]
我把0.11.4的release重新打吧。确实是个比较严重的问题，会导致自定义协议出错。

**Comment by Barenboim** [comment]
@zxyAcmen 你好，麻烦帮我们看看问题修复了吗

**Comment by zxyAcmen** [comment]
已经可以写进kafka了，但有几处用法，我有点不是很明白，也麻烦能否讲解一下。
`	config.set_compress_type(Kafka_NoCompress);
	config.set_client_id("workflow");   这个做什么的
	task->set_config(std::move(config));

    record.set_key("key1", strlen("key1"));    这个做什么的
	record.set_value(msg.data(), msg.length());
	record.add_header_pair("hk1", 3, "hv1", 3);    这个做什么的
	task->add_produce_record(m_Topic_, -1, std::move(record));


还有这下面的一大段具体有什么用来着，我是看例子这么写的，但是不明白什么个意思，这个是在例子中回调函数里的写法

    WFKafkaTask *next_task = NULL;
    std::vector<std::vector<KafkaRecord *>> records;
    std::vector<KafkaToppar *> toppars;
    int api_type = task->get_api_type();

    protocol::KafkaResult new_result;

    switch (api_type)
    {
    case Kafka_Produce:
        task->get_result()->fetch_records(records);

        for (const auto &v : records)
        {
            for (const auto &w: v)
            {
                const void *value;
                size_t value_len;
                w->get_value(&value, &value_len);
                printf("produce\ttopic: %s, partition: %d, status: %d, \
                        offset: %lld, val_len: %zu\n",
                        w->get_topic(), w->get_partition(), w->get_status(),
                        w->get_offset(), value_len);
            }
        }

        break;

    case Kafka_Fetch:
        new_result = std::move(*task->get_result());
        new_result.fetch_records(records);

        if (!records.empty())
        {
            if (!m_NoCgroup_) {
                // next_task = m_KafkaCliPtr_->create_kafka_task("api=commit", 3, produceRspCb);
                next_task = m_KafkaCliPtr_->create_kafka_task("api=commit", 3, [this](WFKafkaTask *task){produceRspCb(task);});
            }

            std::string out;

            for (const auto &v : records)
            {
                if (v.empty())
                    continue;

                char fn[1024];
                snprintf(fn, 1024, "/tmp/kafka.%s.%d.%llu",
                            v.back()->get_topic(), v.back()->get_partition(),
                            v.back()->get_offset());

                FILE *fp = fopen(fn, "w+");
                long long offset = 0;
                int partition = 0;
                std::string topic;

                for (const auto &w : v)
                {
                    const void *value;
                    size_t value_len;
                    w->get_value(&value, &value_len);
                    if (fp)
                        fwrite(value, value_len, 1, fp);

                    offset = w->get_offset();
                    partition = w->get_partition();
                    topic = w->get_topic();

                    if (!m_NoCgroup_) {
                        next_task->add_commit_record(*w);
                    }
                }

                if (!topic.empty())
                {
                    out += "topic: "	  + topic;
                    out += ",partition: " + std::to_string(partition);
                    out += ",offset: "	  + std::to_string(offset) + ";";
                }

                if (fp) {
                    fclose(fp);
                }
            }

            // printf("fetch\t%s\n", out.c_str());

            if (!m_NoCgroup_) {
                series_of(task)->push_back(next_task);
            }
        }

        break;

    case Kafka_OffsetCommit:
        task->get_result()->fetch_toppars(toppars);

        if (!toppars.empty())
        {
            for (const auto& v : toppars)
            {
                printf("commit\ttopic: %s, partition: %d, \
                        offset: %llu, error: %d\n",
                        v->get_topic(), v->get_partition(),
                        v->get_offset(), v->get_error());
            }
        }

        // next_task = client.create_leavegroup_task(3, kafka_callback);
        next_task = m_KafkaCliPtr_->create_leavegroup_task(3, [this](WFKafkaTask *task){produceRspCb(task);});
         

        series_of(task)->push_back(next_task);

        break;

    case Kafka_LeaveGroup:
        printf("leavegroup callback\n");
        break;

    default:
        break;
    }

    if (!next_task) {
        m_KafkaCliPtr_->deinit();
    }
`

**Comment by zxyAcmen** [comment]
还有个问题，我生产者和消费者能使用一个kafka客户端吗？

**Comment by Barenboim** [comment]
> 还有个问题，我生产者和消费者能使用一个kafka客户端吗？

尽量不要这么用吧。感觉不太合理的样子。当然你也可以试试看。

**Comment by zxyAcmen** [comment]
好的，你能把上面我在代码中提到的疑问给解答下吗

**Comment by zxyAcmen** [comment]
![image](https://github.com/sogou/workflow/assets/20756430/fe5bcaf7-4f08-41a7-8949-248ef8461af9)
这个消费者任务是创建好一个就行，一直start()还是说需要自己开线程不停的创建任务再start()呢？

**Comment by kedixa** [comment]
## set_client_id
该参数设置的是`kafka request header`中的`client_id`

```
config.set_client_id("workflow");
```

附`kafka request header v1`的文法
```
Request Header v1 => request_api_key request_api_version correlation_id client_id 
  request_api_key => INT16
  request_api_version => INT16
  correlation_id => INT32
  client_id => NULLABLE_STRING
```

## set_key/set_value/add_header_pair
这些是`kafka record`中的内容，可参考[Record](https://kafka.apache.org/documentation/#record)进一步理解，其中`set_key`是设置`key`的内容，`set_value`是设置`value`的内容，`add_header_pair`是向`Headers`数组增加内容。附

```
length: varint
attributes: int8
    bit 0~7: unused
timestampDelta: varlong
offsetDelta: varint
keyLength: varint
key: byte[]
valueLen: varint
value: byte[]
Headers => [Header]
```

## 下面一大段
太长了，可以指出某些重点内容吗

**Comment by Barenboim** [comment]
> ![image](https://private-user-images.githubusercontent.com/20756430/332775034-fe5bcaf7-4f08-41a7-8949-248ef8461af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzczMzksIm5iZiI6MTcxNjM3NzAzOSwicGF0aCI6Ii8yMDc1NjQzMC8zMzI3NzUwMzQtZmU1YmNhZjctNGYwOC00MWE3LTg5NDktMjQ4ZWY4NDYxYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWIzOGNlYTYyNWFhNmNkYzJjNDhkMGY0ZDZlMTUwYTk3YjUzYWIyZjAxY2Q0N2M0ZjMxNmMxNDJmZTgwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4vp0AHp9qSWcfphXjiqXgO9X9EZ9N2sy5kP_lPV_7w) 这个消费者任务是创建好一个就行，一直start()还是说需要自己开线程不停的创建任务再start()呢？

我们的任务都是一次性的，callback之后就销毁了。所以，每个请求都需要创建任务。

**Comment by zxyAcmen** [comment]
> ## set_client_id
> 该参数设置的是`kafka request header`中的`client_id`
> 
> ```
> config.set_client_id("workflow");
> ```
> 
> 附`kafka request header v1`的文法
> 
> ```
> Request Header v1 => request_api_key request_api_version correlation_id client_id 
>   request_api_key => INT16
>   request_api_version => INT16
>   correlation_id => INT32
>   client_id => NULLABLE_STRING
> ```
> 
> ## set_key/set_value/add_header_pair
> 这些是`kafka record`中的内容，可参考[Record](https://kafka.apache.org/documentation/#record)进一步理解，其中`set_key`是设置`key`的内容，`set_value`是设置`value`的内容，`add_header_pair`是向`Headers`数组增加内容。附
> 
> ```
> length: varint
> attributes: int8
>     bit 0~7: unused
> timestampDelta: varlong
> offsetDelta: varint
> keyLength: varint
> key: byte[]
> valueLen: varint
> value: byte[]
> Headers => [Header]
> ```
> 
> ## 下面一大段
> 太长了，可以指出某些重点内容吗


那我来说下我自己的理解吧
![image](https://github.com/sogou/workflow/assets/20756430/dc64d592-e83c-4930-9a10-9840c24409b9)

1： 比如这张图，是在创建任务的时候使用api=produce为第一个参数时，回调的时候api_type=Kafka_Produce， 看代码像是循环获取结果记录，这个我有点不明白获取的是什么

![image](https://github.com/sogou/workflow/assets/20756430/352cac3f-1690-456c-8d67-5162494b0671)
这个fetch类型也是在创建任务的时候对应的吧，然后这里我理解的也是通过 回调来获取从kafka读取的数据，但是创建这个commit这个任务我就明白具体有啥用，是不是业务不需要关系这个就不需要使用了，commit之后又返回了个api_type=commit类型，
![image](https://github.com/sogou/workflow/assets/20756430/7bafd1c6-13ea-409b-9117-9e97936d995f)
这些动作具体是怎么个事，有个具体说明文档吗

**Comment by zxyAcmen** [comment]
> > ![image](https://private-user-images.githubusercontent.com/20756430/332775034-fe5bcaf7-4f08-41a7-8949-248ef8461af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzczMzksIm5iZiI6MTcxNjM3NzAzOSwicGF0aCI6Ii8yMDc1NjQzMC8zMzI3NzUwMzQtZmU1YmNhZjctNGYwOC00MWE3LTg5NDktMjQ4ZWY4NDYxYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWIzOGNlYTYyNWFhNmNkYzJjNDhkMGY0ZDZlMTUwYTk3YjUzYWIyZjAxY2Q0N2M0ZjMxNmMxNDJmZTgwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4vp0AHp9qSWcfphXjiqXgO9X9EZ9N2sy5kP_lPV_7w) 这个消费者任务是创建好一个就行，一直start()还是说需要自己开线程不停的创建任务再start()呢？
> 
> 我们的任务都是一次性的，callback之后就销毁了。所以，每个请求都需要创建任务。


如果按你这么说，我需要自己创建线程，定时创建消费任务从kafka读取数据，我可以这么理解吗？

**Comment by Barenboim** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/20756430/332775034-fe5bcaf7-4f08-41a7-8949-248ef8461af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzczMzksIm5iZiI6MTcxNjM3NzAzOSwicGF0aCI6Ii8yMDc1NjQzMC8zMzI3NzUwMzQtZmU1YmNhZjctNGYwOC00MWE3LTg5NDktMjQ4ZWY4NDYxYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWIzOGNlYTYyNWFhNmNkYzJjNDhkMGY0ZDZlMTUwYTk3YjUzYWIyZjAxY2Q0N2M0ZjMxNmMxNDJmZTgwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4vp0AHp9qSWcfphXjiqXgO9X9EZ9N2sy5kP_lPV_7w) 这个消费者任务是创建好一个就行，一直start()还是说需要自己开线程不停的创建任务再start()呢？
> > 
> > 
> > 我们的任务都是一次性的，callback之后就销毁了。所以，每个请求都需要创建任务。
> 
> 如果按你这么说，我需要自己创建线程，定时创建消费任务从kafka读取数据，我可以这么理解吗？

不用自己创建线程。你现在不是已经用起来了吗？你就不停的向series里push_back就可以了。

我还是建议看一下我们的文档吧。我们的用法都是相通的。

**Comment by Barenboim** [comment]
@zxyAcmen 这里还有一个例子可以参考：https://github.com/sogou/workflow/issues/1160

**Comment by kedixa** [comment]
## produce
`produce`接口用于向kafka发送数据，此时客户端扮演一个生产者，将数据发往kafka服务器前，用户/客户端需要填写要发送的数据(record)内容及相关信息，比如key, value, header, topic, partition等，但此时客户端不知道该record被生产后的offset。你截图中关于`Kafka_Produce`后的代码，用于遍历当前任务生产了哪些record，此时除了之前填写的内容外，还可获取到这些数据被生产后的offset信息。如果不需要知道这些内容，只需判断produce任务成功与否，可以不遍历。

## fetch
`fetch`接口用于从kafka获取数据，为了保证同一个用户组对每个主题下的消息恰好消费一次，kafka提供了`fetch`后`commit`的操作，从服务端维护当前消费到的位置。假如某次`fetch`取到了`partition 0, offset 10`的消息，在`fetch`成功后主动将该位置提交`commit`到服务器，即使该进程退出了，下次也可以继续从该位置的下一条数据`partition 0, offset 11`继续消费。

如果只需要取一些数据，不需要保证数据消费的唯一性，只是随便玩玩，也可以不提交位置信息。

kafka虽然复杂，但对用户来说常见的操作也就`produce`、`fetch`、`commit`，如果只是简单使用，这些已经够了。如果需要了解其原理，可以参考kafka官方文档，或者搜索一些优秀的博客来学习，不必心急。我就很菜，接触kafka好几年了也记不得每个细节，但踏踏实实搞还是能搞通的，等我有时间了也自己写个kafka客户端玩玩。

**Comment by zxyAcmen** [comment]
![image](https://github.com/sogou/workflow/assets/20756430/6a2a0ec3-26ed-4806-9a16-7e59cd053b15)
示例中这行代码是什么意思，wait_group.done()是在什么时候触发的

**Comment by zxyAcmen** [comment]
> ## produce
> `produce`接口用于向kafka发送数据，此时客户端扮演一个生产者，将数据发往kafka服务器前，用户/客户端需要填写要发送的数据(record)内容及相关信息，比如key, value, header, topic, partition等，但此时客户端不知道该record被生产后的offset。你截图中关于`Kafka_Produce`后的代码，用于遍历当前任务生产了哪些record，此时除了之前填写的内容外，还可获取到这些数据被生产后的offset信息。如果不需要知道这些内容，只需判断produce任务成功与否，可以不遍历。
> 
> ## fetch
> `fetch`接口用于从kafka获取数据，为了保证同一个用户组对每个主题下的消息恰好消费一次，kafka提供了`fetch`后`commit`的操作，从服务端维护当前消费到的位置。假如某次`fetch`取到了`partition 0, offset 10`的消息，在`fetch`成功后主动将该位置提交`commit`到服务器，即使该进程退出了，下次也可以继续从该位置的下一条数据`partition 0, offset 11`继续消费。
> 
> 如果只需要取一些数据，不需要保证数据消费的唯一性，只是随便玩玩，也可以不提交位置信息。
> 
> kafka虽然复杂，但对用户来说常见的操作也就`produce`、`fetch`、`commit`，如果只是简单使用，这些已经够了。如果需要了解其原理，可以参考kafka官方文档，或者搜索一些优秀的博客来学习，不必心急。我就很菜，接触kafka好几年了也记不得每个细节，但踏踏实实搞还是能搞通的，等我有时间了也自己写个kafka客户端玩玩。

我感觉你在说我菜，哈哈，开玩笑的，我自己确实菜。有个问题
![image](https://github.com/sogou/workflow/assets/20756430/5c930c1e-bb68-4eb3-bd89-3803e568181e)

我好像使用捕捉信息kill -2 退出的时候发生了崩溃，只有在stop里调用了deinit(), 之前使用kafka生产者有次是没有init出现这样的崩溃，现在是添加了消费者，程序能正常跑，但是整个退出时，崩溃了。

**Comment by zxyAcmen** [comment]
![image](https://github.com/sogou/workflow/assets/20756430/ae92e2d4-604b-40cd-865d-c20ef8175e4c)
我在主动退出时，stop里直接调用deinit函数，程序崩溃了，但是那个任务是在另一个函数里使用的，这里我应该怎么调用create_leavegroup_task这个函数呢，新建一个任务吗

**Comment by Barenboim** [comment]
你好，你必须保证运行中的任务都回到callback，才能deinit并退出程序。

你这个stop是在哪里调用的？如果你直接在信号处理函数里这么调，那程序肯定崩溃的，因为你的client指针还在被其他线程使用。你需要设计好你的程序退出逻辑。

另外，你的client其实也没有必要new的，直接写成CKafkaComsumer的成员变量就行了。

**Comment by zxyAcmen** [comment]
> Contributor

也就是说这个create_leavegroup_task函数的调用不是必须的，但是必须保证所有的cb都停止了，刚刚确实发现了一个情况，我并没有在消费到数据了，但是commit的回调函数一直在执行，使用的是1160的示例，这是什么原因导致的

**Comment by Barenboim** [comment]
你可以在收入到退出信号之后，不再产生新的消费任务，再执行一个leavegropu任务。leavegroup结束之后，唤醒主进程，退出程序。唤醒主进程可以用wait group来做。还是先参考一下我们的tutorial里的程序吧。

**Comment by zxyAcmen** [comment]
> 你可以在收入到退出信号之后，不再产生新的消费任务，再执行一个leavegropu任务。leavegroup结束之后，唤醒主进程，退出程序。唤醒主进程可以用wait group来做。还是先参考一下我们的tutorial里的程序吧。

感谢，这个问题已经解决了，还有个问题就是 我看程序打印日志有提示commit成功，但是每次重新启动都会把所有的数据都给读出来了，比如说我kafka起始offset是20， 最后一条是40， 第一条启动读取20-40这20条数据，然后向kafka添加了一条数据，消费者读到了 offset  41 的这条数据，然后我重启程序，程序就从20 - 41又全读出来了，这个会是什么原因呢

**Comment by kedixa** [comment]
是否通过`config.set_offset_timestamp`设置了`offset_timestamp`。`offset_timestamp`有以下几个特殊值

- `KAFKA_TIMESTAMP_EARLIEST`表示从现存的最早的一条消息开始消费
- `KAFKA_TIMESTAMP_LATEST`表示从最后一条消息的下一条消息开始消费，也就是开始消费后如果没有新数据产生就消费不到数据
- `KAFKA_TIMESTAMP_UNINIT`表示根据服务器记录的offset开始消费

如果未设置过该值或现象不符，可贴一下关键代码看看。最好别贴图。

**Comment by kedixa** [comment]
贴代码的方式如下
````
```cpp
int func() {
    return 1;
}
```
````

其效果为
```cpp
int func() {
    return 1;
}
```
