### ISSUE TITLE
如何优雅的取消DAG中的后续图节点

### ISSUE THREAD

**Issue by shenchenlin** [sogou/workflow#1562]
您好，我使用WFGraphTask模拟生成了DAG图，现在遇到一个问题，当某个图节点异常时，无法取消后续节点。
在当前节点调用`series_of()`，只能操作当前节点，因为图节点之间并不共享series。
请问有什么优雅的方式能取消后续节点的执行吗？

**Comment by Barenboim** [comment]
你好，这个问题我们也有其他用户提出过。目前来讲，还没有一个特别优雅的方案。你可以先看一下 WFDynamicTask，把可能需要取消的节点用dynamic task来构造，当节点要取消，把任务展开成WFEmptyTask就可以。注意不能展开成nullptr。
WFDynamicTask的接口：
~~~cpp
using WFDynamicTask = WFGenericTask;
using dynamic_create_t = std::function<SubTask *(WFDynamicTask *)>;

class WFTaskFactory
{
    static WFDynamicTask *create_dynamic_task(dynamic_create_t create);
};
~~~

**Comment by Barenboim** [comment]
如果有什么好的设计方案也可以讨论一下。

**Comment by Barenboim** [comment]
@shenchenlin 可以看一下这个修改：https://github.com/sogou/workflow/pull/1583
直接cancel图节点任务的series就可以了，行为上会cancel所有后续节点。因为图节点任务的series对用户来讲没有什么特别用处，所以我们把cancel行为扩展为递归取消后续节点。

**Comment by shenchenlin** [comment]
感谢大佬🙏
