### ISSUE TITLE
myssql cli 使用是否可以创建多个任务

### ISSUE THREAD

**Issue by zxyAcmen** [sogou/workflow#1563]
针对读和写操作，是否可以使用两个任务来区分一个写mysql，一个读mysql，还是说只需要一个任务，在task callback函数里自行区分返回的是写结果还是查询结果？

**Comment by Barenboim** [comment]
没有看懂你的问题。

首先，我们没有mysql cli这种东西，不涉及事务，直接创建任务就可以了。

其次，mysql都是传SQL语句，本身不区分什么读写。

**Comment by zxyAcmen** [comment]
> 没有看懂你的问题。
> 
> 首先，我们没有mysql cli这种东西，不涉及事务时，直接创建任务就可以了。
> 
> 其次，mysql都是传SQL语句，本身不区分什么读写。

那我是要通过应答回调来判断我插入成功还是查询成功吗，我操作mysql任何语句我都是需要关注是否成功。
如果不成功我又怎么获取是哪条语句失败了，暂时不使用事务。

**Comment by Barenboim** [comment]
> > 没有看懂你的问题。
> > 首先，我们没有mysql cli这种东西，不涉及事务时，直接创建任务就可以了。
> > 其次，mysql都是传SQL语句，本身不区分什么读写。
> 
> 那我是要通过应答回调来判断我插入成功还是查询成功吗，我操作mysql任何语句我都是需要关注是否成功。 如果不成功我又怎么获取是哪条语句失败了，暂时不使用事务。

看一下文档吧。callback里有可以从MySQLResult里看，都有状态。还可以拿到你的query语句。

**Comment by zxyAcmen** [comment]
> > > 没有看懂你的问题。
> > > 首先，我们没有mysql cli这种东西，不涉及事务时，直接创建任务就可以了。
> > > 其次，mysql都是传SQL语句，本身不区分什么读写。
> > 
> > 
> > 那我是要通过应答回调来判断我插入成功还是查询成功吗，我操作mysql任何语句我都是需要关注是否成功。 如果不成功我又怎么获取是哪条语句失败了，暂时不使用事务。
> 
> 看一下文档吧。callback里有可以从MySQLResult里看，都有状态。还可以拿到你的query语句。

![image](https://github.com/sogou/workflow/assets/20756430/92e09d6f-a124-43ea-935b-35553fdd6217)
请问下这个定时任务，可以这么创建吗，我的业务是有消息的时候等待一段就执行，没任务的时候任务也不需要存在，这样创建是否会有性能影响。

**Comment by Barenboim** [comment]
> > > > 没有看懂你的问题。
> > > > 首先，我们没有mysql cli这种东西，不涉及事务时，直接创建任务就可以了。
> > > > 其次，mysql都是传SQL语句，本身不区分什么读写。
> > > 
> > > 
> > > 那我是要通过应答回调来判断我插入成功还是查询成功吗，我操作mysql任何语句我都是需要关注是否成功。 如果不成功我又怎么获取是哪条语句失败了，暂时不使用事务。
> > 
> > 
> > 看一下文档吧。callback里有可以从MySQLResult里看，都有状态。还可以拿到你的query语句。
> 
> ![image](https://private-user-images.githubusercontent.com/20756430/334773768-92e09d6f-a124-43ea-935b-35553fdd6217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODE0NzQsIm5iZiI6MTcxNjk4MTE3NCwicGF0aCI6Ii8yMDc1NjQzMC8zMzQ3NzM3NjgtOTJlMDlkNmYtYTEyNC00M2VhLTkzNWItMzU1NTNmZGQ2MjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGUxNmI4Y2FjZTU2MzFjYmFjMTgyMThkMzFlZTI2YzdkM2Y4Y2NlMjkwOTdkNjhjYzU2YWY0MzA5OGJiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVqC_1vW0QSnYbqJxvLvU-AhFYO-LPKIUd3HFIUwMZM) 请问下这个定时任务，可以这么创建吗，我的业务是有消息的时候等待一段就执行，没任务的时候任务也不需要存在，这样创建是否会有性能影响。

这么建timer没有什么问题，但是，你给timer命名了，这样会影响性能。除非你有cancel的需求，否则不要给timer命名。

**Comment by zxyAcmen** [comment]
> > > > > 没有看懂你的问题。
> > > > > 首先，我们没有mysql cli这种东西，不涉及事务时，直接创建任务就可以了。
> > > > > 其次，mysql都是传SQL语句，本身不区分什么读写。
> > > > 
> > > > 
> > > > 那我是要通过应答回调来判断我插入成功还是查询成功吗，我操作mysql任何语句我都是需要关注是否成功。 如果不成功我又怎么获取是哪条语句失败了，暂时不使用事务。
> > > 
> > > 
> > > 看一下文档吧。callback里有可以从MySQLResult里看，都有状态。还可以拿到你的query语句。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/20756430/334773768-92e09d6f-a124-43ea-935b-35553fdd6217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODE0NzQsIm5iZiI6MTcxNjk4MTE3NCwicGF0aCI6Ii8yMDc1NjQzMC8zMzQ3NzM3NjgtOTJlMDlkNmYtYTEyNC00M2VhLTkzNWItMzU1NTNmZGQ2MjE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExMTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGUxNmI4Y2FjZTU2MzFjYmFjMTgyMThkMzFlZTI2YzdkM2Y4Y2NlMjkwOTdkNjhjYzU2YWY0MzA5OGJiODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VVqC_1vW0QSnYbqJxvLvU-AhFYO-LPKIUd3HFIUwMZM) 请问下这个定时任务，可以这么创建吗，我的业务是有消息的时候等待一段就执行，没任务的时候任务也不需要存在，这样创建是否会有性能影响。
> 
> 这么建timer没有什么问题，但是，你给timer命名了，这样会影响性能。除非你有cancel的需求，否则不要给timer命名。

有这个需要的，当我的应答结果上来了，会把真正的结果发送出去，然后会主动取消这个定时器

**Comment by Barenboim** [comment]
嗯嗯，那你实测一下吧。timer也是一种任务，和其它任务没有什么区别。

**Comment by Barenboim** [comment]
任务都是异步的，但主线程可不能返回。我们所有的示例里，都会保证任务都到了callback才唤醒主线程。

**Comment by zxyAcmen** [comment]
> 任务都是异步的，但主线程可不能返回。我们所有的示例里，都会保证任务都到了callback才唤醒主线程。

主线程不是退出，是返回做别的事情了。

**Comment by zxyAcmen** [comment]
起一个定时任务就是一个线程，这个感觉不太行，一般业务可能一下子几百子任务，有可能一下子一个任务没有，这要根据这情况起任务的话，一下子起几百个线程不得累死机器。

**Comment by Barenboim** [comment]
> 起一个定时任务就是一个线程，这个感觉不太行，一般业务可能一下子几百子任务，有可能一下子一个任务没有，这要根据这情况起任务的话，一下子起几百个线程不得累死机器。

当然不是一个定时任务一个线程了。你还是实测一下吧。异常任务和线程之间没有关系。你开100万个定时器都没问题。

**Comment by zxyAcmen** [comment]
业务紧迫，那帮忙看下我这样使用是不是没问题
![image](https://github.com/sogou/workflow/assets/20756430/405c476f-20ee-4930-8387-32ba60fa1625)

**Comment by Barenboim** [comment]
你自己测一下吧。代码结构问题不大，但我怎么知道你那些调用有没有问题。

另外，如果你是在timer callback里创建mysql任务，最好是把任务push_back到series里，而不是重新start。不过你这么做也没有什么问题。

你应该多看我们文档，我们也是要打工的，没有办法帮你看太多业务代码。

**Comment by Barenboim** [comment]
process在网络线程里，默认应该是40个吧。你只要不阻塞，一般不会有问题

**Comment by zxyAcmen** [comment]
> process在网络线程里，默认应该是40个吧。你只要不阻塞，一般不会有问题

这中间我会访问别的中间件，就怕别的中间件出问题，那如果我放到series_of中去处理，中间件出问题卡住了是不是效果一样，还说是放到series_of里会好些。

**Comment by Barenboim** [comment]
中间件是http的吧？那肯定是把http任务放series里啊。不要在 process里等。

**Comment by zxyAcmen** [comment]
> 中间件是http的吧？那肯定是把http任务放series里啊。不要在 process里等。

下面两个调用一个是mysql,一个是kafka,就怕到时候网络出问题，那要放到series,就是在回调process了就直接创建一个任务放到series中吗？ 有具体的例子吗？

**Comment by Barenboim** [comment]
> > 中间件是http的吧？那肯定是把http任务放series里啊。不要在 process里等。
> 
> 下面两个调用一个是mysql,一个是kafka,就怕到时候网络出问题，那要放到series,就是在回调process了就直接创建一个任务放到series中吗？ 有具体的例子吗？

到处都是例子……麻烦你看一下我们10几个tutorial吧，特别是http_proxy，http_file_server这些。不能什么都要问。

**Comment by zxyAcmen** [comment]
> > > 中间件是http的吧？那肯定是把http任务放series里啊。不要在 process里等。
> > 
> > 
> > 下面两个调用一个是mysql,一个是kafka,就怕到时候网络出问题，那要放到series,就是在回调process了就直接创建一个任务放到series中吗？ 有具体的例子吗？
> 
> 到处都是例子……麻烦你看一下我们10几个tutorial吧，特别是http_proxy，http_file_server这些。不能什么都要问。

![image](https://github.com/sogou/workflow/assets/20756430/53d010c3-0452-4838-892d-20e933811831)
这jf里崩溃了

**Comment by Barenboim** [comment]
你这代码写的是啥？你在什么地方给series的context赋值了？

你是不是之前没用过C++啊。

我觉得这些问题，你应该问一下你公司里的leader。

**Comment by zxyAcmen** [comment]
> 你这代码写的是啥？你在什么地方给series的context赋值了？
> 
> 你是不是之前没用过C++啊。
> 
> 我觉得这些问题，你应该问一下你公司里的leader。

我看例子这样写，头文件也没有说明啊，我无语了

**Comment by Barenboim** [comment]
你还是咨询一下你的leader吧，看起来好像也是你leader让你用我们框架的。


很多问题真的太基本了，我们文档写得再好，也没办法解决你不会C++的问题。


我们是开源作者，不是客服。能帮的我们都帮了。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月3日(周一) 下午5:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [sogou/workflow] myssql cli 使用是否可以创建多个任务 (Issue #1563)




 
像这种可以给个默认参数，或者头文件说明一下啊，哥

**Comment by zxyAcmen** [comment]
> 你还是咨询一下你的leader吧，看起来好像也是你leader让你用我们框架的。 很多问题真的太基本了，我们文档写得再好，也没办法解决你不会C++的问题。 我们是开源作者，不是客服。能帮的我们都帮了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月3日(周一) 下午5:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [sogou/workflow] myssql cli 使用是否可以创建多个任务 (Issue #1563) 像这种可以给个默认参数，或者头文件说明一下啊，哥 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的，谢谢，偷偷告诉你，我leader被开除了。

**Comment by Barenboim** [comment]
> > 你还是咨询一下你的leader吧，看起来好像也是你leader让你用我们框架的。 很多问题真的太基本了，我们文档写得再好，也没办法解决你不会C++的问题。 我们是开源作者，不是客服。能帮的我们都帮了。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年6月3日(周一) 下午5:35 收件人: _**@**_.**_>; 抄送: _**@**_._**>;"State _**@**_.**_>; 主题: Re: [sogou/workflow] myssql cli 使用是否可以创建多个任务 (Issue #1563) 像这种可以给个默认参数，或者头文件说明一下啊，哥 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 好的，谢谢，偷偷告诉你，我leader被开除了。

那你压力也很大，能理解。

不过，你程序出了问题，还是应该自己先调试，因为很多问题和我们用法根本无关，你自己打印一下都知道问题在哪里。

希望之后你发更多有建设性的issue。

**Comment by zxyAcmen** [comment]
> > > 你还是咨询一下你的leader吧，看起来好像也是你leader让你用我们框架的。 很多问题真的太基本了，我们文档写得再好，也没办法解决你不会C++的问题。 我们是开源作者，不是客服。能帮的我们都帮了。
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年6月3日(周一) 下午5:35 收件人: _**@**_.**_>; 抄送: _**@**_._**>;"State _**@**_.**_>; 主题: Re: [sogou/workflow] myssql cli 使用是否可以创建多个任务 (Issue #1563) 像这种可以给个默认参数，或者头文件说明一下啊，哥 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> > 
> > 
> > 好的，谢谢，偷偷告诉你，我leader被开除了。
> 
> 那你压力也很大，能理解。
> 
> 不过，你程序出了问题，还是应该自己先调试，因为很多问题和我们用法根本无关，你自己打印一下都知道问题在哪里。
> 
> 希望之后你发更多有建设性的issue。

谢谢理解 ，其实我还有一点没有想明白，比如这个
![image](https://github.com/sogou/workflow/assets/20756430/f566d978-b789-4872-9ece-264f2a71175c)

我肯定是有需要的时候就会创建一个任务，然后series_of是要根据task创建才会在同一个分枝上，因为有可能我的任务不会是连续的，不会说根据redis返回的结果后就在回调里处理下一个任务，可能是过半小时再有redis请求需要处理，这个时候我是需要保存一下这个task的指针呢还是直接创建一个新的任务就行，我理解的可能是这个redis_callback回调执行完这个指针可能就失效了。因为我看文档当中有提到，创建一个新任务就会创建一个橷serise，又觉得这个task是不是可以用作全局保存一下，方便有任务的时候直接使用series，有点愚笨，给指点指点。

**Comment by Barenboim** [comment]
task在callback之后就回收了，指针无效了，所以怎么多不可能在callback之后保持task指针。

半小时之后的任务，和之前的task显然不是一个流程上的东西了，重新创建运行就可以。

创建新任务并不是会创建一个series，而是说任务一定运行在series上。如果直接start一个任务，内部会自动创建一个series。

**Comment by zxyAcmen** [comment]
> task在callback之后就回收了，指针无效了，所以怎么都不可能在callback之后保持task指针。
> 
> 半小时之后的任务，和之前的task显然不是一个流程上的东西了，重新创建运行就可以。
> 
> 创建新任务并不是会创建一个series，而是说任务一定运行在series上。如果直接start一个任务，内部会自动创建一个series。

明白了，就是说内部自己会维护最少一个series, 如果在同一个task上使用series_of 对于连续的任务就能保证在同一个series上，如果是新建没法保证在同一个series上，但内部还是会有series在执行，可以这么理解吗

**Comment by zxyAcmen** [comment]
> task在callback之后就回收了，指针无效了，所以怎么都不可能在callback之后保持task指针。
> 
> 半小时之后的任务，和之前的task显然不是一个流程上的东西了，重新创建运行就可以。
> 
> 创建新任务并不是会创建一个series，而是说任务一定运行在series上。如果直接start一个任务，内部会自动创建一个series。

这里是说我直接创建一个任务，不需要再start了吗

**Comment by Barenboim** [comment]
> > task在callback之后就回收了，指针无效了，所以怎么都不可能在callback之后保持task指针。
> > 半小时之后的任务，和之前的task显然不是一个流程上的东西了，重新创建运行就可以。
> > 创建新任务并不是会创建一个series，而是说任务一定运行在series上。如果直接start一个任务，内部会自动创建一个series。
> 
> 这里是说我直接创建一个任务，不需要再start了吗

当然需要start！

任务要么push_back到运行中的series，要么start。你这个新任务和之前的没有关系了，当然要start。

另外，你这些东西完全可以实验一下再来问。
