### ISSUE TITLE
能否给xmake中的workflow加上windows的支持

### ISSUE THREAD

**Issue by heheda123123** [sogou/workflow#1569]
@Barenboim 你好，我看xmake仓库里的workflow包是你提交的，能否加上windows的支持呢
https://github.com/xmake-io/xmake-repo/blob/dev/packages/w/workflow/xmake.lua

**Comment by holmes1412** [comment]
H i，感谢～ windows环境我们基本不用，都是开源开发者帮支持的。如果你在windows下、又用过xmake，请问可以帮我们提交一下吗？

**Comment by heheda123123** [comment]
> H i，感谢～ windows环境我们基本不用，都是开源开发者帮支持的。如果你在windows下、又用过xmake，请问可以帮我们提交一下吗？

可以的，不过刚刚发现个问题。只看windows分支里面的commit消息，没有明确的版本信息，怎么和release里面的版本号对应呢？或者你们在release里面也加上windows版本的源码？

**Comment by Barenboim** [comment]
你好，release里没有办法加windows源码，功能上没有办法对齐，而且会让主版代码变得很难看，各种ifdef都有出来……

Windows我们现在更需要一个合作开发者帮我们对齐功能，或者如果谁有兴趣，重写开个项目也可以，做出完全跨平台的。

**Comment by Barenboim** [comment]
目前Windows的，还是直接下载最新代码比较好。

**Comment by heheda123123** [comment]
ok，我先把windows分支的最新commit加上，windows测试能跑，后面功能对齐了再改

**Comment by Barenboim** [comment]
@heheda123123 感谢帮我们加windows版的xmake repo! 如果我们项目对你有帮助，也麻烦star一下。
