### ISSUE TITLE
task之间如何顺序传递数据？

### ISSUE THREAD

**Issue by pi1ot** [sogou/workflow#157]
task之间如何顺序传递数据？task1的输出如何自然的（最好还是免复制的）传递给task2的输入？

**Comment by Barenboim** [comment]
同一个series吗？series->set_context()，get_context()。

**Comment by pi1ot** [comment]
> 同一个series吗？series->set_context()，get_context()。

看起来是类似全剧变量或者参数服务器这样的解决方案，有没有可能使用更自然的函数返回值和函数参数这样的组合形式？

**Comment by Barenboim** [comment]
不好弄，主要是task的形态比较自由。你可能是想一上来就把task都创建好，不用写callback? 你可以试试WFDynamicTask，这种task通过一个函数在它实际启动的时候再生成具体的task。也许能用上。

**Comment by pi1ot** [comment]
> 不好弄，主要是task的形态比较自由。你可能是想一上来就把task都创建好，不用写callback? 你可以试试WFDynamicTask，这种task通过一个函数在它实际启动的时候再生成具体的task。也许能用上。

多谢，方便给个example或者demo代码的url吗？

**Comment by Barenboim** [comment]
WFDynamicTask *WFTaskFactory::create_dynamic_task(std::function<SubTask *()> func);
func返回一个任意类型的task，并且作为下一个task被启动。不过我突然觉得接口这样跟好：
WFDynamicTask *WFTaskFactory::create_dynamic_task(std::function<SubTask *(WFDynamicTask *)> func);
下一个版本改一下。
不一定能直接解决你的问题，但是可以把一切任务变成动态创建，避免callback。要做成你说的形式，可能还需要再进行封装。

**Comment by Barenboim** [comment]
一个简单例子，需要更新到最新代码：
~~~cpp
#include <iostream>
#include "workflow/WFFacilities.h"
#include "workflow/WFTaskFactory.h"

WFFacilities::WaitGroup wait_group(1);

SubTask *f(WFDynamicTask *task)
{
    std::string url;
    std::cin >> url;
    return WFTaskFactory::create_http_task(url, 3, 0, [](WFHttpTask *task) {
        const void *body;
        size_t size;

        task->get_resp()->get_parsed_body(&body, &size);
        std::cout << (const char *)body;
        wait_group.done();
    });
}

int main()
{
    WFDynamicTask *t = WFTaskFactory::create_dynamic_task(f);
    t->start();
    wait_group.wait();
    return 0;
}
~~~cpp

**Comment by pi1ot** [comment]
> WFDynamicTask *WFTaskFactory::create_dynamic_task(std::function<SubTask *()> func);
> func返回一个任意类型的task，并且作为下一个task被启动。不过我突然觉得接口这样跟好：
> WFDynamicTask *WFTaskFactory::create_dynamic_task(std::function<SubTask *(WFDynamicTask *)> func);
> 下一个版本改一下。
> 不一定能直接解决你的问题，但是可以把一切任务变成动态创建，避免callback。要做成你说的形式，可能还需要再进行封装。

不好意思，可能误会了，我的本意并不是不写回调，是在workflow的基础上怎么实现dataflow。
比如一个workflow：task1 -> task2 -> task3

**Comment by Barenboim** [comment]
我看了看taskflow里的讨论，其实在我们的系统里现在这个问题同样是一个开放性问题，目前在解决方案上我们的选择比taskflow还是要多一些的，起码有个series context可以用来作为公共上下文。
其实更难解决的问题是在DAG这个场景下。因为DAG里每个任务都可能有多个前驱节点，每个节点会产生不同的输出。目前我们有一个模块是可以解决这个问题的，但因为使用便利性的问题，还没有正式标准化。
另外，如果对DAG有使用需求，我们提供了WFGraphTask。这个模块的实现有点参考taskflow，也是用了precede函数。但同样的，没有为节点间传递数的问题提供统一方案，用户需要自己解决。在DAG里，WFDynamicTask就显得尤为重要了。
