### ISSUE TITLE
redis zadd命令使用，set_request第二个参数是vector<stirng>, 没法添加int类型 score

### ISSUE THREAD

**Issue by zxyAcmen** [sogou/workflow#1571]
![image](https://github.com/sogou/workflow/assets/20756430/19f665a8-6d1f-4c50-9876-cd5a02227e6e)
![image](https://github.com/sogou/workflow/assets/20756430/1809c72b-ebdd-4835-982e-ca3ea3ba4192)
大佬们给看看

**Comment by zxyAcmen** [comment]
![image](https://github.com/sogou/workflow/assets/20756430/2217f462-4401-473b-8c5b-b88d12aa7231)
![image](https://github.com/sogou/workflow/assets/20756430/1d67b4e7-075b-41cf-a10a-82c394c850c0)

**Comment by zxyAcmen** [comment]
> ```c++
> std::string ScoreStr = std::to_string(score);
> req->set_request("ZADD", {key, scoreStr, Value});
> ```

内部会自动指令把score转成int类型，是这样吗

**Comment by kedixa** [comment]
不会，redis协议都是字符串形式，转换是在服务器端实现的

**Comment by zxyAcmen** [comment]
好的，谢谢，学习到了，哈哈。然后就是咱们workflow里所有的任务只要是通过回调到业务层的，就不会再阻塞series的任务了吧，还是说需要业务层自己再把对应的信息异常放到别的任务里执行，让回调的函数快速返回才行。

**Comment by kedixa** [comment]
任务的回调函数结束后，series中的下一个任务会被调起，如果已经没有更多任务，series的回调函数会被调起。因此不能在回调函数中执行耗时的操作（比如sleep），而应尽快执行完回调函数。如果确实有耗时的操作，可封装成WFGoTask在计算线程中执行。

**Comment by zxyAcmen** [comment]
好的，感谢，我去看看WFGoTask如何使用

**Comment by zxyAcmen** [comment]
![image](https://github.com/sogou/workflow/assets/20756430/6e6dc93b-4f59-48f5-9595-a8debb5926dc)
大佬再帮我解答一下这个问题吧，像这个zadd函数，我有可能 是基于别的模块有数据触发我才会调用，没数据的时候我不会调用，我这个start可以这么用吗？还是说我在初始的化的start一次，然后每次调用这个函数时，只需要创建任务，不用再start了，我只需要保证我的主程序在运行就行。


主要我对这个start的理解没有搞明白，有人说每次start会创建series， 有感觉可以只start一次，跟我们的业务逻辑一样，start后就是逻辑处理，这个start是不是也可以理解成只需要调用一次，内部会维护一个series，然后有任务就执行，没任务就待，然后要用的时候再创建一个任务，就不需要再start了

**Comment by kedixa** [comment]
不是。

之所以你会如此误解，我感觉是因为`start`这个名字起的不好，令人有【这是创建了一个后台服务，既然有`task->start();`，那只要我还没`task->stop();`这个服务就一直在运行】的感觉。实际上完全不是，要熟练使用`workflow`框架，需要简单了解一下其设计原理。

阅读`WFXxxTask`的代码可以发现，所谓`task->start`其实就是创建了一个`SeriesWork`然后启动它，等价于
```cpp
SeriesWork *series = Workflow::create_series_work(task, nullptr);
series->start();
```

在`workflow`中，`Task`表达的是一个任务的概念，任务可以是一个Http请求、一个Redis请求、一个计算任务等等，每次执行任务都需要创建`WFXxxTask`，然后将其放置到一个`SeriesWork`上来执行。

`SeriesWork`是维护需要被执行的任务序列的一种东西，我找不到特别容易理解的词来形容这个概念，`workflow`的Series(任务流)更像是无栈协程中的`handle`。或者，如果你熟悉线程模型，可以强硬地认为`Task`是一个个的函数，`Series`像是启动了一个线程，逐个执行其中的函数，直到没有函数可执行时自动退出。

了解了这两点，就可以解决你的疑惑了。当有**新**任务要执行时，比如执行Redis命令`get key`，需要

1. 创建一个`WFRedisTask`，将Redis命令填写到请求体上，设置回调函数
2. 使用这个任务，创建一个新的Series
3. 运行新Series
4. 在任务回调函数中处理结果

其中步骤二和三可以通过`task->start()`化简为一步。所以每个新任务都需要创建新的`Task`（以及用于运行这个任务的`SeriesWork`）。我个人认为，把函数`series->start()`命名为`series->detach()`可能更贴切，像是一个线程被分离出去，如果不采用同步机制，则无法在当前上下文`join`(汇合)它的执行结果。

最后在简单提一下生命周期的问题。`Task`的生命周期在其回调函数结束后结束，在回调函数中，可以继续产生新的`Task`并放置到当前`SeriesWork`上面。当前`Task`运行结束后，`SeriesWork`会取出下一个任务继续运行，当没有新任务时`SeriesWork`会调起自己的回调函数，它的生命周期在自己的回调函数结束后结束。

**Comment by zxyAcmen** [comment]
series 没有任务了会退出吗？如果退出的话那我就能理解每一个新task都需要start了，然后我不想这个series退出的话就在回调函数里通过task获取到series，再把任务push进来，这个series有任务就不会退出了，是这样理解吗？

**Comment by zxyAcmen** [comment]
有这个想法是因为我看boost asio里也都是只要run一次，然后业务层提交任务给它就行，不用的时候stop一下就好，然后我就一直在这思维里。

**Comment by Barenboim** [comment]
> 看到你说的没有任务会退出了，如果我当线程来理解的话，那100个任务start就起了100个线程，这好像又不合理。

为什么你总是认为任务要对应到一个线程……

另外，你做点实验吧。

**Comment by zxyAcmen** [comment]
> series

series 我是说这个，task我知道就是一个函数，用户函数

**Comment by Barenboim** [comment]
series也不是一个线程……

**Comment by zxyAcmen** [comment]
> series 没有任务了会退出。在回调函数里通过task获取到series，再把任务push进来，这个series有任务就不会退出了。
> 
> 没用过asio，不过我猜它的run是启动一个事件循环，或者一个任务调度器，它可能允许一个进程启动多个调度器。workflow使用的是单例模式，全局只有一个调度器，在第一次使用时启动，在进程退出时结束。
> 
> 如果我当“线程”来理解的话，那100个任务start就起了100个“线程”。需要加引号，因为只是在理解概念，实际上是100个任务start就起了100个SeriesWork。

对，asio你理解的是对的，那咱们的这个SeriesWork内部有起线程或者协程吗？还是说内部也是一个函数队列，然后执行。没有另起线程或协程之类的。

**Comment by zxyAcmen** [comment]
好的，非常感谢哈，我属于半吊子，又比较烦的那种，真的非常感谢。

**Comment by Barenboim** [comment]
建议搞不懂可以看一下源代码。我们的代码都很简单，没有什么高级特征。

**Comment by zxyAcmen** [comment]
> 建议搞不懂可以看一下源代码。我们的代码都很简单，没有什么高级特征。

好的，谢谢

**Comment by zxyAcmen** [comment]
> 建议搞不懂可以看一下源代码。我们的代码都很简单，没有什么高级特征。

![image](https://github.com/sogou/workflow/assets/20756430/805dabc0-5c2b-4bd3-aa0e-dde3537b686c)
大佬，看下这个，我试使用mget 的时候可以对多个key进行操作的，这个SMEMBERS是不支持吗，SMEMBERS只能一个key一个key操作吧，我看头文件数据返回也只有一个vector。

**Comment by kedixa** [comment]
`Redis`相关命令可以参考官方文档，里面有每个命令的请求和回复的格式，回复的格式只看`RESP2 Reply`即可。具体你的`Redis Server`支持哪些命令，需要看其版本和配置，`Workflow`只管协议层面的事情。
https://redis.io/docs/latest/commands/smembers/

**Comment by zxyAcmen** [comment]
> `Redis`相关命令可以参考官方文档，里面有每个命令的请求和回复的格式，回复的格式只看`RESP2 Reply`即可。具体你的`Redis Server`支持哪些命令，需要看其版本和配置，`Workflow`只管协议层面的事情。 https://redis.io/docs/latest/commands/smembers/

明白了，感谢。

**Comment by kedixa** [comment]
可以这么认为。`series`是一个双端队列，但如果一开始就通过`series->push_back`把任务都放进去，就退化成了队列，先进先出。

**Comment by zxyAcmen** [comment]
您说的这个一开始是指第一次创建的时候吗？

这样写？
        WFRedisTask *RedisTask = WFTaskFactory::create_redis_task(m_RedisUrl_, 2,
                            std::bind(&CRedisClient::selectRedis, this, std::placeholders::_1));
        RedisTask->user_data = &wait;
        protocol::RedisRequest *req = RedisTask->get_req();
        req->set_request("SMEMBERS", { simRedisKey });
        series_of(RedisTask)->push_back(RedisTask);
        series_of(RedisTask)->start();

**Comment by kedixa** [comment]
```cpp
WFRedisTask *t1 = create_redis_task(...);
SeriesWork *series = Workflow::create_series_work(t1, nullptr);

WFRedisTask *t2 = create_redis_task(...);
series->push_back(t2);

WFRedisTask *t3 = create_redis_task(...);
series->push_back(t3);

series->start();
```

**Comment by zxyAcmen** [comment]
明白了，那就是我在类里维护一下这个series就行，需要在这个上面串行的，push进去即可

**Comment by kedixa** [comment]
`在类里维护一下这个series`这个需求不是很容易，如果你真的想**一直**维护一个正在运行中的series来保证串行，可以参考 #301 中讨论的内容。

**Comment by Barenboim** [comment]
> 明白了，那就是我在类里维护一下这个series就行，需要在这个上面串行的，push进去即可

你需要注意一下，series里没有任务就结束了。

**Comment by zxyAcmen** [comment]
> `在类里维护一下这个series`这个需求不是很容易，如果你真的想**一直**维护一个正在运行中的series来保证串行，可以参考 #301 中讨论的内容。

pure virtual method called
terminate called without an active exception
pure virtual method called

![image](https://github.com/sogou/workflow/assets/20756430/df51c943-61f2-447f-aead-598428d0858a)
大佬，这个是我的任务调用顺序不对吗？

**Comment by zxyAcmen** [comment]
> 或许可以先阅读一下 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> 该问题缺少太多有效信息，所以难以完整地回答。根据已有的信息，有可能是重复使用了已经被析构了的task对象导致的。

恩恩，自己调出来了，现象是我起了个定时任务，30秒一个回调，在第二个定时任务里通过series_of使用了上一个的task，我记得有大佬说过只要回调函数返回，task 就无效了， 我直接在第二个定时任务通过新task->start() 就正常了，感谢大佬。
