### ISSUE TITLE
http请求获取对方应答的数据接口是哪一个

### ISSUE THREAD

**Issue by zxyAcmen** [sogou/workflow#1575]
情况是我使用httpclient post数据，对端会返回一个json的数据体以及200码
200 应答码可以正常获取到，但是获取不到消息体，使用的是下面两个接口都不行，请问是使用错了吗？
![image](https://github.com/sogou/workflow/assets/20756430/7a641b42-c977-4114-bdeb-0aa1736d3552)

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/master/docs/tutorial-01-wget.md

**Comment by zxyAcmen** [comment]
好的，感谢，取出来了，我要分多个路径的话，我可以这么使用吗？但是我调用cancel的时候，好像跳到别的接口里去了，奇怪。
![image](https://github.com/sogou/workflow/assets/20756430/24a14f40-caa8-4135-bdcc-a7b67b5f2af0)
