### ISSUE TITLE
能支持mqtt或zmq吗

### ISSUE THREAD

**Issue by jerry-xie-000** [sogou/workflow#1576]
想问一下Workflow自带的server工厂类怎么支持mqtt或zmq的？

还是说直接用mqtt或zmq的api来创建就可以，然后处理再调用你们的go task？这样workflow好像就只是一个线程池功能了

**Comment by Barenboim** [comment]
你好。没有研究过zmq的协议，但mqtt有看过。mqtt是一个全双工的协议，workflow主版本的server实现不了，需要用更低层poller模块来实现，或者对我们的server进行一些改动。例如这位用户的fork，就是在workflow上实现websocket的server和client：https://github.com/gnbalo/workflow
支持WebSocket server的话，要支持mqtt也很简单了。你可以看一下这个用户的改版，看看能不能在这基础上实现mqtt。
