### ISSUE TITLE
http server服务，使用WFGoTask处理请求结束后线程数没有降低

### ISSUE THREAD

**Issue by gitljh** [sogou/workflow#1577]
http server服务，压测发现：使用WFGoTask处理http request，但是任务结束后服务线程数没有降下来，会是什么原因导致的？
配置poller_threads=16, handler_threads = 64, compute_threads = 128。

**Comment by Barenboim** [comment]
你好。我们是使用线程池的。计算线程池创建之后不会自动销毁的。

**Comment by gitljh** [comment]
由于服务请求量很大，跑一个晚高峰过后，使用cat /proc/{进程号}/status 查看这个服务服务情况，发现线程数涨到大几万，这个有什么办法处理吗？
我看最新的commit:16686ba 有增加【[Enable increasing/decreasing compute threads】这个功能，是否可以通过decreasing来减少线程数量？

**Comment by Barenboim** [comment]
正常情况下，我们是不会动态增加线程的。也就是说，按照你的配置，只会存在208个线程。

除非你在网络线程里调用wait_group.wait()，这个操作一般是不应该存在的。如果你调用这个操作，我们为了保持你的活跃网络线程没有变化，会根据你最多同时等待的线程数来增加线程（最新master代码，也会动态减少）。但是，这个操作是不合理的，你应该把你的计算任务push_back到series里，而不是用wait group。

另外，你检查一下是不是你的代码会创建线程。

**Comment by gitljh** [comment]
在网络线程里面，没有调用wait_group。
在WFGoTask的计算任务里面，我们是会创建标准库线程：

... ...
WFGoTask *gtask = WFTaskFactory::create_go_task("start_task", &UnionManager::asynStartTask, this, task_info, std::ref(ret));
gtask->start();
... ...




int UnionManager::syncStartTask(TaskInfo task_info){
    std::shared_ptr<IStreamTask> task = std::make_shared<StreamTask>();
    if (task.get() == nullptr){
        return APP_RET_MEM_ALLOC_FAIL;
    }

    task->setTaskExceptionCB(this);
    int ret = task->startTask(task_info, task_info.m_stream_id, task_info.m_try_num>0?task_info.m_try_num:300); 
    if (ret != APP_RET_OK){
        return ret;
    }
    setTask(task_info.m_stream_id, task);
    return APP_RET_OK;
}




... ...

ErrorCode startTask(const TaskInfo &task_info, std::string stream_id, int try_num_limit){
    ... ...
    m_thread = new std::thread(&TaskEx::asynRunTask, this);  //std::thread会在析构里面join，然后delete
    ... ...
    return APP_RET_OK;
}

**Comment by Barenboim** [comment]
不是，你自己new线程做什么😂

应该是你自己的线程，我们框架不会创建线程的。

另外，如果你是一个server应该，不太应该直接把一个go task用start()来启动，一般都是这样：
~~~cpp
int process(WFHttpTask *task)
{
    gotask = WFTaskFactory::create_go_task(...);
    series_of(task)->push_back(go_task);
}
~~~
如果你没有使用到series，我也不清楚你是怎么实现异步的。难道你在process里直接等你的线程来唤醒？那就更加不对了。建议先看一下我们文档。

**Comment by gitljh** [comment]
> 正常情况下，我们是不会动态增加线程的。也就是说，按照你的配置，只会存在208个线程。
> 
> 除非你在网络线程里调用wait_group.wait()，这个操作一般是不应该存在的。如果你调用这个操作，我们为了保持你的活跃网络线程没有变化，会根据你最多同时等待的线程数来增加线程（最新master代码，也会动态减少）。但是，这个操作是不合理的，你应该把你的计算任务push_back到series里，而不是用wait group。
> 
> 另外，你检查一下是不是你的代码会创建线程。

【（最新master代码，也会动态减少）】这里的动态减少，是网络线程、计算线程数量都会减少吗？需要上层应用显示调用吗？

另外，我想问一下：是否有api可以知道现在框架中的网络线程、计算线程数是多少？在官方demo示例中没有找到相关调用方法
