### ISSUE TITLE
http请求不响应问题

### ISSUE THREAD

**Issue by loulansuiye** [sogou/workflow#1586]
我在arm平台上使用workflow 这个库使用一段时间之后就概率性出现http请求不响应的问题，不知道大家有没有遇到？或者有什么处理的建议

**Comment by Barenboim** [comment]
你好，有没有更多的信息提供？ 例如，你使用的workflow版本号，是否是SSL的server，配置的各种超时以及消息大小等。

**Comment by Barenboim** [comment]
@loulansuiye 如果有更多信息，随时发给我们。
