### ISSUE TITLE
服务端的process最后回复主调方的时机怎么理解的

### ISSUE THREAD

**Issue by NimbusQin** [sogou/workflow#159]
看了tutorial-05-http_proxy.cc例子，中转服务时，需要在process的同个series上添加task，那么process最后回复主调方的时机是什么时候，等添加的task都执行完成？

**Comment by Barenboim** [comment]
是的，你可以看http_proxy和http_file_server这两个例子。原理上是这样的，server task所在的series，是以processor为首任务，server task为末尾任务的。用户向这个series里添加任务，都不会影响到末尾的server task。所以，当所有用户添加的任务都执行完成，server task被启动，而server task的启动行为就是reply，于是消息被回复。如果不想回复这个消息，可以调用task->noreply()，这样的话会在原本回复的时机直接关闭连接。

**Comment by NimbusQin** [comment]
谢谢
