### ISSUE TITLE
在WFHttpServer的一个请求series里调用set_last_task设置一个任务不能成功返回http请求

### ISSUE THREAD

**Issue by wangyongxiao** [sogou/workflow#1596]
在WFHttpServer的一个请求series里调用set_last_task设置一个任务不能成功返回http请求

我想在我设置的set_last_task里对响应设置body来响应请求，但是都不行，似乎是服务端主动断开连接了

在WFHttpServer的请求series里设置set_last_task是允许的吗？如果不是，我应该在多级串联的task里返回请求呢？
~~~cpp
void workflowhttplasttasktest(){
	WFHttpServer server([](WFHttpTask *task) {
		WFGoTask *go_task3 = WFTaskFactory::create_go_task(
		"1",
		[task](){
			printf("last go_task3\n");
			task->get_resp()->append_output_body("<html>Hello World!</html>"); // 设置set_last_task后在这里响应也不行
		});

		// task->get_resp()->append_output_body("<html>Hello World!</html>"); // 设置set_last_task后在这里响应也不行
		series_of(task)->set_last_task(go_task3);
    });

    if (server.start(8888) == 0) { // start server on port 8888
        getchar(); // press "Enter" to end.
        server.stop();
    }
}
~~~

**Comment by Barenboim** [comment]
是的，set_last_task()并不是给用户用的，一般是框架或一些任务实现用的，我们在注释里有说明。

Server task的series，最后一个任务就是server task本身，除非已经运行到 server task callback，否则不能重新设置。你这个需求，可以通过一个WFModuleTask来解决。module是你自己创建的，可以任意调用set_last_task()。

**Comment by Barenboim** [comment]
你说的“多级串联”，是不是就是我们的模块任务：
https://github.com/sogou/workflow/blob/master/docs/about-module.md

**Comment by wangyongxiao** [comment]
谢谢，我先看一下模块任务

模块任务是能在模块任务运行期间动态的添加任务的吗？

比如模块里最初只有一个任务A，在任务A的运行期间我动态的在后面push_back一个任务B，这种操作是可以的吗？

**Comment by wangyongxiao** [comment]
> 谢谢，我先看一下模块任务
> 
> 模块任务是能在模块任务运行期间动态的添加任务的吗？
> 
> 比如模块里最初只有一个任务A，在任务A的运行期间我动态的在后面push_back一个任务B，这种操作是可以的吗？

测试过了，是可以动态push的

**Comment by Barenboim** [comment]
> 谢谢，我先看一下模块任务
> 
> 模块任务是能在模块任务运行期间动态的添加任务的吗？
> 
> 比如模块里最初只有一个任务A，在任务A的运行期间我动态的在后面push_back一个任务B，这种操作是可以的吗？

可以的啊，这是series的固有功能，模块其实就是内置一个子series而已。series的push_back，push_front都是加锁的，可以在运行期间添加任务。

不过，你这么做需要自己解决生命周期问题，必要的时候通过counter task阻塞series的运行。
