### ISSUE TITLE
希望增加一个中转服务并行调用下游服务的示例

### ISSUE THREAD

**Issue by NimbusQin** [sogou/workflow#160]
希望能增加一个示例：中转服务，收到请求后，并行调用多个下游服务，然后将每个下游服务的回复转发回主调方。

**Comment by Barenboim** [comment]
麻烦写一下具体需求什么的。可以贴一下你大概的代码框架。之前这个问题issue里有人问过的，你可以先翻一翻看看能不能解决你的问题。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/issues/140

**Comment by NimbusQin** [comment]
好的

**Comment by NimbusQin** [comment]
另外想问下，HttpResponse类的append_output_body()函数是多线程安全的吗

**Comment by Barenboim** [comment]
不是的！不要在每个series或task的callback里，去append回复的resp。一定是在parellel的callback里汇总做这个事情。你参考一下parallel_wget示例里的数据转递方法。HttpMessage的所有操作都是单线程的，多线程操作没有什么意义。
