### ISSUE TITLE
workflow uds通讯的性能请教

### ISSUE THREAD

**Issue by vinnie6seu** [sogou/workflow#1600]
1、背景
现在项目中，同机进程间IPC是使用机器上的消息队列，跨机是使用socket通讯。如果跨机通讯改用srpc，为了统一编码模式，同机IPC期望用workflow中的Unix domain socket (UDS)。进行workflow中UDS性能和消息队列性能的对比验证。

2、问题
（1）srpc中貌似现在不支持Unix domain socket (UDS)，是否是直接修改rpc_global.cc，增加对UDS的处理分支？后面srpc有支持计划吗？
（2）粗略写了个对比测试代码，发现都在单线程情况下，交互10万次10k数据，消息队列耗时（1.2s）< 普通socket（1.7s）< workflow uds（8.2s）。 workflow uds性能比消息队列差挺多，想请教下是哪里的问题？

3、编译和测试方法
（1）消息队列
g++ -o message_queue message_queue.cpp -std=c++11 -pthread
./message_queue
（2）普通socket
g++ -o message_socket_client message_socket_client.cpp -std=c++11 -pthread
g++ -o message_socket_server message_socket_server.cpp -std=c++11 -pthread
./message_socket_server
./message_socket_client
（3）workflow uds
使用tutorial-10-ipc_test和CMakeLists.txt编译
./server-uds ipc 4 4
./client-uds ipc 1 4 4

[ipc-test.zip](https://github.com/user-attachments/files/16478915/ipc-test.zip)

**Comment by Barenboim** [comment]
你好，srpc支持UDS的。首先，server肯定支持，start的时候传入一个sockaddr就行。
client的话，简单创建一个upstream，添加一个server指向本地文件就可以了。这个方法workflow和srpc通用。
~~~cpp
int main()
{
    UpstreamManager::create_weighted_random("uds-hostname", true);
    UpstreamManager::upstream_add_server("uds-hostname", "/home/xxx/uds-path");
    ...
}
~~~
这时候使用uds-hostname的URL就访问这个uds路径了。可以配置在SRPCClientParams里的host或URL里。

**Comment by Barenboim** [comment]
UDS性能我们没有专门测试过，UDS和普通socket对workflow来讲代码没有什么区别，就是sockaddr的family不一样而已。你实测workflow的UDS性能低于workflow的IP socket吗？

**Comment by vinnie6seu** [comment]
1、非常感谢对使用UDS的指导，辛苦了，周末还要麻烦你们。
2、粗略测了下workflow的UDS性能略好于workflow的IP socket。
3、我只是在测试过程中产生疑问：最简单的socket单线程同步通讯（message_socket_client+message_socket_server），10k数据TPS有5.8万（交互10万次耗时1.7s），workflow单线程UDS通讯TPS是1.2万（交互10万次耗时8.2s）。workflow通讯过程中没有反复建socket，也没有冗余的报文内容拷贝。按照我写的workflow测试代码，通讯模型应该和message_socket_client+message_socket_server是差不多的，不明白慢在哪里，想请教下？

（1）message_socket_client.cpp
`#include <iostream>
#include <chrono>
#include <thread>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <cstring>

constexpr int PORT = 12345;
constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

void socket_client() {
    int sock = 0;
    struct sockaddr_in serv_addr;
    char msg[MESSAGE_SIZE] = {0};
    memset(msg, 'A', MESSAGE_SIZE);

    if ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
        perror("Socket creation error");
        exit(EXIT_FAILURE);
    }

    serv_addr.sin_family = AF_INET;
    serv_addr.sin_port = htons(PORT);

    if (inet_pton(AF_INET, "127.0.0.1", &serv_addr.sin_addr) <= 0) {
        perror("Invalid address / Address not supported");
        close(sock);
        exit(EXIT_FAILURE);
    }

    if (connect(sock, (struct sockaddr*)&serv_addr, sizeof(serv_addr)) < 0) {
        perror("Connection failed");
        close(sock);
        exit(EXIT_FAILURE);
    }

    auto start = std::chrono::high_resolution_clock::now();

    for (size_t i = 0; i < NUM_MESSAGES; ++i) {
	    // 构建发送数据
	    char buffer[MESSAGE_SIZE] = {0};
	    memcpy(buffer, msg, MESSAGE_SIZE);
	
        if (send(sock, buffer, MESSAGE_SIZE, 0) == -1) {
            perror("send");
            close(sock);
            exit(EXIT_FAILURE);
        }

        if (recv(sock, buffer, MESSAGE_SIZE, 0) == -1) {
            perror("recv");
            close(sock);
            exit(EXIT_FAILURE);
        }
    }

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> elapsed = end - start;
    std::cout << "Socket performance: " << elapsed.count() << " seconds for " << NUM_MESSAGES << " messages\n";

    close(sock);
}

// g++ -o message_socket_client message_socket_client.cpp -std=c++11 -pthread
int main() {
    std::thread client_thread(socket_client);

    client_thread.join();

    return 0;
}
`
（2）message_socket_server.cpp
`#include <iostream>
#include <chrono>
#include <thread>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <cstring>

constexpr int PORT = 12345;
constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

void socket_server() {
    int server_fd, new_socket;
    struct sockaddr_in address;
    int opt = 1;
    int addrlen = sizeof(address);
    

    if ((server_fd = socket(AF_INET, SOCK_STREAM, 0)) == 0) {
        perror("socket failed");
        exit(EXIT_FAILURE);
    }

    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt))) {
        perror("setsockopt");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(PORT);

    if (bind(server_fd, (struct sockaddr*)&address, sizeof(address)) < 0) {
        perror("bind failed");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    if (listen(server_fd, 3) < 0) {
        perror("listen");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    if ((new_socket = accept(server_fd, (struct sockaddr*)&address, (socklen_t*)&addrlen)) < 0) {
        perror("accept");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    for (size_t i = 0; i < NUM_MESSAGES; ++i) {
	    char resuest[MESSAGE_SIZE] = {0};
        memset(resuest, '\0', MESSAGE_SIZE);
        if (recv(new_socket, resuest, MESSAGE_SIZE, 0) == -1) {
            perror("recv");
            close(new_socket);
            close(server_fd);
            exit(EXIT_FAILURE);
        }
		
		char response[MESSAGE_SIZE] = {0};
		memcpy(response, resuest, MESSAGE_SIZE);
        if (send(new_socket, response, MESSAGE_SIZE, 0) == -1) {
            perror("send");
            close(new_socket);
            close(server_fd);
            exit(EXIT_FAILURE);
        }
    }

    close(new_socket);
    close(server_fd);
}

// g++ -o message_socket_server message_socket_server.cpp -std=c++11 -pthread
int main() {
    std::thread server_thread(socket_server);

    server_thread.join();

    return 0;
}
`
（3）client-uds.cc
`#include <stdio.h>
#include <string.h>
#include <sys/un.h>

#include <iostream>
#include <chrono>

#include "message.h"
#include "workflow/WFFacilities.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/Workflow.h"

// ===================================================================================

constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

std::atomic<int> success_count(0);

WFFacilities::WaitGroup wait_group(1);

// ===================================================================================

using WFTutorialTask = WFNetworkTask<protocol::TutorialRequest, protocol::TutorialResponse>;
using tutorial_callback_t = std::function<void(WFTutorialTask *)>;

using namespace protocol;

class MyFactory : public WFTaskFactory {
public:
    static WFTutorialTask *create_tutorial_task(const struct sockaddr *addr, socklen_t addrlen, int retry_max, tutorial_callback_t callback) {
        using NTF = WFNetworkTaskFactory<TutorialRequest, TutorialResponse>;
        WFTutorialTask *task = NTF::create_client_task(TT_TCP, addr, addrlen, retry_max, std::move(callback));
        task->set_keep_alive(30 * 1000);

        return task;
    }
};

// ===================================================================================

int main(int argc, char *argv[]) {
    const char *path;

    if (argc != 5) {
        fprintf(stderr, "USAGE: %s <path> <send_thread_num> <poller_thread_num> <handler_thread_num>\n", argv[0]);
        exit(1);
    }

    path = argv[1];

    int send_threads = atoi(argv[2]);

    WFGlobalSettings setting = GLOBAL_SETTINGS_DEFAULT;
    setting.poller_threads = atoi(argv[3]);
    setting.handler_threads = atoi(argv[4]);

    WORKFLOW_library_init(&setting);

    ////////////////////////////////////////////////////////////////////////////////

    char buf[MESSAGE_SIZE + 1] = {'\0'};
    memset(buf, 'A', MESSAGE_SIZE);

    auto &&create = [path, buf](WFRepeaterTask *) -> SubTask * {
        if (success_count > NUM_MESSAGES) {
            return nullptr;
        }

        struct sockaddr_un sun = {};
        sun.sun_family = AF_UNIX;
        strncpy(sun.sun_path, path, sizeof sun.sun_path - 1);
        WFTutorialTask *task = MyFactory::create_tutorial_task((struct sockaddr *)&sun, sizeof sun, 0, [](WFTutorialTask *task) {
                int state = task->get_state();
                int error = task->get_error();
                TutorialResponse *resp = task->get_resp();
                void *body;
                size_t body_size;

                if (state == WFT_STATE_SUCCESS) {
                    resp->get_message_body_nocopy(&body, &body_size);
                    // printf("Server Response: %.*s\n", (int)body_size, (char *)body);

                    // 统计请求成功次数
                    ++success_count;
                } else {
                    const char *str = WFGlobal::get_error_string(state, error);
                    // fprintf(stderr, "Error: %s\n", str);
                }
            });

        task->get_req()->set_message_body(buf, MESSAGE_SIZE);
        task->get_resp()->set_size_limit(MESSAGE_SIZE);

        return task;
    };

	ParallelWork *pwork = Workflow::create_parallel_work(nullptr);

    for (int i = 0; i < send_threads; i++) {
        WFRepeaterTask *repeater;
        repeater = WFTaskFactory::create_repeater_task(std::move(create), nullptr);

        SeriesWork* series = Workflow::create_series_work(repeater, nullptr);

        pwork->add_series(series);
    }

    ////////////////////////////////////////////////////////////////////////////////

    auto start = std::chrono::high_resolution_clock::now();

    ////////////////////////////////////////////////////////////////////////////////

    Workflow::start_series_work(pwork, [&wait_group](const SeriesWork *) {
        wait_group.done();
    });

    wait_group.wait();

    ////////////////////////////////////////////////////////////////////////////////

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> elapsed = end - start;
    std::cout << "Message queue performance: " << elapsed.count() << " seconds for " << NUM_MESSAGES << " messages\n";

    return 0;
}`
（4）server-uds.cc
`#include <ctype.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/un.h>

#include "message.h"
#include "workflow/WFFacilities.h"
#include "workflow/WFServer.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/Workflow.h"

using WFTutorialTask = WFNetworkTask<protocol::TutorialRequest, protocol::TutorialResponse>;
using WFTutorialServer = WFServer<protocol::TutorialRequest, protocol::TutorialResponse>;

using namespace protocol;

constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

void process(WFTutorialTask *task) {
    TutorialRequest *req = task->get_req();
    TutorialResponse *resp = task->get_resp();
    void *body;
    size_t size;
    size_t i;

    req->get_message_body_nocopy(&body, &size);
    // for (i = 0; i < size; i++)
    //     ((char *)body)[i] = toupper(((char *)body)[i]);

    resp->set_message_body(body, size);
}

static WFFacilities::WaitGroup wait_group(1);

void sig_handler(int signo) {
    wait_group.done();
}

int main(int argc, char *argv[]) {
    struct sockaddr_un sun = {};

    if (argc != 4) {
        fprintf(stderr, "USAGE %s <path> <poller_thread_num> <handler_thread_num>\n", argv[0]);
        exit(1);
    }

    sun.sun_family = AF_UNIX;
    strncpy(sun.sun_path, argv[1], sizeof sun.sun_path - 1);

    WFGlobalSettings setting = GLOBAL_SETTINGS_DEFAULT;
    setting.poller_threads = atoi(argv[2]);
    setting.handler_threads = atoi(argv[3]);

    WORKFLOW_library_init(&setting);

    ////////////////////////////////////////////////////////////////////////////////

    signal(SIGINT, sig_handler);

    ////////////////////////////////////////////////////////////////////////////////

    struct WFServerParams params = SERVER_PARAMS_DEFAULT;
    params.request_size_limit = MESSAGE_SIZE;

    WFTutorialServer server(&params, process);

    if (server.start((struct sockaddr *)&sun, sizeof sun) == 0) {
        wait_group.wait();

        server.stop();
    } else {
        perror("server.start");
        exit(1);
    }

    return 0;
}
`

**Comment by vinnie6seu** [comment]
1、非常感谢对使用UDS的指导，辛苦了，周末还要麻烦你们。
2、粗略测了下workflow的UDS性能略好于workflow的IP socket。
3、我只是在测试过程中产生疑问：最简单的socket单线程同步通讯（message_socket_client+message_socket_server），10k数据TPS有5.8万（交互10万次耗时1.7s），workflow单线程UDS通讯TPS是1.2万（交互10万次耗时8.2s）。workflow通讯过程中没有反复建socket，也没有冗余的报文内容拷贝。按照我写的workflow测试代码，通讯模型应该和message_socket_client+message_socket_server是差不多的，不明白慢在哪里，想请教下？

（1）message_socket_client.cpp
```c++
#include <iostream>
#include <chrono>
#include <thread>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <cstring>

constexpr int PORT = 12345;
constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

void socket_client() {
    int sock = 0;
    struct sockaddr_in serv_addr;
    char msg[MESSAGE_SIZE] = {0};
    memset(msg, 'A', MESSAGE_SIZE);

    if ((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0) {
        perror("Socket creation error");
        exit(EXIT_FAILURE);
    }

    serv_addr.sin_family = AF_INET;
    serv_addr.sin_port = htons(PORT);

    if (inet_pton(AF_INET, "127.0.0.1", &serv_addr.sin_addr) <= 0) {
        perror("Invalid address / Address not supported");
        close(sock);
        exit(EXIT_FAILURE);
    }

    if (connect(sock, (struct sockaddr*)&serv_addr, sizeof(serv_addr)) < 0) {
        perror("Connection failed");
        close(sock);
        exit(EXIT_FAILURE);
    }

    auto start = std::chrono::high_resolution_clock::now();

    for (size_t i = 0; i < NUM_MESSAGES; ++i) {
	    // 构建发送数据
	    char buffer[MESSAGE_SIZE] = {0};
	    memcpy(buffer, msg, MESSAGE_SIZE);
	
        if (send(sock, buffer, MESSAGE_SIZE, 0) == -1) {
            perror("send");
            close(sock);
            exit(EXIT_FAILURE);
        }

        if (recv(sock, buffer, MESSAGE_SIZE, 0) == -1) {
            perror("recv");
            close(sock);
            exit(EXIT_FAILURE);
        }
    }

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> elapsed = end - start;
    std::cout << "Socket performance: " << elapsed.count() << " seconds for " << NUM_MESSAGES << " messages\n";

    close(sock);
}

// g++ -o message_socket_client message_socket_client.cpp -std=c++11 -pthread
int main() {
    std::thread client_thread(socket_client);

    client_thread.join();

    return 0;
}
```
（2）message_socket_server.cpp
```c++
#include <iostream>
#include <chrono>
#include <thread>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <cstring>

constexpr int PORT = 12345;
constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

void socket_server() {
    int server_fd, new_socket;
    struct sockaddr_in address;
    int opt = 1;
    int addrlen = sizeof(address);
    

    if ((server_fd = socket(AF_INET, SOCK_STREAM, 0)) == 0) {
        perror("socket failed");
        exit(EXIT_FAILURE);
    }

    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &opt, sizeof(opt))) {
        perror("setsockopt");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(PORT);

    if (bind(server_fd, (struct sockaddr*)&address, sizeof(address)) < 0) {
        perror("bind failed");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    if (listen(server_fd, 3) < 0) {
        perror("listen");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    if ((new_socket = accept(server_fd, (struct sockaddr*)&address, (socklen_t*)&addrlen)) < 0) {
        perror("accept");
        close(server_fd);
        exit(EXIT_FAILURE);
    }

    for (size_t i = 0; i < NUM_MESSAGES; ++i) {
	    char resuest[MESSAGE_SIZE] = {0};
        memset(resuest, '\0', MESSAGE_SIZE);
        if (recv(new_socket, resuest, MESSAGE_SIZE, 0) == -1) {
            perror("recv");
            close(new_socket);
            close(server_fd);
            exit(EXIT_FAILURE);
        }
		
		char response[MESSAGE_SIZE] = {0};
		memcpy(response, resuest, MESSAGE_SIZE);
        if (send(new_socket, response, MESSAGE_SIZE, 0) == -1) {
            perror("send");
            close(new_socket);
            close(server_fd);
            exit(EXIT_FAILURE);
        }
    }

    close(new_socket);
    close(server_fd);
}

// g++ -o message_socket_server message_socket_server.cpp -std=c++11 -pthread
int main() {
    std::thread server_thread(socket_server);

    server_thread.join();

    return 0;
}
```
（3）client-uds.cc
```c++
#include <stdio.h>
#include <string.h>
#include <sys/un.h>

#include <iostream>
#include <chrono>

#include "message.h"
#include "workflow/WFFacilities.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/Workflow.h"

// ===================================================================================

constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

std::atomic<int> success_count(0);

WFFacilities::WaitGroup wait_group(1);

// ===================================================================================

using WFTutorialTask = WFNetworkTask<protocol::TutorialRequest, protocol::TutorialResponse>;
using tutorial_callback_t = std::function<void(WFTutorialTask *)>;

using namespace protocol;

class MyFactory : public WFTaskFactory {
public:
    static WFTutorialTask *create_tutorial_task(const struct sockaddr *addr, socklen_t addrlen, int retry_max, tutorial_callback_t callback) {
        using NTF = WFNetworkTaskFactory<TutorialRequest, TutorialResponse>;
        WFTutorialTask *task = NTF::create_client_task(TT_TCP, addr, addrlen, retry_max, std::move(callback));
        task->set_keep_alive(30 * 1000);

        return task;
    }
};

// ===================================================================================

int main(int argc, char *argv[]) {
    const char *path;

    if (argc != 5) {
        fprintf(stderr, "USAGE: %s <path> <send_thread_num> <poller_thread_num> <handler_thread_num>\n", argv[0]);
        exit(1);
    }

    path = argv[1];

    int send_threads = atoi(argv[2]);

    WFGlobalSettings setting = GLOBAL_SETTINGS_DEFAULT;
    setting.poller_threads = atoi(argv[3]);
    setting.handler_threads = atoi(argv[4]);

    WORKFLOW_library_init(&setting);

    ////////////////////////////////////////////////////////////////////////////////

    char buf[MESSAGE_SIZE + 1] = {'\0'};
    memset(buf, 'A', MESSAGE_SIZE);

    auto &&create = [path, buf](WFRepeaterTask *) -> SubTask * {
        if (success_count > NUM_MESSAGES) {
            return nullptr;
        }

        struct sockaddr_un sun = {};
        sun.sun_family = AF_UNIX;
        strncpy(sun.sun_path, path, sizeof sun.sun_path - 1);
        WFTutorialTask *task = MyFactory::create_tutorial_task((struct sockaddr *)&sun, sizeof sun, 0, [](WFTutorialTask *task) {
                int state = task->get_state();
                int error = task->get_error();
                TutorialResponse *resp = task->get_resp();
                void *body;
                size_t body_size;

                if (state == WFT_STATE_SUCCESS) {
                    resp->get_message_body_nocopy(&body, &body_size);
                    // printf("Server Response: %.*s\n", (int)body_size, (char *)body);

                    // 统计请求成功次数
                    ++success_count;
                } else {
                    const char *str = WFGlobal::get_error_string(state, error);
                    // fprintf(stderr, "Error: %s\n", str);
                }
            });

        task->get_req()->set_message_body(buf, MESSAGE_SIZE);
        task->get_resp()->set_size_limit(MESSAGE_SIZE);

        return task;
    };

	ParallelWork *pwork = Workflow::create_parallel_work(nullptr);

    for (int i = 0; i < send_threads; i++) {
        WFRepeaterTask *repeater;
        repeater = WFTaskFactory::create_repeater_task(std::move(create), nullptr);

        SeriesWork* series = Workflow::create_series_work(repeater, nullptr);

        pwork->add_series(series);
    }

    ////////////////////////////////////////////////////////////////////////////////

    auto start = std::chrono::high_resolution_clock::now();

    ////////////////////////////////////////////////////////////////////////////////

    Workflow::start_series_work(pwork, [&wait_group](const SeriesWork *) {
        wait_group.done();
    });

    wait_group.wait();

    ////////////////////////////////////////////////////////////////////////////////

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> elapsed = end - start;
    std::cout << "Message queue performance: " << elapsed.count() << " seconds for " << NUM_MESSAGES << " messages\n";

    return 0;
}
```
（4）server-uds.cc
```c++
#include <ctype.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/un.h>

#include "message.h"
#include "workflow/WFFacilities.h"
#include "workflow/WFServer.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/Workflow.h"

using WFTutorialTask = WFNetworkTask<protocol::TutorialRequest, protocol::TutorialResponse>;
using WFTutorialServer = WFServer<protocol::TutorialRequest, protocol::TutorialResponse>;

using namespace protocol;

constexpr size_t MESSAGE_SIZE = 10240;
constexpr size_t NUM_MESSAGES = 100000;

void process(WFTutorialTask *task) {
    TutorialRequest *req = task->get_req();
    TutorialResponse *resp = task->get_resp();
    void *body;
    size_t size;
    size_t i;

    req->get_message_body_nocopy(&body, &size);
    // for (i = 0; i < size; i++)
    //     ((char *)body)[i] = toupper(((char *)body)[i]);

    resp->set_message_body(body, size);
}

static WFFacilities::WaitGroup wait_group(1);

void sig_handler(int signo) {
    wait_group.done();
}

int main(int argc, char *argv[]) {
    struct sockaddr_un sun = {};

    if (argc != 4) {
        fprintf(stderr, "USAGE %s <path> <poller_thread_num> <handler_thread_num>\n", argv[0]);
        exit(1);
    }

    sun.sun_family = AF_UNIX;
    strncpy(sun.sun_path, argv[1], sizeof sun.sun_path - 1);

    WFGlobalSettings setting = GLOBAL_SETTINGS_DEFAULT;
    setting.poller_threads = atoi(argv[2]);
    setting.handler_threads = atoi(argv[3]);

    WORKFLOW_library_init(&setting);

    ////////////////////////////////////////////////////////////////////////////////

    signal(SIGINT, sig_handler);

    ////////////////////////////////////////////////////////////////////////////////

    struct WFServerParams params = SERVER_PARAMS_DEFAULT;
    params.request_size_limit = MESSAGE_SIZE;

    WFTutorialServer server(&params, process);

    if (server.start((struct sockaddr *)&sun, sizeof sun) == 0) {
        wait_group.wait();

        server.stop();
    } else {
        perror("server.start");
        exit(1);
    }

    return 0;
}
```

**Comment by Barenboim** [comment]
我觉得，如果都是单线程串行请求，workflow的代码应该是比你那个简单程序要慢点。

workflow在每收到一个消息，poller线程会把消息放入消息队列由handler线程处理，这个比你的程序多一次线程切换，我觉得这可能是性能差距的主要原因。这一次线程切换在真正的业务里是必要的。

workflow里还有很多连接管理的逻辑，有完整的消息解析，你这个测试代码过于简单，而且也没有并发，所以比workflow框架快好像也很正常。你可以再测试一下workflow在并发情况下的极限qps。

**Comment by Barenboim** [comment]
我把你的程序编译了一下，和你使用同样参数是，时间也是8.2秒。
但client的启动参数改为：
$ ./client-uds ./tmp 120 4 4
完成时间加速到0.555秒。可见并发之后对性能的提升。

**Comment by Barenboim** [comment]
我把你的程序编译了一下，和你使用同样参数是，时间也是8.2秒。
但client的启动参数改为：
$ ./client-uds ./tmp 120 4 4
完成时间加速到0.555秒。可见并发之后对性能的提升。

**Comment by Barenboim** [comment]
~~~sh
$ ./client-uds ./tmp 1 4 4
Message queue performance: 8.26424 seconds for 100000 messages

$ ./client-uds ./tmp 2 4 4
Message queue performance: 4.38358 seconds for 100000 messages

$ ./client-uds ./tmp 4 4 4
Message queue performance: 2.44145 seconds for 100000 messages

$ ./client-uds ./tmp 8 4 4
Message queue performance: 1.36311 seconds for 100000 messages

$ ./client-uds ./tmp 16 4 4
Message queue performance: 0.968524 seconds for 100000 messages

$ ./client-uds ./tmp 32 4 4
Message queue performance: 0.725375 seconds for 100000 messages

$ ./client-uds ./tmp 64 4 4
Message queue performance: 0.587522 seconds for 100000 messages

$ ./client-uds ./tmp 128 4 4    
Message queue performance: 0.547978 seconds for 100000 messages
~~~
这么看我们的并发加速比非常好啊。

**Comment by Barenboim** [comment]
同时去掉server和client的线程切换部分，在poller的回调里直接处理结果，一个并发的情况下：
~~~sh
./client-uds ./tmp 1 4 4
Message queue performance: 3.90728 seconds for 100000 messages

$ ./client-uds ./tmp 64 4 4
Message queue performance: 0.421837 seconds for 100000 messages
~~~
对比一个并发的情况，超过50%的时间销耗是在线程切换。根据perf的统计，剩余约20%的时候都消耗在用户态的内存复制。你的简单同步程序在内存复制上会少很多。
