### ISSUE TITLE
请教关于任务流和任务调度的两个问题

### ISSUE THREAD

**Issue by standbywzp** [sogou/workflow#1605]
向大佬请教两个问题。
1、关于任务流：我有一个处理流程A->B->C，从读任务中获取数据来进行数据处理。A、B、C任务之间是有数据依赖关系的，所以我放到一个series中串行执行。我想实现这个处理流程的循环运行。但由于每一个task执行完就被回收了，所以我现在只能在A的callback里面创建B，再在B的callback里面创建C，C的callback里面创建A，如此循环。我希望A、B、C能持久存在，被反复调用。这个有什么好的解决方案吗？
2、关于任务调度：在任务调度的时候，假设我有A、B、C三类任务，按不同的名字放在三个子队列中。A、B执行的很快，C执行的很慢。如果调度器是公平的调起每一类任务，是否会存在一种情况，耗时长的C任务占用了所有的线程，导致A和B无法及时执行。这个问题应该如何解决？

**Comment by Barenboim** [comment]
第一个问题，目前任务都是一次性的。不过，在你这个业务里，C在callback里创建A好像不是很符合逻辑，可以把A，B，C封装成一个module，在module task的callback里创建下一个module会合理一些。可以看一下模块任务的文档。我们的任务不能复用，但也可以通过dynamic task或repeater task来自动创建任务。

第二个问题，不会。公平性正是解决你说的这个问题。调度的结果是，如果三类（三个队列）任务数量相同而且足够多，总是接近于同时执行完成。与**每个**任务运行时长没有关系，也和启动顺序没有关系。

**Comment by standbywzp** [comment]
感谢解答。
关于第二个问题还有些疑惑。假如A、B、C三个任务分别是接收数据、处理数据和写文件。读写耗时很长，三个任务之间又有依赖关系，我希望提高效率让它们并发执行。那这种情况下进行任务调度，如果只是放到对应的子队列中的话，如何保证他们调度顺序的正确呢？所以我会担心读写任务占据大量线程导致处理任务无法正常运行的情况。

**Comment by Barenboim** [comment]
你第二个问题里说的三个任务，就是第一个问题里的A,B,C吗？


一般来讲，我的的计算任务只处理纯计算的，不要在计算任务里做IO操作，除非你创建独立的Executor。如果只是模拟的话，你可以直接搞点sleep操作之类的。


你任务之间还有依赖关系的话，你就正常编排就可以了，不会出现调度不合理的情况。你可以用sleep来模拟长的计算任务试试。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 下午4:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 请教关于任务流和任务调度的两个问题 (Issue #1605)




 
感谢解答。
 关于第二个问题还有些疑惑。假如A、B、C三个任务分别是接收数据、处理数据和写文件。读写耗时很长，三个任务之间又有依赖关系，我希望提高效率让它们并发执行。那这种情况下进行任务调度，如果只是放到对应的子队列中的话，如何保证他们调度顺序的正确呢？所以我会担心读写任务占据大量线程导致处理任务无法正常运行的情况。

**Comment by Barenboim** [comment]
我们只有计算任务存在队列名这个东西，网络任务和文件IO任务没有队列名。

**Comment by standbywzp** [comment]
不好意思，没有表达清楚。第二个问题里的三个任务不是第一个问题里面的A，B，C。也就是说所有任务直接放进去，不需要考虑任何优先级，都交给workflow调度就可以了对吗。
我现在是用WFThreadTask自定义的IO任务，是不推荐这样做吗？

**Comment by standbywzp** [comment]
我使用的是Windows分支，好像是不支持WFFileIOTask的，文件的异步读写还有其他解决方案吗？

**Comment by Barenboim** [comment]
> 不好意思，没有表达清楚。第二个问题里的三个任务不是第一个问题里面的A，B，C。也就是说所有任务直接放进去，不需要考虑任何优先级，都交给workflow调度就可以了对吗。 我现在是用WFThreadTask自定义的IO任务，是不推荐这样做吗？

自定义的IO任务，不是文件IO，也不是网络吗？是什么样的IO任务呢。最好不要用我们默认的计算线程是来等待IO。可以通过自定义的Executor和ExecQueue来产生thread task。看一下这个issue：https://github.com/sogou/workflow/issues/1511

Windows我们最近没有怎么维护。尽量用Linux版……

**Comment by standbywzp** [comment]
没有没有，我现在就是用WFThreadTask来做文件IO。因为我看 matrix_multiply那个示例里面用WFThreadTask来自定义计算任务，所以是否可以用来做文件IO呢？

**Comment by Barenboim** [comment]
可以肯定可以，但占用了一个计算线程来等待IO，影响计算任务的调度。可以参考issue: #1511 的方法，自己定义一个线程池来使用。

**Comment by standbywzp** [comment]
自定义Executor和ExecQueue来产生thread task，这个线程池就只做文件IO吗？

**Comment by Barenboim** [comment]
> 自定义Executor和ExecQueue来产生thread task，这个线程池就只做文件IO吗？

嗯嗯，避免和计算抢线程。不过，需要用到文件IO强烈建议使用Linux版本。

**Comment by standbywzp** [comment]
明白了，非常感谢大佬耐心解答

**Comment by standbywzp** [comment]
我按您说的用sleep模拟了一下不同运行时长的任务。又产生了一点问题。
我创建了3个WFThreadTask，A任务sleep 1秒，B任务sleep 2秒，C任务sleep 3秒。三种任务的queue不同。
当我把100个A任务push_back到series_a中，100个B任务push_back到series_b中，100个C任务push_back到series_c中，然后将series_a、series_b、series_c，add_series到一个并行任务parallel_work中，然后start这个parallel_work。运行结果是100个A任务和100个B任务很快做完，最后只剩C任务在运行。
当我把100个A任务、100个B任务、100个C任务，分别create 300个series，将这300个series添加到parallel_work里面，再start的时候，运行结果就是基本上同时结束三类任务。
可能是我对调度器的理解还有问题。在我的理解中，子队列就是按照queue的名字区分的。我在创建三类任务的时候，已经区分了三种queue name。无论我是将100个任务添加到1个series中还是create 100个series，最终相同名字的task总会到同一个调度器里面参与调度。但为什么两种方式会有这么大的差别，那明显第二种方式是符合workflow调度原则的，我想不明白中间问题出在哪里，向大佬请教。

**Comment by standbywzp** [comment]
如果要实现公平的调度，是否就要给每个task新创建一个series。同时创建这么多series是否会对资源和运行效率产生影响？

**Comment by Barenboim** [comment]
> 如果要实现公平的调度，是否就要给每个task新创建一个series。同时创建这么多series是否会对资源和运行效率产生影响？

你实验一下吧。
是否是同一个series只取决于任务之间有没有顺序关系，和公平与否没有关系。

**Comment by Barenboim** [comment]
> 我按您说的用sleep模拟了一下不同运行时长的任务。又产生了一点问题。 我创建了3个WFThreadTask，A任务sleep 1秒，B任务sleep 2秒，C任务sleep 3秒。三种任务的queue不同。 当我把100个A任务push_back到series_a中，100个B任务push_back到series_b中，100个C任务push_back到series_c中，然后将series_a、series_b、series_c，add_series到一个并行任务parallel_work中，然后start这个parallel_work。运行结果是100个A任务和100个B任务很快做完，最后只剩C任务在运行。 当我把100个A任务、100个B任务、100个C任务，分别create 300个series，将这300个series添加到parallel_work里面，再start的时候，运行结果就是基本上同时结束三类任务。 可能是我对调度器的理解还有问题。在我的理解中，子队列就是按照queue的名字区分的。我在创建三类任务的时候，已经区分了三种queue name。无论我是将100个任务添加到1个series中还是create 100个series，最终相同名字的task总会到同一个调度器里面参与调度。但为什么两种方式会有这么大的差别，那明显第二种方式是符合workflow调度原则的，我想不明白中间问题出在哪里，向大佬请教。

你第一个业务里，任务直接有依赖关系。series_c无论如何都需要运行300秒。只要有CPU可以用，肯定就是用来处理A和B了。

总之，用户通过series和parallel编排自己的任务就好，计算调度交给底层。

大多数业务都是IO任务和计算任务交替。只有给**每一种**计算任务起一个独立名字就是最佳的。

**Comment by standbywzp** [comment]
好的好的，感谢！！！
