### ISSUE TITLE
Json 解析问题

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1614]
问题描述:
使用wf 的 json 库解析下列json 串,出现序列化后json 内容与原字符串内容不符的情况.代码如下:
std::string response = msg->getMsg();
response = R"([1, 220120000000000866, 22011000064398, 0, "BTCUSD", 1724230490.6028781, 0.0, 0.0, 0, "0.01", "59424.9", "59414.8", "0.1500", "0", "-0.10", "0e-8", "0e-8", "fix", "APP_DEMO_RAW17", "-1", "175.58", 0, 1, "0"])";
json json_data = json::parse(response);
Json json_data1 = Json::parse(response.c_str());
LOG_INFO("[push server] 0 handle order push data = {} ",json_data.dump().c_str());
LOG_INFO("[push server] 3 handle order push data = {} ",json_data1.dump().c_str());
日志输出的内容如下:
[2024-08-21 17:50:21.605] [console] [info] [push server] 0 handle order push data = [1,220120000000000866,22011000064398,0,"BTCUSD",1724230490.602878,0.0,0.0,0,"0.01","59424.9","59414.8","0.1500","0","-0.10","0e-8","0e-8","fix","APP_DEMO_RAW17","-1","175.58",0,1,"0"]
[2024-08-21 17:50:21.605] [console] [info] [push server] 3 handle order push data = [1,220120000000000864,22011000064398,0,"BTCUSD",1.72423e+09,0,0,0,"0.01","59424.9","59414.8","0.1500","0","-0.10","0e-8","0e-8","fix","APP_DEMO_RAW17","-1","175.58",0,1,"0"]
其中 220120000000000866 序列化后变成了220120000000000864 ,稳定复现问题, 代码跟踪后发现Json::parse 调用的是json_value_parse 函数,请帮忙排查下原因,谢谢!

**Comment by Barenboim** [comment]
你好。这个整数（220120000000000866 ）超过了double类型最大无损表示的整数范围了，任何用double来保存数字的JSON解析器都无法精确记录这个数字。例如cJSON，它的JSON结构是这么定义的：
~~~c
typedef struct cJSON
{
    /* next/prev allow you to walk array/object chains. Alternatively, use GetArraySize/GetArrayItem/GetObjectItem */
    struct cJSON *next;
    struct cJSON *prev;
    /* An array or object item will have a child pointer pointing to a chain of the items in the array/object. */
    struct cJSON *child;

    /* The type of the item, as above. */
    int type;

    /* The item's string, if type==cJSON_String  and type == cJSON_Raw */
    char *valuestring;
    /* writing to valueint is DEPRECATED, use cJSON_SetNumberValue instead */
    int valueint;
    /* The item's number, if type==cJSON_Number */
    double valuedouble;

    /* The item's name string, if this item is the child of, or is in the list of subitems of an object. */
    char *string;
} cJSON;
~~~
所以，cJSON也无法精确记录这个数。实际上，你用strtod("220120000000000866", NULL)得到的结果也是220120000000000864.000000。
超过17个有效位的数字，还是建议用字符串来表示，或者使用支持long long型或long double型的JSON解析器。

**Comment by Barenboim** [comment]
wfrest也有nlohmann JSON的支持，你用那个也试一下。

**Comment by 18328594608** [comment]
使用nlohmann 目前来看没有这个问题.他是支持double long 类型的.那我先替换一下好了.感谢解答!

**Comment by Barenboim** [comment]
但就算long double也有上限，超过了同样有精度损失。


另外，long double的长度并无标准，x86-64或arm64下为80bits，但在一些64位平台上和全部的32位平台，它依然为64bits，这个就很麻烦了，会产生不一致性。不过常见的64位平台，long double都是80bits，可精确记录任何long long型整数。











---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月22日(周四) 上午9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] Json 解析问题 (Issue #1614)




 
使用nlohmann 目前来看没有这个问题.他是支持double long 类型的.那我先替换一下好了.感谢解答!

**Comment by 18328594608** [comment]
目前我们的应用都是部署在arm64 的平台下 这个问题暂时不用担心. 不过json_value_parse 里面是否也可以考虑使用ong double 作为替代 double 的方法, 这样针对这个场景也能进行对应的解决.

**Comment by Barenboim** [comment]
> 目前我们的应用都是部署在arm64 的平台下 这个问题暂时不用担心. 不过json_value_parse 里面是否也可以考虑使用ong double 作为替代 double 的方法, 这样针对这个场景也能进行对应的解决.

想过，主要问题在于不一致性，以及对解析速度的影响，而解决的只是一小部分场景。用long long来表示整数可能更加靠谱一下，long long在任何平台长度都是一致的。

**Comment by 18328594608** [comment]
> > 目前我们的应用都是部署在arm64 的平台下 这个问题暂时不用担心. 不过json_value_parse 里面是否也可以考虑使用ong double 作为替代 double 的方法, 这样针对这个场景也能进行对应的解决.
> 
> 想过，主要问题在于不一致性，以及对解析速度的影响，而解决的只是一小部分场景。用long long来表示整数可能更加靠谱一下，long long在任何平台长度都是一致的。
使用 long long 来表示整数确实是一个好主意, 这样不会带来兼容性问题, 这个带来的解析速度影响相较于long double 会更高一些. 这个或许可以尝试一下.

**Comment by Jamishon** [comment]
有json解析的例子吗？做过java和kotlin，再来做C++的json解析，真很累啊

**Comment by Barenboim** [comment]
> 有json解析的例子吗？做过java和kotlin，再来做C++的json解析，真很累啊

你好，你是直接使用workflow是吧？workflow的JSON模块是C语言的，文档和示例在这里：
https://github.com/barenboim/json-parser
