### ISSUE TITLE
rbtree 相关的rb_*符号定义可能与其它库冲突

### ISSUE THREAD

**Issue by oakfire** [sogou/workflow#1618]
这个问题有点隐蔽，导致有点难查，不幸的是我就碰到了。目前是手动修改添加了额外前缀来规避这个问题，毕竟冲突的那个库我没源码。

 rb_* 这样的符号可能有点烂大街，建议考虑优化下，不要导出rbtree 相关 rb_*  的符号定义， 或者包装改名，来规避可能的符号冲突。

此外还有  dns_,  mysql_ , json_ 等等前缀的导出符号，也需要斟酌考虑下这种问题。

**Comment by Barenboim** [comment]
这个没有办法啊。我觉得可能另外一个库也用了Linux那套rbtree？rbtree相关的符号应该只在我们内部使用到，这个有什么办法不导出吗。

**Comment by oakfire** [comment]
> 这个没有办法啊。我觉得可能另外一个库也用了Linux那套rbtree？rbtree相关的符号应该只在我们内部使用到，这个有什么办法不导出吗。

不导出的话，比如 gcc 可以加  `__attribute__((visibility("hidden")))  `

**Comment by Barenboim** [comment]
我试了半天好像也不有什么好方法，哪怕都打包成动态库，调用时也会查找到其它动态库里的符号。

原代码里直接不导出也不行，有些同事可能会直接使用rbtree。这个库本来也很通用，所以才会和你引用的其它库发生冲突。

其它哪怕是有namespace的cpp代码，如果两个库里引用了同一个第三方库，版本不一样，也会有相同的问题。

**Comment by oakfire** [comment]
> 我试了半天好像也没有什么好方法，哪怕都打包成动态库，调用时也会查找到其它动态库里的符号。
> 
> 源代码里直接不导出也不行，有些同事可能会直接使用rbtree。这个库本来也很通用，所以才会和你引用的其它库发生冲突。
> 
> 其它哪怕是有namespace的cpp代码，如果两个库里引用了同一个第三方库，版本不一样，也会有相同的问题。

得导出的话确实避免不了，得使用者自己规避了。

**Comment by wxjql** [comment]
如果 rbtree 封装成静态库的话， 其他引用这个 rbtree 的模块可以使用 GCC 的 -Wl,-exclude-libs,libxxx  ，
