### ISSUE TITLE
msgqueue(消息队列)和任务队列(list封装的)大概的功能是什么那？二者大概是如何配合使用的？

### ISSUE THREAD

**Issue by zhouchunliang** [sogou/workflow#162]
msgqueue(消息队列)和entry对应的任务队列(list封装的)大概的功能是什么那？二者大概是如何配合使用的？

**Comment by zhouchunliang** [comment]
msgqueue是网络通信使用的哈，entry就是网络通信的上下文～这里的上下文，是给网络线程和调度线程用的：
网络线程从socket切一份数据下来，扔给msgqueue；
调度线程从msgqueue拿一份数据下来（包括它的上下文）就可以继续处理了，最后执行到用户的callback；

**Comment by zhouchunliang** [comment]
网络框架和计算框架其中重要的的区别是：msgqueue是网络通信使用，epoll检测到对应的事件，连同上下文信息一起放入epoll res中，然后放到msgqueue中，线程池在从中取进行处理，最后调用回掉函数；而计算框架是将待需处理的任务/请求放置到任务队列(连同entry)，任务队列如有任务，初始化创建的线程池进行任务的处理，最后调用回掉函数；

**Comment by Barenboim** [comment]
问题及回答来源于QQ群。欢迎群里的小伙伴将有代表性的问题直接发到issue，这样可以帮到更多的用户。我们回答问题，贴代码也更加方便。

**Comment by chanchann** [comment]
msgqueue simple analysis : https://github.com/chanchann/workflow_annotation/blob/main/src_analysis/08_msgqueue.md
