### ISSUE TITLE
MySQL client 事务模式下内存问题

### ISSUE THREAD

**Issue by yilunh** [sogou/workflow#1621]
参考[教程](https://github.com/sogou/workflow/blob/master/docs/en/tutorial-12-mysql_cli.md)使用事务模式的MySQL client，每次发送新事务会新建一个唯一ID的WFMySQLConnection二级工厂和seriesWork，结束后发送disconnect并回收资源。目前上线后能够正常收发请求且commit或rollback都符合预期，但经过7*24小时监控发现内存使用每天增加，而之前使用非事务模式时从未遇到过该问题。请问是我的使用姿势有误吗？

**Comment by yilunh** [comment]
感谢回复，请问能否完善事务使用的文档，强调一下需要管理WFMySQLConnection对象的资源，由于姿势错误造成线上内存泄漏挺严重的。

**Comment by Barenboim** [comment]
> 感谢回复，请问能否完善事务使用的文档，强调一下需要管理WFMySQLConnection对象的资源，由于姿势错误造成线上内存泄漏挺严重的。

好的好的。我记得有大概提了一下。感谢使用。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/master/docs/tutorial-12-mysql_cli.md

**Comment by yilunh** [comment]
感谢及时的更新。还想请问，如果复用时使用相同的ID但不同的URL初始化，是否会生成新的连接对象？对应的那一小块内存会被复用吗？

**Comment by Barenboim** [comment]
不会，除非两个URL都表示同一个地址，而且数据库名，字符集什么都完全一样。比如127.0.0.1和localhost，内部可能解析出来就是同一个东西，就找到同一个目标了。


除此之外，ID+url的二元组确定一个通信目标。


其实WFMySQLConnection就是帮助用户实现一个命名事务。你可以看一下实现，完全可以通过自己加一个事务名来解决。就是在URL的query部分加一个trasaction=，内部用于区分连接。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月12日(周四) 晚上8:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] MySQL client 事务模式下内存问题 (Issue #1621)




 
感谢及时的更新。还想请问，如果复用时使用相同的ID但不同的URL初始化，是否会生成新的连接对象？对应的那一小块内存会被复用吗？

**Comment by yilunh** [comment]
感谢大佬答疑，我再研究研究
