### ISSUE TITLE
workflow如何实现同步API，去调用异步方式的第三方服务API

### ISSUE THREAD

**Issue by TongxianYang** [sogou/workflow#1625]
workflow作为服务代理提供API，将接受到http请求去请求第三方服务的API，第三方的服务API是异步的，第三方服务器将资源结果也通过http请求方式post给workflow， 我的问题是如何把workflow对外提供的api实现为同步调用接口？

**Comment by Barenboim** [comment]
我觉得你的需求可能不是实现同步调用吧？

你是想收到POST请求之后，你再回复之前的http请求呢

**Comment by TongxianYang** [comment]
是的，收到第三方服务的post过来结果，再回复到之前用户调用过来的http请求，这种实现整个流程的同步，workflow有没有推荐的方案？ 

比如： app---->workflow---->第三方服务器---->远程终端设备,    设备把最终结果回复到最初的app请求中

**Comment by Barenboim** [comment]
这个简单哈。只有用一下我们的counter，全程异步实现。
收到http请求时，请求第三方API，并使用counter堵住server task的series：
~~~cpp
void process(WFHttpTask *server_task)
{
    WFCounterTask *counter= WFTaskFactory::create_counter_task(1, nullptr);
    series_of(server_task)->push_back(counter);
}
~~~
收到post请求，打开counter就可以了。如果不想传达指针，也可以使用命名counter，利用名字来打开。相关文档：
https://github.com/sogou/workflow/blob/master/docs/about-counter.md
另外，你也可以使用WFMailboxTask，这是一种带数据传递，目标只只能是1的counter，很符合你的场景。

**Comment by Barenboim** [comment]
Mailbox相关接口：
https://github.com/sogou/workflow/blob/4bc8e5681815fb7e058c4a6cf37d39efc69fdec8/src/factory/WFTaskFactory.h#L271

**Comment by Barenboim** [comment]
> 好的，谢谢
> 
> 用workflow中消息队列来等待返回结果，是否可行吖？

如果你说的是这个消息队列：https://github.com/sogou/workflow/blob/master/docs/about-resource-pool.md
可以的。本质上，都是需要产生一个task吧series阻塞住，收到POST请求的时候打开。全程异步。

如果你说的是kernel/msgqueue，那需要占用一个线程等待。这个不可以，容易把所有通讯线程阻塞住导致无法处理POST请求，死锁。同步等待的基础组件是WFFuture，通过动态增加减少通讯线程来解决通讯线程都在等的问题，不过也是一种同步的方式，不推荐。

**Comment by TongxianYang** [comment]
好的，谢谢

**Comment by TongxianYang** [comment]
还有个问题再请教一下，用WFMailboxTask等待异步消息时，怎么给它设置等待超时时间呢？

**Comment by Barenboim** [comment]
Selector可能对你这个场景还不太好。Selector要求每个candidate必须执行submit。但明显你的POST请求可能是永远收不到的。

**Comment by TongxianYang** [comment]
是的，终端设备离线了就永远收不到post消息

好的，那我就用workflow内置的定时器来做吧

**Comment by TongxianYang** [comment]
WFMailboxTask命名和WFTimerTask命名是否可以用同一个命名？ 

如下：
WFTaskFactory::send_by_name("app-rrpc", ptr);
WFTaskFactory::cancel_by_name("app-rrpc");

**Comment by Barenboim** [comment]
可以同名，不同类型的命名任务，名称空间是独立的。

不过我觉得timer没有什么必要命名，这玩意开销极小，而且程序退出的话也就直接中断了。放着就放着。当然你cancel也没什么问题。

**Comment by Barenboim** [comment]
> WFMailboxTask命名和WFTimerTask命名是否可以用同一个命名？
> 
> 如下： WFTaskFactory::send_by_name("app-rrpc", ptr); WFTaskFactory::cancel_by_name("app-rrpc");

对了，send_by_name这个操作没有返回值，不知道消息投递成功了没有……这个不知道对你是否有影响。

**Comment by Barenboim** [comment]
> ![1727171437982](https://private-user-images.githubusercontent.com/95041165/370232094-aed692e4-7c84-4702-9ef5-023e6566d7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzE4NDYsIm5iZiI6MTcyNzE3MTU0NiwicGF0aCI6Ii85NTA0MTE2NS8zNzAyMzIwOTQtYWVkNjkyZTQtN2M4NC00NzAyLTllZjUtMDIzZTY1NjZkN2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZWQ1NDdhNjhiNDY2Y2FjODY4NmQyMDcwOGE1YjBmMDAyMDQ3YTIyNTc0NzI0ZGFiNzA1ZWE4YTI2NDhhNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HM_D5DmBd7lv87Zq8QWADTRAz3NaKlmJAwNO9UWuJdw)
> 
> timer不用串行到http服务器任务中吧？

timer直接start就可以了。

**Comment by Barenboim** [comment]
从你这个代码看起来，send_by_name不加返回值的话，你可能用不了……

**Comment by TongxianYang** [comment]
收到post和timer超时，有一处send_by_name成功，就能退出阻塞就可以了

**Comment by Barenboim** [comment]
> 收到post和timer超时，有一处send_by_name成功，就能退出阻塞就可以了

问题是，如果超时了，POST请求到达之后，你send_by_name的资源如何回收呢？这时候并没有人收到这个消息。

**Comment by TongxianYang** [comment]
确实是哦，有没方案可判断指定的WFMailboxTask已经结束？

**Comment by Barenboim** [comment]
> 确实是哦，有没方案可判断指定的WFMailboxTask已经结束？

我改一下代码吧，今晚就可以搞定。send_by_name操作返回有多少个mailbox收到了消息就可以了。

**Comment by TongxianYang** [comment]
好的，谢谢

![1727172280486](https://github.com/user-attachments/assets/d0884f74-127a-4bfd-a1ed-06cef8d2427d)
创建任务时就分配好空间，然后用这个函数返回空间地址赋值进去， 这种方式也可以的吧？

**Comment by Barenboim** [comment]
> 好的，谢谢
> 
> ![1727172280486](https://private-user-images.githubusercontent.com/95041165/370237265-d0884f74-127a-4bfd-a1ed-06cef8d2427d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzI3ODcsIm5iZiI6MTcyNzE3MjQ4NywicGF0aCI6Ii85NTA0MTE2NS8zNzAyMzcyNjUtZDA4ODRmNzQtMTI3YS00YmZkLWExZWQtMDZjZWY4ZDI0MjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZjNjYWFlYmRiZWEwMWU3NWJhNzY0OTVmNTUzODRmNTZkOTBlMjJhNzc4NDdlNmU1OGU1NzI4Mzk4NjM5YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.erVRTq_zt-UEIR_cOwG4liYoqIheP_kpJk_BGp7l7Zo) 创建任务时就分配好空间，然后用这个函数返回空间地址赋值进去， 这种方式也可以的吧？

但这个空间总是需要回收的。我觉得send_by_name如果不知道投递结果，应该是没有办法实现得比较自然的。

**Comment by Barenboim** [comment]
另外，你这个代码好像有点旧。send操作后来改成virtual的了。

**Comment by TongxianYang** [comment]
> 另外，你这个代码好像有点旧。send操作后来改成virtual的了。

是的，代码用的库刚更新到最后发布的0.11.5版本了

**Comment by TongxianYang** [comment]
> 但这个空间总是需要回收的。我觉得send_by_name如果不知道投递结果，应该是没有办法实现得比较自然的。

好的，等你们更新后，我明天再拉取最新的

**Comment by Barenboim** [comment]
可以看一下这个PR：https://github.com/sogou/workflow/pulls

所有的XXX_by_name函数，都返回一个int代表操作所触发的任务个数。在你这个业务里，send_by_name返回1则代表消息被mailbox成功接收。返回0表示这个名字的mailbox已经被别的任务投递了，应该释放资源。

同样，cancel_by_name也会返回成功取消的定时器个数。

**Comment by TongxianYang** [comment]
好的，谢谢

**Comment by TongxianYang** [comment]
> 可以看一下这个PR：https://github.com/sogou/workflow/pulls
> 
> 所有的XXX_by_name函数，都返回一个int代表操作所触发的任务个数。在你这个业务里，send_by_name返回1则代表消息被mailbox成功接收。返回0表示这个名字的mailbox已经被别的任务投递了，应该释放资源。
> 
> 同样，cancel_by_name也会返回成功取消的定时器个数。

![1728627179153](https://github.com/user-attachments/assets/cd677b6c-4385-4698-aa5f-a90f04af2ac2)
请教下官方，用WFMailboxTask和WFTimerTask配合做的同步API，部署在一台服务器上时，API被调第一次正常应答，第二次调用时http连接进来就直接拒绝，workflow服务进程也死了。  而部署在另一台服务器上时，API被连续请求多次也没死。请问这是什么原因导致的？ workflow内部也没任何打印出来，很难排查出来哪里环境哪里导致？

**Comment by Barenboim** [comment]
多贴一点代码吧。包括timer超时和正常时的send操作。问题应该很好解决。

**Comment by TongxianYang** [comment]
![1728628921833](https://github.com/user-attachments/assets/597d5127-8b85-47ec-b253-52478f7d1ecf)
![1728629067691](https://github.com/user-attachments/assets/663ead43-bddb-4ea5-9d4b-15c2d8ea147a)
超时和正常回应处理代码片段？

**Comment by Barenboim** [comment]
等一下，你是说，workflow的服务器部署在两台机器上，其中一台正常，一台只处理了一个请求，就拒绝服务了是吧？

机器环境有什么不同吗。

**Comment by TongxianYang** [comment]
> 等一下，你是说，workflow的服务器部署在两台机器上，其中一台正常，一台只处理了一个请求，就拒绝服务了是吧？
> 
> 机器环境有什么不同吗。

是的，现在我试了三台机器，其余两台是正常的， 出问题那台是centos7.9,  另外两台是ubuntu20.04。都是阿里云服务器， 不同点就是资源使用情况不一样

**Comment by Barenboim** [comment]
另外，代码里有一个逻辑问题。mailbox任务应该先于timer运行时创建。否则，就存在可能性，timer callback里send是，mailbox还没有创建，导致超时失效。当然，在这个case里，timer超时10秒，这种情况理论上不会发生，但也是不严密。

**Comment by Barenboim** [comment]
> > 等一下，你是说，workflow的服务器部署在两台机器上，其中一台正常，一台只处理了一个请求，就拒绝服务了是吧？
> > 机器环境有什么不同吗。
> 
> 是的，现在我试了三台机器，其余两台是正常的， 出问题那台是centos7.9, 另外两台是ubuntu20.04。都是阿里云服务器， 不同点就是资源使用情况不一样

我感觉是环境问题。可能centos机器上，你之前安装过一个不同的workflow版本，导致头文件不一致。你看看怎么把环境清理干净。

**Comment by TongxianYang** [comment]
> 另外，代码里有一个逻辑问题。mailbox任务应该先于timer运行时创建。否则，就存在可能性，timer callback里send时，mailbox还没有创建，导致超时失效。当然，在这个case里，timer超时10秒，这种情况理论上不会发生，但也是不严密。

其他不用mailbox任务的API是正常的，现在几十台设备访问着

**Comment by Barenboim** [comment]
> > 另外，代码里有一个逻辑问题。mailbox任务应该先于timer运行时创建。否则，就存在可能性，timer callback里send时，mailbox还没有创建，导致超时失效。当然，在这个case里，timer超时10秒，这种情况理论上不会发生，但也是不严密。
> 
> 其他不用mailbox任务的API是正常的，现在几十台设备访问着

我这个说的是另一个问题，按理是不会发生的。你设备上运行过旧版代码，检查一下头文件不一致的可能性。mailbox任务应该没有什么bug的。

**Comment by TongxianYang** [comment]
> > > 另外，代码里有一个逻辑问题。mailbox任务应该先于timer运行时创建。否则，就存在可能性，timer callback里send时，mailbox还没有创建，导致超时失效。当然，在这个case里，timer超时10秒，这种情况理论上不会发生，但也是不严密。
> > 
> > 
> > 其他不用mailbox任务的API是正常的，现在几十台设备访问着
> 
> 我这个说的是另一个问题，按理是不会发生的。你设备上运行过旧版代码，检查一下头文件不一致的可能性。mailbox任务应该没有什么bug的。

其他两台也运行过旧版代码，会不会有可能资源受限导致的进程死掉

**Comment by TongxianYang** [comment]
![1728634435806](https://github.com/user-attachments/assets/ad799274-0949-4210-9dc8-78801cbb37ea)

**Comment by Barenboim** [comment]
> > > > 另外，代码里有一个逻辑问题。mailbox任务应该先于timer运行时创建。否则，就存在可能性，timer callback里send时，mailbox还没有创建，导致超时失效。当然，在这个case里，timer超时10秒，这种情况理论上不会发生，但也是不严密。
> > > 
> > > 
> > > 其他不用mailbox任务的API是正常的，现在几十台设备访问着
> > 
> > 
> > 我这个说的是另一个问题，按理是不会发生的。你设备上运行过旧版代码，检查一下头文件不一致的可能性。mailbox任务应该没有什么bug的。
> 
> 其他两台也运行过旧版代码，会不会有可能资源受限导致的进程死掉

不是资源受限问题，我们的资源需求非常小。你的内存够够的。

你这个现象非常符合头文件与lib不一致。安装过旧的库只是一个必要条件，不是充分条件。

另外，我说的bug改一下吧…… 把timer->start()移到create_mailbox_task()下面就行。

**Comment by TongxianYang** [comment]
> > > > > 另外，代码里有一个逻辑问题。mailbox任务应该先于timer运行时创建。否则，就存在可能性，timer callback里send时，mailbox还没有创建，导致超时失效。当然，在这个case里，timer超时10秒，这种情况理论上不会发生，但也是不严密。
> > > > 
> > > > 
> > > > 其他不用mailbox任务的API是正常的，现在几十台设备访问着
> > > 
> > > 
> > > 我这个说的是另一个问题，按理是不会发生的。你设备上运行过旧版代码，检查一下头文件不一致的可能性。mailbox任务应该没有什么bug的。
> > 
> > 
> > 其他两台也运行过旧版代码，会不会有可能资源受限导致的进程死掉
> 
> 不是资源受限问题，我们的资源需求非常小。你的内存够够的。
> 
> 你这个现象非常符合头文件与lib不一致。安装过旧的库只是一个必要条件，不是充分条件。
> 
> 另外，我说的bug改一下吧…… 把timer->start()移到create_mailbox_task()下面就行。

库文件和头文件我是同时更新的，编译好放到自己目录中链接的

逻辑BUG 我会改掉

**Comment by Barenboim** [comment]
问题就是担心你系统里安装过一个…… 你要不搞个完全干净的环境再试一下？

**Comment by TongxianYang** [comment]
![1728635136153](https://github.com/user-attachments/assets/4338f98f-f5eb-4be0-9e15-10bc71b77396)
库和头文件我直接放到工程中引用和链接的，不是安装到系统默认搜索路径下，不存在旧版头文件的问题

**Comment by TongxianYang** [comment]
> 问题就是担心你系统里安装过一个…… 你要不搞个完全干净的环境再试一下？

我再看看看吧

**Comment by Barenboim** [comment]
你看一下/usr/local/lib和/usr/local/include里有没有把。很多不一致的case，都是因为系统里安装了。

**Comment by TongxianYang** [comment]
> 你看一下/usr/local/lib和/usr/local/include里有没有把。很多不一致的case，都是因为系统里安装了。

![1728636236126](https://github.com/user-attachments/assets/10ac18ba-189c-4763-9241-d15c1c9c13ff)
查了没有，这台已经在使用了，已经在跑其他的服务，环境不能直接系统重装

**Comment by TongxianYang** [comment]
![1728637836560](https://github.com/user-attachments/assets/9dcf701d-2c90-45ee-91ea-7a0be0bf3fbc)
![1728638008779](https://github.com/user-attachments/assets/66608018-6516-4c78-af3a-106ebc61ec9e)
![1728638181301](https://github.com/user-attachments/assets/b9f5061a-5842-4b14-924d-3fd91bf533e8)
我用gdb打印出来的段错误栈信息，帮忙看看有没有发现，centos的编译器和ubuntu的编译器版本不一样的

**Comment by TongxianYang** [comment]
![1728638421104](https://github.com/user-attachments/assets/09bba5ea-090b-4cb0-9091-6a8c294b61a1)

**Comment by Barenboim** [comment]
我看一下这个gdb信息……

**Comment by Barenboim** [comment]
你的uuid_str是在哪里传给root["Payload"]["RequestId"]的？

**Comment by Barenboim** [comment]
知道了……你的代码写得不对。

**Comment by Barenboim** [comment]
最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。

**Comment by TongxianYang** [comment]
> 你的uuid_str是在哪里传给root["payload"]["RequestId"]的？

这个RequestId在远程设备的回复消息中，在发送给设备的消息附带进去的

![1728647257330](https://github.com/user-attachments/assets/93e03c96-8010-4d3a-9a93-f223f45cc16e)

**Comment by Barenboim** [comment]
> > 你的uuid_str是在哪里传给root["payload"]["RequestId"]的？
> 
> 这个RequestId在远程设备的回复消息中，在发送给设备的消息附带进去的
> 
> ![1728647257330](https://private-user-images.githubusercontent.com/95041165/375742726-93e03c96-8010-4d3a-9a93-f223f45cc16e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDc2ODUsIm5iZiI6MTcyODY0NzM4NSwicGF0aCI6Ii85NTA0MTE2NS8zNzU3NDI3MjYtOTNlMDNjOTYtODAxMC00ZDNhLTlhOTMtZjIyM2Y0NWNjMTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDExNDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNDVhNmRlNjhkMTQwOGFiNTRkOTBmYmEzYjM4ZWEyMjE3Yjc0ZmM0OTBhMWMxODMwMzAzMTQ4NjJmMzg3MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h_bak3G4XxCHsX27uE9BIyMtfNF29sGL7TW5l4dsXx4)

这个不重要了。

**Comment by TongxianYang** [comment]
> 最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。

好的，我代码只有在mailbox的callback使用message, 用完delete了，其它外部没有使用message啊

**Comment by TongxianYang** [comment]
我都已经开始把centos系统重装为ubuntu了

**Comment by TongxianYang** [comment]
那就很解释为什么在其他两台ubuntu上面不会导致段错误啊

**Comment by Barenboim** [comment]
> 那就很解释为什么在其他两台ubuntu上面不会导致段错误啊

讨论这个没有什么意义啊。访问已经释放的内存行为无法定义。碰巧没挂也不能说明什么。你理解问题所在没有？

**Comment by TongxianYang** [comment]
> > > 最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。
> > 
> > 
> > 好的，我代码只有在mailbox的callback使用message, 用完delete了，其它外部没有使用message啊
> 
> 但你写的是异步程序。无法保证mailbox callback里的delete，和你后面cancel_by_name()哪个先执行啊。那么你取message里的内容肯定就错了！
> 
> 和你什么系统没有关系，必然是错的。

好的，这个理解了

**Comment by TongxianYang** [comment]
> 最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。

理解你的意思，是不是取消定时器也会执行定时器回调函数？ 我一直理解成定时器回调函数只在定时器过期时触发，提前取消不会触发

**Comment by Barenboim** [comment]
噢噢，先cancel的话，定时器的callback里需要判断一下状态，再决定要不要send，否则定时器可能先于正常的send导致任务取消。


看起来还是先send再cancel好一点。把name保存一下。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月12日(周六) 上午9:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [sogou/workflow] workflow如何实现同步API，去调用异步方式的第三方服务API (Issue #1625)




  
最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。
  
理解你的意思，是不是取消定时器也会执行定时器回调函数？ 我一直理解成定时器回调函数只在定时器过期时触发，提前取消不会触发

**Comment by TongxianYang** [comment]
> 噢噢，先cancel的话，定时器的callback里需要判断一下状态，再决定要不要send，否则定时器可能先于正常的send导致任务取消。 看起来还是先send再cancel好一点。把name保存一下。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年10月12日(周六) 上午9:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [sogou/workflow] workflow如何实现同步API，去调用异步方式的第三方服务API (Issue #1625) 最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。 理解你的意思，是不是取消定时器也会执行定时器回调函数？ 我一直理解成定时器回调函数只在定时器过期时触发，提前取消不会触发 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的，那再请教下，定时器的callback里需要判断状态为什么时对应的定时器是cancel还是到期触发的呢？

**Comment by Barenboim** [comment]
正常到时的话，state为WFT_STATE_SUCCESS。取消的话，state为WFT_STATE_SYS_ERROR，error为ECANCELED。











---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月12日(周六) 中午12:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [sogou/workflow] workflow如何实现同步API，去调用异步方式的第三方服务API (Issue #1625)




  
噢噢，先cancel的话，定时器的callback里需要判断一下状态，再决定要不要send，否则定时器可能先于正常的send导致任务取消。 看起来还是先send再cancel好一点。把name保存一下。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年10月12日(周六) 上午9:51 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [sogou/workflow] workflow如何实现同步API，去调用异步方式的第三方服务API (Issue #1625) 最简单的你可以改成先cancel再send。或者做一个小优化，send返回1才cancel，但这时候不能再用message里的数据了。 理解你的意思，是不是取消定时器也会执行定时器回调函数？ 我一直理解成定时器回调函数只在定时器过期时触发，提前取消不会触发 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
好的，那再请教下，定时器的callback里需要判断状态为什么时对应的定时器是cancel还是到期触发的呢？

**Comment by TongxianYang** [comment]
> 正常到时的话，state为WFT_STATE_SUCCESS。取消的话，state为WFT_STATE_SYS_ERROR，error为ECANCELED。

好的，非常感谢支持

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1635

做了一个优化，确保cancel成功的个数（cancel_by_name()的返回值）与ECANCELED状态的timer个数严格一致。由于你不使用cancel_by_name()的返回值，这个改动对你无影响。但是，在这个新代码下，你的程序可以这么写：
Timer callback：
~~~cpp
void timer_callback(WFTimerTask *timer)
{
    if (timer->get_state() == WFT_STATE_SUCCESS)  // Timer 正常到期
    {
        MESSAGE *msg = new MESSAGE;
        WFTaskFactory::send_by_name(name, msg);   // 无需判断返回值了。
    }
}
~~~
Publish:
~~~cpp
{
    if (WFTaskFactory::cancel_by_name(name) != 0)  // 成功cancel timer
    {
        MESSAGE *msg = new MESSAGE;
        WFTaskFactory::send_by_name(name, msg);   // 无需判断返回值了。
    }
}
~~~

**Comment by TongxianYang** [comment]
> #1635
> 
> 做了一个优化，确保cancel成功的个数（cancel_by_name()的返回值）与ECANCELED状态的timer个数严格一致。由于你不使用cancel_by_name()的返回值，这个改动对你无影响。但是，在这个新代码下，你的程序可以这么写： Timer callback：
> 
> ```c++
> void timer_callback(WFTimerTask *timer)
> {
>     if (timer->get_state() == WFT_STATE_SUCCESS)  // Timer 正常到期
>     {
>         MESSAGE *msg = new MESSAGE;
>         WFTaskFactory::send_by_name(name, msg);   // 无需判断返回值了。
>     }
> }
> ```
> 
> Publish:
> 
> ```c++
> {
>     if (WFTaskFactory::cancel_by_name(name) != 0)  // 成功cancel timer
>     {
>         MESSAGE *msg = new MESSAGE;
>         WFTaskFactory::send_by_name(name, msg);   // 无需判断返回值了。
>     }
> }
> ```

好的，谢谢！

**Comment by Barenboim** [comment]
目前问题都解决了吗？麻烦反馈一下。

**Comment by TongxianYang** [comment]
> 目前问题都解决了吗？麻烦反馈一下。

目前没有出现问题

**Comment by TongxianYang** [comment]
再请教下，workflow的http服务器接口，如何做限制http的请求数，QPS？

**Comment by Barenboim** [comment]
> 再请教下，workflow的http服务器接口，如何做限制http的请求数，QPS？

重新发issue吧。

**Comment by xx-zhang** [comment]
@Barenboim 如果是 server_task 里面等待 task 也可以用 Pool？ 那么这样可以？
```cpp
WFResourcePool pool(1);

int f()
{
     // t1 任务直接用 server_task 代替
    // WFHttpTask *t1 = WFTaskFactory::create_http_task(..., [](void *){pool.post(nullptr);});
    WFHttpTask *t2 = WFTaskFactory::create_http_task(..., [](void *){pool.post(nullptr);});

    WFConditional *c1 = pool.get(server_task, &server_task->user_data);  // 用user_data来保存res是一种实用方法。
    WFConditional *c2 = pool.get(t2, &t2->user_data);

    c2->start();
    // wait for t2 finish here.
    ...
    // 这里的 server_task 让他走主任务里面的逻辑，不管它
    // c1->start();
    ...
}
```

**Comment by Barenboim** [comment]
> @Barenboim 如果是 server_task 里面等待 task 也可以用 Pool？ 那么这样可以？
> 
> ```c++
> WFResourcePool pool(1);
> 
> int f()
> {
>      // t1 任务直接用 server_task 代替
>     // WFHttpTask *t1 = WFTaskFactory::create_http_task(..., [](void *){pool.post(nullptr);});
>     WFHttpTask *t2 = WFTaskFactory::create_http_task(..., [](void *){pool.post(nullptr);});
> 
>     WFConditional *c1 = pool.get(server_task, &server_task->user_data);  // 用user_data来保存res是一种实用方法。
>     WFConditional *c2 = pool.get(t2, &t2->user_data);
> 
>     c2->start();
>     // wait for t2 finish here.
>     ...
>     // 这里的 server_task 让他走主任务里面的逻辑，不管它
>     // c1->start();
>     ...
> }
> ```

目前并不能。而且server task的执行行为是reply，这么做只限制了reply的并发度。

我想想能不能用到processor那里，这就能实现服务的并发度控制了。

**Comment by Barenboim** [comment]
> @Barenboim 如果是 server_task 里面等待 task 也可以用 Pool？ 那么这样可以？
> 
> ```c++
> WFResourcePool pool(1);
> 
> int f()
> {
>      // t1 任务直接用 server_task 代替
>     // WFHttpTask *t1 = WFTaskFactory::create_http_task(..., [](void *){pool.post(nullptr);});
>     WFHttpTask *t2 = WFTaskFactory::create_http_task(..., [](void *){pool.post(nullptr);});
> 
>     WFConditional *c1 = pool.get(server_task, &server_task->user_data);  // 用user_data来保存res是一种实用方法。
>     WFConditional *c2 = pool.get(t2, &t2->user_data);
> 
>     c2->start();
>     // wait for t2 finish here.
>     ...
>     // 这里的 server_task 让他走主任务里面的逻辑，不管它
>     // c1->start();
>     ...
> }
> ```

目前并不能。而且server task的执行行为是reply，这么做只限制了reply的并发度。

我想想能不能用到processor那里，这就能实现服务的并发度控制了。

**Comment by Barenboim** [comment]
> > 目前并不能。而且server task的执行行为是reply，这么做只限制了reply的并发度。
> > 我想想能不能用到processor那里，这就能实现服务的并发度控制了。
> 
> @Barenboim 我让前就是有一些结果是依赖直接响应的，不适合异步，就是需要等待结果后进行过滤处理响应， 如果在server_task层面的 process里面应该是可以的, 可以用 group wait 之类的，但是我想这解耦出来，所以您这个processor这个位置我不能动；

你说的这种调用第三方服务的同步操作，就是自己搞个线程池，然后用这个issue里提到的mailbox来解决啊。不需要要wait group。wait group会卡住我们的线程，用mailbox是完全异步的。
