### ISSUE TITLE
workflow有没有内置一些生成类似UUID系统唯一信息，不需要再依赖其它库

### ISSUE THREAD

**Issue by TongxianYang** [sogou/workflow#1626]
workflow有没有内置一些生成类似UUID系统唯一信息，不需要再依赖其它库

**Comment by Barenboim** [comment]
还是之前那个需求吗？我们的命名任务，确实是需要用户自行产生唯一ID。

但我们srpc里有个SnowFlake类是可以产生唯一ID的，你可以引用SRPC项目，或者把代码抄过去。

**Comment by TongxianYang** [comment]
是的，就是用来识别每一个请求对应的回复信息的

好的，谢谢！
