### ISSUE TITLE
workflow 自带mysql-cli问题反馈

### ISSUE THREAD

**Issue by luoqngAwd245** [sogou/workflow#163]
创建表，create table workflow(ID int, TASK_NAME varchar(32), TIMESTAMP timestamp);
update 数据报错如下：
![企业微信截图_de258244-25d4-4f86-af80-95dda8ffaca7](https://user-images.githubusercontent.com/40060887/100694490-2dd0c880-33ca-11eb-8047-4d7dca26b721.png)

**Comment by Barenboim** [comment]
已定位，马上修复。消息解析上的问题。非常感谢！

**Comment by Barenboim** [comment]
@luoqngAwd245 再试试！

**Comment by luoqngAwd245** [comment]
感谢回复，已解决！👌
