### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by robertsilen** [sogou/workflow#1632]
Is MariaDB supported? Any reason not to add a mention of it to the README?

**Comment by Barenboim** [comment]
Hi.
We fully support MySQL protocol, so I believe we support MariaDB, as well as TiDB or any other DB using MySQL protocol. Indeed I referred to MariaDB's documentation for many protocol details. I would like to add to README about this feature.

**Comment by robertsilen** [comment]
Thanks, I suggested now to add "MySQL protocol supports MariaDB, MySQL, TiDB and others" to README with this PR: https://github.com/sogou/workflow/pull/1633
