### ISSUE TITLE
想基于workflow实现一个http1.1的代理，请问以下需求是否可行？

### ISSUE THREAD

**Issue by ralgond** [sogou/workflow#1634]
需求具体如下：
1、支持连接池，包括客户端连接池和上游服务器连接池，连接池用epoll侦听信号来管理连接；
2、支持异步连接（上游服务器）；
3、支持多线程，在主线程读取完请求头后，请求头的分析和路由决策在线程A，后续操作在线程B完成（接受消息体，发送给上游服务器，并将上游服务器的响应发送给客户端）。

谢谢

**Comment by Barenboim** [comment]
问题是，http1.1 proxy不就是我们的tutorial-05-http_proxy吗？直接运行就可以了。
但不支持https代理。

**Comment by ralgond** [comment]
好的，我这就去看看，感谢您及时的回复。
