### ISSUE TITLE
编译链接问题

### ISSUE THREAD

**Issue by danta7** [sogou/workflow#1636]
为什么我在tutorial中make没有报错，在编译连接测试代码时候出现这个问题 **undefined reference to `EVP_PKEY_CTX_set_rsa_padding' collect2: error: ld returned 1 exit status**

**Comment by Barenboim** [comment]
你好。这个是一个已知问题。感觉是OpenSSL某个版本的bug，之前有用户报过。

如果你不需要用到mysql协议，可以先用make MYSQL=n 的方式不编译mysql，或者升级一下openssl试试。

**Comment by Barenboim** [comment]
之前的issue：https://github.com/sogou/workflow/issues/1427

**Comment by danta7** [comment]
好的 谢谢
