### ISSUE TITLE
get_parsed_body,  maximums  len

### ISSUE THREAD

**Issue by Jamishon** [sogou/workflow#1638]
int state = task->get_state();

        if (state == WFT_STATE_SUCCESS)
        {
            protocol::HttpResponse* response = task->get_resp();

            const void* body;
            size_t len;

            response->get_parsed_body(&body, &len);

            char* resp_body = new char[len + 1];
            memset(resp_body, 0, len + 1);
    }

I use the snap code above to receive the http Post response,  response data is to much,  but the maximum  len is always 380696, but  I use the tool Postman it return all data, how can I get the rest data or there is a bug on the response data buffer .

**Comment by Barenboim** [comment]
You mean the ``len`` is always 380696 while the real response body is much larger?

**Comment by Barenboim** [comment]
Can you show us all HTTP headers the server returned? It's very unlikely that workflow has such bug.

**Comment by Jamishon** [comment]
I use this way to get the all data: 
std::string response =protocol::HttpUtil::decode_chunked_body(resp);

Thank you !
