### ISSUE TITLE
将workflow添加到项目编译报错“无法解析的外部符号 __std_find_trivial_1”

### ISSUE THREAD

**Issue by Wq-dd** [sogou/workflow#1639]
### 报错信息如下：
- “workflow.lib(StringUtil.obj) : error LNK2019: 无法解析的外部符号 __std_find_trivial_1，函数 "char const * __cdecl __std_find_trivial<char const ,char>(char const *,char const *,char)" (??$__std_fi
nd_trivial@$$CBDD@@YAPEBDPEBD0D@Z) 中引用了该符号”

**Comment by Barenboim** [comment]
在搜索引擎上搜了一下，这个问题不少。解决方式有把vs2019升级到vs2022。

应该是一个比较常见的通用问题，可以试一下用搜索引擎解决。

**Comment by Wq-dd** [comment]
有趣的是，我另一台电脑同样是用的vs2019，但是可以编过，有点奇怪。

**Comment by Barenboim** [comment]
Windows下的问题，我应该还没有你懂…… 可能是环境相关的问题。
