### ISSUE TITLE
是否支持自定义的redis操作

### ISSUE THREAD

**Issue by ralgond** [sogou/workflow#1643]
您好：

我这边给redis写了个扩展，添加了一个新的指令，请问WF可否支持这种新的指令？谢谢！

**Comment by Barenboim** [comment]
我们的Redis 任务，根本没有定义命令（订阅除外）。你可以认为所有命令都是自定义的命令。

**Comment by Barenboim** [comment]
之前那个http proxy的示例你搞懂了么。

**Comment by ralgond** [comment]
> 之前那个http proxy的示例你搞懂了么。

还没有用WF的http proxy，因为它是先下载完响应体后再服务下游应用，这种方式和golang的net/http流式的io.Copy接口相比，在代理下载大文件时没有优势，我暂时先用golang实现了。
