### ISSUE TITLE
对于http server task里面进行上下文数据共享的user_data和 context咨询

### ISSUE THREAD

**Issue by xx-zhang** [sogou/workflow#1644]
rt
我看到我们的 server_task->user_data, 也看到  series_of(server_task)->set_context  
对于 server_task   可以用user_data 也可以用 context ， 那么这两者都有什么区别， 
1. 是否可以同时使用，对于 server_task推荐用user_data的情况下，又使用了context是否有隐患
2. 对于其他类型的task是不是就推荐用 context 这样在series任务间能共同访问到。 

两者我都用过，暂时没有发现什么问题； 但是不确定后面业务和任务复杂了还行不行，所以咨询下，怕涉及到里面的逻辑冲突；

**Comment by Barenboim** [comment]
两个当然都可以用。但series context是整个服务流程的上下文，series上的任务交互数据显然应该用series context。server task的user_data我觉得大多数是用来传给server task callback的吧。

**Comment by xx-zhang** [comment]
@Barenboim 好的，多谢答疑， 我原本以为两个实现有相似的地方，例如 context的涉及依赖了user_data，那我就没有问题了。作用域和设计 应该都有区别，整体想了下应该也没有冲突项。 

这个框架的体系还是挺厉害的，学习这个体系的过程，对于我自身一些程序设计的理念也有帮助。

**Comment by Barenboim** [comment]
> @Barenboim 好的，多谢答疑， 我原本以为两个实现有相似的地方，例如 context的涉及依赖了user_data，那我就没有问题了。作用域和设计 应该都有区别，整体想了下应该也没有冲突项。
> 
> 这个框架的体系还是挺厉害的，学习这个体系的过程，对于我自身一些程序设计的理念也有帮助。

没有依赖关系的，这两个域都是给用户使用的，在整个生命周期内可以随便用。多谢，也麻烦帮我们传播一下。
