### ISSUE TITLE
我看我们有取代负载均衡的建议，我也是想着轻量，可维护，可见

### ISSUE THREAD

**Issue by xx-zhang** [sogou/workflow#1645]
所以我很关心一个问题，我workflow http server是一系列的 http api接口， 我也想把我们默认的 html/css/js 也挂载在workflow的路由下，那么这个地方应该怎么配置，如果使用*.js, *.html的方法映射读取本地文件的方法我觉得太重了，是否有更简单的解决方案。

我当前是用的nginx    api  proxy_pass workflow-server:8000; 静态文件就是 /ui  alias 静态的目录。

**Comment by Barenboim** [comment]
这个不是wfrest做的吗？
https://github.com/wfrest/wfrest
可以直接Static一个目录的。

**Comment by xx-zhang** [comment]
好的，我关注一下；
