### ISSUE TITLE
workflow是否有内置函数获取数据库中用到的datetime类型的当前时间字段？

### ISSUE THREAD

**Issue by TongxianYang** [sogou/workflow#1648]
workflow是否有内置函数获取数据库中用到的datetime类型的当前时间字段？

**Comment by Barenboim** [comment]
你说的是mysql client的功能么？看不太懂你这个问题。

**Comment by TongxianYang** [comment]
> 你说的是mysql client的功能么？看不太懂你这个问题。

如下这种格式的时间字符串，若没有内置直接可以获取的话，我就自己去实现
![1730985034201](https://github.com/user-attachments/assets/d3e17484-5a0d-4113-aa7e-8e4881418774)
![1730984956806](https://github.com/user-attachments/assets/2fd1a042-ad4b-4e3a-94d3-02aca99b796c)

**Comment by Barenboim** [comment]
这个是client端产生的吗？你这整个SQL语言发过去，mysql那边会根据当前时间产生数据内容吗？

**Comment by Barenboim** [comment]
我们内容没有内置这个转换函数的。

**Comment by TongxianYang** [comment]
> 这个是client端产生的吗？你这整个SQL语言发过去，mysql那边会根据当前时间产生数据内容吗？

![1730985666799](https://github.com/user-attachments/assets/b94f4cc9-8d77-4cae-950c-1e5be207d6b2)
就想问，有没有函数直接获取这个当前时间  “2024-04-26 03:14:47”

**Comment by Barenboim** [comment]
没有。我是想问，能不能让mysql那边去产生😂







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月7日(周四) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow是否有内置函数获取数据库中用到的datetime类型的当前时间字段？ (Issue #1648)




  
这个是client端产生的吗？你这整个SQL语言发过去，mysql那边会根据当前时间产生数据内容吗？
  
1730985666799.png (view on web)
 就想问，有没有函数直接获取这个当前时间  “2024-04-26 03:14:47”

**Comment by TongxianYang** [comment]
> 没有。我是想问，能不能让mysql那边去产生😂
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年11月7日(周四) 晚上9:24 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sogou/workflow] workflow是否有内置函数获取数据库中用到的datetime类型的当前时间字段？ (Issue #1648) 这个是client端产生的吗？你这整个SQL语言发过去，mysql那边会根据当前时间产生数据内容吗？ 1730985666799.png (view on web) 就想问，有没有函数直接获取这个当前时间 “2024-04-26 03:14:47” — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，谢谢，自己实现

**Comment by Barenboim** [comment]
> 这个是client端产生的吗？你这整个SQL语句发过去，mysql那边会根据当前时间产生数据内容吗？

**Comment by Barenboim** [comment]
嗯嗯，这个issue我先关了。

**Comment by TongxianYang** [comment]
> 嗯嗯，这个issue我先关了。

好的
