### ISSUE TITLE
数据库 text 类型字段读取异常

### ISSUE THREAD

**Issue by 18328594608** [sogou/workflow#1650]
使用自带的mysql client 读取数据库时, 有一列的类型为 text 类型. 执行解析代码时, 该列无法正常的读取出来数据, 对于text列.读取时会判断为is_ulonglong 类型.

**Comment by holmes1412** [comment]
你好，TEXT应该是与BLOB同一种类型，参考：https://dev.mysql.com/doc/refman/8.0/en/blob.html

workflow里用的是传输时的基本类型buffer_type，比如MYSQL_TYPE_BLOB，会对应到server内存储的多种，这个可以参考下面的文档（以这个文档的说法列类型为TEXT的话你用workflow的MYSQL_TYPE_STRIGN应该也可以）：https://dev.mysql.com/doc/c-api/8.0/en/c-api-prepared-statement-type-codes.html

麻烦先用BLOB试试~

**Comment by holmes1412** [comment]
客气客气。看了下用is_ulonglong()检查，也是false的，可以先查看type再按对应的类型去解析就比较好。

如果是因为workflow版本比较旧导致有问题的话，可以升级一下哈~
