### ISSUE TITLE
请求文件名带空格返回结果不正确

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#1651]
如果url为/public/unzip/2f282e3bda484935904735a97154aaef/res 3.json，其中文件名称有空格，返回值不正确

**Comment by Barenboim** [comment]
URL里本来也不能有空格啊，需要调用转义成%20吧？你可以用我们的StringUtil::url_encode进行转义。收到的URL也要decode。

**Comment by HzjFirst** [comment]
但是使用StringUtil::url_encode这个转出来的空格好像是+号，不是%20

**Comment by Barenboim** [comment]
最好不要贴图，贴代码，方便讨论。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月7日(周四) 晚上8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 请求文件名带空格反回结果不正确 (Issue #1651)




 
image.png (view on web)

**Comment by Barenboim** [comment]
加号好像是对的吧？我查一下这块应该是怎么处理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月7日(周四) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 请求文件名带空格反回结果不正确 (Issue #1651)




 
但是使用StringUtil::url_encode这个转出来的空格好像是+号，不是%20

**Comment by HzjFirst** [comment]
我贴的是workflow的StringUtil::url_encode在处理空格时的源码

**Comment by Barenboim** [comment]
那也贴代码吧，要不然手机上看不清。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月7日(周四) 晚上8:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 请求文件名带空格反回结果不正确 (Issue #1651)




 
我贴的是workflow的StringUtil::url_encode在处理空格时的源码

**Comment by Barenboim** [comment]
> 好的，好的，明白了，以后贴代码，不好意思，我还以为大佬用的电脑呢

我不是着急回复你吗。这个问题我们看一下。之后报问题也尽量不要发图，很不方便。

**Comment by Barenboim** [comment]
可以看看这个文档。我感觉我们处理上没有什么问题。encode和decode也是可逆的。
https://juejin.cn/post/7018447255774429214

**Comment by HzjFirst** [comment]
但是我用了workflow的StringUtil::url_encode请求还是返回错误的结果

**Comment by holmes1412** [comment]
你好，确认了下用+和%20都是可以的。能不能确认下对方server也有对应的decode的处理逻辑呢？你可以用workflow中的tutorial来做个实验，encode -> 发送 -> decode，是可以正确处理的~

**Comment by HzjFirst** [comment]
好的，谢谢了，我再测试一下
