### ISSUE TITLE
workflow-0.10.2 偶现  core

### ISSUE THREAD

**Issue by atoms-long** [sogou/workflow#1654]
抓到堆栈信息
`Thread 1 (Thread 0x7ff5c1bd4640 (LWP 135)):
#0  http_header_cursor_next (name=0x7ff5c1bae080, name_len=0x7ff5c1bae088, value=0x7ff5c1bae090, value_len=0x7ff5c1bae098, cursor=0x7ff5c1bae070) at /tmp/workflow-0.10.2/src/protocol/http_parser.c:801
#1  0x000000000065f4d3 in protocol::HttpMessage::encode (this=0x7ff56ea2c228, vectors=0x7ff5c1bae0e0, max=8192) at /tmp/workflow-0.10.2/src/protocol/HttpMessage.cc:163
#2  0x000000000065672a in Communicator::send_message (this=0xc54c88 <__CommManager::get_instance()::kInstance+8>, entry=0x7ff5719fed80) at /tmp/workflow-0.10.2/src/kernel/Communicator.cc:581
#3  0x0000000000657bf1 in Communicator::request_idle_conn (this=this@entry=0xc54c88 <__CommManager::get_instance()::kInstance+8>, session=session@entry=0x7ff56ea2c1a0, target=target@entry=0x7ff573403118) at /tmp/workflow-0.10.2/src/kernel/Communicator.cc:1536
#4  0x0000000000657caf in Communicator::request (this=this@entry=0xc54c88 <__CommManager::get_instance()::kInstance+8>, session=session@entry=0x7ff56ea2c1a0, target=0x7ff573403118) at /tmp/workflow-0.10.2/src/kernel/Communicator.cc:1570
#5  0x000000000066a765 in CommScheduler::request (target=0x7ff56ea2c1f0, wait_timeout=<optimized out>, object=<optimized out>, session=0x7ff56ea2c1a0, this=0xc54c80 `

想请问一下之前有发现相关问题？

**Comment by atoms-long** [comment]
好的，我这边升级试一下

**Comment by Barenboim** [comment]
你用的这个版本，encode时占用的stack比较大，可能达到128KB，我怀疑是你用的场合堆栈有限制。

最新版本的代码，这个stack占用已经减少到32KB了。

**Comment by atoms-long** [comment]
环境是标准的x86 服务器，容器化，栈空间8m,  刚把wf 升级了，我们再观察看一下。感谢！

**Comment by atoms-long** [comment]
升级新版本已经解决。
