### ISSUE TITLE
关于异步写操作的实现以及poller的几个操作

### ISSUE THREAD

**Issue by zhouchunliang** [sogou/workflow#166]
咨询一下，在wget wget_to_redis http_echo_server等tutorial测试中发现，向对等方发送消息均是通过Communicator::send_message_sync中的writev(entry->sockfd, vectors, cnt <= IOV_MAX ? cnt : IOV_MAX)来实现，那epoll.c中的__poller_handle_write的功能是？向对方发送消息时为何不用这个epoll.c中__poller_handle_write？__poller_handle_event和__poller_handle_notify具体的应用场景是什么那？（可以基于具体的场景或者业务谈一下设计时的考虑）
![image](https://user-images.githubusercontent.com/18730685/100847010-27ba1500-34ba-11eb-86a2-07a48e5849d0.png)
![image](https://user-images.githubusercontent.com/18730685/100847064-3e606c00-34ba-11eb-938e-3ff6f6cfead9.png)

**Comment by Barenboim** [comment]
消息一次发得出去，就不走异步写了啊。这样子快。你试个大一点的消息，就会进poller了。

**Comment by Barenboim** [comment]
notify那个你忽略吧，只有mac下的异步文件IO才使用到的。

**Comment by zhouchunliang** [comment]
多谢
