### ISSUE TITLE
【request help】timerTask + gotask联合进行异步处理，但是性能占用非常大，是哪个地方可以优化？

### ISSUE THREAD

**Issue by xx-zhang** [sogou/workflow#1672]
我写了一个日志发送工具， 就是接受http日志，如果超时2s进行聚合发送，或者到达500条进行聚合发送； 于是我启动了一个 gotask和 timerTask, 
```cpp

// https://github.com/xx-zhang/http_log_server/blob/master/src/tools/log_collector.cpp
#include <csignal>
// #include <unistd.h>
#include <cstddef>
#include <cstring>
#include <netdb.h>
#include <openssl/lhash.h>
#include <string>

#include "nlohmann/json.hpp"
#include "gflags/gflags.h"

#include <workflow/WFTaskFactory.h>
#include <workflow/Workflow.h>
#include "workflow/WFHttpServer.h"
#include "workflow/WFFacilities.h"

// #include "workflow/HttpMessage.h"
#include "spdlog/spdlog.h"

#include "utils/coraza_log_helper.h"

// cmd: ./d.elf -log_server http://127.0.0.1:5080 
// g++ -lworkflow -lpthread -lgflags -lssl -lcrypto ./log_collector.cpp -o d.elf -I ../ -I ../../contrib/include/ -lyaml-cpp 
DEFINE_int32(port, 8811, "the server port.");
DEFINE_int32(max_per_send, 500, "the max number of logs for per send.");
DEFINE_string(log_type, "openobserve", "log to dest server default is openobserve");
DEFINE_string(log_server, "http://127.0.0.1:9080/openobserve", "the db file path, like /opt/db/");
DEFINE_string(log_auth, "Basic cm9vdEBleGFtcGxlLmNvbTpFSDFsbGt5Q2tGZDJpamJL", "http basic auto for log dest server.");
DEFINE_string(log_cfg_path, "/opt/hibot/src/data/log_waf.yaml", "log waf yaml path for remap key&value");
// DEFINE_string(index_prefix, "waf", "the prefix of db name of index");

#define REDIRECT_MAX 5
#define RETRY_MAX 2

nlohmann::json log_cfg_json; 
nlohmann::json log_buffer = {}; // 实际上是一个array, 只是用 nlhanmman/json 包裹了
std::mutex buffer_mutex;
// std::string url_log_type; 

const static bool program_terminate = true;
// const static size_t max_per_send = 10;

void http_callback(WFHttpTask *task) {
    protocol::HttpResponse *resp = task->get_resp();
    int state = task->get_state();
    int error = task->get_error();

    auto status_code = resp->get_status_code();

    if (state != WFT_STATE_SUCCESS or strcmp(status_code, "200") != 0) {
        auto phrae = resp->get_reason_phrase();
        std::string response_body;
        resp->append_output_body(response_body.data(), response_body.size());
        spdlog::error("http task error: state = {}, error = {}, status_code = {}, phrase = {} - {}",
                      state, error, status_code, phrae, response_body);
        return;
    }

}


nlohmann::json parse_post_data_standard(nlohmann::json json_data, const std::string log_type)
{
    auto x = parse_log_standard(log_cfg_json, json_data, log_type); 
    return x; 
}

void log_to_openobserve(const nlohmann::json log_buffer_data, const std::string log_type) {
    /** */
    // 下面这个打印的size是字符串size, 如果是1代表这个里面是空；
    spdlog::info("sent logs of type [{}] size is [{}]", log_type, log_buffer_data.size());
    WFHttpTask *http_task;
    std::string local_url = FLAGS_log_server + "/api/default/" + log_type + "/_json";
    http_task = WFTaskFactory::create_http_task(local_url,
                                                REDIRECT_MAX,
                                                RETRY_MAX,
                                                http_callback);
    protocol::HttpRequest *req = http_task->get_req();
    req->set_method("POST");
    // 这个地方进行handle data 为我们的内容；
    auto post_body = log_buffer_data.dump();
    req->append_output_body(post_body.data(), post_body.size());

    // req->add_header_pair("Content-Type", "application/x-www-form-urlencoded");
    // req->add_header_pair("Content-Type", "application/json");
    // spdlog::warn("authntication is {}", FLAGS_log_auth); 
    req->add_header_pair("Authorization", FLAGS_log_auth);
    req->add_header_pair("User-Agent", "curl 7.88.1");
    req->add_header_pair("Connection", "close");
    req->add_header_pair("Accept", "*/*");

    /* Limit the http response size to 100M. */
    protocol::HttpResponse *resp = http_task->get_resp();
    resp->set_size_limit(100 * 1024 * 1024);
    http_task->set_receive_timeout(10 * 1000);
    http_task->start();
}

void log_aggregator(const std::string log_type) {
    // function is to send to remote
    nlohmann::json _logs;
    {
        std::lock_guard<std::mutex> lock(buffer_mutex);
        _logs.swap(log_buffer);
        log_buffer = {}; // 将 log buffer 进行恢复到空。后面有了再进行逐步添加。
    }
    if (!_logs.empty()) {
        log_to_openobserve(_logs, log_type);
    }
}

void add_log_entry(const std::string log_entry, const std::string log_type) {
    {
        std::lock_guard<std::mutex> lock(buffer_mutex);

        nlohmann::json json_data = nlohmann::json::parse(log_entry); 
        if(json_data.is_array()){
            for(auto log_item: json_data){
                auto x = parse_post_data_standard(log_item, log_type);
                if( ! x.empty()){
                    log_buffer.push_back(x);
                }
            }
            return ;
        }

        if(json_data.is_object()){
            auto x = parse_post_data_standard(json_data, log_type);
            if( ! x.empty()){
                log_buffer.push_back(x);
            }
            return ; 
        }
    
    }

    if (log_buffer.size() >= FLAGS_max_per_send) {
        log_aggregator(log_type);
    }
}

void handle_query(WFHttpTask *server_task, const std::string log_prefix, const std::string post_data) {
    // add_log_entry(post_data, log_prefix);
    auto log_type = get_middle_str(log_prefix); 
    // spdlog::warn("[debug] input log_prefix is {}   ->   {}", log_prefix, log_type);

    WFGoTask *go_task = WFTaskFactory::create_go_task("common", add_log_entry, post_data, log_type);
    go_task->start(); 

    WFTimerTask *timer = WFTaskFactory::create_timer_task("test", 2, 0, [=](WFTimerTask *task) {
        // spdlog::warn("timer callback, state = %d, error = %d.\n", task->get_state(), task->get_error());
        log_aggregator(log_type);
    });
    // 这里串接http的任务； 如果任务怎么样就执行；
    // timertask后面执行相关的任务，如果条目达到就会进行操作；
    timer->start();
}

void process(WFHttpTask *server_task) {
    protocol::HttpRequest *req = server_task->get_req();
    protocol::HttpResponse *resp = server_task->get_resp();
    // protocol::HttpHeaderCursor cursor(req);

    char buf[8192];
    const auto request_url = req->get_request_uri();

    // TODO 除了我们约定的URL其他的都不准访问。
    if (strcmp(req->get_method(), "POST") == 0) {
        const void *body_ptr = nullptr;
        size_t body_size = 0;
        req->get_parsed_body(&body_ptr, &body_size);
        auto post_data = (std::string) static_cast<char *>((char *)body_ptr);
        std::string response_body = "OK\r\n";
        try {
            handle_query(server_task, request_url, post_data); // 开始进行处理 server_task
        } catch (...) {
            spdlog::error("handle query EROROR and query is {}", post_data);
            response_body = "ER\r\n";
        }

        resp->set_header_pair("Content-Type", "plain/text");
        resp->append_output_body(response_body.data(), response_body.size());

    } else {
        resp->set_status_code("405");
        resp->set_reason_phrase("Method Not Allowed");
    }
}

static WFFacilities::WaitGroup wait_group(1);

void sig_handler(int signo) {
    wait_group.done();
}

int main(int argc, char *argv[]) {
    google::ParseCommandLineFlags(&argc, &argv, true);
    // google::InitGoogleLogging(argv[0]);
    spdlog::warn("[MAIN] start server 0.0.0.0:{}", FLAGS_port);

    get_log_cfg_json(FLAGS_log_cfg_path, log_cfg_json); 

    signal(SIGINT, sig_handler);
    WFHttpServer server(process);

    if (server.start(FLAGS_port) == 0) {
        wait_group.wait();
        server.stop();
    } else {
        perror("Cannot start server");
        exit(1);
    }

    return 0;
}

// 计数器和时间的限制；
// https://github.com/sogou/workflow/blob/master/docs/about-counter.md
// https://github.com/sogou/workflow/blob/master/docs/about-timer.md

```

但是很显然，我的这个程序非常耗时，500qps的任务，我用syslog-ng cpu的占用率是 49%， 但是这个代码是87%+

到底是哪个环节出现问题了； 
add_log_entry 就是添加一个日志到log_buffer 
log_agg 就是聚合日志
log_openobserve 就是把聚合后的日志发送到远程的es/openserve之类的； 但是为啥性能差了这么多，我白白浪费了三天写的

**Comment by xx-zhang** [comment]
难道是 gotask里面的耗时任务都需要套 gotask?

**Comment by Barenboim** [comment]
首先，我们go task本身就支持超时，如果你是为了限制go task的运行时间，没有必要用go task+timer。

另外，可以简单perf一下是哪些函数多占了CPU，workflow框架本身不会占用多少CPU的。

**Comment by Barenboim** [comment]
你server的逻辑是，收到用户请求之后，先返回response然后后台再进行各种计算吗？因为我看你的server里，并不插入任何任务，而且启动了go task和timer之后立刻就回复了。

**Comment by Barenboim** [comment]
> 难道是 gotask里面的耗时任务都需要套 gotask?

这个肯定不用。go task就是一个函数从头执行到尾，再套go task只会更慢。

我主要没有太理解你这个程序的逻辑，全程都没有用到push_back()而是不停的start任务，server也是立刻返回的，没有等待任何任务的结果。这个符合你的预期吗？

**Comment by xx-zhang** [comment]
> > 难道是 gotask里面的耗时任务都需要套 gotask?
> 
> 这个肯定不用。go task就是一个函数从头执行到尾，再套go task只会更慢。
> 
> 我主要没有太理解你这个程序的逻辑，全程都没有用到push_back()而是不停的start任务，server也是立刻返回的，没有等待任何任务的结果。这个符合你的预期吗？

是的，我的主server不需要确定返回结果，只需要收到了数据后直接处理就行了； 主server不需要响应指定内容； 这里套gotask的目的不是 gotask里面的task超时，是我需要有一个管道监控我的数据流（log_buffer）一段实践没有聚合我就需要手动发送，否则就是达到了一定的数量发送，就是这样的一个功能； 您看看我的哪个最后这个步骤 void log_to_openobserve(const nlohmann::json log_buffer_data, const std::string log_type) 这个是否有必要用http_task 我这里直接 start, 会有异步效果？还是还可能阻塞。

**Comment by xx-zhang** [comment]
> 首先，我们go task本身就支持超时，如果你是为了限制go task的运行时间，没有必要用go task+timer。
> 
> 另外，可以简单perf一下是哪些函数多占了CPU，workflow框架本身不会占用多少CPU的。

好的，我用perf跑一下看看； 我感觉该分离的都分离出去了，没有耗时操作在数据流处理里面

**Comment by Barenboim** [comment]
> > > 难道是 gotask里面的耗时任务都需要套 gotask?
> > 
> > 
> > 这个肯定不用。go task就是一个函数从头执行到尾，再套go task只会更慢。
> > 我主要没有太理解你这个程序的逻辑，全程都没有用到push_back()而是不停的start任务，server也是立刻返回的，没有等待任何任务的结果。这个符合你的预期吗？
> 
> @Barenboim 是的，我的主server不需要确定返回结果，只需要收到了数据后直接处理就行了； 主server不需要响应指定内容； 这里套gotask的目的不是 gotask里面的task超时，是我需要有一个管道监控我的数据流（log_buffer）一段实践没有聚合我就需要手动发送，否则就是达到了一定的数量发送，就是这样的一个功能； 您看看我的哪个最后这个步骤 void log_to_openobserve(const nlohmann::json log_buffer_data, const std::string log_type) 这个是否有必要用http_task 我这里直接 start, 会有异步效果？还是还可能阻塞。

直接start肯定是异步的效果，不占CPU，也不阻塞函数的执行。简单看上去，你的代码没有什么地方会导致workflow多占CPU的，你要看CPU分布简单perf record + perf report一下，看看哪个函数占用太多CPU时间。

如果是说workflow只是CPU占用高并且完成了更多任务，那就是正常的。workflow的特点就是可以把CPU用满而不出现长尾延迟。但你又说qps是一样的。

**Comment by Barenboim** [comment]
~~~
req->append_output_body(post_body.data(), post_body.size());
~~~
这个地方看看能不能用append_output_body_nocopy的接口，前提是确保内存在callback之前都可用。

**Comment by xx-zhang** [comment]
@Barenboim 我指定qps用 wrk2 打的； 发现相同环境下，我的代码是有点问题； 我还没有用过perf， 我准备试试，简单看了top； 
这个地方估计能好一点，但是估计就是省点内存，cpu不一定能优化；我研究下吧

![image](https://github.com/user-attachments/assets/9e259301-2288-48b4-aabb-cd947174349c)

**Comment by Barenboim** [comment]
> @Barenboim 我指定qps用 wrk2 打的； 发现相同环境下，我的代码是有点问题； 我还没有用过perf， 我准备试试，简单看了top； no_copy 这个地方估计能好一点，但是估计就是省点内存，cpu不一定能优化；我研究下吧
> 
> ![image](https://private-user-images.githubusercontent.com/47806549/398697197-9e259301-2288-48b4-aabb-cd947174349c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDY5ODUsIm5iZiI6MTczNTIwNjY4NSwicGF0aCI6Ii80NzgwNjU0OS8zOTg2OTcxOTctOWUyNTkzMDEtMjI4OC00OGI0LWFhYmItY2Q5NDcxNzQzNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MDgwMTc1NWU4NDRmNzhiZGU2MDAzYzRmODlmZmM2YjYxZGQzNjc1OTYzMWI3OTZkMmVhMTIzY2NkMmQ2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7YmnqVW5r_qzBemAIVGcczerb7I5dxkhtZ3Ob3DwFv4)

从你的这个图上看，workflow框架没有占CPU。WFTimerTask::done的CPU占用其实是调用log_aggregator，这个占了时间。这里最好push_back一个go task来执行而且不是在timer callback里直接调用，因为timer callback是在网络handler线程里的，这样会占着网络线程。

**Comment by xx-zhang** [comment]
@Barenboim 改动了，差别不大，跟刚才差不多； 没有区别；
```cpp
    // timertask后面执行相关的任务，如果条目达到就会进行操作；
    WFGoTask *go_task2 = WFTaskFactory::create_go_task("log_aggregator_timer", log_aggregator, log_type);
    WFTimerTask *timer = WFTaskFactory::create_timer_task("test", 2, 0, [=](WFTimerTask *task) {
        series_of(task)->push_back(go_task2); 
    });

    timer->start(); 
 ```
    
    
![image](https://github.com/user-attachments/assets/54d5e988-90fc-45ea-b8cc-618f3f3b0828)


wrk2 send , 1500qps 我的cpu都到了150%； 预期应该五六十可以接受。超出太多了，我需要再研究下
![image](https://github.com/user-attachments/assets/29930520-576a-42d4-b075-6743948e1bbe)

**Comment by Barenboim** [comment]
> @Barenboim 改动了，差别不大，跟刚才差不多； 没有区别；
> 
> ```c++
>     // timertask后面执行相关的任务，如果条目达到就会进行操作；
>     WFGoTask *go_task2 = WFTaskFactory::create_go_task("log_aggregator_timer", log_aggregator, log_type);
>     WFTimerTask *timer = WFTaskFactory::create_timer_task("test", 2, 0, [=](WFTimerTask *task) {
>         series_of(task)->push_back(go_task2); 
>     });
> 
>     timer->start(); 
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/47806549/398708853-54d5e988-90fc-45ea-b8cc-618f3f3b0828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTAwNzAsIm5iZiI6MTczNTIwOTc3MCwicGF0aCI6Ii80NzgwNjU0OS8zOTg3MDg4NTMtNTRkNWU5ODgtOTBmYy00NWVhLWI4Y2MtNjE4ZjNmM2IwODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEwNDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNjMyZDdlNzc2YTEzNjMxYTAxYzk4OTEwYjU1ZjEzNGM0ZGNlYjhmOGFmZDUwODNkMGY3N2NlZTcyMmZmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5xMgKYYFygMao9rkpx_FPMUtzSijyFlS-x9IIRQGDWA)
> 
> wrk2 send , 1500qps 我的cpu都到了150%； 预期应该五六十可以接受。超出太多了，我需要再研究下 ![image](https://private-user-images.githubusercontent.com/47806549/398709273-29930520-576a-42d4-b075-6743948e1bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTAwNzAsIm5iZiI6MTczNTIwOTc3MCwicGF0aCI6Ii80NzgwNjU0OS8zOTg3MDkyNzMtMjk5MzA1MjAtNTc2YS00MmQ0LWIwNzUtNjc0Mzk0OGUxYmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEwNDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OTU0Y2NjODkzY2MxNzI4ZWQ5ZGQ2ZDllNmY0OGM1YWQ4YTU0NTM3M2RjOWFkMGE3OWNjMjA4NDk2MGFhOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zk0VANlKjvrHV-UUtT4bo8dezEzt2SA7cZHb2x9_jwA)

嗯嗯，改动的目的是为了更好的看CPU分布。

CPU高不正是workflow的优点么？可以充分利用CPU并且没有长尾效应才是好的啊。占用CPU 的都是用户函数就没有什么问题，说明框架本身不会增加CPU占用。

**Comment by Barenboim** [comment]
对了，这个调用栈这么深，你是不是代码没有优化啊？

**Comment by xx-zhang** [comment]
> 对了，这个调用栈这么深，你是不是代码没有优化啊？

@Barenboim 嗯嗯， 我研究下这个，因为我起初以为是mutex + workflow有卡死导致的，既然不在这个环节，我就看看我的日志处理的函数里面怎么优化下了。
