### ISSUE TITLE
MySql client issue

### ISSUE THREAD

**Issue by MaybeShewill-CV** [sogou/workflow#169]
1.创建mysql任务执行数据库的插入，插入记录成功，但是会出现Abnormal packet_type=1。想请教下一般可能的原因是什么，控制台输出来自
https://github.com/sogou/workflow/blob/6ffb7e0da9e8ea24300aef79c4f60761388da1f1/tutorial/tutorial-12-mysql_cli.cc#L203-L206

2.对于需要插入多条记录的任务，是分别每条记录建立一个task比较好呢还是建立一个task执行多条insert语句好呢。

数据库小白，问的问题可能比较zz ==！

**Comment by Barenboim** [comment]
~~~cpp
// MySQL packet type
enum
{
	MYSQL_PACKET_OTHER	=	0,
	MYSQL_PACKET_OK,
	MYSQL_PACKET_NULL,
	MYSQL_PACKET_EOF,
	MYSQL_PACKET_ERROR,
	MYSQL_PACKET_LOCAL_INLINE,
};
~~~
这就很奇怪了，因为1是一个PACKET_OK。你更新一下代码重新编译试试。
插入多条记录的方法就看你需求了，你想要并行任务都可以。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 好的 我下来更新下代码再看看哈。嗯 明天试试并行任务：）

**Comment by MaybeShewill-CV** [comment]
@Barenboim 更新了代码重新编译之后没有abnormal packet_type=1的输出了 :)

**Comment by Barenboim** [comment]
感谢使用！有什么新问题随时反馈。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 好的 :+1:
