### ISSUE TITLE
windows分支的tutorial-04-http_echo_server.cc 运行崩溃

### ISSUE THREAD

**Issue by erehw** [sogou/workflow#177]
tutorial-04-http_echo_server.cc 
服务在接收到不正确的请求时，如接收到 hi\r\n\r\n，会崩溃。
vs2019 x64

**Comment by Barenboim** [comment]
感谢反馈。我试了Linux版本没有问题，还会返回400 Bad Request错误。这周我让windows分枝的同学看一下。

**Comment by Barenboim** [comment]
这是windows版在返回400 bad request时的问题。这个pr已经修改。
@erehw

**Comment by Barenboim** [comment]
还有别的问题，还在查。

**Comment by Barenboim** [comment]
已修复！
