### ISSUE TITLE
workflow并行串行处理的机制

### ISSUE THREAD

**Issue by zhouchunliang** [sogou/workflow#192]
请教下，SubTask.cc中任务分发及任务处理中红色框框中大概的含义是什么那？dispath与done均调用subtask_done，看到if条件，但不清楚具体的条件是什么？能否解答下（不论是并行还是串行，任务的分发都是顺序的，只不过分发到不同的request,如dns dispatch到WFRouterTask::dispatch，http task dispatch到WFComplexClientTask::dispatch,进而Communicator::request，但这个过程是通过ParallelTask::dispatch()顺序依次分发的）;另外从服务端接收到数据，放进msgqueue,网络线程池触发handle,每次都必须调用subtask_done，最终调用用户注册的回掉函数，如果是基于此，并行处理的主要机制其实就是利用queue的特性，多个线程调用各自的注册的回掉函数；
![image](https://user-images.githubusercontent.com/18730685/103150525-0e05a800-47b0-11eb-91fc-2c30abf302ee.png)
另外，附加问一个小问题，类似这样的硬编码为1 （node == (struct __poller_node *)1）是什么含义那？
![image](https://user-images.githubusercontent.com/18730685/103150576-66d54080-47b0-11eb-8a14-1ddb7104e3ba.png)

**Comment by Barenboim** [comment]
先回答你第二个问题，我在event的data里，用0和1分别代表定时器和管道事件。因为data是一个指针，所以直接就把数值1强转成指针。1不可能是一个合法地址，所以看到node==1就知道是一个pipe事件，pipe用来通知各种fd的删除和poller的停止。第一个判断if (node>1)，是因为大多数情况下，都是正常的网络事件，于是只需判断一次，就能进入处理逻辑了。
第一个问题有点复杂，我明天再回复。

**Comment by Barenboim** [comment]
第一个问题，直接和你解释SubTask的原理吧。SubTask要求用户实现两个接口，dispatch和done。
dispatch代表任务的发起，可以是任何行为，并且要求任务在完成的时候调用subtask_done方法，一般这时候已经不在dispatch线程了。
done是任务的完成行为，你可以看到subtask_done里立刻调用了任务的done。done方法把任务交回实现者，实现者要负责内存的回收，比如可能delete this。done方法可以返回一个新任务，可以认为原任务转移到新任务并且立刻dispatch，所以return this也是一个常见做法。
以上实现了一个任务的串行执行逻辑。而ParallelTask是一种特殊任务，它的dispatch行为是把所有子任务依次dispatch，而结束条件是所有子任务转移到NULL。同样ParallelTask的done也可以返回一个新的任务继续转移。
以上的方法其实等价于一个无限的串并联组合。其它的你就看代码就好了。
整个kernel目录下的东西都是很早之前就做出来的，不是为了workflow项目设计的。workflow其它的模块只有为了用户用起来更简单。

**Comment by zhouchunliang** [comment]
以redis-cli为列，大致请求过程如下：
![image](https://user-images.githubusercontent.com/18730685/103166233-f1727a00-485a-11eb-87e4-6dc0fca094cf.png)
个人理解：根据任务的类型分发到对应的任务dispatch；可以简单理解为：有对应的任务就需要调用下SubTask::subtask_done；与之对应，有对应的任务结果，也需要调用SubTask::subtask_done触发用户注册的回掉；

**Comment by zhouchunliang** [comment]
ok，多谢

**Comment by Barenboim** [comment]
嗯嗯，你一层一层的考虑就好，底层只定义一套机制和原语，并不知道上层的用法。做SubTask的时候我也并不知道我们后面会干嘛😁

**Comment by zhouchunliang** [comment]
> 做SubTask的时候我也并不知道我们后面会干嘛

多谢讲解

**Comment by fengyonglv** [comment]
你好，subtask_done函数中 **entry指针的作用是什么呢？ 是表示当前Task中正在执行的任务吗？ 找了一下全局代码，还没有看到在那块中使用entry指针。谢谢 @Barenboim

**Comment by Barenboim** [comment]
在SubTask::subtask_done()里使用了。处理parallel的使用，需要知道task是parallel task的那一个入口。
