### ISSUE TITLE
有相关的user_guide文档么

### ISSUE THREAD

**Issue by xingjinglu** [sogou/workflow#195]
是否有一个user_guide文档，整体上介绍workflow的整体架构，以及核心的数据结构和API。
现在只看到一些不同场景的tutorial例子，了解起来比较分散

**Comment by Barenboim** [comment]
现在的文档示例主要是为了用户可以快速使用起来。把实例代码看一遍，主要的功能点应该都可以掌握。
设计文档写起来不容易，我们现在有点没缺少人手。你看看有什么具体问题都可以issues里提问，或者加一下qq群。

**Comment by MaybeShewill-CV** [comment]
@xingjinglu 亲测qq群的“客服”人员响应速度很快：）

**Comment by holmes1412** [comment]
> @xingjinglu 亲测qq群的“客服”人员响应速度很快：）

“客服”路过并表示主要是小伙伴们思路活跃又比较热情！

**Comment by holmes1412** [comment]
@xingjinglu 不介意的话可以到我的知乎专栏围观一下非官方的user_guide:
https://www.zhihu.com/column/c_1219198018936983552
我们最近在2020 pure c++大会也有分享，到时候可以把ppt和回放地址给你～

**Comment by MaybeShewill-CV** [comment]
@holmes1412 👍围观一下：）

**Comment by xingjinglu** [comment]
> @xingjinglu 不介意的话可以到我的知乎专栏围观一下非官方的user_guide:
> https://www.zhihu.com/column/c_1219198018936983552
> 我们最近在2020 pure c++大会也有分享，到时候可以把ppt和回放地址给你～

看到了，

**Comment by xingjinglu** [comment]
> @xingjinglu 不介意的话可以到我的知乎专栏围观一下非官方的user_guide:
> https://www.zhihu.com/column/c_1219198018936983552
> 我们最近在2020 pure c++大会也有分享，到时候可以把ppt和回放地址给你～

学习一下 : )
