### ISSUE TITLE
有打算支持vcpkg么

### ISSUE THREAD

**Issue by lordoffox** [sogou/workflow#197]
如题

**Comment by Barenboim** [comment]
@dengjunplusplus
支持这个东西好改吗？

**Comment by dengjunplusplus** [comment]
@lordoffox 感谢反馈，后续是要支持的，用vcpkg对于Windows平台来说会易用很多。
@Barenboim 初步看来不是很复杂，近期计划加一下

**Comment by lordoffox** [comment]
vcpkg对linux也很方便，cmake可以简化很多，那就期待未来的改进了。

**Comment by sshsu** [comment]
好喜欢你们这个项目，能否也考虑一下把包添加到jfrog的conan center
[教程传送门](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md)

**Comment by dengjunplusplus** [comment]
> 好喜欢你们这个项目，能否也考虑一下把包添加到 jfrog 的 conan center
> [教程传送门](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md)

VCPKG看到希望了，最近再优化下。有时间我研究一下conan center

**Comment by dengjunplusplus** [comment]
@lordoffox workflow的vcpkg已被微软仓库主分支合并，可以更新下vcpkg试试看

**Comment by ilongshan** [comment]
希望能够支持conan
