### ISSUE TITLE
基础任务层WFNetworkTask中keep_alive_timeo超时问题

### ISSUE THREAD

**Issue by zhouchunliang** [sogou/workflow#199]
咨询个小问题，在get_idle_conn的方法中，遍历idle_list，并设置sockfd的timeout为-1；那这个设置的sockfd time为-1，一直处于等待状态，直到数据处理完，才会设置此sockfd time为keepalive time(如果这么理解也有问题，我看代码部份实现中epolladd 设置的时间为keepalive time，并设置idle_list时间也为keepalive time)？
![image](https://user-images.githubusercontent.com/18730685/103406872-3538ec80-4b97-11eb-8321-68d1637a15aa.png)
![image](https://user-images.githubusercontent.com/18730685/103406887-43870880-4b97-11eb-8219-0b5b8c426374.png)
![image](https://user-images.githubusercontent.com/18730685/103406898-4bdf4380-4b97-11eb-959f-fc21f80fad12.png)

**Comment by zhouchunliang** [comment]
仔细阅读了代码，当workflow充当httpserver时，res状态为PR_ST_FINISHED时，timeout>0,添加sockfd可读，超时时间timeout，同时添加service->alive_list；当workflow充当httpclient时,拿到服务端返回的可读结果时，设置target->idle_list

**Comment by Barenboim** [comment]
首先handle_reply_result()是server处理自己异步回复结果的函数。client处理server返回，是在handle_incoming_reply()里。client通过mpoll_set_tiimeout(-1)原子性的将一个连接超时设置为无限，如果成功说明连接没有关闭或者错误，可以复用。
至于keep_alive_timeout这个是网络交互完成之后才被调用的，因为只有交互完才知道连接是否保持以及保持多久。从开始复用连接到交互完成，中间还有很多次的超时设置呢。
