### ISSUE TITLE
CommSession、CommTarget、CommService、CommConnection含义

### ISSUE THREAD

**Issue by zhouchunliang** [sogou/workflow#200]
Communicator.cc中的struct CommConnEntry中CommSession、CommTarget、CommService与CommConnection的含义？
![image](https://user-images.githubusercontent.com/18730685/103769614-8d706280-505f-11eb-8ea4-b6f8e55ef249.png)

**Comment by Barenboim** [comment]
CommTarget是通讯目标，基本上就是ip+port, 还有两个超时参数。连接池什么的都在target里。
CommSession是一次req->resp的交互，主要要实现message_in(), message_out()等几个虚函数，让核心知道怎么产生消息。
CommSerive就是服务了，主要是new_session()的实现，因为对server来讲，session是被动产生的。
Communicator::request(CommSession *session, CommTarget *target)这个借口就可以实现一个异步的网络请求了，你可以写个程序试试，Session大概这么派生：
~~~cpp
class MyHttpSession : public CommSession
{
private:
    CommMessageOut *message_out() override { return new protocol::HttpRequest; }
    CommMessageIn *message_in() override { return new protocol::HttpResponse; }
    void handle(int state, int error) override
    {
        protocol::HttpResponse *resp = (protocol::HttpResponse *)this->get_message_in();
        // print resp
        ...
        delete this->get_message_out();
        delete this->get_message_in();
        delete this;
    }
};

int main()
{
    Communicator comm;
    comm.init(2, 10);
    CommTarget target;
    target.init(...);
    comm.request(new MyHttpSession, &target);
    ...
}
~~~

**Comment by sourcema** [comment]
![image](https://user-images.githubusercontent.com/39115865/221739716-46750d38-bc91-4358-8123-c881612ac6d7.png)
请问下CommConnection只有虚函数，为什么这么定义呢，出于什么考虑呢？

**Comment by Barenboim** [comment]
> ![image](https://user-images.githubusercontent.com/39115865/221739716-46750d38-bc91-4358-8123-c881612ac6d7.png) 请问下CommConnection只有析构方法，为什么这么定义呢，出于什么考虑呢？

Target或Service里有个new_connection可以产生这个类的派生，用户可以给连续设置上下文。

**Comment by sourcema** [comment]
> 
多谢

**Comment by sourcema** [comment]
> > ![image](https://user-images.githubusercontent.com/39115865/221739716-46750d38-bc91-4358-8123-c881612ac6d7.png) 请问下CommConnection只有析构方法，为什么这么定义呢，出于什么考虑呢？
> 
> Target或Service里有个new_connection可以产生这个类的派生，用户可以给连接设置上下文。

多谢
