### ISSUE TITLE
Windows版http请求回调两次后崩溃

### ISSUE THREAD

**Issue by wooviet** [sogou/workflow#203]
创建一个httpTask，然后start，但是回调了两次，第一次回调是正常收到了服务器数据，第二次回调中任务状态是WFT_STATE_SYS_ERROR，具体错误是connection reset，然后框架就崩溃了。

**Comment by Barenboim** [comment]
代码贴一下。我觉得你可能是start了两次，或者被两放进了两个series里了。

**Comment by wooviet** [comment]
`int main(int argc, char* argv[]) {
    //signal(SIGINT, sig_handler);
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 20000;
    settings.endpoint_params.response_timeout = -1;
    WORKFLOW_library_init(&settings);
    Json::Value root;
    root["signatureStr"] = "butel";
    root["signatureVersion"] = "butel";
    root["meetingID"] = "butel";
    root["funcName"] = "butel";
    // const char* url = "http://10.33.36.72:8081/MeetingCtrl";
    const char* url = "http://192.168.17.130:10111/RecordLiveService";
    WFHttpTask* http_task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
                                                            test_http_task_cb);
    http_task->set_send_timeout(2000);
    http_task->set_receive_timeout(2000);
    protocol::HttpRequest* req = http_task->get_req();
    req->add_header_pair("Accept", "*/*");
    // req->add_header_pair("Connection", "close");
    req->set_method("POST");
    req->append_output_body(root.toStyledString());
    http_task->start();
    //wait_group.wait();
    getchar();
    printf("exit suc\n");
    return 0;
}`

**Comment by wooviet** [comment]
int main(int argc, char* argv[]) {
    //signal(SIGINT, sig_handler);
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 20000;
    settings.endpoint_params.response_timeout = -1;
    WORKFLOW_library_init(&settings);
    Json::Value root;
    root["signatureStr"] = "butel";
    root["signatureVersion"] = "butel";
    root["meetingID"] = "butel";
    root["funcName"] = "butel";
    // const char* url = "http://10.33.36.72:8081/MeetingCtrl";
    const char* url = "http://192.168.17.130:10111/RecordLiveService";
    WFHttpTask* http_task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
                                                            test_http_task_cb);
    http_task->set_send_timeout(2000);
    http_task->set_receive_timeout(2000);
    protocol::HttpRequest* req = http_task->get_req();
    req->add_header_pair("Accept", "*/*");
    // req->add_header_pair("Connection", "close");
    req->set_method("POST");
    req->append_output_body(root.toStyledString());
    http_task->start();
    //wait_group.wait();
    getchar();
    printf("exit suc\n");
    return 0;
}

**Comment by wooviet** [comment]
代码就只有这么多，没有刚刚你说的那两个问题，我抓包发现服务器先返回了302，又返回了RST，然后框架就崩溃了，必现，你可以测一下试试，下面是崩溃的堆栈截图：
![图片](https://user-images.githubusercontent.com/25996583/103993386-7ef58880-51d0-11eb-963e-b4836118a2aa.png)

**Comment by wooviet** [comment]
代码就只有这么多，没有刚刚你说的那两个问题，我抓包发现服务器先返回了302，又返回了RST，然后框架就崩溃了，必现，你可以测一下试试

**Comment by wooviet** [comment]
![微信截图_20210108164916](https://user-images.githubusercontent.com/25996583/103994097-7ea9bd00-51d1-11eb-8e8b-b9899a5a153e.png)
这是堆栈的截图

**Comment by Barenboim** [comment]
Windows版啊，好的。我让windows的同学看看哈：）Windows版的bug确实比较多，上线的话目前还是推荐在Unix系统上。

**Comment by wooviet** [comment]
好的谢谢

**Comment by Barenboim** [comment]
@wooviet
再试一下，应该可以了。

**Comment by wooviet** [comment]
@Barenboim 目前看是正常了
