### ISSUE TITLE
吞吐和长尾可以简单解释下吗？之前一直关注qps

### ISSUE THREAD

**Issue by zhouchunliang** [sogou/workflow#210]
如何理解吞吐和长尾？对于重计算类的任务，吞吐和长尾指标如何评定？

**Comment by holmes1412** [comment]
简单理解：吞吐就是你的qps，长尾是你的最慢的那几个请求的耗时情况。
一般来说，系统整体，你希望吞吐高；
可是对独立的请求来说，你希望长尾好。

但是吞吐和长尾一般来说都是trade off的，举个例子：
我们来了请求，都要通过队列去接收和切换到handler对吧，
那么这个队列怎么实现，就非常影响吞吐和长尾。

然后队列可能有锁，
想要吞吐高，拆多几个队列，锁粒度就小了；
但队列拆大了，处理不均匀的话，某些请求来了等了很久没有被处理到，长尾就不好了；

想要多队列又均匀，可以提供一些小队列内处理完去其他队列拿任务分担的机制，
比如work stealing，但是每一层复杂的机制对单个请求对耗时都是一点点额外的增加。
所以怎么做最通用最好，是非常考验系统本身的实现的，也要取决于不同场景下的使用，

也因此才会说，吞吐和长尾是衡量一个系统性能的两个重要维度。
一般来说工业系统，长尾还是要比吞吐重要一些，长尾耗时的突降也非常值得关注。
