### ISSUE TITLE
关于tutorial-10-user_defined_protocol 的使用疑问，客户端连接服务器后会主动发送一条消息

### ISSUE THREAD

**Issue by yangdianxp** [sogou/workflow#216]
关于tutorial-10-user_defined_protocol 的使用疑问，客户端连接服务器后会主动发送一条消息，如何禁止这种行为？

**Comment by Barenboim** [comment]
这个只是个demo，为了让读取用户输入都在callback里进行，就简单这么写了。你实际业务里，就像http一样，需要的时候再请求就可以了。

**Comment by Barenboim** [comment]
我大概理解你的意思了。你可能把第一个请求理解为connection过程了？并不是这样，所以client task不存在连接的过程，你可以参考一下redis client的例子，连接登陆过程都是被隐藏起来的。用户一般不用指定连接，除了带事务的mysql任务。
