### ISSUE TITLE
请问作者是使用什么规范进行mysql异步通信的呢？

### ISSUE THREAD

**Issue by yuanzhanyan** [sogou/workflow#218]

**Comment by yuanzhanyan** [comment]
mysql有这方面的异步支持框架或者组件嘛

**Comment by Barenboim** [comment]
手写的呀。直接解析mysql协议。

**Comment by yuanzhanyan** [comment]
> 手写的呀。直接解析mysql协议。

意思是客户端来维护mysql请求和响应的对应关系，那好像也会存在线程阻塞的问题呀

**Comment by Barenboim** [comment]
不是这样，mysql协议不存在同步还是异步，阻塞还是不阻塞的问题。通信模型是连接上带状态的请求，响应一来一回的过程，做成非阻塞的没有什么问题。如果是事务请求，先建立WFMySQLConnection对象就可以了。而且，就算这个connection对象，也不存在占线程连接的过程。

**Comment by yuanzhanyan** [comment]
> 不是这样，mysql协议不存在同步还是异步，阻塞还是不阻塞的问题。通信模型是连接上带状态的请求，响应一来一回的过程，做成非阻塞的没有什么问题。如果是事务请求，先建立WFMySQLConnection对象就可以了。而且，就算这个connection对象，也不存在占线程连接的过程。
