### ISSUE TITLE
是否支持计算任务和cpu绑定。

### ISSUE THREAD

**Issue by cdjingit** [sogou/workflow#219]
场景：
服务一次请求处理，需要并行执行几个固定的计算任务，框架能否尽量把相同的计算任务调度在同一个cpu上运行？

**Comment by Barenboim** [comment]
这个问题对我们很有启发。我先说一下我们目前的调度方式。
我们每个计算任务的第一个参数都是计算队列名，FAQ里有描述了队列名所起的作用。像你这种并行几个固定的计算任务，推荐的方式是每种任务一个队列名。但是无论队列名怎么选取，只要计算线程没有被占满，所有任务都是实时的被调起的。因此只有cpu跑满时，队列名才会起实际作用。
你提出的相同计算任务尽量在同一个cpu上运行，我现在不知道能不能容入我们的调度策略。我感觉实现这个功能，可能会影响任务调起的实时性。你可以先试试我们现在这个调度算法，看看是否能达到预期性能。我们也考虑一下CPU绑定的问题。因为我们天生带了一个计算队列名，所以接口上是比较适合做这件事的。

**Comment by cdjingit** [comment]
谢谢回复，还没仔细看workflow框架，不清楚内部的细节。只是抛出这么一个问题。是的，如果支持cpu绑定，会给每种任务起一个名字。
当然首先是保证task被及时调度，各个种类task的计算任务不均衡的时候，可能做不到理想的任务的cpu亲缘性。
但是在某些场景下，调度器能合理的把不同名称的任务安排到相对固定的不同的cpu组上执行。
目前我也没仔细想过复杂度和收益。
