### ISSUE TITLE
windows+cmake+VS2019 解决三个问题, 编译完成.

### ISSUE THREAD

**Issue by warm-dawn** [sogou/workflow#263]
![image](https://user-images.githubusercontent.com/59309812/109145133-0a38d680-779d-11eb-8b8a-3a6ccbebc9fb.png)
![image](https://user-images.githubusercontent.com/59309812/109145212-29cfff00-779d-11eb-8809-a4efb0e06d1b.png)

![image](https://user-images.githubusercontent.com/59309812/109145188-1f156a00-779d-11eb-85ec-2969a012d21a.png)
![image](https://user-images.githubusercontent.com/59309812/109145268-3d7b6580-779d-11eb-88cb-b16c03f79c4e.png)

![image](https://user-images.githubusercontent.com/59309812/109145338-5552e980-779d-11eb-805a-7d59d4143df4.png)
![image](https://user-images.githubusercontent.com/59309812/109145367-600d7e80-779d-11eb-94bd-bcd2c8a9584f.png)

**Comment by Barenboim** [comment]
感谢反馈。看了一下好像是random_shuffle在c++17里被移除了。我们同步更新一下。

**Comment by Barenboim** [comment]
你好，可以看看windows分支最新代码有没有问题。
