### ISSUE TITLE
How to compile to dynamic library?

### ISSUE THREAD

**Issue by tjliupeng** [sogou/workflow#27]
Hi, guys,

I just get a 76-byte libworkflow.so and 11.7M libworkflow.a after I run the make command in the project root folder. How to generate a real dynamic shared library?

Even using the libworkflow.a library, I can't compile my code. The error is below:
XXXXX@XXXXX-HPWS:~/personal/gitee/dl4cpp$ make
g++ -g -std=c++11 -Wall -I./sogou-workflow/include -L./sogou-workflow/lib -l:libworkflow.a src/main.cc -o src/main.o
/tmp/cc1vPAdt.o: In function `protocol::HttpMessage::append_output_body(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/HttpMessage.h:159: undefined reference to `protocol::HttpMessage::append_output_body(void const*, unsigned long)'
/tmp/cc1vPAdt.o: In function `EncodeStream::~EncodeStream()':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/EncodeStream.h:101: undefined reference to `EncodeStream::clear_buffer()'
/tmp/cc1vPAdt.o: In function `protocol::RedisValue::~RedisValue()':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/RedisMessage.h:228: undefined reference to `protocol::RedisValue::free_data()'
/tmp/cc1vPAdt.o: In function `protocol::RedisMessage::~RedisMessage()':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/RedisMessage.h:324: undefined reference to `redis_parser_deinit'
/tmp/cc1vPAdt.o: In function `WFServerBase::WFServerBase(WFServerParams const*)':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/WFServer.h:56: undefined reference to `vtable for WFServerBase'
/tmp/cc1vPAdt.o: In function `WFServerBase::start(unsigned short)':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/WFServer.h:69: undefined reference to `WFServerBase::start(int, char const*, unsigned short, char const*, char const*)'
/tmp/cc1vPAdt.o: In function `WFServerBase::stop()':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/WFServer.h:133: undefined reference to `WFServerBase::shutdown()'
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/WFServer.h:134: undefined reference to `WFServerBase::wait_finish()'
/tmp/cc1vPAdt.o: In function `WFServerBase::~WFServerBase()':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/WFServer.h:52: undefined reference to `vtable for WFServerBase'
/tmp/cc1vPAdt.o: In function `WFServer<protocol::HttpRequest, protocol::HttpResponse>::new_session(long long, CommConnection*)':
/home/XXXXX/personal/gitee/dl4cpp/./sogou-workflow/include/WFHttpServer.h:53: undefined reference to `WFServerTaskFactory::create_http_task(std::function<void (WFNetworkTask<protocol::HttpRequest, protocol::HttpResponse>*)>&)'
/tmp/cc1vPAdt.o:(.rodata._ZTV8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE[_ZTV8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE]+0x20): undefined reference to `WFServerBase::handle_unbound()'
/tmp/cc1vPAdt.o:(.rodata._ZTV8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE[_ZTV8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE]+0x28): undefined reference to `WFServerBase::create_listen_fd()'
/tmp/cc1vPAdt.o:(.rodata._ZTV8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE[_ZTV8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE]+0x30): undefined reference to `WFServerBase::new_connection(int)'
/tmp/cc1vPAdt.o:(.rodata._ZTVN8protocol12RedisMessageE[_ZTVN8protocol12RedisMessageE]+0x10): undefined reference to `protocol::RedisMessage::encode(iovec*, int)'
/tmp/cc1vPAdt.o:(.rodata._ZTVN8protocol12RedisMessageE[_ZTVN8protocol12RedisMessageE]+0x28): undefined reference to `protocol::RedisMessage::append(void const*, unsigned long*)'
/tmp/cc1vPAdt.o:(.rodata._ZTVN8protocol12RedisMessageE[_ZTVN8protocol12RedisMessageE]+0x48): undefined reference to `non-virtual thunk to protocol::RedisMessage::append(void const*, unsigned long*)'
/tmp/cc1vPAdt.o:(.rodata._ZTI8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE[_ZTI8WFServerIN8protocol11HttpRequestENS0_12HttpResponseEE]+0x10): undefined reference to `typeinfo for WFServerBase'
collect2: error: ld returned 1 exit status
GNUmakefile:15: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1

**Comment by sonullx** [comment]
Hi there! Thank you for using our project.

I think I could help with the later question.

This is your command:

>  `g++ -g -std=c++11 -Wall -I./sogou-workflow/include -L./sogou-workflow/lib -l:libworkflow.a src/main.cc -o src/main.o`

Here are my two opinions:

+ `src/main.cc` should be put before `-l:libworkflow.a`. Library order does matter when using g++. See [Here](https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc) for more details.

+ `-lssl -lcrypto -lpthread` is needed following `-l:libworkflow.a`. Workflow needs OpenSSL and PThreads.

So, I think the right command was:

`g++ -g -std=c++11 -Wall src/main.cc -I./sogou-workflow/include/ -L./sogou-workflow/lib -l:libworkflow.a -lssl -lcrypto -lpthread -o src/main.o`


In addition, I have two other suggestions:

+ `g++` outputs an executable file, so `main.o` might not be a good name. Usually `.o` file is created by `g++ -c`.

+ It is not necessary to rename `_include` and `_lib` dirs under `sogou-workflow`. But it is all right if you like it, not a problem.


If you got other problems, please don't be hesitate to  contact us. Thank you.

**Comment by tjliupeng** [comment]
My fault.

**Comment by tjliupeng** [comment]
Thanks @sonullx for quick reply. "main.o" is just for my test code. In formal project, I won't use the name like this.

**Comment by tjliupeng** [comment]
@sonullx 
One  more question: why the content of libworkflow.so is text: GROUP ( libworkflow.a AS_NEEDED ( libpthread.so libssl.so libcrypto.so ) ) ? I don't this kind of usage before. Where can I find the reference?

**Comment by sonullx** [comment]
It is a linker script.

See [this](https://sourceware.org/binutils/docs/ld/File-Commands.html).
