### ISSUE TITLE
How to get multi-part form file from the http request?

### ISSUE THREAD

**Issue by tjliupeng** [sogou/workflow#28]
Hi, guys,

I want to use the workflow to build a RESTful server which can receiver image file from client and do some AI works. As the title says, how to get multi-part form file from the http request? Can you share a code example?

Thanks!

**Comment by Barenboim** [comment]
You means splitting query of URI? Like http://.../?a=1&b=2c=3...
Maybe [URIParser](https://github.com/sogou/workflow/blob/master/src/util/URIParser.h) will help you.

**Comment by tjliupeng** [comment]
@Barenboim , URI Like http://.../?a=1&b=2c=3 is the query parameter in URL for GET method. What I mean is the file attachment in the http request.

**Comment by Barenboim** [comment]
You means Http message body?
Example:
void process(WFHttpTask *task)
{
   const void *body;
   size_t size;
   task->get_req()->get_parsed_body(&body, size);
   ...
}
get_parsed_body() is an method of protocol::HttpMessage。BTW, this interface does decode chunk encoding, it returns orginal http message body.

**Comment by Barenboim** [comment]
Sorry, we don't parse multi-part form of http message automatically. So you may get the message body, and parse it by yourself.
Example:
void process(WFHttpTask *task)
{
const void *body;
size_t size;
task->get_req()->get_parsed_body(&body, size);
// parse body here
...
}
get_parsed_body() is an method of protocol::HttpMessage。BTW, this interface does decode chunk encoding, it returns orginal http message body.

**Comment by Barenboim** [comment]
To decode chunked body, you may use HttpUtil::decode_chunked_body in [HttpUtil](https://github.com/sogou/workflow/blob/master/src/protocol/HttpUtil.h). Or use HttpChunkCursor to decode chunks with zero-copy.

**Comment by Barenboim** [comment]
https://github.com/BDZNH/workflow-HttpFormdataParser

**Comment by Barenboim** [comment]
@tjliupeng
Restful web framework based on workflow: https://github.com/wfrest/wfrest

**Comment by tjliupeng** [comment]
> 

Nice.

**Comment by Jamishon** [comment]
int state = task->get_state();

        if (state == WFT_STATE_SUCCESS)
        {
            protocol::HttpResponse* response = task->get_resp();

            const void* body;
            size_t len;

            response->get_parsed_body(&body, &len);

            char* resp_body = new char[len + 1];
            memset(resp_body, 0, len + 1);
    }

I use the snap code above to the http Post response,  response data is to much,  but the maxmium len is always 380696, I use the tool Postman it return the all data, how can I get the rest data or there is a bug on the reponse data buffer .
