### ISSUE TITLE
我应该如何在ubuntu构建？

### ISSUE THREAD

**Issue by ArdxWe** [sogou/workflow#280]

**Comment by ArdxWe** [comment]
希望能将各平台构建方法写在`README`里，这样会更方便 : )

**Comment by Barenboim** [comment]
FAQ里简单写了，你可以看看。安装的话好像make install就可以了。因为没有其他依赖，构建什么的还是比较简单的。如果用到kafka协议，就需要预先安装snappy, lz4和zstd几个压缩库。

**Comment by ArdxWe** [comment]
好的 我已经构建成功 谢谢
