### ISSUE TITLE
请问支持redis集群模式吗？-- 已支持

### ISSUE THREAD

**Issue by wooviet** [sogou/workflow#282]
我看了upstream，这个并不是集群模式。

**Comment by Barenboim** [comment]
能不能描述一下具体需求？目前的redis包括redis client和redis server框架，redis server可以用来实现redis proxy或redis cluster。upstream可以用来实现redis读写分离，数据分片等功能。不太清楚你说的集群模式是哪种需求？

**Comment by wooviet** [comment]
比如我有一个redis集群，三台服务器，客户端访问这个redis集群时应该同时填写三个服务器的地址，否则客户端发送命令会得到错误：MOVED。

**Comment by Barenboim** [comment]
这个的话，upstream确实解决不了，upstream只是一个本地的名称服务，不会把一个任务转成多个。你可以根据需要用workflow的串行或并行来解决。
另外一种方法就是用WFRedisServer来实现一个服务器，由这个服务器来负责多写入，client还是用redis协议访问这个server，这样多一次网络转发。
如果你还有事务性或一致性的需求，那可能需要比较复杂的逻辑来实现了。

**Comment by wooviet** [comment]
实际上如果客户端库如果处理了-MOVED，-ASK之类的错误的话就应该是支持集群模式的。感谢你的回复: )

**Comment by Barenboim** [comment]
哈哈，好像并没有特殊处理。我们研究一下能不能增加这个功能。

**Comment by Barenboim** [comment]
感觉和http redirect差不多，属于我们比较好做的。

**Comment by Barenboim** [comment]
@wooviet 已经完整支持了。MOVED和ASK都支持。client可以自动跳转和ASK。Redis Server实现cluster，也可以通过req->is_asking()来实现ASK语义。
暂不支持对SLOT的保存。
