### ISSUE TITLE
能否不依赖OpenSSL？

### ISSUE THREAD

**Issue by sotex** [sogou/workflow#30]
这个项目很棒，一次编译过，示例代码也能正常运行。
我看了下代码，涉及到 SSL 的地方其实不多，能否改造一下，把这个依赖变为可选项呢？

**Comment by IULOVE** [comment]
我觉得可以把这个改成可选的，这样不需要的可以不用

**Comment by Barenboim** [comment]
哈哈，我也想把ssl的东西都#ifdef了。但我又讨厌ifdef。下个版本我改改看。

**Comment by skyformat99** [comment]
支持，openssl太恶心了啊；

**Comment by Barenboim** [comment]
clean branch不需要ssl，深度代码改动。目前由于用到MD5和SHA1，依然需要链接crypto。

**Comment by sotex** [comment]
> 
> 
> 新的nossl branch不需要ssl，深度代码改动。目前由于用到MD5和SHA1，依然需要链接crypto。

可以考虑把 https://create.stephan-brumme.com/hash-library/ 的代码集成进来，这样又少一点依赖了🤭。
