### ISSUE TITLE
我有一个需求，希望能动态创建多个task，又希望这些task能被顺序的执行来避免多线程竞争，该如何做。

### ISSUE THREAD

**Issue by lordoffox** [sogou/workflow#301]
如题。

**Comment by holmes1412** [comment]
感谢小伙伴的使用～这是一个比较经典的场景，一种解决办法是创建一个series来保证多个task的顺序执行：
```cpp
SeriesWork *series = Workflow::create_series_work(first_task, series_callback);
series->start();
```
只要这个series指针可以被共享，就可以被多方往里放任务。但需要注意的是，series如果执行完、没有任务了就会结束，所以可以使用``WFCounterTask``作为内存开关，series内没有任务的时候放一个
```cpp
WFCounterTask *counter = WFTaskFactory::create_counter_task(1, nullptr);
```
在task的回调里判断一下，当前series里是否还有后续任务，如果没有，就放入一个counter。counter可以用带名字的counter来全局技术，避免自己保存counter task指针的麻烦～
```cpp
void callback(MyTask *task)
{
    if (/* series里没有其他任务了*/ )
    {
        WFCounterTask *counter = WFTaskFactory::create_counter_task("COUNTER_A", 1, nullptr);
        series->push_back(counter);
    }
    ...
}
```
然后每个想往series里放的task，放入的时候都配合打开一下开关；
```cpp
series->push_back(my_task);
WFTaskFactory::count_by_name("COUNTER_A");
```
就可以做到task本身被顺序执行，又能长期使用同一个series的做法了～麻烦看看是否符合当前的需求，如果还有其他用法，欢迎多多交流～

**Comment by Barenboim** [comment]
这个需求挺常见的，其实你需要的就是一个不会自动结束的series，你可以向这个series里不断的增加任务，这样子这些任务就可以顺序的被执行。方法是第次push_back任务时，除了push_back当前任务，还需要再push_back一个目标值为1的counter任务。接下来，上一个counter打开，让当前任务可以被拉起。counter相当于一个塞子，用于堵住series，让series不会自动结束。
其实我们series的push和pop操作都是加锁的，也就是为了用于可以实现这个功能。
@holmes1412 你的示例代码在callback里push_back(counter)应该是不对的。我一会写个block series的示例。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 在callback里面push计数器有什么不对的地方吗

**Comment by Barenboim** [comment]
大概写了一下代码，没有测，方法没问题：
~~~cpp
#include <string>
#include <mutex>
#include "workflow/Workflow.h"
#include "workflow/WFTaskFactory.h"

class BlockSeries
{
public:
	BlockSeries(SubTask *first, const std::string& name) :
		counter_name(name)
	{
		WFCounterTask *counter;
		this->series = Workflow::create_series_work(first, nullptr);
		counter = WFTaskFactory::create_counter_task(counter_name, 1, nullptr);
		this->series->push_back(counter);
	}

	~BlockSeries()
	{
		WFTaskFactory::count_by_name(counter_name);
	}	

	void push_back(SubTask *task)
	{
		WFCounterTask *counter;
		this->mutex.lock();
		counter = WFTaskFactory::create_counter_task(counter_name, 1, nullptr);
		this->series->push_back(task);
		this->series->push_back(counter);
		this->mutex.unlock();
		WFTaskFactory::count_by_name(counter_name);
	}

private:
	SeriesWork *series;
	std::string counter_name;
	std::mutex mutex;
};
~~~

**Comment by holmes1412** [comment]
@Barenboim @MaybeShewill-CV 我是在执行的task的callback里检查series的状态并push_back(counter)哈

**Comment by Barenboim** [comment]
> @Barenboim @MaybeShewill-CV 我是在执行的task的callback里检查series的状态并push_back(counter)哈

这个在并发访问的时候就有问题了。

**Comment by holmes1412** [comment]
> > @Barenboim @MaybeShewill-CV 我是在执行的task的callback里检查series的状态并push_back(counter)哈
> 
> 这个在并发访问的时候就有问题了。

这个用户自行维护series的状态吧，比如atomic记录task个数，第一个减到0的人往里塞counter就可以了，交给用户做。

**Comment by lordoffox** [comment]
非常感谢回答。

**Comment by Barenboim** [comment]
现在这个功能也可以用WFResourcePool来实现。
https://github.com/sogou/workflow/blob/master/docs/about-conditional.md

**Comment by Barenboim** [comment]
你自己试一下吧。我倒不觉得你真的需要这么复杂的东西。



> > 大概写了一下代码，没有测，方法没问题：
> > ```c++
> > #include <string>
> > #include <mutex>
> > #include "workflow/Workflow.h"
> > #include "workflow/WFTaskFactory.h"
> > 
> > class BlockSeries
> > {
> > public:
> > 	BlockSeries(SubTask *first, const std::string& name) :
> > 		counter_name(name)
> > 	{
> > 		WFCounterTask *counter;
> > 		this->series = Workflow::create_series_work(first, nullptr);
> > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > 		this->series->push_back(counter);
> > 	}
> > 
> > 	~BlockSeries()
> > 	{
> > 		// 假设用户已经调用过start()
> > 		WFTaskFactory::count_by_name(this->counter_name);
> > 	}
> > 
> >         void start()
> >         {
> >                 this->series->start();
> >         }
> > 
> > 	void push_back(SubTask *task)
> > 	{
> > 		WFCounterTask *counter;
> > 		this->mutex.lock();
> > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > 		this->series->push_back(task);
> > 		this->series->push_back(counter);
> > 		this->mutex.unlock();
> >                 // 这个counter_by_name打开的是上一个push_back添加的counter。
> > 		WFTaskFactory::count_by_name(this->counter_name);
> > 	}
> > 
> > private:
> > 	SeriesWork *series;
> > 	std::string counter_name;
> > 	std::mutex mutex;
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其中name是一个全局唯一的名字，用来给counter起名的。series没有callback，如果需要的话可以自己改一下代码。
> 
> 太好了，正好现在需要这个，大概理解了下，
> 
> 第一步：这个start第一次调用就是为了开始运行没有任务不自动退出，固定的名字和固定的值1 counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr); 第二步： 这一段是添加新任务，且也是为了保证没有任务的时候不退出 this->series->push_back(task); this->series->push_back(counter); 第三步：这个其实是为了把第一步的阻塞塞子去掉，好让第二步的task任务得到执行 WFTaskFactory::count_by_name(this->counter_name);
> 
> 可以这么理解吗，大佬

**Comment by zxyAcmen** [comment]
> 你自己试一下吧。我倒不觉得你真的需要这么复杂的东西。
> 
> > > 大概写了一下代码，没有测，方法没问题：
> > > ```c++
> > > #include <string>
> > > #include <mutex>
> > > #include "workflow/Workflow.h"
> > > #include "workflow/WFTaskFactory.h"
> > > 
> > > class BlockSeries
> > > {
> > > public:
> > > 	BlockSeries(SubTask *first, const std::string& name) :
> > > 		counter_name(name)
> > > 	{
> > > 		WFCounterTask *counter;
> > > 		this->series = Workflow::create_series_work(first, nullptr);
> > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > 		this->series->push_back(counter);
> > > 	}
> > > 
> > > 	~BlockSeries()
> > > 	{
> > > 		// 假设用户已经调用过start()
> > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > 	}
> > > 
> > >         void start()
> > >         {
> > >                 this->series->start();
> > >         }
> > > 
> > > 	void push_back(SubTask *task)
> > > 	{
> > > 		WFCounterTask *counter;
> > > 		this->mutex.lock();
> > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > 		this->series->push_back(task);
> > > 		this->series->push_back(counter);
> > > 		this->mutex.unlock();
> > >                 // 这个counter_by_name打开的是上一个push_back添加的counter。
> > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > 	}
> > > 
> > > private:
> > > 	SeriesWork *series;
> > > 	std::string counter_name;
> > > 	std::mutex mutex;
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 其中name是一个全局唯一的名字，用来给counter起名的。series没有callback，如果需要的话可以自己改一下代码。
> > 
> > 
> > 太好了，正好现在需要这个，大概理解了下，
> > 第一步：这个start第一次调用就是为了开始运行没有任务不自动退出，固定的名字和固定的值1 counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr); 第二步： 这一段是添加新任务，且也是为了保证没有任务的时候不退出 this->series->push_back(task); this->series->push_back(counter); 第三步：这个其实是为了把第一步的阻塞塞子去掉，好让第二步的task任务得到执行 WFTaskFactory::count_by_name(this->counter_name);
> > 可以这么理解吗，大佬

我感觉你在看不起我(哈哈，开玩笑哈)，现在就是需要这个，现在业务有个状态需要维护，然后要根据各种处理结果来维护，这个正合适的，本来用同步编程，我取数据放到内存，调用hredis 操作的话这个就简单了，这不向大佬们学习使用异步嘛。

**Comment by Barenboim** [comment]
> > 你自己试一下吧。我倒不觉得你真的需要这么复杂的东西。
> > > > 大概写了一下代码，没有测，方法没问题：
> > > > ```c++
> > > > #include <string>
> > > > #include <mutex>
> > > > #include "workflow/Workflow.h"
> > > > #include "workflow/WFTaskFactory.h"
> > > > 
> > > > class BlockSeries
> > > > {
> > > > public:
> > > > 	BlockSeries(SubTask *first, const std::string& name) :
> > > > 		counter_name(name)
> > > > 	{
> > > > 		WFCounterTask *counter;
> > > > 		this->series = Workflow::create_series_work(first, nullptr);
> > > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > > 		this->series->push_back(counter);
> > > > 	}
> > > > 
> > > > 	~BlockSeries()
> > > > 	{
> > > > 		// 假设用户已经调用过start()
> > > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > > 	}
> > > > 
> > > >         void start()
> > > >         {
> > > >                 this->series->start();
> > > >         }
> > > > 
> > > > 	void push_back(SubTask *task)
> > > > 	{
> > > > 		WFCounterTask *counter;
> > > > 		this->mutex.lock();
> > > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > > 		this->series->push_back(task);
> > > > 		this->series->push_back(counter);
> > > > 		this->mutex.unlock();
> > > >                 // 这个counter_by_name打开的是上一个push_back添加的counter。
> > > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > > 	}
> > > > 
> > > > private:
> > > > 	SeriesWork *series;
> > > > 	std::string counter_name;
> > > > 	std::mutex mutex;
> > > > };
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 其中name是一个全局唯一的名字，用来给counter起名的。series没有callback，如果需要的话可以自己改一下代码。
> > > 
> > > 
> > > 太好了，正好现在需要这个，大概理解了下，
> > > 第一步：这个start第一次调用就是为了开始运行没有任务不自动退出，固定的名字和固定的值1 counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr); 第二步： 这一段是添加新任务，且也是为了保证没有任务的时候不退出 this->series->push_back(task); this->series->push_back(counter); 第三步：这个其实是为了把第一步的阻塞塞子去掉，好让第二步的task任务得到执行 WFTaskFactory::count_by_name(this->counter_name);
> > > 可以这么理解吗，大佬
> 
> 我感觉你在看不起我(哈哈，开玩笑哈)，现在就是需要这个，现在业务有个状态需要维护，然后要根据各种处理结果来维护，这个正合适的，本来用同步编程，我取数据放到内存，调用hredis 操作的话这个就简单了，这不向大佬们学习使用异步嘛。

没有看不起，只是希望你多做一些实验，有可能问题没有你想的那么复杂。

从你刚才贴的一些代码，我觉得你还是没有看我们的文档和示例。

**Comment by zxyAcmen** [comment]
恩恩，我先把你这个blackseries先用上吧，我感觉很适合我的这个的

**Comment by zxyAcmen** [comment]
> > > 你自己试一下吧。我倒不觉得你真的需要这么复杂的东西。
> > > > > 大概写了一下代码，没有测，方法没问题：
> > > > > ```c++
> > > > > #include <string>
> > > > > #include <mutex>
> > > > > #include "workflow/Workflow.h"
> > > > > #include "workflow/WFTaskFactory.h"
> > > > > 
> > > > > class BlockSeries
> > > > > {
> > > > > public:
> > > > > 	BlockSeries(SubTask *first, const std::string& name) :
> > > > > 		counter_name(name)
> > > > > 	{
> > > > > 		WFCounterTask *counter;
> > > > > 		this->series = Workflow::create_series_work(first, nullptr);
> > > > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > > > 		this->series->push_back(counter);
> > > > > 	}
> > > > > 
> > > > > 	~BlockSeries()
> > > > > 	{
> > > > > 		// 假设用户已经调用过start()
> > > > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > > > 	}
> > > > > 
> > > > >         void start()
> > > > >         {
> > > > >                 this->series->start();
> > > > >         }
> > > > > 
> > > > > 	void push_back(SubTask *task)
> > > > > 	{
> > > > > 		WFCounterTask *counter;
> > > > > 		this->mutex.lock();
> > > > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > > > 		this->series->push_back(task);
> > > > > 		this->series->push_back(counter);
> > > > > 		this->mutex.unlock();
> > > > >                 // 这个counter_by_name打开的是上一个push_back添加的counter。
> > > > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > > > 	}
> > > > > 
> > > > > private:
> > > > > 	SeriesWork *series;
> > > > > 	std::string counter_name;
> > > > > 	std::mutex mutex;
> > > > > };
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 其中name是一个全局唯一的名字，用来给counter起名的。series没有callback，如果需要的话可以自己改一下代码。
> > > > 
> > > > 
> > > > 太好了，正好现在需要这个，大概理解了下，
> > > > 第一步：这个start第一次调用就是为了开始运行没有任务不自动退出，固定的名字和固定的值1 counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr); 第二步： 这一段是添加新任务，且也是为了保证没有任务的时候不退出 this->series->push_back(task); this->series->push_back(counter); 第三步：这个其实是为了把第一步的阻塞塞子去掉，好让第二步的task任务得到执行 WFTaskFactory::count_by_name(this->counter_name);
> > > > 可以这么理解吗，大佬
> > 
> > 
> > 我感觉你在看不起我(哈哈，开玩笑哈)，现在就是需要这个，现在业务有个状态需要维护，然后要根据各种处理结果来维护，这个正合适的，本来用同步编程，我取数据放到内存，调用hredis 操作的话这个就简单了，这不向大佬们学习使用异步嘛。
> 
> 没有看不起，只是希望你多做一些实验，有可能问题没有你想的那么复杂。
> 
> 从你刚才贴的一些代码，我觉得你还是没有看我们的文档和示例。

验证了下，确实不是我要的那个场景，哈哈，但是就是说，假如我有10个任务，我想感知到第10任务执行完了后，再重新执行一个任务，这种要如何做适合，都是异步的有点不知道咋搞，又不想用成员容器来保存数据记录状态这种，就是通过任务来感知，因为我不到10个任务执行完，我直接开始第11个任务的话，有可能拿到我还处理完的数据又去处理了。

**Comment by Barenboim** [comment]
> > > > 你自己试一下吧。我倒不觉得你真的需要这么复杂的东西。
> > > > > > 大概写了一下代码，没有测，方法没问题：
> > > > > > ```c++
> > > > > > #include <string>
> > > > > > #include <mutex>
> > > > > > #include "workflow/Workflow.h"
> > > > > > #include "workflow/WFTaskFactory.h"
> > > > > > 
> > > > > > class BlockSeries
> > > > > > {
> > > > > > public:
> > > > > > 	BlockSeries(SubTask *first, const std::string& name) :
> > > > > > 		counter_name(name)
> > > > > > 	{
> > > > > > 		WFCounterTask *counter;
> > > > > > 		this->series = Workflow::create_series_work(first, nullptr);
> > > > > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > > > > 		this->series->push_back(counter);
> > > > > > 	}
> > > > > > 
> > > > > > 	~BlockSeries()
> > > > > > 	{
> > > > > > 		// 假设用户已经调用过start()
> > > > > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > > > > 	}
> > > > > > 
> > > > > >         void start()
> > > > > >         {
> > > > > >                 this->series->start();
> > > > > >         }
> > > > > > 
> > > > > > 	void push_back(SubTask *task)
> > > > > > 	{
> > > > > > 		WFCounterTask *counter;
> > > > > > 		this->mutex.lock();
> > > > > > 		counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr);
> > > > > > 		this->series->push_back(task);
> > > > > > 		this->series->push_back(counter);
> > > > > > 		this->mutex.unlock();
> > > > > >                 // 这个counter_by_name打开的是上一个push_back添加的counter。
> > > > > > 		WFTaskFactory::count_by_name(this->counter_name);
> > > > > > 	}
> > > > > > 
> > > > > > private:
> > > > > > 	SeriesWork *series;
> > > > > > 	std::string counter_name;
> > > > > > 	std::mutex mutex;
> > > > > > };
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 其中name是一个全局唯一的名字，用来给counter起名的。series没有callback，如果需要的话可以自己改一下代码。
> > > > > 
> > > > > 
> > > > > 太好了，正好现在需要这个，大概理解了下，
> > > > > 第一步：这个start第一次调用就是为了开始运行没有任务不自动退出，固定的名字和固定的值1 counter = WFTaskFactory::create_counter_task(this->counter_name, 1, nullptr); 第二步： 这一段是添加新任务，且也是为了保证没有任务的时候不退出 this->series->push_back(task); this->series->push_back(counter); 第三步：这个其实是为了把第一步的阻塞塞子去掉，好让第二步的task任务得到执行 WFTaskFactory::count_by_name(this->counter_name);
> > > > > 可以这么理解吗，大佬
> > > 
> > > 
> > > 我感觉你在看不起我(哈哈，开玩笑哈)，现在就是需要这个，现在业务有个状态需要维护，然后要根据各种处理结果来维护，这个正合适的，本来用同步编程，我取数据放到内存，调用hredis 操作的话这个就简单了，这不向大佬们学习使用异步嘛。
> > 
> > 
> > 没有看不起，只是希望你多做一些实验，有可能问题没有你想的那么复杂。
> > 从你刚才贴的一些代码，我觉得你还是没有看我们的文档和示例。
> 
> 验证了下，确实不是我要的那个场景，哈哈，但是就是说，假如我有10个任务，我想感知到第10任务执行完了后，再重新执行一个任务，这种要如何做适合，都是异步的有点不知道咋搞，又不想用成员容器来保存数据记录状态这种，就是通过任务来感知，因为我不到10个任务执行完，我直接开始第11个任务的话，有可能拿到我还处理完的数据又去处理了。

那不就是在第10个任务的callback里，push_back第11个任务吗？

**Comment by zxyAcmen** [comment]
10个相同的任务，比如redis del指令，我不知道哪个是第10啊，你的意思在创建第10个的时候set_callback?

**Comment by Barenboim** [comment]
你10个并行的吗？那用我们的ParallelWork啊。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月6日(周四) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 我有一个需求，希望能动态创建多个task，又希望这些task能被顺序的执行来避免多线程竞争，该如何做。 (#301)




 
10个相同的任务，比如redis del指令，我不知道哪个是第10啊，你的意思在创建第10个的时候set_callback?

**Comment by zxyAcmen** [comment]
我知道了，有个那个user_data可以用对吧

**Comment by Barenboim** [comment]
我真不想回你的问题了。。。


我教不会你。你自己看文档吧。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月6日(周四) 晚上7:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 我有一个需求，希望能动态创建多个task，又希望这些task能被顺序的执行来避免多线程竞争，该如何做。 (#301)




 
我知道了，有个那个user_data可以用对吧

**Comment by zxyAcmen** [comment]
> 我真不想回你的问题了。。。 我教不会你。你自己看文档吧。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月6日(周四) 晚上7:46 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sogou/workflow] 我有一个需求，希望能动态创建多个task，又希望这些task能被顺序的执行来避免多线程竞争，该如何做。 (#301) 我知道了，有个那个user_data可以用对吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

别阿大哥，能者多劳嘛，那个user_data可以用了，因为我一次10个数据处理，会建10个任务，我在建最后一个任务绑定一下user_data,待任务执行完回到call_back的时候判断一下就行了

**Comment by Barenboim** [comment]
> > 我真不想回你的问题了。。。 我教不会你。你自己看文档吧。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年6月6日(周四) 晚上7:46 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [sogou/workflow] 我有一个需求，希望能动态创建多个task，又希望这些task能被顺序的执行来避免多线程竞争，该如何做。 (#301) 我知道了，有个那个user_data可以用对吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 别阿大哥，能者多劳嘛，那个user_data可以用了，因为我一次10个数据处理，会建10个任务，我在建最后一个任务绑定一下user_data,待任务执行完回到call_back的时候判断一下就行了

不要再提问了。或者你去找个同步框架用吧。
