### ISSUE TITLE
problem about waitfor funtion can not work repeatly

### ISSUE THREAD

**Issue by xiaogenbanpk** [sogou/workflow#303]
hi, I meet a problem that when I want run a workflow repeatly by conditions.
if there exists waitfor and publishevent function , the waitfor function can only work properply once.
the code seems like below:
//the main proc  
 while (flag)  {
                if (waitflag)
                {
                host.PublishEvent("MyEvent", "0", "hello");
                }
}
....

//the workflow define
......
 .StartWith<Fluent>()
                    .Input(step => step.Input, data => data["InFlu"])
                    .Output((step, data) => data["OutFlu"] = step.Output)
                   .WaitFor("MyEvent" ,data => "0")
 .Then<Fluent2>()
so,is there any solution about this.

Tks.

**Comment by Barenboim** [comment]
Typically workflow applications do not wait for completion of tasks, but use callbacks instead. 
But I think you can implement the semantics of "WaitFor" by using [WFFuture](https://github.com/sogou/workflow/blob/master/src/manager/WFFuture.h).

**Comment by holmes1412** [comment]
Here`s some additional opinion: 

Because every logic in workflow is task, so, if you want to do things repeatedly, you should run task repeatedly. 

And WaitGroup can help you to do the wait flag.
```cpp
// the main proc
int main()
{
    WFFacilities::WaitGroup wait_group(1);

    auto *task = create_publish_event_task(public_event_callback);
    __set_input(step.Input, task->get_req());
    task->start();
    wait_group.wait();
    ...
}
```

```cpp
// the workflow callback logic define
void public_event_callback(PublicEventTask *task)
{
    if (data >= 0) // your condition
    {
        __get_output(task->get_resp(), step.Output);
        wait_group.done();
    }
    else
    {
        auto *next_task = create_publish_event_task(public_event_callback);
        series_of(this)->push_back(next_task); // repeatedly
    }
}
```

``WaitGroup``is implemented by ``WFFuture``, which means you may also implement your ``wait_for()`` and ``get()`` base on ``WFFuture``.

**Comment by xiaogenbanpk** [comment]
Tks.
