### ISSUE TITLE
How can I build get a dynamic lib such as libworkflow.so ?

### ISSUE THREAD

**Issue by GeorgeXia1828** [sogou/workflow#313]
I run the cmake in workflow, I get libworkflow.a and libworkflow.so, but the libworkflow.so is a txt file. How can i get a real dynamic lib?

**Comment by holmes1412** [comment]
@GeorgeXia1828 Of course~   You only need to change **STATIC** into **SHARED** in cmake.

You can copy the following as a file ``dynamic.patch`` :
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 62d3d39..9a98324 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -24,7 +24,7 @@ add_dependencies(server LINK_HEADERS)
 add_dependencies(client LINK_HEADERS)
 
 add_library(
-       ${PROJECT_NAME} STATIC
+       ${PROJECT_NAME} SHARED
        $<TARGET_OBJECTS:kernel>
        $<TARGET_OBJECTS:util>
        $<TARGET_OBJECTS:manager>
```
And patch into workflow with this cmd:
``patch -p 1 < dynamic.patch``

**Comment by GeorgeXia1828** [comment]
@holmes1412 thanks for your quick reply !!
I tried the diff for src/CMakeLists.txt, for the very line. but，steel the libworkflow.so is 76bytes.

my steps:
git clone xx
cd workflow && modify src/CMakeLists.txt for the very line you diff.
mkdir bld && cd bld && cmake .. && make 
then I found the libworkflow.so is 76 bytes.

-----

however I delete the file something, it seem works out.

`cmake_minimum_required(VERSION 3.6)

find_package(OpenSSL REQUIRED)
include_directories(${OPENSSL_INCLUDE_DIR} ${INC_DIR}/workflow)

add_subdirectory(kernel)
add_subdirectory(util)
add_subdirectory(manager)
add_subdirectory(algorithm)
add_subdirectory(protocol)
add_subdirectory(factory)
add_subdirectory(nameservice)
add_subdirectory(server)
add_subdirectory(client)

add_dependencies(kernel LINK_HEADERS)
add_dependencies(util LINK_HEADERS)
add_dependencies(manager LINK_HEADERS)
add_dependencies(algorithm LINK_HEADERS)
add_dependencies(protocol LINK_HEADERS)
add_dependencies(factory LINK_HEADERS)
add_dependencies(nameservice LINK_HEADERS)
add_dependencies(server LINK_HEADERS)
add_dependencies(client LINK_HEADERS)

add_library(
    ${PROJECT_NAME} SHARED
	$<TARGET_OBJECTS:kernel>
	$<TARGET_OBJECTS:util>
	$<TARGET_OBJECTS:manager>
	$<TARGET_OBJECTS:algorithm>
	$<TARGET_OBJECTS:protocol>
	$<TARGET_OBJECTS:factory>
	$<TARGET_OBJECTS:nameservice>
	$<TARGET_OBJECTS:server>
	$<TARGET_OBJECTS:client>
)`

**Comment by holmes1412** [comment]
@GeorgeXia1828 Sorry, forgot to let you remove the origin txt, please try this patch:
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 62d3d39..d9eb2aa 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -24,7 +24,7 @@ add_dependencies(server LINK_HEADERS)
 add_dependencies(client LINK_HEADERS)
 
 add_library(
-       ${PROJECT_NAME} STATIC
+       ${PROJECT_NAME} SHARED
        $<TARGET_OBJECTS:kernel>
        $<TARGET_OBJECTS:util>
        $<TARGET_OBJECTS:manager>
@@ -57,17 +57,6 @@ install(
        COMPONENT devel
 )
 
-if (APPLE)
-       set(LIBSO ${LIB_DIR}/libworkflow.a)
-else ()
-       set(LIBSO ${LIB_DIR}/libworkflow.so)
-       add_custom_target(
-               SCRIPT_SHARED_LIB ALL
-               COMMAND ${CMAKE_COMMAND} -E echo 'GROUP ( libworkflow.a AS_NEEDED ( libpthread.so libssl.so libcrypto.so ) ) ' > $
-       )
-       add_dependencies(SCRIPT_SHARED_LIB ${PROJECT_NAME})
-endif ()
-
 if (KAFKA STREQUAL "y")
        if (APPLE)
                set(LIBSOKAFKA ${LIB_DIR}/libwfkafka.a)
```

**Comment by holmes1412** [comment]
The reason why we wrote a ``libworkflow.so`` as a txt file is that, we wanted to build a static library ``libworkflow.a`` inside our company, and keep the ``libworkflow.so`` for our developers to link at the same time. 
This txt is a similar usage as **libstdc++**, which can link all your libraries through the txt file:
```
GROUP ( libworkflow.a AS_NEEDED ( libpthread.so libssl.so libcrypto.so ) ) 
```
This usage is  very special and worth sharing~ And if you still have any other problem please let me know.

**Comment by GeorgeXia1828** [comment]
@holmes1412 
thx so much, now it's running now, i will try it. When I saw the txt file, I guess it's something magic, haha,
