### ISSUE TITLE
redis-cli 建立连接的过程是怎样的

### ISSUE THREAD

**Issue by dorothy00dd2** [sogou/workflow#330]
看了下代码，Communitor.cc 里有connect系统调用，通过WFResolverTask调用到这里，每次series start时，会加入一个router，router负责建立连接吗？
request 是在什么时机被解析的呢？ 
能不能说下完成的请求流程。谢谢～

**Comment by Barenboim** [comment]
你好。router是负责dns解析或upstream查找的，和连接没有关系。所有连接管理都在Communicator里。
关于redis的建立连接的过程，可以看一下FAQ里的这个问题：
(为什么使用redis client时无需先建立连接)[https://github.com/sogou/workflow/issues/170]，以及后面关于连接复用规则的问题。
