### ISSUE TITLE
尝试HTTP_SERVER没编译成功

### ISSUE THREAD

**Issue by zsinba** [sogou/workflow#343]
![image](https://user-images.githubusercontent.com/890157/115644961-10d56b80-a352-11eb-9bbf-18fc2f89a9ba.png)

./configure
./make -j20
make install

![image](https://user-images.githubusercontent.com/890157/115644992-22b70e80-a352-11eb-8e4a-8e9071168ae3.png)

页面上的例子,没编译通过. 
wsl2.0版本.

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/115645066-48dcae80-a352-11eb-9738-cd194935a90f.png)

G++ GCC都没能成功.

**Comment by Barenboim** [comment]
你先到tutorial目录里make，用实例里的代码吧。
~~~sh
cd workflow
make
cd tutorial
make
~~~
直接g++里起码需要-l指定链接库啊。

**Comment by zsinba** [comment]
谢谢.
