### ISSUE TITLE
post请求结束，程序crash，代码调试挂在dispatch中的subtask_done中，麻烦请问问题在哪？

### ISSUE THREAD

**Issue by Weili17** [sogou/workflow#346]
void process(WFHttpTask *task) {
    // test post request
    if (strcmp(task->get_req()->get_request_uri(), "/post") == 0) {
        static std::atomic<int> flag;
        server.shutdown();
        cout << "the method is:" <<  task->get_req()->get_method() << "the http_version is: " <<
             task->get_req()->get_http_version() << endl;
        task->get_req();
        task->get_req()->set_method("POST");
        task->get_req()->get_method();
        cout << "the method is:" <<  task->get_req()->get_method() << "the http_version is: " <<
             task->get_req()->get_http_version() << endl;
        const void** body;
        size_t* size;
        bool getBody = task->get_req()->get_parsed_body(body, size);
        std::cout << "get body result is: " << getBody << " body: " << (string) (static_cast<const char*>(*body)) << " size: " << *size << endl;
        task->get_resp()->append_output_body("{json : 2}");
        return;
    }
    return;
}
int main(int argc, char *argv[])
{
    if (server.start(8888) == 0)
        server.wait_finish();
    return 0;
}
程序打印日志：
the method is:POSTthe http_version is: HTTP/1.1
the method is:POSTthe http_version is: HTTP/1.1
get body result is: 1 body: first=1&second=2 size: 16

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

如果不调用task->get_req()->get_parsed_body(body, size);
程序返回正常结果

**Comment by Barenboim** [comment]
你的get_parsed_body用法明显是错的啊。
应该是：
~~~cpp
{
    const void *body;
    size_t size;
    task->get_req()->get_parsed_body(&body, &size);
    ....
}
~~~
