### ISSUE TITLE
支持Postgres

### ISSUE THREAD

**Issue by ltnil** [sogou/workflow#348]
可否支持Postgres数据库

**Comment by Barenboim** [comment]
哈哈，我也想多支持几种数据库，但postgres公司里没有需求，而且我们每种协议的实现都是个大工程，现在真没有人力。
其实协议都可以以插件形式加入进来，类似现在的kafka客户端，不使用的话都无需编译。看看以后有没有用户来帮我们开发postgres插件。不过真的每种协议开发难度都不小。
