### ISSUE TITLE
请问有群可以联系吗

### ISSUE THREAD

**Issue by jovany-wang** [sogou/workflow#35]
刚接触，通过现有文档可能有一些问题还不太清楚。

**Comment by holmes1412** [comment]
@jovany-wang 你好～感谢关注，我们刚刚组建了一个QQ群，可以加：618773193
如果需要验证可以说明一下是workflow。
我们项目刚开源，希望与大家多多交流～

附上二维码：

![39752468-C477-4608-A1FC-96B6070DCC10](https://user-images.githubusercontent.com/1880011/92300953-e9cc5400-ef91-11ea-82f5-4cf3174cd851.jpeg)

**Comment by NeilStone123** [comment]
有没有微信群啊

**Comment by holmes1412** [comment]
@NeilStone123 你好，目前只有QQ群～对srpc感兴趣的话也可以加，与workflow是同一个开发者群。

**Comment by Mervyen** [comment]
请问一下会有TG群吗？

**Comment by holmes1412** [comment]
> 请问一下会有TG群吗？

暂时没有～有问题可以发issue，优先级会比加群高～^_^
