### ISSUE TITLE
如何创建一个https的客户端任务呢？

### ISSUE THREAD

**Issue by SimoAutumn** [sogou/workflow#350]
请问，如何创建一个https的客户端任务呢？是需要证书文件和密钥文件的吧，如何用workflow来发起请求呢

**Comment by Barenboim** [comment]
WFTaskFactory::create_http_task("https://www....", ...);
不用秘钥的。

**Comment by SimoAutumn** [comment]
大概明白了，就是框架已经把ssl/tls相关的细节封装好了，上层直接调用统一的接口就行了，无需关注这些细节了。

**Comment by Barenboim** [comment]
是的。做https抓取的话，要记得我们默认是关闭TLS SNI的，这会影响极少数https站点的抓取。打开SNI的方法参考FAQ里关于部分https站点抓取失败的问题，或参考这个[issue](https://github.com/sogou/workflow/issues/307)。
