### ISSUE TITLE
如何直接使用poller模块写异步网络程序

### ISSUE THREAD

**Issue by zxyAcmen** [sogou/workflow#351]
首先感谢强大的团队以及开发者的无私分享。
说说我的需求：只是想单独的使用里面的epoll以及消息缓存机制来替换掉现有libevent库，好让自己更深入的理解网络编程以及学习牛人的思想。希望大佬们具体讲下从哪开始看或者如何快速的使用这块的功能。万分感谢！

**Comment by Barenboim** [comment]
感谢夸奖。
workflow的网络事件模块是kernel目录下的poller，这是一个可以独立使用的C语言实现的异步网络模块，支持linux下的epoll和macOS下的queue，相信可以满足一切网络程序的需求。我们以[nossl](https://github.com/sogou/workflow/tree/nossl)分枝下的[poller.h](https://github.com/sogou/workflow/blob/nossl/src/kernel/poller.h)为例：
~~~c
#ifndef _POLLER_H_
#define _POLLER_H_

#include <sys/types.h>
#include <sys/socket.h>
#include <time.h>

typedef struct __poller poller_t;
typedef struct __poller_message poller_message_t;

struct __poller_message
{
	int (*append)(const void *, size_t *, poller_message_t *);
	char data[0];
};

struct poller_data
{
#define PD_OP_READ			1
#define PD_OP_WRITE			2
#define PD_OP_LISTEN		3
#define PD_OP_CONNECT		4
#define PD_OP_EVENT			8
#define PD_OP_NOTIFY		9
#define PD_OP_TIMER			10
	short operation;
	unsigned short iovcnt;
	int fd;
	union
	{
		void *(*accept)(const struct sockaddr *, socklen_t, int, void *);
		void *(*event)(void *);
		void *(*notify)(void *, void *);
	};
	void *context;
	union
	{
		poller_message_t *message;
		struct iovec *write_iov;
		void *result;
	};
};

struct poller_result
{
#define PR_ST_SUCCESS		0
#define PR_ST_FINISHED		1
#define PR_ST_ERROR			2
#define PR_ST_DELETED		3
#define PR_ST_MODIFIED		4
#define PR_ST_STOPPED		5
	int state;
	int error;
	struct poller_data data;
	/* In callback, spaces of six pointers are available from here. */
};

struct poller_params
{
	size_t max_open_files;
	poller_message_t *(*create_message)(void *);
	int (*partial_written)(size_t, void *);
	void (*callback)(struct poller_result *, void *);
	void *context;
};

#ifdef __cplusplus
extern "C"
{
#endif

poller_t *poller_create(const struct poller_params *params);
int poller_start(poller_t *poller);
int poller_add(const struct poller_data *data, int timeout, poller_t *poller);
int poller_del(int fd, poller_t *poller);
int poller_mod(const struct poller_data *data, int timeout, poller_t *poller);
int poller_set_timeout(int fd, int timeout, poller_t *poller);
int poller_add_timer(const struct timespec *value, void *context,
					 poller_t *poller);
void poller_stop(poller_t *poller);
void poller_destroy(poller_t *poller);

#ifdef __cplusplus
}
#endif

#endif
~~~
### poller_t *poller_create(const struct poller_params *params);
产生一个poller对象。需要传一个params参数，包含如下的域：
* size_t max_open_files：如果为0则默认为65536
* poller_message_t *(*create_message)(void *)：发生读事件时创建一条消息。poller既不是proactor也不是reactor，而是以完整的一条消息为交互单位。
  * create_message的void *参数来自于struct poller_data里的void *context（注意不是poller_params里的context）。
  * poller_message_t是一条完整的消息，这是一个变长结构体，需要而且只需要实现append。
    * append的参数const void *buf和size_t *size分别是收到的数据以及数据的长度。如果buf内容跨越一条消息（所谓tcp粘包），可通过修改*size表示这条消息消费的字节数，而剩下的数为被下一条消息消费。
    * append返回1表示本条消息已经完整（callback会得到一次SUCCESS状态），返回0表示需要继续传输，返回-1表示失败。失败时必须填写的errno，用于之后的失败返回。
  * partial_written是写的时候表示写成功了一部分数据，一般用来更新下一个超时。
  * callback：用于返回结果，参数是一个poller_result和context。
  * context：callback里的void *参数。
### int poller_start(poller_t *poller);
待续...

**Comment by Lisprez** [comment]
谢老师, 我现在将我的问题陈述如下:

1. 在__poller_handle_read函数中已经调用了read, 这是已经将数据都读入了缓冲区了
2. 后面在循环里调用__poller_append_message, 我的理解是在对收到的数据进行分割, 所以这期间还调用了create_message函数
而我比较困惑的是, 在create_message函数里又调用了create_service_session这个函数, 到这里我就看不明白了, 在这之后就是下面的代码:
```c
        session = entry->session;
	session->in = session->message_in();
	if (session->in)
	{
		session->in->poller_message_t::append = Communicator::append;
		session->in->entry = entry;
	}

	return session->in;
```
好像就是直接知道应该如何划分read收到的数据了一样, 我是没有看明白, 中间没有串通

请谢老师指点

**Comment by Barenboim** [comment]
> 谢老师, 我现在将我的问题陈述如下:
> 
> 1. 在__poller_handle_read函数中已经调用了read, 这是已经将数据都读入了缓冲区了
> 2. 后面在循环里调用__poller_append_message, 我的理解是在对收到的数据进行分割, 所以这期间还调用了create_message函数
>    而我比较困惑的是, 在create_message函数里又调用了create_service_session这个函数, 到这里我就看不明白了, 在这之后就是下面的代码:
> 
> ```c
>         session = entry->session;
> 	session->in = session->message_in();
> 	if (session->in)
> 	{
> 		session->in->poller_message_t::append = Communicator::append;
> 		session->in->entry = entry;
> 	}
> 
> 	return session->in;
> ```
> 
> 好像就是直接知道应该如何划分read收到的数据了一样, 我是没有看明白, 中间没有串通
> 
> 请谢老师指点

create_service_session是Communicator层的函数。这个函数返回一个session，再通过session的虚函数message_in产生一个poller_message_t类型的消息。如何划分（反序列化）read收到的数据，是由message_in返回的消息决定的。这个地方是server在接收一个client发过来的request。
poller和Communicator两个层次最好不要混在一起看，理解poller提供的操作元语，再看Communicator是如何使用的。目前Communicator层强行吧poller的pipeline功能简化成reqest->response，poller本身提供的功能远比Communicator强大。

**Comment by Lisprez** [comment]
> > 谢老师, 我现在将我的问题陈述如下:
> > 
> > 1. 在__poller_handle_read函数中已经调用了read, 这是已经将数据都读入了缓冲区了
> > 2. 后面在循环里调用__poller_append_message, 我的理解是在对收到的数据进行分割, 所以这期间还调用了create_message函数
> >    而我比较困惑的是, 在create_message函数里又调用了create_service_session这个函数, 到这里我就看不明白了, 在这之后就是下面的代码:
> > 
> > ```c
> >         session = entry->session;
> > 	session->in = session->message_in();
> > 	if (session->in)
> > 	{
> > 		session->in->poller_message_t::append = Communicator::append;
> > 		session->in->entry = entry;
> > 	}
> > 
> > 	return session->in;
> > ```
> > 
> > 
> > 好像就是直接知道应该如何划分read收到的数据了一样, 我是没有看明白, 中间没有串通
> > 请谢老师指点
> 
> create_service_session是Communicator层的函数。这个函数返回一个session，再通过session的虚函数message_in产生一个poller_message_t类型的消息。如何划分（反序列化）read收到的数据，是由message_in返回的消息决定的。这个地方是server在接收一个client发过来的request。
> poller和Communicator两个层次最好不要混在一起看，理解poller提供的操作元语，再看Communicator是如何使用的。目前Communicator层强行吧poller的pipeline功能简化成reqest->response，poller本身提供的功能远比Communicator强大。

由于我的脑子里并没有一个顶层架构的大概，所以我只能跟着函数调用，主线就是epoll的那三个函数，在这个过程中也确实被绕的比较晕
