### ISSUE TITLE
增加了一个WFGraphTask建立有向无环图的示例

### ISSUE THREAD

**Issue by Barenboim** [sogou/workflow#355]
tutorial里增加了一个用WFGraphTask建立DAG的示例。简单建立一个图，先发起一个timer task进行一秒的等待，再启动两个http抓取，最后的go_task打印http抓取的一些信息。
这个示例其实可以用串并联来实现，只是为了演示怎么建立一个依赖关系更加复杂的有向无环图。
示例代码：[https://github.com/sogou/workflow/blob/master/tutorial/tutorial-11-graph_task.cc](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-11-graph_task.cc)

**Comment by MaybeShewill-CV** [comment]
@Barenboim 请问简单的串联任务应该也可以用DAG的这种方式组织吧，感觉这种方式代码逻辑看着更清晰点。性能上和普通的串联任务有差异嘛？

**Comment by Barenboim** [comment]
后端服务器开发的话，大多数场景都是串并联。串并联有个好处是可以特别的动态，上一个结束了再决定做什么，数据传递也比较方便。
我们现在这个DAG方法，可能用在并行计算场景比较好，整个graph启动前是先建好的，没有办法动态加节点。要给graph增加动态性可以配合WFDynamicTask使用。另外graph也是一种task，可以无限套娃。不过一般的网络应用里，目前这个还是不太方便。大家看需求用吧。

**Comment by fumihwh** [comment]
请问创建DAG的时候会不会最后有一个拓扑排序的过程？
```
/* Build the graph */
a-->b;	
a-->c;	
b-->d;	
c-->d;
```
以上的代码如果改写成如下是否最终等价
```
/* Build the graph */
b-->d;	
c-->d;
a-->b;	
a-->c;	
```
谢谢。

**Comment by Barenboim** [comment]
等价的！
还可以写成：
a-->b-->d;
a-->c-->d;

**Comment by fumihwh** [comment]
@Barenboim 
谢谢回答，所以内部其实会有一个拓扑排序的处理？

**Comment by Barenboim** [comment]
按照我们的方法，没有排序的过程。或者说运行过程就是在排序？

**Comment by fumihwh** [comment]
@Barenboim 
难道是动态的去寻找下一个节点么？那起始节点如何确定的呢？

**Comment by Barenboim** [comment]
原理是这样：
每个节点都包含一个计数器，计数器的目标值就是节点入度。
每个节点执行完成，就count一下它后继节点的计数器，达到目标值了，计数器调起它对应的节点。
而所有的计数器一开始都被放入一个大的并行任务里，graph启动时都一起启动，这时那些入度为0的节点就直接调起了。
运行过程其实包含了一个拓扑排序。但任务都是异步执行，所以不保证深度优先或广度优先，有随机性（偏向广度）。

**Comment by fumihwh** [comment]
@Barenboim 了解了～谢谢
