### ISSUE TITLE
如何用workflow的httptask 发送一个post请求，来用于访问Restful的服务器

### ISSUE THREAD

**Issue by boookc** [sogou/workflow#356]
如何用workflow的httptask 发送一个post请求，来用于访问Restful的服务器
看例子好像是get方式的请求，暂时在HttpRequest类中没有找到相应的方法
比如用curl命令发一个post请求： curl -X POST http://ip:port/func  -F 'file=@"123.jpg"'  -F "rotate=true"

**Comment by Barenboim** [comment]
HttpTask *task = create_http_task(...);
task->get_req()->set_method("POST");

**Comment by boookc** [comment]
> WFHttpTask *task = create_http_task(...);
> task->get_req()->set_method("POST");
> 如果要读取本地文件，可以配合WFFileIOTask。

大佬，能否帮忙写个读取本地文件，放到httptask post请求中的 简单demo

**Comment by Barenboim** [comment]
这个很简单啊，你可以参考一下[http_file_server](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-09-http_file_server.cc)这个示例，无非就是在FileIOTask的callback里，创建一个http POST任务。大概长这样：
~~~cpp
void http_callback(WFHttpTask *http_task)
{
    free(http_task->user_data);
    // ...
}

void fileio_callback(WFFileIOTask *task)
{
    FileIOArgs *args = task->get_args();

    close(args->fd);
    if (task->get_state() != WFT_STATE_SUCCESS)
    {
        free(args->buf);
        return;
    }

    WFHttpTask *http_task = WFTaskFactory::create_http_task(..., http_callback);
    http_task->get_req()->set_method("POST");
    http_task->get_req()->append_output_body_nocopy(args->buf, args->count); /* nocopy */
    http_task->user_data = args->buf; /* To free. */
    **task << http_task;
}
~~~

**Comment by Barenboim** [comment]
@boookc

**Comment by chanchann** [comment]
An experiment code: https://github.com/chanchann/workflow_annotation/tree/main/demos/14_restful
