### ISSUE TITLE
举例一个通用使用场景

### ISSUE THREAD

**Issue by shopee-jin** [sogou/workflow#360]
服务A 同时访问 服务B, C

需求是长链接和multiplexing (云容器对资源敏感)

你们有没有提供? or, 要自己写http2库?

**Comment by Barenboim** [comment]
首先，您可以先看一看[http_proxy](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-05-http_proxy.cc)这个例子，这个例子相当于只访问服务B，把B的结果直接返回。
然后，你把proxy里产生一个http上游任务，变成产生一个parallel task，用于并行的访问B, C就可以了。因为parallel task也是一种task，把这个task串到series里，在parallel的callback（B, C都是结束之后被调用）里填写要返回的response body。关于parallel task的使用可以参考[parallel_wget](https://github.com/sogou/workflow/blob/master/tutorial/tutorial-06-parallel_wget.cc)这个例子。
连接的复用，multiplexing这些都是内部解决了的。你直接操作task就可以了。另外千万不要在process里等待任务完成。
http2不支持。

**Comment by shopee-jin** [comment]
我对于怎么使用库已经看懂了, 只是对原理设计好奇

**Comment by Barenboim** [comment]
不好意思，有个地方我刚才回复的有点问题。
我们的连接复用非常的智能，你简单写个抓取试一试就知道了。FAQ里也有关于连接管理的解释，你可以看一下。
但是我们并有没http2那种单连接上的multiplexing，这个在后端非streaming业务里，用处不大，容易有其它的问题。我们现在常用的模式是http/1.1的长连接。

**Comment by shopee-jin** [comment]
谢谢, 我先去找faq里面的连接管理

**Comment by shopee-jin** [comment]
我基本明白了, 可以close了

**Comment by Barenboim** [comment]
> 提个建议, FAQ里面默认对ip+port最多开200个http1长链接, 如果服务B,C各部署了300个容器, 服务A访问B,C, 那么就200*300+200*300

这个只是个上限，那么多容器的话，你怎么都不会把连接用满的。

**Comment by shopee-jin** [comment]
> > 提个建议, FAQ里面默认对ip+port最多开200个http1长链接, 如果服务B,C各部署了300个容器, 服务A访问B,C, 那么就200_300+200_300
> 
> 这个只是个上限，那么多容器的话，你怎么都不会把连接用满的。

大促只要有任意1s qps到达峰值, 就不再释放了, 就会一直持续大量心跳包, 这点应该是需要改进的

**Comment by Barenboim** [comment]
可能是我不太了解你的应用场景。你是希望用multiplexing的方式来减少连接的数量吗？我们现在的模式是有连接保持时间，只要在这个时间里没有被复用就会自动关闭。multiplexing确实可以减少连接数，但是大促的话会不会导致拥塞也不太好说。
你可以实际对比一下multiplexing的方案，我觉得大部分场景可能我们这个性能稳一点：）

**Comment by shopee-jin** [comment]
> 可能是我不太了解你的应用场景。你是希望用multiplexing的方式来减少连接的数量吗？我们现在的模式是有连接保持时间，只要在这个时间里没有被复用就会自动关闭。multiplexing确实可以减少连接数，但是大促的话会不会导致拥塞也不太好说。
> 你可以实际对比一下multiplexing的方案，我觉得大部分场景可能我们这个性能稳一点：）

哦懂了你们实现了连接池,  我以为是faq里面说max固定的

**Comment by Barenboim** [comment]
欢迎实际项目里试一试哈。
