### ISSUE TITLE
windows下，cmake+vs2015编译不过

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#370]
<img width="938" alt="屏幕截图 2021-05-18 122327" src="https://user-images.githubusercontent.com/26808449/118589885-df768100-b7d3-11eb-8dc5-f7919864b9ed.png">
我用cmake生成了工程，里面配置了openssl,在用vs2015编译库时，一直报错，看错误是winsock的冲突，配置里添加了WIN32_LEAN_AND_MEAN的宏，还是一样报错！紧急求助，最近遇到了mysql写入瓶颈的问题，想用下workflow里的mysql客户端

**Comment by Barenboim** [comment]
不好意思，需要切一下分枝，或者clone的时候指定Windows分枝。
git clone https://github.com/sogou/workflow -b windows
或者：
git clone https://github.com/sogou/workflow
cd workflow
git checkout windows

**Comment by xiaoshizijiayou** [comment]
你好，我就是下载windows分支编译的，翻了翻之前的issue,说可能是openssl版本的问题，不要使用1.0版本，使用1.1版本的即可，已经重新验证过，确实是这个问题可以编译通过了！
