### ISSUE TITLE
windows下，vcpkg编译不过

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#371]
我按照git上的编译说明操作，到一半出错，无法编译通过
<img width="711" alt="屏幕截图 2021-05-18 122550" src="https://user-images.githubusercontent.com/26808449/118590039-34b29280-b7d4-11eb-9be7-75d258359766.png">

**Comment by wasphin** [comment]
这编译器安装的有问题吧，看提示是检测编译器失败了，和 workflow 没关系。
