### ISSUE TITLE
Windows VS 2015编译的库后，编译mysql demo错误

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#372]
库好不容易编译过了，demo又跑不通了，我都快哭了
<img width="777" alt="屏幕截图 2021-05-18 160619" src="https://user-images.githubusercontent.com/26808449/118615337-33449280-b7f3-11eb-80a2-cf8a19ab52af.png">
<img width="790" alt="屏幕截图 2021-05-18 183729" src="https://user-images.githubusercontent.com/26808449/118637256-2b431d80-b808-11eb-8ff0-201b73f291f6.png">

**Comment by Barenboim** [comment]
就是openssl没有链接上。我让windows的同学看看哈。
@dengjunplusplus

**Comment by xiaoshizijiayou** [comment]
一开始用的1.0的openssl，库编译不过；后来换成了1.1的了，库编译过了，开始运行demo，就又报错

**Comment by Barenboim** [comment]
这个是运行时错误的话，我怀疑是链接库不匹配之类的问题。

**Comment by xiaoshizijiayou** [comment]
可能是哪个库不匹配？可以的话，我把demo工程发过去，帮忙看下

**Comment by Barenboim** [comment]
好的，需要等我们windows的同学看。
您也可以在windows下装个WSL试试我们Linux版。Linux版各方面完善一点。

**Comment by xiaoshizijiayou** [comment]
目前我们的程序都是在windows系统下的，还是优先考虑windows的

**Comment by dengjunplusplus** [comment]
@xiaoshizijiayou 需要链接ws2_32和wsock32这两个库，CMakeLists.txt中有
![image](https://user-images.githubusercontent.com/65080805/118746632-25dae700-b88b-11eb-82a5-4bcf2811e5ab.png)
