### ISSUE TITLE
workflow编译构建错误

### ISSUE THREAD

**Issue by ComixHe** [sogou/workflow#383]
在构建workflow时make报错：
as：未识别的选项 ‘--gdwarf-5’
as版本：
GNU assembler version 2.30 (x86_64-pc-linux-gnu) using BFD version (GNU Binutils) 2.30

**Comment by Barenboim** [comment]
麻烦贴一下您的操作系统和编译器相关信息。

**Comment by ComixHe** [comment]
操作系统：archlinux
内核版本：5.12.5-arch1-1
编译器gcc信息：
使用内建 specs。
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
线程模型：posix
Supported LTO compression algorithms: zlib zstd
gcc 版本 11.1.0 (GCC) 
binutils版本：2.36.1-3

**Comment by kirbyzhou** [comment]
你用的gcc-11，默认调试信息格式是gdwarf-5，需要binutils-2.35.2以上版本支持。
而你的AS的版本显示是2.30，binutils的版本显示2.36.1-3。这两个版本对不上。
建议检查一下机器上是否有多个binutils/as，以及PATH设置的路径是否正常。

**Comment by ComixHe** [comment]
已经解决，谢谢。
