### ISSUE TITLE
编译kafka_cli失败

### ISSUE THREAD

**Issue by fuzhenwen201** [sogou/workflow#390]
libwfkafka.a(KafkaMessage.cc.o):(.data.rel.ro._ZTIN8protocol15KafkaSnappySinkE[_ZTIN8protocol15KafkaSnappySinkE]+0x10): undefined reference to `typeinfo for snappy::Sink'
workflow/_lib/libwfkafka.a(KafkaMessage.cc.o):(.data.rel.ro._ZTIN8protocol17KafkaSnappySourceE[_ZTIN8protocol17KafkaSnappySourceE]+0x10): undefined reference to `typeinfo for snappy::Source'

**Comment by Barenboim** [comment]
@wzl12356

**Comment by wzl12356** [comment]
什么环境？

**Comment by fuzhenwen201** [comment]
> 什么环境？

linux

**Comment by holmes1412** [comment]
@fuzhenwen201 snappy的``Sink()``和``Source()``是**1.1.3**才加入的离散压缩接口，麻烦确认下snappy的版本，升级下再试试～

**Comment by Barenboim** [comment]
@fuzhenwen201

**Comment by fuzhenwen201** [comment]
@holmes1412 我使用的snappy是1.1.9版本的了

**Comment by Barenboim** [comment]
麻烦您尽可能的提供多一些信息方便我们排查问题。目前看起来就是没有链接上snappy的库。

**Comment by wzl12356** [comment]
> @holmes1412 我使用的snappy是1.1.9版本的了

snappy1.1.9版本编译选项有-fno-rtti，和目前的workflow不兼容，可以先尝试回滚到1.1.8或者之前的版本，我们会尽快评估workflow的修改方案。

**Comment by Barenboim** [comment]
我们刚刚给snappy提交了一个PR，因为我们觉得是1.1.9版本的一个问题，不应该有这个编译选项。

**Comment by Barenboim** [comment]
@fuzhenwen201 麻烦您再试一下，应该可以了。
