### ISSUE TITLE
串行 task 依赖前一个 task 的返回构建请求

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#393]
例如有 task1 和 task2，task2 需要依赖 task1 的返回结果来构建请求，请问除了在 task1 的 callback 里创建 task2 外还有别的什么方法能比较方便地实现这个需求么？

**Comment by Barenboim** [comment]
也可以试试动态任务。动态任务的执行行为是产生一个任务，这个任务会取代自己。
~~~cpp
using dynamic_create_t = std::function<SubTask *(WFDynamicTask *)>;

class WFTaskFactory
{
    static WFDynamicTask *create_dynamic_task(dynamic_create_t create);
};
~~~

**Comment by hiberabyss** [comment]
> 也可以试试动态任务。动态任务的执行行为是产生一个任务，这个任务会取代自己。
> 
> ```
> using dynamic_create_t = std::function<SubTask *(WFDynamicTask *)>;
> 
> class WFTaskFactory
> {
>     static WFDynamicTask *create_dynamic_task(dynamic_create_t create);
> };
> ```
> 
> 用WFDynamicTask的好处是让task1和task2彻底解耦。

也是需要在 DynamicTask 里创建新的 task ？感觉和在 task1 里创建 task2 没有太大的区别，期望的方式是类似 task2 在 task1 里注册一个 set_request 的函数，然后 task1 完成的时候调用这个 set_request 函数。

这样就可以提前创建好 task1 和 task2，把他们按期望的顺序组织起来。

**Comment by Barenboim** [comment]
嗯嗯，我可以理解你这个需求，主要就是数据传递问题。
我们目前如果预先创建好task2的话，像URL什么是改不了的。而且某些情况下，可能有task1失败就不运行task2的情况。所以现在比较通用的模式只有WFDynamicTask。task1把结果放在series context，由dynamic task去决定下一个任务怎么创建。如果不需要task2了，还可以返回一个empty task。好像可以覆盖你的需求？dynamic create函数就相当于你的set request。

**Comment by hiberabyss** [comment]
> 嗯嗯，我可以理解你这个需求，主要就是数据传递问题。
> 我们目前如果预先创建好task2的话，像URL什么是改不了的。而且某些情况下，可能有task1失败就不运行task2的情况。所以现在比较通用的模式只有WFDynamicTask。task1把结果放在series context，由dynamic task去决定下一个任务怎么创建。如果不需要task2了，还可以返回一个empty task。好像可以覆盖你的需求？dynamic create函数就相当于你的set request。

我再去详细了解下怎么来基于 WFDynamicTask 实现这个需求，感谢你的建议！
