### ISSUE TITLE
tcp/udp server

### ISSUE THREAD

**Issue by BestP2P** [sogou/workflow#40]
看例子只有http的，可以作为tcp，udp服务器吗?

**Comment by Barenboim** [comment]
可参考tutorial-10，自定义协议c/s。另外我们原生也提供了redis server，可以用来做redis协议的服务。
我们的server支持TCP，TCP-SSL，SCTP以及SCTP-SSL，但不支持UDP server。client支持UDP client。

**Comment by BestP2P** [comment]
好的，谢谢

**Comment by Barenboim** [comment]
注意一下client task里的resp，如果请求过程中如果有retry，会被析构重新构造。所以RESP类最好是RAII的。如果不是的话，也有办法，遇到实际需要可以再提issue。祝coding愉快。

**Comment by BestP2P** [comment]
好的，准备试试这个库，这个库挺不错的，易于使用，也经过搜狗的考验

**Comment by Barenboim** [comment]
关于自定义协议的client/server，简单的就像turtorial-10那么实现就可以了。默计包含了DNS和retry功能。
而功能更强的client/server实现可以非常非常复杂。
http任务里，会自动补全header，会自动计算连接保持时间，client会redirect，server会自动识别连接保证次数，精确处理Expect: 100-continue请求。
redis任务里，包含了自动登陆的交互过程，数据库id的选取。
mysql任务，包含了复杂的登陆过程，对server发来的挑战数计算，字符串和数据库选取，更有复杂的事务状态处理，并且一切都是全异步的。mysql任务的实现几乎挑战了我们任务交互功能的极限。
kafka任务是一种典型的分布式任务，交互上主要是各种meta信息的更新，路由，rebalance等。kafka协议虽然复杂，但对我们框架来讲更为友好，因为我们天生适合分布式系统的实现。
所有协议不支持pipeline server，可以实现pipeline client，但有损系统美感，目前没有提供相关实现。之后打算直接上streaming引擎。
