### ISSUE TITLE
国产机【龙芯统信UOS】编译报错若干，请求支援解决

### ISSUE THREAD

**Issue by DaoYB033** [sogou/workflow#411]
/home/username/workflow-master/src/kernel/IOService_linux.cc:89:2: error: #error endian?
 #error endian?
  ^~~~~
/home/username/workflow-master/src/kernel/IOService_linux.cc:93:23: error: ‘__pad1’ has not been declared
  PADDEDptr(void *buf, __pad1);
                       ^~~~~~
/home/username/workflow-master/src/kernel/IOService_linux.cc:93:29: error: ISO C++ forbids declaration of ‘PADDEDptr’ with no type [-fpermissive]
  PADDEDptr(void *buf, __pad1);
                             ^
/home/username/workflow-master/src/kernel/IOService_linux.cc:94:11: error: ‘nbytes’ has not been declared
  PADDEDul(nbytes, __pad2);
           ^~~~~~
/home/username/workflow-master/src/kernel/IOService_linux.cc:94:19: error: ‘__pad2’ has not been declared
  PADDEDul(nbytes, __pad2);
                   ^~~~~~
/home/username/workflow-master/src/kernel/IOService_linux.cc:94:25: error: ISO C++ forbids declaration of ‘PADDEDul’ with no type [-fpermissive]
  PADDEDul(nbytes, __pad2);
                         ^
/home/username/workflow-master/src/kernel/IOService_linux.cc:108:24: error: ‘__pad’ has not been declared
  PADDEDptr(void *data, __pad1); /* Return in the io completion event */
                        ^~~~~~
/home/username/workflow-master/src/kernel/IOService_linux.cc:108:30: error: ISO C++ forbids declaration of ‘PADDEDptr’ with no type [-fpermissive]
  PADDEDptr(void *data, __pad1); /* Return in the io completion event */
... ...
编译报错如上，请求支援解决，谢谢！

**Comment by Barenboim** [comment]
你好，非常感谢把这个问题报给我们。我们很希望可以尽快支持国产龙芯处理器。
现在的问题是我们的linux aio模块找不到龙芯处理器对应的体系结构：
~~~cpp
#if defined(__i386__) /* little endian, 32 bits */
#define PADDED(x, y)	x; unsigned y
#define PADDEDptr(x, y)	x; unsigned y
#define PADDEDul(x, y)	unsigned long x; unsigned y
#elif defined(__ia64__) || defined(__x86_64__) || defined(__alpha__)
#define PADDED(x, y)	x, y
#define PADDEDptr(x, y)	x
#define PADDEDul(x, y)	unsigned long x
#elif defined(__powerpc64__) /* big endian, 64 bits */
#define PADDED(x, y)	unsigned y; x
#define PADDEDptr(x,y)	x
#define PADDEDul(x, y)	unsigned long x
#elif defined(__PPC__)  /* big endian, 32 bits */
#define PADDED(x, y)	unsigned y; x
#define PADDEDptr(x, y)	unsigned y; x
#define PADDEDul(x, y)	unsigned y; unsigned long x
#elif defined(__s390x__) /* big endian, 64 bits */
#define PADDED(x, y)	unsigned y; x
#define PADDEDptr(x,y)	x
#define PADDEDul(x, y)	unsigned long x
#elif defined(__s390__) /* big endian, 32 bits */
#define PADDED(x, y)	unsigned y; x
#define PADDEDptr(x, y) unsigned y; x
#define PADDEDul(x, y)	unsigned y; unsigned long x
#elif defined(__arm__)
#  if defined (__ARMEB__) /* big endian, 32 bits */
#define PADDED(x, y)	unsigned y; x
#define PADDEDptr(x, y)	unsigned y; x
#define PADDEDul(x, y)	unsigned y; unsigned long x
#  else                   /* little endian, 32 bits */
#define PADDED(x, y)	x; unsigned y
#define PADDEDptr(x, y)	x; unsigned y
#define PADDEDul(x, y)	unsigned long x; unsigned y
#  endif
#elif defined(__aarch64__)
#  if defined (__AARCH64EB__) /* big endian, 64 bits */
#define PADDED(x, y)    unsigned y; x
#define PADDEDptr(x,y)  x
#define PADDEDul(x, y)  unsigned long x
#  elif defined(__AARCH64EL__) /* little endian, 64 bits */
#define PADDED(x, y)    x, y
#define PADDEDptr(x, y) x
#define PADDEDul(x, y)  unsigned long x
#  endif
#else
#error	endian?
#endif
~~~
这段判断处理器的代码是从libaio.h里直接抄过来的，并没有龙芯处理器对应的宏。
你能不能把你用的处理器会添回哪个宏标志，以及对应的体系结构（大小端，字长）提供给我们，我们增加这个支持。
另外，如果你要把代码尽快跑起来，也可以改用thread方式的aio。thread方法一般是给mac用的，但也适用于其它unix系统。
在[kernel/Communicator.h](https://github.com/sogou/workflow/blob/34a6d5da6f815d48d3b0e363c77a1a95fd41c94f/src/kernel/Communicator.h#L256)里：
~~~cpp
#ifdef __linux__
# include "IOService_linux.h"
#else
# include "IOService_thread.h"
#endif
~~~
改成：
~~~cpp
#ifdef 0
# include "IOService_linux.h"
#else
# include "IOService_thread.h"
#endif
~~~
并把[kernel/CMakeList.txt](https://github.com/sogou/workflow/blob/master/src/kernel/CMakeLists.txt)和[CMakeLists_Headers.txt](https://github.com/sogou/workflow/blob/master/CMakeLists_Headers.txt)里，IOService_linux相关的改为IOService_thread，暂时用多线程的方式来处理文件异步IO就可以了。

**Comment by Barenboim** [comment]
@DaoYB033 
麻烦你更新到最新master再试一下，应该可以了。

**Comment by DaoYB033** [comment]
今天终于更新下来了，make成功，大神V5，谢谢！

**Comment by Barenboim** [comment]
非常感谢协助我们完成对龙芯处理器的支持。我在首面readme里加上支持龙芯的描述了。
