### ISSUE TITLE
现在有一个需求：高频写入数据库的操作，才接触，不太清楚用什么样的workflow结构处理

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#413]
目前能想到的是：创建一个串行，如果有数据过来的时候，就不断往里添加任务，如果没有任务处理的时候，就等待着，请给点建议，多谢！！！

**Comment by Barenboim** [comment]
这个我回答过的。参考一下：https://github.com/sogou/workflow/issues/301#issuecomment-804774242

**Comment by xiaoshizijiayou** [comment]
issue301我已经仔细看了，有3个疑问，请解答一下：1.blockseries,在push_back里有加锁，这个是必须的吗，我看文档其他说明里说封装的接口是可以保证原子性的；2.我看了mysql client的demo，对于高频写入的话，是不是每次写入都是一个独立任务；3.mysql client的demo里还提到了可以对每个sql任务添加一个专门连接，这个连接是必须要加的吗，使用和不使用的区别在哪儿，如果使用的话，有没有最大连接数的限制？看一些介绍里说，咱们workflow里相当于是做了数据库连接池的工作，是指的这个专门连接的接口吗？

**Comment by Barenboim** [comment]
1、blockseries的push_back里加锁是必须的，不是接口没有原子性，而是每次我实际添加了两个任务，为保证这两个任务中间不被打断，必须加锁。
2、我们任务是最小操作单位，必须是每次创建任务（但是，mysql任务支持多语句多结果集，一个query可以包含多条SQL语句）。
3、mysql独占连接不是必须的。只有你需要用到事务才需要用到独占链接，否则直接用WFTaskFactory来创建mysql任务就好。workflow框架有非常智能的连接管理，连接会在任务之间复用。单个目标默认最大连接数是200。

**Comment by Barenboim** [comment]
补充一下，使用WFMySQLConnection时，不受最大连接数影响。可以创建无限个WFMySQLConnection对象（注意ID不同），连接之间互不影响。
最大连接数只在框架管理连接时起作用。

**Comment by Barenboim** [comment]
@xiaoshizijiayou
