### ISSUE TITLE
[Feature Request] Support pipelining for RedisClient

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#436]
Redis 客户端能增加 pipelining 访问模式的支持么？

https://redis.io/topics/pipelining

**Comment by Barenboim** [comment]
这个可能不好加。我们可以加个批量接口，但做出来不是太好用，暂时有这个需求的也不多。而且我们的redis是支持集群模式的，也就是说请求还会重定向，这个再pipeline的话挺奇怪也很不好实现。
你可以拿我们这个对比一下其它pipeline redis client的性能和延迟。我感觉除了可能会多几个连接，我们各方面都会更好。

**Comment by heemoon** [comment]
pipeline 在同一个key的顺序操作中，可能是有些用处的，针对同一个key，会命中到同一个 redis slot 中。

**Comment by Barenboim** [comment]
> pipeline 在同一个key的顺序操作中，可能是有些用处的，针对同一个key，会命中到同一个 redis slot 中。

嗯嗯。这里有个扩展项目支持redis pipeline client的，可以看看：https://github.com/kedixa/workflow-extra/blob/master/example/PipeRedisExample.cpp
问题是我们的redis server无法支持pipeline。只有client的话，不是很统一。
