### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by fuzhenwen201** [sogou/workflow#440]
![image](https://user-images.githubusercontent.com/8003583/124103872-4ace9680-da94-11eb-81aa-d53e7aff43a9.png)

**Comment by holmes1412** [comment]
你好，我这边复现不了。可以把你在什么平台、用的哪个分支、编译用的什么命令发一下吗？

**Comment by Barenboim** [comment]
这是因为我们之前为了可以裁剪编译，把RedisValue和RedisMessage的析构函数放到了.cc文件。我怀疑你可能是.h更新了之后，没有重新编译导致。完整重新编译一下应该没问题的！

**Comment by Barenboim** [comment]
@fuzhenwen201
