### ISSUE TITLE
关于WFMySQLConnection的用法的疑问

### ISSUE THREAD

**Issue by myseemylife** [sogou/workflow#444]
### 背景

1. 项目中使用workflow 封装了一个http restful api service. 在具体的service中涉及到mysql数据库的访问.因为需要支持事务,使用了WFSQLConnection. 
2. server 中每个新请求incoming.都会创建一个thread Task来处理.
3. 具体service代码中 增删改查可能会有多个数据库操作,为了图方便 使用waitgroup强行将sql的逻辑 同步化了

### 遇到的问题
在用户请求并发多个个请求查询数据库数据,经常会出现error msg: Resource temporarily unavailable.

### 问题
1. 这种情况下 异步+回调方实现,如何组织代码,更好. 比较缺乏这方面的经验.  
2. error msg: Resource temporarily unavailable.这个问题该如何排查.猜想可能与我在任务中block的操作有关

**Comment by Barenboim** [comment]
我觉的你的问题好像是MySQLConnection被多个线程同时使用了吧。如果用MySQLConnection的话，每个Connection必须是独占的，而不是大家一起用。并且创建的时候需要确保id不同。
~~~cpp
class WFMySQLConnection
{
public:
    WFMySQLConnection(int id);
};
~~~
有个比较简单的方法，只要你的事务没有跨请求，可以每次现创建Connection，但还是要确保id是唯一的（相当于我们那边维护了一个连接池，你通过id就可以获得连接)：
~~~cpp
int get_unique_id()
{
    // Implement get_unique_id() and free_unique_id() by yourself.
    ....
}

void mysql_callback(WFMySQLTask *task)
{
    auto *conn = (WFMySQLConnection *)series_of(task)->get_context();
    conn->create_query_task("COMMIT", ...);
    ...
}

void process(WFHttpTask *task)
{
    int unique_id = get_unique_id();
    auto  *conn = new WFMySQLConnection(unique_id);
    conn->init("mysql://user:pass@127.0.0.1/db1?character_set=utf8");

    SeriesWork *series = series_of(task);
    series->set_context(conn);
    series->set_callback([unique_id](const SeriesWork *series) {
        auto *conn = (WFMySQLConnection *)series->get_context();
        conn->deinit();
        delete conn;
        free_unique_id(unique_id);
    }

    auto *mysql_task = conn->create_query_task("BEGIN; INSERT ...", mysql_callback);
    series->push_back(mysql_task);
}
~~~
大概这个结构，没有什么问题。最好不要用WaitGroup堵住process线程。

**Comment by myseemylife** [comment]
@Barenboim 代码中的确是 在不同线程下 重用了同一个connection. i will try your advise later. 在多说一点(最近一直在困惑我),
因为之前用多线程实现过一个类似的restful service.  每一个请求独占一个线程,.完成http parse,执行serveice logic,返回response. 这种顺序同步执行的思维很自然. 
在用workflow改写过程中,我发现.我需要不停创建的task,.然后再上个任务的完成callback中.决定是否继续执行后面的逻辑. 整个的逻辑 都被分散在 各个不同的task函数及其 回调中. 与之前同步处理的方式相比,似乎编码负担更重一点. 对于实现 api 路由来说,感觉不太好.期待大佬有成熟的代码组织建议分享.

**Comment by Barenboim** [comment]
不怎么在意性能的话，倒是可以用我们里面的WaitGroup或WFFuture，但是这样就没有办法做到完全的异步了，会占有一个等待线程。
我们比一般的异步库好一点的地方是又个series吧任务串起来，可以吧series看作协程，而series context可以看着协程局部变量。server回复的时机就是协程结束。
我们另外一个解决办法就是封装复合任务了。可以把一起完成某一个功能的一组异步任务，封装成一个任务。例如http本身就是一个复合任务，一次http请求可能要经历多次异步过程，但对使用者来讲就是一次callback，这是我们库比较有竞争力的地方。但是封装复合任务对普通用户来讲，难度有点太大了。

**Comment by myseemylife** [comment]
@Barenboim 谢谢大佬~问题已经解决.我自己私下琢磨下
