### ISSUE TITLE
Windows版Kafka 几时会有

### ISSUE THREAD

**Issue by qiufengyeluo** [sogou/workflow#445]
Windows版Kafka 几时会有

**Comment by holmes1412** [comment]
这个很简单😊目前kafka是增量编译的，你可以参考一下主分支在cmake编译时指定kafka所需要的文件，然后拉取windows分支，再然后把主分支上的kafka相关的代码挪过去、编译加上，即可！

windows+kafka的用户真的很少，感谢你关注我们的项目！

**Comment by Barenboim** [comment]
进行中了

**Comment by Barenboim** [comment]
@qiufengyeluo
Windows下的kafka client加上了。能不能帮我们实验一下？
