### ISSUE TITLE
[Upstream] What's the best practice to update upstream

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#446]
When using service manager system like `nacos`, only all instances could be get without know whether some instance got added or removed.

In this case, how to update the upstream? One way may be calling each instance with `upstream_replace_server`, is this 
the suggest way?

Another suggestion about upstream:
It will be useful if upstream could have a interface which could return the final address (e.g. ip with port), thus could integrate 
upstream with third party service easily.

**Comment by Barenboim** [comment]
OK, it is an interesting topic. In our framework you need to create an upstream name before adding a server. But any operation on upstream, creating or  adding/replacing servers, is absolutely thread-safe. You may call the upstream interfaces any time you want. But currently we don't support adding servers to an upstream name that doesn't exist. Maybe we will support this feature later.

**Comment by Barenboim** [comment]
> OK, it is an interesting topic. In our framework you need to create an upstream name before adding a server. But any operation on upstream, creating or adding/replacing servers, is absolutely thread-safe. You may call the upstream interfaces any time you want. But currently we don't support adding servers to an upstream name that doesn't exist. Maybe we will support this feature later.

Yes, any upstream operations are thread-safe, and you can always call upstream_replace_server to add or update a server. But we found a little bug in upstream_replace_server. We will fix it right away.

**Comment by Barenboim** [comment]
Fixed!

**Comment by holmes1412** [comment]
**The first question: How to use other service manage system?**
 Of course you can use ``upstream_replace_server()``. This api will remove the existed servers with this server_name, and guarantee to add a new one. The return value means how many servers is removed just now.

**The second question: How to get the final addresses?**
Sorry, you cannot get the ip with port in upstream. You can use ``void get_main_address(std::vector<std::string>& addr_list);`` to get all the servers you added before.

**Comment by Barenboim** [comment]
@hiberabyss
