### ISSUE TITLE
使用upstream模块时对于自定义协议提示URI解析失败的问题

### ISSUE THREAD

**Issue by SimoAutumn** [sogou/workflow#460]
对于一套自定义协议的报文，server端起了两个服务，假定为 localhost:6601 和  localhost:6602，当通过WFNetworkTaskFactory::create_client_task(TT_TCP, upstream_name, retry_max, callback)创建一串task任务时，希望按照既定的upstream策略进行流量分配，但由于此处的协议不是内置支持的http/redis/mysql，添加upstream server的代码如下：
UpstreamManager::upstream_add_server(upstream_name, "127.0.0.1:6601");
UpstreamManager::upstream_add_server(upstream_name, "127.0.0.1:6602");
在callback处检测task的state和error，错误提示 WFT_ERR_URI_PARSE_FAILED ，怀疑是对自定义协议支持的问题，因此想了解对于此种情况该怎么处理？这样感觉会比较灵活，框架可以统一处理，开发/配置时只需要关注协议报文的实现。

**Comment by Barenboim** [comment]
是这样的。create_client_task有两个接口，一个是：
create_client_task(TT_TCP, host, port, retry_max, calllback);
另外一个是：
create_client_task(TT_TCP, url, retry_max, callback)
也就是说，你其实调用的是url的接口。简单的，你只需要写成：
create_client_task(TT_TCP, upstream_name, 1, retry_max, callback);
或者：
create_client_task(TT_TCP, "myprotocol://upstream_name:1/", retry_max, callback);
现在我们无论如何需要有一个默认端口，这里传了个1。但是因为你已经注册了upstream名，实际会用upstream里的server端口。你也可以给你的协议注册一个默认端口，这样URL里就不用写端口了。方法是：
WFGlobal::register_default_port("myprotocol", port);

**Comment by SimoAutumn** [comment]
谢谢，已测试，验证ok。
