### ISSUE TITLE
高并发时出现链接超时

### ISSUE THREAD

**Issue by ussturn** [sogou/workflow#463]
使用workfow 用jmeter压测并发量不高是出现 non http response code     connection timed out

**Comment by Barenboim** [comment]
你好，不知道您server端的服务逻辑是什么样的。我们没有遇到过高并发下超时的情况。如果是并发度特别的高，是不是因为最大连接数满了？ server参数时有个最大连接数配置，修改方法如下：
~~~cpp
int main()
{
    struct WFServerParams params = HTTP_SERVER_PARAMS_DEFAULT;
    params.max_connections = 100000;    /* default value is 2000 */
    WFHttpServer server(&params, process);
}
~~~
由于server最大连接数默认值为2000，可以考虑一下是不是连接满了。连接满了会踢掉旧连接，无连接可以踢的话会拒绝新连接。

**Comment by Barenboim** [comment]
@ussturn 现在还有超时问题吗？麻烦和我们反馈一下。
