### ISSUE TITLE
workflow.lib无法使用 (Windows版问题)

### ISSUE THREAD

**Issue by xjlovelearning** [sogou/workflow#466]
用cmake编译的workflow.lib,建立一个简单的工程，报error LNK2019: 无法解析的外部符号 _SSL_set_bio等错误

**Comment by Barenboim** [comment]
没有链接OpenSSL。明天Windows的同学看一看。

**Comment by dengjunplusplus** [comment]
@Barenboim  问题已经解决，他的openssl库文件名称写错了
