### ISSUE TITLE
URIParser是否有必要做URI校验

### ISSUE THREAD

**Issue by chenxudong** [sogou/workflow#477]
URI的格式为 scheme://[userinfo@]host[:port][/path][?query][#fragment]
URIParser的基本功能是按照标准格式解析出对应字段，如果格式正确则交付给下一步操作。
除了判断格式是否正确外，URIParser是否有必要做其他校验？
基于错误越早发现处理代价越低，scheme、host、port关系到通信链路，可以做严格值校验，比如port=”abc“可以提前报错处理掉。但其他字段相当于通信双方自己的内容，很难界定这个值对不对（RFC仅供参考，很多URL的query字段里有各种异常值），按照RFC规定字符集进行值校验限制了通信的灵活性。建议去掉部分字段的合法性校验，由通信双方自行处理。

**Comment by Barenboim** [comment]
能不能给我们提交一个Pull Request?

**Comment by Barenboim** [comment]
我觉得格式可以宽松一点，目前我们的URI解析严格按照RPC标准做的，不少浏览器可以允许的URL是会被我们认为是非法字符的。你可以参考一下浏览器或者CURL这类工具，把字符集放空到和它们一致，我觉得是可行的。
