### ISSUE TITLE
workflow能否被当成一个简单高效的线程池来使用？

### ISSUE THREAD

**Issue by ChunelFeng** [sogou/workflow#484]
具体的业务功能，我可以自己实现。
但我想要异步的执行n个任务，并且通过workflow来进行调度。

by the way，有无提供协程（池）功能？

**Comment by Barenboim** [comment]
好问题。用户可以只使用go task，把workflow框架退化成一个线程池。这种情况下，通讯相关的资源都不会被创建。创建go task的接口如下：
~~~cpp
class WFTaskFactory
{
public:
    template<class FUNC, class... ARGS>
    static WFGoTask *create_go_task(const std::string& queue_name, FUNC&& func, ARGS&&... args);
};
~~~
其中，队列名queue_name的作用在FAQ里有介绍，如果没有什么调度需求，随便传个固定的静态字符串就可以了。func和args是函数名和参数列表。
go task和其他任务一样，可以被push_back到series里，当然也可以配合parallel使用。也就是说，这是一个可以实现任务依赖关系的线程池。go task也有callback，但默认为nullptr，可以通过set_callback接口设置。
workflow框架的计算线程池，线程数量默认等于本机总的CPU核数，可以通过全局配置修改。但注意，需要在第一次创建go task之前就设置。例如，把计算线程数定为20：
~~~cpp
#include "workflow/WFGlobal.h"
int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.compute_threads = 20;
    WORKFLOW_library_init(&settings);
    ....
}
~~~
示例可以参考这个文档：
https://github.com/sogou/workflow/blob/master/docs/about-go-task.md

**Comment by Barenboim** [comment]
by the way，说到协程，本质上我们的series就是协程，series context可以理解成协程的局部变量。

**Comment by Jamishon** [comment]
struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.compute_threads = 20;
    WORKFLOW_library_init(&settings);
    
    这段代码解决了我在Windows Server 2003和2012上，双核 CPU, go task 运行不起来的问题，唉，这个bug花了一天的时间

**Comment by Barenboim** [comment]
> struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT; settings.compute_threads = 20; WORKFLOW_library_init(&settings);
> 
> ```
> 这段代码解决了我在Windows Server 2003和2012上，双核 CPU, go task 运行不起来的问题，唉，这个bug花了一天的时间
> ```

默认的计算线程数等于所在机器的CPU核心数。
