### ISSUE TITLE
忍不住想吐槽定时器

### ISSUE THREAD

**Issue by dou1984** [sogou/workflow#485]
目前定时器最长定时用期约4200秒，明显不够用啊
而且定时器精度1ms一般就足够了，微秒级别的系统都反应不过来吧

**Comment by Barenboim** [comment]
可以多串几个，效果一样的。
你这么一说，我们确实可以在增加几个定时器的接口，支持更长的定时时间。之前我们是担心用户程序需要退出，定时器还没有到期比较麻烦。不过后来想起来定时器可以被程序退出安全的中断的。

**Comment by Barenboim** [comment]
增加了一个这样的接口能满意吗？
~~~cpp
class WFTaskFactory
{
    static WFTimerTask *create_timer_task(time_t seconds, long nanoseconds, timer_callback_t callback);
};
~~~

**Comment by dou1984** [comment]
点个赞

**Comment by dou1984** [comment]
> 增加了一个这样的接口能满意吗？
> 
> ```c++
> class WFTaskFactory
> {
>     static WFTimerTask *create_timer_task(time_t seconds, long nanoseconds, timer_callback_t callback);
> };
> ```

点个赞👍
