### ISSUE TITLE
vectors[i].iov_base 只写入了请求头的名字，没有写入value

### ISSUE THREAD

**Issue by CNYuYang** [sogou/workflow#502]
https://github.com/sogou/workflow/blob/5b29d199a22691a1fb297148ef28dc70b2fd4c39/src/protocol/HttpMessage.cc#L168

```cpp
vectors[i].iov_base = (void *)header.name;
vectors[i].iov_len = header.name_len + 2 + header.value_len + 2;
```

vectors[i].iov_base 只写入了请求头的名字，没有写入value

**Comment by Barenboim** [comment]
这个和里面的内存布局有关系，我们把name和value在内存里连续保存了，减少所需vector的个数。

**Comment by CNYuYang** [comment]
但是name和value之间不应该是": "吗，结尾是“\r\n"

**Comment by Barenboim** [comment]
我们里面存的就是“name: value\r\n”，中间那个+2就是“: "，后面的+2是"\r\n"。

**Comment by CNYuYang** [comment]
嗷嗷嗷，看到了，Thx~
