### ISSUE TITLE
关于回复请求时连接获取的困惑？

### ISSUE THREAD

**Issue by littledoglily** [sogou/workflow#505]
大概看了代码结构实在感叹代码的精简程度和高效。但还是有一些困惑。通过http_echo_server的例子，请求在handle_incoming_request中session->handle处理完之后，应该是通过Communicator::reply回复的，这个里面又会调用Communicator::reply_idle_conn这个函数拿出一个空连接，想知道target中的idle_list中的结构是在何时放进去的？ 是只有在一个请求过来，初始化完成之后才放进去吗？

**Comment by Barenboim** [comment]
谢谢夸奖。
关于reply的问题，首先解释一下，idle_list和reply_idle_conn这两个命名是有点问题的。因为这个模块先实现client端的功能，idle_list本来是指keep-alive的可复用连接。实现server时，发现client的keep-alive连接和server的待回复连接在使用上有点类似，可以直接复用代码，于是就还把server侧待回复的连接也放在idle_list。
在server端，target中的idle_list是在成功接收到一个client请求是添加的。而且，对于server来讲，target（CommServiceTarget）里的idle_list最多只有一个连接。而client端的idle_list可以有许多的keep-alive连接。

**Comment by littledoglily** [comment]
ok，理解了！
