### ISSUE TITLE
workflow目前的稳定版不支持websocket协议吗？

### ISSUE THREAD

**Issue by tashaxing** [sogou/workflow#508]
但是看到branch里面有个websocket的分支，不知道是不是

**Comment by holmes1412** [comment]
是的～这个功能前两个月刚写完，目前还在websocket分支，最近准备合并到主分支。

在合到主分支之前我还有一些考虑：
- 目前网络模型下，只有client，没有server；
- 希望得到小伙伴们对接口的建议，留一些推荐使用习惯的余地；

所以如果你有需要websocket，欢迎使用，并且有任何都欢迎提给我^_^ 之后就马上会合到master了～
