### ISSUE TITLE
[Timer] 示例程序中 Timer 为什么需要加锁

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#528]
对于如下的 Timer 退出示例中，为什么在 timer_callback 判断是否退出前需要加锁？

![image](https://user-images.githubusercontent.com/2898670/129533784-29b0ec0e-623d-42f0-9438-fd8cce5b850a.png)

**Comment by Barenboim** [comment]
完整示例在这里：https://github.com/sogou/workflow/blob/master/docs/about-timer.md
这个示例里，我们通过program_terminate来判断程序main函数是否可能已经返回。如果main函数已经结束，我们就不应该再运行新的任务了（包括timer或http）。
如果不加这个锁，很显然可能程序运行到series->push_back()的时候主进程退出，那么就可能在主进程退出之后又运行了一个任务，与我们的基本假设不符合。
不过这个示例的用法是比较少见的，一般也就是用在有timer任务没有结束的情况下退出程序。我目前的想法是开发一个可以手动中断timer任务的方法，解决程序结束时，还有timer未返回的情况。
