### ISSUE TITLE
kafka_cli abort()

### ISSUE THREAD

**Issue by zhangxuebing123** [sogou/workflow#530]
[具体堆栈信息如下:
![20210817100545](https://user-images.githubusercontent.com/18676943/129656533-eb42748c-6ea6-4f32-98b3-acd431dfcde2.png)
/etc/resolv.conf为空

**Comment by Barenboim** [comment]
没有dns服务器，哪怕是只用ip地址，好像是直接挂的。你可以随便配个dns服务器地址，或者在全局配置里把resolv_conf_path配置为NULL。
不过这是个好问题，我觉得我们可以改一下，让用户只使用ip时，可以不需要有dns服务器。谢谢反馈。

**Comment by zhangxuebing123** [comment]
好的，我配了一个DNS服务器地址是可以了。谢谢 @Barenboim

**Comment by Barenboim** [comment]
我来打个补丁解决这个问题。

**Comment by Barenboim** [comment]
已经解决。目前的方式resolv.conf里找不到nameserver，就用公用dns: 8.8.8.8 。如果resolv.conf解析结果有问题，也会走系统的dns函数，程序不再abort()。
