### ISSUE TITLE
kafka_cli core

### ISSUE THREAD

**Issue by zhangxuebing123** [sogou/workflow#532]
![20210820095101](https://user-images.githubusercontent.com/18676943/130166604-0b8dca95-c788-4b6d-aa78-c74255accb36.png)
![e53f7fa6abe3804586dfe588a8c59b34](https://user-images.githubusercontent.com/18676943/130166608-31a0be0d-25b7-4461-b784-22744ae742f2.png)
难道是我用法的问题么？  使用的是消费者组模式

**Comment by wzl12356** [comment]
你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。

**Comment by zhangxuebing123** [comment]
> 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。

这个重新封一下， 大体就是生产消费两个client , 不同的线程分别调生产和消费

**Comment by zhangxuebing123** [comment]
> 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。

[demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)

**Comment by wzl12356** [comment]
> > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> 
> [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)

代码有点问题，
![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
这样会串联多个相同的task指针，第一个调度完了会自动删除，后面在调度会出问题。
解决方案就是把					
`if(!no_fetch_group)
series_of(task)->push_back(next_task);`
这两行拿到括号外面即可。

**Comment by zhangxuebing123** [comment]
> > > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> > 
> > 
> > [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)
> 
> 代码有点问题，
> ![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
> 这样会串联多个相同的task指针，第一个调度完了会自动删除，后面再次调度相同的task指针会出问题（task已经在第一次调度完成后被析构）。
> 解决方案就是把
> `if(!no_fetch_group) series_of(task)->push_back(next_task);`
> 这两行拿到括号外面即可。
.... 还是有点问题。。。 搞不来搞不来！！

**Comment by Barenboim** [comment]
您好，如果还有什么问题可以随时和我们继续交流。
我们目前kafka用户不少，如果有什么潜在问题也想尽早的发现。也非常感谢你帮助我们排查了几个问题。

**Comment by wzl12356** [comment]
> > > > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> > > 
> > > 
> > > [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)
> > 
> > 
> > 代码有点问题，
> > ![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
> > 这样会串联多个相同的task指针，第一个调度完了会自动删除，后面再次调度相同的task指针会出问题（task已经在第一次调度完成后被析构）。
> > 解决方案就是把
> > `if(!no_fetch_group) series_of(task)->push_back(next_task);`
> > 这两行拿到括号外面即可。
> > .... 还是有点问题。。。 搞不来搞不来！！

你代码中的commit的callback会发送一个leavegroup，相当于结束了fetch，这个按说应该是在最后程序退出的时候再创建leavegroup task的。

**Comment by Barenboim** [comment]
@zhangxuebing123

**Comment by zhangxuebing123** [comment]
> > > > > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> > > > 
> > > > 
> > > > [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)
> > > 
> > > 
> > > 代码有点问题，
> > > ![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
> > > 这样会串联多个相同的task指针，第一个调度完了会自动删除，后面再次调度相同的task指针会出问题（task已经在第一次调度完成后被析构）。
> > > 解决方案就是把
> > > `if(!no_fetch_group) series_of(task)->push_back(next_task);`
> > > 这两行拿到括号外面即可。
> > > .... 还是有点问题。。。 搞不来搞不来！！
> 
> 你代码中的commit的callback会发送一个leavegroup，相当于结束了fetch，这个按说应该是在最后程序退出的时候再创建leavegroup task的。

如果我要是实现fetch的poll模式，  是在callback的offsetcommit中创建next_fetch_task, 然后push_back嘛？？  还有什么其他的设置？

**Comment by zhangxuebing123** [comment]
> > > > > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> > > > 
> > > > 
> > > > [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)
> > > 
> > > 
> > > 代码有点问题，
> > > ![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
> > > 这样会串联多个相同的task指针，第一个调度完了会自动删除，后面再次调度相同的task指针会出问题（task已经在第一次调度完成后被析构）。
> > > 解决方案就是把
> > > `if(!no_fetch_group) series_of(task)->push_back(next_task);`
> > > 这两行拿到括号外面即可。
> > > .... 还是有点问题。。。 搞不来搞不来！！
> 
> 你代码中的commit的callback会发送一个leavegroup，相当于结束了fetch，这个按说应该是在最后程序退出的时候再创建leavegroup task的。

**Comment by zhangxuebing123** [comment]
> > > > > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> > > > 
> > > > 
> > > > [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)
> > > 
> > > 
> > > 代码有点问题，
> > > ![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
> > > 这样会串联多个相同的task指针，第一个调度完了会自动删除，后面再次调度相同的task指针会出问题（task已经在第一次调度完成后被析构）。
> > > 解决方案就是把
> > > `if(!no_fetch_group) series_of(task)->push_back(next_task);`
> > > 这两行拿到括号外面即可。
> > > .... 还是有点问题。。。 搞不来搞不来！！
> 
> 你代码中的commit的callback会发送一个leavegroup，相当于结束了fetch，这个按说应该是在最后程序退出的时候再创建leavegroup task的。

请问一下这个消费者的poll模式这边是怎么实现的？

**Comment by wzl12356** [comment]
> > > > > > 你是先生产然后再消费？代码是什么样子的，方便的话，贴一下实例。
> > > > > 
> > > > > 
> > > > > [demo.zip](https://github.com/sogou/workflow/files/7018839/demo.zip)
> > > > 
> > > > 
> > > > 代码有点问题，
> > > > ![image](https://user-images.githubusercontent.com/16952500/130193543-9c5cd257-0097-4bb3-a19f-ee5b3ee635e8.png)
> > > > 这样会串联多个相同的task指针，第一个调度完了会自动删除，后面再次调度相同的task指针会出问题（task已经在第一次调度完成后被析构）。
> > > > 解决方案就是把
> > > > `if(!no_fetch_group) series_of(task)->push_back(next_task);`
> > > > 这两行拿到括号外面即可。
> > > > .... 还是有点问题。。。 搞不来搞不来！！
> > 
> > 
> > 你代码中的commit的callback会发送一个leavegroup，相当于结束了fetch，这个按说应该是在最后程序退出的时候再创建leavegroup task的。
> 
> 请问一下这个消费者的poll模式这边是怎么实现的？
WFKafkaClient的设计和librdkafka不同，它没有一个显式的poll线程。在消费者组模式下，会有SeriesWork在后台负责发送heartbeat，维护消费者组一直在线；用户在使用的时候，首先应该创建消费者Task（Fetch类型的task，同时应该指定callback函数），然后将这个task串联到SeriesWork中（如：series_of(task)->push_back(next_task);），或者直接调用task的start方法。由于workflow是个高效的异步框架，因此当fetch任务获取到数据后，将会执行前面指定的callback函数，用户的处理逻辑应该在callback中实现。WFKafkaClient内部会维护消费的offset，用户也可以通过创建Commit task来提交当前已经消费的offset，具体例子可以参考tutorial/tutorial-13-kafka_cli.cc。

**Comment by Barenboim** [comment]
@zhangxuebing123
