### ISSUE TITLE
mysql客户端连接地址的密码中也包含字符@的问题

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#537]
mysql客户端连接地址中包含特殊字符@，通过@区分地址，账号和密码，我的密码里包含@字符，连接时会报错，有什么方法可以解决这个问题吗？

**Comment by Barenboim** [comment]
encode一下。我们的[StringUtil](https://github.com/sogou/workflow/blob/master/src/util/StringUtil.h)有url encode的功能。

**Comment by xiaoshizijiayou** [comment]
好的

**Comment by Barenboim** [comment]
@xiaoshizijiayou
这里还需要说明一下，不能对url整体encode，因为encode函数内部依然无法区分那个@分割符。
所以，你可能需要对password部分单独encode，再拼接url。

**Comment by xiaoshizijiayou** [comment]
> @xiaoshizijiayou
> 这里还需要说明一下，不能对url整体encode，因为encode函数内部依然无法区分那个@分割符。
> 所以，你可能需要对password部分单独encode，再拼接url。

普通字符串加encode的字符串，直接提交连接，就可以识别是吗，不需要做什么特殊操作，比如decode

**Comment by Barenboim** [comment]
对，直接连接。比如你的密码是"@@@123"，用户名是"xiaoshizi"，域名是localhost那么：
~~~cpp
{
    std::string url = "mysql://xiaoshizi:" + StringUtil::url_encode("@@@123") + "@localhost/"
    WFMySQLTask *task = WFTaskFactory::create_mysql_task(url, ....);
}
~~~
大概这样子。

**Comment by xiaoshizijiayou** [comment]
@Barenboim 按你说的这种方法试了，不行呢，给解答下吧

**Comment by xiaoshizijiayou** [comment]
@Barenboim url_encode_component,用这个才管用

**Comment by Barenboim** [comment]
噢噢，好像是的。url_encode是整体url的encode，'@'字符会被跳过。url_encode_component可以。
不过感觉上目前这个用法多少有点复杂。
