### ISSUE TITLE
workflow关于macos和Linux对应的底层接口一致吗？

### ISSUE THREAD

**Issue by lixiaoqian521** [sogou/workflow#539]
你好我想问一下，我在mac上面运行workflow，底层的系统api和Linux一样吗？是否都遵循posix标准？

**Comment by Barenboim** [comment]
macOS下可以放心使用。macOS和Linux的区别是：
1、IO多路复用，macOS下用的是kqueue，Linux下是epoll。对外没有任何区别。
2、macOS下，文件异步IO使用的是多线程模拟，而Linux下，使用的是Linux专有的aio系列系统调用。所以Linux下文件异步IO会更快，并且支持Linux专有的preadv和pwritev。macOS下不使用posix AIO，因为这个也是多线程模拟并且性能不佳。
3、其它的完全一致。我们的代码会在这两个平台上都进行测试的。
