### ISSUE TITLE
windows版本配置的实收报错

### ISSUE THREAD

**Issue by FfeiGithub** [sogou/workflow#54]
![image](https://user-images.githubusercontent.com/29305637/93410730-19e9f000-f8cc-11ea-89a0-a2f4eff2aabd.png)

当用CMake对windows版本的分支进行配置的时候，报错，然后generate生成的工程编译也报错

**Comment by sonullx** [comment]
你好，CMake在构建工程的过程中用到了git信息，如果是Download ZIP拿到的代码确实会出现这个问题。
你可以暂时选择从GitHub clone的方式来获取源代码。
我们会尽快处理这个问题。

感谢您的反馈。

**Comment by Barenboim** [comment]
已修复。

**Comment by Barenboim** [comment]
windows branch已修正，麻烦帮我们试一试
