### ISSUE TITLE
Help: workflow对长连接推送服务的支持

### ISSUE THREAD

**Issue by cxxjava** [sogou/workflow#543]
业务需求：
1. 支持tcp长连接，同时若能支持websocket更佳；
2. 服务端能在客户端在线状态下主动推送消息（不是客户端心跳模式的一来一回）；
3. 客户端网络异常断开情况下，服务端对该客户端推送消息时，workflow能主动鉴别网络断开的状态（网络层主动read socketfd 后异步回调应用层？）；

**Comment by Barenboim** [comment]
@cxxjava
你可以看看这个同步push的接口是不是可以简单先使用，这里没有异步写的支持，所以推送超过TCP send buf的数据暂时做不到（之后可以实现，但每个push需要先创建一个push task）。另外，series结束时，如果不想回复正常的resp了，可以调一下server_task->noreply()，连接会在原本回复的时机被关闭。
@dou1984
你说的更完整的实现，之后可以用我们的websocket。
