### ISSUE TITLE
[MySQL] 客户端能否支持 ORM 方式的数据 query

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#556]

**Comment by Barenboim** [comment]
这个问题，我们项目本身是不打算提供ORM接口的，这不符合我们的设计理念。我们只提供必要的功能，让用户可以在这个基础上封装出适合自己的接口。例如最近就有热心用户实现了workflow http server的html form data模块并且开源：https://github.com/BDZNH/workflow-HttpFormdataParser
