### ISSUE TITLE
如何保证用户请求严格按照先后顺序被处理和返回结果

### ISSUE THREAD

**Issue by KelvinYin** [sogou/workflow#559]
需求描述：

1. 该服务有上下游服务，使用 TCP 连接（也有可能是 NGINX 转发过来）；
2. 单个用户的请求必须按照时间先后顺序串行处理，即处理完前一条消息才能处理下一条；
3. 结果返回也要有序；
4. 不同用户的请求可以分配到不同的线程处理；

一个简单的想法是用一个 handler 线程再做一次分发，根据 UID 把请求发到不同的处理线程上，但这样不能保证返回结果的有序。
![image](https://user-images.githubusercontent.com/6712458/132681949-697808cb-e189-4c12-b863-c52aa8a3ce03.png)

请问用 workflow 如果解决这类问题？

谢谢！

**Comment by Barenboim** [comment]
只要handler_thread大于1，那么process就是并发执行的了。这时，同一个UID请求，好像是无法区分时间上哪个先到达的。这种情况下是随便一种顺序都可以吗？也就是说，同一时刻同一UID的请求，是否只需保证以某种顺序串行处理和返回就可以了？

**Comment by KelvinYin** [comment]
> 只要handler_thread大于1，那么process就是并发执行的了。这时，同一个UID请求，好像是无法区分时间上哪个先到达的。这种情况下是随便一种顺序都可以吗？也就是说，同一时刻同一UID的请求，是否只需保证以某种顺序串行处理和返回就可以了？

同一个 UID 的请求必须是串行处理，如果能按照用户的发起时间排序最好。在交易系统中，用户策略下单的前后顺序可能会影响收益。

**Comment by Barenboim** [comment]
两个请求同时到达，如何判断发起时间呢？是否请求里有递增的request_id？否则的话，是不是可以认为，server这边谁先抢到某种锁先执行就可以了？

**Comment by KelvinYin** [comment]
> 两个请求同时到达，如何判断发起时间呢？是否请求里有递增的request_id？

递增的 request_id 是可选字段，不能依赖于这个字段判断。

> 是不是可以认为，server这边谁先抢到某种锁先执行就可以了？

我觉得也只能用这种方式，绝对的按时间排序不太现实。我问题描述中的那张图中，每个计算线程再加一个返回结果的队列，保证返回结果的有序性就好了，这个有序性是指先处理的请求先收到回复。

**Comment by Barenboim** [comment]
你可以用我们的resource pool来做这件事。比如以下这个demo，可以是把所有的请求串行化执行：
~~~cpp
WFResourcePool respool(1);

void process(WFHttpTask *task)
{
    WFGoTask *t = create_go_task(....);
    
    t->set_callback([&task] (WFGoTask *) {
        respoll.post(nullptr);
        task->get_resp()->append_output_body(...);
    });

    WFConditional *cond = respool.get(t);
    series_of(task)->push_back(cond);
}
~~~
你把这个respool改成每个UID下一个就可以了。关于resource pool，可以参考这个方档：
https://github.com/sogou/workflow/blob/master/docs/about-conditional.md
一切串行化的需求都可以用resource pool来实现。

**Comment by Barenboim** [comment]
如果你这边对于返回的序要求更严格，代码可以改成这样：
WFResourcePool respool(1);

void process(WFHttpTask *task)
{
    WFGoTask *t = create_go_task(....);
    
    t->set_callback([&task] (WFGoTask *) {
        task->get_resp()->append_output_body(...);
    });

    WFConditional *cond = respool.get(t);
    series_of(task)->push_back(cond);
    task->set_callback([] (WFHttpTask *) {  respoll.post(nullptr); });
}
这样让server task在回复写入TCP buffer之后，再允许下一个请示的执行。但是，先写入TCP buffer，也不能保证客户端先收到回复。

**Comment by KelvinYin** [comment]
这种串行化应该可以一定程序上解决时序问题。

严格的时序性能想到的就是，全链路都是单线程才容易保证。

**Comment by Barenboim** [comment]
> 这种串行化应该可以一定程序上解决时序问题。
> 
> 严格的时序性能想到的就是，全链路都是单线程才容易保证。

我的第二个demo，其实就是已经很严格的串行化了。你只需改成每个UID一个resource pool，就可以实现单UID下的串行，整体的并发。

**Comment by KelvinYin** [comment]
非常感谢，我下午看了 Resource pool，理解了 demo 代码中的作用。

**Comment by chanchann** [comment]
A simple experiment code : 

https://github.com/chanchann/workflow_annotation/blob/main/demos/26_resource_pool/26_issue_559_server.cc

https://github.com/chanchann/workflow_annotation/blob/main/demos/26_resource_pool/26_issue_559_client.cc
