### ISSUE TITLE
关于长连接数和分布式相关

### ISSUE THREAD

**Issue by xjchilli** [sogou/workflow#561]
请问有测试过最大的长连接数么？分布式处理在低层是如何实现的呢？

**Comment by Barenboim** [comment]
这个默认最大65536的fd，最大长连接几万都是试过的。如果需要超过65536的fd的话，需要改一行源代码。毕竟很少有人需要那么多并发连接。
另外server最大的连接数限制，默认为2000，超过的话会关闭最久未使用的keep-alive连接。可以通过server参数来修改。这个文档里有说明：
https://github.com/sogou/workflow/blob/master/docs/tutorial-05-http_proxy.md
client对单个ip的最大连接，默认为200，可以通过全局配置修改，或通过upstream来修改单个目标的配置。可以看这个文档：
https://github.com/sogou/workflow/blob/master/docs/about-config.md
以及服务治理的文档：
https://github.com/sogou/workflow/blob/master/docs/about-service-governance.md#upstream-server的参数

**Comment by Barenboim** [comment]
关于连接复用，在FAQ里也有一些的说明。
