### ISSUE TITLE
How about wrap Sockaddr class?

### ISSUE THREAD

**Issue by chanchann** [sogou/workflow#562]
Hi, these days I try to use this awesome framework, but I find that in 

https://github.com/sogou/workflow/blob/master/tutorial/tutorial-04-http_echo_server.cc.  

```
server_task->get_peer_addr((struct sockaddr *)&addr, &l);
if (addr.ss_family == AF_INET)
{
struct sockaddr_in *sin = (struct sockaddr_in *)&addr;
inet_ntop(AF_INET, &sin->sin_addr, addrstr, 128);
port = ntohs(sin->sin_port);
}
else if (addr.ss_family == AF_INET6)
{
struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)&addr;
inet_ntop(AF_INET6, &sin6->sin6_addr, addrstr, 128);
port = ntohs(sin6->sin6_port);
}
else
strcpy(addrstr, "Unknown");
```
If users want to print the peer IP: port string, they have to write this piece of code. 

Why not offer a sockaddr(InetAdder) class which can make it more convenient to get the information of the sockaddr(inetAddr)?

Just like https://github.com/chenshuo/muduo/blob/master/muduo/net/InetAddress.h

```
// we can just write like this 
InetAddr inet_addr;
server_task->get_peer_addr(inet_addr);
inet_addr.getIp();
inet_addr.getPort();
inet_addr.getFamily();
......
```

**Comment by chanchann** [comment]
And users need not judge whether it is ipv4 or ipv6.

**Comment by Barenboim** [comment]
I do not see any advantage of wrapping a socket address. I think the structure **sockaddr** with variable length is a general way to store an address.  Of course you may come up with a helper function (or class) to print the address string, but  it's recommended to use simple data structures (like struct sockaddr) in module interfaces.
BTW, the WFServer supports unix domain socket too. Obviously getIP() and getPort() are not general enough. It's not that easy to design an address wrapper :)

**Comment by chanchann** [comment]
Thanks for your response.
