### ISSUE TITLE
LNK2019 msbuild

### ISSUE THREAD

**Issue by jie235** [sogou/workflow#563]
### window10 , visual studio 2019

安装的时候使用vcpkg，编译安装过程中也安装了openssl（version: 1.1.1l）。、

编写简单的示例程序，出现 LNK2019 错误（以及众多 LNK2001 ）无法解析的外部符号。

### window10, clion 2020.3.2 cmake 工程使用 msbuild 为编译器出现同样的问题

**Comment by holmes1412** [comment]
@dengjunplusplus windows的编译问题麻烦有空帮看看哈～

**Comment by Barenboim** [comment]
记得切到Windows分支。

**Comment by jie235** [comment]
> 记得切到Windows分支。

大意了，谢谢~

**Comment by jie235** [comment]
> @dengjunplusplus windows的编译问题麻烦有空帮看看哈～

谢谢~ 已经解决了笑哭😂
