### ISSUE TITLE
有没有考虑过强化一下HTTP协议呢？

### ISSUE THREAD

**Issue by rareli** [sogou/workflow#572]
有没有考虑过强化一下HTTP协议呢？
Route、HTTP(Cookie、Session、Parameter、文件上传处理等)相关，这样也可以用作webserver。
同时，websocket也可以支持一下。

**Comment by holmes1412** [comment]
websocket已经支持啦，在开发分支上，之后会很快合到主分支：https://github.com/sogou/workflow/tree/websocket

**Comment by rareli** [comment]
1.websocket支持服端吗？
2.workflow能用作web framework吗？

**Comment by Barenboim** [comment]
你好。websocket目前只有client呢。
workflow可以用作web framework，只是我们的侧重点是做高性能服务，任务流管理，名称服务这些。做web framework需要的一些像route，cookie，以及html层的东西我们是做得比较少的。但现在我们的server接口不妨碍用户在此基础上做扩展。但这块我们的经验不是很多，所以目前没有开发相关的生态项目。

**Comment by chanchann** [comment]
@rareli 你看，可以看下wfrest这个项目

项目地址 : https://github.com/wfrest/wfrest

wfrest根据workflow进行开发，相当于workflow的插件，增加了route，Cookie, 文件上传下载等HTTP常见功能

注册handler，取出req的header，url相关字段，发送文件，Json， 获取，设置cookie 等等都非常方便

比如我们注册一个handler

```cpp
svr.GET("/wildcast/{name}/action*", [](const HttpReq *req, HttpResp *resp)
{
    const std::string& name = req->param("name");
    ...
});
```

或者提供一个静态文件服务

```cpp
HttpServer svr;
svr.Static("/static", "./www/static");

svr.Static("/public", "./www");
```
设置cookie

```cpp
cookie.set_path("/").set_http_only(true);
resp->add_cookie(std::move(cookie));
resp->String("Set Cookie\n");
```
