### ISSUE TITLE
是否有计划支持udp server？

### ISSUE THREAD

**Issue by ChungTak** [sogou/workflow#576]
我想试试workflow是否合适做流媒体服务，需要接收udp消息。请问udp server有没有计划添加的呢？

**Comment by Barenboim** [comment]
请问你需要做可靠UDP吗？可靠UDP和普通UDP，我们server的实现方式可能会不一样。

**Comment by ChungTak** [comment]
不需要可靠～～ 允许丢包.  用来做sip协议～udp发送rtp包

**Comment by Barenboim** [comment]
今天想了一天，感觉UDP server沿用我们现在这个模式不太好做。因为我们目前的模式下TCP server如果在process过程中有收到数据，我们会认为这是垃圾数据直接断开连接（我们彻底抛弃http/1.1的pipeline功能）。但对于UDP这是有问题的，UDP包可能会重复收到不应该认为是错误数据。所以整个模式就不太一样。
UDP client我们是支持比较好的，目前DNS解析默认就是用UDP协议发送。如果你想实现UDP server，可以用我们的poller模块来实现异步读取。而UDP没有异步写入的需求，写入数据直接对fd进行操作就可以了。poller模块的接口说明可以看看这个：https://github.com/sogou/workflow/issues/351

**Comment by wangwenqiangGitHub** [comment]
您好：很高兴能有这么优秀的框架可以学习, 目前使用的话，还有一些顾虑，比如我是嵌入式设备开发，很多网络通讯都是udp去接收传感器数据，通过传感器的消息解析，分发给不同的场景, 看到咱们已经支持信号-槽这种观者者模式，想问一下，有没有什么方法可以监听我自己设置的udp fd，通过回调的方式来处理 传感器到来的数据，然后自己就可以分发给不同的模块处理了。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/issues/1499
已经实现了。
