### ISSUE TITLE
图并发任务数的限制问题请教。

### ISSUE THREAD

**Issue by zhaojinzhou** [sogou/workflow#594]
请教下在构建图流程的时候，试图测试下并发效果。 
但在下面的例子中，同时并发的节点任务数，似乎受限于机器的核数。
这个参数是哪里可以设置的吗？
运行的结果是每次只同时执行cpu核数那么多个节点。 
分多次分批执行。 实际上可以同时并发，同时执行。 
期待 应该创建100个线程，实际上只创建了 接近CPU逻辑核那么多个线程。

![image](https://user-images.githubusercontent.com/16334836/137463522-32d06758-a090-4c35-8430-aff70f22eec9.png)

**Comment by chanchann** [comment]
就算是协程也没办法逃过线程的切换啊，你要并发就绕不过多线程的，这里的Series中的task不就相当于协程了吗，利用callback远比这些有栈协程高效普适

**Comment by chanchann** [comment]
其实不管协程也好，还是利用callback，框架的作者都帮你把脏活累活干了，我们只需要调用简单接口就可以完成各种任务了\﻿ (•◡•) /

**Comment by zhaojinzhou** [comment]
> 你好，感谢您对项目的肯定。
> 需要说明一下，虽然许多用户使用我们的框架做并行计算，但我们最大的优势是在于计算通讯的结合，特别是通讯与计算关系非常复杂的应用，可以把CPU利用率打满而不会出现慢请求。
> 如果只做纯计算，并且每个计算的粒度比较小的情况，虽然没有和taskflow做过对比，但是感觉我们应该没有优势，毕竟他们就是专门做并行计算的。work stealing我们没有，因为我们的应用里，默认计算任务都不会太轻，因此主要消耗在于计算本身而不是消息队列。
> 关于callback，我们的所有计算任务，callback就是计算结束在本线程直接调用，不会有切线程的开销。
> 欢迎继续使用我们的系统并随时反馈问题。

愚见。
我理解work stealing 被用于网络任务的时候，优化负载和时延比并行计算效果还好。这也是为什么baidu-rpc的同步和异步rpc全部默认使用bthread(实现了work stealing的线程)，期待更好。

**Comment by Barenboim** [comment]
可以这么写的：
~~~cpp
for (int i = 0; i < 100; i++) {
    a-->(*(b_t[i]))-->d;
}
~~~
'-->' operator is just for fun :) equal to:
a.precede(*b_t[i]).precede(d);
