### ISSUE TITLE
WebSocket 支持有问题

### ISSUE THREAD

**Issue by luangong** [sogou/workflow#616]
WebSocket 支持有问题，没有实现 random masking key，会导致示例程序 `websocket_cli` 崩溃退出。

首先用 Node.js 写了个简易的 WebSocket echo server，代码如下：

```js
const ws = require('ws');
const server = new ws.Server({ port: 8080 });

server.on('connection', (socket) => {
  socket.on('message', (data) => {
    console.log(data);
    socket.send(data);
  });
});

console.log(`Listening on ws://localhost:8080`);
```

然后编译并执行 tutorial 里的 `websocket_cli` 程序，在发送 frame 时崩溃退出，server 报错信息如下：

```
$ node server.js
Listening on ws://localhost:8080
events.js:377
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: MASK must be set
    at Receiver.getInfo (/Users/luangong/Documents/websocket/node_modules/ws/lib/receiver.js:289:16)
    at Receiver.startLoop (/Users/luangong/Documents/websocket/node_modules/ws/lib/receiver.js:136:22)
    at Receiver._write (/Users/luangong/Documents/websocket/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/Users/luangong/Documents/websocket/node_modules/ws/lib/websocket.js:1116:35)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/Users/luangong/Documents/websocket/node_modules/ws/lib/websocket.js:1002:13)
    at Receiver.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'WS_ERR_EXPECTED_MASK',
  [Symbol(status-code)]: 1002
}
```

在 macOS Catalina (10.15.7) 上执行 `websocket_cli` 报错信息如下：

```
$ ./websocket_cli ws://localhost:8080
send callback() state=0 error=0
opcode=8
websocket_cli(20393,0x70000bd67000) malloc: *** error for object 0x7f98c58048e2: pointer being freed was not allocated
websocket_cli(20393,0x70000bd67000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    20393 abort      ./websocket_cli ws://localhost:8080
```

网上搜了下说是由于没有设置 WebSocket masking key，于是在发送消息前加一行代码：

```diff
  WebSocketFrame *msg = task->get_msg();
+ msg->set_masking_key(0x12345678);
  msg->set_text_data("This is Workflow websocket client.");
```

这样 server 收发第一条消息是没问题的，但是 client 端在关闭连接的时候又崩溃了：

```
$ ./websocket_cli ws://localhost:8080
send callback() state=0 error=0
opcode=2
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
[1]    21025 abort      ./websocket_cli ws://localhost:8080
```

server 端还是提示没有设置 masking key，看了下 [WebSocket 规范](https://datatracker.ietf.org/doc/html/rfc6455#section-5)要求每个 client-to-server frame 的 masking key 都要不一样，于是我手动给 `WebSocketClient::create_ping_task()` 和 `WebSocketClient::create_close_task()` 也各加了一行 `msg->set_masking_key(...)`，现在关闭连接没问题了，server 没崩溃，但是 `websocket_cli` 还是崩溃，报错信息跟刚才的一样：

```
$ ./websocket_cli ws://localhost:8080
send callback() state=0 error=0
opcode=2
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
[1]    22975 abort      ./websocket_cli ws://localhost:8080
```

又去网上搜了下，说是可能因为 mutex 在一个线程里 lock 但在另一个线程里 unlock 导致的（[https://stackoverflow.com/q/66773247](https://stackoverflow.com/q/66773247)），这个涉及到 workflow 的线程管理与 mutex 使用机制，就没有再深究了，请 @holmes1412 和 @Barenboim 帮忙看下？

**Comment by Barenboim** [comment]
感谢试用我们的websocket分支。我们先把协议的问题改一下。因为我们都是后端团队没有websocket的应用场景，没有熟悉的同学一起搞，整个协议的实现是@holmes1412 独立查资料做的。目前这个协议交互还要很多问题需要解决……
谢谢你的反馈，我们尽量在websocket上多投入一点精力。

**Comment by luangong** [comment]
感谢 @Barenboim 及时的回复，我的一个朋友是做加密货币高频量化交易的，我帮忙打点杂，由于现在的加密货币交易所大多都提供基于 WebSocket 的订阅式 API 以推送交易信息，由于我们需要比较高的性能和实时性，虽然可以用 Node.js 写客户端但是 CPU 和 I/O 性能不够，所以看上了 workflow，我来先试用一下，再次感谢~

**Comment by Barenboim** [comment]
实在是抱歉，我们也想有多一些的应用场景。但目前我们还没有可以用于生产环境的websocket。
workflow项目主要应用场景还是后端的高性能高并发服务，计算与通讯结合，RPC。其他场景我们努力拓展一下。

**Comment by holmes1412** [comment]
@luangong 你好，关于masking key是协议里建议每个请求都不一样，所以workflow的websocket目前是提供了接口`set_masking_key()`可以用户自己设置，有个文档可以参考一下：[tutorial-14-websocket_cli.md](https://github.com/sogou/workflow/blob/websocket/docs/tutorial-14-websocket_cli.md)

另外，有些websocket server是不会严格要求，比如[uWebSockets](https://github.com/uNetworking/uWebSockets)，所以你不设置也可以用workflow的websocket的client与uWebSockets的server互通，我的tutorial也是这样测试的。

而如果你用的server有要求，可以使用接口进行设置。我在`WFWebSocketParams`里留了一个flag: random_masking_key是用做是否打开随机生成masking key的，这些在文档[websocket_cli的参数](https://github.com/sogou/workflow/blob/websocket/docs/tutorial-14-websocket_cli.md#websocket_cli的参数)中有提到，随机生成的功能正在开发中，合并master前肯定会完成，感谢提醒！

lock的问题怀疑和使用方有关？因为我们没有使用到异常，如果方便的话也可以把使用的代码贴出来看看。再次感谢反馈～

**Comment by luangong** [comment]
@holmes1412 我看协议里说每个 frame 的 masking key 都要不一样：

> The masking key is a 32-bit value chosen at random by the client.  When preparing a masked frame, the client MUST pick a fresh masking key from the set of allowed 32-bit values.  The masking key needs to be unpredictable; thus, the masking key MUST be derived from a strong source of entropy, and the masking key for a given frame MUST NOT make it simple for a server/proxy to predict the masking key for a subsequent frame.

具体就看各个 server 的实现对这个怎么理解和处理的了。

另外 `WebSocketClient::create_ping_task()` 和 `WebSocketClient::create_close_task()` 源代码里也需要加上 `msg->set_masking_key(...)`。

参见 https://datatracker.ietf.org/doc/html/rfc6455#section-5.3

**Comment by holmes1412** [comment]
嗯，如果手动设置的话确实有这个问题，masking key是每一种frame都有的，如果要手动设置的话确实用户就设置不到ping和close了。原先没有多试几种server的实现确实是有所疏忽了，通过client参数指定rand产生的方式我最近会支持上～

之后会按[tutorial-14-websocket_cli.md](https://github.com/sogou/workflow/blob/websocket/docs/tutorial-14-websocket_cli.md)里的client参数进行指定：
```cpp
struct WFWebSocketParams
{
    int idle_timeout;        // client保持长连接的空闲时间，超过idle_timeout没有数据过来会自动断开。默认：10s
    int ping_interval;       // client自动发ping的时间间隔，用于做心跳，保持与远端的连接。默认：-1，不自动发ping(功能开发中)
    size_t size_limit;       // 每个数据包的大小限制，超过的话会拿到错误码1009(WSStatusCodeTooLarge)。默认：不限制
    bool random_masking_key; // WebSocket协议中数据包的掩码，框架帮每次自动随机生成一个。默认：不自动生成(功能开发中)
};
```

**Comment by wasphin** [comment]
根据标准看, mask 作为客户端是必须的, 开放给用户感觉并没有什么必要.

https://datatracker.ietf.org/doc/html/rfc6455#section-5.1

```
   a client MUST mask all frames that it
   sends to the server (see Section 5.3 for further details).  (Note
   that masking is done whether or not the WebSocket Protocol is running
   over TLS.)  The server MUST close the connection upon receiving a
   frame that is not masked.
```

**Comment by holmes1412** [comment]
@wasphin 感谢提醒！如上回复哈，原先是发现某些client没有做这个功能，并且我互通的server也没有强制检查，所以实现第一版功能的时候就使用了提供接口设置的形式，另外也留了个配置让用户指定由框架随机生成。这个flag应该还是保留吧？但考虑到严谨性，等这两天支持上我会也把**默认配置设置为true，默认随机生成**～等改完了我会告知大家，如果觉得还不太合适，我会再作修改^_^~

**Comment by luangong** [comment]
推荐参考下 [Chromium 的 WebSocket 实现](https://chromium.googlesource.com/chromium/src/net/+/refs/heads/main/websockets)，连单元测试用例都可以借鉴，链接底部的参考资料也很有价值

**Comment by holmes1412** [comment]
> 推荐参考下 [Chromium 的 WebSocket 实现](https://chromium.googlesource.com/chromium/src/net/+/refs/heads/main/websockets)，连单元测试用例都可以借鉴，链接底部的参考资料也很有价值，不用完全从头开始造轮子

感谢！这个很有价值，我会认真参考其中的接口设计和过一下里边的case～
