### ISSUE TITLE
websocket 应该支持 /path

### ISSUE THREAD

**Issue by wasphin** [sogou/workflow#618]
我们在使用 websocket 的时候会设置 path, 类似 `ws://xxxx:xxx/ws` 这样, 对应到 HTTP Upgrade 请求中的时候, URI 应该为 `/path` 而不是 `/`.

https://github.com/sogou/workflow/blob/a8bce14af86f3057c7d5c45c82456c1f4ae86d49/src/factory/WebSocketTaskImpl.cc#L158

另外, Upgrade 的回复是有要求的, 必须为 `HTTP/1.1 101 Switching Protocols`, 即 HTTP 状态码为 101.

https://datatracker.ietf.org/doc/html/rfc6455

```
   The handshake from the server is much simpler than the client
   handshake.  The first line is an HTTP Status-Line, with the status
   code 101:

        HTTP/1.1 101 Switching Protocols

   Any status code other than 101 indicates that the WebSocket handshake
   has not completed and that the semantics of HTTP still apply.
```

由于 path 未支持, 导致未成功升级为 websocket 协议, 仍为 http 协议, 后续解析便无意义, `websocket_cli` 崩溃.

另外, `tutorial` 的建议的调试过程是怎样的? 两个 `cmake` 工程, 修改 `workflow` 源码后需要编译 `workflow` 再编译 `tutorial`, 有些繁琐. 是不是可以直接集成到 `workflow` 主工程中去, 通过选项开启/禁用 `tutorial`  的编译?

**Comment by holmes1412** [comment]
感谢建议！

1. 添加`/path`是漏了，原先没有注意到，这个马上给加上～
2. 判断回复101是有的，在[WebSocketTaskImpl.cc#L18](https://github.com/sogou/workflow/blob/websocket/src/factory/WebSocketTaskImpl.cc#L187)
```cpp
void ComplexWebSocketChannel::handle_in(CommMessageIn *in)
{
	...
	if (this->state == WFT_STATE_UNDEFINED)
	{
		HttpResponse *resp = static_cast<HttpResponse *>(in);

		if (strcmp(resp->get_status_code(), "101") == 0)
			this->state = WFT_STATE_SUCCESS;
		else
			this->state = WFT_STATE_TASK_ERROR;
		...
	}
```
3. 因为主目录和tutorial目录都添加了`GNUmakefile`，可以在主目录上`make && make tutorial`就可以一键编译`workflow`主工程和`tutorial`了，这样能方便一些。

**Comment by holmes1412** [comment]
@wasphin 感谢帮忙定位问题！path的修复已经提了一个 PR #619，麻烦有空了再看看还有什么建议>_<

**Comment by wasphin** [comment]
`/path` 是加上了, 但是回复 502 后看仍有数据发送, 这也是之前误以为未处理 101 的原因.

执行的命令:
```
./websocket_cli ws://192.168.3.216:8000/ws
```

抓包提取的 tcp 内容:
```
GET /ws HTTP/1.1
Host: 192.168.3.216
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==
Sec-WebSocket-Protocol: chat
Sec-WebSocket-Version: 13

HTTP/1.1 502 Bad Gateway
Server: nginx/1.19.6
Date: Mon, 01 Nov 2021 01:00:36 GMT
Content-Type: text/html
Content-Length: 157
Connection: keep-alive

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.19.6</center>
</body>
</html>
."....This is Workflow websocket client.HTTP/1.1 400 Bad Request
Server: nginx/1.19.6
Date: Mon, 01 Nov 2021 01:00:36 GMT
Content-Type: text/html
Content-Length: 157
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.19.6</center>
</body>
</html>
```

`Host` 中非标准端口(这里用的 8000)应该是要带上的. 参考: https://datatracker.ietf.org/doc/html/rfc2616/#section-14.23

**Comment by holmes1412** [comment]
了解，这个我排查一下！

**Comment by wasphin** [comment]
502 这个问题是因为添加了 `Sec-WebSocket-Protocol: chat` 导致的, 服务端未设置相关协议, 这个字段我理解应该由应用层根据需要去设置.

https://datatracker.ietf.org/doc/html/rfc6455#section-1.9
https://datatracker.ietf.org/doc/html/rfc6455#section-11.3.4

**Comment by holmes1412** [comment]
非常感谢！已经修改并提供接口让用户自行设置了。#646
麻烦再试试看～

**Comment by wasphin** [comment]
手动删除了 protocol 测试是没问题的，这一块修改应该问题不大。

但是从之前的抓包看，出错返回 502 后仍去发送了 websocket 数据，这个没看明白哪儿的状态有问题～

**Comment by holmes1412** [comment]
嗯，这也是我没有想明白的点～但我用的server也没有复现出这个情况。等以后复现了我肯定会再debug查一下🙏

**Comment by wasphin** [comment]
这边调试看, 返回非 101, 设置 channel 状态为失败后, 被这里又重置为成功了:
https://github.com/sogou/workflow/blob/dadf46dd44f6b124526310235cb87bb0aa40e1d8/src/factory/WFChannel.inl#L361

**Comment by wasphin** [comment]
测试可以了.

**Comment by holmes1412** [comment]
感谢~
