### ISSUE TITLE
[Redis Password] There will be 3001 error if redis password contains `+` and `=`

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#622]
当连接 redis 时，如果类似  `demostring+VeDemo==` 这样的密码，在连接 redis 时会报错。换密码后连接就没问题。

**Comment by Barenboim** [comment]
参考一下这个？
https://github.com/sogou/workflow/issues/537

**Comment by Barenboim** [comment]
issue有更新，需要使用StringUltil::encode_url_component接口。
