### ISSUE TITLE
[KafkaClient] 作为 Producer 写数据时某些 partition 无法自动恢复

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#624]
当 Kafka Client 写数据时，如果某个 partition 出现问题，则后续都不会往这个 partition 去写数据了，即使后续这个 partition 恢复正常了。能有办法定期检测 partition 是否恢复正常么？

**Comment by wzl12356** [comment]
是某个partition的leader挂了吗？另外机器的配置是个什么情况？（几个partition，几个副本）

**Comment by hiberabyss** [comment]
> 是某个partition的leader挂了吗？另外机器的配置是个什么情况？（几个partition，几个副本）

16 个 partition， 3 个副本

**Comment by wzl12356** [comment]
partition具体是出了什么问题？

**Comment by hiberabyss** [comment]
具体不清楚哈，kafka client 会提示连接超时：

```
Error Msg: Connection timed out
```

**Comment by wzl12356** [comment]
是说kafka集群本身并没有出问题是吗？只是client写数据失败？

**Comment by Barenboim** [comment]
@hiberabyss
