### ISSUE TITLE
workflow中的异步文件处理(win),异步耗时操作，多个异步流程的配合

### ISSUE THREAD

**Issue by lainswork** [sogou/workflow#628]
我想将Workflow与其他线程池、线程、或者异步系统一起使用
比如，实现一个文件服务器（win平台）:
我看到官方例子里面的文件服务器中使用了WFTaskFactory::create_pread_task来进行异步文件读写
但是win7平台是不支持的，在这个需求中，我能不能写一个线程池
当http请求进来时，将读写文件工作交给线程池，在不堵塞process（sogo Workflow框架）的情况下，当线程池将读取工作完成再对http进行下一步处理。再搞麻烦一点，每次提交给线程池后线程池每完成文件读取的1/n，都通知Workflow来处理已读取文件数据，将数据写到http应答。当文件整个全部完成读写，触发http请求完成。
类似的需求要怎么实现呢，需要哪些接口和api配合？

再比如：进程里一个http服务器，一个mysql客户端，接受http请求后查询数据库，查询完毕后返回http请求，类似的情况有项目例子可以参考吗？

对于服务端向客户端发送超大文件的疑惑:
将数据写入HttpResponse（append_output_body）时，http访问者是实时接收到数据的吗？假如我分多次调用append_output_body，那么访问方在我调用第二次append_output_body时，是否已经从tcp获得了我第一次添加的数据（假设每次调用append_output_body期间Workflow的异步tcp io行为已经结束）

最后再问：sogou-workflow可以在QT中使用吗？

**Comment by Barenboim** [comment]
都是非常好的问题，我分成几个回复吧。
先回答mysql客户端的问题。这是我们一个比较典型的应用，和tutorial05，tutorial09的原理是一样的，把mysql task插入http server task所在的series，mysql_callback里填写回复即可。代码大概这样：
~~~cpp
void mysql_callback(WFMySQLTask *mysql_task)
{
    auto *http_resp = (protocol::HttpResponse *)series_of(task)->get_context();

    if (mysql_task->get_state() != WFT_STATE_SUCCESS)
    {
        http_resp->set_status_code("503");
        return;
    }

    protocol::MySQLResultCursor cursor(mysql_task->get_resp());
    while (cursor.get_cursor_status() == MYSQL_STATUS_GET_RESULT)
    {
        /* fetch result here*/
        http_resp->append_out_body(...);
    }
}

void process(WFHttpTask *http_server_task)
{
    SeriesWork *series = series_of(http_server_task);
    series->set_context(http_server_task->get_resp());
    WFMySQLTask *mysql_task = create_mysql_task(..., mysql_callback);
    mysql_task->set_query("SELECT ...");
    series->push_back(mysql_task);
}
~~~

**Comment by Barenboim** [comment]
发送超大文件问题。append_output_body并不是立即发送的，都是在发送的时机一次性写。目前解决这个问题有一个不太完美的方法，就是server task是有push接口的，你可以查看这个issues：
https://github.com/sogou/workflow/issues/543
push接口实时同步推送数据。但是，这个接口并不能处理异步写。例如你push 10M数据，返回值可能是1M，代表把1M数据写入TCP buf。然后你可能需要通过timer自己来做等待和重试。这个接口可能比较适合于自定义协议。如果http server要使用这个接口，你还需要自己push前面的HTTP/1.1 200 OK以及header，push结束还需要调用一下server_task->noreply()，表示不用发起真正的回复。所以，push这个特征在http server不太实用，比较适用于自定协议的推送服务器。
总之HttpMessage::append_output_body并不是实时发送回复的（毕竟后面你还可能添加http header呢）。

**Comment by Barenboim** [comment]
Windows下文件任务的问题。本来windows下文件任务并不难，iocp是支持的。但我们现在windows的同学没有时间做这个功能开发。你提出的自定义线程池问题，是一个通用问题。不过我们有一种更加方便的手段，因为我们本身就可以退化为一个线程池。如果你不用计算任务，那你拿计算线程当作你线程池就可以了，从头到尾都创建go task就行。可以看这个issue和这个文档：
https://github.com/sogou/workflow/issues/484
https://github.com/sogou/workflow/blob/master/docs/about-go-task.md
但是，如果你自身有计算任务，那么你的线程任务（可能用于等待文件IO）就和计算任务抢线程了，显然不太合适。可以自己创建一个Executor和一个ExecQueue，Executor就相当于一个线程池，通过你自己的Executor和ExecQueue来创建ThreadTask或go task就可以了。
也就是说，我们内部的线程任务就可以满足你的需求，无需你自己去创建线程池。如果你非要自己搞线程池，也是可以的。因为我们本身就支持把一个非本框架的异步任务融合进来，你可以看一下counter的文档：
https://github.com/sogou/workflow/blob/master/docs/about-counter.md

**Comment by Barenboim** [comment]
QT里可以用的。不过我一直对我们的windows版不是太有信心，windows版也缺少一些功能。还是推荐使用纯unix版的master分支。

**Comment by lainswork** [comment]
> 发送超大文件问题.append_output_body并不是立即发送的，都是在发送的时机一次性写目前解决这个问题有一个不太完美的方法，就是服务器的任务是有推接口的，你可以查看这个问题： [＃ 543](https://github.com/sogou/workflow/issues/543) push 接口实时同步传输数据。，，这个接口并不能处理异步写入。例如可能你push 10M，返回值是1M 数据，代表把1M 数据写入TCP buf。然后你可能需要通过定时器自己来等待和重试。这个接口可能适合于自定义协议。如果http服务器要使用这个接口，你还需要自己push前面的HTTP/1.1 200 OKheader，push结束还需要调用一下server_task->noreply()，表示不用发起真正的回复。所以，推这个特征在http服务器不太实用，比较适用于自定协议的推送服务器。 总之HttpMessage :: append_output_body并不是实时发送回复的（毕竟后面你还可能添加http头呢） 。

**Comment by lainswork** [comment]
目前的WFNetworkTask有push 接口吗，只看到有noreply接口

**Comment by Barenboim** [comment]
汗，我忘了给Windows分支加了，下午我加一下。
tcp send buf影响的是一次写入的大小。整体数据多大都没问题，只要对方有在收。
这个buf操作系统会动态调整大小的。

**Comment by Barenboim** [comment]
好了，windows我也给加上了。

**Comment by lainswork** [comment]
> 发送超大文件问题。append_output_body并不是立即发送的，都是在发送的时机一次性写。目前解决这个问题有一个不太完美的方法，就是server task是有push接口的，你可以查看这个issues： #543 push接口实时同步推送数据。但是，这个接口并不能处理异步写。例如你push 10M数据，返回值可能是1M，代表把1M数据写入TCP buf。然后你可能需要通过timer自己来做等待和重试。这个接口可能比较适合于自定义协议。如果http server要使用这个接口，你还需要自己push前面的HTTP/1.1 200 OK以及header，push结束还需要调用一下server_task->noreply()，表示不用发起真正的回复。所以，push这个特征在http server不太实用，比较适用于自定协议的推送服务器。 总之HttpMessage::append_output_body并不是实时发送回复的（毕竟后面你还可能添加http header呢）。

http1.1里面有个叫分块传输编码（Chunked transfer encoding）的协议，是在写入基本的http头部后，按照规则将分散开的chunk块内存写入到tcp buf，这样能实现大文件传输，还有一个断点续传协议Accept-Ranges Content-Range。
不过不管协议是怎么定的，想要实现超大文件传输的话，就只能做到实时写入tcp，因为我们无法在服务上将磁盘的整个文件读取到内存然后交给HttpResponse（即使workflow底层是将数据分块写入的，我们也无法做到将超大文件读取到内存）

**Comment by Barenboim** [comment]
> > 发送超大文件问题。append_output_body并不是立即发送的，都是在发送的时机一次性写。目前解决这个问题有一个不太完美的方法，就是server task是有push接口的，你可以查看这个issues： #543 push接口实时同步推送数据。但是，这个接口并不能处理异步写。例如你push 10M数据，返回值可能是1M，代表把1M数据写入TCP buf。然后你可能需要通过timer自己来做等待和重试。这个接口可能比较适合于自定义协议。如果http server要使用这个接口，你还需要自己push前面的HTTP/1.1 200 OK以及header，push结束还需要调用一下server_task->noreply()，表示不用发起真正的回复。所以，push这个特征在http server不太实用，比较适用于自定协议的推送服务器。 总之HttpMessage::append_output_body并不是实时发送回复的（毕竟后面你还可能添加http header呢）。
> 
> http1.1里面有个叫分块传输编码（Chunked transfer encoding）的协议，是在写入基本的http头部后，按照规则将分散开的chunk块内存写入到tcp buf，这样能实现大文件传输，还有一个断点续传协议Accept-Ranges Content-Range。 不过不管协议是怎么定的，想要实现超大文件传输的话，就只能做到实时写入tcp，因为我们无法在服务上将磁盘的整个文件读取到内存然后交给HttpResponse（即使workflow底层是将数据分块写入的，我们也无法做到将超大文件读取到内存）

嗯嗯，我知道chunk编码的目的。只是说大文件传输确实不是我们的专长。
