### ISSUE TITLE
kafka一次produce task最多支持多少record?

### ISSUE THREAD

**Issue by csyourui** [sogou/workflow#631]
在使用中发现task->add_produce_record方法可以增加record，比较好奇这个最多可以加入多少record，是否和一条record的大小有关？

**Comment by Barenboim** [comment]
可以无限加！太大了内部会帮你拆包。
@wzl12356

**Comment by wzl12356** [comment]
会受到kafka_config_t中produce_msg_max_bytes produce_msgset_cnt produce_msgset_max_bytes 这三个的限制，这个是kafka协议定的。
除此之外没有限制，内部会合并包发送。

**Comment by Barenboim** [comment]
@csyourui
