### ISSUE TITLE
windows下http服务不能正确返回

### ISSUE THREAD

**Issue by ussturn** [sogou/workflow#639]
void process(WFHttpTask* server_task)
{
 protocol::HttpRequest* req = server_task->get_req();
 protocol::HttpResponse* res = server_task->get_resp();

 //此行不调用http 服务不能正确返回，客户端socket会处于挂起状态。
 res->set_http_version(req->get_http_version());
}

**Comment by Barenboim** [comment]
按道理，server task是会自动加上HTTP/1.1的，代码在：
https://github.com/sogou/workflow/blob/windows/src/factory/HttpTaskImpl.cc#L864
是不是你的client只能识别HTTP/1.0 ?

**Comment by Barenboim** [comment]
你好，麻烦帮我们确认一下是不是这个问题，然后回复一下啊。
@ussturn
