### ISSUE TITLE
tutorial/tutorial-12-mysql_cli.cc 例子里的series和issues里提到的blockseries有什么区别，分别在什么场景下用

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#640]
任务执行完后，series是不是会自动退出；blockseries不会自动退出？其他区别呢？

**Comment by Barenboim** [comment]
嗯嗯，正常的series当队列里已经没有任务了，就会callback并结束。blockseries通过一个counter把series堵住不让队列空，也就不会结束了，随时可以往末尾添加任务。
不过，因为WFResourcePool的加入，blockseries可以用resource pool来实现。
