### ISSUE TITLE
请问对WorkFlow框架有没有未来的日程规划表呢

### ISSUE THREAD

**Issue by xuebing1995** [sogou/workflow#644]

**Comment by Barenboim** [comment]
还是说一说你有什么具体需求吧：）时间表太难给了。

**Comment by xuebing1995** [comment]
目前正在研究这个框架，此框架基本内容很健全，但是对于改造框架完整性还不够，如日志模块、单元测试等模块化内容是否有计划加入。因为模块健全后更方便开发者形成全家桶式使用，仅需少量开发即可融入项目中使用，使开发变得更简单。所以想知道您对此框架后续发展有没有一个计划（在哪个时间点添加某些功能、模块等）。

**Comment by Barenboim** [comment]
我们的目标不是做全家桶。以log模块为例，我们不会绑定一个确定的log模块，因为这样不但多一个依赖，而且也限制了用户的使用方法。
workflow的生态有很多项目，都在sogou的空间下，比如：
1. [srpc](https://github.com/sogou/srpc) ，可以对接opentelemetry的链路追踪上报。
2. [wf-prometheus](https://github.com/sogou/wf-prometheus)。基于workflow的prometheus exporter，用于向prometheus上报metrics。
3. [workflow-k8s](https://github.com/sogou/workflow-k8s)。workflow对接k8s服务推送的插件。

**Comment by xuebing1995** [comment]
好的，顺便问下您：我看最新的代码配置和之前有所变动；
1.poller、handler和 compute我看最新的代码默认值是这样的，这个出于什么考虑设置的2、20和默认使用CPU核数；
2.当应用（IO密集或CPU密集）时又该如何设置合理这三个值，或者在设计之初如何考量这三者的关系比例，才能达到最大性能；

**Comment by Barenboim** [comment]
poller thread主分支好像是4了，你看的是Windows?
默认值都是一些经验值，为了让大多数用户不用调整就可以获得比较好的性能。实际业务中，如果io量比较大可以增加poller，业务逻辑比较多或qps比较大可以增加handler。计算的话，就看你要用多少计算资源了。如果没有使用到计算任务，计算线程也不会创建。
具体都是要实测一下比较好。

**Comment by xuebing1995** [comment]
好的，感谢，希望workflow发扬光大!!!!
