### ISSUE TITLE
TCP server 如何主动发数据给到客户端

### ISSUE THREAD

**Issue by zxj123qweasdqq** [sogou/workflow#649]
Windows下面TCP 协议server端如何主动发数据给客户端，是要把task 保存然后push 数据吗？
;

**Comment by holmes1412** [comment]
你好，如果想用push接口的话，可以参考一下这个回复中的用法：https://github.com/sogou/workflow/issues/628#issuecomment-962638634

**Comment by Barenboim** [comment]
其实，本质上我们并不支持server主动向client发数据。后来加了个push接口，用于解决一些server推送的场景，可以做Kubernetes API Server那样的推送，但本质上还是http协议。
