### ISSUE TITLE
通过workflow实现转发功能的问题

### ISSUE THREAD

**Issue by willreno1987** [sogou/workflow#658]
服务器A-->转发服务器(workflow实现)--->服务器B(workflow实现)，要求B的vitrual CommConnection* new_connection(int accept_fd)函数中能读取到A的ip，可以实现么？

**Comment by Barenboim** [comment]
楠楠同学，我先指出一下你这个问题本身的问题哈。提issue的时候，最好直接说明你的实际需求，而不是说你试图解决的方案。你可以先参考一下这个XY problem：http://xyproblem.info

**Comment by willreno1987** [comment]
简单的说一下应用场景：A服务器通过代理服务器发消息给服务器B，B服务器需要根据A的IP来判断是否可以访问。只有B服务器有服务器白名单IP的列表。代理服务器怎么使用workflow实现，来让B能识别A的ip。

**Comment by Barenboim** [comment]
你肯定没有办法通过proxy和B的连接fd，取得A的IP地址的。所以这事并不能通过实现B的new_connection虚函数来实现。而且通过new_connection实现的话，只能简单在断开连接，proxy也无法知道B是什么原因不接受请求。
我觉得可以在proxy的process里，把A的地址拿出来，放到http header里转给B：
~~~cpp
void proxy_process(WFHttpTask *task)
{
    struct sockaddr_storage ss;
    socklen_t addrlen = sizeof *ss;
    if (task->get_peer_addr(&ss, &addrlen) == 0)
    {
        //add a header;
    }
}
~~~
B如果在header里发现来源IP不是白名单，返回一个403之类的响应。如果做得细一点，proxy可以记录下来这个IP是被禁止的，这样proxy可以实现new_connection直接拒绝这个IP的下一次连接，或者下次直接给这个IP返回403

**Comment by willreno1987** [comment]
感觉谢爷的回答。首先**“proxy可以记录下来这个IP是被禁止的，这样proxy可以实现new_connection直接拒绝这个IP的下一次连接”**这个是不可以的，B的白名单的变化频率非常的高，如果这么做，需要涉及B和proxy白名单数据一致性的问题，会增加整个问题的复杂度。
