### ISSUE TITLE
MySQL Connection Spike from Workflow

### ISSUE THREAD

**Issue by redkongdong** [sogou/workflow#661]
Problem statement: We have multiple MySQL shards, and only one shard has abnormal connections spike(keep for 3 mins) at one time. 

And we have own client throttle logic which limits max on-the-fly request concurrency and use round robin for load balance.
If it is our throttle limit bug, all shards should have connections spikes at the same time instead only one.

Please help on this issue.

**Comment by Barenboim** [comment]
You may limit the concurrency of accessing any resource by using WFResourcePool.
Here is an example of limiting the max concurrent connections to MySQL server to 50:
~~~cpp
#include "workflow/WFResourcePool.h"
#include "workflow/WFTaskFactory.h"

WFResourcePool respool(50);  // resource numbers

void mysql_callback(WFMySQLTask *task)
{
    respool.post(NULL);  // post back the resource
    ...
}

void my_func()
{
    WFMySQLTask *mysql_task = WFTaskFactory::create_mysql_task(..., mysql_callback);
    // get a resource from resource pool.
    WFConditional *cond = respool.get(mysql_task);
    cond->start(); // or series->push_back(cond);
}
~~~
More information about resource pool: https://github.com/sogou/workflow/blob/master/docs/about-conditional.md

**Comment by redkongdong** [comment]
> I wonder it's a bug of your client:)
> 
> And you may limit the concurrency of accessing any resource by using WFResourcePool. Here is an example of limiting the max concurrent connections to MySQL server to 50:
> 
> ```c++
> #include "workflow/WFResourcePool.h"
> #include "workflow/WFTaskFactory.h"
> 
> WFResourcePool respool(50);  // resource numbers
> 
> void mysql_callback(WFMySQLTask *task)
> {
>     respool.post(NULL);  // post back the resource
>     ...
> }
> 
> void my_func()
> {
>     WFMySQLTask *mysql_task = WFTaskFactory::create_mysql_task(..., mysql_callback);
>     // get a resource from resource pool.
>     WFConditional *cond = respool.get(mysql_task);
>     cond->start(); // or series->push_back(cond);
> }
> ```
> 
> More information about resource pool: https://github.com/sogou/workflow/blob/master/docs/about-conditional.md

Hey Barenboim,

Can this pool size be dynamiclly changed?

**Comment by Barenboim** [comment]
> > I wonder it's a bug of your client:)
> > And you may limit the concurrency of accessing any resource by using WFResourcePool. Here is an example of limiting the max concurrent connections to MySQL server to 50:
> > ```c++
> > #include "workflow/WFResourcePool.h"
> > #include "workflow/WFTaskFactory.h"
> > 
> > WFResourcePool respool(50);  // resource numbers
> > 
> > void mysql_callback(WFMySQLTask *task)
> > {
> >     respool.post(NULL);  // post back the resource
> >     ...
> > }
> > 
> > void my_func()
> > {
> >     WFMySQLTask *mysql_task = WFTaskFactory::create_mysql_task(..., mysql_callback);
> >     // get a resource from resource pool.
> >     WFConditional *cond = respool.get(mysql_task);
> >     cond->start(); // or series->push_back(cond);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > More information about resource pool: https://github.com/sogou/workflow/blob/master/docs/about-conditional.md
> 
> Hey Barenboim,
> 
> Can this pool size be dynamiclly changed?

The may try to subclass WFResroucePool and make it's size dynamic.

**Comment by Barenboim** [comment]
It seems that you are using a pretty old version of workflow. Please update to the latest release.

**Comment by redkongdong** [comment]
It is because one of mysql servers becomes slower.

**Comment by Barenboim** [comment]
You may use the kernel scheudler's load balancing to solve this problem. Just add all the mysql server's IP addresses to a single domain name. The scheduler will consider the load of each IP when selecting communication target.
