### ISSUE TITLE
Where is EndpointAddress released at UpstreamManager remove?

### ISSUE THREAD

**Issue by redkongdong** [sogou/workflow#670]
Please help point out the reference count used by EndpointAddress at release?
Thx.

**Comment by holmes1412** [comment]
Hi, we do use reference count for EndpointAddress, to keep those EndpointAddresses which are using by tasks remained during upstream_remove() is called.

This is a very common usage and you may find the **ref** in https://github.com/sogou/workflow/blob/master/src/nameservice/WFServiceGovernance.h#L82
```cpp
class EndpointAddress                                                              
{                                                                                  
public:                                                                            
    std::string address;                                                           
    std::string host;                                                              
    std::string port;                                                              
    unsigned int fail_count;                                                       
    std::atomic<int> ref;                                                                                                               
    ...                         
};       
```
The **ref** will set as 1 in constructor `EndpointAddress()`, increased every time its EndpointAddress is selected in `select()` by tasks,  and decreased every time the tasks return it back which reflects in the `tracing_deleter()`. It will also be decreased when you call `upstream_remove()`.

**Comment by redkongdong** [comment]
Thanks, @holmes1412
