### ISSUE TITLE
server callback设置为类成员函数时报错

### ISSUE THREAD

**Issue by grapefruitL** [sogou/workflow#671]
我想封装一个类用来启动图像处理服务，封装的原因是方便其他同事调用：他们重载类里面图像处理的部分就行了。
因此我将server的callback写成了类成员函数，编译以下代码
```
WFHttpServer server(&params, this->process);
this->serverHandle = &server;
```
时产生报错：
```
error: no matching function for call to ‘WFServer<protocol::HttpRequest, protocol::HttpResponse>::WFServer(WFServerParams*, <unresolved overloaded function type>)’
  WFHttpServer server(&params, this->process);
```

**Comment by holmes1412** [comment]
你好，这个server的`process`类型（没理解错的话就是你说的server的callback），是个`std::function<void (WFHttpTask *)>`，可以参考https://github.com/sogou/workflow/blob/master/src/server/WFHttpServer.h

如果你是类成员的函数，那么成员函数至少有个this指针，这样的话，你需要bind掉函数参数才可以的。

可以检查一下你的类型是否和process的类型严格一直。

**Comment by Barenboim** [comment]
非静态成员函数是不能传给std::function的。需要先std::bind一下。
~~~cpp
auto process = std::bind(&MyClass::process, this, std::place_holders::1);
WFHttpServer server(&params, std::move(process));
~~~
另外，注意一下process不是callback。server task有callback，是在回复完成之后调用的。

**Comment by Barenboim** [comment]
@grapefruitL

**Comment by grapefruitL** [comment]
@Barenboim @holmes1412 谢谢！
