### ISSUE TITLE
如何知道当前workflow是处于忙的状态

### ISSUE THREAD

**Issue by willreno1987** [sogou/workflow#674]
请问大神，怎么知道当前httpserver是处于忙碌的状态。因为业务需要，在当时服务器如果特别忙的时候则不进行某些逻辑的触发。

**Comment by Barenboim** [comment]
业务的忙碌与否，可能需要应用层自己来定义。WFServer有个get_conn_count()的函数，但这个函数只能得到总的连接数，包括了处于keep-alive状态的连接，并不能反映server的忙碌程度。
