### ISSUE TITLE
wget例子访问python搭建的httpserver，报错system error:connection reset by peer

### ISSUE THREAD

**Issue by zhouyi19930811** [sogou/workflow#677]
在linux PC上，使用python -m SimpleHTTPServer 8000搭建httpsever，然后使用master分支，编译样例，运行./wget http://ip:8000，报错system error:connection reset by peer。请支持解决一下，谢谢。

**Comment by Barenboim** [comment]
你好。你试试./wget http://ip:8000/ 这么写能不能成功，就是加上"/"。
我们最近修复了URIParser的一个问题。之前URIParser遇到URL里没有path，解析有点问题。
如果加上"/"可以成功，你更新一下代码就可以了。

**Comment by Barenboim** [comment]
你好，我用python SimpleHTTPServer验证了这个问题。这是workflow v0.9.8 URI parser的一个bug。你只要把代码更新到最新，或者URL里加上"/"，问题都可以解决。建议更新一下代码。

**Comment by zhouyi19930811** [comment]
更新代码后，已经解决了这个问题，谢谢。
