### ISSUE TITLE
有关windows编译问题

### ISSUE THREAD

**Issue by supermanmsc** [sogou/workflow#68]
在linux下轻松的编译过了, 但是...

我切换到windows分之后, 编译无法通过, 希望有相关的文档可以参考, 

修改代码 添加openssl库
[src/CMakeLists.txt :2] 
+ list(APPEND CMAKE_PREFIX_PATH "D:/workflow/openssl-v1.0.0-x86")

cmake配置: Visual Studio 12 x86  Release

报错如下
[main] 正在生成文件夹: workflow 
[build] 正在启动生成
...
...
[build] D:\workflow\src\util\URIParser.cc(351): warning C4996: '_strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [D:\workflow\build\src\util\util.vcxproj]

[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(235): error C2011: “sockaddr”:“struct”类型重定义 (编译源文件 D:\workflow\src\server\WFServer.cc) [D:\workflow\build\src\server\server.vcxproj]

[build] D:\workflow\src\client\WFMySQLConnection.cc(41): warning C4996: '_strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [D:\workflow\build\src\client\client.vcxproj]
[build] D:\workflow\_include\workflow\RedisMessage.h(329): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\HttpTaskImpl.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] D:\workflow\_include\workflow\RedisMessage.h(329): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\MySQLTaskImpl.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\string.h(143): note: 参见“_strdup”的声明
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(1007): note: 参见“sockaddr”的声明 (编译源文件 D:\workflow\src\server\WFServer.cc)
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\string.h(143): note: 参见“_strdup”的声明
[build] D:\workflow\src\util\URIParser.cc(358): warning C4996: '_strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [D:\workflow\build\src\util\util.vcxproj]
[build] D:\workflow\_include\workflow\HttpMessage.h(62): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\HttpTaskImpl.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(437): error C2059: 语法错误:“常量” (编译源文件 D:\workflow\src\server\WFServer.cc) [D:\workflow\build\src\server\server.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(437): error C3805: “常量”: 意外标记，应输入“}”或者“,” (编译源文件 D:\workflow\src\server\WFServer.cc) [D:\workflow\build\src\server\server.vcxproj]
[build] D:\workflow\_include\workflow\HttpMessage.h(67): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\HttpTaskImpl.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(572): warning C4005: “IN_CLASSA”: 宏重定义 (编译源文件 D:\workflow\src\server\WFServer.cc) [D:\workflow\build\src\server\server.vcxproj]
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(284): note: 参见“IN_CLASSA”的前一个定义 (编译源文件 D:\workflow\src\server\WFServer.cc)
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\string.h(143): note: 参见“_strdup”的声明
[build] D:\workflow\_include\workflow\HttpMessage.h(62): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\MySQLTaskImpl.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] D:\workflow\_include\workflow\HttpMessage.h(67): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\MySQLTaskImpl.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] D:\workflow\_include\workflow\RedisMessage.h(329): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\WFTaskFactory.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] D:\workflow\_include\workflow\HttpMessage.h(62): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\WFTaskFactory.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(578): warning C4005: “IN_CLASSB”: 宏重定义 (编译源文件 D:\workflow\src\server\WFServer.cc) [D:\workflow\build\src\server\server.vcxproj]
[build] D:\workflow\src\util\URIParser.cc(365): warning C4996: '_strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [D:\workflow\build\src\util\util.vcxproj]
[build] D:\workflow\_include\workflow\HttpMessage.h(67): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\factory\WFTaskFactory.cc) [D:\workflow\build\src\factory\factory.vcxproj]
[build] D:\workflow\src\factory\WFTaskFactory.cc(55): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) [D:\workflow\build\src\factory\factory.vcxproj]
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(290): note: 参见“IN_CLASSB”的前一个定义 (编译源文件 D:\workflow\src\server\WFServer.cc)
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(457): note: 参见“AF_IPX”的前一个定义 (编译源文件 D:\workflow\src\manager\RouteManager.cc)
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(147): warning C4005: “AF_MAX”: 宏重定义 (编译源文件 D:\workflow\src\manager\RouteManager.cc) [D:\workflow\build\src\manager\manager.vcxproj]
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(476): note: 参见“AF_MAX”的前一个定义 (编译源文件 D:\workflow\src\manager\RouteManager.cc)
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(185): warning C4005: “SO_DONTLINGER”: 宏重定义 (编译源文件 D:\workflow\src\manager\RouteManager.cc) [D:\workflow\build\src\manager\manager.vcxproj]
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(399): note: 参见“SO_DONTLINGER”的前一个定义 (编译源文件 D:\workflow\src\manager\RouteManager.cc)
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared\ws2def.h(235): error C2011: “sockaddr”:“struct”类型重定义 (编译源文件 D:\workflow\src\manager\RouteManager.cc) [D:\workflow\build\src\manager\manager.vcxproj]
[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(1007): note: 参见“sockaddr”的声明 (编译源
.
.
.
.
.

[build]   C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\winsock.h(1007): note: 参见“sockaddr”的声明 (编译源文件 D:\workflow\src\protocol\HttpUtil.cc)
[build] D:\workflow\_include\workflow\Communicator.h(204): error C2227: “->sa_family”的左边必须指向类/结构/联合/泛型类型 (编译源文件 D:\workflow\src\protocol\HttpUtil.cc) [D:\workflow\build\src\protocol\protocol.vcxproj]
[build] d:\workflow\src\protocol\HttpMessage.h(62): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\protocol\HttpUtil.cc) [D:\workflow\build\src\protocol\protocol.vcxproj]
[build] d:\workflow\src\protocol\HttpMessage.h(67): warning C4800: “int”: 将值强制为布尔值“true”或“false”(性能警告) (编译源文件 D:\workflow\src\protocol\HttpUtil.cc) [D:\workflow\build\src\protocol\protocol.vcxproj]
[build] 生成已完成，退出代码为 1

**Comment by holmes1412** [comment]
@supermanmsc 你好～想确认下两个事情：

  * 是否是从https://github.com/sogou/workflow.git上checkout下来的呢？
    * 因为我看到你star的是我fork的分支，不是sogou下的项目主cangku～可以star这个主仓库😉

  * checkout下来后编译windows需要切换到windows分支：
    * ``git checkout windows`` 再编译～

**Comment by supermanmsc** [comment]
![image](https://user-images.githubusercontent.com/12078448/94384398-17618300-0175-11eb-8ba4-c2bc36659b24.png)
我确实是从sogou/workflow.git上下载的,

**Comment by supermanmsc** [comment]
编译的时候不能使用 1.0.0的openssl  ,详细信息如下:
参考这个网址:
https://blog.csdn.net/SUKHOI27SMK/article/details/55000279
![image](https://user-images.githubusercontent.com/12078448/94387463-c81f5080-017c-11eb-8863-36a0a0b3d1e3.png)
![image](https://user-images.githubusercontent.com/12078448/94387468-cbb2d780-017c-11eb-9b0a-fe4475c330f0.png)

在1.0.0的openssl里, 包含了windows.h文件, 导致许多结构重定义了, 1.1.1的里面没有包含这个文件.

另外使用vs2019的小伙伴, 注意cmake版本, 官网对3.18版本的releasenode如下:
https://cmake.org/cmake/help/v3.18/release/3.18.html
最后面说, 3.18里才支持2019 但是我感觉使用3.17的cmake也可以, 3.17也没说不支持2019, 不能应为3.18说支持了2019就说3.17不支持. 哈哈.
