### ISSUE TITLE
回包的时候不定期core，请问有遇到过么（MySQL client）？

### ISSUE THREAD

**Issue by chenlinzhong** [sogou/workflow#682]
回包的时候不定期core，下面是Sanitizer分析得到的core栈，请问有遇到过么？可能是什么原因呢？

AddressSanitizer:DEADLYSIGNAL
=================================================================
==37681==ERROR: AddressSanitizer: BUS on unknown address 0x000000000000 (pc 0x7ff8ae4d90de bp 0xbebebebebebebeae sp 0x7ff89b0feef0 T26)
    #0 0x7ff8ae4d90dd  (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x2f0dd)
    #1 0x7ff8ae595b8a in __interceptor_free (/opt/compiler/gcc-8.2/lib/libasan.so.5+0xebb8a)
    #2 0x9be470 in mysql_parser_deinit /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/protocol/mysql_parser.c:62
    #3 0x9bea6b in protocol::MySQLMessage::~MySQLMessage() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/protocol/MySQLMessage.cc:43
    #4 0x9c7d70 in protocol::MySQLResponse::~MySQLResponse() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/_include/workflow/MySQLMessage.h:88
    #5 0x9c7d70 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::clear_resp() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTaskFactory.inl:186
    #6 0x9c7d70 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::switch_callback(WFTimerTask*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTaskFactory.inl:421
    #7 0x9c7f69 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::done() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTaskFactory.inl:486
    #8 0x9d1696 in SubTask::subtask_done() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/SubTask.cc:31
    #9 0x9cf5b9 in Communicator::handle_incoming_reply(poller_result*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/Communicator.cc:691
    #10 0x9d116a in Communicator::handler_thread_routine(void*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/Communicator.cc:1093
    #11 0x9e148c in __thrdpool_routine /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/thrdpool.c:72
    #12 0x7ff8ae492da3 in start_thread /home/liruihao/mygcc82/glibc-2.21/nptl/pthread_create.c:333
    #13 0x7ff8ae0f932c in clone (/opt/compiler/gcc-8.2/lib/libc.so.6+0xeb32c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x2f0dd)
Thread T26 created by T0 here:
    #0 0x7ff8ae4f6f50 in pthread_create (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x4cf50)
    #1 0x9e1683 in __thrdpool_create_threads /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/thrdpool.c:156
    #2 0x9e1683 in thrdpool_create /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/thrdpool.c:192

==37681==ABORTING

**Comment by holmes1412** [comment]
你好，请问这是个mysql请求吗？请求的语句是否方便发一下？

另外发现你现在的代码并不是最新的，可以升级下最新代码试试看是否还有问题。

**Comment by chenlinzhong** [comment]
回复的好快，给力，不是mysql的，我们连的是一个newsql，兼容mysql协议，好的，我们先试试

**Comment by holmes1412** [comment]
哈哈我们也和tidb协议兼容>_<~~~所以按说是MySQL协议就木有问题~~~

另外怀疑是retry引起的，你也可以把请求的retry配到0试试看还有没有这个core。

如果升级代码还不行，可以告知一下是什么newsql，我们也整一个试试。

**Comment by chenlinzhong** [comment]
我们升级了下，对比retry调整为前后，发现retry调整为0后稳定性提升明显，并发跑了2小时进程也正常（之前是半小时内必core），截止目前还未出core，想了解下为啥建议调整retry呢？

**Comment by Barenboim** [comment]
请问一下，新代码在有retry的情况下，还有问题吗？
之前那个core是在retry过程中发生的。

**Comment by chenlinzhong** [comment]
> 
core不确定是不是在retry过程中发生的
新代码在有retry的情况下，跟旧代码的core栈表现上是一样的
把retry调整到0后，现在看着还比较正常

**Comment by Barenboim** [comment]
> core不确定是不是在retry过程中发生的
> 新代码在有retry的情况下，跟旧代码的core栈表现上是一样的
> 把retry调整到0后，现在看着还比较正常

也就是说，新代码在有retry的情况下，也出现过core？我们马上查

**Comment by chenlinzhong** [comment]
是的，把retry调整为0，跑了3小时，还是出core了

AddressSanitizer:DEADLYSIGNAL
=================================================================
==34506==ERROR: AddressSanitizer: BUS on unknown address 0x000000000000 (pc 0x7f31117a60de bp 0xbebebebebebebeae sp 0x7f30fc58dec0 T29)
    #0 0x7f31117a60dd  (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x2f0dd)
    #1 0x7f3111862b8a in __interceptor_free (/opt/compiler/gcc-8.2/lib/libasan.so.5+0xebb8a)
    #2 0x9bd860 in mysql_parser_deinit /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/protocol/mysql_parser.c:62
    #3 0x9bde5b in protocol::MySQLMessage::~MySQLMessage() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/protocol/MySQLMessage.cc:43
    #4 0x9c8886 in protocol::MySQLResponse::~MySQLResponse() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/_include/workflow/MySQLMessage.h:88
    #5 0x9c8886 in WFNetworkTask<protocol::MySQLRequest, protocol::MySQLResponse>::~WFNetworkTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/WFTask.h:312
    #6 0x9c8886 in WFClientTask<protocol::MySQLRequest, protocol::MySQLResponse>::~WFClientTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/WFTask.inl:111
    #7 0x9c8886 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::~WFComplexClientTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/WFTaskFactory.inl:97
    #8 0x9c8886 in ComplexMySQLTask::~ComplexMySQLTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/MySQLTaskImpl.cc:40
    #9 0x9c8886 in ComplexMySQLTask::~ComplexMySQLTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/MySQLTaskImpl.cc:40
    #10 0x9c7b14 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::switch_callback(WFTimerTask*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/WFTaskFactory.inl:435
    #11 0x9c7c09 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::done() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/factory/WFTaskFactory.inl:495
    #12 0x9d0946 in SubTask::subtask_done() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/kernel/SubTask.cc:31
    #13 0x9ce889 in Communicator::handle_incoming_reply(poller_result*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/kernel/Communicator.cc:702
    #14 0x9d041a in Communicator::handler_thread_routine(void*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/kernel/Communicator.cc:1104
    #15 0x9dfe5c in __thrdpool_routine /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/kernel/thrdpool.c:72
    #16 0x7f311175fda3 in start_thread /home/liruihao/mygcc82/glibc-2.21/nptl/pthread_create.c:333
    #17 0x7f31113c632c in clone (/opt/compiler/gcc-8.2/lib/libc.so.6+0xeb32c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x2f0dd)
Thread T29 created by T0 here:
    #0 0x7f31117c3f50 in pthread_create (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x4cf50)
    #1 0x9e0053 in __thrdpool_create_threads /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/kernel/thrdpool.c:156
    #2 0x9e0053 in thrdpool_create /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace/baidu/third-party/sogou-workflow/src/kernel/thrdpool.c:192

==34506==ABORTING

**Comment by chenlinzhong** [comment]
新代码, retry=0，稳定了一些跑了3个小时小时，还是出core了

AddressSanitizer:DEADLYSIGNAL
=================================================================
==34506==ERROR: AddressSanitizer: BUS on unknown address 0x000000000000 (pc 0x7f31117a60de bp 0xbebebebebebebeae sp 0x7f30fc58dec0 T29)
    #0 0x7f31117a60dd  (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x2f0dd)
    #1 0x7f3111862b8a in __interceptor_free (/opt/compiler/gcc-8.2/lib/libasan.so.5+0xebb8a)
    #2 0x9bd860 in mysql_parser_deinit /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/protocol/mysql_parser.c:62
    #3 0x9bde5b in protocol::MySQLMessage::~MySQLMessage() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/protocol/MySQLMessage.cc:43
    #4 0x9c8886 in protocol::MySQLResponse::~MySQLResponse() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/_include/workflow/MySQLMessage.h:88
    #5 0x9c8886 in WFNetworkTask<protocol::MySQLRequest, protocol::MySQLResponse>::~WFNetworkTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTask.h:312
    #6 0x9c8886 in WFClientTask<protocol::MySQLRequest, protocol::MySQLResponse>::~WFClientTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTask.inl:111
    #7 0x9c8886 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::~WFComplexClientTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTaskFactory.inl:97
    #8 0x9c8886 in ComplexMySQLTask::~ComplexMySQLTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/MySQLTaskImpl.cc:40
    #9 0x9c8886 in ComplexMySQLTask::~ComplexMySQLTask() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/MySQLTaskImpl.cc:40
    #10 0x9c7b14 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::switch_callback(WFTimerTask*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTaskFactory.inl:435
    #11 0x9c7c09 in WFComplexClientTask<protocol::MySQLRequest, protocol::MySQLResponse, bool>::done() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/factory/WFTaskFactory.inl:495
    #12 0x9d0946 in SubTask::subtask_done() /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/SubTask.cc:31
    #13 0x9ce889 in Communicator::handle_incoming_reply(poller_result*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/Communicator.cc:702
    #14 0x9d041a in Communicator::handler_thread_routine(void*) /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/Communicator.cc:1104
    #15 0x9dfe5c in __thrdpool_routine /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/thrdpool.c:72
    #16 0x7f311175fda3 in start_thread /home/liruihao/mygcc82/glibc-2.21/nptl/pthread_create.c:333
    #17 0x7f31113c632c in clone (/opt/compiler/gcc-8.2/lib/libc.so.6+0xeb32c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: BUS (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x2f0dd)
Thread T29 created by T0 here:
    #0 0x7f31117c3f50 in pthread_create (/opt/compiler/gcc-8.2/lib/libasan.so.5+0x4cf50)
    #1 0x9e0053 in __thrdpool_create_threads /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/thrdpool.c:156
    #2 0x9e0053 in thrdpool_create /home/ferry/ONLINE_SERVICE/other/ferry/task_workspace//third-party/sogou-workflow/src/kernel/thrdpool.c:192

==34506==ABORTING

**Comment by chenlinzhong** [comment]
> 

是的

**Comment by Barenboim** [comment]
你好，这个mysql parser反初始化时的一个bug。对于一个内容不完整的mysql结果，可能引起free一个野指针。非常感谢给我们报告这个问题。

**Comment by Barenboim** [comment]
已经合并修改代码。麻烦再试一下！

**Comment by chenlinzhong** [comment]
好的，我们验证下

**Comment by Barenboim** [comment]
这个bug确实和retry没有什么关系。是MySQLMessage析构时候的问题。一直没有发现可能是因为我们常用的MySQL server和Tidb很少出现数据传一半出错的情况。

**Comment by chenlinzhong** [comment]
> 

是的，我们在看代码的时候也已经感觉那里可能存在问题，猜测是newsql回包不完整或者返回非标准mysql协议的内容，准备用标准的mysql来验证下，现在已经用新的代码重新跑着了，再观察下

**Comment by chenlinzhong** [comment]
升级后，从昨天16点开始后，已持续稳定运行15小时以上，有新情况再同步，感谢感谢~
ps: 
同事：这个跟进效率也太快了吧   
我：这可能也是为啥这个项目有这么多star的原因之一， respect！

**Comment by Barenboim** [comment]
> 升级后，从昨天16点开始后，已持续稳定运行15小时以上，有新情况再同步，感谢感谢~
> ps:
> 同事：这个跟进效率也太快了吧
> 我：这可能也是为啥这个项目有这么多star的原因之一， respect！

哈哈，如果在贵业务中被应用，也给我们加个star呀！

**Comment by chenlinzhong** [comment]
哦哦，加star居然给忘了，加上，现在稳定运行24小时以上了，稳！！

**Comment by chenlinzhong** [comment]
issue先不要close哈，过两天高压测试。。看看会不会有新状况

**Comment by Barenboim** [comment]
多谢多谢！嗯嗯，也感谢帮我们压测这么久😊

**Comment by chenlinzhong** [comment]
这几天我们又发现新的问题
1.select可能会返回超过预期的数据，比如select了一个字段返回3个字段
2.返回不定期返回bad message  

我们使用了内部团队自研的newsql（兼容mysql协议），可能是协议兼容性的问题，也可以是workflow解析问题，找newsql问了下说只能抓包看看，对于 bad message newsql的同学说可能是链路关闭后，workflow又重新复用了这个链路
这两个问题有遇到过么，或者有没有什么定位的思路

**Comment by holmes1412** [comment]
1. select一个字段返回3个字段可以抓包看看是不是server就这么做的，而且如果这种情况，server的协议里写明field_count为3的话workflow的行为是会按照三个字段给解析出来的，若都能成功解析那么说明server返回就是这样的。
2. 如果有某些地方情况和协议不兼容，workflow解析失败就会拿到bad message。建议可以把具体拿到bad mesaage的语句拿出来返回包是否和官方协议不一样，如果是和官方协议一样的话也许是Workflow解析的疏漏，会帮改掉～
3. 连接如果被关workflow会重新建立连接，不用担心这个问题。如果某些操作对连接独占很敏感比如事务，建议尝试WFMySQLConnection

**Comment by Barenboim** [comment]
> 这几天我们又发现新的问题 1.select可能会返回超过预期的数据，比如select了一个字段返回3个字段 2.返回不定期返回bad message
> 
> 我们使用了内部团队自研的newsql（兼容mysql协议），可能是协议兼容性的问题，也可以是workflow解析问题，找newsql问了下说只能抓包看看，对于 bad message newsql的同学说可能是链路关闭后，workflow又重新复用了这个链路 这两个问题有遇到过么，或者有没有什么定位的思路



> 这几天我们又发现新的问题 1.select可能会返回超过预期的数据，比如select了一个字段返回3个字段 2.返回不定期返回bad message
> 
> 我们使用了内部团队自研的newsql（兼容mysql协议），可能是协议兼容性的问题，也可以是workflow解析问题，找newsql问了下说只能抓包看看，对于 bad message newsql的同学说可能是链路关闭后，workflow又重新复用了这个链路 这两个问题有遇到过么，或者有没有什么定位的思路

链路关闭后，workflow会立即检测到连接关闭不会复用这个连接。如果是关闭的一瞬间复用了这个连接，内部会得到一个ECONNRETSET错误，此时如果配置了retry会触发重试。
EBADMSG只会发生在请求发出之后，收到不符合协议的数据。这时候内部会关连接，而且也会引发重试。
我怀疑是收到的数据不符合规范。我们可以一起查一下是哪边的问题。

**Comment by chenlinzhong** [comment]
ok，定位了，是newsql返回了非标准mysql协议的格式，我们现在适配了下，问题解了

**Comment by Barenboim** [comment]
其实workflow也包含了一个MySQL server框架。但目前还差些东西，也不了，否则就推荐给你们开发newsql了。
我们的WFRedisServer是可以用的，有自制的redis server可以考虑一下。

**Comment by chenlinzhong** [comment]
ok

**Comment by chenlinzhong** [comment]
嗯嗯，了解了
