### ISSUE TITLE
err message出现乱码的情况（MySQL Client）

### ISSUE THREAD

**Issue by zhl0921** [sogou/workflow#685]
我这边执行一个事务，begin；sql1；sql2；sql3；commit；
从抓包看每个sql的返回如下：
![image](https://user-images.githubusercontent.com/17234849/146142918-81deaa86-8ac4-45d8-b47c-a30ec2a64a8d.png)
![image](https://user-images.githubusercontent.com/17234849/146142946-c1fcdc98-98e2-41c4-bd7f-032f390ac429.png)
![image](https://user-images.githubusercontent.com/17234849/146143010-a088dbeb-0392-4df1-bd87-c3170ad64905.png)
三个err message合并在一起，只去掉了第一个err message的头部，后面的err message的头部没有去掉 导致乱码
![image](https://user-images.githubusercontent.com/17234849/146142701-b5cb5544-f098-4d02-8cd0-06585422956d.png)

**Comment by holmes1412** [comment]
你好，我目前还没有复现出可以拿到包含多条error语句的回复包，比如我把tuturial-12-mysql_cli.cc里的语句改为：
```cpp
begin;show columns from 1;show columns from 2;show columns from 3;commit;
```
拿到的只有一个error语句回复，长度为44
```cpp
?z#42S02Table 'test.1' doesn't exist
```
能不能告知下server的版本、以及你具体的语句是什么呢？

**Comment by zhl0921** [comment]
我们用的是自己的new sql，我找mysql 验证一下

**Comment by holmes1412** [comment]
哈哈有意思～～～怎么这么多小伙伴用workflow访问new sql呢>_<

这里我介绍一下细节：
根据MySQL官方协议，error packet的包头里是没有地方告诉用户是否包含多条结果集的阈的。相比来说，ok包和result set包里都有server_status阈，通过设置flag：`MYSQL_SERVER_MORE_RESULTS_EXIST`来告知后面是否还有下一个包。

如果能找到是MySQL官方协议规范说明如何区分的话，我这边会根据官方规范帮你拆开。但如果这个多error是你们的自己添加的协议拼接，建议你可以二次开发改一下，也很简单～
