### ISSUE TITLE
Why is wf high performance   

### ISSUE THREAD

**Issue by Wkh3** [sogou/workflow#688]
Also based on epoll, what are the main optimizations that wf does to get better performance than nginx?

**Comment by Barenboim** [comment]
I don't know. We don't even use memory pool or any lockfree technology.

**Comment by Wkh3** [comment]
nginx and muduo both handle events synchronously after calling epoll_wait,while wf handle events  asynchronously.  Why did wf  
do that? For better performance?

**Comment by Barenboim** [comment]
Yes, the IO results will be pass over to the handler threads through a message queue. This is a very common method of networking framework. If the message queue is removed and the IO threads call **handler**s directly, we will gain about 10% performance increase.

**Comment by Barenboim** [comment]
We have to separate handler threads from IO threads to prevent user's handlers blocking our IO threads. And in some scenarios the number of handler threads can be very large, we should not let all threads to wait for IO events.
