### ISSUE TITLE
workflow长链接超时问题确认

### ISSUE THREAD

**Issue by zhaojie16** [sogou/workflow#689]
1.
workflow  — mysql server   
长链接，mysql server设置了180s超时，会主动把长链接close。
这个workflow可以感知吗？
如果来一个sql请求，workflow的行为，会依然使用老的无效链接？还是会失败一次，再创建一个新的链接啊？

**Comment by zhaojie16** [comment]
![15F8B355409135029A37F1EF967A4555](https://user-images.githubusercontent.com/43134736/146512200-2d9c03a7-fa37-4a55-8668-b8997b59149b.jpg)

**Comment by Barenboim** [comment]
首先，如图所示，workflow MYSQL任务对连接默认保持的时间是60秒，事务操作是一小时。如果你的MySQL server那边连接保持时间是180秒，那么其实workflow会先关连接。
如果是server先主动关闭，workflow是立即能感知到并且关闭连接的，不会复用已经被对方关闭的连接。如果是关闭一瞬间正好被复用，那么会得到一个ECONNRESET错误。如果配置了retry，则触发重试，对用户无感。

**Comment by zhaojie16** [comment]
感谢谢爷的回复，了解了。
