### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#690]
有一个本地文件E:/test.txt,通过请求上传到server[root]路径下，

**Comment by Barenboim** [comment]
你可以参考一上这项目的实现：https://github.com/wfrest/wfrest，但是你好像是windows平台，wfrest项目目前不支持windows。
workflow本身不提供上传服务的实现，需要你自己写http server的process。你也可以参考tutorial10，把下载换成上传就可以了。不过，windows平台没有异步文件任务，你自己可以用标准IO写文件。

**Comment by HzjFirst** [comment]
我可能说的不太明白，workflow的程序服务是在ubuntu上的，但是文件是在window上，想通过http请求的方式，将window上的固定路径的文件，上传到ubuntu上

**Comment by Barenboim** [comment]
好吧。那你用wfrest项目最方便。里有POST和Save文件的接口。
Windows上你自己要发个POST请求过去啊。

**Comment by HzjFirst** [comment]
嗯嗯，我正在看，但是还没有走通
