### ISSUE TITLE
workflow超时和连接复用问题

### ISSUE THREAD

**Issue by cindyzqtnew** [sogou/workflow#692]
Hi folks,

我这边是兼容MySQL协议的一个NewSQL产品，使用workflow连接我们服务时，发现出现连接被中断的问题。查看workflow代码，发现超时配置是60s，事务是1个小时。对此有些疑问：

1、怎样判断区分60s和1小时的task？是通过是否发送begin等相关关键字匹配判断吗？

2、这个具体是什么超时？是连接从发起到关闭的时间？如果是，那么这个超时是怎样实现的？通过标准MySQL client连接数据库服务端后，通过set超时变量的方式，让数据库服务端感知超时配置，然后依赖数据库服务端在超时后主动断链？抑或，workflow自己对全部连接进行计时统计，超时了，则主动关闭连接？

3、若一个事务涉及数个任务（复用同一个连接），那么这个超时时间是否包含这些任务之间的时间间隔（应用程序有可能需要根据每次任务返回的结果，进行处理，再发起下一个任务（复用同一个连接和事务）？

4、有没有可能出现，超时是1小时（事务），然后由于数据库服务端等原因，连接被中断了，那么复用这个连接时，workflow不主动探活，照常发送sql，导致出core？因为对于标准的mysql client，给已经断开的Conn直接发送sql，是有可能core的。

**Comment by Barenboim** [comment]
在回答你几个具体问题之前，我先声明一下，workflow核心对连接的管理和复用是非常细致的，不可能出现任何你能想到的不合理情况。前面一个关于mysql的问题我也大概说了一下连接管理，你可以参考。

**Comment by Barenboim** [comment]
1、内部如何区分事务与非事务
最简单的，你通过WFTaskFactory创建的任务，就是非事务。你通过WFMySQLConnection创建的任务，就被认为是事务。事务请求不做retry，连接断了就是错误。事务型请求，默认连接保持时间为1小时。
2、连接保持时间是指连接上一次使用之后，如果没有被复用最长保持多久，简单来讲就是一个LRU队列。你可以修改任务的连接保持时间，也就是这个任务完成之后，连接能保持多久：
~~~cpp
int myfunc()
{
    WFMySQLTask *task = WFTaskFactory::create_mysql_task(...);
    task->set_keep_alive(120 * 1000);
    task->start();
}
~~~
这个例子表示连接用完保持两分钟。但在callback里设置连接保持时间不会起作用，因为此时连接可能已经被复用了。内部复用连接采用FIFO，刚释放的连接优先复用。连接到时间未复用，内部会主动关闭。
3、这个已经解释了。事务的话，需要用WFMySQLConnection来创建任务。
4、不会，会重新建连接。就算WFMySQLConnection也会重新建连接，但你下一个任务会得到一个事务中断错误。之后你可以接着用这个connection。

连接管理这块，你就往最合理的方式想就对了。我们一定比你想的还合理。至于server主动断连接的情况怎么处理，参考上一个issue。

**Comment by Barenboim** [comment]
@cindyzqtnew

**Comment by cindyzqtnew** [comment]
@Barenboim 我了解，这个问题已解决。谢谢啦~
