### ISSUE TITLE
Compile task_unittest.cc failed to build on Windows with MSVC "error C2039: 'create_pwrite_task': is not a member of 'WFTaskFactory'"

### ISSUE THREAD

**Issue by YangYang129** [sogou/workflow#694]
Compile task_unittest.cc failed to "error C2039: 'create_pwrite_task': is not a member of 'WFTaskFactory'". It can reproduces on version https://github.com/sogou/workflow/commit/e40a8aa62c11762ebc3c5b748da481fc06310ceb. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.8)
Operating system: Windows server 2019

Reproduce steps:
1. git clone -b windows https://github.com/sogou/workflow F:\gitP\workflow
2. cd F:\gitP\workflow
3. mkdir build_amd64 & cd build_amd64 
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=F:\tools\OpenSSL ..
5. msbuild /p:Configuration=Release;Platform=x64 workflow.sln /t:Rebuild /m 
6. cd .. & cd test
7. mkdir build_amd64test & cd build_amd64test
7. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DGTest_DIR="F:\gitP\xbmc\tools\x64\lib\cmake\GTest" -DOPENSSL_ROOT_DIR=F:\tools\OpenSSL ..
8. msbuild /p:Configuration=Release;Platform=x64 workflow_test.sln /t:Rebuild /m 

**Error log:**
[msbuild_amd64test.log](https://github.com/sogou/workflow/files/7743537/msbuild_amd64test.log)

**Error info:**
16>F:\gitP\workflow\test\task_unittest.cc(212,31): error C2039: 'create_pwrite_task': is not a member of 'WFTaskFactory' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
       F:\gitP\workflow\_include\workflow/WFTaskFactory.h(103): message : see declaration of 'WFTaskFactory' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(212,49): error C3861: 'create_pwrite_task': identifier not found [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(212,14): error C3535: cannot deduce type for 'auto *' from 'unknown-type' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(226,30): error C2039: 'create_pread_task': is not a member of 'WFTaskFactory' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
       F:\gitP\workflow\_include\workflow/WFTaskFactory.h(103): message : see declaration of 'WFTaskFactory' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(226,47): error C3861: 'create_pread_task': identifier not found [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(226,13): error C3535: cannot deduce type for 'auto *' from 'unknown-type' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(240,27): error C2665: 'Workflow::create_series_work': none of the 2 overloads could convert all the argument types [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
       F:\gitP\workflow\_include\workflow\Workflow.h(163,11): message : could be 'SeriesWork *Workflow::create_series_work(SubTask *,series_callback_t)' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
       F:\gitP\workflow\test\task_unittest.cc(245,3): message : while trying to match the argument list '(int *, WFFileIOTask_task_unittest_Test::TestBody::<lambda_0a01b2881e0364697778d8189eeb04ea>)' [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]
    16>F:\gitP\workflow\test\task_unittest.cc(247,8): error C3536: 'series': cannot be used before it is initialized [F:\gitP\workflow\test\build_amd64\task_unittest.vcxproj]

**Comment by Barenboim** [comment]
Sorry, don't use unit-test on the Windows platform. Because we don't implement fileIO task for windows platform yet.

**Comment by Barenboim** [comment]
This pull request removed fileio task testing on windows.

**Comment by YangYang129** [comment]
@Barenboim I re-try to msbuild workflow_test.sln on latest version https://github.com/sogou/workflow/commit/c4f7dcc1f2951960a734eddd9a070118d02a73a7, msbuild pass and but ctest fail   on x64 **Error log:**[testamd64_rel.log](https://github.com/sogou/workflow/files/7761450/testamd64_rel.log).
 msbuild fail "libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp__CertOpenStore@20 referenced in function _capi_open_store" on x86 **Error log:** [msbuild_amd86test.log](https://github.com/sogou/workflow/files/7761521/msbuild_amd86test.log).

Reproduce steps on x64 (Open a vs2019 x64 command prompt):
1. git clone -b windows https://github.com/sogou/workflow F:\gitP\sogou\workflow
2. cd F:\gitP\sogou\workflow
3. mkdir build_amd64rel & cd build_amd64rel
4. cmake -G "Visual Studio 16 2019" -A win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=F:\gitP\symless\openssl_win32\win32 ..
5. msbuild /p:Configuration=Release;Platform=win32 workflow.sln /t:Rebuild /m
6. cd .. & cd test
7. mkdir build_x86 & cd build_x86
8. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="F:\gitP\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows -DOPENSSL_ROOT_DIR=F:\tools\OpenSSL ..
9. msbuild /p:Configuration=Release;Platform=x64 workflow_test.sln /t:Rebuild /m
10. ctest --build-config Release --output-on-failure

Reproduce steps on x86 (Open a vs2019 x86 command prompt):
1. git clone -b windows https://github.com/sogou/workflow C:\Setup\workflow
2. cd C:\Setup\workflow
3. mkdir build_x86 & cd build_x86
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=F:\tools\OpenSSL ..
5. msbuild /p:Configuration=Release;Platform=x64 workflow.sln /t:Rebuild /m
6. cd .. & cd test
7. mkdir build_amd64rel_test & cd build_amd64rel_test
8. cmake -G "Visual Studio 16 2019" -A win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="F:\gitP\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows -DOPENSSL_ROOT_DIR="F:\gitP\symless\openssl_win32\win32" ..
9. msbuild /p:Configuration=Release;Platform=win32 workflow_test.sln /t:Rebuild /m

**Comment by Barenboim** [comment]
Can you run the tutorials on windows? 
We didn't run test cases on windows platform before.
