### ISSUE TITLE
mysql client收发包大小限制问题？

### ISSUE THREAD

**Issue by zhaojie16** [sogou/workflow#696]
请问，workflow做mysql client， 一次返回的包大小可以调整吗？最大是多少呢？谢谢

**Comment by Barenboim** [comment]
你是说限制回包的大小？这个是所有任务通用的：
task->get_resp()->set_size_limit();
任何任务都可以通过这个接口设置收包大小。如果超过这个大小，将得到一个EMSGSIZE错误。

**Comment by zhaojie16** [comment]
如果我们不设置resp的大小呢？谢爷，这种情况回包默认size会是多大啊？

**Comment by Barenboim** [comment]
你是公司内部团队的么？

**Comment by zhaojie16** [comment]
不是内部团队的哈。但是也知道谢爷。
