### ISSUE TITLE
服务代理例子使用问题

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#698]
服务代理例子：应该怎么发送请求？

**Comment by Barenboim** [comment]
你是说向外发http请求吗？和wget一样啊。

**Comment by HzjFirst** [comment]
http://192.168.46.135:8080/http://www.sogou.com/
http://192.168.46.135:8080是我服务的地址和端口，http://www.sogou.com/是我想要服务代理帮我代理的目标地址，这样发送请求不对，应该怎么发送请求？

**Comment by HzjFirst** [comment]
![image](https://user-images.githubusercontent.com/62458770/146878670-f030b2dd-a57d-4f08-85e8-5f6cf3dd5ddf.png)
就是这个WFHttpTask的get_request_uri()怎么在发送请求的时候给值？

**Comment by Barenboim** [comment]
这个发请求肯定不对。http proxy是有标准的，发送的方法是，request line是这么写的：
GET http://www.sogou.com/ HTTP/1.1
当然，如果你定义成http://192.168.46.135:8080/http://www.sogou.com/ 这么发请求，那也不难啊。因为这样的话你收到的request_uri就是"/http://www.sogou.com/" ，前面多了一个'/'。你的process可以这么写：
~~~cpp
void process(WFHttpTask *server_task)
{
    std::string url = server_task->get_req()->get_request_uri() + 1;
    WFHttpTask *task = WFTaskFactory::create_http_task(url, ...);
    ...
}
~~~

**Comment by Barenboim** [comment]
如果你是想用workflow给我们的tutorial05-http_proxy发请求，可以这么做：
~~~cpp
{
    WFHttpTask *task = WFTaskFactory::create_http_task("http://192.168.46.135:8080/", ....);
    task->get_req()->set_request_url("http://www.sogou.com/");
    task->get_req()->set_header_pair("Host", "www.sogou.com");
    task->start();
}
~~~
我在FAQ里关于怎么作用http代理，有讲这个方法。

**Comment by HzjFirst** [comment]
嗯嗯，明白了，谢谢大佬啦。

**Comment by HzjFirst** [comment]
嗯嗯，明白了，谢谢大佬
