### ISSUE TITLE
http长连接使用问题

### ISSUE THREAD

**Issue by willkk** [sogou/workflow#699]
第一次请求能成功，第二次请求程序core。显式设置keep_alive很短或如图通过头部设置close程序可以多次发起短连接，正常请求。
![078265a7a14f98a69eeada4a467e9ad](https://user-images.githubusercontent.com/17777977/146928787-35cb0037-e336-44f1-bd6c-7fb6f6a38b41.png)
![49c6d75cb6bc91493048b3ac482f968](https://user-images.githubusercontent.com/17777977/146928819-a39ee19c-bcc7-4de6-ad8e-7ff0b1837599.png)
看代码create_http_task默认设置了keep alive 60s，帮忙看下呢。

**Comment by Barenboim** [comment]
你的req是局部变量吧? 那不能nocopy啊。把append_output_body后面的_nocopy去掉应该就对了。

**Comment by willkk** [comment]
req是局部变量，把nocopy去掉还是一样的错误。

**Comment by willkk** [comment]
![1640093329(1)](https://user-images.githubusercontent.com/17777977/146937964-17504bcb-b0a8-4108-8a0c-a91a62cefb4d.png)

**Comment by Barenboim** [comment]
你那边代码可能不是最新，麻烦up一下代码先。
如果还不行，你先关闭我们的异步dns解析。方法是:
~~~cpp
int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.resolv_conf_path = NULL;
    WORKFLOW_library_init(&settings);
    ....
}
~~~

**Comment by willkk** [comment]
我昨天拉了master分支编译，也一样的。

**Comment by willkk** [comment]
> 

试了下这个设置，没效果，看堆栈日志还是有WFResolverTask::dispatch。

**Comment by willkk** [comment]
> 你那边代码可能不是最新，麻烦up一下代码先。 如果还不行，你先关闭我们的异步dns解析。方法是:
> 
> ```c++
> int main()
> {
>     struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
>     settings.resolv_conf_path = NULL;
>     WORKFLOW_library_init(&settings);
>     ....
> }
> ```

试了下这个设置，没效果，看堆栈日志还是有WFResolverTask::dispatch。

**Comment by Barenboim** [comment]
你重新clone一份代码，用我们的tutorial01改改看看能不能复现吧。因为这个问题太基础了，不太像workflow本身的问题。我怀疑是你环境下lib和头文件不匹配。

**Comment by willkk** [comment]
```c++
#include <netdb.h>
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include "workflow/HttpMessage.h"
#include "workflow/HttpUtil.h"
#include "workflow/WFTaskFactory.h"
#include "workflow/WFFacilities.h"
#include <iostream>

#define REDIRECT_MAX    5
#define RETRY_MAX       2

bool check_http_status(WFHttpTask* task) {
  int state = task->get_state();
  int error = task->get_error();
  switch (state) {
  case WFT_STATE_SYS_ERROR:
    std::cout<< "system error:" << strerror(error) << std::endl;
    break;
  case WFT_STATE_DNS_ERROR:
    std::cout << "DNS error:" << gai_strerror(error) << std::endl;
    break;
  case WFT_STATE_SSL_ERROR:
    std::cout << "SSL error:" << error << std::endl;
    break;
  case WFT_STATE_TASK_ERROR:
    std::cout << "Task error: " << error << std::endl;
    break;
  case WFT_STATE_SUCCESS:
    break;
  }

  if (state != WFT_STATE_SUCCESS) {
    std::cout << "Http req failed. State:" << state << std::endl;
    return false;
  }
  int code = atoi(task->get_resp()->get_status_code());
  if (code != HttpStatusOK) {
    std::cout << "Http req bad status code:" << code << std::endl;
    return false;
  }
  return true;
}

int DoHttp(std::string url, const char* method, std::string& req, std::string& resp,
  std::vector<std::string> headers) {
  WFFacilities::WaitGroup wait_group(1);
  int ret = 0;
  auto callback = [&ret, &wait_group, &resp](WFHttpTask *task) {
    auto *task_resp = task->get_resp();
    if (!check_http_status(task)) {
      std::cout << "check_http_status false." << std::endl;
      ret = -1;
    } else {
      const void *body;
      size_t len;
      if (task_resp->get_parsed_body(&body, &len)) {
        resp.assign((const char*)body, len);
      } else {
        ret = -2;
        std::cout << "Parse http resp failed." << std::endl;
      }
    }
    wait_group.done();
  };
  WFHttpTask *task = WFTaskFactory::create_http_task(url, 1, 0, callback);
  protocol::HttpRequest *task_req = task->get_req();
  task_req->set_method(method);
  task->set_receive_timeout(5000);  //  ms
  task->set_keep_alive(5000);  //  ms
  for (auto h : headers) {
    auto pos = h.find(":");
    if (pos == std::string::npos) {
      continue;
    }

    auto key = h.substr(0, pos);
    auto val = h.substr(pos+1);
    task_req->add_header_pair(key, val);
  }
  task_req->add_header_pair("Content-Type", "application/json");
  task_req->append_output_body(req.c_str(), req.size());
  task->start();
  wait_group.wait();
  return ret;
}

void wget_callback(WFHttpTask *task)
{
        protocol::HttpRequest *req = task->get_req();
        protocol::HttpResponse *resp = task->get_resp();
        int state = task->get_state();
        int error = task->get_error();

        switch (state)
        {
        case WFT_STATE_SYS_ERROR:
                fprintf(stderr, "system error: %s\n", strerror(error));
                break;
        case WFT_STATE_DNS_ERROR:
                fprintf(stderr, "DNS error: %s\n", gai_strerror(error));
                break;
        case WFT_STATE_SSL_ERROR:
                fprintf(stderr, "SSL error: %d\n", error);
                break;
        case WFT_STATE_TASK_ERROR:
                fprintf(stderr, "Task error: %d\n", error);
                break;
        case WFT_STATE_SUCCESS:
                break;
        }

        if (state != WFT_STATE_SUCCESS)
        {
                fprintf(stderr, "Failed. Press Ctrl-C to exit.\n");
                return;
        }

        std::string name;
        std::string value;

        /* Print request. */
        fprintf(stderr, "%s %s %s\r\n", req->get_method(),
                                                                        req->get_http_version(),
                                                                        req->get_request_uri());

        protocol::HttpHeaderCursor req_cursor(req);

        while (req_cursor.next(name, value))
                fprintf(stderr, "%s: %s\r\n", name.c_str(), value.c_str());
        fprintf(stderr, "\r\n");

        /* Print response header. */
        fprintf(stderr, "%s %s %s\r\n", resp->get_http_version(),
                                                                        resp->get_status_code(),
                                                                        resp->get_reason_phrase());

        protocol::HttpHeaderCursor resp_cursor(resp);

        while (resp_cursor.next(name, value))
                fprintf(stderr, "%s: %s\r\n", name.c_str(), value.c_str());
        fprintf(stderr, "\r\n");

        /* Print response body. */
        const void *body;
        size_t body_len;

        resp->get_parsed_body(&body, &body_len);
        fwrite(body, 1, body_len, stdout);
        fflush(stdout);

        fprintf(stderr, "\nSuccess. Press Ctrl-C to exit.\n");
}

static WFFacilities::WaitGroup wait_group(1);

void sig_handler(int signo)
{
        wait_group.done();
}

int main(int argc, char *argv[])
{
        WFHttpTask *task;

        if (argc != 2)
        {
                fprintf(stderr, "USAGE: %s <http URL>\n", argv[0]);
                //exit(1);
        }

        signal(SIGINT, sig_handler);

        /*std::string url = argv[1];
        if (strncasecmp(argv[1], "http://", 7) != 0 &&
                strncasecmp(argv[1], "https://", 8) != 0)
        {
                url = "http://" + url;
        }*/

  std::string url = "http://127.0.0.1:19021/vod/v2";
  std::string req = "";   //  填写请求
  std::string resp;
  int ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;
  ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;
  ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;
  ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;
  ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;
  ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;
  ret = DoHttp(url, HttpMethodPost, req, resp, {});
  std::cout << "HttpPost url:" << url << " req:" << req << " resp:" << resp << " ret:" << ret << std::endl;

        //task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
        //                                                                         wget_callback);
        //protocol::HttpRequest *req = task->get_req();
        //req->add_header_pair("Accept", "*/*");
        //req->add_header_pair("User-Agent", "Wget/1.14 (linux-gnu)");
        //req->add_header_pair("Connection", "close");
        //task->start();

        //wait_group.wait();
        return 0;
}
```
昨晚拉的master分支代码，在workflow/tutorial目录直接改完make，server是我的，正常应该链接的是master版lworkflow ib库吧。
build.cmake/CMakeFiles/wget.dir/link.txt：`/usr/bin/c++  -Wall -fPIC -pipe -std=c++11 -fno-exceptions -O2 -g -DNDEBUG CMakeFiles/wget.dir/tutorial-01-wget.cc.o -o ../wget   -L/root/projects/Access/build/workflow/_lib  -Wl,-rpath,/root/pro    jects/Access/build/workflow/_lib -lworkflow /usr/lib64/librt.so`。

不管设置`task->set_keep_alive(5000); `与否，都是短连接。如下图：
![企业微信截图_16401742571998](https://user-images.githubusercontent.com/17777977/147089448-f4f52b76-c19c-45ba-b7f8-8b19fe70f9bc.png)

**Comment by Barenboim** [comment]
这个要看server端是不是短连接。有可能是server端关闭的连接。但如果你用workflow的http server，默认情况下是长连接的。
另外，core的问题现在是不是没有出现了？

**Comment by willkk** [comment]
server不会断的，你看截图都是客户端先断的。core问题没有了，但不确定是不是没有走到长接连逻辑才消失的。

**Comment by Barenboim** [comment]
如果是这样，你不要用set_keep_alive(5000)，改成：
resp->add_header_pair("Connection", "Keep-Alive");
试试。

**Comment by Barenboim** [comment]
或者是你发一下http server返回的header是什么。

**Comment by Barenboim** [comment]
如果这段代码里
~~~cpp
  for (auto h : headers) {
    auto pos = h.find(":");
    if (pos == std::string::npos) {
      continue;
    }

    auto key = h.substr(0, pos);
    auto val = h.substr(pos+1);
    task_req->add_header_pair(key, val);
  }
~~~
给req加了connection close的header，是有可能让server断连接的。

**Comment by willkk** [comment]
> 如果这段代码里
> 
> ```c++
>   for (auto h : headers) {
>     auto pos = h.find(":");
>     if (pos == std::string::npos) {
>       continue;
>     }
> 
>     auto key = h.substr(0, pos);
>     auto val = h.substr(pos+1);
>     task_req->add_header_pair(key, val);
>   }
> ```
> 
> 给req加了connection close的header，是有可能让server断连接的。

没有的，你看上面示例代码，header是空的。

另外，设置`task_req->add_header_pair("Connection", "Keep-Alive");`请求有相应头部，但会core。堆栈跟之前贴的一样。确认是`task_resp`？

**Comment by Barenboim** [comment]
这个我们真是从来没有遇到过。这个问题也太严重了，如果这样应该早就被发现。

**Comment by willkk** [comment]
上面有测试代码，你可以复现下。随便go或python开一个web server。

**Comment by Barenboim** [comment]
你是不是机器上安装了workflow？
/usr/bin/c++ -Wall -fPIC -pipe -std=c++11 -fno-exceptions -O2 -g -DNDEBUG CMakeFiles/wget.dir/tutorial-01-wget.cc.o -o ../wget -L/root/projects/Access/build/workflow/_lib -Wl,-rpath,/root/pro jects/Access/build/workflow/_lib -lworkflow /usr/lib64/librt.so。
然后你这个编译里用的头文件，和你已经安装的workflow lib并不匹配？

**Comment by willkk** [comment]
> 

怎么确认呢，workflow安装路径是啥？

**Comment by Barenboim** [comment]
-L/root/projects/Access/build/workflow/_lib
你现在链接的是这个路径啊。

**Comment by willkk** [comment]
/root/projects/Access/这个是我的项目路径，我把workflow clone到项目的build目录了，应该不影响。

**Comment by holmes1412** [comment]
@willkk 我发现你已经用了tutorial-01去做改造了，为什么不直接使用tutorial下的CMakeLists.txt呀？建议先直接使用默认的cmake文件，咱们先排除链接等其他问题～

**Comment by willkk** [comment]
我是在workflow/tutorial目录直接make，有问题？

**Comment by Barenboim** [comment]
/usr/bin/c++ -Wall -fPIC -pipe -std=c++11 -fno-exceptions -O2 -g -DNDEBUG CMakeFiles/wget.dir/tutorial-01-wget.cc.o -o ../wget -L/root/projects/Access/build/workflow/_lib -Wl,-rpath,/root/pro jects/Access/build/workflow/_lib -lworkflow /usr/lib64/librt.so
这个是tutorial里的make打出来的吗？

**Comment by willkk** [comment]
是。build.cmake/CMakeFiles/wget.dir/link.txt这个文件，用./wget运行的。

**Comment by Barenboim** [comment]
core的地方，还是显示Communicator.cc:522行吗？

**Comment by willkk** [comment]
> > 如果这段代码里
> > ```c++
> >   for (auto h : headers) {
> >     auto pos = h.find(":");
> >     if (pos == std::string::npos) {
> >       continue;
> >     }
> > 
> >     auto key = h.substr(0, pos);
> >     auto val = h.substr(pos+1);
> >     task_req->add_header_pair(key, val);
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 给req加了connection close的header，是有可能让server断连接的。
> 
> 没有的，你看上面示例代码，header是空的。
> 
> 另外，设置`task_req->add_header_pair("Connection", "Keep-Alive");`请求有相应头部，但会core。堆栈跟之前贴的一样。确认是`task_resp`？

这个是刚才req 头加了Keep-Alive后core的case。
![企业微信截图_164017792095](https://user-images.githubusercontent.com/17777977/147096555-261c6f10-d062-4ca5-90b1-24f50edba21a.png)

**Comment by willkk** [comment]
你们先复现下呢？可以查起来比较快。

**Comment by Barenboim** [comment]
但是第522行是一个return 1啊，不是一个会core的地方。

**Comment by holmes1412** [comment]
关键是试了很多次，不能复现呀：
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/1880011/147096692-60f2fbf4-346e-484e-963d-a8afa46c1860.png">
加上`task_req->add_header_pair("Connection", "Keep-Alive");`：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1880011/147097019-8ff5f363-762e-4927-a7b5-31f9c6d3c9aa.png">
server的截图参考：
<img width="716" alt="image" src="https://user-images.githubusercontent.com/1880011/147096721-572f2349-425f-4df7-b2a6-36719d5b0248.png">

**Comment by holmes1412** [comment]
建议还是重新试一下，排除一下期间的手误等情况？

1. 重新拉workflow代码；
2. 把tutorial-01改成你贴的那些；
3. 执行make; cd tutorial; make;
4. 启动server: ./http_echo_server 19021
5. 启动client：./wget http://127.0.0.1:19021

**Comment by willkk** [comment]
好的，我先看下我这边的环境问题。

**Comment by willkk** [comment]
522行的应该是我之前编的老版本库代码。我刚把项目里面第三方库的workflow文件都替换成了最新master分支代码（_lib和_include目录）。堆栈日志：
![企业微信截图_16401787112274](https://user-images.githubusercontent.com/17777977/147098044-477f3516-1ac7-4014-992b-751414d29988.png)
![企业微信截图_16401788564082](https://user-images.githubusercontent.com/17777977/147098298-5121427d-c1d7-4418-8bd2-8aa1e7bf4352.png)

**Comment by Barenboim** [comment]
所以还是比较大概率是你那边代码不一致的问题。我们已经用你的代码在自己机器上跑过了，没出现你说的问题。

**Comment by willkk** [comment]
我找一个新环境，用master再试试。看你们是用的echo server？

**Comment by Barenboim** [comment]
是的。我们测试是用自己的echo server

**Comment by willkk** [comment]
测试了一轮，感觉是跟trpc server有关联，DoHttp本身看起来没问题。
