### ISSUE TITLE
windows版本code

### ISSUE THREAD

**Issue by MaybeShewill-CV** [sogou/workflow#7]
什么时候会开放windows版本的代码呢?

**Comment by alpc62** [comment]
我考虑一下，要不要单独拉windows分支放出来win版本。或者放到我fork的地方去。我们这边想一想，会尽快给你答复 @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@alpc62 好滴 感觉代码写的很清楚 有很多值得学习的地方 👍

**Comment by alpc62** [comment]
https://github.com/alpc62/workflow/tree/windows  
你可以先用这个体验 @MaybeShewill-CV 后续在合适时机我们会合入主线上  
建议用``vs2019``，以及本机要有``openssl-devel``库，windows版本要高于``vista``（win7/win10都可以）  
功能上暂时不支持FileIOTask，其余与linux一致，FileIO working with iocp我会尽快完成并合入  
有任何使用上的问题可以直接找我，我随时在  
另外这个分支不仅支持windows，本质上是跨三平台的：liunx, macos, linux

**Comment by MaybeShewill-CV** [comment]
@alpc62 好的 感谢:)

**Comment by MaybeShewill-CV** [comment]
@alpc62 未来有计划出比较框架性的介绍文档吗。感觉现在的文档都是在介绍比较局部的细节，对整个框架的设计和结构没有办法很好的描述和介绍。未来有没有计划出一下这方面介绍的文档，尤其是介绍各个模块的功能和模块之间关系的文档。谢谢：）

**Comment by alpc62** [comment]
@Barenboim @holmes1412

**Comment by Barenboim** [comment]
> @alpc62 未来有计划出比较框架性的介绍文档吗。感觉现在的文档都是在介绍比较局部的细节，对整个框架的设计和结构没有办法很好的描述和介绍。未来有没有计划出一下这方面介绍的文档，尤其是介绍各个模块的功能和模块之间关系的文档。谢谢：）

目前的文档主要是使用说明，将来我们再逐步添加实现原理上的介绍。谢谢热心用户。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 个人感觉如果有个系统性的整体介绍能帮助用户更好地把这个框架融入自己的开发任务，否则只看现在的一些例子的说明感觉还是不太能很好的领会框架的要点。哈哈，期待未来文档能越来越丰富。看好workflow！！！

**Comment by alpc62** [comment]
@MaybeShewill-CV   有兴趣可以看看这份文档，规约为以下6种编程

- [网络IO](https://github.com/alpc62/AnyClient#网络io)
  - [HttpClient](https://github.com/alpc62/AnyClient#httpclient)
  - [RedisClient](https://github.com/alpc62/AnyClient#redisclient)
  - [MySQLClient](https://github.com/alpc62/AnyClient#mysqlclient)
  - [KafkaClient](https://github.com/alpc62/AnyClient#kafkaclient)
- [磁盘IO](https://github.com/alpc62/AnyClient#磁盘io)
- [定时器](https://github.com/alpc62/AnyClient#定时器)
- [计数器](https://github.com/alpc62/AnyClient#计数器)
- [CPU](https://github.com/alpc62/AnyClient#cpu)
- [GPU](https://github.com/alpc62/AnyClient#gpu)

**Comment by MaybeShewill-CV** [comment]
@alpc62 好的 非常感谢:)

**Comment by 1261385937** [comment]
Windows 版本的 需要管理员权限打开vs 才能编译

**Comment by kkzi** [comment]
@alpc62  windows 10, msvc 2019 16.7.3


-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
CMAKE_C_FLAGS_DEBUG is /MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_RELEASE is /MD /O2 /Ob2 /DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO is /MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_C_FLAGS_MINSIZEREL is /MD /O1 /Ob1 /DNDEBUG
CMAKE_CXX_FLAGS_DEBUG is /MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_RELEASE is /MD /O2 /Ob2 /DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO is /MD /Zi /O2 /Ob1 /DNDEBUG
CMAKE_CXX_FLAGS_MINSIZEREL is /MD /O1 /Ob1 /DNDEBUG
-- Found OpenSSL: D:/local/vcpkg/installed/x64-windows/lib/libcrypto.lib (found version "1.1.1d")
**CMake Error at src/CMakeLists.txt:7 (add_subdirectory):
  add_subdirectory given source "kernel_win" which is not an existing
  directory.**


CMake Error at src/CMakeLists.txt:20 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "kernel".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.


-- Configuring incomplete, errors occurred!
See also "D:/sss/workflow/b/CMakeFiles/CMakeOutput.log".

**Comment by alpc62** [comment]
- Sorry, At this moment, the "master" branch does **NOT** support the windows platform yet
- You need pull the branch "windows" @kkzi 
- like this: ``git clone -b windows https://github.com/sogou/workflow.git``

**Comment by SixDayCoder** [comment]
windows版本cmake gen2019工程正常 编译ALL_BUILD时报错 

failed to create symbolic link 'C:/Users/Administrator/Desktop/workflow/workflow/_include/workflow/PlatformSocket.h': operation not permitted	LINK_HEADERS	C:\Users\Administrator\Desktop\workflow\workflow\build\EXEC	1	

无法打开包括文件: “PlatformSocket.h”: No such file or directory	algorithm	C:\Users\Administrator\Desktop\workflow\workflow\src\algorithm\DNSRoutine.cc	21

**Comment by Barenboim** [comment]
请用管理员权限试试。

**Comment by SixDayCoder** [comment]
@Barenboim 您好 使用管理器权限后可以成功生成 感谢
