### ISSUE TITLE
workflow发送multi-statement给mysql，回包出现TCP粘包问题

### ISSUE THREAD

**Issue by skaco** [sogou/workflow#701]
Hi,

在验证mysql multi-statement时，发现TCP粘包问题。发送一个包含12个sql的multi-statement给mysql，回包时从第11个包开始会出现粘包的问题。
问题表现如下：
multi-statement形式是`begin;10个insert;commit;`，request query packet大小超过了2000。
抓包文件显示第11个sql(insert)和第12个sql(commit)的结果在同一个response packet里面。
![image](https://user-images.githubusercontent.com/992257/147182750-c29c3ec4-f9bc-4f48-9d6b-af8251aca5ae.png)

试验了包含更多的sql语句的multi-statement，第11个包里合并了第11个及之后所有sql的结果。
换了不同的机器去访问同一个mysql集群，发现这个问题概率性出现。在ping mysql时延更小、CPU更空闲的机器不容易出现粘包问题。

Nagle算法与CORK算法都可能导致TCP粘包，想咨询下workflow有没有方案或建议处理这类粘包问题。

**Comment by Barenboim** [comment]
对端是MySQL server还是Tidb或其它newsql呢？MySQL协议是可以判断一个response在哪里结束的，按理没有你说的粘包问题。multi statement返回的结果应该是一个response而不是多个，response里包含多个结果集。

**Comment by skaco** [comment]
对端是MySQL，从抓包文件看，发送multi-statement返回结果是按照语句为单位返回response。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/ddf23e535fc0b682eef9cf628bab943b019eb29e/src/protocol/mysql_parser.c#L252
在这个地方，每个MySQL OK packet里有个flag，表示是否还有下一个结果集。多结果集我们是理解成为一个response的。多结果集的应用很多，按理不会在这个地方出问题（不过确实我们也改过很多次多结果集的解析问题）。
你先确认一下workflow的代码是什么版本，如果不是最新的更新到最新。如果还是有问题，能不能构造一个可以复现的SQL语句，我们这边来调试一下？

**Comment by Barenboim** [comment]
~~~
begin;insert into aaa values(10,1);insert into aaa values(11,1);insert into aaa values(13,1);commit;
~~~
这条语句可以复现问题是吧？

**Comment by skaco** [comment]
哦哦，OK packet里面的more results都是符合预期的。
`begin;insert into aaa values(14,1);insert into aaa values(15,1);insert into aaa values(16,1);insert into aaa values(17,1);insert into aaa values(18,1);insert into aaa values(19,1);insert into aaa values(20,1);insert into aaa values(21,1);insert into aaa values(22,1);insert into aaa values(23,1);insert into aaa values(24,1);insert into aaa values(25,1);insert into aaa values(26,1);insert into aaa values(27,1);insert into aaa values(28,1);insert into aaa values(29,1);insert into aaa values(30,1);insert into aaa values(32,1);insert into aaa values(33,1);insert into aaa values(34,1);insert into aaa values(35,1);insert into aaa values(36,1);insert into aaa values(37,1);insert into aaa values(38,1);insert into aaa values(39,1);insert into aaa values(40,1);insert into aaa values(41,1);insert into aaa values(42,1);insert into aaa values(43,1);insert into aaa values(44,1);insert into aaa values(45,1);insert into aaa values(46,1);insert into aaa values(47,1);insert into aaa values(48,1);insert into aaa values(49,1);insert into aaa values(50,1);commit;`
当我把语句个数增加到了39个，这个问题是必现的。并且出现了新的报错Got packets out of order
![image](https://user-images.githubusercontent.com/992257/147214273-2066788a-88dc-4942-b9bb-e22dda44b5c4.png)

**Comment by Barenboim** [comment]
重试时的seq out of order问题我们改过了的，但只是在retry的时候才会出现。麻烦你up一下代码再试试。

**Comment by Barenboim** [comment]
我这边执行了你39条语句的case，一切正常，显示36 row affected.

**Comment by Barenboim** [comment]
@skaco
