### ISSUE TITLE
请求返回值乱码问题

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#706]
postman一个请求，workflow服务在Response的body添加数据出现乱码，有时乱码，有时正常：
添加之前打印正常，如图：
![image](https://user-images.githubusercontent.com/62458770/147627985-17b32e01-6af1-4ab4-91ee-87b04b6b5d02.png)
在postman中显示不正常，如果：
![image](https://user-images.githubusercontent.com/62458770/147628095-b2fe27fc-9112-4e67-9508-6ce6a9dcf23e.png)

**Comment by Barenboim** [comment]
这种情况下你先看看你append的数据内容有没有问题，或者是不是你用nocopy的方式，然后内存被修改或回收了。这种太基础的错误不太可能是框架的bug。

**Comment by HzjFirst** [comment]
有一次我也怀疑是这个问题，所以把变量定义成全局的了，但是还出现了这个问题，不知道原因是什么，

**Comment by Barenboim** [comment]
可以贴一下代码。

**Comment by HzjFirst** [comment]
我用全局变量+nocopy的方式测试，返回有问题，但是将采用copy的方式，基本上不出现问题了，我先把问题关了，到时候再频繁出现问题，我就把代码粘上去，咱们一块看看
