### ISSUE TITLE
WSL (Windows下的Linux子系统) 文件任务导致 触发 abort（） 系统ubuntu20.04LTS

### ISSUE THREAD

**Issue by lainswork** [sogou/workflow#709]
libc.so.6!__GI_raise(int sig) (\build\glibc-eX1tMB\glibc-2.31\sysdeps\unix\sysv\linux\raise.c:50)
libc.so.6!__GI_abort() (\build\glibc-eX1tMB\glibc-2.31\stdlib\abort.c:79)
__CommManager::__CommManager(__CommManager * const this) (\home\lains\projects\workflow\src\manager\WFGlobal.cc:364)
__CommManager::get_instance() (\home\lains\projects\workflow\src\manager\WFGlobal.cc:327)
__CommManager::get_instance() (\home\lains\projects\workflow\src\manager\WFGlobal.cc:325)
WFGlobal::get_io_service() (\home\lains\projects\workflow\src\manager\WFGlobal.cc:658)
WFTaskFactory::create_pread_task(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*, unsigned long, long, std::function<void (WFFileTask<FileIOArgs>*)>)(const std::string & pathname, void * buf, size_t count, off_t offset, fio_callback_t callback) (\home\lains\projects\workflow\src\factory\FileTaskImpl.cc:363)
wfrest::HttpFile::send_file(const std::string & path, size_t start, size_t end, wfrest::HttpResp * resp) (\usr\include\c++\9\new:174)
wfrest::HttpResp::File(wfrest::HttpResp * const this, const std::string & path) (\home\lains\projects\wfrest\wfrest\HttpMsg.cc:371)
wfrest::HttpServer::<lambda(const wfrest::HttpReq*, wfrest::HttpResp*)>::operator()(const wfrest::HttpReq *, wfrest::HttpResp *) const(const wfrest::HttpServer::<lambda(const wfrest::HttpReq*, wfrest::HttpResp*)> * const __closure, const wfrest::HttpReq * req, wfrest::HttpResp * resp) (\home\lains\projects\wfrest\wfrest\HttpServer.cc:109)
std::function<void (wfrest::HttpReq const*, wfrest::HttpResp*)>::operator()(wfrest::HttpReq const*, wfrest::HttpResp*) const( __args#1,  __args#0, const std::function<void(const wfrest::HttpReq*, wfrest::HttpResp*)> * const this) (\usr\include\c++\9\bits\std_function.h:683)
wfrest::BluePrint::<lambda(const wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*)>::operator()(wfrest::HttpResp * resp, const wfrest::HttpReq * req, const wfrest::BluePrint::<lambda(const wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*)> * const __closure) (\home\lains\projects\wfrest\wfrest\BluePrint.cc:14)
std::_Function_handler<WFGoTask*(wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*), wfrest::BluePrint::GET(char const*, const Handler&)::<lambda(const wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*)> >::_M_invoke(const std::_Any_data &, wfrest::HttpReq *&&, wfrest::HttpResp *&&, SeriesWork *&&)( __functor,  __args#0,  __args#1,  __args#2) (\usr\include\c++\9\bits\std_function.h:285)
std::function<WFGoTask* (wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*)>::operator()(wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*) const( __args#2,  __args#1,  __args#0, const std::function<WFGoTask*(wfrest::HttpReq*, wfrest::HttpResp*, SeriesWork*)> * const this) (\usr\include\c++\9\bits\std_function.h:683)
wfrest::Router::call(const wfrest::Router * const this, const std::string & verb, const std::string & route, wfrest::HttpServerTask * server_task) (\home\lains\projects\wfrest\wfrest\Router.cc:80)
wfrest::HttpServer::process(wfrest::HttpServer * const this, wfrest::HttpTask * task) (\usr\include\c++\9\bits\char_traits.h:300)
std::__invoke_impl<void, void (wfrest::HttpServer::*&)(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*), wfrest::HttpServer*&, WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*>(void (wfrest::HttpServer::*&)(wfrest::HttpServer * const, WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp> *) __f, wfrest::HttpServer *& __t) (\usr\include\c++\9\bits\invoke.h:73)
std::__invoke<void (wfrest::HttpServer::*&)(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*), wfrest::HttpServer*&, WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*>(void (wfrest::HttpServer::*&)(wfrest::HttpServer * const, WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp> *) __fn) (\usr\include\c++\9\bits\invoke.h:95)
std::_Bind<void (wfrest::HttpServer::*(wfrest::HttpServer*, std::_Placeholder<1>))(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*)>::__call<void, WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*&&, 0ul, 1ul>(std::tuple<WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*&&>&&, std::_Index_tuple<0ul, 1ul>)(std::_Bind<void (wfrest::HttpServer::*(wfrest::HttpServer*, std::_Placeholder<1>))(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*)> * const this, std::tuple<WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*&&> && __args) (\usr\include\c++\9\functional:400)
std::_Bind<void (wfrest::HttpServer::*(wfrest::HttpServer*, std::_Placeholder<1>))(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*)>::operator()<WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*, void>(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*&&)(std::_Bind<void (wfrest::HttpServer::*(wfrest::HttpServer*, std::_Placeholder<1>))(WFNetworkTask<wfrest::HttpReq, wfrest::HttpResp>*)> * const this) (\usr\include\c++\9\functional:484)

具体在WFGlobal.cc
__CommManager()构造函数中 scheduler_.init初始化失败

**Comment by Barenboim** [comment]
我记得这是WSL旧版本的一个问题，刚开始WSL确实不支持Linux AIO。但听说2.0版已经支持了。你那边是什么版本？

**Comment by lainswork** [comment]
WSL1 看来是wsl的锅了
