### ISSUE TITLE
windows vcpkg 崩溃

### ISSUE THREAD

**Issue by lainswork** [sogou/workflow#710]
主文件 
![image](https://user-images.githubusercontent.com/46841563/147823310-0ed2f76e-ee22-413f-88aa-55b7d3ca22e1.png)

workflow 版本workflow:x64-windows   0.9.7 从vcpkg安装
好像是调用stop后线程池没停
![image](https://user-images.githubusercontent.com/46841563/147823254-d68e4ce8-b914-451a-9120-7ad488c035dc.png)

**Comment by Barenboim** [comment]
Windows的最好都更新到最新windows分支代码。我们也尽快更新vcpkg。
stop之后线程池确实不会停。workflow的线程池是client和server共用的。程序退出时才关闭线程。
