### ISSUE TITLE
mysql 连接出现 MySQL Access Denied 

### ISSUE THREAD

**Issue by lainswork** [sogou/workflow#711]
账号lains，密码990720。的组合可以使用Navicat 15 for MySQL连接mysql成功
使用官方的tutorial-12-mysql_cli程序通过命令传入url：
"mysql://lains:990720@127.0.0.1:3306/candlepower?character_set=utf8&character_set_results=utf8"|
会提示MySQL Access Denied 
mysql版本8.0

**Comment by chanchann** [comment]
https://github.com/sogou/workflow/issues/186

**Comment by Barenboim** [comment]
MySQL8默认SHA256 认证的问题。我抽空实现一下。主要这个协议很复杂，而且MySQL官方完全没有相关文档。只有MariaDB网站上可以找到协议描述：https://mariadb.com/kb/en/clientserver-protocol/。
你先在server端修改一下配置吧。

**Comment by Barenboim** [comment]
MariaDB这个文档也很不详细，几乎没法用。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1163
这个问题已经彻底解决！最新代码支持MySQL 8所有的认证方式，包括tcp和SSL。
