### ISSUE TITLE
关于文件任务的问题

### ISSUE THREAD

**Issue by lainswork** [sogou/workflow#712]
以IOService_thread为例
IOService_thread::request中开了单独的线程去读取文件
我阅读代码发现只有IOService_thread::decref中对做完任务的链表进行清理的工作
文件任务在线程中完成后，wf框架是怎么收到消息的呢？
我看源码中与IOService_thread有关系的只有一个Communicator::io_bind 
能不能详细解释这里一下。我在完成win平台的iocp异步文件部分

**Comment by lainswork** [comment]
如果我把
![image](https://user-images.githubusercontent.com/46841563/147948421-af7b8eec-795f-4dbd-9a16-1cdec8d19b4e.png)
作为文件读写完成后的通知事件的话，我仍然不理解为啥要在文件完成后增加IOService_thread的引用计数

**Comment by Barenboim** [comment]
第一个问题。thread方式的文件任务如何通知到Communicator的问题。
我在poller里添加了一个fd（pipe的读端），等待的事件时PD_OP_NOTIFY。Thread IO完成之后向pipe写端写入一个指针，指向完成IO的IOSession。现在的问题是Windows版没有poller，所以这个通知机制在Windows下没有办法使用。

**Comment by Barenboim** [comment]
第二个问题。为什么在thread IOService::aio_finish里对service增加应用计数。
这个做法和linux IOService::aio_finish一样，也和CommService::accept一样，通过增加引用计数来防止service被解绑完成回到handle_unbound()。这时候有一个io事件完成，需要等Communicator::handle_aio_result处理，而这个函数处理完会调用service->decref()减少引用计数。
Thread IO如果IO完成事件被poller获得，才调用aio_finish。如果IO完成之前被io_unbind()，则不会运行到aio_finish，而是当decref到0的时候，回收io的结果。这时是通过pthread_join来等待IO thread退出的。

**Comment by Barenboim** [comment]
这个主意是考虑CommService和IOService随时可能被任何线程解绑，中间还可能夹杂各种错误，因此需要行为很精确。

**Comment by lainswork** [comment]
我大致了解这个poller工作原理了，其中的差别主要在linux上io_bind可以向系统注册事件完成的回调
在win iocp下，处理io结果的是自己的线程池在跑Communicator::handler_thread_routine这个函数，
这....有点难啦...

**Comment by Barenboim** [comment]
嗯嗯，当然Linux下也不用这个。Thread aio一般是mac下使用。Linux的实现你可以看看IOService_ linux。利用的是Linux专用的系统调用。
