### ISSUE TITLE
[Kafka Client] 存在 Partition 失败时后续无法恢复对应的写数据操作

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#713]
当往 Kafka 的 partition 里写数据时，如果某些 partition 写失败，后续在 partition 恢复后，client 也不会往里面更新数据。

需要有定期的探活机制。

**Comment by wzl12356** [comment]
是有若干个partition完全不可用是吗？在不可用期间，produce task执行时失败的吗？

**Comment by hiberabyss** [comment]
> 是有若干个partition完全不可用是吗？在不可用期间，produce task执行时失败的吗？

produce task 没有失败哈，就是只有某几个 partition 失败。

**Comment by wzl12356** [comment]
这种情况下，对应的KafkaRecord的get_status() 返回-1？

**Comment by hiberabyss** [comment]
> 这种情况下，对应的KafkaRecord的get_status() 返回-1？

出错的时候提示的是 err connect，后续就没有错误提示了

**Comment by wzl12356** [comment]
这个错误是怎么打印出来的呢？

**Comment by wzl12356** [comment]
能把完整的错误发出来吗？

**Comment by hiberabyss** [comment]
是用下面的代码打印的哈：

![image](https://user-images.githubusercontent.com/2898670/148046873-1c936a8d-99fc-4c0c-9e78-1875e3340076.png)

**Comment by hiberabyss** [comment]
等我后面找时间复现下哈

**Comment by wzl12356** [comment]
#718 
麻烦验证一下是否可以解决

**Comment by hiberabyss** [comment]
在本地还没法复现这个 case ，我再调研下怎么复现

**Comment by hiberabyss** [comment]
问下目前 kafka produce 的时候有自定义的 partition 选择策略么？还是用的 kafka 默认策略？

然后写数据的时候会有 key 么？

**Comment by Barenboim** [comment]
在WFKafkaClient.h里，有kafka_partitioner_t:
~~~cpp
using kafka_partitioner_t = std::function<int (const char *topic_name,
                                               const void *key,
                                               size_t key_len,
                                               int partition_num)>;
~~~
然后你可以通过WFKafkaTask的set_partitioner接口传入一个partitioner。

**Comment by hiberabyss** [comment]
重现了之前的问题，用新版的 workflow 可以解决！感谢！

**Comment by hiberabyss** [comment]
再请教下 kafka 里的超时时间和 workflow task 里的超时时间是什么关系呢？

**Comment by Barenboim** [comment]
kakfa里的超时好像是kafka协议里的，要填在数据包里的。workflow task里的超时是框架的。
@wzl12356

**Comment by wzl12356** [comment]
> kakfa里的超时好像是kafka协议里的，要填在数据包里的。workflow task里的超时是框架的。 @wzl12356

对，kafka的api接口里面有响应的设置，比如fetch和produce都有，会在内部创建workflow task的时候，进行对应的设置。
