### ISSUE TITLE
计算任务里可以获取series吗？

### ISSUE THREAD

**Issue by grapefruitL** [sogou/workflow#716]
我的需求是做（图像）数据处理，我在Process里拿到数据开了一个计算任务来处理数据，这个计算任务和process形成一个串行，处理结果是通过计算任务的callback通过上下文写入process的response的。
我的问题是：感觉写一个callback来存放response多此一举，我能不能直接在计算任务里获取到series呢？这样创建计算任务的时候callback设置为nullptr就行了，以下是创建计算任务的代码：
```
using MMFactory = WFThreadTaskFactory<MMInput, MMOutput>;
auto processImg_b = std::bind(&processImg, this, _1, _2);
auto callback_b = std::bind(&processImgcallback, this, _1);
MMTask *task = MMFactory::create_thread_task("process_task", processImg_b, callback_b);
```

**Comment by grapefruitL** [comment]
有此想法是因为如果数据还需要下载 那么还需要开一个http 任务获取数据，那么就是三个任务的串行：process->计算任务（如果不需要下载 则直接处理，如果需要下载则加一个wget任务）->按需添加的wget任务。这样的话，我想到两种办法：
1、让计算任务等待wget任务完成，利用上下文拿到下载数据然后处理
2、将计算逻辑放在wget任务的callback里，同时计算任务的callback要根据是否有wget任务来决定是否写response
无论哪种都觉得有点“别扭”，我希望在计算任务里判断：如果没有wget任务则直接写response，如果有则将计算逻辑和写response逻辑放在wget的callback里

**Comment by Barenboim** [comment]
我明白你的需求。我们规定thread task的计算逻辑里不包含series，其实是为了让算法足够的纯粹，就是做INPUT到OUTPUT的转化，让callback里再去使用OUTPUT的结果，然后决定下一步怎么处理。我们认为这样更有利于不同团队的分工。
你个需求，好像并不是一个纯粹的算法，而是让算法直接写response的结果。那你可以直接用我们的go task，计算里需要什么参数直接传进去就可以了。文档：https://github.com/sogou/workflow/blob/master/docs/en/about-go-task.md

**Comment by grapefruitL** [comment]
@Barenboim 谢谢解答，多问一句，如果在go任务的callback里再指定后续串行任务，那后续任务是立即开始还是等待这个callback结束后才开始呢？

**Comment by Barenboim** [comment]
那肯定是callback结束之后开始啊，串到series里都是callback之后开始。想立即开始只能start。

**Comment by grapefruitL** [comment]
谢谢！
