### ISSUE TITLE
关于send_message_async的作用

### ISSUE THREAD

**Issue by fengyonglv** [sogou/workflow#719]
在阅读wf的poller.c源码过程中，看到有管道 pipe_wr/pipe_rd。 其中一个地方对pipe_wr进行写的是在 send_message_async函数中。
而 Communicator::send_message 会调用 send_message_async。
一般来说会调用 send_message_sync这个函数， 而在 entry->ssl 存在的时候才会调用 send_message_async 这个异步写函数。所以请问 send_message_async 这个函数的作用是什么？
![C7B097DB-F10F-43DA-B546-B4593201D0D7](https://user-images.githubusercontent.com/24933778/148351794-262ec728-fc45-42e1-96f4-ba6a2efbe7e1.png)
  
  
在上面使用 send_message_async后， 会在poll_wait中读取 pipe_rd的事件，然后是否会调用 handler_thread_routine 这个函数，如果是这个函数的话，那么对应switch里面是那一个 data.operation ?
![image](https://user-images.githubusercontent.com/24933778/148352367-f4ce50be-fc21-4de9-aad4-0edba3fe4e7c.png)

另外，如果是上面说的事件， 那么，在写入pipe_wr的时候，是什么时候把 old的 operation写进去？
![image](https://user-images.githubusercontent.com/24933778/148352664-a273b193-ba7a-43ca-af22-d1c176def022.png)

**Comment by Barenboim** [comment]
你对代码的阅读有点问题。
目前在ssl的情况下只用async send（这个可以被优化，之后可能会改），非ssl的情况下是先sync send，如果sync send不能发送全部数据，会进入async send的。send_message_sync返回的是剩余多少数据没有发送，当返回值>0，会进入async send。
async send又分两种情况，一种是连接刚刚建立上，fd不在poller里，这时候直接给fd加个写事件。另一种情况，fd是一个复用连接或被动连接（server），那么fd在poller里（等待读事件），我们通过poller_mod原子性的把fd改为写，这时候会写pipe写入一个指针，代表被替换了的poller_node。之后poller通过callback返回一个PD_ST_MODIFIED结果，表示之后的fd被修改。

**Comment by Barenboim** [comment]
感谢提醒，我顺手把SSL的写也优化了一下，现在SSL也先试着同步写了。

**Comment by fengyonglv** [comment]
感谢你的回答，我看代码理解确实是不太准确，经过你的回答之后，解答了我对着这一块很多的疑惑。
但是我还有一个疑问，被替换的poller_node应该是要被free释放掉，为什么不直接就free, 而是要写pipe，等从队列拿出来再free?

**Comment by Barenboim** [comment]
你要考了并发的问题。对poller的操作是多线程并发的，可能这时候poller线程正在使用这个node。而且poller线程使用node还是在锁外的，所以必须写入pipe等待poller线程去处理（调用callback返回给用户）。

**Comment by fengyonglv** [comment]
谢谢你热心回答

**Comment by Barenboim** [comment]
你好，你是不是不小心把star取消了:)

**Comment by fengyonglv** [comment]
好的，我又点回去了
