### ISSUE TITLE
客户端建立TCP连接后无请求情况下框架如何主动发送数据

### ISSUE THREAD

**Issue by gao223845** [sogou/workflow#721]
大家好，我现在正在实现一个物联网设备的接入任务，具体实现是：**在设备与后端建立TCP连接后，我的设备不会发送任何数据到服务器，只有当我的服务器主动发送查询命令时，设备才会返回数据**，但是我看到workflow中都是客户端先发送请求到服务器，服务器callback才能处理，那如果使用workflow框架，可以实现**上述的操作**吗？

**Comment by Barenboim** [comment]
请问服务器主动发送第一条命令之后，client可以发送request吗？如果是这种情况，相对于第一个请求是空请求，这个和MySQL协议是一样的，你可以参考一下MySQLImpl.cc的处理（看nossl分支的，master分支由于要支持SSL，代码太复杂）。

**Comment by Barenboim** [comment]
不过，看起来你的需求是request永远从server端发起？这个模式有点奇怪，我想一想。

**Comment by gao223845** [comment]
因为设备可以主动发起TCP连接，但是设备是被动模式，只有服务器发送工作命令，设备才会开始工作，所以建立连接后需要服务器主动发送工作命令，设备才会回复

**Comment by gao223845** [comment]
最重要的是，设备在被动模式下，建立TCP连接后，什么都不会发送

**Comment by Barenboim** [comment]
这个要实现其实也不难。你先看一看tutorial-10-user_defined_protocol。然后你每个request内容其实都是上一个server命令的回复，client callback其实都是process。
~~~cpp
void callback(MyNetworkTask *server_req)
{
    int cmd = server_req->get_resp()->get_cmd();

    MyNetworkTask *client_resp = WFNetworkTaskFactory<...>::create_client_task(..., callback);
    client_resp->get_req()->set_result(process(cmd));

    series_of(server_req)->push_back(client_resp);
}
~~~
然后第一次请求的req序列化成空（encode函数返回0就可以）。不要并发这个其实是可以work的。

**Comment by Barenboim** [comment]
另外有个global参数最好改一下，否则会出现server 10秒不发命令，client就认为超时的情况：
~~~
#include "workflow/WFGlobal.h"

int main()
{
    int WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.response_timeout = 3600 * 1000;
    WORKFLOW_library_init(&settings);
    ...
}
~~~
我感觉我们通过对task的派生，是可以实现更加自然一点的client-server角色互换的功能的。需要想一想。

**Comment by gao223845** [comment]
我思考了一下，还是不太理解在客户端没有请求的情况下框架如何开始执行server的callback，并且您在代码中通过create_client_task来访问客户端，无法实现，因为设备和服务器不在同一个局域网。所以框架搭建的服务器能否主动发送数据到客户端

**Comment by gao223845** [comment]
我思考了一下，还是不太理解在客户端没有请求的情况下框架如何开始执行server的callback，并且您在代码中通过create_client_task来访问客户端，无法实现，因为设备和服务器不在同一个局域网。所以框架搭建的服务器能否主动发送数据到客户端

**Comment by holmes1412** [comment]
> 我思考了一下，还是不太理解在客户端没有请求的情况下框架如何开始执行server的callback，并且您在代码中通过create_client_task来访问客户端，无法实现，因为设备和服务器不在同一个局域网。所以框架搭建的服务器能否主动发送数据到客户端

是用create_client_task去访问服务器。

我粗糙地画个交互图：

```
[客户端]                                                 [服务器]
               （你可以通过req序列化为空来实现）
发起connection -----------------------------------------> 建立连接

                                                        （keep_alive==-1）

callback(MyNetworkTask *server_req) <------------------ 发起server_req
  |
  V
client_resp = create_client_task();
  |
  V
发送client_resp -----------------------------------------> server收到回复

                                                        （keep_alive==-1）

callback(MyNetworkTask *server_req) <------------------- 发起server_req
。。。
```

**Comment by Barenboim** [comment]
> 我思考了一下，还是不太理解在客户端没有请求的情况下框架如何开始执行server的callback，并且您在代码中通过create_client_task来访问客户端，无法实现，因为设备和服务器不在同一个局域网。所以框架搭建的服务器能否主动发送数据到客户端

我这个示例是连接发起端的代码（也就是client，后续请求的被调用方）。server端的话，可能还更复杂一点。如果你要用这个写server，我建议协议上修改一下，client连接完成之后先发送一个数据包代表自己已经接入。这样server端代码好写一点。

**Comment by Barenboim** [comment]
另外你说的server的callback，是不是指server的process函数？

**Comment by gao223845** [comment]
是我没有说清楚，客户端的设备已经是一个成品了，没有使用workflow，主动建立TCP连接（只会建立连接，不会主动发送任何数据），处于被动模式，任务是：服务器下发指令后可以向服务器返回数据。
服务器上用了workflow，需要服务器主动发送命令，也就是虽然在连接上是设备->服务器，但真正的交互方式是服务器->设备->服务器，所以问题就是服务器上的workflow如何在没有收到请求的情况下主动发送命令到客户端，或者说是否容易实现

**Comment by Barenboim** [comment]
如果是这样的情况，在没有改workflow框架的情况下，只能这么做：
~~~cpp
class MyProtocolServer : public WFServer<MyRequest, MyResponse>
{
    WFConnection *new_connection(int accept_fd) override
    {
         char *buf = first request;
         write(accept_fd, but, but_size)
         return this->WFServer::new_connection(accept_fd);
    }
}
~~~
也就是说，先给client发送第一条请求。这样你的server就会运行到process啦。当然你process收到的req，实际是client的resp。然后你下次写client发请求，就让server执行回复就可以了，这和普通的server没有什么区别。不过不要忘了加上这句：
~~~
void process(...)
{
    task->set_keep_alive(10*1000);
}
~~~
因为这时候keep_alive超时实际上是client的回复超时。
有一点绕，但要实现是可以的（需要server在new_connection里发送第一个请求）。

**Comment by gao223845** [comment]
感谢感谢，我尝试一下
