### ISSUE TITLE
Windows版本https访问一次后无法再次访问

### ISSUE THREAD

**Issue by wooviet** [sogou/workflow#722]
具体操作是：
1.WFHttpServer start的时候传入自签名的证书，Windows版本和Linux版本在两台机器上各启动一个。
2.使用谷歌浏览器分别访问两个服务器监听地址，Windows版本第一次可以正常访问，之后F5刷新界面再次访问，刷新按钮一直转圈没反应，linux版本不存在这个问题。
这个现象你们复测应该可以出现。

**Comment by holmes1412** [comment]
你好，Windows并不是一个稳定的版本，仅供尝试。这个问题我们会先记录，等以后有人帮忙维护windows分支的时候进行修复，或者如果你知道如何修复，欢迎提PR~~~

线上都建议使用Linux版。

**Comment by dengjunplusplus** [comment]
@wooviet 麻烦问下用的是哪个版本，测试程序方便发一下吗？我这边本地复现不了，用tutorial里面的http_echo_server加上ssl证书以后，能够正常访问

**Comment by Barenboim** [comment]
这个问题有可能和浏览器用的TSL版本也有关系。

**Comment by Barenboim** [comment]
你好@wooviet ，能不能用我们windows分支的最新代码再帮我们试一下。我感觉可能是您之前测试代码版本的问题。

**Comment by wooviet** [comment]
@Barenboim @dengjunplusplus 使用windows分支最新代码重新编译后测试，该问题还是存在，具体测试代码可以参考：
void process_https_requests(WFHttpTask* server_task){
    auto* http_req = server_task->get_req();
    std::string uri = http_req->get_request_uri();
    printf("recv request uri: %s, method: %s\n", uri.c_str(), http_req->get_method());

    auto* resp = server_task->get_resp();
    resp->add_header_pair("Content-Type", "application/json; charset=UTF-8");
    resp->set_status_code("200");
}

int main(){
    WFHttpServer https_server(process_https_requests);
    if (int ret = https_server.start("0.0.0.0", 20046, "test.pem", "test.key"); ret != 0){
        printf("fail to start https server. ret: %d\n", ret);
        return ret;
    }
    printf("start suc\n");
    getchar();
    https_server.stop();
    return 0;
}
之后通过谷歌浏览器访问https://本机ip:20046，会出现之前描述的问题。

**Comment by dengjunplusplus** [comment]
@wooviet 我这边试了下还是正常的，每次都能正常访问

![image](https://user-images.githubusercontent.com/65080805/151347884-0074073f-bb88-4655-b8ca-06f31cabd722.png)
![437d049259a5571132e159c7359cbd4](https://user-images.githubusercontent.com/65080805/151347502-7866fc66-20f0-4a5d-9703-0f68a7477530.png)
![0932c0c3f4f9c8ac6feba5af738e5da](https://user-images.githubusercontent.com/65080805/151347511-c2c41c52-b025-45e6-bc5c-c7db9e2da880.png)

**Comment by dengjunplusplus** [comment]
@wooviet 我的联系方式已发你邮箱，可以微信或QQ联系我们一起看下问题
