### ISSUE TITLE
无法打开包括文件: “sys/uio.h”: No such file or directory	(Windows)

### ISSUE THREAD

**Issue by guan4286** [sogou/workflow#726]
win10系统，cmake编译如下：
![image](https://user-images.githubusercontent.com/34204574/149324964-afc0db00-5e27-432d-b3cb-f1b7aba2c59a.png)

然后转移到vs下编译，报错如下：
![image](https://user-images.githubusercontent.com/34204574/149325150-2e31c1d6-d0b7-4607-9307-1ba669a63437.png)
![image](https://user-images.githubusercontent.com/34204574/149325273-f708c7cb-5ef2-476a-b904-40b8b3e779c2.png)

请问这是怎么回事？

**Comment by guan4286** [comment]
OpenSSL-Win64为我手动创建的一个文件夹

**Comment by Barenboim** [comment]
汗。。。。马上修了。这个是手误。

**Comment by guan4286** [comment]
啥意思？我需要重新下载吗？

**Comment by Barenboim** [comment]
是我之前改windows代码出的小问题。你pull一下再试试。

**Comment by guan4286** [comment]
![image](https://user-images.githubusercontent.com/34204574/149328399-90297981-ce1f-470f-ba73-4150a49e6d30.png)
这个正常 吗？算编译成功了吗？

**Comment by Barenboim** [comment]
这个应该是编译通过了：）
