### ISSUE TITLE
请问一下这边连接mysql失败是什么原因呢？

### ISSUE THREAD

**Issue by lixiaoqian521** [sogou/workflow#729]
`        std::string url = "mysql://root:" + StringUtil::url_encode_component("WangjunyiLIXIAOQIAN123@@@") + "@localhost";
        resp->MySQL(url, "SHOW DATABASES");`
"error":"Connection refused"
然后用mysql -u root -pWangjunyiLIXIAOQIAN123@@@是可以正常登录的

**Comment by Barenboim** [comment]
你好，确定是什么原因了嘛？好像是用的wfrest项目？

**Comment by lixiaoqian521** [comment]
不好意思好像还没有确认

**Comment by lixiaoqian521** [comment]
已经确定原因了，mysql没有开启，因为我是一个新手刚开始使用mysql，然后mysql8.0好像不太一样，不会默认打开3306端口？我查看my.cnf发现3306是被占用的，所以一直连接被拒绝。

**Comment by lixiaoqian521** [comment]
或者我这么说一下就是
apt安装mysql，然后mysql -u root -p连接没问题，但是用api去调用连接会被拒绝
排查解决过程：
sudo netstat -anlp|grep mysql
查看没有打开端口号
sudo vim /etc/mysql/mysql.conf.d/mysqld.cnf
发现
#port = 3306
被注释起来
去掉注释，重启mysql（重启过程中发现mysql不能关掉用sudo service mysql restart，会卡住）
采用kill -9，然后他自动重启，之后重新调用wf api去连接mysql正常

**Comment by lixiaoqian521** [comment]
> 你好，确定是什么原因了嘛？好像是用的wfrest项目？

是wfrest，很喜欢这种http框架，比较丝滑。
