### ISSUE TITLE
so库问题

### ISSUE THREAD

**Issue by SkyTeamWater** [sogou/workflow#730]
so 库，实际上走的 .a 后期加命令转成的 so。。所以 mac 下只有 .a,而 linux 下，硬编码了 libpthread.so
要对 cmakelists 做大量改动，让它直接编译生成 so 是最好的办法，但是建议还是库自身去完善它

**Comment by Barenboim** [comment]
什么意思？是说我们编出来的.so和libpthread.so不兼容吗？

**Comment by SkyTeamWater** [comment]
看起来是这样的


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月19日 11:14:04
收件人: ***@***.***&gt;;
抄送: "Bradford ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] so库问题 (Issue #730)




 
什么意思？是说我们编出来的.so和libpthread.so不兼容吗？

**Comment by SkyTeamWater** [comment]
应该要直接make出.so而不是.a转.so

**Comment by Barenboim** [comment]
我们问问其他的fedaro有没有这个问题。

**Comment by SkyTeamWater** [comment]
> 我们问问其他的fedaro有没有这个问题。

我是在把workflow添加到xmake的包管理器中出现了问题，如果不对CMakeList进行更改，只有fedora过不了ci，如果改CMakeList全部都因为.so的问题过不了ci

**Comment by Barenboim** [comment]
感谢帮我们提交xmake-repo。如果确认需要编译真实.so我们修改一下，顺便发个版给你提及xmake。

**Comment by SkyTeamWater** [comment]
确认，谢谢
![image](https://user-images.githubusercontent.com/51621873/150060554-8a92b35b-3d80-4572-b510-e48c98b9a8b7.png)
现在只能通过这种方式不用shared

**Comment by SkyTeamWater** [comment]
![5TVGQJZ3DO~Z(K9BFDMP8B8](https://user-images.githubusercontent.com/51621873/150060920-c93b0717-19b0-4688-840c-4f028cdeed77.jpg)
而且缺符号

**Comment by holmes1412** [comment]
> 应该要直接make出.so而不是.a转.so

这个起因是公司内的上线版本管理规范需要，所以我们要编译出.a，并且按照libstdc++的写法在.so以文本方式带上了相关依赖库。

**Comment by SkyTeamWater** [comment]
原来如此

**Comment by waruqi** [comment]
fedora上报 libpthread.so not found，有可能只提供了静态pthread库，所以 
cmakelist里面写死 libpthread.so need，之后link workflow.so 时候，链接器就报错了

不一定要重编so，但可能需要适配下 pthread 的问题

**Comment by Barenboim** [comment]
> fedora上报 libpthread.so not found，有可能只提供了静态pthread库，所以 cmakelist里面写死 libpthread.so need，之后link workflow.so 时候，链接器就报错了
> 
> 不一定要重编so，但可能需要适配下 pthread 的问题

我们正在统一改成真实的.so，并且分别叫libworkflow.a和libworkflow.so，这样可以么？
现在在解决mac下.so的问题。好像mac下产生.so需要指定依赖，我们还不太会。大家可以看看这个pr。
https://github.com/sogou/workflow/pull/731

**Comment by Barenboim** [comment]
搞不定Mac下wfkafka动态库的问题，因为要链上zlib，lz4和snappy三个库。所有现在Mac下wfkafka只生成静态库。
我把这个PR合了，大家看看满不满足要求。
@waruqi @SkyTeamWater

**Comment by Barenboim** [comment]
求助APPLE下的wfkafka动态库生成问题。

**Comment by SkyTeamWater** [comment]
> 搞不定Mac下wfkafka动态库的问题，因为要链上zlib，lz4，snappy和zstd四个库，但怎么都找不到。所以现在Mac下wfkafka只生成静态库。
> 我把这个PR合了，大家看看满不满足要求。
> @waruqi @SkyTeamWater 

麻烦打一个tag发个release我过一下ci

**Comment by Barenboim** [comment]
> > 搞不定Mac下wfkafka动态库的问题，因为要链上zlib，lz4，snappy和zstd四个库，但怎么都找不到。所以现在Mac下wfkafka只生成静态库。
> > 我把这个PR合了，大家看看满不满足要求。
> > @waruqi @SkyTeamWater
> 
> 麻烦打一个tag发个release我过一下ci

能不能先用master试一下？

**Comment by SkyTeamWater** [comment]
> > > 搞不定Mac下wfkafka动态库的问题，因为要链上zlib，lz4，snappy和zstd四个库，但怎么都找不到。所以现在Mac下wfkafka只生成静态库。
> > > 我把这个PR合了，大家看看满不满足要求。
> > > @waruqi @SkyTeamWater
> > 
> > 麻烦打一个tag发个release我过一下ci
> 
> 能不能先用master试一下？

好的

**Comment by SkyTeamWater** [comment]
不过macosx有可能是因为ci test没有用到kafka

**Comment by SkyTeamWater** [comment]
不过还是感谢你们为我们解决问题

**Comment by Barenboim** [comment]
安卓和这个有没有关系：
~~~
if (NOT CMAKE_SYSTEM_NAME STREQUAL "Android")
	find_package(OpenSSL REQUIRED)
endif ()
~~~
直接去掉又好像有别的问题。

**Comment by waruqi** [comment]
目前是指定了 STATIC/SHARED 同时编译的 static/shared ，编译也慢，做包的时候，还得额外删掉不要的库

https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

我觉得可以就一个 add_library 然后走 BUILD_SHARED_LIBS 自动设置切换当前编译 .a 还是 .so

**Comment by Barenboim** [comment]
你好，ruqi。请问xmake-repo是只需要静态库，还是都需要，还是可选呢？

**Comment by waruqi** [comment]
> 你好，ruqi。请问xmake-repo是只需要静态库，还是都需要，还是可选呢？

默认安装是仅静态库，如果指定 `xrepo install -k shared workflow` 或者 xmake.lua 里面指定 `add_requires("workflow", {configs = {shared = true}})` ，就会安装动态库。。

既节省编译时间和磁盘空间，还可以按需切换使用 .a 还是 .so

**Comment by Barenboim** [comment]
好的，感谢。明天我们搞一下。

**Comment by BDZNH** [comment]
> @Barenboim 除了Android全过ci，包括macosx，Android报错undefined reference ![image](https://user-images.githubusercontent.com/51621873/150162904-8332e27b-4709-4913-8547-1129c2d1dc8d.png)

@Barenboim  @SkyTeamWater 

安卓的部分需要手动把 ssl 添加到编译环境里面，可以参考我仓库里的修改 ![add build workflow for android script](https://github.com/BDZNH/workflow-android/commit/4db56fe52baf4e3533a19824ab46b88632b94121)

我这个办法是放在 NDK 里面编译的，如果放在AOSP里面编译还需要一些单独的办法。AOSP 自己带了 ssl ，如果能配置好 soong 的配置，应该也可以编译出来。

**Comment by holmes1412** [comment]
感谢！这是个好消息～
安卓的话，交叉编译时确实是需要用户指定ssl路径的，当时提交了这个改动：https://github.com/sogou/workflow/pull/322 需要类似这样，用户可以在交叉编译的脚本里指定比如这样：
```sh
cmake -DOPENSSL_ROOT_DIR=/usr/local \
      -DOPENSSL_LIBRARIES=/usr/local/lib \
      -DOPENSSL_INCLUDE_DIR=/usr/local/include \
      ...
```
麻烦看看这样的话合适吗？

**Comment by SkyTeamWater** [comment]
> 

谢谢帮助！我现在按照这个试一下

**Comment by SkyTeamWater** [comment]
@holmes1412 很遗憾，在指定DOPENSSL_ROOT_DIR DOPENSSL_LIBRARIES DOPENSSL_INCLUDE_DIR后依旧同样的报错信息

**Comment by Barenboim** [comment]
最新的Cmake改动已经支持生成mac下的wfkafka动态库了。
hi，@waruqi。我们参考了一下brpc的做法还是决定同时生成static和shared两个库。我们整体编译速度比较快，多生成一个应该不会占用太多编译时间。非常感谢你的建议和帮助。

**Comment by SkyTeamWater** [comment]
感谢，我这边还在想办法解决Android下的openssl问题

**Comment by holmes1412** [comment]
@BDZNH @SkyTeamWater 非常感谢对Android下的改动建议，我觉得这个仓库的改动[add build workflow for android script](https://github.com/BDZNH/workflow-android/commit/4db56fe52baf4e3533a19824ab46b88632b94121)是合理的，请问你们能不能把其中对CMakeLists.txt，src/CMakeLists.txt，tutorial/CMakeLists.txt的改动给workflow提一个PR呢？

**Comment by waruqi** [comment]
目前 master 上只有一处 OPENSSL_INCLUDE_DIR 的设置，所以不完整，link 不了，应该至少吧 link libraries 补上， 否则指定 OPENSSL_ROOT_DIR OPENSSL_LIBRARIES 也是没效果的。。

另外，android 高版本 ndk 自带 ssl，所以实际是可以过掉的，而 r20 等稍微低点的版本没 ssl ，得手动设置进去。

https://github.com/sogou/workflow/blob/0ec98afdde75511717704f4217c69a32eaa65410/src/CMakeLists.txt#L7

不过，xmake-repo 仓库里面，我还是强行打 patch 进去，让 android 过掉了，暂时可用。。 @SkyTeamWater

**Comment by BDZNH** [comment]
> 目前 master 上只有一处 OPENSSL_INCLUDE_DIR 的设置，所以不完整，so 库 link 不了，应该至少吧 link libraries 补上， 否则指定 OPENSSL_ROOT_DIR OPENSSL_LIBRARIES 也是没效果的。。
> 
> 另外，android 高版本 ndk 自带 ssl，所以实际是可以过掉的，而 r20 等稍微低点的版本没 ssl ，得手动设置进去。
> 
> https://github.com/sogou/workflow/blob/0ec98afdde75511717704f4217c69a32eaa65410/src/CMakeLists.txt#L7
> 
> 不过，xmake-repo 仓库里面，我还是强行打 patch 进去，让 android 过掉了，暂时可用。。 @SkyTeamWater

你确定 NDK 带了 ssl 吗，我从这个链接下的 https://dl.google.com/android/repository/android-ndk-r23b-linux.zip ，确实没有 libssl.so 和 libcrypto.so 。

**Comment by BDZNH** [comment]
> @BDZNH @SkyTeamWater 非常感谢对Android下的改动建议，我觉得这个仓库的改动[add build workflow for android script](https://github.com/BDZNH/workflow-android/commit/4db56fe52baf4e3533a19824ab46b88632b94121)是合理的，请问你们能不能把其中对CMakeLists.txt，src/CMakeLists.txt，tutorial/CMakeLists.txt的改动给workflow提一个PR呢？

改 CmakeLists.txt 倒是好说，今天晚点我看看发一个 pr 过来。
但是用NDK编译的话，直接用当前的仓库里的 GNUMakefile 还不行，用 NDK 编译还得带一些NDK特有的编译参数。可以参考我提交里面的那个 shell 脚本。

**Comment by waruqi** [comment]
> > 目前 master 上只有一处 OPENSSL_INCLUDE_DIR 的设置，所以不完整，so 库 link 不了，应该至少吧 link libraries 补上， 否则指定 OPENSSL_ROOT_DIR OPENSSL_LIBRARIES 也是没效果的。。
> > 另外，android 高版本 ndk 自带 ssl，所以实际是可以过掉的，而 r20 等稍微低点的版本没 ssl ，得手动设置进去。
> > https://github.com/sogou/workflow/blob/0ec98afdde75511717704f4217c69a32eaa65410/src/CMakeLists.txt#L7
> > 
> > 不过，xmake-repo 仓库里面，我还是强行打 patch 进去，让 android 过掉了，暂时可用。。 @SkyTeamWater
> 
> 你确定 NDK 带了 ssl 吗，我从这个链接下的 https://dl.google.com/android/repository/android-ndk-r23b-linux.zip ，确实没有 libssl.so 和 libcrypto.so 。

一开始，我用了 ndk 23 直接就过掉编译了，切到 ndk20 才复现了 undef ssl 的问题，我以为高版本带了，才会这样，刚看了下，确实没带。。

**Comment by SkyTeamWater** [comment]
> @BDZNH @SkyTeamWater 非常感谢对Android下的改动建议，我觉得这个仓库的改动[add build workflow for android script](https://github.com/BDZNH/workflow-android/commit/4db56fe52baf4e3533a19824ab46b88632b94121)是合理的，请问你们能不能把其中对CMakeLists.txt，src/CMakeLists.txt，tutorial/CMakeLists.txt的改动给workflow提一个PR呢？

提了

**Comment by BDZNH** [comment]
> @BDZNH @SkyTeamWater 非常感谢对Android下的改动建议，我觉得这个仓库的改动[add build workflow for android script](https://github.com/BDZNH/workflow-android/commit/4db56fe52baf4e3533a19824ab46b88632b94121)是合理的，请问你们能不能把其中对CMakeLists.txt，src/CMakeLists.txt，tutorial/CMakeLists.txt的改动给workflow提一个PR呢？

支持 NDK 编译的修改已经发起 pr 了。

**Comment by holmes1412** [comment]
刚才看到PR了，正想提两个小建议：
1. commit log里不要带中文～PR的描述里就无所谓，但commit log跟随项目代码走，还是希望尽量统一；
2. SSL库的编译方式可能不会放到workflow的编译里，你觉得类似build_android.sh这样的工具由NDK用户自行管理是否合适呢？

**Comment by BDZNH** [comment]
> 

好的，commit log 这个是我疏忽了，平日里给自己的仓库提交比较随意。。。
build_android.sh 这个也是考虑到和目前 workflow 里面的 GNUMakefile 的方式不太契合，所以我没有把脚本随 pr 带过来，我也倾向于由用户自己编译 ssl 。 使用 NDK 编译 ssl 和 workflow 的方式可以开一个 doc 或者 issue 供后面使用的同学参考。

**Comment by holmes1412** [comment]
了解，GNUMakefile主要为了支持我们内部编译上线平台（平台流程需要通过make、make install和make check），所以确实只是一个额外的工具～
我们会为build_android.sh增加一个doc或者issue～这个建议很好～

**Comment by Barenboim** [comment]
android问题@BDZNH  已经帮助我们解决了，感谢！麻烦大家看看现在还有没有别的什么问题。

**Comment by Barenboim** [comment]
我个目前对Linux下的shared库（.so）不执行link_target_libraries操作，也就是说用户在编译可执行文件时，除了-lworkflow之后，还需要自行-lpthread -lssl -lcrypto。但APPLE和ANDROID的话，由于执行了这几行：
~~~
if (APPLE)
	target_link_libraries(${SHARED_LIB_NAME} OpenSSL::SSL OpenSSL::Crypto pthread)
elseif(ANDROID)
	target_link_libraries(${SHARED_LIB_NAME} ssl crypto c)
endif ()
~~~
动态库应该就包含了依赖的信息了，编译可执行无需再-lpthread -lssl -lcrypto。请教一下大家，这个做法可以吗？

**Comment by Barenboim** [comment]
修改成这样了：
~~~
if(ANDROID)
	target_link_libraries(${SHARED_LIB_NAME} ssl crypto c)
else()
	target_link_libraries(${SHARED_LIB_NAME} OpenSSL::SSL OpenSSL::Crypto pthread)
endif ()
~~~
不知道会不会再出现Federo那个问题。。。

**Comment by Barenboim** [comment]
@SkyTeamWater 
v0.9.10 已经发布。可以用这个release入xmake-repo。

**Comment by SkyTeamWater** [comment]
收到，在改了

**Comment by SkyTeamWater** [comment]
感谢

**Comment by Barenboim** [comment]
我担心Federa又要不过……

**Comment by SkyTeamWater** [comment]
ci全过了

**Comment by holmes1412** [comment]
感谢各位小伙伴鼎力相助🎉🎉🎉

**Comment by Barenboim** [comment]
多谢各位！@SkyTeamWater 能不能帮我们把libwfkafka也入一下xmake-repo？cmake加上-DKAFKA=y就会编译出wfkafka。希望libwfkafka作为一个独立的库。

**Comment by SkyTeamWater** [comment]
> 多谢各位！@SkyTeamWater 能不能帮我们把libwfkafka也入一下xmake-repo？cmake加上-DKAFKA=y就会编译出wfkafka。希望libwfkafka作为一个独立的库。

我试试嗷

**Comment by SkyTeamWater** [comment]
@Barenboim 你是想单独搞一个库还是作为workflow的某个选项?

**Comment by SkyTeamWater** [comment]
> 多谢各位！@SkyTeamWater 能不能帮我们把libwfkafka也入一下xmake-repo？cmake加上-DKAFKA=y就会编译出wfkafka。希望libwfkafka作为一个独立的库。
请问对libwfkafka的描述应该是怎么样的呢？

**Comment by Barenboim** [comment]
这个是C++ Workflow的Kafka客户端插件，依赖workflow，libz，zstd，snappy，lz4等。
描述可以写"C++ Workflow's Kafka Client"。

**Comment by SkyTeamWater** [comment]
收到

**Comment by SkyTeamWater** [comment]
openssl不需要吗

**Comment by Barenboim** [comment]
相当于workflow的一个plugin，依赖workflow，所以也是依赖ssl和crypto。

**Comment by SkyTeamWater** [comment]
ok

**Comment by SkyTeamWater** [comment]
0.9.10的workflow还没有merge上去，我暂时没办法

**Comment by Barenboim** [comment]
好的好的，不着急等等ruki大佬merge。

**Comment by SkyTeamWater** [comment]
@Barenboim 能提供一下test libwfkafka的代码片段吗

**Comment by Barenboim** [comment]
> @Barenboim 能提供一下test libwfkafka的代码片段吗

这个的难点在于，需要先启动一个kafka机群。。。要不你new一个WFKafkaClient然后直接delete了？

**Comment by SkyTeamWater** [comment]
我直接按类测试了


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月23日 12:31:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"Bradford ***@***.***&gt;;
主题: Re: [sogou/workflow] so库问题 (Issue #730)




  
@Barenboim 能提供一下test libwfkafka的代码片段吗
  
这个的难点在于，需要先启动一个kafka机群。。。要不你new一个WFKafkaClient然后直接delete了？

**Comment by Barenboim** [comment]
两个库都成功入xmake-repo了，再次感谢各位！

**Comment by Barenboim** [comment]
@SkyTeamWater 可不可以再帮我们发个Issue，介绍一下xrepo下workflow和libwfkafka的安装？

**Comment by SkyTeamWater** [comment]
> @SkyTeamWater 可不可以再帮我们发个Issue，介绍一下xrepo下workflow和libwfkafka的安装？

好的，半小时后，现在在忙

**Comment by SkyTeamWater** [comment]
@Barenboim 要中文版还是英文版啊?
