### ISSUE TITLE
是否能实现HTTP服务在返回后继续做其他IO操作？

### ISSUE THREAD

**Issue by Kexiii** [sogou/workflow#741]
想了解下workflow是否支持http server在返回后继续做一些其他耗时的IO操作？比如在一次http requset业务流程中最后需要做一些耗时的远端网络IO或者磁盘IO打点一些日志，但是HTTP的最终response其实已经在这些IO前完备了，workflow能否支持先直接返回http结果，然后继续完成剩下的与返回结果无关的其他IO计算, 缩短整体的http请求响应时间？

**Comment by Barenboim** [comment]
你真是问到了workflow的强项了：）这当然可以实现，并且非常优雅。server task的callback里，可以继续向series里追加任务的。例如：
~~~cpp
void process(WFHttpTask *server_task)
{
    ...
    server_task->set_callback([](WFHttpTask *server_task) {
        WFFileIOTask *log_task = WFTaskFactory::create_pwrite_task(...);
         series_of(server_task)->push_back(log_task);
    });
}
~~~
server_task的callback调用时机是回复完成，默认是nullptr。这个示例为server_task设置了一个callback，callback里继续向series追加任务。这个做法非常安全。

**Comment by Barenboim** [comment]
其实无论是server_task还是client_task，callback的调用时机是一致的，就是http（或其他网络协议）交互完成。

**Comment by Kexiii** [comment]
感谢回复，相当赞，我尝试一下👍
