### ISSUE TITLE
关于Upstream的使用不理解的地方

### ISSUE THREAD

**Issue by jiangmz1985** [sogou/workflow#744]
我想用Upstream来做反向代理，负载均衡，于是从test中单独把Upstream的操作拨离出来封装成一个单独的进程，另外模拟了2个后端的服务端进程，反向代理proxy的关键代码如下：
`	UpstreamManager::upstream_create_weighted_random("weighted.random", false);

	AddressParams address_params = ADDRESS_PARAMS_DEFAULT;

	address_params.weight = 1000;

	UpstreamManager::upstream_add_server("weighted.random",
										 "127.0.0.1:8001",
										 &address_params);

	address_params.weight = 1;

	UpstreamManager::upstream_add_server("weighted.random",
										 "127.0.0.1:8002",
										 &address_params);`

但是我用curl 来访问的时候应该访问proxy的地址却不知道应该访问哪个地址  curl http://weighted.random 提示域名不能解析，我看test中是使用workflow的创建create_http_task任务可直接访问http://weighted.random。我不理解外部应该怎么访问proxy，请指教~

**Comment by holmes1412** [comment]
你的curl应该访问你的proxy的地址。之后由proxy帮你转发到weighte.random这个名字，而upstream帮你在绑定的8001和8002做二选一。

因为upstream是这个用workflow写的proxy进程内部的域名列表，curl无法知道。

**Comment by jiangmz1985** [comment]
> 你的curl应该访问你的proxy的地址。之后由proxy帮你转发到weighte.random这个名字，而upstream帮你在绑定的8001和8002做二选一。
> 
> 因为upstream是这个用workflow写的proxy进程内部的域名列表，curl无法知道。

相当于我需要在proxy里再开放一个端口比如8080，将访问8080的请求，使用weighte.random这个名字通过upstream做负载是么，这个proxy的实现是否可以参照tutorial-05-http_proxy.cc呢?

**Comment by Barenboim** [comment]
> > 你的curl应该访问你的proxy的地址。之后由proxy帮你转发到weighte.random这个名字，而upstream帮你在绑定的8001和8002做二选一。
> > 因为upstream是这个用workflow写的proxy进程内部的域名列表，curl无法知道。
> 
> 相当于我需要在proxy里再开放一个端口比如8080，将访问8080的请求，使用weighte.random这个名字通过upstream做负载是么，这个proxy的实现是否可以参照tutorial-05-http_proxy.cc呢?

Proxy基本上就是tutorial05那个模板。你是http协议吗？http的话，用了upstream之后，我们在Host这个header里默认填写的是upstream名，也就是说填写的是你的"weighted.random"。如果你需要填写成目标ip或域名需求加一点东西。

**Comment by jiangmz1985** [comment]
> 
感谢回复，我刚刚仿着tutorial05的模板，将upstream引入后，确实实现了一个能进行HTTP服务的负载与路由的反向代理服务端，不知道对于直接使用TCP协议的websock请求而言，这些功能是否都支持呢，在API的调用上或者编程上有没有特殊的地方呢？

**Comment by Barenboim** [comment]
webscoket的server暂时不支持噢。目前主要用法都是基于req，resp模式的。其它模式还在探索。

**Comment by jiangmz1985** [comment]
> webscoket的server暂时不支持噢。目前主要用法都是基于req，resp模式的。其它模式还在探索。

OK，感谢回复~
