### ISSUE TITLE
Got no_reply error for my customized protocol

### ISSUE THREAD

**Issue by wangh09** [sogou/workflow#75]
Hi, I'm playing with workflow + protobuf, here's my example:

the server
```
#include <workflow/ProtocolMessage.h>
#include <workflow/WFTask.h>
#include <workflow/WFServer.h>
#include <workflow/WFFacilities.h>
#include "proto/common.pb.h"
using namespace std;
namespace protocol {
    class OrderMessage : public ProtocolMessage {
    public:
        trade::Order order;
    private:
        int encode(struct iovec *vectors, int max) override {
            int size = order.ByteSizeLong();
            void *buffer = new char[size];
            order.SerializePartialToArray(buffer, size);
            vectors[0].iov_base = buffer;
            vectors[0].iov_len = size;
            return 1;
        }
        int append(const void *buf, size_t *size) override {
            order.ParsePartialFromArray(buf, size[0]);
            return 1;
        }
    };
}
using WFTestTask = WFNetworkTask<protocol::OrderMessage, protocol::OrderMessage>;
void process(WFTestTask *task)
{
    protocol::OrderMessage *req = task->get_req();
    protocol::OrderMessage *resp = task->get_resp();
    cout << req->order.price() << endl;
    resp->order.set_price("123");
}

static WFFacilities::WaitGroup wait_group(1);

int main()
{
    using WFTestServer = WFServer<protocol::OrderMessage, protocol::OrderMessage>;
    WFServerParams params = SERVER_PARAMS_DEFAULT;
    WFTestServer server(&params, process);
    if (server.start(AF_INET, 8080) == 0) {
        cout << "success!" << endl;
        wait_group.wait();
        server.stop();
    } else {

    }
    return 0;
}
```
the client
```
using WFTestTask = WFNetworkTask<protocol::OrderMessage, protocol::OrderMessage>;
using tutorial_callback_t = std::function<void (WFTestTask *)>;
class MyFactory : public WFTaskFactory
{
public:
    static WFTestTask *create_tutorial_task(const std::string& host,
                                                unsigned short port,
                                                int retry_max,
                                                tutorial_callback_t callback)
    {
        using NTF = WFNetworkTaskFactory<protocol::OrderMessage, protocol::OrderMessage>;
        WFTestTask *task = NTF::create_client_task(TT_TCP, host, port,
                                                       retry_max,
                                                       std::move(callback));
        task->set_keep_alive(30 * 1000);
        return task;
    }
};

int main()
{
    std::string host = "0.0.0.0";
    int port = 8080;
    std::function<void (WFTestTask *task)> callback =
    [&host, port, &callback](WFTestTask *task) {
        int state = task->get_state();
        int error = task->get_error();
        cout << state << " " << error << endl;
        if (state != WFT_STATE_SUCCESS)
        {
            if (state == WFT_STATE_SYS_ERROR)
                fprintf(stderr, "SYS error: %s\n", strerror(error));
            else if (state == WFT_STATE_DNS_ERROR)
                fprintf(stderr, "DNS error: %s\n", gai_strerror(error));
            else
                fprintf(stderr, "other error.\n");
            return;
        }
        protocol::OrderMessage *resp = task->get_resp();
        cout << resp->order.price() << endl;
    };
    WFFacilities::WaitGroup wait_group(1);
    WFTestTask *task = MyFactory::create_tutorial_task(host, port, 0, callback);
    auto req = task->get_req();
    req->order.set_price("333");
    task->start();
}
```

and I got the no reply error (namely state = 2, error = 0) on the client side. Any suggestion? Thanks !

**Comment by Barenboim** [comment]
Because client’s main function terminates! 
Please: wait_group.wait();
BTW, are you sure your encode() doesn’t have memleak?

**Comment by Barenboim** [comment]
About exit of the program: [https://github.com/sogou/workflow/docs/about-exit.md](https://github.com/sogou/workflow/docs/about-exit.md)

**Comment by Barenboim** [comment]
You implementation of append() cannot garentee you receive the whole message. You know that, right?

**Comment by wangh09** [comment]
> Your implementation of append() cannot garentee you receive the whole message. You know that, right?

Thanks for your reply! 
For the append(): yes I know that, just want to see it works for now;
For the enocde(): I have to make the buffer a member of the message right?

**Comment by Barenboim** [comment]
> > Your implementation of append() cannot garentee you receive the whole message. You know that, right?
> 
> Thanks for your reply!
> For the append(): yes I know that, just want to see it works for now;
> For the enocde(): I have to make the buffer a member of the message right?

Yes. Make it a member of the message class, allocate memory in it's constructor or encode() function and release in it's destructor. But don't do this:
~~~cpp
        using NTF = WFNetworkTaskFactory<protocol::OrderMessage, protocol::OrderMessage>;
        WFTestTask *task = NTF::create_client_task(TT_TCP, host, port,
                                                       retry_max,
                                                       std::move(callback));
        task->set_keep_alive(30 * 1000);
        task->get_resp()->buffer = new char[MAX];     // not very good.
        return task;
~~~
This makes the response class non-RAII. But the response object may be destroyed and reconstructed during communication when retrial occurs. If it's not a RAII class, you have to set **prepare** function or make a derivation of WFNetworkTask.

**Comment by wangh09** [comment]
Another question about the client: I see it is tasks that can be kept alive, but a task seems to be not thread safe. Then how to reuse the connections? 
Say my architecture is Client <-> ServerA <-> ServerB, ServerA accepts stateless http requests from the Client, and passes them to ServerB on persistent tcp connections (10 for example). should I create 10 tasks and use locks to share them?

**Comment by Barenboim** [comment]
So you are writing a ServerA? Please refer to [tutorial-05-http_proxy](https://github.com/sogou/workflow/blob/master/docs/tutorial-05-http_proxy.md)
Note: connections can be reused, but tasks cannot be reused by users.

**Comment by Barenboim** [comment]
task->set_keep_alive() sets the connection underneath to be reused or not, not the task.
For http protocol,  adding http header “Connection” is a better way. Though both ways work.
