### ISSUE TITLE
嵌入式应用，workflow是否支持观察者模式，如增加signal。

### ISSUE THREAD

**Issue by edwincj2017** [sogou/workflow#750]
您好，请问以下场景，workflow框架怎么高效处理 【n事件--->n*m业务】？
设备：嵌入式arm边缘计算设备
OS：Linux
业务场景：下连不同iot设备，上连云服务，同时支持对接第三方接口，经常有数据变化，系统配置修改，远程控制，升级设备固件等一个事件对应多个业务模块的情形，观察者模式更适合，
boost太大且繁杂，不是很适合嵌入式，workflow精简高效，支持高并发，但仅支持抽象工厂模式和任务。
急盼回复，诚谢。

**Comment by Barenboim** [comment]
你相当于观察者模式下的server吗？

**Comment by edwincj2017** [comment]
是，移植workflow到嵌入式arm+linux里，设备有流媒体数据处理，边缘算法等。

**Comment by Barenboim** [comment]
client先发送一条watch消息，然后server在有数据的时候推送，然后连接一直保持到server主动关闭吗？

**Comment by Barenboim** [comment]
有个不太完美的解决方案：https://github.com/sogou/workflow/issues/543

**Comment by edwincj2017** [comment]
类似，但不完全是订阅，发布的方式，先将业务模块绑定到对应的signal，当该signal触发时，绑定了该singal的业务模块会以回调方式处理，类似于C#的事件，boost的signal2，

**Comment by Barenboim** [comment]
主要还是看通信模型。signal你需要自己实现一下。用一个counter把server task所在的series堵住，然后signal里打开这个counter，然后在counter的callback里push回数据就好了。不过我们这块目前支持不了太复杂的通信模型，比如你的client没事还要发个心跳什么的，我们可能就直接认为是垃圾数据就把连接断开了。

**Comment by edwincj2017** [comment]
看了#543，push应该不适合，实际我们不是server-client模式，只是单进程里不同业务模块之间的交互，控制。
比如，手机设置了夜晚模式后，所有app都会知道系统也设置为夜晚模式，进而都调整app自己ui和亮度等

**Comment by Barenboim** [comment]
> ，

这个很有意思啊！好像是某种进程通信模式？目前我们的进程通信确实只有网络一种。你可以尝试实现一下，或者再发一些材料出来看看。如果这个东西比较标准，我们还是可以加一下的。

**Comment by edwincj2017** [comment]
就是进程通信，需求也类似与QT库的信号--槽，感谢耐心回复。
开源workflow并持续更新，为你们点赞打call ！！！

**Comment by edwincj2017** [comment]
https://www.jianshu.com/p/fa2603cabbe1  嵌入式观察者 供参考

**Comment by Barenboim** [comment]
谢谢，我看一看

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/923/files
做出来了。我们挺适合做这个的。

**Comment by Barenboim** [comment]
增加了这几个函数：
~~~cpp
class WFTaskFactory
{
    static WFConditional *create_conditional(const std::string& cond_name,
                                                                          SubTask *task, void **msgbuf);

     static WFConditional *create_conditional(const std::string& cond_name,
                                                                           SubTask *task);

      static void signal_by_name(const std::string& cond_name, void *msg);
}
~~~
create_conditonal函数把任何任务转化成conditional，用这个conditional取代原来的任务（conditional也是一种任务）。cond_name表示条件名，用于signal_by_name函数的唤醒。msgbuf时用于存放消息的缓冲区，可以缺省。
signal_by_name唤醒cond_name下的所有conditional，让对应任务被执行。
示例：
~~~cpp
#include "workflow/WFTaskFactory.h"

int main()
{
    WFHttpTask *task = WFTaskFactory::create_http_tasl(url, ...);
    WFConditoinal *cond = WFTaskFactory::create_conditional("test", task);
    WFTimerTask *timer = WFTaskFacotry::create_timer_task(1000000, [](void *) {
        WFTaskFactory::signal_by_name("test", nullptr);
    });

    timer->start();
    cond->start();

    pause();
    return 0;
}
~~~
这个示例，实现了延迟一秒的http抓取。就算signal先于cond->start()被执行也是正确的。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/master/docs/about-conditional.md
