### ISSUE TITLE
性能测试时，打印Resource temporarily unavailable错误

### ISSUE THREAD

**Issue by whanwant** [sogou/workflow#752]
我在linux centos7 性能测试客户端性能的时候(大概1w多caps)，不停刷Resource temporarily unavailable错误。
![image](https://user-images.githubusercontent.com/26357687/153562873-cac84622-b294-4b0e-be41-7615a885f153.png)

![U1(59}OY@I42KS~0}IT55_Q](https://user-images.githubusercontent.com/26357687/153561446-36f90f49-3433-4044-b213-4dbab573d2da.jpg)
压测过程中 netstat查看端口情况，链路数已达到max_connections的最大数量  
同时发现绝大部分socket都不能及时收上来消息，怀疑是不是协议栈处理响应的速度慢了？(因为我基本上的收到响应回調就扔到另一个线程池，也没做多余处理)

请问有什么办法可以解决这个问题？

**Comment by Barenboim** [comment]
max_connections调一下，就可以解决Resource temporarily unavailable问题。
对于最大并发请求数的控制，推荐使用资源池的方法：
https://github.com/sogou/workflow/blob/master/docs/about-conditional.md
如果存在tcp buffer里数量来不及读取的情况，可以考虑增加全局配置里的poller_threads。不过你可能问题不在这。

**Comment by Barenboim** [comment]
@whanwant

**Comment by guijiyang** [comment]
> max_connections调一下，就可以解决Resource temporarily unavailable问题。 对于最大并发请求数的控制，推荐使用资源池的方法： https://github.com/sogou/workflow/blob/master/docs/about-conditional.md 如果存在tcp buffer里数据来不及读取的情况，可以考虑增加全局配置里的poller_threads。不过你可能问题不在这。

我设置了max_connections，还是会有这个问题，好像是没有生效，不管设置成什么数字，在一个for循环里面，启动几千的httptask。
`struct WFGlobalSettings settings =
    {
        /*	.endpoint_params	=	*/	{
            /*	.max_connections		=	*/	20,
            /*	.connect_timeout		=	*/	10 * 1000,
            /*	.response_timeout		=	*/	10 * 1000,
            /*	.ssl_connect_timeout	=	*/	10 * 1000,
            /*	.use_tls_sni			=	*/	false
            },
        /*	.dns_server_params	=	*/	ENDPOINT_PARAMS_DEFAULT,
        /*	.dns_ttl_default	=	*/	12 * 3600,
        /*	.dns_ttl_min		=	*/	180,
        /*	.dns_threads		=	*/	8,
        /*	.poller_threads		=	*/	4,
        /*	.handler_threads	=	*/	10,
        /*	.compute_threads	=	*/	-1,
        /*	.resolv_conf_path	=	*/	NULL,
        /*	.hosts_path			=	*/	NULL
    };
    WORKFLOW_library_init(&settings);`

**Comment by Barenboim** [comment]
为什么你把max_connections调成20了？难道不是应该往上调？
用法：
~~~cpp
int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAUTL;
    settings.max_connections = 5000;
    WORKFLOW_library_init(&settings);
    ...
}
~~~

**Comment by guijiyang** [comment]
那我可能对这个参数理解错了，我以为这个错误是因为客户端发的请求太多了。

**Comment by Barenboim** [comment]
> 那我可能对这个参数理解错了，我以为这个错误是因为客户端发的请求太多了。现在可以了，多谢！

咦，你和发issue的是同一个人吗？

**Comment by guijiyang** [comment]
> > 那我可能对这个参数理解错了，我以为这个错误是因为客户端发的请求太多了。现在可以了，多谢！
> 
> 咦，你和发issue的是同一个人吗？

不是，我正好看到类似的问题，就借着问一下了，哈哈
