### ISSUE TITLE
关于tcp长连接的问题

### ISSUE THREAD

**Issue by lsm19870508** [sogou/workflow#764]
有几个问题，求大佬指点啊：
1、之前问到过tcp长连接主动给客户端推消息，当时提到的大难是调用series->push接口，来主动推送，那么现在的问题是，我怎么能拿到对应的task对象进行操作呢？
或者说，我能不能直接拿到socketfd或者更上层的对象进行保存,然后有需要的时候可以取出对象进行推送操作
 2、再就是有没有socket建立连接和连接断开的回调函数？这个需求也是希望能确切判定连接是否还存在以进行处理
谢谢~~

**Comment by lsm19870508** [comment]
我这边的工作场景是这样的.
客户端发指令给服务器，然后服务器对指令进行处理后，调用各个嵌入式智能设备，所以说需要服务器具备主动推送消息的能力。
原本预想是这样：
workflow->写服务器
qt->写pc客户端
c->写嵌入式客户端
但是现在根据我对代码的理解，似乎workflow支持的是客户端一次请求一次返回的形式，如果我想主动推送消息给嵌入式客户端那边，似乎没有太好的办法。

**Comment by Barenboim** [comment]
1、server_task->push()操作的对象就是底层的socket（或SSL），push操作就是对socket直接写。调用push()操作显然是在server_task的生命周期之内。你不可能保持server_task对应的sockfd，因为这个随时可能被关闭。
2、这两个时机你都是可以得到的。得到连接建立事件的方法是实现server的new_connection函数：
~~~cpp
class MyHttpServer : public WFHttpServer
{
    WFConnection *new_connection(int accept_fd) override
    {
        // You operation.
        if (success)
             return this->WFHttpServer::new_connection(accept_fd);
        else
             return NULL;
    }
}
~~~
获得连接关闭事件的方法是， 给连接设置一个上下文和一个deleter。deleter调用时机就是连接关闭的时机了：
~~~cpp
int process(WFHttpTask *server_task)
{
    WFConnection *conn = server_task->get_connection();
    MyConnContext *ctx = conn->get_context();
    if (ctx == nullptr)
    {
        ctx = new MyConnContext;
        auto deleter = [](void *ctx) { delete (MyConnContext *)ctx; }
        conn->set_context(ctx, deleter);
    }
}
~~~

**Comment by Barenboim** [comment]
其实你的那个工作场景是可以实现的，就是会比较麻烦。你在server的process里用counter堵住任务流就可以了。事件到达的时候调用server_task的push操作。出现错误或连接关闭，就打开counter让任务流结束。任务流不结束，就是相当于你持有了socket。

**Comment by lsm19870508** [comment]
第2点已经明白，十分感谢。
但是第1点仍然有些不明白的地方。
如果我将process用counter阻塞的话，那客户端是否得监听多个socket?一个socket相当于专门的监听者，一直在跟服务器连着，等候服务器发消息过来，而另外一个socket则进行其它非阻塞的通讯？
否则的话，用同一socket的话，就会阻塞消息队列的吧？

**Comment by Barenboim** [comment]
是的。你想用一个socket同时watch，然后还能随时发送请求。我们确实是做不到的。

**Comment by lsm19870508** [comment]
明白了，感谢~~

**Comment by TianlongXiang** [comment]
> 其实你的那个工作场景是可以实现的，就是会比较麻烦。你在server的process里用counter堵住任务流就可以了。事件到达的时候调用server_task的push操作。出现错误或连接关闭，就打开counter让任务流结束。任务流不结束，就是相当于你持有了socket。

当我有很多这样的请求通过计数器堵住的时候，对底层的任务调度会不会有影响

**Comment by Barenboim** [comment]
> > 其实你的那个工作场景是可以实现的，就是会比较麻烦。你在server的process里用counter堵住任务流就可以了。事件到达的时候调用server_task的push操作。出现错误或连接关闭，就打开counter让任务流结束。任务流不结束，就是相当于你持有了socket。
> 
> 当我有很多这样的请求通过计数器堵住的时候，对底层的任务调度会不会有影响

不会，counter就是一小段内存而以，不占什么资源。
