### ISSUE TITLE
mysql客户端针对不同查询语句返回结果的区分和处理

### ISSUE THREAD

**Issue by xiaoshizijiayou** [sogou/workflow#768]
我现在遇到这样的问题，
1.mysql客户端有很多不同查询语句，由于返回结果是异步的，不知道如何处理结果的获取，目前能想到的：a.都用一个返回回调函数，在里面通过表名来区分处理，但是这样回调函数就太长了；b.针对不同的查询语句，注册不同名的回调函数，分别在里面加上对应处理，这样感觉需要写好多回调函数，请指教下有没有更好的方案
2.目前接口里是不是没有，根据字段名直接获取字段值的函数，需要自己封装使用，是吗？

**Comment by Barenboim** [comment]
1、你的task里本来就可以放自己的用户数据，task->user_data。你在user_data里自己做的什么来区分就可以了。我觉得这个问题的解决方法有许多种。
2、我们的MySQLResult由多个result set组成的结构，每个result set通过cursor扫出结果。我们并不会提前给result set的内容建立KV形式的映射，所以你只能顺序的访问。

**Comment by xiaoshizijiayou** [comment]
嗯呢，我上面说的，使用各自查询使用各自的回调函数的方案可以吗？

**Comment by Barenboim** [comment]
可行啊。我觉得各调各的callback最好。

**Comment by xiaoshizijiayou** [comment]
嗯，按这样的话，同一类查询请求在同对应回调函数里，是顺序执行的吗，会乱序吗？

**Comment by Barenboim** [comment]
你并发发出去的请求，回调顺序肯定是不能保证的啊。和你是不是指定同一个回调函数没有关系。

**Comment by xiaoshizijiayou** [comment]
嗯嗯，好的，多谢
