### ISSUE TITLE
kafka客户端崩溃

### ISSUE THREAD

**Issue by song-git** [sogou/workflow#771]
初始化一个WFKafkaClient，然后启动一个查询任务，由于kafka服务未启动，回调函数打印了错误信息：Kafka meta api failed。
主线程阻塞于getchar函数，此时输入任意字符使得主线程退出。在退出时程序崩溃。
崩溃点为： WFTaskFactory.cc:190 ，调试发现 WFTaskFactory.cc:187行 delete node->task; 析构时会将 counters_map_.rb_node 置为空指针，因此在 190行counters_map_.rb_node为空指针导致崩溃发生。

使用的版本为 0.9.9

**Comment by Barenboim** [comment]
可能是命名计数器没有count到目标，程序结束的问题。这个理论上是不允许的，感觉有可能是WFKafkaClient处理上的一些问题。你是否有调用WFKafkaClient::deinit()呢？

**Comment by song-git** [comment]
十分感谢大佬的回答，事实上我是想实现一个循环处理事件的kafka客户端，以及能够正确的结束它。
由于我对workflow研究得还不够深入，因此可能用法上存在错误，代码如下， 我试图在 kafka_callback 回调函数中发现连接失败时重新发起连接。 目前发现当返回状态为 WFT_STATE_TASK_ERROR 时，再次create_kafka_task似乎是一种错误的行为。
`
#include <stdio.h>
#include "workflow/WFKafkaClient.h"
#include "workflow/WFFacilities.h"

#define log_error_g printf
#define log_debug_g printf

static WFKafkaClient g_kafka_client;
static bool g_kafka_flag = false; /* 用于标识kafka客户端是否启动 */

static WFKafkaTask *g_kafka_task = nullptr;
static const char *WATCH_TOPIC = "topic=abc&api=fetch";

static unsigned int g_kafka_failed_count = 0;

static void _commit_callback(WFKafkaTask *p_kafka)
{
    // do nothing now.
}

static void kafka_callback(WFKafkaTask *p_kafka)
{
    int state = p_kafka->get_state();
    int error = p_kafka->get_error();

    if (state != WFT_STATE_SUCCESS)
    {
        log_error_g("kafka callback error msg: %s\n", WFGlobal::get_error_string(state, error));

        // 逐渐递增重连kafka的时间, 直到1分钟
        if (g_kafka_failed_count < 60)
            ++g_kafka_failed_count;

        // 防止KAFKA没启动时连接太频繁, 增加一个定时器
        WFTimerTask *p_next = WFTaskFactory::create_timer_task(
            g_kafka_failed_count * 1000000,
            [](WFTimerTask *t)
            {
                log_error_g("reconnect.\n");
                WFKafkaTask *_next = g_kafka_client.create_kafka_task(WATCH_TOPIC, 3, kafka_callback);
                series_of(t)->push_back(_next);
            });

        series_of(p_kafka)->push_back(p_next);
        return;
    }

    g_kafka_failed_count = 0;

    do
    {
        int api_type = p_kafka->get_api_type();
        if (Kafka_Fetch != api_type)
        {
            log_debug_g("kafka callback error msg type: %d\n", api_type);
            break;
        }

        protocol::KafkaResult *new_result = p_kafka->get_result();
        if (nullptr == new_result)
            break;

        std::vector<std::vector<protocol::KafkaRecord *>> records;
        new_result->fetch_records(records);

        if (records.empty())
            break;

        // TODO 处理records中数据

        WFKafkaTask *commit_task = NULL;
        commit_task = g_kafka_client.create_kafka_task("api=commit", 3, _commit_callback);

        series_of(p_kafka)->push_back(commit_task);

    } while (0);

    WFKafkaTask *p_next = g_kafka_client.create_kafka_task(WATCH_TOPIC, 3, kafka_callback);
    series_of(p_kafka)->push_back(p_next);

    return;
}

int kafka_start()
{
    int ret = g_kafka_client.init("kafka://127.0.0.1:9092", "abc");
    if (ret != 0)
    {
        return ret;
    }

    g_kafka_flag = true;

    g_kafka_task = g_kafka_client.create_kafka_task(WATCH_TOPIC, 3, kafka_callback);

    if (nullptr == g_kafka_task)
    {
        log_error_g("main: create kafka failed.\n");
        return -1;
    }

    log_debug_g("kafka_start.\n");

    protocol::KafkaConfig kafka_config;
    kafka_config.set_client_id("abc");
    g_kafka_task->set_config(kafka_config);
    g_kafka_task->start();

    return 0;
}

void kafka_stop()
{
    log_debug_g("kafka_stop.\n");

    // 会触发assert
    if (g_kafka_flag)
    {
        //     g_kafka_flag = false;

        //     if (nullptr != g_kafka_task)
        //         g_kafka_task->dismiss();

        g_kafka_client.deinit();
    }
}

int main()
{
    kafka_start();

    getchar();

    kafka_stop();
    return 0;
}
`

**Comment by song-git** [comment]
十分感谢大佬的回答，这实际上可能是我没有正确的处理错误的状态导致的。
事实上我是想知道如何在一个kafka查询任务启动后，优雅的取消和关闭这个任务，也就是说异步任务还没有返回和执行回调，但是主程序需要退出。此时如何取消这个异步查询任务。

**Comment by Barenboim** [comment]
也非常感谢你把这个现象报给我们，我也修改了一下未完成named counter在退出时的行为。之前逻辑上确实会有double free的问题。现在直接不管了，因为这种情况我们本来也不允许：https://github.com/sogou/workflow/pull/772
kafka任务还没有callback要退出程序，应该是做不到。kafka任务是复合任务，任务之间不会检查程序是否已经退出，会直接发起下一步的任务，所以很可能程序会直接core了。关于程序的退出，可以看看这个文档：
https://github.com/sogou/workflow/blob/master/docs/about-exit.md

**Comment by song-git** [comment]
我又仔细阅读了一下doc中关于exit小节的内容，大概已经知道解决方案了。非常抱歉，耽误了作者宝贵的时间。

**Comment by song-git** [comment]
感谢感谢，我想这个问题已经解决了。 顺带说一下这个库确实非常好用， 哈哈。 感谢你们的贡献。
