### ISSUE TITLE
提升了http抓取的兼容性

### ISSUE THREAD

**Issue by Barenboim** [sogou/workflow#782]
我们发现还有一些不太规范的http server，没有在http header里指定body长度，而通过关闭连接的方法来代表传输结束。例如这个URL：http://xh.5156edu.com/hot2.php ，返回的http header是这样的：
~~~
  HTTP/1.1 200 OK
  Connection: close
  Date: Thu, 03 Mar 2022 12:43:52 GMT
  Server: Microsoft-IIS/6.0
  X-Powered-By: PHP/5.1.2
  Content-type: text/html
~~~
http body消息传输完成之后，直接关闭了连接。以前我们会得到一个CONNRESET错误（在原来的tutorial-05-http_proxy里，我们还在callback里特判了这种情况）。现在，我们内部增加了一些处理逻辑，不再认为这是一个错误回复。代码的修改在：https://github.com/sogou/workflow/blob/516da621aea136c4c25c048b89875f62c9d20af6/src/factory/HttpTaskImpl.cc#L342

**Comment by Barenboim** [comment]
之前http proxy示例里，写了这样的代码：
~~~cpp
void http_callback(WFHttpTask *task)
{
    auto *resp = task->get_resp();
    int state = resp->get_state();
    int error = resp->get_error();

    if (state == WFT_STATE_SYS_ERROR && error == ECONNRESET)
        state == WFT_STATE_SUCCESS;

    if (state == WFT_STATE_SUCCESS)
    {
         if (resp->get_parserd_body(&body, &size))
             ...
    }
}
~~~
显然不应该把这个兼容性处理在用户代码里实现。目前，proxy的代码已经简化为：
~~~cpp
void http_callback(WFHttpTask *task)
{
    auto *resp = task->get_resp();
    int state = resp->get_state();
    int error = resp->get_error();

    if (state == WFT_STATE_SUCCESS)
    {
         resp->get_parserd_body(&body, &size);
         ...
    }
}
~~~
无需不再判断CONNRESET错误，也无需判断get_parsed_body()的返回值了，代码大幅简化。

**Comment by wasphin** [comment]
> 我们发现还有一些不太规范的http server，没有在http header里指定body长度，而通过关闭连接的方法来代表传输结束。

这个其实是符合规范的，长度判断可以参考：
https://datatracker.ietf.org/doc/html/rfc2068#section-4.4
对应的是最后一种情况。

**Comment by Barenboim** [comment]
> > 我们发现还有一些不太规范的http server，没有在http header里指定body长度，而通过关闭连接的方法来代表传输结束。
> 
> 这个其实是符合规范的，长度判断可以参考： https://datatracker.ietf.org/doc/html/rfc2068#section-4.4 对应的是最后一种情况。

是的，后来我也发现HTTP协议是允许这个方式的……只是现在很少有server这么干。
我也更新了一下代码里的注释，不再描述为不规范。
