### ISSUE TITLE
GoTask代码疑问

### ISSUE THREAD

**Issue by fengyonglv** [sogou/workflow#784]
请教一个关于GoTask代码的问题，看得有一点疑惑。 executor_thread_routine这里是线程池执行的函数，但是在这个函数里面为什么又会把queue->task_list的任务添加到线程池里面？ 因为go_task->start时候调用Executor::request就把任务添加到线程池里面。  
https://github.com/sogou/workflow/blob/0db42d9344c8faa9c9d7744a5c0f73789bbb5a21/src/kernel/Executor.cc#L92

**Comment by Barenboim** [comment]
这个就是我们的计算调度方法啊，来保证每个一个ExecQueue调度的公平性。你可以自行理解一下这个算法的优点，代码也没几行，都在Executor.cc里。
