### ISSUE TITLE
windows编译问题

### ISSUE THREAD

**Issue by xiaohuixiong123** [sogou/workflow#785]
错误
CMake Error at src/kernel/CMakeLists.txt:9 (message):
  IOService unsupported.

CMakeLists.txt:9
if (CMAKE_SYSTEM_NAME STREQUAL "Linux" OR CMAKE_SYSTEM_NAME STREQUAL "Android")
	set(IOSERVICE_FILE IOService_linux.cc)
elseif (UNIX)
	set(IOSERVICE_FILE IOService_thread.cc)
else ()
	message(FATAL_ERROR "IOService unsupported.")
endif ()
在makefile中不支持windows这怎么办呢，直接封掉message(FATAL_ERROR "IOService unsupported.")可以吗

**Comment by Barenboim** [comment]
麻烦用Windows分支。主分枝只支持unix。

**Comment by Barenboim** [comment]
你切换到Windows分支，readme里有编译的说明

**Comment by xiaohuixiong123** [comment]
ok Thankyou

**Comment by bingoabs** [comment]
Thanks. Made a ridiculous mistake.
