### ISSUE TITLE
windows tutorial问题

### ISSUE THREAD

**Issue by xiaohuixiong123** [sogou/workflow#786]
您好！
turorial 中的WORKFLOW_INCLUDE_DIR指定的路径是哪个呢，workflow中并没有include的路径呢？

**Comment by Barenboim** [comment]
应该是根目录下的 "_include"。主分支"src/include"目录是给bazel用到。

**Comment by xiaohuixiong123** [comment]
您好！根目录中并没有_include的目录呢

**Comment by xiaohuixiong123** [comment]
已解决，谢谢！编译完workflow之后即可
