### ISSUE TITLE
是不是不支持 redis 存取字节 ？

### ISSUE THREAD

**Issue by icefoxhz** [sogou/workflow#792]
class Student
{
public:
	int age = 16;
	char* name = "zhansan";
};

Student stu;
stu.age = 22;
stu.name = "lisi";
char data[1024] = { 0 };
::memcpy(&data, &stu, sizeof(Student));

string sData(data, sizeof(Student));

Student stu1;
::memcpy(&stu1, sData.c_str(), sizeof(Student));

cout << stu1.age << " " << stu1.name << endl;

/ /  存入redis
{
  auto setTask = WFTaskFactory::create_redis_task(URL, RETRY_MAX, redisSet_callback);
  auto req = setTask->get_req();
  req->set_request("SET", { "name", sData});
  setTask->start();
}

请问，要如何取？ 我取出来都是被截断的，只能取到 age !!     还是我写的哪里有问题 ？

**Comment by Barenboim** [comment]
😓
C++不是这么用的啊，你要写个函数把Student类的对象作序列化和反序列化，memcpy不能复制name所指向的内容的。

**Comment by Barenboim** [comment]
你把name写成数组，比如：
char name[100] = "zhansan"
可以。

**Comment by icefoxhz** [comment]
好的~ 谢谢~ 我试试

**Comment by icefoxhz** [comment]
经测试，序列化后没问题了~  3q
