### ISSUE TITLE
workflow的http server支持异步应答http请求吗？

### ISSUE THREAD

**Issue by lkkey80** [sogou/workflow#796]
#include <stdio.h>
#include "workflow/WFHttpServer.h"

int main()
{
    WFHttpServer server([](WFHttpTask *task) {
        task->get_resp()->append_output_body("<html>Hello World!</html>");
    });

    if (server.start(8888) == 0) { // start server on port 8888
        getchar(); // press "Enter" to end.
        server.stop();
    }

    return 0;
}
也就是在另外的线程里处理任务，然后填充  task->get_resp()->append_output_body("<html>Hello World!</html>");应答，而不是在
http_process_t里直接应答。

**Comment by Barenboim** [comment]
proxy就是一个简单的异步server：
https://github.com/sogou/workflow/blob/master/docs/tutorial-05-http_proxy.md
gitee上有几个更简单的示例：
https://gitee.com/sogou/workflow/issues/I3ZESU
https://gitee.com/sogou/workflow/issues/I400D1
关于server的回复时机，可以看一下FAQ：
https://github.com/sogou/workflow/issues/170

**Comment by Barenboim** [comment]
如果要等待非本框架的异步任务，可以用counter解决。参考这个issue下面的回复:
https://github.com/sogou/workflow/issues/751

**Comment by lkkey80** [comment]
感谢解答。

**Comment by EricPengShuai** [comment]
@Barenboim 您好，我刚刚接触 WF 项目，对其中的 http server 异步示例 tutorial-05-http_proxy.cc 有点疑惑，编译运行之后 
尝试着运行
```bash
./http_proxy 9090
````
浏览器访问 http://localhost:9090 提示的总是 404 Not Found. 想问一下怎样才能访问到 `WFT_STATE_SUCCESS`

另外关于异步问题，就是 WF 提供的 http server 框架都是异步的吗，就是只要调用 `resp->append_output_body_nocopy` 接口就可以直接返回结果，而不需要等待 process 返回吗

**Comment by Barenboim** [comment]
> @Barenboim 您好，我刚刚接触 WF 项目，对其中的 http server 异步示例 tutorial-05-http_proxy.cc 有点疑惑，编译运行之后 尝试着运行
> 
> ```shell
> ./http_proxy 9090
> ```
> 
> 浏览器访问 http://localhost:9090 提示的总是 404 Not Found. 想问一下怎样才能访问到 `WFT_STATE_SUCCESS`
> 
> 另外关于异步问题，就是 WF 提供的 http server 框架都是异步的吗，就是只要调用 `resp->append_output_body_nocopy` 接口就可以直接返回结果，而不需要等待 process 返回吗

你好，能不能重发个issue?
