### ISSUE TITLE
服务端、客户端如何主动关闭套接字

### ISSUE THREAD

**Issue by song-git** [sogou/workflow#798]
在基本的服务器、客户端通讯程序中，如何实现以下操作呢：
1、服务端接收到客户端的请求并处理后，响应数据，然后主动关闭套接字。
2、客户端发送一些数据后，主动关闭套接字。
我查阅了文档和其他issues，没有找到类似解决办法。

**Comment by Barenboim** [comment]
请问你是什么协议，如果是http，直接加上connection: close就可以了。其他协议，task->set_keep_alive(0)就是短连接。

**Comment by Barenboim** [comment]
如果你的client任务只想发送，不想接收数据就关闭连接，也是可行的，直接把接收超时设为0，task->set_recv_timeout(0)。然后你将得到一个超时错误。

**Comment by song-git** [comment]
感谢楼上的回答，我使用了 task->set_keep_alive(0) ，可以实现目标。
我们使用的是自定义的TLV格式的协议。
