### ISSUE TITLE
tcp连接建立后，如果发生异常导致断链，服务端和客户端是否有事件回调接口及时感知到异常?

### ISSUE THREAD

**Issue by zhaoyaogit** [sogou/workflow#803]
测试了tutorial-10-user_defined_protocol目录下的server和client，关闭任意一方，对方都没有任何异常日志打印，需要客户端再发送一笔，才会打印unknown error。socket的错误errorno没有明确打印出来。
1，socket断链是否存在感知及时回调事件处理？
2，socket错误是否明确打印错误的errorno？

**Comment by Barenboim** [comment]
连接关闭是可以被跟踪的。
server:
~~~cpp
int process(WFMyTask *task)
{
    if (task->get_task_seq() == 0)
    {
        WFConnection *conn = task->get_connection();
        conn->set_context(NULL, [](void *context){ printf("Connection closed\n"); });
    }
}
~~~
task->get_task_seq()得到这个task是连接上的第几个请求。如果是第0个，就调用set_context设置一个连接上下文。set_context()第一个参数是上下文，第二个参数是deleter，用来销毁context。deleter调用时机是连接被释放。
client简单的可以在callback里设置，但需要先判断是不是一个成功的请求（失败请求可能连接根本没建立上）。
~~~cpp
void my_callback(WFMyTask *task)
{
    if (task->get_state() == WFT_STATE_SUCCESS && task->get_task_seq() == 0)
    {
        WFConnection *conn = task->get_connect();
        conn->set_context(NULL, [](void *context){ printf("Connection closed\n"); });
    }
}
~~~
对于一个keep-alive的连接，一般关闭原因都是一方close或keep-alive时间到期。所以，基本上也没有errno。通信过程中的socket错误，可以在callback里拿到。当state == WFT_STATE_SYS_ERROR时，error就是errno。对于server_task，callback需要自己set一下，例如：
~~~cpp
int process(WFMyTask *server_task)
{
    server_task->set_callback([](WFMyTask *task) {
          printf("state = %d, error = %d\n", task->get_state(), task->get_error());
    });
}
~~~

**Comment by Barenboim** [comment]
> 测试了tutorial-10-user_defined_protocol目录下的server和client，关闭任意一方，对方都没有任何异常日志打印，需要客户端再发送一笔，才会打印unknown error。socket的错误errorno没有明确打印出来。
> 1，socket断链是否存在感知及时回调事件处理？
> 2，socket错误是否明确打印错误的errorno？

另外，这个unknown error应该不是workflow打的吧。

**Comment by zhaoyaogit** [comment]
> > 测试了tutorial-10-user_defined_protocol目录下的server和client，关闭任意一方，对方都没有任何异常日志打印，需要客户端再发送一笔，才会打印unknown error。socket的错误errorno没有明确打印出来。
> > 1，socket断链是否存在感知及时回调事件处理？
> > 2，socket错误是否明确打印错误的errorno？
> 
> 另外，这个unknown error应该不是workflow打的吧。
关闭server服务程序。client继续发送消息，大概卡3秒后才返回错误：Unknown error
int error = task->get_error();
……
fprintf(stderr, "SYS error: %s\n", strerror(error)); //error的值1225
打印：SYS error: Unknown error
我先看看代码，刚开始了解这个库，还没仔细看代码，谢谢了

**Comment by Barenboim** [comment]
我知道了，你应该这么打印：
~~~cpp
#include <workflow/WFGlobal.h>

void callback(WFMyTask *task)
{
    state = task->get_state();
    error = task->get_error();
    fprintf(stderr, "%s\n", WFGlobal::get_error_string(state, error));
}
~~~
不过error等于1225有点奇怪。你用的是windows吗？

**Comment by zhaoyaogit** [comment]
> 

是的。windows分支代码在windows平台测试的。

**Comment by Barenboim** [comment]
我感觉如果你server关了，client应该是连接失败错误，对应的error就是errno应该没问题。那么你调用strerror似乎也是对的。很奇怪为什么打印unknown。

**Comment by Barenboim** [comment]
查了一下Windows下1225是：The remote computer refused the
network connection
是不是Windows下不是用strerror函数来打印？不过我们的WFGlobal::get_error_string()也是调用的strerror。

**Comment by zhaoyaogit** [comment]
> 我们的WFGlobal::get_error_string()也是调用的strerror。

打印1225是用strerror函数打印的。使用WFGlobal::get_error_string()打印也是unknown，我先研究下，代码还没仔细看。只是初步了解下了。

**Comment by Barenboim** [comment]
@zhaoyaogit 你好！我看你star一圈workflow的相关项目，麻烦把这个主项目也点一下呀，多谢多谢：）

**Comment by zhaoyaogit** [comment]
> 

OK!!!
最近在看workflow和srpc代码呢。学习下。

**Comment by Barenboim** [comment]
嗯嗯，有任何问题随时发issue或群里交流！

**Comment by CBookShu** [comment]
windows分支的server测试代码，用的IPV6启动的服务器，client在连接的时候，会连不上的。把代码：server.start(AF_INET6, port) 注释掉，留下server.start(AF_INET, port) 就可以连上了。

**Comment by CBookShu** [comment]
windows分支的server测试代码，client在连接的时候，的确会连不上的。
把代码：server.start(AF_INET6, port) 注释掉，留下server.start(AF_INET, port) 就可以连上了。如下：
       WFTutorialServer server(&params, process);
	if (/*server.start(AF_INET6, port) == 0 ||*/
		server.start(AF_INET, port) == 0)
	{
		getchar();
		server.stop();
	}
	else
	{
		perror("server.start");
		exit(1);
	}
