### ISSUE TITLE
Kafka client "死循环"

### ISSUE THREAD

**Issue by redkongdong** [sogou/workflow#811]
topic 空的，如果返回是offset out of range, 就一直retry. 现象就像client hang住，client 定义的 kafka_callback一直得不到调用

看起来像是这个改动引起的
kafka: fix out of range error for fetch #678

**Comment by wzl12356** [comment]
topic为空指的是里面没有数据是吗？

**Comment by redkongdong** [comment]
> topic为空指的是里面没有数据是吗？

是的，没有数据.

**Comment by wzl12356** [comment]
#813

**Comment by redkongdong** [comment]
Cool, thx @wzl12356

**Comment by Barenboim** [comment]
@redkongdong 感谢报告问题！也帮我们试试看。

**Comment by redkongdong** [comment]
> @redkongdong 感谢报告问题！也帮我们试试看。

Sure, seems the topic has been written today since it is shared test environment, will try once it is cleaned tomorrow and let you know.

**Comment by Barenboim** [comment]
> > @redkongdong 感谢报告问题！也帮我们试试看。
> 
> Sure, seems the topic has been written today since it is shared test environment, will try once it is cleaned tomorrow and let you know.

Thanks. Take your time.

**Comment by redkongdong** [comment]
It works for me. Thx.

**Comment by redkongdong** [comment]
It works for me. Thx.
