### ISSUE TITLE
关于workflow 串行和并行的疑惑

### ISSUE THREAD

**Issue by lkkey80** [sogou/workflow#816]
顺序加入到同一个series的不同task是按照加入顺序串行执行的吗？
如果是串行执行的，是在同一个线程中串行执行吗？
特别地，顺序加入到同一个series的多个go task也是串行执行的吗？

**Comment by Barenboim** [comment]
1、同一个series里的任务，肯定是严格串行执行啊。加入可以push_front或push_back，但一般用户都是调push_back。所以可以认为执行顺序与你加入的顺序一致。
2、不在同一个线程里执行。通信有处理线程，计算有计算线程。就算是同一种任务，也不会是同一个线程中执行。
3、看第一条。

**Comment by littledoglily** [comment]
使用parallelwork并行请求下游，发送请求的过程是在不同线程发送的吗？目前按照自己对代码的理解 好像发送的过程是串行的？但是回调因为收包->msg_queue -> handle thread这个过程 会在不同的处理线程并行执行

**Comment by Barenboim** [comment]
如果可以同步发送完，就是在一个线程里发的。不会在这个时候去启动多个线程发数据。







---原始邮件---
发件人: "Charles ***@***.***&gt;
发送时间: 2022年3月25日(周五) 晚上9:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 关于workflow 串行和并行的疑惑 (Issue #816)




 
使用parallelwork并行请求下游，发送请求的过程是在不同线程发送的吗？目前按照自己对代码的理解 好像发送的过程是串行的？但是回调因为收包-&gt;msg_queue -&gt; handle thread这个过程 会在不同的处理线程并行执行

**Comment by littledoglily** [comment]
> 

会有情况下真正在多个IO线程并行发送吗？ 因为parallelTask::dispatch就是串行调用subtask的dispatch的

**Comment by Barenboim** [comment]
send buffer放不下数据，启动异步发送，这个时候可能会多线程并发发送。

**Comment by littledoglily** [comment]
> send buffer放不下数据，启动异步发送，这个时候可能会多线程并发发送。
想确认一下 如果我用parallework add 2个serieswork， 每个serieswork中有个一个add task， 那2个add task也是串行调用的吗？

**Comment by Barenboim** [comment]
add task是计算任务吧？计算任务要切线程的，是并行。
