### ISSUE TITLE
create_graph_node 创建顺序变一下为什么结果就不对了？ 

### ISSUE THREAD

**Issue by icefoxhz** [sogou/workflow#817]
以下运行结果正确：

WFGoTask *go_task1 = WFTaskFactory::create_go_task("task1", task1, 3);
WFGoTask *go_task2 = WFTaskFactory::create_go_task("task2", task2, 4);
WFGoTask *go_task3 = WFTaskFactory::create_go_task("task3", task3, 8);
WFGoTask *go_task4 = WFTaskFactory::create_go_task("task4", task4, 4);
WFGoTask *go_task5 = WFTaskFactory::create_go_task("task5", task5, 44);
WFGoTask *go_task6 = WFTaskFactory::create_go_task("task6", task6, 6);

WFGraphNode *g1 = &graph->create_graph_node(go_task1);
WFGraphNode *g2 = &graph->create_graph_node(go_task2);
WFGraphNode *g3 = &graph->create_graph_node(go_task3);
WFGraphNode *g4 = &graph->create_graph_node(go_task4);
WFGraphNode *g5 = &graph->create_graph_node(go_task5);
WFGraphNode *g6 = &graph->create_graph_node(go_task6);

------------------------------------------------------------------------------------------------

如果换下 create_graph_node 的顺序，结果就不对了~~

WFGoTask *go_task1 = WFTaskFactory::create_go_task("task1", task1, 3);
WFGoTask *go_task2 = WFTaskFactory::create_go_task("task2", task2, 4);
WFGoTask *go_task3 = WFTaskFactory::create_go_task("task3", task3, 8);
WFGoTask *go_task4 = WFTaskFactory::create_go_task("task4", task4, 4);
WFGoTask *go_task5 = WFTaskFactory::create_go_task("task5", task5, 44);
WFGoTask *go_task6 = WFTaskFactory::create_go_task("task6", task6, 6);

WFGraphNode *g6 = &graph->create_graph_node(go_task6);
WFGraphNode *g5 = &graph->create_graph_node(go_task5);
WFGraphNode *g4 = &graph->create_graph_node(go_task4);
WFGraphNode *g3 = &graph->create_graph_node(go_task3);
WFGraphNode *g2 = &graph->create_graph_node(go_task2);
WFGraphNode *g1 = &graph->create_graph_node(go_task1);

**Comment by icefoxhz** [comment]
完整测试代码：


#ifndef WORKFLOWTEST_SRC_GRAPHTEST_H_
#define WORKFLOWTEST_SRC_GRAPHTEST_H_

#include <csignal>
#include "workflow/WFFacilities.h"
#include "workflow/WFTaskFactory.h"
#include "iostream"
#include "string"
#include <set>
#include <nlohmann/json.hpp>

using namespace nlohmann;
using namespace std;

/*
                               3

         3 + 4 = 7                                 3 * 8 = 24

7 + 4=11                 44/2 + 7= 29

                      11 +29 + 24 + 6  = 70

 */

using namespace protocol;

using name2graphMap = map<string, const WFGraphNode *>;

int result_task1 = 0;
int result_task2 = 0;
int result_task3 = 0;
int result_task4 = 0;
int result_task5 = 0;
int result_task6 = 0;

void task1(int i) {
    result_task1 = i;
}

void task2(int i) {
    result_task2 = result_task1 + i;
}

void task3(int i) {
    result_task3 = result_task1 * i;
}

void task4(int i) {
    result_task4 = result_task2 + i;
}

void task5(int i) {
    result_task5 = i / 2 + result_task2;
}

void task6(int i) {
    result_task6 = result_task4 + result_task5 + result_task3 + i;
}

void testGraphTask() {
    string workflowJson =
        "{\"name\":\"t1\",\"next\":[{\"name\":\"t2\",\"next\":[{\"name\":\"t4\",\"next\":[{\"name\":\"t6\",\"next\":[]}]},{\"name\":\"t5\",\"next\":[{\"name\":\"t6\",\"next\":[]}]}]},{\"name\":\"t3\",\"next\":[{\"name\":\"t6\",\"next\":[]}]}]}";

    string workParam = "{\"t1\":{\"param\":3,\"op\":\"operator1\"},\"t2\":{\"param\":4,\"op\":\"operator2\"},\"t3\":{\"param\":8,\"op\":\"operator3\"},\"t4\":{\"param\":4,\"op\":\"operator4\"},\"t5\":{\"param\":44,\"op\":\"operator5\"},\"t6\":{\"param\":6,\"op\":\"operator6\"}}";

    WFFacilities::WaitGroup wait_group(1);

    /* Create a graph. Graph is also a kind of task */
    WFGraphTask *graph = WFTaskFactory::create_graph_task([&](WFGraphTask *) {
      cout << ">>>>>>>>>>>>  任务结束  <<<<<<<<<<<<<" << endl;
      cout << result_task6 << endl;
      wait_group.done();
    });

    //  一定要先创建完任务， 才能加入到图节点~  不然结果就不对了
    WFGoTask *go_task1 = WFTaskFactory::create_go_task("task1", task1, 3);
    WFGoTask *go_task2 = WFTaskFactory::create_go_task("task2", task2, 4);
    WFGoTask *go_task3 = WFTaskFactory::create_go_task("task3", task3, 8);
    WFGoTask *go_task4 = WFTaskFactory::create_go_task("task4", task4, 4);
    WFGoTask *go_task5 = WFTaskFactory::create_go_task("task5", task5, 44);
    WFGoTask *go_task6 = WFTaskFactory::create_go_task("task6", task6, 6);

    WFGraphNode *g1 = &graph->create_graph_node(go_task1);
    WFGraphNode *g2 = &graph->create_graph_node(go_task2);
    WFGraphNode *g3 = &graph->create_graph_node(go_task3);
    WFGraphNode *g4 = &graph->create_graph_node(go_task4);
    WFGraphNode *g5 = &graph->create_graph_node(go_task5);
    WFGraphNode *g6 = &graph->create_graph_node(go_task6);

    name2graphMap taskFuncMapper;
    taskFuncMapper.emplace("t4", g4);
    taskFuncMapper.emplace("t5", g5);
    taskFuncMapper.emplace("t6", g6);
    taskFuncMapper.emplace("t1", g1);
    taskFuncMapper.emplace("t2", g2);
    taskFuncMapper.emplace("t3", g3);

    g1 --> g2;
    g1 --> g3;
    g2 --> g4;
    g2 --> g5;
    g3 --> g6;
    g4 --> g6;
    g5 --> g6;

    graph->start();
    wait_group.wait();
}

#endif //WORKFLOWTEST_SRC_GRAPHTEST_H_

**Comment by icefoxhz** [comment]
![image](https://user-images.githubusercontent.com/35057092/159881640-13eb978d-57e5-4582-8df8-e214b8cf685b.png)

这个流程~~

**Comment by Barenboim** [comment]
为什么你写成：
~~~cpp
WFGraphNode *g1 = &graph->create_graph_node(go_task1);
~~~
而不是：
~~~cpp
WFGraphNode& g1 = graph->create_graph_node(go_task1);
~~~
只有引用才可以进行运算符重载。

**Comment by icefoxhz** [comment]
好的~  确实~  谢谢
