### ISSUE TITLE
HTTP客户端的回调中收到错误11

### ISSUE THREAD

**Issue by song-git** [sogou/workflow#818]
我的程序是一个HTTP转发器，当我建立大量的HTTP客户端任务时，我在回调中收到了state=1,error=11 (EAGAIN,Resource temporarily unavailable）的错误， 请问这种情况下是应该重新创建客户端任务吗？

**Comment by Barenboim** [comment]
这个是因为client对某个server的连接数，超过client配置的对单个目标的最大连接数了。这个值默认为200 。
修改方法：
~~~cpp
#include "workflow/WFGlobal.h"

int main()
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 1000;
    WORKFLOW_library_init(&settings);
    ...
}
~~~
另外，可以使用WFResourcePool更好的实现对外连接数控制。

**Comment by song-git** [comment]
非常感谢楼上的回答，目前使用上面的代码解决了问题，感谢分享的方法，正在研究。
