### ISSUE TITLE
图像识别服务器

### ISSUE THREAD

**Issue by deep-practice** [sogou/workflow#822]
场景：使用workflow来做图像识别服务器，每一次请求过来调用相应的模型或者模型组合进行计算。
问题：workflow的task在调用完毕就销毁，但计算过程使用的GPU资源希望第一次分配后就一直保留，不要每来个请求就去重新分配资源初始化等等，用workflow怎么实现好一点呢

**Comment by Barenboim** [comment]
这个不矛盾吧。task销毁其实只销毁了request和response。全局资源管理完全是在用户自己手里。

**Comment by deep-practice** [comment]
加载模型和推理要在一个线程上才能推理成功，而加载模型只希望进行一次，这种情况怎么处理呢

**Comment by Barenboim** [comment]
推理是在我们的计算线程上执行的吗？如果是多线程推理，按照你的描述应该也是多个线程都需要加载吧？
用thread local试一下。

**Comment by MaybeShewill-CV** [comment]
@deep-practice 可以试试在workflow的task启动之前 初始化好全局detector，然后workflow里的计算线程都使用这个全局detector，这样就可以避免频繁的GPU资源申请。

**Comment by deep-practice** [comment]
谢谢大家的解答 我试试 主要是之前我初始化engine和推理没在一个线程的时候 tensorrt就不能进行推理

**Comment by hanhaonwu** [comment]
> 谢谢大家的解答 我试试 主要是之前我初始化engine和推理没在一个线程的时候 tensorrt就不能进行推理

想问下后续怎么解决的啊？

**Comment by Barenboim** [comment]
你那边有遇到什么问题可以重新开个issue描述一下。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 凌晨1:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [sogou/workflow] 图像识别服务器 (Issue #822)




  
谢谢大家的解答 我试试 主要是之前我初始化engine和推理没在一个线程的时候 tensorrt就不能进行推理
  
想问下后续怎么解决的啊？

**Comment by xyx361100238** [comment]
如果我需要实现语音识别引擎这样的流式长连接请求/返回，可以使用workflow框架吗？

**Comment by Barenboim** [comment]
> 如果我需要实现语音识别引擎这样的流式长连接请求/返回，可以使用workflow框架吗？

全双工的我们支持得不好，有用户在魔改。
我们底层的poller模块是全双工的，用这个可以实现任何网络上的需求。你也可以直接用这个模块写程序。

**Comment by xyx361100238** [comment]
多谢！
