### ISSUE TITLE
workflow里面有使用tcp传输大块数据的例子吗

### ISSUE THREAD

**Issue by lkkey80** [sogou/workflow#823]
如题，就是直接使用TCP发送和接收一些二进制大块数据

**Comment by Barenboim** [comment]
一切都是基于消息的。一般用法里，只有消息的序列化反序列化，不会直接调用send或receive。

**Comment by lkkey80** [comment]
是不是可以通过自定义协议，达到使用tcp收发数据的目的？如果是这样的话，使用workflow持续收发大量的数据，比如用于传输大量的流媒体数据，workflow适合这种场景吗？

**Comment by lkkey80** [comment]
@Barenboim

**Comment by Barenboim** [comment]
流媒体确实不是我们的强项。有几个issue问到过流媒体server，你可以看看：https://github.com/sogou/workflow/issues/758

**Comment by lkkey80** [comment]
那workflow支持tcp长连接吗

**Comment by Barenboim** [comment]
你指的长连接是什么？关于连接的保持，我们有很多文档说明。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月26日(周六) 晚上9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow里面有使用tcp传输大块数据的例子吗 (Issue #823)




 
那workflow支持tcp长连接吗

**Comment by lkkey80** [comment]
能贴几个连接保持的文档链接吗

**Comment by Barenboim** [comment]
你自己翻一下文档吧。比较散落。

**Comment by Barenboim** [comment]
或者你描述清楚，你要实现什么功能。

**Comment by lkkey80** [comment]
需要实现这样一个功能：
1，支持TCP长连接；
2，实现客户端和服务端；
3，客户端以大概1GB/s的速度持续向服务端走TCP发送数据。

**Comment by lkkey80** [comment]
场景就是用来做分布式存储

**Comment by Barenboim** [comment]
长连接一直支持。你看看自定义协议的文档吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月26日(周六) 晚上9:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] workflow里面有使用tcp传输大块数据的例子吗 (Issue #823)




 
场景就是用来做分布式存储

**Comment by lkkey80** [comment]
通过自定义协议，也就是定义一个简单的header，然后后面跟上业务数据，每次大概发送1~2MB数据，持续调用接口发送，对于”客户端以大概1GB/s的速度持续向服务端走TCP发送数据“这个需求，workflow是否擅长呢

**Comment by Barenboim** [comment]
> 需要实现这样一个功能： 1，支持TCP长连接； 2，实现客户端和服务端； 3，客户端以大概1GB/s的速度持续向服务端走TCP发送数据。

Client发送请求前，数据需要在内存里。你这个场景，用我们的框架实现可能不太好。不过，我建议不要连续发那么多数据，最好转成多次的小一些的请求。

**Comment by lkkey80** [comment]
数据发送前会都在内存生成好，是多次小的发送，每次1~2MB左右

**Comment by lkkey80** [comment]
server端也是每次收到1~2MB就写入磁盘，只是client <--> server整体吞吐量能到1GB/s就可以了

**Comment by Barenboim** [comment]
> server端也是每次收到1~2MB就写入磁盘，只是client <--> server整体吞吐量能到1GB/s就可以了

吞吐量1G不是什么问题😓串行不够，还可以并发不是吗？
