### ISSUE TITLE
关于workflow自定义协议中接收socket数据buffer问题

### ISSUE THREAD

**Issue by lkkey80** [sogou/workflow#825]
class ProtocolMessage : public CommMessageOut, public CommMessageIn
{
private:
    virtual int encode(struct iovec vectors[], int max);

    /* You have to implement one of the 'append' functions, and the first one
     * with arguement 'size_t *size' is recommmended. */
    virtual int append(const void *buf, size_t *size);
    virtual int append(const void *buf, size_t size);

    ...
};
workflow自定义协议反序列化函数append被调用时，socket的数据已经被workflow read到内存里了，这块内存是workflow内部自己
申请的吧，那是否支持使将socket数据直接读取到用户自己申请的内存空间呢，这样可以减少一次将socket数据从workflow内存拷贝到用户自己内存的开销？

**Comment by Barenboim** [comment]
Sorry，我们不支持直接读到用户buffer。这是个很好的问题。如果要支持你说的这个功能，接口设计上会比目前复杂很多，用户的代码也会变复杂。实际测试中，我们认为这一次内存复制不会影响多少性能。

**Comment by lkkey80** [comment]
对于普通的rpc/http请求应当问题不大，如果每秒1~2GB的网络数据交互，或许不是非常高效。

**Comment by Barenboim** [comment]
如果担心这块的问题，你可以试试改一点代码。我暂时想不到特别简洁的方法。
