### ISSUE TITLE
线程间通信

### ISSUE THREAD

**Issue by jiephe** [sogou/workflow#827]
hello  我们项目现在用的QT QT一个很好的机制就是线程间的通信，一个线程发个signal，另一个线程就会执行相应的slot函数了，同时还附带了数据。想问下我们这个项目，支持这样的线程间通信吗？因为qt的线程之间的数据交换是天然支持的。我们现在不想用qt了，我想能不能以workflow为基础替换掉

**Comment by Barenboim** [comment]
好像有人问这个问题。你看一看我们的MailboxTask可不可以解决这个问题。
在WFTaskFactory.h里：
~~~cpp
class WFTaskFactory
{
public:
    static WFMailboxTask *create_mailbox_task(size_t size, mailbox_callback_t callback);

    /* Use 'user_data' as mailbox. Store only one message. */
    static WFMailboxTask *create_mailbox_task(mailbox_callback_t callback);
};
~~~
Mailbox是一种任务，当一个mailbox投递的消息达到预定的size，callback会被调用。
WFMailboxTask的接口如下：
~~~cpp
class WFMailboxTask : public WFGenericTask
{
public:
    // 投递一条消息
    void send(void *msg);
    // 得到mailbox地址以及当前的消息数。在callback里使用，n返回值必然等于size。
    void **get_mailbox(size_t *n);
};
~~~
其实，mailbox就是在counter的基础上加上了msg。功能和counter差不多。你也可以看看counter的文档：
https://github.com/sogou/workflow/blob/master/docs/about-counter.md

**Comment by Barenboim** [comment]
当然，我们没有线程等待的概念。当Mailbox最后一条消息被投递，callback直接调用，而不是切回启动任务的线程。

**Comment by wasphin** [comment]
Qt 有自己事件处理机制, 模型应该和 workflow 差别不小, 不做些改动恐怕是不行的.

**Comment by Barenboim** [comment]
@jiephe

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/issues/750
做出来了。大家看看是不是想要的。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/923/files
