### ISSUE TITLE
websocket分支增加windows支持要做哪些工作?

### ISSUE THREAD

**Issue by yfz0574** [sogou/workflow#831]
咨询了1412回复说websocket不只是需要协议,还需要改通信器,而WIN下面跟LINUX的通信器不一样,要修改通信器可能挺麻烦,能否出个教程讲述下大体思路流程和注意点?真的想用这个框架.

**Comment by Barenboim** [comment]
搞不定。。。win的核心不一样，我不太会弄。因为webSocket在communicator里加了几个接口，iocp下完全不一样。这个我真没办法。没有全职Windows开发😓
