### ISSUE TITLE
乌龙，乌龙的背后又是一个设计的思考，6666------------wf架构上有个bug，一个fd的r，w两种类型的事件没发同时添加到epoll中，会导致全双工的链接无法正常工作

### ISSUE THREAD

**Issue by gnblao** [sogou/workflow#832]
wf架构上有个bug，一个fd的r，w两种类型的事件没法同时添加到epoll中，会导致全双工的链接无法正常工作。
现在代码中，在添加w关注的时候，会把r给清零了

**Comment by gnblao** [comment]
Communicator::handle_write_result   拉回来了

**Comment by Barenboim** [comment]
哈哈。这都被你发现了。我们的做法是dup一下再放进去。poller模块可以实现任何功能的网络程序。

**Comment by Barenboim** [comment]
毕竟需要关注写事件的情况不多。因为我们一般会先进行同步写，同步写不能完成再异步写，所以需要dup的概率也不大。这样实际上真正全双工的。另外你也可以单开个poller专门给写用。

**Comment by Barenboim** [comment]
如果你问的是Communicator层，也是没有问题的。我们会原子性的把rd事件改成wr事件，然后在handle_write_result里，看情况(对于非keep_alive的server，直接关闭)再把rd事件加回去。
