### ISSUE TITLE
半双工和全双工通讯架构的一些思考---欢迎拍砖。。。。

### ISSUE THREAD

**Issue by gnblao** [sogou/workflow#833]
半双工和全双工通信
半双工：req->rsp->req->rsp->req->rsp
全双工：req->req->req->rsp->req->rsp->rsp->   或者是csjcjhbvvjbbdsb->rsp

目前对半双工的通用通讯架构比较多，对于全双工的基本上都是独立实现
半双工协议：http1.X   。。。。。
全双工协议：http2 webwosket quic 。。。。。

全双工协议有个特点在tcp/udp。。。之上为了复用链接，搞一个传输frame层。在frame之上堆stream和req之类的

So：
   想要一个支持通用的（half-duplex/full-duplex）架构，如何做比较好。我也没想好，我只想抛个砖。。。。。。。。。。最近看wf的代码学习（baipiao）了好多好东西～哈哈哈～

**Comment by holmes1412** [comment]
感谢小伙伴的热心关注呀，Workflow内部对于全双工的实现可以看看[Websocket分支](https://github.com/sogou/workflow/tree/websocket)，通信器的模式有点不同。

虽然对于连接来说不能混用不同的模式，但是对于Workflow的使用者来说，可以同时使用一来一回模式（比如Http 1.X）和全双工模式（比如Websocket），并且在任务流层面是无缝衔接的。由于实际使用上几乎没有同时需要在一个场景内高并发使用两者的需求，所以在使用全双工比较多的情况下，要把poller_threads数量改大点会更好。

传统的事件循环模式应该是比较容易同时支持两种模式吧？只不过代码写起来比较麻烦。我也坐等一个更漂亮的方案～
