### ISSUE TITLE
mysql转义的问题

### ISSUE THREAD

**Issue by lsm19870508** [sogou/workflow#836]
Hi,我在使用Mysql的set_query()方法时，同样发现插入字符串未经过转义的问题

我已翻阅过 https://github.com/sogou/workflow/issues/537 的回答，了解workflow并未提供转义的方法，所以我打算使用mysql自带的mysql_escape_string来进行字符串处理，然而当我这么做的时候，我遇到了大量宏重复定义的问题（mysql_types.h中的枚举宏），不得已，我只能将mysql_types.h中的变量全部加了WF_

现在我想问的是，能否提供个类似mysql_escape_string的方法，或者有没有一种更优雅的方式，来进行字符串的转义。

**Comment by Barenboim** [comment]
你好。关于enum的符号和MySQL官方client冲突的问题，我们之前为了不改变用户使用情况，直接用了和mysql官方名字一样的enum符号。但为了避免用户在 workflow框架里使用官方mysql client出现冲突，只要不include "workflow/MySQLResult.h"，这些标号不会暴露。这么做，相当于让用户在workflow的mysql client和官方mysql client里只能二选一。一般情况下也不会有什么问题。
但如果你要引入官方的工具链，这个问题可能就会暴露出来了。所以，我想到的解决方案是我们自建mysql client工具链，避免用户需要去引用官方mysql client。你可以把你需要的一些工具罗列一下，我们加一个MySQLUtil模块进来。

**Comment by lsm19870508** [comment]
感谢如此快的回复。
就目前看来，我这边的需求，主要就是mysql自带的mysql_escape_string或mysql_real_escape_string方法，因为这会是非常常见的需求，而自己实现，主要担心效率和功能上会存在问题。
谢谢~~

**Comment by Barenboim** [comment]
好像escape_string好像就是转这几个字符吧：
~~~c
switch (*from) {
        case 0: /* Must be escaped for 'mysql' */
          escape = '0';
          break;
        case '\n': /* Must be escaped for logs */
          escape = 'n';
          break;
        case '\r':
          escape = 'r';
          break;
        case '\\':
          escape = '\\';
          break;
        case '\'':
          escape = '\'';
          break;
        case '"': /* Better safe than sorry */
          escape = '"';
          break;
        case '\032': /* This gives problems on Win32 */
          escape = 'Z';
          break;
      }
~~~
把这几个变成"\x"这个形式就可以了。而且不用考虑什么charset_info。
real_escape是有charset_info的意思？

**Comment by Barenboim** [comment]
我这个是从mysql源代码里看的，好像默认就转这几个。

**Comment by lsm19870508** [comment]
那应该就没问题了，另外赞下你这边的效率{大拇指~！}

**Comment by Barenboim** [comment]
还有一个应该是：mysql_real_escape_string_quote，只转义引号里的内容。mysql已经废弃了mysql_real_escape_string函数，建议只使用带_quote的。我也尽快加一下。

**Comment by lsm19870508** [comment]
我这边之前的数据测试后是没问题的~~感谢~~

**Comment by Barenboim** [comment]
加上了MySQLUtil::escape_string_quote。不过感觉这个函数好像没有什么用，就是将一个引号变成两个引号。
