### ISSUE TITLE
workflow的http协议支持Content-Type: multipart/form-data类型的post吗

### ISSUE THREAD

**Issue by Dreamerzp** [sogou/workflow#843]

**Comment by Dreamerzp** [comment]
摸索了下http multipart上传文件，可以直接使用https://github.com/AndsonYe/MultipartEncoder.git这部分代码，跟workflow很好的结合起来
//某个json作为表单数据
json j;
j["downLoadFileName"] = "1.jpg";
std::string req_str = j.dump();

MultipartParser parser;
//表单数据1
parser.AddParameter("username", "hello");
//表单数据2
parser.AddParameter("password", "world");
//表单数据3
parser.AddParameter("json", req_str);
//上传的图片文件
parser.AddFile("multipartFile", "1.jpg");
//得到boundary和body
std::string boundary = parser.boundary();
std::string body = parser.GenBodyContent();
// std::cout << body << std::endl;

WFHttpTask *task;
//拟用于上传数据的url，例如某个oss地址
std::string url = "https://oss.xxxxxx.com/oss/xxxxxx";
//callback 自己定义，与workflow的tutorial-01-wget.cc中差不多
task = WFTaskFactory::create_http_task(url, REDIRECT_MAX, RETRY_MAX,
										   callback);
protocol::HttpRequest *req = task->get_req();
req->add_header_pair("Accept", "*/*");
req->add_header_pair("User-Agent", "Wget/1.14 (linux-gnu)");
req->add_header_pair("Connection", "close");
//设置Content-Type
req->add_header_pair("Content-Type", "multipart/form-data; boundary=" + boundary);
req->set_method("POST");
req->append_output_body(body);
task->start();

**Comment by mayunxi** [comment]
非常感谢提供post的示例，找了好久
