### ISSUE TITLE
异步问题咨询

### ISSUE THREAD

**Issue by 2205430768** [sogou/workflow#846]
workflow的图式调度框架 a->b   a->c    c->d   b->d       如果a节点执行完，b和c都是网络请求，b和c的网络请求是并行发送的吗？还是串行发送？

**Comment by Barenboim** [comment]
b，c两个任务，在一个线程内被串行dispatch。而在我们的模型里，为了加快网络请求的写速度，会先尝试同步write。如果tcp buf不能容纳整个request，才会进入异步写逻辑。所以，在这个case里，如果b，c的request可以被写入tcp buf，writev操作其实是在一个线程里串行执行的。但是对用户来讲，b和c逻辑上就是两个并发的网络请求。

**Comment by 2205430768** [comment]
b 和c串行 写     相比   b c都开启异步写    两者的性能差距大吗？

**Comment by Barenboim** [comment]
那肯定是串行写快。你可以直接删去这里三行代码：
https://github.com/sogou/workflow/blob/404c7313514cf8268ebef26cbaa98df68bec485e/src/kernel/Communicator.cc#L583
那么就没有同步写了，完全异步。这么做的话，在大多数的场景应该会慢很多。

**Comment by Barenboim** [comment]
@2205430768
