### ISSUE TITLE
Kafka fetch KafkaRecord 无效key, value ptr

### ISSUE THREAD

**Issue by redkongdong** [sogou/workflow#848]
Fetch 读取key或value(struct kafka_record_t)指针是无效的的地址(!=NULL)，offset, partition 对应是实际存在的, 不知道有没有遇到过?还在debug

**Comment by Barenboim** [comment]
@wzl12356

**Comment by redkongdong** [comment]
两次运行kafka_record_t的结果，key, value指针地址都没有变

{key = 0x7eff2cb7c0bc, key_len = 24, key_is_move = 1, value = 0x7eff2cb7c0d6, value_len = 667, value_is_move = 1, timestamp = 1649757868354, offset = 445343423, header_list = {next = 0x7eff04000b50, prev = 0x7eff04000b50}, status = -1, toppar = 0x7eff28004a40}

  {key = 0x7facee13a0bc, key_len = 24, key_is_move = 1, value = 0x7facee13a0d6, value_len = 667, value_is_move = 1, timestamp = 1649757868354, offset = 445343423, header_list = {next = 0x7facc0000b50, prev = 0x7facc0000b50}, status = -1, toppar = 0x7faca80049b0}

**Comment by redkongdong** [comment]
parse_record_batch 解析出来的key, value地址和fetch_records 出来的是一样的
parse_record_batch 里边还是有效的，应该是之后哪把内存给释放掉了

**Comment by redkongdong** [comment]
kafka_parser_deinit 把那个内存个free掉了

**Comment by Barenboim** [comment]
好改吗？要不发我们发个pr?

**Comment by redkongdong** [comment]
> 好改吗？要不发我们发个pr?

Kafka代码不熟悉:(  还不知道为什么在调动user callback前把KafakMessage msgbuf给release掉了.

**Comment by redkongdong** [comment]
@wzl12356

请教一下fetch finish_once 一直有has_next, 一直继续fetch, 直到最后finish调用user callback读取所有records
中间每次fetch的结果保存在哪了呢？还是只是记录了一下指针地址？？？每次进行下一次fetch 前buf都会清空吧

**Comment by redkongdong** [comment]
> 这个地方调用clear_resp是正确的，因为这个时候应该不会调用callback。 key和value的地址是在Response里面的，会在内部调用的kafka_move_task_callback时候move到result里面的。 出现这个问题的原因容我再想想。

get_mutable_ctx 调用kafka_move_task_callback, clear_resp后直接return出去了？


			this->clear_resp();
			return false;
		}

		if (!is_user_request_)
		{
			is_user_request_ = true;
			delete this->get_message_out();
			this->get_resp()->clear_buf();
			return false;
		}

		if (this->get_resp()->get_api_type() == Kafka_Fetch ||
			this->get_resp()->get_api_type() == Kafka_Produce ||
			this->get_resp()->get_api_type() == Kafka_ApiVersions)
		{
			if (*get_mutable_ctx())
				(*get_mutable_ctx())(this);
		}

**Comment by wzl12356** [comment]
> > 这个地方调用clear_resp是正确的，因为这个时候应该不会调用callback。 key和value的地址是在Response里面的，会在内部调用的kafka_move_task_callback时候move到result里面的。 出现这个问题的原因容我再想想。
> 
> get_mutable_ctx 调用kafka_move_task_callback, clear_resp后直接return出去了？
> 
> ```
> 		this->clear_resp();
> 		return false;
> 	}
> 
> 	if (!is_user_request_)
> 	{
> 		is_user_request_ = true;
> 		delete this->get_message_out();
> 		this->get_resp()->clear_buf();
> 		return false;
> 	}
> 
> 	if (this->get_resp()->get_api_type() == Kafka_Fetch ||
> 		this->get_resp()->get_api_type() == Kafka_Produce ||
> 		this->get_resp()->get_api_type() == Kafka_ApiVersions)
> 	{
> 		if (*get_mutable_ctx())
> 			(*get_mutable_ctx())(this);
> 	}
> ```

clear_resp后面return false，会再次调度这个task的。

**Comment by redkongdong** [comment]
> 

再次调度应该是继续fetch新的结果吧？那当前这个结果是保存在哪呢？

**Comment by wzl12356** [comment]
> > 
> 
> 再次调度应该是继续fetch新的结果吧？那当前这个结果是保存在哪呢？

当前任务没有结束，所以不会把这个结果返回给用户，因为也就不会执行用户的callback

**Comment by redkongdong** [comment]
目前看起来是this->get_resp()->get_api_type() == Kafka_Fetch 调用到 clear_resp 会有问题

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/852/files
可以试试这次大改的结果。

**Comment by redkongdong** [comment]
> #852 可以试试这次大改的结果。

好的

**Comment by redkongdong** [comment]
Doesn't work :(

**Comment by redkongdong** [comment]
> #852 可以试试这次大改的结果。

这个mgs正常读取会有问题, 我看offset偏倚了一些导致decode失败，原版没有问题

**Comment by wzl12356** [comment]
是说相同的offset，旧版可以解析，新版解析失败吗？

**Comment by redkongdong** [comment]
> 是说相同的offset，旧版可以解析，新版解析失败吗？

是的，我的是MySQL binlog的msg, 需要protobuf decode. 我比较看是新版起始多出来一些bytes导致decode失败

**Comment by wzl12356** [comment]
解析消息逻辑本次并没有修改，怀疑是和处理某些消息的时候有问题。
你的kafka版本是什么？
能提供一下出问题的数据吗？

**Comment by redkongdong** [comment]
> 解析消息逻辑本次并没有修改，怀疑是和处理某些消息的时候有问题。 你的kafka版本是什么？ 能提供一下出问题的数据吗？

是指workflow的？
0.9.11  + https://github.com/sogou/workflow/pull/852
我只消费数据，producer是从binlog通过写到kafka里边的

我找找数据，测试环境定期给删了

**Comment by wzl12356** [comment]
kafka broker的版本

**Comment by redkongdong** [comment]
> 

2.11-0.11.0.2

**Comment by wzl12356** [comment]
版本还不一样吗？

**Comment by redkongdong** [comment]
> 版本还不一样吗？

什么意思？ Workflow的版本有要求吗？

**Comment by wzl12356** [comment]
#858

**Comment by redkongdong** [comment]
> #858

Thx.
