### ISSUE TITLE
工作流执行问题

### ISSUE THREAD

**Issue by HzjFirst** [sogou/workflow#849]
SeriesWork按照node1->node2->node3执行的任务执行，当执行完成后判断是否满足条件，如果不满足条件再次执行node1->node2->node3,这样可以吗？WF如果完成这样的工作，有没有什么好的思路？

**Comment by Barenboim** [comment]
这个属于某种循环的逻辑吧。目前来讲的话，只有单个的网络任务可以自我循环，不用重新create。一串任务，只能重新创建再push到series里了。

**Comment by Barenboim** [comment]
是的，每个任务在callback之后就没有了，内存自动释放。所以，三个任务都执行完成之后，series就清空了。如果不加入新任务，series的callback就被调用。

**Comment by HzjFirst** [comment]
嗯嗯，好的，谢谢，明白了
