### ISSUE TITLE
kafka集群中leader重启后问题

### ISSUE THREAD

**Issue by song-git** [sogou/workflow#853]
我在使用workflow作为kafka客户端消费消息时， 当集群中的一台重启后，kafka客户端回调报错 state 67 ，错误号 5006.
重启客户端进程回调也一直返回这个状态码。知道集群中的那台服务器启动完成后，才能恢复正常。
请问这种情况是客户端的问题吗？客户端应该如何正确的应对这种情况呢。

**Comment by Barenboim** [comment]
你可以先更新到最新代码再试一下。
@wzl12356

**Comment by wzl12356** [comment]
更新一下代码再试试吧

**Comment by song-git** [comment]
更新最新的代码后，会出现 Bad message, Connection refused, No such file or directory 等三种情况，但是进程退出重启后能基本恢复正常了。

**Comment by wzl12356** [comment]
是kafka broker重启吗？

**Comment by Barenboim** [comment]
@wzl12356 Bad Message这个错误可能需要关注一下。其他两个可以理解。

**Comment by wzl12356** [comment]
> @wzl12356 Bad Message这个错误可能需要关注一下。其他两个可以理解。

这个应该不是系统错误EBADMSG，应该是Kafka协议的错误KAFKA_FENCED_LEADER_EPOCH，代表broker不可用了

**Comment by song-git** [comment]
其他两种错误客户端看起来都可以正常继续运行， 但是 No such file or directory  对应状态码 state 67 好像就需要重新初始化客户端然后再创建任务了， 可以介绍一下这种情况下，如何不退出程序进行更合理的重启客户端吗？
我对kafka了解较少， 可能有说的不对的地方，希望得到指正。感谢。

**Comment by song-git** [comment]
> 是kafka broker重启吗？如果是broker重启的话，得看有没有对应的tp备份，如果没有备份，那确实是不可用的。

确实是broker重启了，我们在测试各种集群异常时，客户端模块的稳定性。看是否能保持正常工作。

**Comment by wzl12356** [comment]
> 其他两种错误客户端看起来都可以正常继续运行， 但是 No such file or directory 对应状态码 state 67 好像就需要重新初始化客户端然后再创建任务了， 可以介绍一下这种情况下，如何不退出程序进行更合理的重启客户端吗？ 我对kafka了解较少， 可能有说的不对的地方，希望得到指正。感谢。

我目前的逻辑是，在消费者组模式下，当broker不可用的时候，我会尝试重新获取meta信息，然后再可能会重新分配消费者（rebalance）。但是如果broker一直不可用，就会导致task一直失败。
其它客户端可以正常消费的数据吗？

**Comment by wzl12356** [comment]
还是说，fetch的过程中，如果broker发生重启，即使broker完成重启后，fetch也会失败，且只有重启客户端才可以正常fetch？

**Comment by wzl12356** [comment]
> 更新最新的代码后，会出现 Bad message, Connection refused, No such file or directory 等三种情况，但是进程退出重启后能基本恢复正常了。

这三个错误下，task的state都是1也就是WFT_STATE_SYS_ERROR吗？

**Comment by song-git** [comment]
不是 No such file or directory 对应的state是67.  最新的代码还有另外一个问题是，commit好像失效了， 会导致消息循环消费。

**Comment by wzl12356** [comment]
> 不是 No such file or directory 对应的state是67. 最新的代码还有另外一个问题是，commit好像失效了， 会导致消息循环消费。

是重复消费从某个offset消费吗？

**Comment by song-git** [comment]
> 


> > 不是 No such file or directory 对应的state是67. 最新的代码还有另外一个问题是，commit好像失效了， 会导致消息循环消费。
> 
> 是重复消费从某个offset消费吗？
是的， commit好像失效了，一直是同一个offset的消息在循环。

**Comment by wzl12356** [comment]
> > 
> 
> > > 不是 No such file or directory 对应的state是67. 最新的代码还有另外一个问题是，commit好像失效了， 会导致消息循环消费。
> > 
> > 
> > 是重复消费从某个offset消费吗？
> > 是的， commit好像失效了，一直是同一个offset的消息在循环。

是在多次callback里面得到了相同offset的records的？这些task的状态都是成功的吗？

**Comment by song-git** [comment]
> > > 
> > 
> > 
> > > > 不是 No such file or directory 对应的state是67. 最新的代码还有另外一个问题是，commit好像失效了， 会导致消息循环消费。
> > > 
> > > 
> > > 是重复消费从某个offset消费吗？
> > > 是的， commit好像失效了，一直是同一个offset的消息在循环。
> 
> 是在多次callback里面得到了相同offset的records的？这些task的状态都是成功的吗？

之前没注意到， 目前集群环境被拆掉了， 等我们环境重装后，我再验证一下这个问题。

**Comment by wzl12356** [comment]
已经更新了一个逻辑，就是把集群的broker地址列表改成meta返回的broker列表，有空可以再试试。
#868

**Comment by Barenboim** [comment]
@song-git 已经合并入主分支，可以再试一下
