### ISSUE TITLE
Kafka Client 如何安全退出

### ISSUE THREAD

**Issue by redkongdong** [sogou/workflow#855]
直接kill 会segment fault. 我看有个线程在访问kafka client member变量已经被删除了，需要的等待所有pending请求执行完才能退出吗？

Leave group done!!!
[Thread 0x7f0f1fc02700 (LWP 18516) exited]
[Thread 0x7f0f14bec700 (LWP 18538) exited]
[Thread 0x7f0ebffff700 (LWP 18539) exited]
[Thread 0x7f0f153ed700 (LWP 18537) exited]
[Thread 0x7f0f15bee700 (LWP 18536) exited]
[Thread 0x7f0f163ef700 (LWP 18535) exited]
[Thread 0x7f0f16bf0700 (LWP 18534) exited]
[Thread 0x7f0f173f1700 (LWP 18533) exited]
[Thread 0x7f0f17bf2700 (LWP 18532) exited]
[Thread 0x7f0f183f3700 (LWP 18531) exited]
[Thread 0x7f0f18bf4700 (LWP 18530) exited]
[Thread 0x7f0f193f5700 (LWP 18529) exited]
[Thread 0x7f0f19bf6700 (LWP 18528) exited]
[Thread 0x7f0f1a3f7700 (LWP 18527) exited]
[Thread 0x7f0f1abf8700 (LWP 18526) exited]
[Thread 0x7f0f1bbfa700 (LWP 18524) exited]
[Thread 0x7f0f1c3fb700 (LWP 18523) exited]
[Thread 0x7f0f1cbfc700 (LWP 18522) exited]
[Thread 0x7f0f1d3fd700 (LWP 18521) exited]
[Thread 0x7f0f1dbfe700 (LWP 18520) exited]
[Thread 0x7f0f1e3ff700 (LWP 18519) exited]
[Thread 0x7f0f1ec00700 (LWP 18518) exited]
[Thread 0x7f0f1f401700 (LWP 18517) exited]
[Thread 0x7f0f20403700 (LWP 18515) exited]

Thread 12 "taocdc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f0f1b3f9700 (LWP 18525)]
0x00007f0f24a085c4 in ComplexKafkaTask::set_meta_status (this=0x7f0f04001630, status=META_UNINIT)
    at WFKafkaClient.cc:824
824			(*this->client->member->meta_map)[meta->get_topic()] = status;
(gdb) p this->client->member
$1 = (KafkaMember *) 0x0
(gdb)

**Comment by wzl12356** [comment]
这个地方代码有bug，我修改一下

**Comment by wzl12356** [comment]
#868

**Comment by Barenboim** [comment]
已经merge。可以再试一下 @redkongkong

**Comment by redkongdong** [comment]
好的
