### ISSUE TITLE
Series对象的内存什么时候释放？

### ISSUE THREAD

**Issue by neobreaker** [sogou/workflow#856]
Tutorial 中程序结束， WaitGroup 里面计数器任务的 SerialWork 没有释放？怎么没有看到释放这部分内存的地方？

**Comment by neobreaker** [comment]
现在加上 “你好，请问一下：”   应该还来得及

**Comment by Barenboim** [comment]
> 现在加上 “你好，请问一下：” 应该还来得及

来得及来得及：）

**Comment by Barenboim** [comment]
你好，你那边说的中途结束是什么含义？是说不得task callback直接exit程序吗？这块可以看看“关于程序退出”那个文档：https://github.com/sogou/workflow/blob/master/docs/about-exit.md

**Comment by neobreaker** [comment]
你好，Tutorial  中 程序启动后创建WaitGroup 对象会分配CountTask 和 SerialWork 的内存对象，然后程序执行完成到 WaitGroup 的wait， 此时main线程阻塞等待。 用户输入Ctrl+C 程序执行到信号处理函数 CountTask 计数完成调用callack 写promise 然后释放CountTask 内存 ， main线程从wait唤醒 程序退出。  我的疑问是 之前分配的 SerialWork  内存对象在哪释放呢？

**Comment by Barenboim** [comment]
我们是有自动内存回收机制的啊。比如task，在callback之后就释放了，用户无需自己delete。series其实也一样，会在callback后自动释放，只有默认的情况下，这个callback为nullptr。具体释放的函数，应该在SeriesWork::pop里。
