### ISSUE TITLE
关于wf引入当做submodule的咨询

### ISSUE THREAD

**Issue by ChunelFeng** [sogou/workflow#861]
awsl ，我想通过wf的网络能力，给CGraph做个后台服务。
开了个新坑：https://github.com/CDevOrg/CGraph-NIO

但是当做submodule引入的时候，总是显示 kafka 的东东无法引入.
看图哈，我在 cmakelist.txt 中已经删除了，但是没啥用啊——我姿势不对？？？

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37905059/163723270-4e749bf2-9358-4800-afa8-57c80b2d302d.png">

参考了这里提供的例子：https://github.com/sogou/workflow/issues/589
没用起来啊。我tm是个没用的开发啊

有没啥好方法，可以帮忙排除那几个.cc文件哈，至少让我编译不报错。
或者可以直接引入仅包含网络功能的库

![image](https://user-images.githubusercontent.com/37905059/163723474-3f62b53c-b142-4112-883c-681b660b031e.png)

btw，有没有可能提供一个最少最小引入的 wf.h 文件，不要再受这种苦了。
不干了，我要睡觉了，下周再搞，呜呜呜呜。。。
求下周帮忙看看。。。

**Comment by holmes1412** [comment]
srpc里的做法，并不是在srpc项目的Cmake file里通过file去指定workflow里要的文件；而是先通过命令编译submodule中的workflow项目、再在srpc里find_package(workflow required config hints xxxxx)去找它。这样可以借助workflow本身的make命令默认不会编译kafka的特点而无需预装其他依赖。
具体流程：
编译命令make -> GNUMakefile 里先make -C workflow -> 再cmake srpc -> CMakeList.txt里find_package(workflow required config hints ../submodule/workflow)

**Comment by holmes1412** [comment]
实在不行，我真的要吹一波bazel，你参考下这个项目：https://github.com/sogou/workflow-polaris
共两个文件：
1、WORKSPACE
~~~
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
	name = "com_github_sogou_workflow",
	remote = "https://github.com/sogou/workflow.git",
	tag = "v0.9.11",
)
~~~
2、BUILD
~~~
cc_library(
        ...
	deps = [
		'@com_github_sogou_workflow//:http',  # 要哪个模块就用哪个模块
~~~
引入workflow就是这么丝滑

**Comment by ChunelFeng** [comment]
啊啊啊，我不会，但我愿意学。。。
你们为什么这么厉害。

我明天看看，如果第一种引入方法，能保证我在clion上每次都可以编译一下wf的改动的代码的话，
我更倾向于第一种。

别问为什么，问就是不会bazel。。。

**Comment by ChunelFeng** [comment]
> 首先感谢优秀的小伙伴引用workflow~~
> 
> srpc里的做法，并不是在srpc项目的Cmake file里通过file去指定workflow里要的文件；而是先通过命令编译submodule中的workflow项目、再在srpc里find_package(workflow required config hints xxxxx)去找它。这样可以借助workflow本身的make命令默认不会编译kafka的特点而无需预装其他依赖。
> 
> 具体流程： 编译命令make -> GNUMakefile 里先make -C workflow -> 再cmake srpc -> CMakeList.txt里find_package(workflow required config hints ../submodule/workflow)



哈哈哈，优秀谈不上。

如果有纳一点还不错的话，就是有品味——选择了wf吧，哈哈哈哈

**Comment by Barenboim** [comment]
模仿一下SRPC项目吧，利用workflow的CMake就没有问题。我们默认并不会编译kafka模块，因为这个模块有外部依赖。

**Comment by ChunelFeng** [comment]
done
