### ISSUE TITLE
死锁

### ISSUE THREAD

**Issue by ussturn** [sogou/workflow#862]
http服务和http请求都使用workflow 出现死锁， 是不是 http 服务和请求用的是同一个线程池

**Comment by Barenboim** [comment]
您好。之前我给你回复过几次issue，你都没有回音啊。这次如果解决了问题，请务必回复一下。

没错，所有的网络任务，都使用同一个线程池。所以，你不可以在网络任务的callback或process里，同步的等待另一个网络任务的结束。Server需要等待下游任务的话，应该把任务push_back到series里，请参考http-proxy示例。
如果一定要同步等待，可以用我们提供的WFFacilities::WaitGroup。用这个的话，就不会死锁了。不要用pthread的cond来实现唤醒。

**Comment by ussturn** [comment]
谢谢！ 我试试看
