### ISSUE TITLE
任务中途卡死了怎么办呢

### ISSUE THREAD

**Issue by guochaopeng** [sogou/workflow#877]
如果串联任务，其中的某一个任务卡死了，那后面的资源怎么释放

**Comment by jiaobendaye** [comment]
怎么通过一个timer强行停止一个正在运行的serial或者task呢？

**Comment by holmes1412** [comment]
@jiaobendaye 这个问题可以从几个点来回答：

1. timer task不是用来强行停止任何series或task，timer task是用来和其他task组装在一起，时间点到了它的callback会被调用，但不会停止已经执行的task；
2. 正在运行的task不能被强制停止，如果是网络任务，可以配合超时文档按需配置timeout： https://github.com/sogou/workflow/blob/master/docs/about-timeout.md
3. 正在运行的series可以通过cancel接口取消掉后面还没执行的任务，你可以在任务的callback里按需cancel当前的series；

相关issue可以看看：https://github.com/sogou/workflow/issues/422

**Comment by Barenboim** [comment]
@guochaopeng
