### ISSUE TITLE
The "single task queue" design of `thrdpool` results in heavy lock contention

### ISSUE THREAD

**Issue by Yriuns** [sogou/workflow#878]
A simple benchmark

follow the discussion on Zhihu: https://zhuanlan.zhihu.com/p/503733481

```cpp
#include "workflow/thrdpool.h"
#include <atomic>
#include <iostream>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

std::atomic<int64_t> global_count{0};

void trival_task(void *context) {
  ++global_count;
}

static inline int64_t GetUnixTimeUs() {
  struct timeval tp;
  gettimeofday(&tp, nullptr);
  return (((int64_t) tp.tv_sec) * 1000000 + (int64_t) tp.tv_usec);
}

int main() {
  const int nthreads = 16;
  int npools = 1; // <- replace it 16
  auto pools = new thrdpool_t*[npools];
  for (int i = 0; i < npools; ++i) {
    pools[i] = thrdpool_create(nthreads / npools, 0);
  }
  int64_t n = 10000000;
  auto t1 = GetUnixTimeUs();
  for (int64_t i = 0; i < n; ++i) {
    struct thrdpool_task task = {
      .routine    =    trival_task,
      .context    =    NULL,
    };
    thrdpool_schedule(&task, pools[i % npools]);
  }
  while (global_count != n) {
    usleep(10000);
  }
  auto t2 = GetUnixTimeUs();
  std::cout << (double)n / (t2 - t1) << std::endl;
  return 0;
}
```
In this test, we keep the total threads unchanged, i.e. 16, and change the `npools` so that we can use multiple task queue.
In a 40-cores server, `npools=16` can achieve around 40w/s throughput. However,`npools=1` only achieve 11w/s throughput.

**Comment by Barenboim** [comment]
Thank you for this test!
You are right, when the thread task is very light, the overhead of scheduling the task would be significant. This is why we do not suggest submitting a very light-weighted computing task.
May be we will improve our thead pool by using our message queue :)
https://github.com/sogou/workflow/blob/master/src/kernel/msgqueue.h
https://github.com/sogou/workflow/blob/master/src/kernel/msgqueue.c

**Comment by Barenboim** [comment]
I think this is a common problem of most thread pool implementations. Would you also run this test on other implementations? Like this repo: https://github.com/progschj/ThreadPool

**Comment by Yriuns** [comment]
> I think this is a common problem of most thread pool implementations. Would you also run this test on other implementations? Like this repo: https://github.com/progschj/ThreadPool

In our implementation, we introduce a lock-free queue for each worker, so that the lock-contention mainly happens on producer(pop can be lock-free, but push need to notify the worker thread, so it still need a lock). I can provide a test result later.

**Comment by Yriuns** [comment]
```cpp
#include "workflow/thrdpool.h"
#include "concurrentqueue.h" // https://github.com/cameron314/concurrentqueue/blob/master/concurrentqueue.h
#include <atomic>
#include <iostream>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <vector>
#include <condition_variable>
#include <mutex>

std::atomic<int64_t> global_count{0};

void trival_task(void *context) {
  ++global_count;
}

static inline int64_t GetUnixTimeUs() {
  struct timeval tp;
  gettimeofday(&tp, nullptr);
  return (((int64_t) tp.tv_sec) * 1000000 + (int64_t) tp.tv_usec);
}

class ThreadWorker {
public:
  void add_task(thrdpool_task *task) {
    queue_.enqueue(*task);
    if (going_to_sleep) {
      std::unique_lock<std::mutex> lock(mtx_);
      if (waiting_) {
        cond_.notify_one();
      } else {
        notified_ = true;
      }
    }
  }
  void run() {
    while (true) {
      thrdpool_task task;
      pop_task(task);
      task.routine(task.context);
    }
  }
private:
  void pop_task(thrdpool_task &task) {
    while (true) {
      if (queue_.try_dequeue(task)) {
        break;
      }
      going_to_sleep = true;
      if (queue_.try_dequeue(task)) {
        break;
      }
      std::unique_lock<std::mutex> lock(mtx_);
      if (notified_) {
        notified_ = false;
      } else {
        waiting_ = true;
        cond_.wait(lock);
        waiting_ = false;
      }
    }
    going_to_sleep = false;
  }
  moodycamel::ConcurrentQueue<thrdpool_task> queue_;
  std::mutex mtx_;
  std::condition_variable cond_;
  std::atomic<bool> waiting_{false};
  std::atomic<bool> going_to_sleep{false};
  bool notified_ = false;
};

class ThreadPool {
public:
  ThreadPool(int nthreads) : nthreads_(nthreads) {
    for (int i = 0; i < nthreads; ++i) {
      workers_.push_back(new ThreadWorker());
    }
    for (int i = 0; i < nthreads; ++i) {
      std::thread(&ThreadWorker::run, workers_[i]).detach();
    }
  }
  void thrdpool_schedule(thrdpool_task *task) {
    thread_local int next_id = 0;
    workers_[next_id]->add_task(task);
    next_id = (next_id + 1) % nthreads_;
  }
private:
  int nthreads_;
  std::vector<ThreadWorker *> workers_;
};

constexpr int64_t n = 10000000;

void workflow_producer(thrdpool_t *pool) {
  for (int64_t i = 0; i < n; ++i) {
    struct thrdpool_task task = {
      .routine    =    trival_task,
      .context    =    NULL,
    };
    thrdpool_schedule(&task, pool);
  }
}

void my_producer(ThreadPool *pool) {
  for (int64_t i = 0; i < n; ++i) {
    struct thrdpool_task task = {
      .routine    =    trival_task,
      .context    =    NULL,
    };
    pool->thrdpool_schedule(&task);
  }
}

void test_threadpool(bool is_workflow) {
  int nconsumers = 16;
  int nproducers = 4;
  ThreadPool my_pool(nconsumers);
  auto pool = thrdpool_create(nconsumers, 0);
  if (is_workflow) {
    for (int i = 0; i < nproducers; ++i) {
      std::thread(&workflow_producer, pool).detach();
    }
  } else {
    for (int i = 0; i < nproducers; ++i) {
      std::thread(&my_producer, &my_pool).detach();
    }
  }
  auto t1 = GetUnixTimeUs();
  while (global_count != n * nproducers) {
    usleep(10000);
  }
  auto t2 = GetUnixTimeUs();
  std::cout << t2 << " " << t1 << " " << (double)global_count.load() / (t2 - t1) << std::endl;
}

int main() {
    test_threadpool(true);
    // test_threadpool(false);
    return 0;
}
```

I write a toy version of our internal implementation, and change the test from single-producer/multi-consumer to multi-producer/multi-consumer. Here is the test result of 4-producers/16-consumers:
- workflow's thread pool: 20w/s
- `ThreadPool`: 398w/s

**Comment by Barenboim** [comment]
Thank you again for sharing the idea and the codes!
Actually, up to now, we does't use any lock-free technic in this project. Based on you test, the performance of lock-free queue is quite shocking.
We always use locks because in most scenarios, the performance of locking queue is good enough for our computing task, and a locking queue will always guarantee the order of tasks executing.
Of course, in some scenarios where we cannot predict the executions time of a computing task (may range from 1us to 1s), there would be a series performance decreasing in our thread pool. We will try to fix it.

**Comment by Yriuns** [comment]
> Thank you again for sharing the idea and the codes! Actually, up to now, we does't use any lock-free technic in this project. Based on you test, the performance of lock-free queue is quite shocking. We always use locks because in most scenarios, the performance of locking queue is good enough for our computing task, and a locking queue will always guarantee the order of tasks executing. Of course, in some scenarios where we cannot predict the executions time of a computing task (may range from 1us to 1s), there would be a series performance decreasing in our thread pool. We will try to fix it.

Agreed. The scheduling overhead is greatly affected by the task's property.

**Comment by Barenboim** [comment]
@Yriuns 
I'v refactored our thread pool by using our msgqueue in this PR. Could you make a test on this new implementation? 
https://github.com/sogou/workflow/pull/954/files
