### ISSUE TITLE
clang++可以编译，g++编译失败。我确定我的g++是支持c++11的。

### ISSUE THREAD

**Issue by Draven-1** [sogou/workflow#882]
![image](https://user-images.githubusercontent.com/54003179/165872960-80e93df7-bbbb-4241-8093-2b05fb6f7804.png)

echo_server.cc  就是  tutorial/tutorial-04-http_echo_server.cc

**Comment by Draven-1** [comment]
> 是不是你的lib是clang编译，用g++链不上？ 可以尝试在tutorial目录里直接打make。

是g++的问题。g++是我自己编译的一个版本比较高的。可能配置不全导致的吧。

**Comment by wasphin** [comment]
C++ ABI 不兼容的问题，string 很容易出现。
