### ISSUE TITLE
关于服务端的process的疑问

### ISSUE THREAD

**Issue by liaozhengsong** [sogou/workflow#902]
请问process可以看成是专门用来处理server的response的任务吗？也就是当process调用的时候，前面所有的任务都已经执行完成了，随后process专门用来生成给客户端的回复。
但是如果采用上述的看法的话，当process执行过程中前面的任务都已经完成了，那么process自然就不能修改前面的任务了。
所以现在的问题就是，process应该在什么时机调用呢？到底是一个客户端连接的开始的时候调用，还是服务端任务完成之后才调用呢？

**Comment by liaozhengsong** [comment]
我自己用代码测试了一下，发现process的执行会在所有的任务之前。这样我就有了一个结论：
process会在所有的服务端任务之前执行，其作用是找server的任务，以便用户可以调整任务的属性，用户的回复会在任务所在的序列执行完成之后返回给客户端。

**Comment by holmes1412** [comment]
你对回复时机的理解是对的，process是被动调起的，所以没有什么“前面的任务”一说。可以看看[FAQ](https://github.com/sogou/workflow/issues/170)中的“server是在process函数结束后回复请求吗”。
这样可以很方便地实现异步server。

**Comment by Barenboim** [comment]
嗯嗯，process是在server收到一个完整的请求是被调用。然后server task的series就是处理逻辑。
最近，我们还开发了一个module task，用于优化server处理逻辑的开发，你可以看一下：
https://github.com/sogou/workflow/blob/master/docs/about-module.md

**Comment by Barenboim** [comment]
@liaozhengsong
