### ISSUE TITLE
关于http下载服务器实现限制向客户端传输响应速率的需求实现（下载限速）

### ISSUE THREAD

**Issue by willreno1987** [sogou/workflow#903]
使用workflow实现的http文件服务器，在客户端连接下载的时候,需要进行限速处理。请问,如何实现呢？

**Comment by Barenboim** [comment]
目前可以用的方法，是利用server task的push接口：
~~~cpp
void process(WFHttpTask *task)
{
    task->noreply(); // 不使用框架reply。
    task->push("HTTP 200 OK\r\nTransfer-Encoding: chunked\r\n ...."); // 需自己构造全部返回内容
    WFTimerTask *timer = WFTaskFactory::create_timer_task(1000, [task](WFTimerTask *timer) {
          task->push(...);
          // 根据自己的限速需求构造timer和调用push
          ...
     });
    series_of(task)->push_back(timer);
}
~~~
注意push是一个同步非阻塞调用接口，所以如果push的数据超过tcp send buffer的空间，push返回实际写入字节或返回-1，errno=EAGAIN。不过你既然是要限速，想必也不会一次push太多字节。另外，注意要调用noreply，否则框架还会回复实际的http response。noreply之后，原本reply的时机，会直接关闭连接。也就是说，长链接也用不了（除非是自定义协议）。但既然是限速，短链接应该无所谓吧。

**Comment by willreno1987** [comment]
谢谢爷回复，又研究下了的chunk编码规则，试验了上述代码，已经搞定了。

**Comment by willreno1987** [comment]
好的 我试试 谢谢
