### ISSUE TITLE
kafka一直进入回调问题

### ISSUE THREAD

**Issue by MrStack** [sogou/workflow#911]
请问通过create_kafka_task(some_topic,2,kafka_callback)函数创建的消费者任务，什么时候进入回调呢？

目前遇到通过这种方式注册的回调kafka_callback会在任务创建的时候就进入，然后由于回调内又会创建新的kafka任务，并将回调函数函数设置为自身(kafka_callbakc)，导致频繁进入回调函数，但是此时并没有监听的topic消息产生。

部分源码：
`static void kafka_callback(WFKafkaTask *p_kafka)
{
    //do something

    std::cout<<"create new task\n"<<std::endl;
    WFKafkaTask *p_next = g_kafka_client.create_kafka_task(WATCH_TOPIC, 3, kafka_callback);
    series_of(p_kafka)->push_back(p_next);

    return;
}
`

我理解的是，创建一个kafka任务后，当指定topic有消息产生过后才会进入kafka_callback，然后进行相应处理，处理完后创建一个新任务继续监听消息。
但是目前是不断进入kafka_callback这个回调，但是并没有消息产生。

**Comment by wzl12356** [comment]
首先，在callback中设置自己是callback是可以的，其实就是任务执行后执行用户的callback。
WATCH_TOPIC 这个是什么？

**Comment by MrStack** [comment]
WATCH_TOPIC是字符串"api=fetch&topic=user"

**Comment by MrStack** [comment]
就目前从日志来看，即使生产者没有产生user这个主题的消息，但是还会频繁打印“create new task”这句话。
我理解的是当某个user主题的消息到达后才应该进入回调，可是现在没有user主题的消息还是会进入回调呢？这样就导致一直在创建新任务，然后CPU占用率很高

**Comment by wzl12356** [comment]
不是，没有数据也会callback的，只不过取的消息是空，不会一直阻塞task的

**Comment by MrStack** [comment]
那请问如果要实现监听消息的话，必须要这样一直回调循环吗？还是说需要用其他什么编程模型来实现呢？

**Comment by MrStack** [comment]
好的，谢谢，我试试

**Comment by Barenboim** [comment]
> 就目前从日志来看，即使生产者没有产生user这个主题的消息，但是还会频繁打印“create new task”这句话。
> 我理解的是当某个user主题的消息到达后才应该进入回调，可是现在没有user主题的消息还是会进入回调呢？这样就导致一直在创建新任务，然后CPU占用率很高

kafka的fetch操作，是有一个等待超时的。哪怕没有新消息，也不应该一直回调的。你那边看到CPU占用率高？

**Comment by MrStack** [comment]
> > 就目前从日志来看，即使生产者没有产生user这个主题的消息，但是还会频繁打印“create new task”这句话。
> > 我理解的是当某个user主题的消息到达后才应该进入回调，可是现在没有user主题的消息还是会进入回调呢？这样就导致一直在创建新任务，然后CPU占用率很高
> 
> kafka的fetch操作，是有一个等待超时的。哪怕没有新消息，也不应该一直回调的。你那边看到CPU占用率高？

是的0.10.1这个版本更新后kafka会一直进入回调，0.9.10版本不会，感觉这两个版本的行为似乎不一致。

**Comment by Barenboim** [comment]
我来看一下。

**Comment by Barenboim** [comment]
> > > 就目前从日志来看，即使生产者没有产生user这个主题的消息，但是还会频繁打印“create new task”这句话。
> > > 我理解的是当某个user主题的消息到达后才应该进入回调，可是现在没有user主题的消息还是会进入回调呢？这样就导致一直在创建新任务，然后CPU占用率很高
> > 
> > 
> > kafka的fetch操作，是有一个等待超时的。哪怕没有新消息，也不应该一直回调的。你那边看到CPU占用率高？
> 
> 是的0.10.1这个版本更新后kafka会一直进入回调，0.9.10版本不会，感觉这两个版本的行为似乎不一致。

你好，麻烦帮我们看一下，在没有新消息并callback时，callback里的task->get_state()和task->get_error()分别是什么？是不是WFT_STATE_SYS_ERROR（1）和ETIMEOUT（110）。如果是，从任务发起到callback之间的时间是多少？

**Comment by Barenboim** [comment]
还有一个问题，您说0.9.10版不会一直进回调，这个问题是0.9.11引入的，还是0.10.1？因为后面这两个版本差别挺大的。

**Comment by Barenboim** [comment]
感觉上应该是这个默认行为修改的原因：
https://github.com/sogou/workflow/commit/e68c36ddbd7e056df3b8eb883ee6dda4c6766563
之前：
conf->offset_timestamp = KAFKA_TIMESTAMP_EARLIEST;
改为了：
 conf->offset_timestamp = KAFKA_TIMESTAMP_LATEST;
你这么改看看行不行：
~~~cpp
{
    WFKafkaClient client;
    client.init(url);
    protocol::KafkaConfig conf;
    conf.set_offset_timestamp(KAFKA_TIMESTAMP_EARLIEST);
    client.set_config(std::move(conf));
    ...
}
~~~

**Comment by Barenboim** [comment]
@MrStack
