### ISSUE TITLE
workflow如何保证执行顺序的同时又避免开启过多线程数？

### ISSUE THREAD

**Issue by willkk** [sogou/workflow#912]
比如A->B->C三个子任务组成的串行任务列表。三个子任务都继承WFTreadTask对象，重载execute方法。当前是在execute里面使用WaitGroup，线程外部调用WaitGroup::done操作实现线程退出。但WaitGroup默认会新增线程。有没有其他实现方法，进来不新增线程，同时能直接复用SeriesWork和ParallelWork原有语义？

**Comment by Barenboim** [comment]
啊啊啊。千万不要在execute过程wait。也不要在thread task的callback里wait。计算线程是固定的，堵住就没人能计算了。

**Comment by Barenboim** [comment]
Waitgroup只会在通讯线程里增加线程，计算线程里不会。但无论如何，计算任务的执行和callback，都不要wait。可以用counter什么的

**Comment by willkk** [comment]
给个示例？

**Comment by Barenboim** [comment]
我不太明白你的问题。thread task和其他任何task一样，都可以放在series里。用于thread task的线程数，默认等于机器上CPU核数。你正常用，不存在线程会超出的问题。

**Comment by Barenboim** [comment]
https://xyproblem.info/
你看一下这个xyproblem，尽量提出X问题，而不是Y问题。

**Comment by Barenboim** [comment]
另外，也没有必要重载execute方法，直接使用go task就可以了。
https://github.com/sogou/workflow/blob/master/docs/about-go-task.md

**Comment by willkk** [comment]
使用WaitGroup的问题是，会阻塞线程，这样就要求程序开启成千上万的线程。可能会带来效率和扩展性问题。而如上所说，使用Counter又会额外引入代码来保证执行顺序问题。所以，问题如标题所说。

**Comment by holmes1412** [comment]
其实我理解，如果我们SeriesWork push三个任务，该怎么解决数据依赖就还是怎么解决数据依赖问题。举个例子，我们在一开始创建SeriesWork的时候，把任务流上需要处理的data创建好，挂到SeriesWork的context上。
然后比如在中间的execute结束之后，把数据也填到context上，就可以了。

也就是说，不要把任务流依赖和数据混为一谈，就会很优雅，你可以试试用series的context统一解决数据传递问题？

**Comment by Barenboim** [comment]
业务场景是典型串并联，那么workflow哪里不能解决呢？series push三个thread task，本来就肯定保序啊。不存在你说的问题。你直接用就对的。没有任何派生和wait的需求。

**Comment by willkk** [comment]
我一个任务可能执行几十分钟或几个小时。

**Comment by Barenboim** [comment]
你几时分钟不是一直在计算吧？如果不是，中间是要插入定时还是等待呢？
如果定时，直接定时器。如果等待，就在callback 里插入counter，别人唤醒counter就可以。thread task的execute中间插入等待是不对的。如果你的计算+等待，构成一个完整的业务逻辑，你想要模块话一些，也可以用我们的moduel task解决：
https://github.com/sogou/workflow/blob/master/docs/about-module.md
但无论是如何，thread task内部肯定是纯计算的。

**Comment by holmes1412** [comment]
我理解，就是需要有一个概念，如果一件事情是：
~~~cpp
execute()
{
aaa；
......// 中间可能要被打断、或者中断、或者卡住很久什么的
bbb;
}
~~~
无论aaa和bbb是什么逻辑，其实本质上他们这些逻辑是应该被拆开成两个任务的，这就是workflow做结构化并发的时候是基于任务而不是基于线程的一个思想。

**Comment by Barenboim** [comment]
你一点要描述清楚原始业务需求（X problem）。不要描述你尝试的解决方案。

**Comment by Barenboim** [comment]
如果计算里加入等待，然后想做成一个单个的thread task，理论上派生是可以的。但派生的是dispatch()方法和done()方法。你派生execute也是不对的。

**Comment by willkk** [comment]
原始需求如issue标题：workflow用于大并发网络任务场景，非计算场景，所以要控制线程数，保证扩展性。另外，前后任务有数据依赖，所以要保证串并行顺序。个人想法是尽量基于SeriesWork和ParallelWork容器本身语义，避免过多冗余代码。

**Comment by Barenboim** [comment]
感觉你这个需求直接用就好了啊。workflow的网络线程数本来就可以配置。只要你不使用waitgroup，线程也不会增加。好像你不需要改任何东西。
另外，其实我还是不理解原始需求，基本上我一直在猜你的问题是什么。
https://xyproblem.info/
这个看一下吧，对我们很有用。

**Comment by holmes1412** [comment]
其实现在有一个很重要的问题是：“任务等待其他链路告知任务结束”。如果你的链路本身不是Workflow的task，而是其他框架的异步流程，那么一定需要其他唤醒机制来回到workflow的流程中。
既然你原先也拥有了waitgroup，感觉你拥有counter也没什么区别。更何况，counter task本身是一种task，比waitgroup更加符合“前后都是任务流”的思想。你也许可以先尝试看看这个解决方案，并没有你想象中的复杂。 @willkk

**Comment by Barenboim** [comment]
@willkk
这个我先关了。没有看明白你的需求。有需要可以重新打开issue讨论。
