### ISSUE TITLE
workflow 线程池改造 tips

### ISSUE THREAD

**Issue by zhouguoqionghai** [sogou/workflow#913]
这样一种场景：我有 10 任务，分成 2 组。假设前 5 个为 A 组，后 5 个为 B 组。每组当中，只要有一个执行失败（类似任务函数返回值非 0），那么每组剩下未执行的任务需要直接从任务队列当中剔除不再执行。

假设A组的3号任务执行失败，剩下的4，5号任务就不需要再执行，另外还需要再往线程池当中投递一个清理的任务。

这种场景，怎么改造比较合适呢？

**Comment by Barenboim** [comment]
每个组里的任务的顺序执行的吧? 这个很简单，用我们的计算任务和series的cancel接口就可以了。你先看一下go task这个文档，一全给你写的demo。
https://github.com/sogou/workflow/blob/master/docs/about-go-task.md

**Comment by zhouguoqionghai** [comment]
嗯嗯，我想表达的重点不在于顺序，而是在于取消呀。

**Comment by Barenboim** [comment]
我感觉你的重点是任务之间的依赖关系。这块就是workflow解决的问题。

**Comment by Barenboim** [comment]
> 感谢小姐姐回答，笔芯。

？？

**Comment by MaybeShewill-CV** [comment]
@zhouguoqionghai  哈哈哈 认错人了 小姐姐是另外一位:)
