### ISSUE TITLE
这行代码是否有并发问题

### ISSUE THREAD

**Issue by WangShuaiNWPU** [sogou/workflow#916]
https://github.com/sogou/workflow/blob/d694479b15fa33b3d6d14ed3a0a6234d300f6b5a/src/kernel/thrdpool.c#L74

这行代码是pthread_mutex_unlock(&pool->mutex)之后执行，此时没有获取到互斥锁，那这个if (pool->nthreads == 0)读操作，是存在并发问题的吧？

**Comment by Barenboim** [comment]
你好。这个判断在锁外，但是并不会存在并发的问题。这里有两种情况：
1、72行task_routine里调用了thrdpool_destroy，那么，destroy函数里会等待所有其它线程退出。此时，除了本线程，已经没有任何线程可能访问pool对像，且nthreads==0判断成立，释放pool并返回。
2、task_routine里没有调用thrdpool_destroy，那么，可能有线程池正在退出那么其它线程可能正在操作pool->nthreads。但就算有线程在写nthreads（nthreads可能正在自减），对nthread==0的判断都不会成立，无论在任何硬件体系结构下都不会成立。本线程正常进入下一次循环。
所以，这里并没有并发相关的风险。感谢看得这么仔细。

**Comment by WangShuaiNWPU** [comment]
好的，感谢答疑
