### ISSUE TITLE
set_response_timeout接口

### ISSUE THREAD

**Issue by gnblao** [sogou/workflow#918]
hi，client task去请求一个url时候，wf中都是通过sg（nameseivce）拿到对应ip的target，而这个target中的response_timeout值，来自WFGlobal，这样感觉缺少灵活性。程序中可能有不同client，而每个的response_timeout值可能不一样。

**Comment by Barenboim** [comment]
目前简单的方法是通过upstream来修改，在upstream的文档里有介绍，对单个域名可以独立配置connect_timeout和response_timeout等。
之前，有一个版本是可以配置任务级的response_timeout，后来觉得不是太好，暂时给删了。这个确实是有用的，但需要想一个更完美的方法。

**Comment by gnblao** [comment]
我先玩玩，现在还是保持默认的，后续在考虑下怎么魔改一下😄😄

**Comment by gnblao** [comment]
我先玩玩，现在还是保持默认的，后续在考虑下怎么魔改一下😄😄
