### ISSUE TITLE
[Bug] Kafka record have wrong offset value

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#927]
当用类似下面的方式访问 kafka 时，返回的多个 rec 的 offset 和实际的 offset 不一致：

![image](https://user-images.githubusercontent.com/2898670/170968773-5c6150a7-9044-4d27-a83f-9697b8f0c9b7.png)

当用 rec->get_offset() 获取 offset 时，打印的 offset 值是一样的，且和请求时不一致：

![image](https://user-images.githubusercontent.com/2898670/170969575-80fe63e2-1889-421e-9624-f52c07e3ddf4.png)

**Comment by hiberabyss** [comment]
@wzl12356 能帮忙看下么？或者方便的话能帮忙提供下你的联系方式么？我的邮箱是： lhbf@qq.com . 谢谢！

**Comment by wzl12356** [comment]
这个是指定offset的模式吗？

**Comment by hiberabyss** [comment]
> 这个是指定offset的模式吗？

对的，用下面的方式访问的：

```
      KafkaToppar toppar;
      toppar.set_topic_partition(item->topic(), 0);
      toppar.set_offset(item->offset());
      task->add_toppar(toppar);
```

打印日志对应的代码：

![image](https://user-images.githubusercontent.com/2898670/170995329-509daf86-9162-4766-8948-b3d42c55ad8c.png)

**Comment by Barenboim** [comment]
似乎获得的offset比你请求更小？request是240226，得到240225？
这个有点奇怪。toppar.set_offset()操作只是原封不动吧offset添入Kafka请求。协议里填写240226，得到240225，好像不太应该。

**Comment by Barenboim** [comment]
我现在有点不确定你的task->add_toppar()是否成功。如果这句没有成功，那么240226的offset可能根本没有设置到task里。你能不能打印一下taks->add_toppar()的返回值呢？

**Comment by hiberabyss** [comment]
> 我现在有点不确定你的task->add_toppar()是否成功。如果这句没有成功，那么240226的offset可能根本没有设置到task里。你能不能打印一下taks->add_toppar()的返回值呢？

返回值是 1

**Comment by hiberabyss** [comment]
> 你之前消费过240225这条记录吗？

应该是消费过的？这里有什么区别么？消费过的 offset 是我自己维护的

**Comment by Barenboim** [comment]
我担心新的offset没有设置成功，或者因为什么原因回到上一个offset上。
我看了一下代码，WFKafkaClient里似乎没有什么情况会得到一个减1的offset。
您能不能gdb帮我们跟一下？主要看这一行：
https://github.com/sogou/workflow/blob/46aff3bc242489bb2e2e3595903afe2bd02b5cf6/src/protocol/KafkaMessage.cc#L2398
当你设置了240226，这里是否有什么情况下，get_offset得到240225。

**Comment by Barenboim** [comment]
现在我需要搞清楚是发送的时候就错了，还是返回的记录offset不对。

**Comment by hiberabyss** [comment]
> 现在我需要搞清楚是发送的时候就错了，还是返回的记录offset不对。

可以通过抓包的方式来看么？

**Comment by Barenboim** [comment]
抓包会不会比较麻烦？如果你有源代码并且可以复现，直接打印一下就可以了。
另外，你用的kafka是最新版的吗？

**Comment by Barenboim** [comment]
这里3月份关于smaller offset的一个修改：
https://github.com/sogou/workflow/pull/804

**Comment by hiberabyss** [comment]
问下回包的 offset 可以在哪里看呀？

**Comment by Barenboim** [comment]
协调内容我不太懂……你先看看是不是代码版本的问题。

**Comment by hiberabyss** [comment]
> 协议内容我不太懂……你先看看是不是代码版本的问题。

用的是最新版本的代码哈

**Comment by Barenboim** [comment]
😂
那等等这个协议的作者吧。现在看起来，好像发送的offset是正确的，而且，对方确实可能在某些逻辑下会返回一个比较发送offset更小的记录。然后client这边有一些处理逻辑。可能是什么地方处理得不太对。你那边有环境可以帮我们单步的跟一下。

**Comment by hiberabyss** [comment]
> 😂 那等等这个协议的作者吧。现在看起来，好像发送的offset是正确的，而且，对方确实可能在某些逻辑下会返回一个比发送offset更小的记录。然后client这边有一些处理逻辑。可能是什么地方处理得不太对。你那边有环境可以帮我们单步的跟一下。

发现编译成 debug 模式是正常的，release 版本就有问题 [捂脸]

我是用的 c++20

**Comment by Barenboim** [comment]
> > 😂 那等等这个协议的作者吧。现在看起来，好像发送的offset是正确的，而且，对方确实可能在某些逻辑下会返回一个比发送offset更小的记录。然后client这边有一些处理逻辑。可能是什么地方处理得不太对。你那边有环境可以帮我们单步的跟一下。
> 
> 发现编译成 debug 模式是正常的，release 版本就有问题 [捂脸]
> 
> 我是用的 c++20

这就很尴尬了。如果可以的话，之后也帮我们看看发送和接收的数据包有没有什么不同。

**Comment by Barenboim** [comment]
感觉上我们的代码不至于出现加了优化之后行为不一样的问题啊。也麻烦检测一下，之前是不是链接的是一个老版本的lib。

**Comment by hiberabyss** [comment]
我用的 bazel ，不太会出现库链接错的问题

**Comment by Barenboim** [comment]
你现在可以确定是debug和release的区别了？那这个就有意思了😄

**Comment by Barenboim** [comment]
还需要确定一个问题，是否是你的业务代码debug和release的原因……

**Comment by wzl12356** [comment]
可以在KafkaRequest::encode_fetch中加日志，打印请求协议中的offset，看是否符合预期

**Comment by hiberabyss** [comment]
> 可以在KafkaRequest::encode_fetch中加日志，打印请求协议中的offset，看是否符合预期

打印的 offset 是符合预期的，但日志是在获取完消息后才打印的，这个符合预期吧？

**Comment by Barenboim** [comment]
request里的offset应该不会变的。获取完消息再打印应该是一样的。也就是说，现在发送的消息，offset是对的。但收回来的数据好像offset不对，比请求的少了1。而且还是debug/release相关……

**Comment by hiberabyss** [comment]
> request里的offset应该不会变的。获取完消息再打印应该是一样的。也就是说，现在发送的消息，offset是对的。但收回来的数据好像offset不对，比请求的少了1。而且还是debug/release相关……

是我之前代码的问题，之前 printf 的时候没有加换行符；然后打印 kafka 消息和打印 offset 应该是不同的线程，打印的顺序就和实际的顺序不一致了。

加了换行符之后就是在打印消息前输出的了，这个行为 debug 和 release 是一致的。

**Comment by hiberabyss** [comment]
> 还需要确定一个问题，是否是你的业务代码debug和release的原因……

我后面单独写了一个简单的只是消费的示例代码，也是一样的问题；感觉和我的业务代码应该关系不大。

**Comment by Barenboim** [comment]
你加上这个呢：
~~~cpp
{
    WFKafkaClient client;
    client.init(url);
    protocol::KafkaConfig conf;
    conf.set_offset_timestamp(KAFKA_TIMESTAMP_EARLIEST);
    client.set_config(std::move(conf));
    ...
}
~~~

**Comment by hiberabyss** [comment]
没用哈，一样的问题

**Comment by hiberabyss** [comment]
抓包看请求没什么区别：

这个是 release 版本，offset 有问题的请求：

![image](https://user-images.githubusercontent.com/2898670/171129613-a87a000e-8b9e-4ada-ab03-ea0d35d83c0c.png)

下面是 debug 版本的请求：
![image](https://user-images.githubusercontent.com/2898670/171129877-c2419e7f-45a5-42f4-9da5-9dd6ba08c641.png)

**Comment by wzl12356** [comment]
现在是说encode_fetch中打印的offset是对的？但是返回消息的offset是不对的吗？
可以看一下parse_fetch中的offset是否正确，之前遇到过指定offset情况下，请求offset和返回不一致的情况，感觉和kafka broker有关（当时用rdkafka也测试过，表现一致）

**Comment by hiberabyss** [comment]
> 现在是说encode_fetch中打印的offset是对的？但是返回消息的offset是不对的吗？ 可以看一下parse_fetch中的offset是否正确，之前遇到过指定offset情况下，请求offset和返回不一致的情况，感觉和kafka broker有关（当时用rdkafka也测试过，表现一致）

经过调试发现是 `parse_varint_i64` 这个函数在 release 和 debug 模式下行为不一致，在把  static inline 去掉后逻辑是 OK 的：

https://github.com/sogou/workflow/pull/928

看起来是 inline 的时候  `n` 这个变量被优化掉了，在测试的时候如果 `printf n`，逻辑就符合预期。

**Comment by Barenboim** [comment]
现在的问题是，我们发送的数据和接收的数据，都没有问题。但在gcc11的编译器里，解析回包时，如果在release(O2)情况下，有一个64bit整数解析不正确，导致response读取到的offset错误，但实际fetch到的数据，是正确的。
我这个描述正确吗？

**Comment by Barenboim** [comment]
你好。麻烦再用master最新代码帮我们试一下还有没有问题。我们没有发现代码方面的bug，按照你说的去除了两个inline函数，顺便改了一些warning。 @hiberabyss 
如果这个修改可以消除你的offset问题，那只能怀疑是踩了g++11的bug。

**Comment by hiberabyss** [comment]
现在问题已经修复了，和数据类型有关系。之前的 long long 类型 break 了 strict-aliasing ，对应的行为是 undefined，编译期升级时行为逻辑有可能有变化。

**Comment by Barenboim** [comment]
> 现在问题已经修复了，和数据类型有关系。之前的 long long 类型 break 了 strict-aliasing ，对应的行为是 undefined，编译期升级时行为逻辑有可能有变化。

我去，是哪一行代码，可以发一下吗？我现在有个地方改成uint64，然后就好了吗？

**Comment by Barenboim** [comment]
但是我改这个类型时，特意用g++11的编译器，对比long long和int64在x86_64上的汇编代码，是完全identical的。

**Comment by hiberabyss** [comment]
应该是这部分的修改：

![image](https://user-images.githubusercontent.com/2898670/172161846-e7f86aa0-3a15-4fa6-bcb0-dbdd1c8df149.png)

这里主要是加编译优化 -fstrict-aliasing 后的行为不一致，如果编译器认为类型不一致，会认为不同类型的指针也是不一样的，导致指针传值的方式失效。

**Comment by hiberabyss** [comment]
这是我之前简化的示例，把  long long 改成 int64_t 之后逻辑是正确的。否则 gcc11 里 O2 和 O1 的返回结果不一致

```
#include <cstdint>
#include <iostream>
#include <algorithm>
#include <vector>

using namespace std;

void parse_varint_u64(void **buf, uint64_t *val) {
	size_t of = 0;
	uint64_t num = 0;

	do {
		num |= (uint64_t)(((char *)(*buf))[(int)of] & 0x7f);
	} while (((char *)(*buf))[(int)of++] & 0x80);

	*val = num;
}

void parse_varint_i64(void **buf, int64_t *val) {
	uint64_t n = 123;
	parse_varint_u64(buf, &n);

  // printf("n: %d\n", n);

  *val = (int64_t)(n >> 1) ^ -(int64_t)(n & 1);
}

int main(int argc, char *argv[]) {
  size_t size = 16;
  void* data = malloc(size);
  for (size_t i = 0; i < size; ++i) {
    ((char*)data)[i] = i + 10;
  }

	long long offset_delta = 0;

  parse_varint_i64(&data, (int64_t *)&offset_delta);

  std::cout << "offset delta: " << offset_delta << std::endl;

  return 0;
}
```

**Comment by Barenboim** [comment]
谢谢。这个确实算我们的bug，只是我们没想到long long和int64指针还有不能互相转的情况。之前的代码写成int64才是对的。
