### ISSUE TITLE
客户端卡死，服务器不响应

### ISSUE THREAD

**Issue by zj376879088** [sogou/workflow#930]
一个简单的http api服务，客户端少于10个，每秒钟都有几次请求。
客户端是java请求，服务端使用workflow实现。
长时间使用，大概7天左右，就会出现客户端请求卡死，达到最大超时时间抛错。而服务端业务部分不能收到任何消息。
使用lsof -i观察端口情况，端口依然处于监听状态。但是最后一条，fd显示1023。连接全部是close_wait状态，后面没用其他日志。
短时间不复现，长时间必现，没有有效日志。
出现此情况后，无论怎么请求，服务器均不再响应。

**Comment by Barenboim** [comment]
这个程序没有什么问题，文件操作的fd不会泄漏。
出现close_wait只可能是handler线程忙碌或卡死。由于timer回调所使用的线程也是handler线程。你程序里启动了timer，比较怀疑你在timer的callback做了什么事情导致函数没有返回，然后有启动了新的timer，最后20个handler都被timer callback占着。
另外，你好像最大文件数是1024，但server的max_connections加大到1万，这个好像没有什么意义。当然这不是出问题的原因。

**Comment by zj376879088** [comment]
这是timer部分代码，利用ping保存mysql长连接。
/*定时器任务*/
/////////////////////////////////////////////////////
std::mutex mutex;

bool program_terminate = false;

unsigned int timer_interval = 30000000;

void timer_callback(WFTimerTask *timer)
{
    //std::cout << "timer_callback time: " << getCTime() << std::endl;
    mutex.lock();
    if (!program_terminate)
    {
        /*为保证数据的的长连接，30秒维持连接一次。如果数据库连接失败，退出系统*/
        if(MysqlDB::getInstance()->ping() != 0) {
            fprintf(stderr, "数据库失连，请检查系统！\n");
            exit(-1);
        }
        /*重新触发定时器*/
        series_of(timer)->push_back(WFTaskFactory::create_timer_task(timer_interval, timer_callback));
    }
    mutex.unlock();
}
////////////////////////////////////////////////////////

**Comment by Barenboim** [comment]
timer callback里调用exit不对。但这个有log，很好排查。
现在只能怀疑这几句非workflow框架的调用：
~~~cpp
        CusRrequest cr(uh->getUri(), req, uh->getKeys());
        cr.checkReqUri(uri);
        std::string resp = uh->cb(&cr);
~~~
可以看看一下线程是不是卡在这个cb调用里了。在程序卡死的时候，gdb -p <进程号>看下线程的状态。
MySQL可以尝试用workflow自带的MySQL任务。

**Comment by zj376879088** [comment]
下面是回调处理的代码，不涉及文件句柄。卡死的时，业务逻辑部分没有任何消息过来，请求并没有到上层。我另外一个同事也使用了我给他的代码，他的回调实现部分与我不同。因为调用频次比我高，大概3/4天也会出现不响应情况。
string apiHandler(CRequest *req) {
    
    const void* body = req->getBody();

    printf("Request-BODY: %s\n", (char*)body);
    if (*(char*)body != '{') {
      return "{\"code\":-1, \"message\":\"please post json\"}";
    }
    
    Json::Reader reader;
    Json::Value obj;
    if (!reader.parse((const char*)body, obj)) {
      return "{\"code\":-1, \"message\":\"body json parse error!\"}";
    }
    
    string type = obj.get("type", JSON_EMT_STR).asString();
    if (type.size() == 0) {
      return "{\"code\":-1, \"message\":\"no message type find\"}";
    }
    
    MysqlDB* db = MysqlDB::getInstance();
    string error;
    if (type == "userInsert") {
      Json::Value data = obj.get("data", JSON_EMT_OBJ);
      if (data.size() == 0) {
        return "{\"code\":-1, \"message\":\"no data find\"}";
      }
      
      int ret = db->user_insert(data, error);
      if (ret < 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }
      
      Json::Value result;
      result["code"] = 0;
      result["message"] = "success";
      result["newId"] = ret;
      
      Json::FastWriter writer;
      std::string pdata = writer.write(result);
      return pdata;

    } 
    else if (type == "userDeleteByIds") {
      Json::Value data = obj.get("data", JSON_EMT_OBJ);
      if (data.size() == 0) {
        return "{\"code\":-1, \"message\":\"no data find\"}";
      }
      
      if (db->user_delete_by_ids(data, error) != 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }
      return "{\"code\":0, \"message\":\"success\"}";
    }
    else if (type == "userDeleteByNames") {
      Json::Value data = obj.get("data", JSON_EMT_OBJ);
      if (data.size() == 0) {
        return "{\"code\":-1, \"message\":\"no data find\"}";
      }
      
      if (db->user_delete_by_names(data, error) != 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }
      return "{\"code\":0, \"message\":\"success\"}";
    }
    else if (type == "userUpdate") {
      Json::Value data = obj.get("data", JSON_EMT_OBJ);
      if (data.size() == 0) {
        return "{\"code\":-1, \"message\":\"no data find\"}";
      }
      
      if (db->user_update(data, error) != 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }
      return "{\"code\":0, \"message\":\"success\"}";
    }
    else if (type == "userSelectAll") {
      Json::Value data;   
      if (db->user_select_all(data, error) != 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }
      
      Json::Value result;
      result["code"] = 0;
      result["type"] = type;
      result["data"] = data;
      
      Json::FastWriter writer;
      std::string pdata = writer.write(result);
      return pdata;
    }
    else if (type == "userSelectByName") {
      Json::Value p = obj.get("data", JSON_EMT_OBJ);
      if (p.size() == 0) {
        return "{\"code\":-1, \"message\":\"no data find\"}";
      }
      
      Json::Value data;
      if (db->user_select_one_by_name(p, data, error) != 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }
      Json::Value result;
      result["code"] = 0;
      result["type"] = type;
      result["data"] = data;
      
      Json::FastWriter writer;
      std::string pdata = writer.write(result);
      return pdata;
    }
    else if (type == "setAccuracy") {
        int accuracy = obj.get("accuracy", JSON_EMT_INT).asInt();
        CFace::getInstance()->setAccuracy(accuracy);
        return "{\"code\":0, \"message\":\"success\"}";
    }
    else if (type == "getFingers") {

      Json::Value data;
      if (db->load_fingers(data, error) != 0) {
        return "{\"code\":-1, \"message\":\"" + error+"\"}";
      }

      Json::Value result;
      result["code"] = 0;
      result["type"] = type;
      result["data"] = data;

      Json::FastWriter writer;
      std::string pdata = writer.write(result);
      return pdata;
    }
    else {
        return "{\"code\":-1, \"message\":\"request type error\"}";
    }
}

**Comment by Barenboim** [comment]
你这个我感觉就是线程卡在了数据库啊……
另外，你好像就是个restful应用，可以使用基于workflow的wfrest项目，访问数据库简单一点。
https://github.com/wfrest/wfrest
访问mysql可以参考这个例子：
https://github.com/wfrest/wfrest/blob/main/example/21_mysql.cc
由于访问mysql也基于workflow的mysql实现，不会存在卡死问题。

**Comment by zj376879088** [comment]
后面我会用wfrest实现测试一下。我现在使用的是mysql官方提供的c源码接口，是常用代码，理论上也不存在问题。lsof显示耗尽的句柄是IPv4。真的很难查，因为一旦发现问题，就没有任何有效日志，服务器完全静默状态，底层的socket消息上不来。
我会将前面提出有疑点的几处，都修改了再测试看看。

**Comment by Barenboim** [comment]
> 后面我会用wfrest实现测试一下。我现在使用的是mysql官方提供的c源码接口，是常用代码，理论上也不存在问题。lsof显示耗尽的句柄是IPv4。真的很难查，因为一旦发现问题，就没有任何有效日志，服务器完全静默状态，底层的socket消息上不来。 我会将前面提出有疑点的几处，都修改了再测试看看。

句柄耗尽不一定是泄露。从现象上看，是handler线程没有在工作了。所以想让你用gdb -p或gstack看一下线程都卡在哪个调用了。这个很好查的。一个命令搞定。

**Comment by zj376879088** [comment]
好的，再遇上我就试一下！

**Comment by Barenboim** [comment]
> 有遇到类似问题，但可以确定的是读数据库慢导致的(测试不读数据库服务就会一直稳定，一旦读数据库过段时间就会拒绝几乎所有请求)。 有个疑惑是，这种情况除了让读数据库快起来之外有什么方法让服务不卡死吗。 当然我也没理解为什么会不响应任何请求，包括健康检查的请求都不正常响应 我的场景也不是每个请求都需要读数据库，因为有缓存。
> 
> 可以接受某些请求失败，但不能接受整个服务都挂掉了，不知道是不是有什么建议。
> 
> 还想问下如果客户端请求 50ms 超时，服务端能不能放弃已经超过 50ms 的任务不再处理。

谢谢报出这个问题。我觉得从这个源码上看，也只能是访问数据库的问题。当然，里面还有一个语句是从连接池里拿连接，也不排除是拿连接时卡死。
如果访问的数据库是MySQL协议的，可以直接用我们的MySQL任务。在个在连接管理和超时控制上会好很多，而且就完全异步没有等待了。可以看一下这个文档：https://github.com/sogou/workflow/blob/master/docs/tutorial-12-mysql_cli.md
超时不再处理的问题，只能在server逻辑里自己来判断了。其实也不太难，但需要用户自己来实现。

**Comment by Barenboim** [comment]
@rockyzhengwu @zj376879088 
workflow如果完全卡死，只有一个可能的原因，就是handler线程在等待被唤醒，而唤醒的位置是在网络任务的callback里。这样，如果所有线程都在wait，也就没有线程可以callback并signal了。
但是，用我们的WFFuture和WFFacilities::WaitGroup都不会出现这个问题。因为WFFuture或WaitGroup内部有一个机制，就是如果handler线程进入等待，在智能的增加handler线程，保持活跃的handler线程永远不会减少。
但如果你自己用pthread的condition或std::future来做等待和唤醒，就会出现没有活跃线程的问题了。这个我们是解决不了的，就相当于你在同一个线程池里互相唤醒，肯定有机率会进入死锁。
解决方案也简单。最好是不会在callback里等待。一定要等待必须用我们的wait_group或future，不用能系统库里的。

**Comment by rockyzhengwu** [comment]
@Barenboim  谢谢回复，不是 MySQL 是 [Aerospike](https://github.com/aerospike/aerospike-client-c) , 了解了。

**Comment by Barenboim** [comment]
> @Barenboim 谢谢回复，不是 MySQL 是 [Aerospike](https://github.com/aerospike/aerospike-client-c) , 了解了。

我看了一下他也有async client。配合workfow的WFCounterTask就可以做成一个workflow的异步任务了。这样，handler线程就不会被占住。

**Comment by zj376879088** [comment]
另外，就算handler处理的慢，假设耗时60s，那么60s后也应该释放了。而当前的情况是，一旦出现卡死情况，就永远不会恢复。

**Comment by rockyzhengwu** [comment]
```
void process(WFHttpTask *task) {

  WFFacilities::WaitGroup wait_group(1);
  WFGoTask *query_task = WFTaskFactory::create_go_task("test", query_batch_double_sync, args...);
  query_task->set_callback([&](WFGoTask *query_task) {
    wait_group.done();
  });
  query_task->start();
  wait_group.wait();

}

```

@Barenboim 请教下，看了 go task 好像也是用 counter task 实现的，能在 process 里这样等吗，`query_batch_double_sync` 这个不是异步的

**Comment by Barenboim** [comment]
> ```
> void process(WFHttpTask *task) {
> 
>   WFFacilities::WaitGroup wait_group(1);
>   WFGoTask *query_task = WFTaskFactory::create_go_task("test", query_batch_double_sync, args...);
>   query_task->set_callback([&](WFGoTask *query_task) {
>     wait_group.done();
>   });
>   query_task->start();
>   wait_group.wait();
> 
> }
> ```
> 
> @Barenboim 请教下，看了 go task 好像也是用 counter task 实现的，能在 process 里这样等吗，`query_batch_double_sync` 这个不是异步的

WfGoTask是计算任务，和counter没有什么关系的。但是你上面的程序为什么要这样写呢？应该是series_of(task)->push_back(query_task)。workflow的程序最好不要有wait操作。

**Comment by Barenboim** [comment]
> > WfGoTask是计算任务，和counter没有什么关系的。但是你上面的程序为什么要这样写呢？应该是series_of(task)->push_back(query_task)。workflow的程序最好不要有wait操作。
> 
> 我的逻辑是要在 process 里处理 : 去 kv 拿特征 -> 放到 CTR 的模型里 -> 返回。 我想等 kv 那一步。 感觉没用对 WF .....

并不是process函数结束回复啊……而是server task是series里最后一个任务，series里没有任务了，就回复。
例如，一个延迟一秒返回的server，应该这么写：
~~~cpp
void process(WFHttpTask *task)
{
    task->get_resp()->append_output_body("<html>Hello World!<html>");
    series_of(task)->push_back(WFTaskFatory::create_timer_task(1000000, nullptr));
}
~~~

**Comment by rockyzhengwu** [comment]
> > > WfGoTask是计算任务，和counter没有什么关系的。但是你上面的程序为什么要这样写呢？应该是series_of(task)->push_back(query_task)。workflow的程序最好不要有wait操作。
> > 
> > 
> > 我的逻辑是要在 process 里处理 : 去 kv 拿特征 -> 放到 CTR 的模型里 -> 返回。 我想等 kv 那一步。 感觉没用对 WF .....
> 
> 并不是process函数结束回复啊……而是server task是series里最后一个任务，series里没有任务了，就回复。 例如，一个延迟一秒返回的server，应该这么写：
> 
> ```c++
> void process(WFHttpTask *task)
> {
>     task->get_resp()->append_output_body("<html>Hello World!<html>");
>     series_of(task)->push_back(WFTaskFatory::create_timer_task(1000000, nullptr));
> }
> ```

我把所有逻辑写了个函数在 process 里用大概这样的
```c++
void process(WFHttpTask *task)
{
    req->get_parsed_body(&body, &size);
    model->predict(body, response_body);
    resp->append_output_body(response_body.data(), response_body.size());
}
```
拿特征也在 predict 里面，满足某些条件才需要去拿。上面那个 waitgroup 的例子我其实是写到了 ```model->predict``` 里面的某个地方

**Comment by Barenboim** [comment]
如果你的predict是个纯计算，应该用go_task的：
~~~cpp
void process(WFHttpTask *task)
{
    req->get_parsed_body(&body, &size);
    response_body = new std::string;
    WFGoTask *predict_task = WFTaskFactory::create_go_task("test", predict, body, response_body);
    predict_task->user_data = response_body;
    predict_task->set_callback([task](WFGoTask *predict_task) {
        std::string *response_body = (std::string *)predict_task->user_data;
        task->get_resp()->append_output_body(response_body.data(), response_body.size());
    });
    series_of(task)->push_back(predict_task);
}
~~~

**Comment by Barenboim** [comment]
什么大家这么难以理解series里任务都完成之后回复的这个问题😂

**Comment by Barenboim** [comment]
不如你把你的问题重新开的issu讨论吧。完全描述一下业务需求，我看看怎么实现最合理。@rockyzhengwu

**Comment by rockyzhengwu** [comment]
> 不如你把你的问题重新开的issue讨论吧。完全描述一下业务需求，我看看怎么实现最合理。@rockyzhengwu

好的，用了这么久，确实发现没理解

**Comment by Barenboim** [comment]
@zj376879088 你好，这个issue我先close了。如果有新的case，可以重新打开issue讨论。

**Comment by Barenboim** [comment]
@zj376879088 @rockyzhengwu 
有新发现。当打开文件数超过max open files，即accept出现错误时（EMFILE），我们会认为监听fd出错，此时会关闭监听。这种情况确会有server不再响应的情况。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/987/files
