### ISSUE TITLE
failed to install and compile

### ISSUE THREAD

**Issue by wyfSunflower** [sogou/workflow#932]
xtark@xtark-vmpc:~/Documents/workflow/tutorial$ sudo apt-get install libworkflow-dev -y
[sudo] xtark 的密码： 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 libworkflow-dev
xtark@xtark-vmpc:~/Documents/workflow/tutorial$ sudo apt-get install libworkflow1 -y
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 libworkflow1

xtark@xtark-vmpc:~/Documents/workflow/build$ cat http_client.cc 
// [http_client.cc]
#include "stdio.h"
#include "workflow/HttpMessage.h"
#include "workflow/WFTaskFactory.h"

int main (int argc, char *argv[])
{
    const char *url = "https://github.com/sogou/workflow";
    WFHttpTask *task = WFTaskFactory::create_http_task (url, 2, 3,
            [](WFHttpTask * task) { 
                fprintf(stderr, "%s %s %s\r\n",
                        task->get_resp()->get_http_version(),
                        task->get_resp()->get_status_code(),
                        task->get_resp()->get_reason_phrase());
    });
    task->start();
    getchar(); // press "Enter" to end.
    return 0;
}
xtark@xtark-vmpc:~/Documents/workflow/build$ g++ -o http_client http_client.cc --std=c++11 -lworkflow -lssl -lcrypto -lpthread
http_client.cc:3:10: fatal error: workflow/HttpMessage.h: 没有那个文件或目录
 #include "workflow/HttpMessage.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Barenboim** [comment]
应该是
~~~sh
$ sudo apt-get install libworkflow-dev
~~~
另外，好像apt那边的版本还是0.9.11，最好还是用最新的：
~~~sh
$ git clone https://github.com/sogou/workflow
$ cd workflow
$ make
$ make install
~~~

**Comment by Barenboim** [comment]
你是ubuntu 22.04吗？如果是Debian，可能还需要加上sid。
ubuntu 22.04才是正式包

**Comment by wyfSunflower** [comment]
ubuntu 18.04

**Comment by wyfSunflower** [comment]
> 你是ubuntu 22.04吗？如果是Debian，可能还需要加上sid。 ubuntu 22.04才是正式包

ubuntu 18.04

**Comment by holmes1412** [comment]
你好，Debian里的package管理是这样的：先进入unstable，然后跟随不同系统版本发布进入新版本的正式包里，workflow是去年年底进的debian，所以目前跟随了4月份发版的Ubuntu 22.04，18.04里是没有的。
具体进度可以参考debian官网哈：https://tracker.debian.org/pkg/workflow

**Comment by wyfSunflower** [comment]
tusk@tusk-virtual-machine:~/workflow$ g++ -o http_client http_client.cc --std=c++11 -lworkflow -lssl -lcrypto -lpthread
tusk@tusk-virtual-machine:~/workflow$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
tusk@tusk-virtual-machine:~/workflow$ ./http_client 
./http_client: error while loading shared libraries: libworkflow.so: cannot open shared object file: No such file or directory
