### ISSUE TITLE
[Kafka Coredump] Kafka client 偶尔会出现 core dump

### ISSUE THREAD

**Issue by hiberabyss** [sogou/workflow#940]
下面是对应 coredump 时的栈；

![image](https://user-images.githubusercontent.com/2898670/173487485-e22849f2-8d1d-41ec-a370-b3ee3aad22d0.png)

在调用 WFGlobal::get_error_string 函数时，会有下面的报错：

```
URI Parse Failed
Unknown
```

**Comment by Barenboim** [comment]
感觉不是workflow这边的代码？我们没有kafka.h文件啊。

**Comment by Barenboim** [comment]
你好，能不能加上debug信息，看一下具体core在哪一行吗？

**Comment by Barenboim** [comment]
@hiberabyss 我修改了一些潜在错误。可以再试一下。原来代码可能在32位下会有问题。

**Comment by hiberabyss** [comment]
嗯，我先更新到最新的版本；感谢！

**Comment by Barenboim** [comment]
@hiberabyss 最新代码还有复现问题吗？

**Comment by hiberabyss** [comment]
还是会有类似的问题哈

**Comment by Barenboim** [comment]
看看core的具体位置吧。

**Comment by hiberabyss** [comment]
![image](https://user-images.githubusercontent.com/2898670/175872750-6407ae62-61db-4dc2-94c3-58429bb903b7.png)

**Comment by Barenboim** [comment]
这个能给个具体行数么😓

**Comment by Barenboim** [comment]
$ make DEBUG=y KAFKA=y
这样我们才能得到具体行数。感觉你这个是core在parse_partition里面了。你后面那个截图里，这个函数被一路内联，所以只看到parse_metadata。

**Comment by Barenboim** [comment]
@hiberabyss 
有什么新发现么？

**Comment by hiberabyss** [comment]
没有，最新的代码还是会偶尔出现，没法在线下复现。

出现 task error = 11 很奇怪，看代码不应该有这个错误码

**Comment by Barenboim** [comment]
是state=SYS ERROR，并且errno 11吗？
那这个是连接到上限了。可以加大对单个目标的的max_connections。

**Comment by Barenboim** [comment]
> > 是state=SYS ERROR，并且errno 11吗？ 那这个是连接到上限了。可以加大对单个目标的max_connections。
> 
> state 是 67 WFT_STATE_TASK_ERROR

我们kafka最新代码，按理已经修复了TASK_ERROR，但error又是errno的问题。如果有这种情况，是不是并非新代码？另外，如果是11，可能是连接数超过200了。可以调。

**Comment by hiberabyss** [comment]
之前用的还是 6 月中旬的代码，我先更新到最新的 commit ；这里的连接是指 client 和某个 kafka broker 的连接数？这个参数该怎么调整？

**Comment by Barenboim** [comment]
> 之前用的还是 6 月中旬的代码，我先更新到最新的 commit ；这里的连接是指 client 和某个 kafka broker 的连接数？这个参数该怎么调整？

是的，就是max connection参数。可以改全局的，也可以改单个upstream的。但如果说对单个broker连接都到200了，感觉是不是有别的问题？改全局的方法：
~~~cpp
{
    struct WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.endpoint_params.max_connections = 1000;
    WORKFLOW_library_init(&settings);
}
~~~

**Comment by Barenboim** [comment]
> 更新到 [d3b0bda](https://github.com/sogou/workflow/commit/d3b0bda9939709cc4d7d7a4a9b31ed9bc16d76ad) 版本后，还是会出现 state 67， error 11 的错误。

这个……我查一下。

**Comment by Barenboim** [comment]
看起来这个error是broker通过消息返回的。现在这个表示方法，不是太好。我们想想怎么优化一下。
还是再看看试试还会不会core。

**Comment by Barenboim** [comment]
看起来这个error是broker通过消息返回的。现在这个表示方法，不是太好。我们想想怎么优化一下。
还是再试试还会不会core。

**Comment by hiberabyss** [comment]
为什么还不时会有 URI Parse Failed 的错误呢，这个不应该是初始化时候的错误么。我的程序只有在启动的时候会初始化 kafka client

![image](https://user-images.githubusercontent.com/2898670/177679087-c27a1c28-5b9e-407d-8f5d-d8fecfb7d76f.png)

**Comment by Barenboim** [comment]
URI是在发起实际任务时才解析的噢，所以后面有URI Parse Failed也是正常的。但偶尔出现一个就有点奇怪。我再看一下。

**Comment by Barenboim** [comment]
@hiberabyss
做了个很大的修改：https://github.com/sogou/workflow/pull/981
对于TASK ERROR，可以调用task->get_kafka_error()获得进一步的错误吗。kafka error定义在[kafka_parser.h](https://github.com/sogou/workflow/blob/master/src/protocol/kafka_parser.h)里的第一个enum里。
之前错误11，应该是KAFKA_STALE_CONTROLLER_EPOCH这个错误。不知道是否符合预期？
这个改动还需要@wzl12356 再review一下。

**Comment by Barenboim** [comment]
@hiberabyss 你好。能不能直接从我的fork上拉代码试一下？没有什么大问题我再合一下。

**Comment by Barenboim** [comment]
已经合进master！

**Comment by Barenboim** [comment]
@hiberabyss 
我先关了issue。有发现新问题继续讨论。
