### ISSUE TITLE
基于消息队列模块重写了线程池，计算调度性能大幅提升。

### ISSUE THREAD

**Issue by Barenboim** [sogou/workflow#955]
之前线程池获取任务的实现：
~~~cpp
{
	while (1)
	{
		pthread_mutex_lock(&pool->mutex);
		while (!pool->terminate && list_empty(&pool->task_queue))
			pthread_cond_wait(&pool->cond, &pool->mutex);

		if (pool->terminate)
			break;

		entry = list_entry(*pos, struct __thrdpool_task_entry, list);
		list_del(*pos);
		pthread_mutex_unlock(&pool->mutex);

		task_routine = entry->task.routine;
		task_context = entry->task.context;
		free(entry);
		task_routine(task_context);
		...
	}
}
~~~
新的基于msgqueue的实现：
~~~cpp
{
	while (!pool->terminate)
	{
		entry = (struct __thrdpool_task_entry *)msgqueue_get(pool->msgqueue);
		if (!entry)
			break;

		task_routine = entry->task.routine;
		task_context = entry->task.context;
		free(entry);
		task_routine(task_context);
		...
	}
}
~~~
代码大幅简化。由于msgqueue模块使用了更加高效的生产者消费者队列实现，新的线程池在调度overhead上大幅度降低。实测100万个轻量级计算任务，总运行时间从5.2s降低到3.5秒。
PR: https://github.com/sogou/workflow/pull/954
消息队列代码：
https://github.com/sogou/workflow/blob/master/src/kernel/msgqueue.h
https://github.com/sogou/workflow/blob/master/src/kernel/msgqueue.c
线程池新代码
https://github.com/sogou/workflow/blob/master/src/kernel/thrdpool.h
https://github.com/sogou/workflow/blob/master/src/kernel/thrdpool.c

**Comment by wangwenqiangGitHub** [comment]
想问下有没消息队列性能测试的例子

**Comment by Barenboim** [comment]
您可以自己试一下哈。比一般的无锁队例肯定慢，但在我们的测试环境，每秒读200多万个消息没什么问题。消息队列模式可以放心使用。
