### ISSUE TITLE
Kafka客户端的异常行为

### ISSUE THREAD

**Issue by song-git** [sogou/workflow#956]
最近在用Kafka客户端时，发现异常如下：
1、客户端采用每200毫秒创建一个Kafka客户端任务（topic=xxx&api=fetch）。
2、程序运行一段时间后， 就收不到消息了 - 异常情形
3、使用GDB进行调试，断点到创建任务的线程后， 又能收到消息了 - 正常情形。

通过抓包对比，发现异常情形时发出的request中offset都是-1，正常情形下，offset是正常值。

![image](https://user-images.githubusercontent.com/5081806/175019108-b6b54c37-88af-49e3-aaa3-cc14f89e7022.png)

**Comment by song-git** [comment]
在这个过程中客户端程序没有重启，经历了 正常 - 异常 - GDB - 正常 的过程。

**Comment by Barenboim** [comment]
你好，请问是最新master的代码吗？

**Comment by Barenboim** [comment]
offset -1好像是从最新开始取的意思，然后可能没有新数据，就block了。
但比较奇怪的是，为什么之前offset会是-1，以及为什么GDB就好了。我看看内部是不是需要等待哪个任务结束去更新offset。
你先确认一下是不是最新的代码。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/master/docs/tutorial-13-kafka_cli.md#fetch任务
你是用手动模式还是消费者组模式？手动模式每次set_offset可以正常吗？

**Comment by song-git** [comment]
> 

其实是有新消息的，使用Kafka的脚本中 console consumer 可以成功接收到消息的。

**Comment by song-git** [comment]
> 你好，请问是最新master的代码吗？

使用的是最近的release版本，0.10.1

**Comment by Barenboim** [comment]
> > 你好，请问是最新master的代码吗？
> 
> 使用的是最近的release版本，0.10.1

最新kafka message修改了一些bug，确实可能和这种复现率很低的问题相关。麻烦用master帮我们试试看。

**Comment by song-git** [comment]
我在一个任务中设置了多个topic，和这个会有关系吗？

**Comment by Barenboim** [comment]
应该没有关系。本来就支持多次add_toppar。
多个toppar的话，会是一个并行任务，然后每个任务回来分别更新offset。但更新offset的地方没有加member的锁，我确实有点怀疑这块有没有问题。也麻烦你帮我们跟一下。kafka client的作者目前只有周末可能有时间查问题。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/43ced86665d4b6bf5945f7abf98e6b21d3fb7c5c/src/client/WFKafkaClient.cc#L550
这是多个toppar并行之后，处理每个offset的回调。单个toppar的fetch任务，回调是空的。所有的处理都在并行任务结束的回调里。如果一直只有一个kafka任务，确实没有抢锁的问题。

**Comment by song-git** [comment]
[kafka.zip](https://github.com/sogou/workflow/files/8966500/kafka.zip)
我尝试了一下把topic分别创建不同的任务，客户端一直报错。文件是抓包的数据。
但是这种方式也成功过。

**Comment by song-git** [comment]
![image](https://user-images.githubusercontent.com/5081806/175282986-849f061d-3c9e-486b-9361-ab8238965cb4.png)
主要代码是这样的。

**Comment by Barenboim** [comment]
> ![image](https://user-images.githubusercontent.com/5081806/175282986-849f061d-3c9e-486b-9361-ab8238965cb4.png)
> 主要代码是这样的。

你好。这个kafka callback提示什么错误呢？

**Comment by song-git** [comment]
> > ![image](https://user-images.githubusercontent.com/5081806/175282986-849f061d-3c9e-486b-9361-ab8238965cb4.png)
> > 主要代码是这样的。
> 
> 你好。这个kafka callback提示什么错误呢？

![image](https://user-images.githubusercontent.com/5081806/175290978-0a46e775-69d1-4cc7-84cb-77cf0195629a.png)
这是错误日志

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/blob/6701df39201330a43fdca84b44dbfe30adaa1c7b/src/client/WFKafkaClient.cc#L838
这个地方，是不是没有add_toppar() ？

**Comment by Barenboim** [comment]
原理上，第一个任务发现还没有meta信息，会在fetch前面插入一个Kafka_FindCoordinator：
https://github.com/sogou/workflow/blob/6701df39201330a43fdca84b44dbfe30adaa1c7b/src/client/WFKafkaClient.cc#L729
其它同时发送的fetch任务，看到有人已经发起来Kafka_FindCoordinator，则会通过一个counter等待第一个人获得meta信息。
现在看起来，Kafka_FindCoordinator这个好像就没有成功……因为后面的fetch任务，toppar_list_map是空的。这个按理是由Kafka_FindCoordinator任务填写的。
你串行执行是好的？

**Comment by song-git** [comment]
[kafka2.zip](https://github.com/sogou/workflow/files/8967163/kafka2.zip)
这是改成把5个任务串行后的效果。
![image](https://user-images.githubusercontent.com/5081806/175299848-c655d071-bec4-4593-97ec-dd399cf9a8bf.png)

**Comment by Barenboim** [comment]
串行都不行？那不是相当于什么都干不了？你是不是哪里用错了。
比如需不需要task->add_toppar()？
另外，我改了一个client的小问题：https://github.com/sogou/workflow/pull/958 你在我这个分支上拉代码，然后再试一下并发的log吧。

**Comment by song-git** [comment]
> 串行都不行？那不是相当于什么都干不了？你是不是哪里用错了。 比如需不需要task->add_toppar()？ 另外，我改了一个client的小问题：#958 你在我这个分支上拉代码，然后再试一下并发的，发一下log吧。

现在退回了最开始，一个任务里面放多个topic，暂时能正常。
相当于又退回了最开始的时候了。

**Comment by Barenboim** [comment]
> 一次创建5个任务的时候，有一个任务也能成功。其余4个失败。

串行还是并行？

**Comment by Barenboim** [comment]
感觉没有道理啊。这是很常规的用法。

**Comment by Barenboim** [comment]
是不是200ms的fetch timeout引起什么超时了？

**Comment by song-git** [comment]
我有点怀疑是不是和服务端也有关系，第二次串行的时候抓包里(上面的kafka2.zip)，看到是服务端首先响应了一个异常。
![image](https://user-images.githubusercontent.com/5081806/175440600-2127c3d5-826c-4937-a8c4-420b77ed76a7.png)
或者是客户端有异常情形没处理到？

**Comment by Barenboim** [comment]
没有进程在调用leavegroup吧？
我们没有复现你的问题，这个代码看起来很常规，如果有问题我们的kafka client根本不work😂我们下午看看你的抓包。
BTW，从workflow工厂（client也是一种工厂）产生的任务，不用判断nullptr的。一切错误都从callback里拿。

**Comment by Barenboim** [comment]
又发现我们的一个问题，我们的req里没有设置correlation id。我们改一下。

**Comment by Barenboim** [comment]
新的这个修改，可以修复pcap的问题了。你用master分支再试一下。如果还不行，再抓个包给我们。

**Comment by song-git** [comment]
好的，我切换master再试一下， 先关闭这个问题。下次再重新开问题吧。
