### ISSUE TITLE
如何等待可能超时的异步框架的事件完成

### ISSUE THREAD

**Issue by BDZNH** [sogou/workflow#962]
我看了 [Server如何等待一个非本框架的异步事件完成？-- Good Question](https://github.com/sogou/workflow/issues/328)
counter 的用法我大概理解了，我的场景是这样的。
接收到一次请求之后，在 process 唤起另外一个框架（进程），将命名计数器的名字传给这个进程，由这个进程完成工作之后打开counter，但是这个进程可能需要 5s 甚至更长才能有结果，（也有可能这个进程中途异常退出了，这样的话 counter 就不会被这个进程打开了）。

上面的描述是否清晰足够清晰呢

简单来说，我参考了[Server如何等待一个非本框架的异步事件完成？-- Good Question](https://github.com/sogou/workflow/issues/328)用 counter 堵住 series的话 ，需要等到 counter 打开才能继续处理，有可能这个 counter 不会被打开，所以我有没有什么比较合适的办法再等待一定时间之后再自行打开 counter 呢？目前我是考虑开一个线程去等待一定时间之后去打开counter的。

周末多有叨扰😶

**Comment by BDZNH** [comment]
可能我还是没能描述清楚。以 [Server如何等待一个非本框架的异步事件完成？-- Good Question](https://github.com/sogou/workflow/issues/328) 里面的例子来说
```cpp
void process(WFHttpTask *server_task, const char *root)
{
    // get abs_path
    ...
    // create a named counter with name 'abs_path'
    WFCounterTask *counter = WFTaskFactory::create_counter_task(abs_path, 1, [abs_path](WFCounterTask *counter) {
         SeriesWork *series = series_of(counter);
         WFHttpTask *server_task = (WFHttpTask *)series->get_context();
        /* OK, everthing is ready. create your pread task and push back to series ....*/
    });
    // Notify python program to create file with abs_path.
    // 我在这里唤起另外一个进程，由另外一个进程在完成工作之后，访问 "process_file_ready" 来 count_by_name 
    // 这样的逻辑在正常情况下是 OK 的，但是这个进程可能由于其他的原因（闪退之类的），并没有 访问 "process_file_ready" 来 count_by_name 
    // 这样的话，这条连接是不是就停在一直等待 count_by_name 了，所以我想弄一个超时来自行 count_by_name
    ...
    // save server_task in series' context.
    series_of(server_task)->set_context(server_task);
    // add counter to series.
    series_of(server_task)->push_back(counter);
}
// 增加一个处理完成通知的服务。request uri是全路径。
void process_file_ready(WFHttpTask *server_task)
{
    WFTaskFactory::count_by_name(server_task->get_req()->get_request_uri());
}

int main(int argc, char *argv[])
{
    ...
    WFHttpServer file_server(std::bind(process, root));
    WFHttpServer msg_server(process_file_ready);
    file_server.start(8000);
    msg_server.start(8001);
    getchar();
    file_server.stop();
    msg_server.stop();
    return 0;
}
```

我的问题点在于， counter 和 timer 如何结合使用呢，直接向 series 连续 push_back 一个 counter 和一个 timer 吗

**Comment by Barenboim** [comment]
Timer直接start就可以了，不和counter串连。timer是一种几乎开销为0的任务，可以随便起的。

**Comment by BDZNH** [comment]
感谢解答👍

**Comment by Barenboim** [comment]
Timer直接start啊。timer的开销几乎为0，随便挂timer。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月25日(周六) 上午10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] 如何等待可能超时的异步框架的事件完成 (Issue #962)




 
可能我还是没能描述清楚。以 Server如何等待一个非本框架的异步事件完成？-- Good Question 里面的例子来说
 void process(WFHttpTask *server_task, const char *root) {     // get abs_path     ...     // create a named counter with name 'abs_path'     WFCounterTask *counter = WFTaskFactory::create_counter_task(abs_path, 1, [abs_path](WFCounterTask *counter) {          SeriesWork *series = series_of(counter);          WFHttpTask *server_task = (WFHttpTask *)series-&gt;get_context();         /* OK, everthing is ready. create your pread task and push back to series ....*/     });     // Notify python program to create file with abs_path.     // 我在这里唤起另外一个进程，由另外一个进程在完成工作之后，访问 "process_file_ready" 来 count_by_name      // 这样的逻辑在正常情况下是 OK 的，但是这个进程可能由于其他的原因（闪退之类的），并没有 访问 "process_file_ready" 来 count_by_name      // 这样的话，这条连接是不是就停在一直等待 count_by_name 了，所以我想弄一个超时来自行 count_by_name     ...     // save server_task in series' context.     series_of(server_task)-&gt;set_context(server_task);     // add counter to series.     series_of(server_task)-&gt;push_back(counter); } // 增加一个处理完成通知的服务。request uri是全路径。 void process_file_ready(WFHttpTask *server_task) {     WFTaskFactory::count_by_name(server_task-&gt;get_req()-&gt;get_request_uri()); } int main(int argc, char *argv[]) {     ...     WFHttpServer file_server(std::bind(process, root));     WFHttpServer msg_server(process_file_ready);     file_server.start(8000);     msg_server.start(8001);     getchar();     file_server.stop();     msg_server.stop();     return 0; }
 
我的问题点在于， counter 和 timer 如何结合使用呢，直接向 series 连续 push_back 一个 counter 和一个 timer 吗
