### ISSUE TITLE
mac m1 平台编译问题

### ISSUE THREAD

**Issue by iambyd** [sogou/workflow#966]
m1架构下，cmake build 一直不通过，symbol(s) not found for architecture arm64

**Comment by Barenboim** [comment]
M1架构我们测过的啊。你直接make报什么错？

**Comment by iambyd** [comment]
我这边还是一个c++小白，网上说你们这个项目非常值得学习，我就拉取了下来，学习下，这个就是拿你们那个示例make后报的错，我不知道，是不是CMakeLists.txt没配置好还是如何，感谢大佬指导！
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/11927058/175795230-98a19127-3048-432d-ba3b-601e89a81d0c.png">

**Comment by holmes1412** [comment]
看起来是你自己写的CMake？有可能是没有成功链接workflow的lib。
主页的示例在tutorial/tutorial-00-helloworld.cc就有，你可以在项目主目录：
~~~sh
make && make tutorial
~~~
先用tutorial里的CMake帮你编出来～

**Comment by iambyd** [comment]
> 

这个可以编译的，不过我总不能一直在tutorial下吧，得引用到外部项目咯

**Comment by iambyd** [comment]
> 看起来是你自己写的CMake？有可能是没有成功链接workflow的lib。 主页的示例在tutorial/tutorial-00-helloworld.cc就有，你可以在项目主目录：
> 
> ```shell
> make && make tutorial
> ```
> 
> 先用tutorial里的CMake帮你编出来～

是的，我自己重新写的cmake，外部引用下，您上面提的示例没啥问题的。

**Comment by Barenboim** [comment]
> > 看起来是你自己写的CMake？有可能是没有成功链接workflow的lib。 主页的示例在tutorial/tutorial-00-helloworld.cc就有，你可以在项目主目录：
> > ```shell
> > make && make tutorial
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 先用tutorial里的CMake帮你编出来～
> 
> 是的，我自己重新写的cmake，外部引用下，您上面提的示例没啥问题的。

你就模仿tutorial的CMake写就好了😂可能你以前用的库都是header only，我们是需要链接一下的。

**Comment by holmes1412** [comment]
可以检查一下有没有target_link_libraries之类的哈
