### ISSUE TITLE
提前释放计算队列的问题

### ISSUE THREAD

**Issue by wenjiedong-30** [sogou/workflow#975]
请问一下，假如我创建了数十个WFThreadTask的任务，他们拥有相同的队列名字，此时上层应用需要退出而我不想继续等待任务全部完成，可以强制队列释放并不执行剩余任务吗？

**Comment by wenjiedong-30** [comment]
> 请问一下，假如我创建了数十个WFThreadTask的任务，他们拥有相同的队列名字，此时上层应用需要退出而我不想继续等待任务全部完成，可以强制队列释放并不执行剩余任务吗？

另外可以补充下 请问可以获取到剩余任务的长度吗？

**Comment by Barenboim** [comment]
> 请问一下，假如我创建了数十个WFThreadTask的任务，他们拥有相同的队列名字，此时上层应用需要退出而我不想继续等待任务全部完成，可以强制队列释放并不执行剩余任务吗？

如果是程序结束，直接退出就可以了，任务会直接callback并且get_state()==WFT_STATE_ABORTED。
如果不想程序退出，并且保证没有别人在使用计算任务，可以重新初始化计算执行器，同样没有执行的任务会callback：
~~~cpp
void reinit_compute_executor()
{
    Executor *executor = WFGlobal::get_compute_executor();
    executor.deinit();
    int compute_threads = WFGlobal::get_global_settings()->compute_threads;
    if (compute_threads <= 0)
          compute_threads = sysconf(_SC_NPROCESSORS_ONLN);
    compute_executor_.init(compute_threads);
};
~~~
这个方法比较hack一点，会影响到全局中的计算任务。你也以不使用全局的计算执行器，自己创建Executor和ExecQueue，然后用这个函数来创建Thread Task:
~~~cpp
template <class INPUT, class OUTPUT>
WFThreadTaskFatory
{
    static T *create_thread_task(ExecQueue *queue, Executor *executor,
                                 std::function<void (INPUT *, OUTPUT *)> routine,
                                 std::function<void (T *)> callback);
};
~~~
然后executor和queue都你自己管理。同样，要让没有执行的任务结束，直接调用executor.deinit()函数就可以了。
