### ISSUE TITLE
如何有效解决超时任务非法访问series_context资源的

### ISSUE THREAD

**Issue by MaybeShewill-CV** [sogou/workflow#977]
在timed_go任务中使用了series_context来存储一些数据供其他任务使用，根据timed_go任务描述如果这个任务超时那么会直接返回任务的callback但timed_go任务本身并没有真正中断，那么当series已经结束，series_context已经被释放时，若timed_go任务还在继续执行那么会发生任务非法访问series_context的问题。
![example](https://user-images.githubusercontent.com/15725187/177710214-6b87bf0f-3f6f-4348-bc68-c0b364750ede.png)

目前采取的解决方案时使用一个counter，counter的callback里删除series_ctx资源，在timed_go任务结束的时候唤醒counter。
![1](https://user-images.githubusercontent.com/15725187/177709665-09aa5a56-95db-4535-8054-64aa0b395687.png)

想咨询下像这种情况有什么好的解决方案。还有个小问题就是如果timed_go_task始终执行不完，最终线程池的compute_handler被耗尽的话框架怎么解决这个问题呢?

**Comment by Barenboim** [comment]
这个问题，我们是比较推荐在计算任务的算法里，剥离掉和series有关的逻辑。
对于一般的go_task，在计算过程中访问series是安全的。但如果是带超时的go task，有可能你的计算函数都还没结束，就超时callback了。所以，最好还是不要这么干。如果需要访问series context，可以直接记下context指针，然后里面再用引用计数的方式来解决最终释放的问题。你用counter的方法，好像基本上就是这个原理了。
最后关于你的go task函数始终不退出的问题，我们框架层应该是没有什么好办法的。需要用户自己来保证算法会结束。

**Comment by MaybeShewill-CV** [comment]
@Barenboim 确实在客户端并发比较大的情况下计算函数还没结束就超时了。如果我需要在go task的callback里填写计算结果到resp，这样是不是也只能使用series_context来记录计算结果了，还有什么更合理的方式嘛：）

**Comment by MaybeShewill-CV** [comment]
@Barenboim 可能是我的问题没有描述清楚，就是我需要在callback里拿到go task的计算结果填入到resp里，这种情况下需要series context去保存计算结果.

**Comment by MaybeShewill-CV** [comment]
@Barenboim 好的 我明天试试看把结果存在task->user_data

**Comment by Barenboim** [comment]
已经更新了文档：
https://github.com/sogou/workflow/blob/master/docs/about-go-task.md#带执行时间限制的go-task
确实用户能帮我们发现很多小细节！
