### ISSUE TITLE
请问只想使用http协议解析的话，怎么弄呢？

### ISSUE THREAD

**Issue by zhai-php** [sogou/workflow#983]
std::string http_protocol_content = "这里是http的文本内容";
解析这个http_protocol_content，得到一个request的对象，可以获取所有的数据。

**Comment by Barenboim** [comment]
如果只想利用http解析，可以使用http_parser模块：
https://github.com/sogou/workflow/blob/master/src/protocol/http_parser.h
https://github.com/sogou/workflow/blob/master/src/protocol/http_parser.c
创建一个parser，不停调用http_parser_append_message()直到返回1代表消息完整。

**Comment by Barenboim** [comment]
@zhai-php
