### ISSUE TITLE
一直提示找不到openssl

### ISSUE THREAD

**Issue by NeilStone123** [sogou/workflow#99]
在执行cmake的时候出现如下错误
-- Detecting CXX compile features - done
CMAKE_C_FLAGS_DEBUG is -g
CMAKE_C_FLAGS_RELEASE is -O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG
CMAKE_C_FLAGS_MINSIZEREL is -Os -DNDEBUG
CMAKE_CXX_FLAGS_DEBUG is -g
CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG
CMAKE_CXX_FLAGS_MINSIZEREL is -Os -DNDEBUG
CMake Error at /usr/local/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.8/Modules/FindOpenSSL.cmake:387 (find_package_handle_standard_args)
  src/CMakeLists.txt:3 (find_package)
但是机器上已经安装了openssl，按照cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1d -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl@1.1/1.1.1d/lib来指定执行也还是报这个错误，请教一下

**Comment by sonullx** [comment]
如果是MacOS X上使用homebrew安装的openssl，建议尝试加选项`-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl`。

**Comment by NeilStone123** [comment]
多谢，方法可行
