### ISSUE TITLE
win分支使用问题

### ISSUE THREAD

**Issue by mwyhaha** [sogou/workflow#991]
win分支timertask中创建了一个networktask，发起请求，server端收到后回复，client端的无反应呢，简单调试，感觉像是IOCP没有响应。

**Comment by Barenboim** [comment]
你好。应该不会有这么明显的错误的。能不能把代码贴一下我们看看？

**Comment by mwyhaha** [comment]
有试了一下，在timertask中创建了一个同步的srpc任务，客户端请求后，在Communicator::handle_incoming_idle函数中的“delete ctx”这里卡住了。异步请求任务没这个现象。

**Comment by mwyhaha** [comment]
补充一下场景：客户端和服务端都是Windows系统。客户端线程卡死。

**Comment by Barenboim** [comment]
"delete ctx"这里好像删除了一个没有析构函数的对象，不太应该会卡死。
如果异步没有问题，同步卡死，可能和srpc的同步机制有关系。
您能不能贴一下代码，我们让群友也帮忙复现一下？我们Windows的开发比较忙，不太有时间查问题。

**Comment by mwyhaha** [comment]
应该是我自己的代码问题。后面再继续测试调试一下。
