### ISSUE TITLE
关于实现一个while(1)中断任务

### ISSUE THREAD

**Issue by DDGRCF** [sogou/workflow#995]
您好！我这有这样一个需求，就是客户端发送命令，来使服务器go-task任务跳出某个循环。
我目前就是有两个想法：1.发送一个信号，2.开个condition。
您那边有好的解决方案吗

**Comment by Barenboim** [comment]
你好。
go-task任务占用的是计算线程池，默认数量等于计算机的总核心数。如果你不想这个线程池被占满，最好不要在go task进行等待。
你想通知计算任务结束的方法很多，比如通过一个变量，循环几次之后check是下是不是false之类的。最好不要用信号。用condition的话，会把线程卡住。你确认没问题就好。
另外计算任务的线程池大小，也是可以调的。

**Comment by DDGRCF** [comment]
> 你好。 go-task任务占用的是计算线程池，默认数量等于计算机的总核心数。如果你不想这个线程池被占满，最好不要在go task进行等待。 你想通知计算任务结束的方法很多，比如通过一个变量，循环几次之后check是下是不是false之类的。最好不要用信号。用condition的话，会把线程卡住。你确认没问题就好。 另外计算任务的线程池大小，也是可以调的。
好哒

**Comment by DDGRCF** [comment]
> 你好。 go-task任务占用的是计算线程池，默认数量等于计算机的总核心数。如果你不想这个线程池被占满，最好不要在go task进行等待。 你想通知计算任务结束的方法很多，比如通过一个变量，循环几次之后check是下是不是false之类的。最好不要用信号。用condition的话，会把线程卡住。你确认没问题就好。 另外计算任务的线程池大小，也是可以调的。

好哒
