### ISSUE TITLE
tutorial中的kafka_cli打印消息内容是否有功能支持？

### ISSUE THREAD

**Issue by henryw2019** [sogou/workflow#998]
使用kafka_cli作为生产者跟kafka对接，报：error msg：Bad message
Failed. Press Ctrl-C to exit.

想尝试打印与kafka服务端的消息内容或者通讯报文，是否有相应的函数支持？

**Comment by Barenboim** [comment]
你好。请问你用的是master的最新代码吗？一个请求也没有成功过？
如果想dump消息，可以在KafkaResponse::append这里，把buf的内容下来，代码位置：
https://github.com/sogou/workflow/blob/fb88ad55cdb9eecafa402f27c0e7ff4c0efd2dfa/src/protocol/KafkaMessage.cc#L3820
如果你对kakfa协议也比较熟，可以帮我们看看哪一个包的parse出问题了。

**Comment by Barenboim** [comment]
可以同时看一下request包的序列化函数，这样可以把request和response对应起来。request的序列化在：
https://github.com/sogou/workflow/blob/fb88ad55cdb9eecafa402f27c0e7ff4c0efd2dfa/src/protocol/KafkaMessage.cc#L2086

**Comment by henryw2019** [comment]
我使用的是0.10.2版本代码。
我尝试修改了您指出的代码位置，在KaflaMessasge::apend 增加了一些printf 试图把buf的内容打印出来，但是buf输出结果为空，但size是302 和 29。

**Comment by Barenboim** [comment]
> 我使用的是0.10.2版本代码。 我尝试修改了您指出的代码位置，在KaflaMessasge::apend 增加了一些printf 试图把buf的内容打印出来，但是buf输出结果为空，但size是302 和 29。

Kafka是二进制协议哈，记得不能当作字符串来处理。另外，建议用最新master上的代码。

**Comment by henryw2019** [comment]
我还是没打印出来…… 
有没有类似http的get_parsed_body方式可以获取呢？

**Comment by Barenboim** [comment]
你怎么打印的？不可以printf("%s", buf)的，因为不是字符串。
可以用fwrite(buf, *size, 1, stderr)这么打。但这样打出来也是二进制。所以需要先处理一下。

**Comment by henryw2019** [comment]
二进制打印出来似乎还是看不出问题在哪，Bad message 应该是返回的内容解析失败了吧。您说的处理是不是需要经过这个解析：
  int ret = kafka_parser_append_message(buf, size, this->parser);

**Comment by Barenboim** [comment]
嗯嗯，您能不能跟一下，看看什么地方认为数据格式不对？

**Comment by henryw2019** [comment]
跟了一下解析的代码，没看出什么问题。
为什么会有多次调用KafkaResponse::append，是因为内部有多次交互吗？
感觉问题好像出在认证上：
在tutorial中加上config.set_sasl_mech("SCRAM-SHA-256")后，使用错误的密码执行，在buf输出中会出现invalid credential字样   但回调函数报错信息依然是Bad message。
如果我使用正确的密码执行，buf中就没什么可以阅读的信息了(部分内容看起来像是base64编码)，回调函数报error msg: Unknown.

**Comment by Barenboim** [comment]
> 跟了一下解析的代码，没看出什么问题。 为什么会有多次调用KafkaResponse::append，是因为内部有多次交互吗？ 感觉问题好像出在认证上： 在tutorial中加上config.set_sasl_mech("SCRAM-SHA-256")后，使用错误的密码执行，在buf输出中会出现invalid credential字样 但回调函数报错信息依然是Bad message。 如果我使用正确的密码执行，buf中就没什么可以阅读的信息了(部分内容看起来像是base64编码)，回调函数报error msg: Unknown.

对，内部要至少要先交互一次，获得broker的版本。如果你能发送第二个包，说明起码第一次交互正确了。你能不能抓个包给我们分析一下？

**Comment by henryw2019** [comment]
要抓tcpdump包吗？还是打印buf？
公司服务器上的东西没办法拿出来，是否可以告诉我kafka task里面都调用了哪些函数，我现在还没找到Unknown、Bad message的错误码是哪个地方赋值的。
kafka_cli有没有选项可以编译后通过gdb调试？

**Comment by Barenboim** [comment]
有的。你make KAFKA=y DEBUG=y就可以得到无优化的代码，然后就可以gdb进去了。EBADMSG肯定是在KafkaMessage.cc里置的，errno=EBADMSG的地方。Unknown这个不太对，我跟一下。

**Comment by Barenboim** [comment]
就是顺着append接口一路跟下去。看看什么地方置了EBADMSG

**Comment by henryw2019** [comment]
密码错误时的Bad message位置找到了，是在parse_saslauthenticate里面设置的，这个地方是不是应该展示error_message内容更清晰。
密码正确返回Unknown的位置还是没找到，好像起来很多线程，不知道该追哪个

**Comment by Barenboim** [comment]
感谢感谢！具体行数麻烦发一下。

**Comment by Barenboim** [comment]
> 密码错误时的Bad message位置找到了，是在parse_saslauthenticate里面设置的，这个地方是不是应该展示error_message内容更清晰。
> 密码正确返回Unknown的位置还是没找到，好像起来很多线程，不知道该追哪个

我看了一下这个实现，这里是为了方便，在认证失败的时候直接关连接，就把这个错误当作消息解析错误了。我觉得这个逻辑可以优化一下。目前这种情况下，你应该可以通过task->get_kafka_error()得到一个KAFKA_SASL_AUTHENTICATION_FAILED。但是get_state()现在得到sys error是不对的，应该是task error。

**Comment by henryw2019** [comment]
请问callback是在 KafkaResponse::append 返回后调用的吗？
我这里KafkaResponse::append返回ret是1，但是callback里面task->get_error()拿到的值却是-1 。我在KafkaMessage.cc 里面每个return前都加了打印输出

**Comment by Barenboim** [comment]
get_error()值是-1是什么？没有这种错误啊。你能不能把callback里get_state()，get_error()和task->get_kafka_error()都打一下？

**Comment by Barenboim** [comment]
如果append返回了1，能不能看看什么地方把state给改成WFT_STATE_SYS_ERROR了？

**Comment by henryw2019** [comment]
这几个值打印出来是这样的：state=67 ，error=5010，kafka_error=-1，

在KafkaTaskImpl.cc的process_sasl_authenticate()里面返回的。

**Comment by Barenboim** [comment]
> 这几个值打印出来是这样的：state=67 ，error=5010，kafka_error=-1，
> 
> 在KafkaTaskImpl.cc的process_sasl_authenticate()里面返回的。

state=67是WFT_STATE_TASK_ERROR, error=5010是WFT_ERR_KAFKA_SASL_DISALLOWED，这个的意思是broker端不支持SASL认证。你的kafka broker端版本是什么？

**Comment by henryw2019** [comment]
版本是2.4.0。
我用java版本的客户端是可以的，对比了一下参数设置，
java有security.protocol的参数，值是SASL_PLAINTEXT，另外还有参数sasl.mechanism、key.serializer、value.serializer、sasl.jaas.config、username、password；
wokflow的参数我只设置了username、password、sasl_mechanism 其他都是框架默认参数。
会不会和这些参数设置有关系？

**Comment by wzl12356** [comment]
#1008 
试一下这个

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1009
我又小改了一下。
@henryw2019 应该是sasl认证的一个bug。
密码错误时的EBADMSG，我之后改一下。

**Comment by henryw2019** [comment]
成功了，感谢大佬。为什么加了2行赋值就解决了，可以指导一下吗？
还有个小问题是命令参数用c 执行消费时，有2次回调，第1次回调正常处理了，第2次回调会报error msg:Connection reset by peer.
如果命令行参数用 c d  ，可以读出全部消息，不会有这个报错。

**Comment by Barenboim** [comment]
> 成功了，感谢大佬。为什么加了2行赋值就解决了，可以指导一下吗？
> 还有个小问题是命令参数用c 执行消费时，有2次回调，第1次回调正常处理了，第2次回调会报error msg:Connection reset by peer.
> 如果命令行参数用 c d ，可以读出全部消息，不会有这个报错。

之后有一版代码重构时，把sasl认证给搞出问题了……因为我们把默认kafka错误改成了-1，全部正确之后再把错误清除。结果sasl这里记了清😓谢谢帮我们发现问题。
第二个问题我们一会看一下。

**Comment by henryw2019** [comment]
谢谢解答，密码错误报BADMSG 和 消费报错 的问题 让我试着改改代码吧，争取周末提PR

**Comment by Barenboim** [comment]
> 谢谢解答，密码错误报BADMSG 和 消费报错 的问题 让我试着改改代码吧，争取周末提PR

第一个问题可能不好改哈，涉及到workflow里的很多机制。
消费报错我们看一下是什么原因。

**Comment by Barenboim** [comment]
消费报错的问题我们没有复现出来。如果第二个callback出错，这是一个commit操作用来提交offset的。只有消费者组模式下才会有这个操作。这个挺常用的，我们之前也没有遇到这个问题。麻烦你看看是不是和sasl有关系，或者帮我们跟一下是什么原因，多谢。

**Comment by henryw2019** [comment]
应该是我用法的问题，我只有1个topic可以访问，把no_group 赋值true 就没问题了。

**Comment by Barenboim** [comment]
> 应该是我用法的问题，我只有1个topic可以访问，把no_group 赋值true 就没问题了。

但我们返回reset也好像不太对

**Comment by henryw2019** [comment]
调试看到reset的错误是在Communicator.cc 704行 res->state 为PR_ST_FINISHED 中赋值的。

**Comment by Barenboim** [comment]
那就是对方直接把连接关了，没有给我们回复完整的kakfa response。这个行为对吗？

**Comment by henryw2019** [comment]
要怎么判断是不是对方直接关闭了连接呢，kafka交换信息的过程我不太了解。

**Comment by Barenboim** [comment]
这个就是对方把连接关了。你可以看看关连接之前，有没有发送数据。也就是说，这次请求里，我们的KafkaResponse::append有没有被调用过。

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/1013
麻烦试一下我这个改动。如果sasl密码错误，得到的错误应该是：
get_state() = WFT_STATE_TASK_ERROR(67)
get_error() = WFT_ERR_KAFKA_SASL_DISALLOWED(5010)
get_kafka_error() = KAFKA_SASL_AUTHENTICATION_FAILED(58)

**Comment by henryw2019** [comment]
> https://github.com/sogou/workflow/pull/1013
> 麻烦试一下我这个改动。如果sasl密码错误，得到的错误应该是：
> get_state() = WFT_STATE_TASK_ERROR(67)
> get_error() = WFT_ERR_KAFKA_SASL_DISALLOWED(5010)
> get_kafka_error() = KAFKA_SASL_AUTHENTICATION_FAILED(58)

好像不对，现在密码错误报错还是Badmessage,
state=2，error=74,kafka_error=0。

**Comment by Barenboim** [comment]
> > #1013
> > 麻烦试一下我这个改动。如果sasl密码错误，得到的错误应该是：
> > get_state() = WFT_STATE_TASK_ERROR(67)
> > get_error() = WFT_ERR_KAFKA_SASL_DISALLOWED(5010)
> > get_kafka_error() = KAFKA_SASL_AUTHENTICATION_FAILED(58)
> 
> 好像不对，现在密码错误报错还是Badmessage, state=2，error=74,kafka_error=0。

😓能不能看看现在是哪一行给errno赋值EBADMSG？

**Comment by Barenboim** [comment]
可以再拉一下新代码。
https://github.com/barenboim/workflow-dev

**Comment by henryw2019** [comment]
在parse_i16里面，val赋值为58，然后parse_saslauthenticate error 为58，满足了不等于0条件，errno 赋值为EBADMSG

**Comment by henryw2019** [comment]
我是用sogou的master分支跑的，你的dev分支我试了下也是badmsg，应该是同一个位置报错的。

**Comment by Barenboim** [comment]
我的dev上最新代码，还是EBADMSG吗？这个有点搞不懂。我再看一下。

**Comment by Barenboim** [comment]
@henryw2019 
又改了代码。这次真的应该对了……

**Comment by Barenboim** [comment]
@wzl12356 
所有的error默认值我重新改为0了。默认UNKNOWN的话，太多坑了。麻烦看看最新的修改有没有什么问题。

**Comment by henryw2019** [comment]
你的dev分支还是badmsg，这次是KafkaMessage.cc 2817行赋值的，if条件中的size值=4

**Comment by Barenboim** [comment]
明白了。。。多谢多谢，我接着改。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 上午9:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sogou/workflow] tutorial中的kafka_cli打印消息内容是否有功能支持？ (Issue #998)




 
你的dev分支还是badmsg，这次是KafkaMessage.cc 2817行赋值的，if条件中的size值=4

**Comment by henryw2019** [comment]
我有个想法，为什么不在报Badmsg的时候，把kafka返回的信息填进去呢，返回的消息中有明确的认证失败描述。

**Comment by Barenboim** [comment]
这次，应该真的好了！麻烦再试一下。

**Comment by Barenboim** [comment]
之前少改了parse_response里的代码了。parse_saslauthenticate的返回之后，parse_response还会再处理一下。

**Comment by Barenboim** [comment]
> 我有个想法，为什么不在报Badmsg的时候，把kafka返回的信息填进去呢，返回的消息中有明确的认证失败描述。

用户拿到的WFKafkaTask并不是一个网络任务，实现的网络任务是KafkaTaskImpl里的__WFKafkaTask，这个在callback之后一般就释放了，我们只保留了需要的信息。目前并没有保存原始的回复。

**Comment by henryw2019** [comment]
不好意思，今天忘了看这个了，明天我验证一下。

**Comment by Barenboim** [comment]
> 不好意思，今天忘了看这个了，明天我验证一下。

真是麻烦啦。我已经合并了主分支。

**Comment by henryw2019** [comment]
> https://github.com/sogou/workflow/pull/1013
> 麻烦试一下我这个改动。如果sasl密码错误，得到的错误应该是：
> get_state() = WFT_STATE_TASK_ERROR(67)
> get_error() = WFT_ERR_KAFKA_SASL_DISALLOWED(5010)
> get_kafka_error() = KAFKA_SASL_AUTHENTICATION_FAILED(58)

现在符合这个预期了，不过错误码的翻译好像漏了几个，我补上了，请看看对不对。
https://github.com/sogou/workflow/pull/1016

**Comment by Barenboim** [comment]
谢谢帮我们联调这么久😂
错误码这个是遗漏了。你的修改有一点拼写错误，麻烦再改一下。

**Comment by henryw2019** [comment]
已经更正了，感谢这么耐心帮忙解决问题！

**Comment by Barenboim** [comment]
> 已经更正了，感谢这么耐心帮忙解决问题！

嗯嗯。也帮我们star一下项目哈。

**Comment by henryw2019** [comment]
好的，心满意足的关闭议题😊
